### ISSUE TITLE
Why can't I map key combinations?

### ISSUE THREAD

**Issue by jtmarmon** [mawww/kakoune#1002]
It seems that map only supports single key mappings (with the exception of user mode which allows you to map `,` plus another single key).

1. Is there a documented reason for this? I tried pretty extensively to find it myself but can't seem to
2. Obviously there are some combined keys in kakoune already, for example `ge` goes to the end of the file. Can I remap these somehow?
3. Is there a way to change the key for user mode? I'd like to use space instead of comma

**Comment by Delapouite** [comment]
Hi.
For point 3, I also prefer `<space>` over `,`  : 
```
map global normal <space> ,
```

**Comment by jtmarmon** [comment]
thanks @Delapouite ! derped a bit on that one.

**Comment by mawww** [comment]
Single keys mapping is mostly a question of simplicity, supporting multi keys mapping means we need to disambiguate between 'a' being mapped, and 'ab'. How do we do that ? with a timer ?

You can however implement your own multi key mappings with the `on-key` command, for example:
`map global normal i ':on-key %{ %sh{ case "$kak_key" in; 'a') echo 'exec blah'; ' ;; <a-b>') ... } }'`

I guess you'd usually extract the on-key into a command, and just map the first key to `:my-command<ret>`

**Comment by jtmarmon** [comment]
thanks @mawww - what about remapping or adding new options to existing multi-keys? for example, could I extend `g` to have `gq` which does blah?

**Comment by hxegon** [comment]
@mawww I was actually thinking about this yesterday. What if we had something like:
'a' and 'ab' type mappings aren't allowed in the same config.
with 'ab' mapped, 'a' acts like a nested leader.
This can be extended recursively: you can't have 'ab' and 'abc' mappings together, etc.

**Comment by mawww** [comment]
@jtmarmon yes you can, `g` is the `goto` mode you see in the `map` completion candidates.

@hxegon Yep, we can do all sorts of things like that, but I think it adds a lot of complexity for a pretty small gain, and we have a way to implement this if needed with the `on-key` command (although I agree its less convenient).

**Comment by hxegon** [comment]
@mawww Agreed. I'm going to take a whack at an extracted version of that ```on-key``` command, would that go in rc/base?

**Comment by mawww** [comment]
Not sure what you mean by 'an extracted version of that `on-key` command'

**Comment by hxegon** [comment]
@mawww I mean, abstract away  [your example](https://github.com/mawww/kakoune/issues/1002#issuecomment-267368025) into a wrapper command that defines (what looks like) multi character leader mappings. If a better way to do this gets implemented, it could be internally changed without breaking peoples config. Something like:

```command-name [['ab', ":echo 'some command'<ret>"], ['ac', ":echo 'some other command'<ret>"]]```
I feel like this would be a nice convenience/stability gain. let me know what you think.

**Comment by jtmarmon** [comment]
@mawww ahh got it. I didn't know `goto` was a mode at all - i'm starting to understand how this editor works now :) so basically any key combination that is allowed is a mode, and goto is one of them. if i wanted to i could probably design my own. makes sense. thank you!

@Delapouite given you've remapped space, how do you clear multiple selections?

**Comment by mawww** [comment]
@jtmarmon for the purpose of key mapping, it is. On the implementation side, the mode is more like a 'pending key' mode, that gets used in various places (g, v, text objects, "<reg>...).

@hxegon Could be an interesting experiment to see how clean/ugly it gets to have a generic multi key mapping system, but I doubt I'll merge that as a bundled script, I dont want to encourage arbitrary multi key mappings, we already have almost no free keys left for built-in commands.

I think the issue itself is not relevant anymore, closing, but feel free to continue the discussion.

**Comment by jtmarmon** [comment]
thanks @mawww - I tried to figure this out by going through the source but I had a really hard time finding it. do you know how I can map another key to clear multiple selections?

**Comment by mawww** [comment]
Exactly the same way you'd map any key. In kakoune mapping are not recursive, the target keys are kakoune commands, not whatever these keys are mapped to.

```
map global normal <space> ,
map global normal , <space>
```

Swaps the `,` and `<space>` keys.

**Comment by jtmarmon** [comment]
> In kakoune mapping are not recursive
ahh i didn't know that. got it! thanks

**Comment by BjornMelgaard** [comment]
Had swapped : and ;

```
map global normal ':' ';'
map global normal ';' ':'
```
```
// xkb
replace key <AC10> { [ colon, semicolon ],
                   [ Cyrillic_zhe, Cyrillic_ZHE ] };
```

**Comment by andrewla** [comment]
This is an old issue that came up during a search for mapping multiple keys, so leaving a note here that custom user modes can be defined as of #1803 and that is a better solution.  You can either use the default `user` mode or introduce a new mode with `declare-user-mode` to effectively get combinations.
