### ISSUE TITLE
Ubuntu/Debian package

### ISSUE THREAD

**Issue by hxegon** [mawww/kakoune#1004]
I've never created a .deb package before, but I'll take the initiative. Some questions:

- PPA or nah?
- If I create a kakoune PPA, is there a mechanism for me to add @mawww as an owner to prevent any trust shenanigans?
- I just use Ubuntu, so the most straight forward path (for me) is to just make/test against Ubuntu. Is anyone interested in testing/building/using on Debian?
- Binary or Source package?
- Should we make release branches/tags, or is building against master fine?
- Is some kind of automated build/release system a good idea, and if so, how?
- I'm in experienced with c++ and compiling/building/make in general. What questions am I missing?

I'll research these myself, but I'd like some feedback. If anyone with more experience wants to step up in my place, speak up. I just want this to get done, I don't care how.

**Comment by doppioandante** [comment]
I've never took care of packaging anything but as I use Ubuntu right now I might look into it.
What is the alternative to a PPA? I think that would be a good thing btw.
For the moment kakoune doesn't have versions to tag onto, so building against master would make sense.
There's nothing particular about C++ and building kakoune, don't know about an automated building system though.

**Comment by hxegon** [comment]
@doppioandante 
> What is the alternative to a PPA?

It's described in depth [here](http://packaging.ubuntu.com/html/packaging-new-software.html#submitting-for-inclusion), but basically submitting it to debian and having it included in the default repos..

**Comment by doppioandante** [comment]
I'll look into it.
Packaging kakoune for debian would be really nice but it requires a changelog and, I would say, at least a principle of versioning that just aren't there yet.

A PPA that tracks master would be the easier solution for now.

**Comment by hxegon** [comment]
seems that we are [going to need some kind of version number](https://help.launchpad.net/Packaging/PPA/BuildingASourcePackage#Versioning) either way. Do you have any plans for versioning @mawww? I think making up a version number would be fine for now, we could probably do sequential build numbers or something, but I wanted to check.

**Comment by rschulman** [comment]
FYI that kakoune will not build on Debian Jessie because gcc < 5.0. Getting builds working for that may be more difficult than just throwing together a buildbot.

**Comment by lenormf** [comment]
As I've written the `make_deb` script, I'll share my experience and say that it's a lot of work to create a good package. There's a lot of things to do to make it debian-compliant in the first place, but what's more important is *maintaining* it. The changelog needs to be written (which might not be provided by the vendor, so the maintainer of the package might have to look into the changes made and summarize them himself), patches need to be applied and made available between releases, the repo itself needs to be available 24/7…

I don't think this is something a new user should venture into, as they usually come and go, and we don't want some infrastructure to be made available for some time and then dumped onto somebody else's plate.

**Comment by hxegon** [comment]
Hmm, I was hoping that a making a changelog could be automated based on commit messages, but looking through the history I don't think that'd be the case.

 After reading your comment, I think that trying to make a package _right now_ would be misguided. However, I'd like to break the blocking problems out into actionable issues (where appropriate) and come back to it when those are done.

The two I'm thinking of are the changelog and versioning.

Could you elaborate on patches and repo availability, @lenormf? By repo I'm thinking either github or the PPA, which from reading the Ubuntu docs sounds like its hosted for you. Also, do you think just making an Ubuntu package be significantly simpler than Debian + Ubuntu?

**Comment by lenormf** [comment]
The launchpad would solve the hosting issue, I was under the impression that you needed to keep it on one of your systems.

As for the patches, they are fixes that make the program work on the system between two versions, they have to be made available in the package, and since they won't necessarily be merged upstream, you have to keep track of which is relevant for the current version. Some might work for some ubuntu versions, some not… it's a lot of work.

And since you need versions to be able to either do a changelog or keep track of patches, there's not much we can do here aside from having a rolling release-type PPA. Feel free to do it if you want to, but on the day we have the means to get a real package rolling, someone will need to step up to take care of it.

As for the debian/ubuntu difference, I think the packages are farily similar, you can automate that I reckon.

**Comment by mawww** [comment]
Seems there is http://packages.ubuntu.com/zesty/kakoune now. Anyway this is for the community to take care of, I dont use either Debian or Ubuntu,
