### ISSUE TITLE
Debugging filetype bug

### ISSUE THREAD

**Issue by tmiller** [mawww/kakoune#1008]
I have a ruby file located at `spec/spec_helper.rb` and it is being loaded up using the cpp filetype. However, in other projects `spec/spec_helper.rb` loads up as a ruby file. How can I debug this so that I can try to figure out what the issue might be?

**Comment by tmiller** [comment]
I should note I've looked in `rc/core/c-family.kak` and I didn't see anything that stood out.

**Comment by mawww** [comment]
Hello, it could be that `file` (the shell command) says that file is a cpp file. I merged a PR yesterday or the day before that make `file` only a fallback, so extensions should always take precedence now, did you use a 1-2 days old version ?

**Comment by tmiller** [comment]
Yes I did, I'll update and see if it works.

**Comment by tmiller** [comment]
Yup that is exactly what was happening, thank you for all the hard work you've put into this!

**Comment by mawww** [comment]
No problem, thanks for giving it a try.
