### ISSUE TITLE
Get Clippy to say the command being edited does not exist

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1021]

**Comment by doppioandante** [comment]
The command being edited? Also why clippy?

**Comment by lenormf** [comment]
This would make the autoinfo pop up everytime text is entered in the menu, it would be too much information I think. There's an alternative involving a delay after the last key has been hit, but I don't like it either has afaik anything involving timing has been avoided to this day.

**Comment by alexherbo2** [comment]
I was considering after entering the full command by validating a space or Clippy preventing executing command that does not exist.

**Comment by leemachin** [comment]
I like how fish shell handles this: if a command exists it'll be highlighted one colour (e.g. blue), and if it doesn't it will be highlighted differently (e.g. red).  

`ValidCommand` and `InvalidCommand` faces could be an alternative to provide subtle hints about the command, and it means you don't have to deal with timing or knowing when to show a popup.

**Comment by lenormf** [comment]
I'm not too fond of highlighting the command itself, but maybe adding a symbol in the prompt would be a good alternative. Either way I don't think this feature is needed at all, as validating a non-existing command will display an error message anyway.

**Comment by mawww** [comment]
We already have a precedent with regex prompts changing colors when the regex is invalid, (the prompt text changes color, not the user entered one), I'd be open to do that for commands as well. Would that be ok ?

**Comment by lenormf** [comment]
I got so used to that feature that I completely forgot about it! I think it'd be nice to used that principle again.

**Comment by alexherbo2** [comment]
It’s ok for me.
