### ISSUE TITLE
<a-h> not working in :exec

### ISSUE THREAD

**Issue by speckins** [mawww/kakoune#1022]
I'm trying to map Ctrl-U in insert mode using exactly the suggestion in [this comment](https://github.com/mawww/kakoune/issues/334#issuecomment-124083019):

    map global insert <c-u> '<a-;>:exec -draft <a-h>d<ret>'

But I'm getting the following error after entering the `map` command:

    1:1: 'exec' unknown option '-draftd'

If I leave off the `-draft` option, the mapping is accepted, but when I attempt to execute it, this error occurs:

    execd : no such command

(Edit:  forgot to mention, I'm using a0c787e on OS X 10.9.5)

**Comment by lenormf** [comment]
You need an extra level of escaping because there is a promp context spawned in your list of keys:

```
map global insert <c-u> '<a-;>:exec<space>-draft<space><lt>a-h>d<ret>'
```

You could also move the `exec` string into a hidden function to make things clearer, and only use `eval<space>myfunc<ret>` in the binding itself.

**Comment by speckins** [comment]
@lenormf Thanks.

FYI I implemented this the second way with a slightly more complicated function since the behavior of `<a-h>d` wasn't consistent.

```
def -hidden delete-to-beginning-of-line %{ %sh{
    if [ $kak_cursor_column -gt 1 ]; then
        prevcol=$(($kak_cursor_column - 1))
        printf %s "
            select $kak_cursor_line.1,$kak_cursor_line.$prevcol
            exec -draft d
        "
    fi
} }

map global insert <c-u> '<a-;>:eval delete-to-beginning-of-line<ret>'
```
