### ISSUE TITLE
3 bugs about "addhl column"

### ISSUE THREAD

**Issue by iology** [mawww/kakoune#1023]
Just notes for now:

pic. "addhl column 20 RedColumn", ..., the green blocks are selections of spaces and tabs

<img width="423" alt="2016-12-18" src="https://cloud.githubusercontent.com/assets/23622455/21290516/c5ddeeae-c4f8-11e6-8f63-502b55a2be7e.png">

- [ ] Multi-byte characters are splitted apart.
- [ ] Combining characters are separated from the main character.
- [ ] Incorrect alignment, even after view shift: (pic. only line#32 is not empty)

    > <img width="402" alt="2016-12-18" src="https://cloud.githubusercontent.com/assets/23622455/21290585/07c31982-c4fb-11e6-8f90-994cb44134c1.png">

Related code:

* https://github.com/mawww/kakoune/blob/bc8b30c988cf8b471cac0b2bc5cea9fd8594c846/src/highlighters.cc#L580-L585

**Comment by lenormf** [comment]
I don't understand what's wrong in the first case, and I don't understand what you're saying in the other two. Could you elaborate a bit more please?

**Comment by iology** [comment]
The config: (`addhl show_whitespaces` can slightly change the layout, add it if you want to see one more bug)

```
face RedColumn default,red
hook global WinCreate .* %{
addhl number_lines -hlcursor -separator ' '
addhl column 20 RedColumn
addhl column 40 RedColumn
colorscheme zenburn
```

The three sentences:

```
## multibyte character <ĝ> (<U+011D>)
#La belaj virinoj loĝas en tiu urbo.

## combining character <g>+ˆ
#La belaj virinoj loĝas en tiu urbo.

## combining character g+<ˆ>  (g + <U+0302>)
#La belaj birdoj loĝas en tiu urbo.
```

ĝ (U+011D) in sentence#1 and ˆ (U+0302) in sentence#3 are both multi-byte character, and got truncated by the highlight. "g" in sentence#2 is just one byte, so it is lucky.

In addition to solve the multi-byte issue, we also need to take care for all combining characters like ˆ (U+0302).

<img width="410" alt="2016-12-18" src="https://cloud.githubusercontent.com/assets/23622455/21295603/a31788da-c593-11e6-9708-0ee3a36e451e.png">


---

Then the rest alignment issues. Settings:

```
set global tabstop 4
```

<img width="490" alt="2016-12-18" src="https://cloud.githubusercontent.com/assets/23622455/21295616/f7be2e8e-c593-11e6-9030-d484ad92334b.png">

New bug added here: the zero-width character U+200B

Text:

```
# zero-width character <U+200B>
Here:<​>

A<space><tab>Z-*<eol>
A 	Z----------------------------------
A 	Z---------------------------------
A 	Z--------------
A 	Z-------------
A 	Z
----4--------------19-22---------------39-42
The numbers are columns of the red bar after A Z.
Some spaces and tabs are selected to show their widths.
```

<img width="361" alt="2016-12-19_02_42_26-hd" src="https://cloud.githubusercontent.com/assets/23622455/21295653/d85bb68c-c594-11e6-85a9-322798de7a29.png">

Text:

```
-------------------20---25-------------40------------------
```

My cursor is at column 25, and I use lock-view to right shift five columns.
