### ISSUE TITLE
[Suggestion] '.' matching newline character

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1024]
Hi,

With the defaults of `boost::regex`,  `.` matches the newline character. More often that not, I'm only interested in covering the current line when I type `.*`, so I have to use `[^\n]*` to work around it which is a bit annoying.

Would it be possible to expose the boost setting `match_not_dot_newline`, maybe as an option for interactive use?

**Comment by mawww** [comment]
I think something like `(?-s)` allows you to force . to only match non newlines in the regex

**Comment by occivink** [comment]
You're right, it does. I can't find any reference to this in the boost documentation, are there other flags that can change the behaviour mid-regex?

**Comment by lenormf** [comment]
`smix` are the Perl modifiers mentioned in the boostregex documentation.

**Comment by occivink** [comment]
Thanks, I've found them documented [here](http://perldoc.perl.org/perlre.html). `m` and `i` should be the most useful for interactive use, and they can be toggled on/off mid-regex with `(?_)` and `(?-_)`.

I guess for my issue I can just make mappings that prepend this prefix to all regex entered, although that's not super elegant.

**Comment by lenormf** [comment]
Using `[^\n]*` is an acceptable way too, there are a few scattered in the builtin scripts.

**Comment by occivink** [comment]
Sure, but I think it's a bit too annoying to type that instead of just `.`. Like I said, most of the time I just want to match on the same line.
