### ISSUE TITLE
Add vim-surround-like feature

### ISSUE THREAD

**Issue by opsound** [mawww/kakoune#1025]
Since selections are so integral to Kakoune, it would be awesome to have a feature for surrounding the selection(s), and changing the surrounding characters.

See https://github.com/tpope/vim-surround

**Comment by lenormf** [comment]
This is pretty easy to do by default already, using `i` and `a`. If you want to make things easier, you could implement a script that declares some bindings to quickly surround a selection, but I don't think this would be a good fit for upstream.

**Comment by spinningarrow** [comment]
@lenormf could you elaborate how to change the surrounding characters using i and a? I'm pretty new to Kakoune and I had the same question as OP.

**Comment by lenormf** [comment]
Assuming you want to surround the word under the cursor with a shell variable expansion:

```
<a-i>w
i ${ <esc>
a } <esc>
```

`i` inserts things at the beginning of the selection, `a` extend the selection by its end.

**Comment by spinningarrow** [comment]
I see. Is there also a way to do the second thing i.e. changing the surrounding characters? For example if I have

    "something quoted"

I'd like to change the double quotes to single quotes to make it

    'something quoted'

As an aside, I'm fine with this being in a separate script but it's such a useful and well-used feature that I would second it being considered to be in core. This would make it different from vim though, where it is an external plugin.

**Comment by spinningarrow** [comment]
I think I figured out the answer to my question above. I can do this by selecting around the quotes (`alt+a "`) then splitting to multiple cursors on the quote (`s"`) and then changing them to single quotes (`c'`).

**Comment by lenormf** [comment]
`r'` would keep you in normal mode, but `c'` works as well.

**Comment by opsound** [comment]
Thanks for the tips, all. I need more practice using the kakoune way. It would be great for more experienced users to share some of these usage patterns in the wiki :)

**Comment by ianthehenry** [comment]
In case future generations find this, you can add this to your `kakrc` to get behavior very similar to `vim-surround`:

```
def surround %!on-key %@exec %sh&
  case "$kak_key" in
  "<lt>") key="<" ;;
  "<gt>") key=">" ;;
  "<space>") key=" " ;;
  "<tab>") key="\t" ;;
  \<*\>) echo ":echo<space>no<ret>"; exit 1 ;;
  *) key="$kak_key" ;;
  esac

  open="$key"
  close="$key"
  case "$key" in
  ")") open="(" ;;
  "]") open="[" ;;
  "}") open="{" ;;
  ">") open="<" ;;
  "(") open="( "; close=" )" ;;
  "[") open="[ "; close=" ]" ;;
  "{") open="{ "; close=" }" ;;
  "<") open="< "; close=" >" ;;
  esac

  epilogue=${close//?/H}

  open=${open/</<lt>}
  close=${close/>/<gt>}

  open=${open/ /<space>}
  close=${close/ /<space>}
  
  echo "i$open<esc>a$close<esc>$epilogue"
&@!

map global user s ":surround<ret>"
```

(Improvements welcome.)

**Comment by Delapouite** [comment]
Great, thanks ianthehenry. I have added your snippet to the wiki : https://github.com/mawww/kakoune/wiki/Surround-selections . This way it can be tweak easily by anyone.

**Comment by alexherbo2** [comment]
I added this feature in #1295.
