### ISSUE TITLE
Make it easier to write portable scripts

### ISSUE THREAD

**Issue by leemachin** [mawww/kakoune#1027]
I quite like how simple kakoune's config layer is, but I feel like it is far too easy to make mistakes with it because it assumes POSIX compliance means a consistent environment. Examples:

- `/bin/sh` on a Mac is just an alias for `bash`. If you write kak scripts on a Mac you won't realise this unless you have the presence of mind to install an `sh` specific linter.

- `readlink` on a Mac is not `readlink` on Linux. You need to install `gnu-coreutils` for that, which means you need `greadlink`. This makes (what should be) simple tasks like expanding the string `'~'` into a canonical directory (and making it reusable) an absolute nightmare (and can make your scripts less readable), unless you want to provide other shell scripts or binaries along with your `kak` script. This is the same with other commands that have differing GNU and BSD implementations, or even if the commands are just outdated.

For personal scripts this isn't an issue at all, because you know what's installed on your system. IFor everything else, you can't assume that something exists and works as you expect if you want to share the script and make it portable. The alternatives are adding extra scripts, binaries, or building services that return the commands over RPC. 

I don't want to suggest diverging from the unix way, but choosing to reduce the available guaranteed toolset to what was defined by a very old standard  can make it hard to write scripts that others can reliably use without bundling dependencies. I'm not convinced that embedding a scripting language is the best idea (embed one language, watch the issues flood in for embedding others), but there has to be a way to make this more intuitive and modern without compromising the editor's goal.

I would love to help provide a solution that can abstract some of this away, even if that just means defining a best practice (it's okay to provide part of your functionality as a compiled binary, for example), documenting anything I may have misunderstood, or embellishing the POSIX shell context with a nice set of convenience functions.

**Comment by occivink** [comment]
I can't speak for everybody, but I wouldn't really have a problem using a script that has more dependencies than just POSIX as long as those are clearly defined and reasonable. 
I think the POSIX guidelines are mostly here for the bundled scripts to make sure that they work on _most_ platforms, anything outside is free to go wild.

**Comment by lenormf** [comment]
>I would love to help provide a solution that can abstract some of this away, even if that just means defining a best practice (it's okay to provide part of your functionality as a compiled binary, for example), documenting anything I may have misunderstood, or embellishing the POSIX shell context with a nice set of convenience functions.

Not sure I understood this part.


Right now the only way to provide shell contexts with default functions would be to `source` a file before executing the script in the scope. This is a side effect, it would take away some execution time from scripts that don't need the functions, and it's in the end not absolutely necessary as there's enough tools available on every UNIX system to reimplement the features we need.

Adding dependencies is the last resort, and if we haven't had to do it until now I don't think we'll ever have to; having the project work out of the box with a minimal amount of dependency is fundamental, and considering that `boost` will be thrown out of the window as soon as the regex API can be implemented with `std::regex` (which is a core functionality of the project), I don't see the project requiring additional tools just to run kak scripts.

This is a difficult subject, there are several opinions about how to tackle it, but I think how it's being handled right now is the best (albeit not the easiest) way.

**Comment by leemachin** [comment]
I understand the point, and I think the current system is perfect when you're just writing scripts for your own benefit: if it works on your machine then it's good enough.

> This is a difficult subject, there are several opinions about how to tackle it, but I think how it's being handled right now is the best (albeit not the easiest) way.

True. This is why I want to focus on how it could be made easier (which is the problem), as opposed to picking one solution and treating it as the only way to fix the problem. Thinking about user friendliness on the configuration side is worthwhile.

**Comment by mawww** [comment]
I agree trying to keep compatibility with POSIX is often painful, I was cursing at the lack of word boundary assertions in POSIX awk just yesterday. And in practice we dont even strictly follow POSIX as you saw with the use of readlink in some scripts.

I dont see following the standard as a goal itself, but as a way to ensure we keep wide compatibility with various operating systems and user lands. That is why I think `readlink` is acceptable: there is no sane POSIX alternatives, and it is available on almost all platforms. As a quick guideline for shell commands, I'd say if `busybox` supports it, its probably reasonable to use it.

I wont be adding any other commands/binaries that `kak` to Kakoune without an extremely strong case for them, as I think keeping Kakoune as self contained as possible (provided a POSIX system to run it on) is very important. And as much as I often curse our limitation to POSIX shell when we could have all nice features from bash or zsh, not depending on these is still worth it.

What we lack is still a proper integration with `checkbashism` or some other shell checker to easily detect when we add dependencies to non POSIX features.

I am not sure there is a lot to add here, as I think most expressed opinions are very similar: respecting POSIX is painful, but we dont have any satisfying alternatives to keep portablity without depending on other projects. Closing for now, but dont hesitate to create new issues for any proposals on how to improve the current situation.
