### ISSUE TITLE
<Backspace> key not working

### ISSUE THREAD

**Issue by roxma** [mawww/kakoune#1030]
Hi, I have a centos 7 on windows 7 host, and I'm using Xshell, ssh to the machine.

Somehow I can't get delete character with the `<backspace>` key. It's working well on vim and neovim.

And I've checked the README.md, which says:

> `<backspace>` or `<a-x>`: erase character before cursor

I cant't figure out how to get it to work, so I post an issue here, hoping to get some help.

**Comment by mawww** [comment]
Sorry, I missed that issue, you can try to `set global debug keys` to have every keys hit written to the `*debug*` buffer. That should show what the backspace key is interpretted as by Kakoune.

**Comment by roxma** [comment]
```
Client 'unnamed0' got key '<c-h>' 
```

**Comment by roxma** [comment]
I tried
```
map global insert <c-h> <Backspace>
```
now its working in insert mode.
I want this to work in all modes, do I need to add mappings for each of them?

**Comment by roxma** [comment]
![image](https://cloud.githubusercontent.com/assets/4538941/21755995/570cb978-d656-11e6-9588-fe556e2fd2e4.png)

I just noticed that this settings on xshell work for me too.

However, I would like this to work out of the box. Can `<c-h>` mapped to `<backspace>` by default in `kak`?
