### ISSUE TITLE
Adding C++ unit tests

### ISSUE THREAD

**Issue by leira** [mawww/kakoune#1033]
I don't feel quite easy submitting code without unit tests. Kakoune has really nice kak tests, but no C++ tests. I think C++ unit tests are necessary too, to have some lower level tests might not necessary testable with kak tests. What about we start to C++ unit tests, I can help adding test cases as as a way to understand the code, when I read it.

I'm really interested in https://github.com/philsquared/Catch/, though never used. Catch looks really nice, I want to give it a try. We can put test code under /test/cpp. What do you guys think?

**Comment by lenormf** [comment]
There is testing to some extend, using `assert`s. Other than that, having tests requires somebody to write and maintain them, it's a lot of work for a one-person project.

**Comment by occivink** [comment]
There are already some C++ unit tests embedded in the codebase, [see here](https://github.com/mawww/kakoune/search?utf8=%E2%9C%93&q=UnitTest&type=Code)

**Comment by leira** [comment]
This is some really nicely done trick! Simple and elegant, @mawww never cease to amaze me~

**Comment by lenormf** [comment]
So, can we close this now?

**Comment by leira** [comment]
Yeah, sure~

**Comment by leira** [comment]
Thanks~

**Comment by occivink** [comment]
>This is some really nicely done trick!

It's definitely an interesting take. The immediate advantage that I can see is proximity of test with code (out of sight, out of mind after all) and the ability to test functions from anonymous namespaces.

I wonder if the tests get optimized out when optimization are turned on?

**Comment by lenormf** [comment]
Check out [D](http://dlang.org/), this type of testing is builtin in the language.
