### ISSUE TITLE
Plugins or something?

### ISSUE THREAD

**Issue by spinningarrow** [mawww/kakoune#1034]
I would like to incorporate [parinfer][]-like functionality in Kakoune[1]. I couldn't find any documentation on how that might work. Is extension via plugins or scripting supported in any way or on the roadmap? 

[1]: A list of plugins for other text editors can be found here: https://shaunlebron.github.io/parinfer/#editor-plugins

[parinfer]: https://shaunlebron.github.io/parinfer/

**Comment by doppioandante** [comment]
The extension mechanism is not via plug-ins, see https://github.com/mawww/kakoune/blob/master/doc/manpages/faq.asciidoc#why-arent-there-other-scopes-similar-to-sh-eg-python- (maybe you can find more discussion in the issue tracker but I'm not sure).

If I understand [this](https://github.com/shaunlebron/parinfer/tree/master/lib) correctly, pareinfer is ported ad hoc for every editor. We would need it as an external standalone component, with various amounts of glue to make it work with kakoune.

**Comment by spinningarrow** [comment]
> We would need it as an external standalone component, with various amounts of glue to make it work with kakoune

I think something like this might already be possible. I believe vim-parinfer was using the Node version of parinfer via some kind of JSON api before it switched to using parinfer written in vimscript. What kind of glue is supported? Can I run a `curl` command to a local server and get its output into the kakoune buffer? (sorry still reading through the readme, but sounds like this might be possible)

**Comment by doppioandante** [comment]
For 'glue' I mean the kakoune 'scripting language' (which is no different from the commands that you can use while editing). In particular, the %sh{ } block is used to spawn an external shell: usually the output of the command processed into kakoune commands that will then be executed via :exec or :eval

**Comment by spinningarrow** [comment]
Ooh `exec` looks pretty interesting. I'll read up some more. Thanks!

**Comment by spinningarrow** [comment]
Question: can something like `exec` be executed in insert mode?

**Comment by doppioandante** [comment]
Look at hooks, there are a couple of them for character insertion and key "insertion", that's probably what you are looking for.

**Comment by mawww** [comment]
Implementing parinfer using an external tool should definitely be doable with the current infrastructure. Closing this.
