### ISSUE TITLE
Cursor to other end of selection?

### ISSUE THREAD

**Issue by nyarly** [mawww/kakoune#1036]
Experimenting with movement, I found (and can't find docs for...) that HJKL expand the selection, which is great. However, I can't figure out an equivalent to Vim's visual-mode "o" to jump the cursor to the other end of the selection. Is there such a key?

**Comment by lenormf** [comment]
`<a-;>`.

**Comment by mawww** [comment]
and `<a-:>` will force the selection to have the cursor at the end.
