### ISSUE TITLE
daemon mode dies if socket already exists

### ISSUE THREAD

**Issue by akkartik** [mawww/kakoune#1041]
```bash
$ kak -s main -d
Kakoune forked to background, for session 'main'
send SIGTERM to process 21327 for closing the session
uncaught exception (N7Kakoune13runtime_errorE):
```

Since it was working before my recent `git pull`, I did a binary search and isolated the cause to 831887cd3a5b2b71dbb3ef1b25fd0220ea7230d7 which creates sockets in the user-specific `$TMPDIR`. After this patch things work again:

```
 static StringView tmpdir()
 {
-    StringView tmpdir = getenv("TMPDIR");
-    if (not tmpdir.empty())
-        return tmpdir.back() == '/' ? tmpdir.substr(0_byte, tmpdir.length()-1)
-                                    : tmpdir;
     return "/tmp";
 }
```

**Comment by akkartik** [comment]
Ah, running under gdb shows the full error:

```
uncaught exception (N7Kakoune13runtime_errorE):
unable to bind listen socket '/var/folders/00/0w4cr000h01000cxqpysvccm003hjl/T/kakoune/akkartik/main': Address already in use
```

But kak wasn't already running. Looks like the socket is sometimes not being deleted. Let me close this for now and reopen it when I have more details.

**Comment by lenormf** [comment]
Actually please leave this open, so we concentrate all the details (and things you've tried) in the same thread. Only close the issue when it's been fixed.

**Comment by akkartik** [comment]
Yes, I meant to reopen the same issue when I ran into it again. I closed it because of the possibility it was some error on my part. Several times today I tried to create a daemon when one for the same session was already running.

Reopening, but please feel free to close.

**Comment by lenormf** [comment]
I understand, although *any* crash from the client is a serious issue we need to fix, even if it's "your fault" :)

**Comment by akkartik** [comment]
Ah, that makes sense. What was I thinking. I've given this issue a better name.

**Comment by lenormf** [comment]
Cheers.

**Comment by mawww** [comment]
This is not a crash per se, but I guess "uncaught exception" is not very nice. Generally I think the current behaviour is sound: if the session socket file exists, refuse to start. We have `kak -l` to list sessions, and `kak -clear` to remove dead ones.

**Comment by akkartik** [comment]
Makes sense. Perhaps the issue here is that the error message at the top of this bug isn't very useful. The message that is visible in gdb is not visible at the regular commandline.

**Comment by mawww** [comment]
Yeah, the message should be better now, we were missing a trailing `\n` in it, so the actual error might have gotten hidden by the shell prompt appearing on top of it.
