### ISSUE TITLE
`<a-i><space>` doesn't work

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1043]
Hi,

We've recently added the possibility to use `<a-i>` along with any punctuation sign, and I find myself more and more wishing that `<a-i><space>` would select everything between two whitespaces (which seems not to be working at the moment).

Thanks.

**Comment by kballard** [comment]
I believe `<a-i>W` already does what you want. That said, it's probably a good idea to support `<a-i><space>` anyway as it seems reasonable to expect that to work.

**Comment by mawww** [comment]
`<a-i><space>` works already, but does not do that, it selects a whitespace object, which is a set of consecutive whitespaces.

**Comment by lenormf** [comment]
In my mind `<a-i>` means "select everything between…", hence the confusion. Not sure how to spin it, closing for now.
