### ISSUE TITLE
`kak -ro foo` should warn if I try to edit the buffer

### ISSUE THREAD

**Issue by kballard** [mawww/kakoune#1050]
If I try to edit a readonly buffer (e.g. one opened with `kak -ro foo`), Kakoune should warn me that I'm editing a readonly file. Right now there's not even an indication that the file is in readonly mode, and it's only when I try to `:wq` that it informs me that the buffer is readonly.

**Comment by leemachin** [comment]
That would be helpful :) something you can do in a kak script right now is to do something like this:

```
hook global BufOpen .* %sh{
  if [ $kak_opt_readonly = true ]; then
    echo "face Default default,red"
  fi
}
```

Not tested at all (and the colour is a bit extreme :D). But the idea is that you change the background colour of the editor ever so slightly for readonly buffers, so you can at least tell the difference in the absence of an explicit warning.

**Comment by kballard** [comment]
I bet you could create something using the `InsertBegin` hook and a custom buffer option (to avoid duplicate warnings). Vim also pauses input for a couple of seconds to drive home the point, but I'm guessing Kakoune has no way to do that.

Similarly, read-only status should show up in the mode line somehow.

**Comment by kballard** [comment]
Ok, here's that hook. Still haven't looked into the mode line though.

```kak
decl -hidden bool _readonly_warning_shown false

hook global InsertBegin .* %{ %sh{
    if [ $kak_opt_readonly = true -a $kak_opt__readonly_warning_shown = false ]; then
        echo 'set buffer _readonly_warning_shown true'
        echo 'echo -markup {Error}Warning: This buffer is readonly.'
    fi
} }
```

**Comment by lenormf** [comment]
This was the default behaviour, but it cluttered the code massively so we decided to remove it. Most likely won't be put back in again.

**Comment by kballard** [comment]
Cluttered the code massively? What about that hook I showed? That's not much clutter, and the only detritus it leaves is a single hidden option. I still need to look into if I can get an indicator in the mode line though (and really, it should have one by default).

**Comment by lenormf** [comment]
I was talking about [the code itself](https://github.com/mawww/kakoune/pull/731), users can implement a hook themselves if they really want a notification. No need to have one by default.

**Comment by kballard** [comment]
Kakoune ships with a set of rc files already, it's easy to add this hook into those files.

**Comment by lenormf** [comment]
There's no need for this behaviour to be a default, if there was then it would have been implemented already.

**Comment by alexherbo2** [comment]
We could indicate the buffer is read-only in the status line at least.

**Comment by kballard** [comment]
@lenormf I'm getting rather tired of your arguments along the line of "if this behavior was good, it would have been done already". Why do you keep using that line? Kakoune is not a perfect editor (nothing is), and there's always room for improvement.

**Comment by lenormf** [comment]
I don't know @alexherbo2, we thought about all this already, and what came out is that the readonly more is an alternative behaviour always instated by the user voluntarily, so they would know when it's enabled or not, and it's not a behaviour used enough to warrant a space in the status line.

As for warnings that warn the user that a buffer is being edited in readonly mode, it would make us add a couple lines to each primitive that edits the buffer (and maybe more, as you can edit the buffer using `exec`/`eval` etc). So in the end it's better if the user adds a hooks and displays a widget in their modeline, if they really need it.

**Comment by itsgreggreg** [comment]
If you open a file you have permissions to read but not write then the condition of read-only was not instated by the user voluntarily or at least knowingly. It would be nice to know that before you start typing.

ie: `kak /etc/hosts`

**Comment by lenormf** [comment]
This issue concerns the readonly mode so it doesn't really apply here, but since detecting filesystem constraints is more complicated than checking read/write permissions -as several mechanisms can prevent a user to overwrite a file-, it would require some additional thinking in its own issue I think. Right now an error message is only displayed when the editor hasn't managed to save a file, but it would probably be nice to have a warning message when the buffer is opened (again, not trivial to detect reliably when it's the case though).
