### ISSUE TITLE
Question: What does 'exec <a-K>\\A[\\h\\v\\n]*\\z<ret>' in commenting.kak do?

### ISSUE THREAD

**Issue by leira** [mawww/kakoune#1052]
I'm trying to understand commenting.kak, I have a question regarding this line:
```
            ## The selection is empty
            exec <a-K>\\A[\\h\\v\\n]*\\z<ret>
```

What does this line trying to do? I understand it matching a selection of nothing, or a selection of white spaces. But what is this line trying to achieve, and how does it achieve that?

**Comment by lenormf** [comment]
It unselects selections that only contain horizontal/vertical/newline characters, `<a-K>` is mostly used after an `<a-s>` or a select that created multiple selections.

**Comment by occivink** [comment]
Most of the stuff in there is regex syntax, the various escape sequnce are documented [here](http://www.boost.org/doc/libs/1_62_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html). It looks like `[\h\v\n]*` could be simplified by `\s*` though.

**Comment by leira** [comment]
Thanks for the explanation.
