### ISSUE TITLE
Evaluate dynregex while searching

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1054]
It would be nice if one could see all search results while writing the search regexp when having a highlighter such as:

    addhl dynregex '%reg{/}' 0:+u 1:+b

I presume that one problem is that the `/` register is not set until the search is actually finished.

**Comment by lenormf** [comment]
One alternative would be to have a hook on register updates, as suggested in #859.

**Comment by mawww** [comment]
Yeah, that should be doable.

**Comment by mawww** [comment]
not the hook on register update, we dont update registers during increment search, we should do that, and restore the registers on cancel.

**Comment by mawww** [comment]
But it might interact badly with multiple clients.

**Comment by danr** [comment]
Thank you for your gift! Works wonders!
