### ISSUE TITLE
no RuntimeError hook on kak .

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1056]
Hi.
ranger.kak provides the following hook:

```
hook global RuntimeError "\d+:\d+: '\w+' (.*): is a directory" %{ %sh{
    directory=$(expr $kak_hook_param : "[0-9]*:[0-9]*: '[a-z]*' \\(.*\\): is a directory")
   echo ranger $directory
}}
```
which is quite handy with the `edit .` command for example.

But typing `kak .` in the shell to open a fresh instance of kakoune does not trigger this RuntimeError hook, it only logs a similar startup_error to the debug buffer.

It would be great if the shell `kak .` command could also trigger the same RuntimeError as kakoune `edit .` command. This way, ranger would be automatically be opened at startup.

**Comment by lenormf** [comment]
Would it be better if `ranger` was spawned on `BufCreate` when the buffer points to a directory, and simply drop the error message when it's supposed to be displayed? Relying on the error format is not very robust.
