### ISSUE TITLE
RGB colors don't work properly in Terminal.app

### ISSUE THREAD

**Issue by kballard** [mawww/kakoune#1057]
Terminal.app on macOS 10.12 supports the xterm 256 colorspace, but doesn't support changing colors to specific RGB values. I suspect Kakoune is trying to rely on the latter functionality, because loading a colorscheme that uses RGB values produces awful results. For example, the base16 colorscheme looks like:

`kak -n -e 'source "%val{runtime}/colors/base16.kak"'`
![screen shot 2016-12-21 at 2 19 25 pm](https://cloud.githubusercontent.com/assets/714/21408195/7d61e03a-c788-11e6-9c41-7e6ae98868d0.png)

More generally, I can produce bad effects just by using rgb colors. Using just a single rgb color for a background doesn't work (it produces a pure black no matter what color I pick):

`kak -n -e 'face BufferPadding green,rgb:FF0000'`
![screen shot 2016-12-21 at 2 22 44 pm](https://cloud.githubusercontent.com/assets/714/21408265/f43686c0-c788-11e6-9c11-bf30227d23bf.png)

But if I throw in an rgb foreground color, the background becomes blue (and the foreground becomes black):

`kak -n -e 'face BufferPadding rgb:00FF00,rgb:FF0000'`
![screen shot 2016-12-21 at 2 23 43 pm](https://cloud.githubusercontent.com/assets/714/21408298/21c963f0-c789-11e6-9a6c-add5449811b7.png)

This behavior suggests that the foreground color is trying to override color 16 and the background color is trying to override color 17.

I imagine the source of the problem here is that Terminal.app uses `TERM=xterm-256color` by default, but the `xterm-256color` terminal supports the `ccc` capability (which advertises that the colors can change), and of course Terminal.app doesn't actually support that. I think it uses this profile because there's a large number of tools out there that look for "xterm" instead of supporting terminfo properly. In any case, it seems that Kakoune needs some way to disable support for arbitrary RGB colors (which would instead map those colors to the nearest color in the xterm 256 colorspace). The `TERM_PROGRAM` env var can be used to detect Terminal.app (the value is `Apple_Terminal`). This capability (supporting arbitrary RGB colors) could be exposed as a global option and a bundled kak rc script could detect Terminal.app and turn off the capability (that way if someone uses another terminal with this same issue, they could work around the problem there too).

(all screenshots were taken using the "Basic" Terminal profile, which is black text on white background by default)

**Comment by kballard** [comment]
It occurs to me that the best place to put this option is probably as one of the ncurses options in `ui_options`.

**Comment by mawww** [comment]
we could add a workaround option to manually disable color changes in the ncurses ui, but arguably the bug is not on Kakoune side, the terminfo is wrong for the terminal. I'd prefer the bug to be fixed on the terminal side instead of adding workaround code for other applications in Kakoune. Any chance to get Terminal.app fixed ?

**Comment by kballard** [comment]
No chance. Terminal.app uses xterm-256color by default for 2 big reasons:

1. There's a huge amount of software out there that compares `$TERM` to known values (e.g. "xterm", "xterm-color", "xterm-256color", etc) instead of using terminfo. Software that does this typically also hard-codes the ANSI escapes instead of generating them using terminfo. So if Terminal.app used its own terminfo entry, it would break compatibility with all of that software.
2. Even if the above didn't matter, if Terminal.app used its own terminfo, it wouldn't work whenever you ssh'd into another machine, because that other machine wouldn't have the relevant terminfo entry. And if it reverted TERM back to "xterm-256color" in that case, we'd be left with the original problem.

So yes, ideally, Terminal.app would use its own terminfo, but it's just not practical to do so. Given that, having a ui_option to disable color changes in the ncurses UI seems like the best approach (at which point I'd submit a PR with a kak rc script that enables this automatically whenever `TERM_PROGRAM` equals `Apple_Terminal`, if you don't do that yourself).
