### ISSUE TITLE
Skip *debug* buffer when using buffer-next and buffer-previous

### ISSUE THREAD

**Issue by itsgreggreg** [mawww/kakoune#1059]
I use `:bn` and `:bp` to switch between editing buffers. Sometimes this leads me to the debug buffer. I can't see a time when this would be useful. If i'm ever gonna check on the debug buffer it's because I'm switching to it by name. IMHO the default should be to skip over the *debug* buffer when cycling through buffers.

**Comment by lenormf** [comment]
Those commands display the next/previous buffer in the list of open buffers, I don't think they need to be any kind of smart. If you really don't like this behaviour, you can declare aliases to your own functions that will execute one more `:bn` or `:bp` if they've made you end up on the debug buffer, something like the following:

```
def my-buffer-next %{
  buffer-next
  %sh{ [ "${kak_bufname}" = '*debug*' ] && echo buffer-next }
}
```
