### ISSUE TITLE
Make non-optional "prompt" windows more salient

### ISSUE THREAD

**Issue by akkartik** [mawww/kakoune#1060]
It took me a while to realize why kakoune would sometimes get into a mode where the usual keys didn't work anymore. Say I opened a client where a file was stale. I'd get this popup:

!["modified externally" prompt](https://cloud.githubusercontent.com/assets/3161/21414040/d7cd8c86-c7b0-11e6-9a60-49631146093b.png)

But since I've already trained myself to ignore most autocomplete windows (particularly on my usual windows that are much larger in full-screen than the above example), say I don't notice the popup and press a command. The screen now looks like this:

![missed the prompt, pressed a key](https://cloud.githubusercontent.com/assets/3161/21414061/00b060ec-c7b1-11e6-9307-6ea0efdb941b.png)

Now I'm confused. Worse, the popup has vanished, so I have no way to tell what's going on anymore. In practice I'd find myself jabbing at a few keys, and most likely eventually hit `<Esc>`, which would result in this cryptic message that I again wasn't noticing:

![file kept](https://cloud.githubusercontent.com/assets/3161/21414124/a3a4fd8a-c7b1-11e6-8de3-7fe1610e91d0.png)

It took me a while to realize that this innocuous phrasing of "kept" meant that *I lose changes if I save*.

---

A couple of improvements, in the spirit of [5 whys](https://en.wikipedia.org/wiki/5_Whys):

1. Make windows that have prompts a different color background. Maybe red?

2. Keep the prompt up when the user doesn't press a valid option.

3. In the case of the "modified externally" prompt, maybe have the message say, "ignoring external modifications" or something like that. Again in some color other than the usual yellow.

**Comment by akkartik** [comment]
Alternative suggestion: draw prompts in the center rather than bottom right. They're modal dialogs, so they should look like modal dialogs.

**Comment by lenormf** [comment]
The popup should definitely not disappear if an unexpected key is hit (or it should have one choice to lose the current changes, and anything else would load the new version).

The message that prints what action was subsequently taken could also be moved from the status bar to a clippy autoinfo type message.

However printing this message box in the middle of the screen would potentially prevent you from seeing that the contents of the buffer has changed, not sure if it's a good exception to make.

**Comment by casimir** [comment]
Guess it misses 2 why's. I think of the one more:
Why not use the `autoreload` option to change the behavior?

I set it to `yes` personally.

**Comment by leemachin** [comment]
Autoreload makes sense when the file has no local edits (why would you choose to leave an unaltered file out of date if you edited it somewhere else?). I think the prompt when you attempt to save an altered buffer (or add another edit) should bug you until you make an unambiguous choice: yes, no, and potentially a third option to see a diff if you don't know why the file has changed (which can sometimes happen when messing around with git, for example). Unrecognised key input for those choises is ignored so you don't accidentally dismiss the prompt and mess up the file.

**Comment by akkartik** [comment]
Yes, to be clear I *like* the default behavior here. I just want to make it more obvious and fool-proof (the fool being me).

**Comment by akkartik** [comment]
For example, I always appreciate Vim's warnings about an already-existing swap file.

**Comment by mawww** [comment]
I think having a modal info box would be a good solution, the fact that the window sometimes disappear is due to how the info system works, it seems in some cases `info_hide` gets called by some other code that ends up hiding the reloading info.
