### ISSUE TITLE
Improve documentation for kakrc and autoloading

### ISSUE THREAD

**Issue by itsgreggreg** [mawww/kakoune#1063]
It took me much to long to figure out how this stuff works and I imagine many people would give up before figuring it out. I have no idea what `$XDG_CONFIG_HOME` is or where it comes from and the official documentation doesn't mention that kakoune will fall back to `~/.config` if it can't find it. I also think you need to put in bold or something that if you create your own autoload directory that it'll stop using the share autoload directory. I couldn't figure out what went wrong and was removing files one by one until I went over the docs with a fine toothed come to figure it out. 

IMHO the most sensible defaults would be to just tell people to put files in ~/.config/kak and to autoload everything with the option to turn it off in kakrc. The 2nd best option would be to clarify the docs. something like:

## 5 Configuration and Autoloading

Kak will search for your configuration files in the following order
 1. a `../share/kak` folder relative to your kak binary
 2. ` $XDG_CONFIG_HOME/kak` if it is defined
 3. `~/.config/kak`

### 5.1. kakrc

You can create a `kakrc` file and place it in your configuration folder.<br>
If you start kak with the `-n` flag, your kakrc will not be loaded.

### 5.2 Color Schemes

Kakoune ships with a few color schemes installed to ../share/kak/colors/.<br>
You can place your own colorschemes in `your_config_directory/colors` and they will be added to the autocomplete.

### 5.3 Autoload

Kakoune will load all scripts in the filst `/autoload` directory it finds, and it ships with one at `../share/kak/autoload` relative to your kak binary.

All other kak files you want kakoune to run on startup, such as custom commands and highlighters, place in `your_config_directory/autoload`.

**NOTE:** If you create this directory, kakoune will stop loading the system directory at `..share/kak/autoload`. You can then simlink the `..share/kak/autoload` directory into your autoload directory or just individual files if you like.

for example, this would simlink all of the default autoload files into your own autoload directory if you are on a mac:
~~~bash
ln -s /usr/local/share/kak/autoload ~/.config/kak/autoload/autoload
~~~

**Comment by casimir** [comment]
Guess the XDG specification is not universal yet. In most xdg-util or custom lob implementation the default path is `~/.config`, I guess it should states explicitly in the readme. Neovim did a pretty good job with this https://neovim.io/doc/user/nvim.html#nvim-from-vim. Presenting the path as the default (even if it's only mostly true) and providing a link its XDG support doc page.

About the autoload I think the documentation is clear as is. It's the bahavior that is surprising, I don't know another software that does the same instead of merging system and user config. 
While surprising if find the symbolic link trick pretty elegant.

**Comment by ekie** [comment]
thank you for the feedback, i think this can be improved and updated, when doing so have a look at https://github.com/mawww/kakoune/blob/master/README.asciidoc#23-running

~~~~~~~

...

At startup, if `-n` is not specified, Kakoune will try to source the file
`../share/kak/kakrc` relative to the kak binary. This kak file will then try
to recursively source any files in `$XDG_CONFIG_HOME/kak/autoload` (with
`$XDG_CONFIG_HOME` defaulting to `$HOME/.config`, and falling back to
`../share/kak/autoload/` if that autoload directory does not exists), then
`../share/kak/kakrc.local` if it exists, and finally `$XDG_CONFIG_HOME/kak/kakrc`.

That leads to the following behaviour: by default, with no user autoload
directory, the system wide autoload directory is used, once the user wants
control on autoloading, they can create an autoload directory and eventually
symlink individual scripts, or the whole system wide autoload directory. They
can as well add any new scripts not provided with Kakoune.
~~~~~~~

for the motivation behind the design choices have a look @ https://github.com/mawww/kakoune/issues/554

**Comment by Arcanum-XIII** [comment]
XDG didn't meant a thing for MacOS X, and I would guess that the other member of the BSD family will not be aware of it. Took me a while to figure it.

**Comment by mawww** [comment]
Seems there is a bit of confusion around this, so clearly we have to improve the documentation.

The first thing is that seems some people think `../share/kak/kakrc` is the user configuration or some kind of fallback. It is **not**. `../share/kak/kakrc` is Kakoune's startup script, and that startup script has the necessary logic to load user configuration.

From the Kakoune binary point of view, the only thing it tries to source is `../share/kak/kakrc`, this script, that is bundled with Kakoune. Its this script that search for user configuration and loads autoload scripts.

**Comment by mawww** [comment]
I hope the new wording is less confusing.

**Comment by josephrocca** [comment]
I was a bit confused by the current README.md config section. Probably could let people know that `$XDG_CONFIG_HOME` usually means `~/.config` (if that is indeed the case - I am a noob)
