### ISSUE TITLE
Don't prepend `-` char for lines above current_line when relative line num enabled

### ISSUE THREAD

**Issue by alexanderjeurissen** [mawww/kakoune#1068]
If relative line numbers are enabled then lines above the current cursor line are prepended with a `-` sign. This IMO adds unnecessary clutter to the UI. The fact that these lines are above the current line makes it obvious that one needs to use the `k` character together with the count to navigate to the appropriate line. (this is common vim knowledge)

I think I've traced the source of this behaviour to the following file:
https://github.com/mawww/kakoune/blob/master/src/highlighters.cc#L753

If we make this difference absolute using `abs` then the `-` sign should be gone.

I'm just checking if you have interest in this behaviour changing before I submit a patch.

**Comment by mawww** [comment]
I dont mind personally, what I would not be keen on is adding yet another switch to the number_lines highighter, so we need to choose between the two.

Any strong opinions on that ?

**Comment by lenormf** [comment]
When I switch back to a buffer and I don't know where the cursor is, I use the minus signs as a hint that I should look down. Without them I would have to read the numbers to know what direction to look, which uses more brain cycles. I don't mind removing the minus signs, but they are not totally superfluous.

**Comment by alexherbo2** [comment]
I prefer without the signs, but with a hint on the current line.

**Comment by alexanderjeurissen** [comment]
@lenormf If we make the curent line more distinguishable from other line numbers (by means of highlighting for example), would that solve your use-case ?

**Comment by alexherbo2** [comment]
``` kak
add-highlighter number_lines -relative -hlcursor
```
