### ISSUE TITLE
Add <F1> command to show contextual help

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#107]

**Comment by Delapouite** [comment]
Currently there's no real entry point to the manpages, each of the files in https://github.com/mawww/kakoune/tree/master/doc/manpages describe a specific topic.

We could add a `doc/manpages/index.asciidoc` serving as a TOC to then reach other specific docs.
The trampoline written here https://github.com/mawww/kakoune/issues/1122#issuecomment-274334942 would fit nicely for this purpose.

The `<F1>` key could they simply be mapped to `:doc index`

**Comment by lenormf** [comment]
I don't think mapping `FN` keys is a good idea, as some keyboards don't even have them anymore.

As for the table of contents, it's supposedly not needed because of completion on the `doc` command. Having a `:doc index` command wouldn't make sense either.

**Comment by mawww** [comment]
Yeah, I dont think F keys should be mapped by default. They are available to user though.
