### ISSUE TITLE
Homebrew formula produces a debug build

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1070]
I think the OSX users would rather have an optimized build by default.

**Comment by lenormf** [comment]
The `Makefile` produces a debug build by default on purpose, so that users who get a crash can post a stacktrace in the bug report. I think we should keep it that way from some more time, we would lose a lot of information by stripping symbols.

**Comment by occivink** [comment]
I think that's expected if you build it manually, but for distribution purposes it's doing a disservice to the users to ship non-optimized binaries. It's also normal for new users to check how well kakoune performs with hueg files and we don't want them to get a wrong impression of kakoune's performance.

**Comment by mawww** [comment]
I agree, the brew recipe is akin to installing through a package manager, I think it should build an optimized version.

**Comment by occivink** [comment]
Fixed as of 66ad1ff1229b172bade9010a2b1abd18252f8a79.
