### ISSUE TITLE
User mappings should allow for multiple characters

### ISSUE THREAD

**Issue by alexanderjeurissen** [mawww/kakoune#1071]
Currently it's only possible to map to a single character in the User space. This severely limits the ability for mnemonic key bindings. such as:

```
# ,ws => new vertical split
map global user ws '<esc>:tmux-new-vertical<ret>'

# ,wv => new horizontal split
map global user wv '<esc>:tmux-new-horizontal<ret>'
```

**Comment by doppioandante** [comment]
Maybe you can use the on-key command to do this?

**Comment by danr** [comment]
Yes! It can be done like this with `on-key`:

    def my-multimap %{
        on-key %{ %sh{
            case "$kak_key" in
                s) echo tmux-new-vertical
                   ;;
                v) echo tmux-new-horizontal
                   ;;
            esac
        } }
    }

    map global user w :my-multimap<ret>

**Comment by mawww** [comment]
`on-key` is the way to go, Kakoune does not support multi key mappings to keep it simple, and avoid all the complexity that would arise from ambiguities with multiple keys.
