### ISSUE TITLE
Keyboard shortcuts are inconsistent in Readme

### ISSUE THREAD

**Issue by akkartik** [mawww/kakoune#1075]
Sometimes it says `<c-r>`, sometimes `ctrl-r`, sometimes `control-o`. Similarly for 'alt' and other modifiers. Makes it hard to search the docs for a specific shortcut. Would there be any interest in standardizing to one of those forms? If so, please let me know what you prefer and I can create a PR.

**Comment by mawww** [comment]
Yeah, it would be nice to unify all those, `<c-r>` would be the preferred as thats what Kakoune can parse.
