### ISSUE TITLE
After updating in brew I got this error

### ISSUE THREAD

**Issue by dbazuin** [mawww/kakoune#1079]
Error: kakoune was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!

**Comment by dbazuin** [comment]
For now I am unable to use kaknoune. It is installed but not linked.

**Comment by doppioandante** [comment]
According to IRC this is the way to install it:
> PKG_CONFIG_PATH=/usr/local/opt/ncurses/lib/pkgconfig brew install --HEAD https://raw.githubusercontent.com/mawww/kakoune/master/contrib/kakoune.rb

could you close?

**Comment by dbazuin** [comment]
I did need to manual delete the kakoune folder in the cellar but then indeed it worked.
