### ISSUE TITLE
Explain the name?

### ISSUE THREAD

**Issue by nathanl** [mawww/kakoune#1085]
How is Kakoune pronounced? I can't chat about it without knowing this. :)

Also, where does the name come from?

**Comment by doppioandante** [comment]
https://github.com/mawww/kakoune/blob/master/doc/manpages/faq.asciidoc#how-to-pronounce-the-name-of-the-project-and-what-does-it-mean-

You can browse the same document doing :doc faq inside kakoune

**Comment by casimir** [comment]
You will find your answer in https://github.com/mawww/kakoune/blob/master/doc/manpages/faq.asciidoc  If not sufficient you are more than welcome on IRC to discuss this.

**Comment by mawww** [comment]
I hope the existing documentation is enough, if you have improvement suggestion, join IRC to discuss them, comment here, or open a pull request :)

**Comment by nathanl** [comment]
Thanks!

**Comment by nonbeing** [comment]
The docs have moved in the repo., As of July 2018, the correct link for `faq.asciidoc` now is https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc
