### ISSUE TITLE
Rust completion: racer support.

### ISSUE THREAD

**Issue by dpc** [mawww/kakoune#1087]
Hi,

I wonder how much effort would be to add a completion through `racer` - standard tool for Rust completion. Seems to me that it should be reasonably simple to add a hook to `rust.kak` that if `racer` binary is detected would invoke `racer` to get a list of completions.

**Comment by occivink** [comment]
I don't know how (dis)similar a racer script would be, but there is already support for C/C++/obj-C autocompletions by clang in [clang.kak](https://github.com/mawww/kakoune/blob/master/rc/extra/clang.kak)

**Comment by casimir** [comment]
I have some prototype working on my laptop but I'm short on hacking time these days. Feel free to copy it: https://github.com/casimir/kakoune-extra/blob/master/racer.kak

**Comment by dpc** [comment]
@casimir That's a good start. After turning on with `racer-completion-enable` it does some autocompletion on `std:` instead of `std::` but other than that it seems to work.

**Comment by mawww** [comment]
Closing this issue, please open a PR when the racer.kak script is ready.

**Comment by casimir** [comment]
@mawww I can't say this will happen fast but I will, sooner or later.

@dpc I hope this version will do for now, I'll ping when the script is ready!

**Comment by dpc** [comment]
@casimir Thanks!

**Comment by casimir** [comment]
@dpc @mawww As promised it took some times 😉 → #1249
