### ISSUE TITLE
Why db to delete buffer instead of bd

### ISSUE THREAD

**Issue by monkoose** [mawww/kakoune#1094]
Hi there! 
Just start learning your editor. And here is some thing that i don't understand. What is the point to have default alias db to delete buffer and not bd?

First of all in bd keystroke there is mentioned "object" "verb" sentence(buffer delete), unlike db(delete buffer). And it is more common for vim users. So what was the point? If we have same bn bp b "name" navigations?
And i'm not complaining, just asking. For the first glance i relly like kakoune. Good job guys.

**Comment by ekie** [comment]
hi,
have a look @ https://github.com/mawww/kakoune/issues/806 & https://github.com/mawww/kakoune/pull/827 & https://github.com/mawww/kakoune/commit/dcd733e5fab9016afbf9d8b5c5774053c1ce24af

**Comment by monkoose** [comment]
Thank you @ekie this clear for me that in editor we have `object-verb` and in prompt we have `verb-object` to be more common for unix/vim users. And i always can alias `bd` if would need so. 
I will write my thoughts about #827 later in that discussion.
