### ISSUE TITLE
kak -l shows no sessions on OSX

### ISSUE THREAD

**Issue by Droggelbecher** [mawww/kakoune#1097]
I have several instances running, some just started with "kak somefile", but also kak -d -s somename, none of which show up with "kak -l" on OSX. It is however possible to connect to the named session with "kak -c somename".
In contrast to README.md (2.3 Running), the session fifos don't seem to show up under what is "/tmp" on my mac but seem to be stored someplace else.

**Comment by casimir** [comment]
I can confirm. Possibly this come from 4b696836d1516587812b6ce51f41ed825b26e7e8 there is at least still 3 hard coded `/tmp`: [here](https://github.com/mawww/kakoune/blob/7dae25c33fa94b12538b69213e3d731ca51df6b3/src/main.cc#L765), [here](https://github.com/mawww/kakoune/blob/7dae25c33fa94b12538b69213e3d731ca51df6b3/src/main.cc#L773) and [here](https://github.com/mawww/kakoune/blob/26e1caef7b855ccd45655988f0114bfc513bf08b/src/remote.cc#L489).

In the default shell:
```sh
$ echo $TMPDIR
/var/folders/3f/1bq1zpss1q115x53wq04w_r40000gn/T/
```
