### ISSUE TITLE
U+1B[1m ... U+1B[0m

### ISSUE THREAD

**Issue by AnthonyJacob** [mawww/kakoune#1098]
For example after `:doc commands` I get a page containing 

> U+1B[1mPRIMITIVESU+1B[0m

 ....

What is that (I suppose it should be a title tag, but kakoune fails to render it for some reason)? Is that a bug? How do I fix it? 

I am Fedora 25 user.

**Comment by 4d47** [comment]
Note that commenting the `export MAN_KEEP_FORMATTING=y` line in `rc/core/doc.kak` seems to fix this.

**Comment by AnthonyJacob** [comment]
I am sorry but you must be a bit more explicit. Where is rc folder located?

**Comment by 4d47** [comment]
Note that commenting [this line](https://github.com/mawww/kakoune/blob/76c58aa022a896dc170c207ff821992ee354d934/rc/core/doc.kak#L8) seems to fix.

**Comment by AnthonyJacob** [comment]
Well, I did not build from source. Instead I ran

>dnf copr enable jkonecny/kakoune
>dnf install kakoune

**Comment by mawww** [comment]
@lenormf Why do we need that MAN_KEEP_FORMATING env var set ?

**Comment by lenormf** [comment]
@mawww I think this is a chunk that was mistakenly merged from a WIP of mine that implements the overstrike syntax. This environment variable forces the `mandb` implementation to keep the `\x08` characters in the output even when it is not a terminal. I think it can safely be removed.

**Comment by lenormf** [comment]
I don't think the commit will have an impact on the issue, as the `MAN_KEEP_FORMATTING` option merely keeps the overstrike sequences in the output (which are then interpreted by the pager to be converted in ansi sequences). It all depends on the implementation of `man` everyone is running, and we don't know what @AnthonyJacob or @4d47 are using.

**Comment by lenormf** [comment]
As mentioned earlier, removing the environment variable had no impact on the issue, we need to reopen this as users are still experiencing trouble.
