### ISSUE TITLE
Add user defined key mapping to info boxes

### ISSUE THREAD

**Issue by 4d47** [mawww/kakoune#1100]
Would be nice to add user defined key mapping to the info boxes / clippy assistant in addition to the default keys. Eg. by adding some user map in kakrc:

    map global user q ':write-quit<ret>'

On pressing `,` the info boxe is empty. It would be nice to have q listed.
Other modes like goto and view list the default keys in there info boxes.

From what I found the maps mode that produces info boxes are: goto, view and user.

**Comment by doppioandante** [comment]
There's an `info` command that creates a custom info box, but you probably want it to be a default?

**Comment by 4d47** [comment]
Yes I was thinking by default but then I understand it's probably lot's of work for little added benefits.
Also if user mappings are documented in info boxes why not documenting in :doc shortcuts too !

I tried to replace the user mappings info box with my own custom but was not able to work it out.
`:map global normal , :info<space>yada<ret>,`

**Comment by danr** [comment]
What happens with that keybinding is that pressing `,` removes the `info` box. This is a bit inconsistent as `on-key` does not remove `info` boxes.

**Comment by mawww** [comment]
This is mostly tricky because we dont have much to display for the user key, only the fact that it exists. To make that useful we would probably need a docstring on key mappings.

**Comment by 4d47** [comment]
Found this [Add -docstring switch to :map command](https://github.com/mawww/kakoune/issues/105)
