### ISSUE TITLE
clang completion 

### ISSUE THREAD

**Issue by kangjoni76** [mawww/kakoune#1102]
I did following this tutorial https://github.com/mawww/kakoune/wiki/How-To to enable clang completion. 
Let me tell what I've done
1. copy kaksrcfolder/rc to kakinstallrootfolder/
2. copy kaksrcfolder/share to  kakinstallrootfolder/share
here the third steps from your links ```set the clang_options to the command line options your code needs, and add the following hook to your kakrc: hook global WinSetOption filetype=cpp %{ clang-enable-autocomplete; clang-enable-diagnostics }```
I didnt get what you mean by setting clang_options syntax here.
I just did by adding ```hook global WinSetOption filetype=cpp %{ clang-enable-autocomplete; clang-enable-diagnostics }``` to kakrc file at end of file in kakinstallrootfolder/share and nothing happens.
thanks happy new year btw.

**Comment by mawww** [comment]
Hello,

You should not have to copy the folders manually, if you do a `make install`, Kakoune will install these files in the appropriate location (you can control the prefix with `make install prefix=...`). You can as well just run kakoune from the src/ directory, without installing it.

In both cases, your user configuration should be in a file named `~/.config/kak/kakrc`. The `clang_options` is a kakoune option (that can be changed using the `set` command) that contains the flags to pass to the clang process when completing. You'll want to put include path flags, preprocessor defines, etc... in there.

The kakrc file in share is Kakounes init script, it is not intended to be user edited. It is actually that script that will load your user configuration in `~/.config/kak/kakrc`.

Happy new year, and thanks for trying Kakoune.

Maxime.

**Comment by kangjoni76** [comment]
Aargh. sorry for late answer, I did solve just now this case with proper  change to Makefile to not build the doc and adjusting some cxxflags and ldflags , then adding custom function in clang.kak with body of function declared as follows : 
````
def clangsetincludeflag -docstring "Set standart clang include flag for code completions" %{
    clang-enable-autocomplete
    set global clang_options "-I/use/include -stdlib=libc++"
}
````
And open some c++ file
kak file.cc
:clangsetincludeflag <- enter 

And booms :)
