### ISSUE TITLE
Unexpected behavior when inserting newline in comment

### ISSUE THREAD

**Issue by bitonic** [mawww/kakoune#1111]
When entering a new line inside a multi line comment, the comment start gets mangled with the words: https://asciinema.org/a/462ho8doqi978llxuiox6ue6u . Also happens with the Haskell mode.

**Comment by mawww** [comment]
Cannot reproduce on latest, I think c3e1bab9d6195570a59e315669b3afd8761ca459 fixed it. Reopen if that is not the case.

**Comment by bitonic** [comment]
You're right, it is fixed. Thanks!
