### ISSUE TITLE
:ranger non-functional in tmux

### ISSUE THREAD

**Issue by Droggelbecher** [mawww/kakoune#1117]
ranger version: 1.7.1
tmux version: 1.8

After typing ":ranger", nothing happens, *debug* contains a stderr output of tmux complaining about incorrect usage of "split-window".
<img width="584" alt="screen shot 2017-01-10 at 9 00 08 am" src="https://cloud.githubusercontent.com/assets/118525/21798171/5a3dfdec-d713-11e6-984c-0feecf0dde23.png">

**Comment by lenormf** [comment]
As in #615, I think this script was made with `tmux 2.x` in mind, ask @alexherbo2 if he can have some kind of retro-compatibility with older versions.

**Comment by Droggelbecher** [comment]
Ah, sorry I'm stuck here with ubuntu 14.04 (*eyeroll*), I'll just see if I find a backport/ppa/whatever, don't worry about it :)

**Comment by mawww** [comment]
Seems reasonable to only support tmux 2+, closing.
