### ISSUE TITLE
Comment start is misaligned when entering newlines for intented comments

### ISSUE THREAD

**Issue by bitonic** [mawww/kakoune#1118]
See <https://asciinema.org/a/4mtl3cyadva0tuuqdpdik2tw6>. Reproduced on 9f0bca53c41a5e363020ab7421b37b165b2db9a2 , I've tried with Haskell and C.

**Comment by mawww** [comment]
Argh, thats due to 5ddc28eaade3985d0d59597f2fd834e692b03a07 that now pastes at line begin, so before the indent.

A solution is to do the comment prefix copy hook *before* copying the indent from previous line. I am testing that to see if it works fine or if it breaks some other indent behavious.

**Comment by danr** [comment]
I'm sorry about this mess, I'm working on a fix and I think I have it. Give me a few more.

**Comment by doppioandante** [comment]
@mawww maybe we should abstract the autoindentation.
What about something like this:
1) an option to retain indentation from previous line, which could be useful per se for langauges that still don't have a rc script
2) a way for scripts dictate when to indent or deindent, based on previous line ( e.g. '{' at the end, or 'def' at the beginning, or any pattern) or based on current line (e.g. C++ 'public:', 'end' or '}')

Is there any shortcoming? Replicating the actual commands to indent in every script is bad.

**Comment by mawww** [comment]
@doppioandante Long time ago there was some additional abstraction in Kakoune for indentation, but then I realized we could implement it using normal mode commands. Its been a very good validation that the editing model was expressive enough.

Its something I dont plan to change, a possibility would be to introduce a .kak file that provides all the building block for auto indentation. But I am not convinced its worth it yet.
