### ISSUE TITLE
Enter / Escape to reload / not reload buffer when modified externally

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#113]

**Comment by dumblob** [comment]
If *Enter/Escape* was meant as an answer to a question dialog (e.g. in the command/status line) appearing in affected windows, when a file was modified then *+1*. If only a buffer was modified in a different window, it should be updated in all windows simultaneously without user intervention.

**Comment by mawww** [comment]
Hum I did not bind that because I felt we wanted a more explicit keystroke (y/n or r/k) to avoid reloading by error. However we now can undo reloading anyway so its ok if you reload by error, you did not lose your changes, so I guess Enter/Escape for that would make sense.
