### ISSUE TITLE
Feature request: NormalKey hook -with-maps

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1132]
The `NormalKey` hook tells me which key has been pressed _after_ it has gone through the keymaps. I rebind a lot of keys and would also like to have a hook to know which key I pressed _before_ remapped.

Use cases: replay it using `exec -with-maps`. Use it in a macro register. Inform what I pressed like `normal` `autoinfo`.

Thanks!

**Comment by mawww** [comment]
Hello,

We cannot provide that directly in the NormalKey hook, because mappings have been handled higher in the call stack. Changing that would require a lot of code changes.

Could you precise the use case you have in mind, I did not get it.

Cheers.

**Comment by danr** [comment]
Pardon for being imprecise. I simply meant a (new) hook for the "raw" keys, as is outputted by `set buffer debug keys`.

About the use cases:
I can then store this key, and repeat it by using `exec -with-maps`. Or I can use it to make a macro, or just echo what I typed for educational purposes.
