### ISSUE TITLE
Feature request: beautify

### ISSUE THREAD

**Issue by hcarver** [mawww/kakoune#1139]
I'd love a feature that works like [Atom's beautify](https://github.com/Glavin001/atom-beautify). At its simplest, this would an add-in that can apply formatting and indentation rules to an existing buffer. This might already exist, but I couldn't find it.

**Comment by Delapouite** [comment]
Hi.

You need to specify the formatcmd option to use this rc file : https://github.com/mawww/kakoune/blob/master/rc/core/formatter.kak

**Comment by mawww** [comment]
@hcarver On the most basic level, its very simple to do, just select the lines you want to reformat, and use the `|` command to pipe it through whatever formatter you want. 

Using unibeautifier, you could just type: `|unibeautify --language JavaScript --config-json '{"JavaScript":{"insize":2,"inchar":" "}}'` and the selection should get formatted. Put that into a mapping or a custom command and you'r good to go.

formatter.kak provides a wrapping around that, with a `:format` command that will use the `formatcmd` option to format the whole buffer.

**Comment by hcarver** [comment]
Thanks both. @mawww's answer is closer to what I was after. I ended up doing 

1. `npm install --global unibeautify-cli`
1. `npm install --global beautifier-prettydiff`
1. Then in my .config/kak/kakrc, `hook global BufCreate .*\.json %{ set buffer formatcmd 'unibeautify --language JavaScript --config-json \'{"JavaScript":{"insize":2,"inchar":" "}}\'' }`
1. And now the `:format` command works in JSON files.

Not sure if there's a good place to add that to the wiki, but hopefully the next person with this question will find this thread. 👍

**Comment by casimir** [comment]
@lenormf this could be a good candidate for your syntastic script.
