### ISSUE TITLE
Lag switching modes

### ISSUE THREAD

**Issue by haydensmack** [mawww/kakoune#1142]
Hi,

I have found that there is a delay when switching out of the insert and prompt modes. But switching into these modes there is no delay. I'm using a fresh install of Kak on Mac.

Is there any reason for this? And can this delay be fixed? 

Thanks.

**Comment by lenormf** [comment]
Are you using a terminal multiplexer?

**Comment by haydensmack** [comment]
Yeah, tmux. That's interesting, I didn't notice that without tmux there is no delay. Do you know the reason why it does this?

**Comment by mawww** [comment]
Add
```
set -sg escape-time 25
```
In your tmux.conf.

Whats happening is that tmux, as Kakoune, uses a delay to distinguish Alt+Key and Esc. But the default tmux delay is huge (500ms or so), leading to a big delay. 25ms is good enough on modern computers.

**Comment by haydensmack** [comment]
Thanks for that explanation. The solution worked perfectly.
