### ISSUE TITLE
Using arrow keys in normal mode from SSH

### ISSUE THREAD

**Issue by sebsebmc** [mawww/kakoune#1145]
When in normal mode and using kakoune over SSH, using the arrow keys inserts `A` `B` `C` or `D` depending on the key. This same behaviour is seen in vim but they have the `set nocompatible` option to deal with this.

**Comment by lenormf** [comment]
Are you sure this option and your issue are related? According to the documentation, this is a `vi`/`vim` feature compatibility option, whereas your issue seems to be a termcaps one.

What terminal are you using? Does your server have the appropriate terminfo installed, for your terminal?

**Comment by sebsebmc** [comment]
I don't really have the in-depth knowledge of terminals to recognize that this was a terminal problem. I'm using Bash on Windows to ssh to a Ubuntu (16.04) machine.

I'm guessing that this is caused by Bash on Windows, though I could not find this exact issue mentioned in their issue tracker. I believe Bash on Windows claims `term=xterm` but mostly because it is the most popular option, not necessarily because they implement all the xterm features.

**Comment by mawww** [comment]
Yeah, this is very likely a terminfo problem, we cant do much if the terminfo is not matching the actual terminal correctly.
