### ISSUE TITLE
How to suspend new X11 window / Tmux pane ?

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1146]
Hi

The `new` command opens either: 
- a X11 window with a new terminal https://github.com/mawww/kakoune/blob/master/rc/base/x11.kak#L31
- a tmux pane https://github.com/mawww/kakoune/blob/master/rc/base/tmux.kak#L27

Unfortunately, whatever the above solution I use, I can't find a simple way to suspend this new client with `<c-z>` like the original client. Am I missing something?

EDIT: I'm using xterm

Possibly related : https://github.com/mawww/kakoune/issues/483

**Comment by occivink** [comment]
I think it's because kakoune gets started directly in the new tmux pane / terminal emulator instead of below a shell, so there is no shell to provide job control.
Although I can see that some of the terminals in x11.kak (urxvt, xterm, mintty) do get started under a shell so I think it should work with them.

**Comment by lenormf** [comment]
It depends on what terminal you use I reckon.

**Comment by Delapouite** [comment]
Yes there's this terminal detection declaration at the top : 

```
decl str termcmd %sh{
    for termcmd in 'termite        -e      ' \
                   'urxvt          -e sh -c' \
                   'rxvt           -e sh -c' \
                   'xterm          -e sh -c' \
                   'roxterm        -e sh -c' \
                   'mintty         -e sh -c' \
                   'sakura         -e      ' \
                   'gnome-terminal -e      ' \
                   'xfce4-terminal -e      ' ; do
        terminal=${termcmd%% *}
        if which $terminal > /dev/null 2>&1; then
            printf %s\\n "'$termcmd'"
            exit
        fi
    done
}
```

`echo %opt{termcmd}` correctly returns `xterm -e sh -c` but the `<c-z>` problem is still here.

**Comment by occivink** [comment]
If you exit the new kakoune instance, do you drop into a shell or does the pane/window get closed?

**Comment by lenormf** [comment]
Indeed, job/input control is probably not activated by the shell when using the `-c` flag, maybe adding an `-i` flag to the `termcmd` would work?

**Comment by mawww** [comment]
The use of `sh -c` is only an implementation detail here, to unify the way terminal emulators parse the command to launch (some take a single argument and parse it, some other takes all following arguments and pass them as is to the command).

I dont think users should expect a job controlling shell being available underneath each Kakoune clients. It will be true only if launched manually from a shell.

Additionally, you'd probably get another shell than the one you expect, we use a POSIX shell, it might be bash or zsh on certain systems, but it might as well just be dash or busybox sh.

**Comment by Delapouite** [comment]
Thanks for your help.

This leads me to a follow up question concerning a client managment workflow.

To get a new client with proper job control we can do it without kakoune `new` command by simply opening another terminal with a window manager (i3, xmonad…).
But then we need to do a `kak -l` to find the right session_id, and a `kak -c session_id`. Is there any shortcut to launch kak directly connected to the last active session_id ?

**Comment by mawww** [comment]
Hum, I am not sure what the *last active* session would be. Note that you can see the session id in the status line. It should be simple to write a wrapper script that connects to the first session kak -l returns, or to do something fancier by accessing the associated socket files (in /tmp/kakoune/<user>/<session>)

**Comment by Delapouite** [comment]
Thanks all for your precious advices.

I managed to create a workflow that suit my needs for now, taking inspiration from [this](https://github.com/mawww/kakoune/wiki/Convenient-kak-daemon-helper---bin-stub) to deal with `<ctrl-z>` issues.
I've described it in the this new wiki page about ranger : https://github.com/mawww/kakoune/wiki/Ranger
