### ISSUE TITLE
Selection gets modified in some cases with "exec -draft" 

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1148]
Hi,

If you do `:exec -draft ca<esc>` with a one-character cursor, the current selection gets shifted. 
I expect the '-draft' switch to preserve my current selection.

**Comment by lenormf** [comment]
I think this is a dupe of #857. The issue stems from the underlying implementation of the `c` (and `r` allegedly), which deletes text before inserting new data, effectively triggering a selection modification prior  to entering insert mode again.

**Comment by occivink** [comment]
Yes that looks similar. Incidentally, I stumbled upon my issue while making a `minesweeper` script.
