### ISSUE TITLE
`shortcuts` is a poor name for the help document

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1150]
They are not really shortcuts to anything, as they are _the_ way to make kakoune do anything.

I would expect it to be `keys`, `keybindings` or something else with `key`.

(This is about `:doc shortcuts`)

**Comment by danr** [comment]
Or as the command to change them is `map`, something like `keymaps`, `keymappings` would be helpful.

**Comment by alexherbo2** [comment]
How about

- `commands`
  - `normal`
  - `insert`
  - `command`

**Comment by mawww** [comment]
I did rename to keys for now, it could be nice to split that document into one doc per modes.
