### ISSUE TITLE
add `gm` : go to matching char

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1151]
Hi

`m` and `M` keys already deal with matching chars.

What about adding `gm`, which stands for *go to matching* to jump from an opening char to its closing one and vice-versa?

**Comment by lenormf** [comment]
Hitting `m` again will put the anchor on the other matching character. You have also used `<a-;>`.

**Comment by danr** [comment]
Expanding on lenormf's answer:

    map global goto m '<esc>m;'

**Comment by lenormf** [comment]
I think this issue can be closed.
