### ISSUE TITLE
Inconsistency between i and a insertions

### ISSUE THREAD

**Issue by ianthehenry** [mawww/kakoune#1155]
`a` selects the newly inserted text, while `i`, `I`, and `A` do not.

It would be nice to have them be consistent. I would expect `a` not to extend the selection.

It would also be nice if there was a command to select the previously-inserted text after leaving insert mode.

**Comment by lenormf** [comment]
The `a` key *extends* the current selection to contain the inserted text, it doesn't select it. If you want to keep the original selection, you can save it using `Z` and restore it after appending text to it using `z`, if `a` didn't extend the selection we would have no way of integrating newly inserted text into a selection, but the opposite is possible with the method I described.

**Comment by alexherbo2** [comment]
I think we need an example to splotlight that `a` command has to work the way it does.

```
Banana Orange Apple Mango
```

1. Select a word
2. `a`
3. Type some text

What would be the behaviour if `a` didn’t extend?

**Comment by lenormf** [comment]
>`a` preserve selection

>a cannot preserve selection or append text without extending selection.

That's a bit contradictory isn't it.

**Comment by alexherbo2** [comment]
`a` preserves selection and appends text to selection, otherwise letters would be inserted from right to left.

**Comment by ianthehenry** [comment]
Okay. It seems the behavior is weirder than I thought. I did not expect the insertion point in insert mode to be linked to the selection the way that it is. I.e. the fact that using the arrow keys to navigate in insert mode drops the current selection is surprising to me. But it makes sense on reflection: otherwise, why would exiting insert mode reposition the cursor when you don't have a selection?

**Comment by lenormf** [comment]
There is no concept of cursor in the editor, there's always a selection that can be one character wide, and the arrow keys brings back the secondary cursor onto the anchor, and then move the anchor. That's why the editor is "selection oriented", there is no abstract level between the buffer (in which you can move around in most editors) and the actual data, there's something selected at all times.

**Comment by alexherbo2** [comment]
In earlier version of Kakoune, there were this explaining:

> There is no concept of cursor in Kakoune, only selections, a single character selection can be seen as a cursor but there is no difference internally.

**Comment by alexherbo2** [comment]
@lenormf Actually when I mean `preserve` is that the anchor is not moved.

**Comment by lenormf** [comment]
The anchor moves along the letters being inserted, after hitting `a`.
