### ISSUE TITLE
Nesting exec inside on-key causes... garbage arguments?

### ISSUE THREAD

**Issue by ianthehenry** [mawww/kakoune#1156]
There seems to be a problem with the following command:

    def insert -params 1 %{on-key %{exec "i%val{key}%arg{1}<esc>"}}

`%arg{1}` appears to be expanded to -- not random! -- but bytes that certainly shouldn't be there. I've gotten ` - uname`; `\u80`, `exec`, and I've gotten Kakoune to crash. Wha?

Using `7ba24c043aced097631e21463d79b21b17442a4e`. It works fine without the `on-key`:

    def insert -params 1 %{exec "i%arg{1}<esc>"}

**Comment by lenormf** [comment]
Whereas this issue is probably due to improper quoting of the command, the expansions result in the introduction of seemingly uninitialized variables into the command when they are used improperly.
