### ISSUE TITLE
`a` command shouldn’t reposition the cursor when its anchor is moved

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1158]
@ianthehenry found this bug in #1155 using the arrow keys to navigate in insert mode.

**Comment by mawww** [comment]
I am not convinced it would be a better behaviour. Its pretty predictible to say "You enter insert mode using append, we move the cursor right on enter, we will move it left on exit". Adding some logic that will not move the cursor left anymore based on a certain set of actions in insert mode seems like adding complexity in the editor behaviour with no clear gains.
