### ISSUE TITLE
Impossible to rebind Gh?

### ISSUE THREAD

**Issue by JakeHedman** [mawww/kakoune#1162]
I prefer using jkl; rather then hjkl, but it does not seem to possible to rebind Gh-Gl to Gj-G;?

**Comment by alexherbo2** [comment]
``` kak
map global goto <key> <keys>
```

**Comment by JakeHedman** [comment]
Thank you!

**Comment by danr** [comment]
Also related: `view` mode, accessed with `v` and `V`:

    map global view <key> <keys>
