### ISSUE TITLE
Use options for info boxes in the submaps (user, view, goto, etc)

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1165]
It's a known problem (#1100) that adding or changing keys to the submaps don't change the popup-window information. As an example, I might add `gn` to go to the text buffer:

    map global goto n '<esc>:buffer-next<ret>'

Right now, nothing for `n` will show in the `g` info box.

I propose to have a string option `goto_info` which is the info that gets displayed when the goto mode is entered. To have more text viewed when pressing `g` I simply add to this option, like this:

    set -add global goto_info %{n:    next buffer}

We can have at least these options:
* `user_info`
* `view_info`
* `goto_info`
* `object_info`
* `register_info`

Plus:
* Can extend or modify the info text (See #1100)
* Can view the info at any time, in any way (See #1152)

Minus:
* Completion of options gets more cluttered

**Comment by lenormf** [comment]
It sounds like a workaround for the real issue, which is that the editor has no way of getting the documentation string for custom mappings.

**Comment by Delapouite** [comment]
These additions may be a way to enhance the current behavior of the the register info that pops up when pressing the `"` key.
It currently shows the name and definitions of special registers. It would be awesome if it would show the content of each register (truncated if too long).

This kind of neat interactive listing of registers content when you're about to use them is demonstrated in the vim-peekaboo plugin : https://github.com/junegunn/vim-peekaboo


![](https://cloud.githubusercontent.com/assets/700826/6095261/bb00340c-af96-11e4-9df5-9cd869673a11.gif)
