### ISSUE TITLE
gc should center with small buffers

### ISSUE THREAD

**Issue by 4d47** [mawww/kakoune#1170]
When a buffer does not fill the window (eg. tildes appears), `gc` still center on window.
So if the buffer is less than half the screen, `gc` is behaving like `gj` and `gb`.

I think it should center of buffer. A 10 lines buffer on a 50 lines window, `gc` should go on line 5.

**Comment by lenormf** [comment]
The behaviour you suggest isn't one you would expect from a mapping documented as "window centering".

I think the current behaviour is consistent with its name/documentation, you probably just need another binding (or a custom one added to your configuration).

**Comment by 4d47** [comment]
Note that `:doc keys gc` is saying "go to the middle displayed line".

Personally only use gc sporadically so I'm ok with keeping current behavior, I think was surprised because I had the Vim `M` key in mind.
