### ISSUE TITLE
add an option to align modeline to the left

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1171]
Hi.

Currently the modeline is right aligned which is I think is sensible decision by default:  it gets out of the way and contribute to a more zen experience while coding, with less distraction. 

On the other hand, it contributes to a perverse effect: I often struggle to remember in which mode I'm mode currently in. Normal mode? Insert mode? (my brain acts in mysterious ways sometimes…)
Which leads to a bad experience because I type the wrong keys. Surprisingly in vim, I don't have this issue. The mode indicator is in the bottom left corner which is placed more in my immediate vision focus. Since code is always left align, I just "perceive" the mode changing in my peripherical vision. In kakoune, it's "too far" on the right.

There's already a `ncurses_status_on_top` option. Could there be something like a new `ncurses_status_align` option with a `left|center|right` value? Thanks.

**Comment by alexherbo2** [comment]
I agree the mode info is too far for what I would use it.

**Comment by lenormf** [comment]
That's tricky because it will conflict with the prompts, and lots of `if`s are going to be required to support that.

**Comment by doppioandante** [comment]
This would be very easy to do in the GUI but unfortunately it's still not as good as the terminal UI.

**Comment by danr** [comment]
I also struggle to see it. Also how many selections I have, sometimes I'm surprised I have a bunch of extra selections hidden somewhere out of sight.

That said, one can get more information to the left by easy means:

    hook global InsertBegin .* %{
        echo -color blue -- '-- INSERT -- '
    }
    hook global InsertEnd .* echo

**Comment by casimir** [comment]
I don't know if it's achievable in a generic way but while using (neo)vim I have my cursor changing with modes (block for normal and bar for insert). This use a VT100 escape code, something like that IIRC: https://www.reddit.com/r/vim/comments/2of45a/terminal_vim_changing_cursor_shape_on_linux/.
Another mechanism that's fairly used (e.g. by vim-airline) is to change the status line background color. Again I didn't try it myself in kakoune.

**Comment by mawww** [comment]
So, if we put the status line on the left, what do you think should happens when a status line message is displayed, and when we enter a prompt ?

**Comment by lenormf** [comment]
Prompts could be spawned on the opposite side of the statusbar, and messages still displayed where they used to be. But even so, it would eat one line of buffer content.

And it's possible that this entire issue is due to the fact that the terminal is just too large, hence the distance between the first column and the current mode (getting rid of the dead space on the right side of the window by resizing the terminal will fix your issue).

**Comment by Delapouite** [comment]
Thanks all.

You made very good points and offered many solutions to alleviate my base issue :
- use hooks `insertBegin` and `insertEnd` to add more visual indications like echoing -- EDIT -- at the bottom or changing face colors (cursor, statusbar, even background…)
- use tmux layouts to avoid unneeded full screen and resize the terminal to a reasonable width

It feels much better already. I was too blind (pun intended) to see this obvious tricks. Thanks again.

**Comment by mawww** [comment]
Does not seems worth it, closing.
