### ISSUE TITLE
Cursor should not have to be on last line when anchor is out of sight

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1172]
With a selection higher than the viewport, Kakoune insists on the cursor to be on the last line of the viewport (or first line for `<a-:><a-;>` selections). Commands like `vc` and `vt` do nothing. I'm now fumbling in the dark when it comes to interacting with the rest of the buffer's contents. 

I propose the cursor to be allowed anywhere in the viewport also in these circumstances.

**Comment by danr** [comment]
Note: this can be partially mitigated with the `scrolloff` option.

**Comment by mawww** [comment]
With the highlighting refactoring that came for `wrap`, we now only ensure the cursor is visible, instead of trying to get most of the main selection visible.
