### ISSUE TITLE
Allow arbitrary selection of search matches with `N` without moving the selection on the next `n`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1173]
Hi,

I'd like a way to create an arbitrary selection based on search matches (skipping some matches, keeping some). Currently, I select all the search matches and trim the ones I don't want manually with `<a-space>`, but it's tedious and sometimes doesn't do it.

Thanks.

**Comment by occivink** [comment]
I'm not sure I get what you propose, but I could definitely use an easier way to make such selections. Could you explain what you have in mind?

**Comment by lenormf** [comment]
```
def jumpnext %{ eval -save-regs m %{
    exec -draft "<space>n:reg m %val{selection_desc}<ret>"
    exec <a-space>:select<space>%val{selections_desc} : %reg{m}<ret>
} }
map global user n %{: jumpnext<ret>}
```

The above function doesn't quite work yet ("select: invalid argument count"), but it sums up the idea. Since all the `n` based bindings are taken, it might not be possible to have that as a primitive, but at least there will be code here for people who want it.

What it does is jump to the next search match after having deselected the current one, but keeping the previous selections intact. Right now you can't select arbitrary search matches with `N` and `n`, as the selections will move along the anchor when `n` is hit - that's what this issue is about.

**Comment by lenormf** [comment]
By the way @mawww, when two tokens are expanded next to each other in a string, a space in inserted between them, I didn't expect that (`echo %val{bufname}%val{bufname}` will print a space separated string).

**Comment by occivink** [comment]
Sounds like it would be easy to do with a reverse `'`

**Comment by danr** [comment]
@lenorm: You can get them next to each other in a `"`, like this: `"%val{selections_desc}:%reg{m}"`.

Below is my approach. It does not work when you only have one selection, though:

    map global user n '"aZ<a-space>"bZ"az<space>n"b<a-z>'

**Comment by alexherbo2** [comment]
I would like changing `n` command with this behaviour.

**Comment by mawww** [comment]
@alexherbo2 and remove the ability to search next match from multiple selections at the same time ?

**Comment by lenormf** [comment]
Here is the binding I'm using, for those interested, once again I got caught by the escaping:

```
def jumpnext %{ eval -save-regs m %{
    exec -draft '<space>n: reg m "%val{selection_desc}"<ret>'
    exec '<a-space>: select "%val{selections_desc}:%reg{m}"<ret>'
} }
map global user n %{: jumpnext<ret>}
```

**Comment by alexherbo2** [comment]
@mawww There still `/` `<up>` `<ret>` xD

**Comment by lenormf** [comment]
I'm enclined to close this issue now that a working implementation has been posted online (for archiving sakes), unless a compromise is reached soon to have that builtin.

**Comment by lenormf** [comment]
Here is the relevant part of a conversation we had about the issue on IRC:

```
ironzorg | alex``: what do you propose about my issue, regarding keeping previous search selections intact?
ironzorg | all the bindings that could make sense have been allocated already, we don't have much room
  alex`` | i don’t know
  alex`` | do u use `n` with multiple sels?
  alex`` | i think i never used like that
ironzorg | no, only when I wanted to ignore the current one and jump onto the next :)
ironzorg | which prompted my issue
  alex`` | if i need there still /<up><ret> and ? (no equivalent to extend from anchor point to next match)
  alex`` | i like your `n` being default actually
  alex`` | we dont lost expressivity with explicit / and ? <up>
   mawww | I think it could make sense to do that actually
  alex`` | `n`, _'_, <a-space>, <a-n> work but is painfull
   mawww | We already have a precedent, as N does not do the same a ?<ret>
  alex`` | yep
  alex`` | that what i would highlight
   mawww | and current n would be just /<ret>
   mawww | (<up> is not necessary, empty prompt means use the / reg)
```
