### ISSUE TITLE
Some prompts share the last entry in their history

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1174]
If the prompt of search, reverse-search, select or split do not have any history, pressing `<up>` will use the last value entered in any of the other prompts.

Example:
on such a buffer: 
```
ababab
```
after executing `/a<ret>xs<up>` the selection will be split on all `a` and the prompt `select:` stays empty.

**Comment by mawww** [comment]
Thats the expected behaviour, all these commands fallback to the content of the search register `/` if the prompt is validated empty.

**Comment by occivink** [comment]
Oh, I had no idea. Is it intended that pressing `<up>` changes the preview only when the history is empty though?
