### ISSUE TITLE
Make clarifications and specializations in colorscheme faces.

### ISSUE THREAD

**Issue by nicholastmosher** [mawww/kakoune#1186]
A continuation of some points brought up in #1181.

The primary ideas are:
* Disambiguate the `identifier` face by renaming it to `variable`.
* Add new faces, `module` and `function`:
  * `module` to highlight the names of imported resources (e.g. `<stdio.h>` or `java.lang.String`)
  * `function` to highlight functions defined previously in the file, working directory, or included modules.
* Discuss the merit of adding some sort of `import` face (may need better name suggestions), which would highlight the keyword(s) of a language that performs the module importing (e.g. `#include` or `require( )`).

**Comment by mawww** [comment]
This has been fixed.
