### ISSUE TITLE
Customize informative message

### ISSUE THREAD

**Issue by antoyo** [mawww/kakoune#1187]
Hello.
I use the bépo keyboard layout and I noticed that changing the bindings won't change the info (doc) messages.
For instance, with the following:
```kak
map global g c h
unmap global g h
```
The message for `goto` will still show:
```
h: line begin
```

 (and, by the way, the `gh` binding will still be active: is it normal?)

Thanks to fix this issue.

**Comment by ekie** [comment]
Hello,

the info message will display only the defaults that are hardcoded (those keys cannot be unmapped) in   

https://github.com/mawww/kakoune/blob/master/src/normal.cc#L114.

regarding an updated info there are several open issues. have a look @ #1165

**Comment by mawww** [comment]
This is now doable using maps docstrings.
