### ISSUE TITLE
Kakoune does not reset the shell colors correctly

### ISSUE THREAD

**Issue by antoyo** [mawww/kakoune#1188]
Hello.

I have an issue with the fish shell (I don't know if this affects other shells).

After I exit kakoune, the colors are messed up.

For instance, the fish shell colors the command in blue.
But, if I start kakoune, scroll down with `<C-d>`, then exit it, the commands (including the previous ones) will be colored in grey.

Thanks to fix this issue.

**Comment by lenormf** [comment]
This has been an ongoing issue that might hard to fix, it has been somewhat mitigated in the commit that closed #327.

**Comment by mawww** [comment]
Hello,

We try to restore the color palette on exit using the OSC 104 escape sequence. It is possible the terminal you use does not support it. The best fix would be to get support for palette restore in the terminal.

You can as well add `ncurses_change_colors=false` to `ui_options` to prevent Kakoune from touching the palette.

What terminal are you using ? AFAIK rxvt-unicode supports palette changing but not palette restoration.

**Comment by antoyo** [comment]
I use `rxvt-unicode`.

**Comment by mawww** [comment]
We cannot do much on Kakoune side here, the solution would be to add support for palette restoring to rxvt-unicode, or to disable palette changing on Kakoune (with `ncurses_change_colors=false`).
