### ISSUE TITLE
Option to disable the mouse

### ISSUE THREAD

**Issue by antoyo** [mawww/kakoune#1191]
Hello.
It would be nice to have an option to disable the support for the mouse.
Thanks to add this.

**Comment by ekie** [comment]
Hej,

the mouse support is disabled by default and you would need to enable it explicitly with 
`set global ui_options ncurses_enable_mouse=true`. check your config file, maybe you enabled it by accident. to disable `set global ui_options ncurses_enable_mouse=false`

**Comment by antoyo** [comment]
It seems to be enabled by default.
Anyway, adding this line in my kakrc fixed the issue.
Thanks.

**Comment by sgraf812** [comment]
According to https://github.com/mawww/kakoune/issues/4372#issuecomment-925461815, it's 

```
set -add global ui_options terminal_enable_mouse=false
```

now. E.g., `terminal`, not `ncurses`.
