### ISSUE TITLE
Add toolsclient handling for lint.kak

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1194]
Hi

Currently errors and warning are displayed in the gutter of the current buffer with associated info bubbles which is great.
But unfortunately there's no way to see the full list of errors in a glimpse.

So kakoune could display this jumpable list in another buffer in a toolsclient, like grep.kak does it. (and syntastic or neomake on vim)

I'll probably implement it soon and propose a PR. I create this issue first to see if anyone already made has this kind of solution.

**Comment by mawww** [comment]
This is already available, although the buffer does not get displayed automatically. When you lint, you'll get the output from the linter in the `*lint-output*` buffer, with filetype set to `make`, so it will be a jumpable list.

**Comment by lenormf** [comment]
I thought this was more about having the errors in `%opt{toolsclient}` than having errors listed in the lint buffer, isn't it?

**Comment by lenormf** [comment]
Was the answer questioned? I think `*lint-output*` was what was requested, so we can probably close this issue.

**Comment by Delapouite** [comment]
My problem is not totally solved, but I'm gonna close this thread for now to reduce the noise.

My remaining issue is that `*lint-output*` appears when I cycle through buffers with `:buffer-next`. It could be treated like the `*debug*` buffer.

**Comment by Delapouite** [comment]
Ref: -debug flag added in https://github.com/mawww/kakoune/commit/a0b42323ed4de19ca38d24c25134f7c86c47bba2
