### ISSUE TITLE
Make it possible to remap a sequence of keys

### ISSUE THREAD

**Issue by kmicklas** [mawww/kakoune#1196]
A common configuration I have grown to love in vim is mapping 'jk' to escape in insert mode, but `:map` seems to only accept one key.

**Comment by ekie** [comment]
hello,

there is https://github.com/mawww/kakoune/wiki/Avoid-the-escape-key.

**Comment by Delapouite** [comment]
Hi

For map nesting you can also use `on-key` as described here : https://github.com/mawww/kakoune/wiki/Implementing-user-mode

**Comment by mawww** [comment]
Hopefully the given doc are sufficient. Closing.
