### ISSUE TITLE
Weird artifacts in tooltip/clippy when running on Mac OS

### ISSUE THREAD

**Issue by phreeza** [mawww/kakoune#1198]
I installed kakoune via homebrew, and get this weird behaviour when clippy pops up. Looks like an ecoding issue but it happens in both iTerm and Terminal.app, which has the default settings I think.
![screen shot 2017-02-08 at 22 18 25](https://cloud.githubusercontent.com/assets/123894/22757809/8ebd38d0-ee4c-11e6-86e2-c58c4202cece.png)

**Comment by lenormf** [comment]
What is your version of ncurses, does it have unicode support enabled, and does the same thing happen with a different terminal?

**Comment by phreeza** [comment]
I installed ncurses from homebrew, it is 6.0.2 though i am not 100% sure the kakoune build was performed against that, does it have to be given explicitly? I did not enable unicode support explicitly when installing ncurses, do I have to? Same thing happens for both the system terminal and iTerm.

**Comment by casimir** [comment]
The makefile should take care of ncurses for you and use the homebrew version. If the mouse support  is working (e.g.: scrolling up/down) then you're using ncurses 6.
Does it happen with the buffer's content or just the info box? Also what are the outputs for `echo $TERM` and `locale`?

**Comment by casimir** [comment]
Ok I could reproduce a non existing language code can provoke this.
```
LANG=nope kak
```
@phreeza can you try with a `LANG` that exists on your system?

**Comment by phreeza** [comment]
My LANG was indeed misconfigured (en_EN.UTF-8, which as far as I can tell
isn't even a thing) Setting to en_US.UTF-8 did the trick. Thanks!

**Comment by lenormf** [comment]
How did that variable come to be misconfigured? Did you modify it yourself, or was it set automatically to that by the system?

**Comment by phreeza** [comment]
I set it myself. I believe what happened is that it was originally de_DE,
and i just guessed the English version as en_EN and set manually it in my
.zshrc...
