### ISSUE TITLE
Is there a forum for nooby questions, or just the issue tracker?

### ISSUE THREAD

**Issue by bclinthall** [mawww/kakoune#1199]

**Comment by alexherbo2** [comment]
There is no forum, but you can catch the community instantly on [IRC][].

[IRC]: irc://chat.freenode.net/kakoune

**Comment by bclinthall** [comment]
Thanks.  I see now that there is mention of IRC in the introduction to the README.asciidoc, though honestly I didn't know what IRC was.  Connecting to IRC, I now also see that there is a subreddit https://www.reddit.com/r/kakoune/ .  It would have been helpful to me if there were a "Questions and Comments" item in the README table of contents that listed those two resources.  Thanks for your help!

**Comment by Delapouite** [comment]
I've added the reddit link in the header of the [wiki](https://github.com/mawww/kakoune/wiki) main page for easier reach.

**Comment by mawww** [comment]
I believe this has been answered. Closing.
