### ISSUE TITLE
Is there a way to search by regex and replace replace using backreferences?

### ISSUE THREAD

**Issue by bclinthall** [mawww/kakoune#1200]
Say I want to replace every series of digits followed by period than whitespace with the same series of digits followed close parenthesis and same whitespace.
search `(\d+)\.(\s)`
replace `\1\)\2`
Can't find a way to get this to work in kakoune.
I'd post this in a q and a forum for kakoune if I could find one.

**Comment by alexherbo2** [comment]
After getting your selections with `s`, you can `c` and access to captures using `<c-r>` `[0-9]` in insert mode.

**Comment by bclinthall** [comment]
Awesome.  That's really powerful.

**Comment by danr** [comment]
I find less and less need for capture groups in Kakoune. Here's an outline to do this without them:

 * select all `\d+\.\s` (for instance using `%s`),
 * select the dot in these selections: `s\.<ret>` or `<a-f>.;`
 * replace it: `r)`
