### ISSUE TITLE
Display last entry from prompt history

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1204]
Even after knowing, I’m still surprised to see nothing in the search prompt while Kakoune reusing the last search.

Could be nice to shadow the last entry like [fish][] does.

[fish]: https://github.com/fish-shell/fish-shell

**Comment by Delapouite** [comment]
I think this issue can be closed now that https://github.com/mawww/kakoune/commit/9a449a33446f1c52bb02b4bea13bbc86d5742f2d has landed.
