### ISSUE TITLE
Execute command as prompt gets filled

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1209]
Similar to how incremental search works, it would be nice if the `prompt` command would let you specify a command to be executed everytime the user types something in the prompt. 

My use-case is to make this particular binding more interactive:
`def search_add %{ prompt 'search add:' %{ exec -save-regs '' ':reg / '%val{text}'<ret>N' } }`
whose purpose is to make heterogenous selections easier.

**Comment by mawww** [comment]
Here you go.

**Comment by occivink** [comment]
Thank you, that was... prompt.

**Comment by alexherbo2** [comment]
XD

**Comment by occivink** [comment]
Either I'm misunderstanding how it works or there's something wrong, but this
```
prompt -on-change %{ exec d } 'test' %{ echo a }
```
(or any `-on-change` command using exec) spits out a lot of errors.

**Comment by mawww** [comment]
You get an error because you are recursively triggering the on-change command by doing `exec d` which results in inserting a `d` in the edited text. The error you see is the maximum nested command depth limit getting hit.

**Comment by occivink** [comment]
Why would that be recursive though? `-on-change` applies to changes in the prompt right? Besides the same happens when you don't modify the buffer, for example with `exec y`, `exec /abc<ret>`, ...
