### ISSUE TITLE
Cannot set or save numeric registers

### ISSUE THREAD

**Issue by stevenyvr987** [mawww/kakoune#1214]
The following two examples work (kak quits silently) for an alphabetic register.

kak -n -e 'reg x 1; quit'
kak -n -e 'eval -save-regs x quit'

but the following two examples do not work for a numeric register.

1. kak -n -e 'reg 1 1; quit'

Status line says, 'this register is not assignable'.
It would be useful if numeric registers can be manually set, for example, restoring search capture values from the previous session.

2. kak -n -e 'eval -save-regs 1; quit'

kak aborts with the message 'terminated by signal SIGABRT (Abort)', and kak -l lists a dead session.
I'm not a c++ programmer and so can't offer a fix.

**Comment by mawww** [comment]
The crash should be fixed, for the assignment support, its a bit tricky, because the numeric registers are bound to the selections. I am looking at how we can approach that problem.
