### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by ekie** [mawww/kakoune#1215]
assert failed "std::is_sorted(begin, end, compare_selections)" at selection.cc:79
[Debug Infos]
pid: 19872
callstack:
kak(Kakoune::Backtrace::Backtrace()+0x2b) [0x825d1b]
kak(Kakoune::on_assert_failed(char const*)+0x24) [0x94fc14]
kak() [0x893548]
kak(Kakoune::compute_modified_ranges(Kakoune::Buffer&, unsigned long)+0x191) [0x88f459]
kak(Kakoune::undo(Kakoune::Context&, Kakoune::NormalParams)+0x96) [0x82c581]
kak(Kakoune::InputModes::Normal::on_key(Kakoune::Key)+0x777) [0x8f3517]
kak(Kakoune::InputMode::handle_key(Kakoune::Key)+0x42) [0x8f1cb6]
kak(Kakoune::InputHandler::handle_key(Kakoune::Key)+0x1f8) [0x8f05ac]
kak(Kakoune::Client::process_pending_inputs()+0x425) [0x8ac713]
kak(Kakoune::ClientManager::process_pending_inputs() const+0x59) [0x95c319]
kak(run_server(Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, bool, bool, bool, UIType, Kakoune::ArrayView<Kakoune::StringView const>)+0x92a) [0x786d0b]
kak(main+0x210e) [0x78a9a5]
/usr/lib/libc.so.6(__libc_start_main+0xf1) [0x7f15c12d6291]
kak(_start+0x2a) [0x71693a]

**Comment by lenormf** [comment]
Could you please unmangle this stacktrace, and try to give instructions about how to reproduce the issue?
