### ISSUE TITLE
having "exec" in "prompt -on-change" pushes keys to the prompt

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1217]
... recursively triggering itself. This limits the usability of the switch.

If possible, it would be preferable for the -on-change command to apply to the buffer directly.

**Comment by Delapouite** [comment]
```
:prompt foo nop -on-change boom
```
Then `<ret>`  -> error message in status `'prompt' boom : no such command`
Then `<left>` -> crash with
```
uncaught exception (N7Kakoune17command_not_foundE):
boom : no such command
```
