### ISSUE TITLE
Specifying several -groups for hook ignores all but the first

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1219]
I noticed this when I wanted to put a hook in several groups, so any rmhooks would remove it.  Look at:

    hook global -group first -group second NormalKey .* %{info woohooo}

The command is accepted, but the hook is only in group `first`.

**Comment by lenormf** [comment]
Your usecase looks like the symptom of a design flaw, why do you need two groups for a single hook ?

**Comment by danr** [comment]
I use one group, `kakrc`, which I remove all hooks from before reloading kakrc. I wanted to add another group here, `whitespace_trimming_pre_bufwrite` to remove when I needed it.

Note that I'm not really proposing here that it should be possible to have hooks in several groups, but it would expect an error to be thrown if it is not supported.

**Comment by lenormf** [comment]
I see.

Another behaviour could be to document that the first group passed has the priority over all subsequent ones, which is what seems to be happening.
