### ISSUE TITLE
Removing the parent directory of an open file kills file completion

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1229]
Hi,

Steps to reproduce the issue:

```
 mkdir t && kak t/a
:cd t; write
^Z
rm -r t && mkdir t && echo > t/a
fg
```

After hitting the return key to refresh the contents of the buffer, I don't get any file completion on `edit`.

Note that this will happen only if the instance of `kak` was within the directory that got removed.

HTH.

**Comment by mawww** [comment]
So, whats happening here is that the current directory of Kakoune is still the previous `t`, removing and recreating a directory with the same name did not magically move Kakoune to the new directory. It happens that, as this directory has been removed from the filesystem, it is empty (not even containing . or ..).

We could try to outsmart the kernel and pretend we actually are in the newly created directory, but I am not convinced its worth it. Besides, seems you'll get the same behaviour in the shell:

```
$ mkdir t   
$ cd t
$ touch a
$ ls
a
$ rm -r ../t
$ ls
$ mkdir ../t
$ touch ../t/a
$ ls
$ cd ../t  
$ ls
a
```

**Comment by lenormf** [comment]
Makes sense, however when I resume the client, refresh the buffer contents and write it, the newly created `a` is overwritten, however I still can't explore the current directory. So there seems to be a discrepancy there, I can write the file tp the new inode even though the client is apparently still in the old one?

**Comment by lenormf** [comment]
I guess the full path to the file is used when saving a buffer, even when the buffer's name is only a basename. Either way, no need to do anything about this.
