### ISSUE TITLE
Value of a numeric register appears to be lost after moving the cursor

### ISSUE THREAD

**Issue by stevenyvr987** [mawww/kakoune#1231]
The following three working examples will set an alphabetic or numeric register and then echo its value on the status line.

```
kak -n -e 'reg a a;                   echo %reg[a]' # value a shows
kak -n -e 'reg 1 1;                   echo %reg[1]' # value 1 shows
kak -n -e 'exec i1<esc> /(1)<ret>;    echo %reg[1]' # value 1 shows
```
If the cursor is moved, for example, using 1g, before trying to echo, then the value for the numeric register appears to be lost and nothing shows up on the status line.
```
kak -n -e 'reg a a;          exec 1g; echo %reg[a]' # value a shows
kak -n -e 'reg 1 1;          exec 1g; echo %reg[1]' # no show
kak -n -e 'exec i1<esc> /(1)<ret> 1g; echo %reg[1]' # no show
```
It doesn't appear the problem is related to using the reg command for a numeric register, but to something inherent to its inner workings.

**Comment by mawww** [comment]
Numeric registers are capture groups values, they are linked to the selection itself, basic movements are conceptually mutating a selection, so they preserve the capture groups, but jumping around with `g` is treated like replacing the selections with a new one, and the capture groups are not preserved.

**Comment by stevenyvr987** [comment]
OK, I get it, I think.

Thinking out loud, so a numeric register will remember the selection range of a search capture rather than the text behind the selection. If I want to use the initially captured text without worrying about future cursor movements, I could capture the initial text in a non-numeric register, for example.

**Comment by lenormf** [comment]
Can this issue be closed now?

**Comment by stevenyvr987** [comment]
Yes, I'll do it, although I think an edited version of mawww's comment could be added to the docs for clarification.
