### ISSUE TITLE
selection commands should filter selections that don’t match the object

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1240]
Similar behaviour than `keep` and `select` commands.

**Comment by lenormf** [comment]
Do you have an example?

**Comment by occivink** [comment]
@lenormf object selection is sometimes a noop (for example, `<a-i>b` when not within parentheses) and it could be argued that instead of a noop it should filter out the non-successful ones (and consequently fail when no selections succeeded)

**Comment by alexherbo2** [comment]
Yep, similar behaviour than `keep` and `select` commands.

**Comment by lenormf** [comment]
I think this was fixed in cc88b0f5861254cd9a95e7289f843e68fb7edbc1.

**Comment by mawww** [comment]
Yep thats right.
