### ISSUE TITLE
Search matching across multiple lines

### ISSUE THREAD

**Issue by leira** [mawww/kakoune#1254]
When I use '/' to search some pattern, say "void.*\)", meant to match a void function signature, kakoune matched starting from the first 'void' to the last ')' in the document, which almost matched the whole document.

Is it a designed behavior, or is it a bug? If it's a designed behavior, how do I limit the match only inside the lines? My kakoune was built from master branch on 3/3/2017.

**Comment by lenormf** [comment]
It's by design, search isn't supposed to be arbitrarily limited to lines, so `.+` will include newline characters. Use `[^\n]+` to search within a line, or use the non greedy version of your pattern for the prototype: `.+?\)`.

**Comment by danr** [comment]
You can also search within each selection using `s`. So you could select the whole line with `x` and search in it: `xsvoid.*\)<ret>`.

**Comment by maximbaz** [comment]
Should this issue be closed?
