### ISSUE TITLE
Use 'jk' to exit insert mode

### ISSUE THREAD

**Issue by palango** [mawww/kakoune#1255]
I'm used to use `jk` to exit insert mode in vim.
[](url)
I found [this code](https://github.com/mawww/kakoune/wiki/Avoid-the-escape-key) for using `jj`
```
hook global InsertChar j %{ try %{
  exec -draft hH <a-k>jj<ret> d
  exec <esc>
}}
```

However, changing `jj` to `jk` there doesn't work. Any hints are appreciated.

**Comment by alexherbo2** [comment]
Hook on `k` instead of `j`.

**Comment by palango** [comment]
Thanks, I added it to the wiki as well.
