### ISSUE TITLE
Building Kakoune on os X after installing dependencies with macports

### ISSUE THREAD

**Issue by guillaumecherel** [mawww/kakoune#1261]
Related to issue #974, I installed all kakoune's dependencies with macports, and had the error when running make that "boost/regex.hpp" couldn't be found. It worked fine after editing the Makefile like so: 

    ifeq ($(os),Darwin)
        LIBS += -lncurses -lboost_regex-mt
        CPPFLAGS += -I$(PREFIX)/opt/ncurses/include -I$(PREFIX)/opt/boost/include -I/opt/local/include
        LDFLAGS += -L$(PREFIX)/opt/ncurses/lib -L$(PREFIX)/opt/boost/lib -L/opt/local/lib

**Comment by lenormf** [comment]
Hi,

Could you please create a pull request instead, so we can easily see what was changed in the file and facilitate the introduction of your fix into the codebase?

Thanks.

**Comment by guillaumecherel** [comment]
I just did that. My first pull request, hope I did things right.

**Comment by mawww** [comment]
Thanks.
