### ISSUE TITLE
Gitter, irc, matrix channel?

### ISSUE THREAD

**Issue by dpc** [mawww/kakoune#1266]
Hi,

Is there any place for people to discuss interactively and seek help about kakoune?

**Comment by danr** [comment]
Yes! Chat with us at `#kakoune` at `irc.freenode.net`!

**Comment by dpc** [comment]
It could be advertised somewhere at the top of README, BTW. I think building community is of the top importance for a project like Kakoune.

**Comment by ekie** [comment]
It is mentioned in the introduction https://github.com/mawww/kakoune#1-introduction. Do you have something else in mind ?

**Comment by dpc** [comment]
The README of Kakoune is awesome  - very informative etc, but it's a long wall of text. People like me, newcomers, are lazy, distracted and just curious. Before filling the ticket, I did ctrl+f on `chat` and `gitter`, and failed to do it on `irc`.

Personally on my projects I display a badge at the very top, next to build status. [example](https://github.com/dpc/rdedup). I think IRC is fine, as long as you link to some webirc. Basically the same thing applies as in sales/marketing: the easier it is, the higher the retention, the more people eventually reach it, the easier it is to get the community to roll by itself and have a functional self-help group.

For this reason I prefer gitter, as it keeps history and preservers communication through session. Someone might be browsing hackernews at lunchbreak, gets in, asks couple of questions, noone responds in time, the person is gone. With gitter, they can check after a day or two, and there might be a notification for them with an answer. From my perspective, after I discovered Matrix and it's IRC and gitter integration the difference between IRC and Gitter got a little smaller.

The above are all just my opinions. See you on irc channel at some point!

**Comment by ekie** [comment]
the idea to point to a webirc is nice, since irc is unfortunately not that well known anymore and this lowers the barrier. if you have the time mayb you can come up with a pullrequest.

recently i saw a irc<->gitter bridge, that might be an option for the future too
