### ISSUE TITLE
`<c-h>` to work in normal mode.

### ISSUE THREAD

**Issue by dpc** [mawww/kakoune#1270]
dpc 20:15 Any idea why map global normal '<c-h>' ':buffer-previous<ret>' doesn't work, while map global normal '<c-l>' ':buffer-next<ret>' is fine?
ironzorg 20:50 dpc: <c-h> is a special key isn't it ; https://github.com/mawww/kakoune/commit/37fbe6c6ebe57357d61aad3f6a7e2ae482bb9e5e
ironzorg 20:54 maybe you should open an issue, because I'm not sure we're interested in having that translation done in normal mode, only in insert mode

**Comment by Delapouite** [comment]
The keys have been eaten by GitHub markdown. The discussion is about `<c-l>` versrus `<c-h>`

**Comment by lenormf** [comment]
```
     dpc | Any idea why `map global normal '<c-h>' ':buffer-previous<ret>'` doesn't work, while `map global normal '<c-l>' ':buffer-next<ret>'` is fine?
ironzorg | dpc: <c-h> is a special key isn't it
ironzorg | https://github.com/mawww/kakoune/commit/37fbe6c6ebe57357d61aad3f6a7e2ae482bb9e5e
ironzorg | maybe you should open an issue, because I'm not sure we're interested in having that translation done in normal mode, only in insert mode
```

There we go!

**Comment by mawww** [comment]
Thats not something we can handle on a mode by mode basis, its a limitation of terminal input, in the terminal `<backspace>` sends `<c-h>`. We cannot fix that ourselves, the problem is that we receive a `<c-h>` and we need to interpret it as `<backspace>`. Non-terminal UIs wont have this problem.

**Comment by danr** [comment]
You can still bind `<c-h>` in normal mode by binding `<backspace>`, like this:

    map global normal <backspace> :buffer-previous<ret>

**Comment by dpc** [comment]
How does it work in Vim then? I have the same mappings in Vim...

**Comment by mawww** [comment]
Does vim manage to distinguish between you hitting `<c-h>` and you hitting `<backspace>`

**Comment by dpc** [comment]
Just checked, and yes. `<c-h>` switches to previous buffer in my setup, but hitting backspace does not. It's actually neovim, run in terminal to be precise.

**Comment by mawww** [comment]
neovim uses libtermkey for input, and this, combined with a supporting terminal, can make it possible to distinguish the two keys. I did not know we have in the wild terminals that do support this input scheme, can you tell me which one you are using ?

We could eventually fix that by moving away from ncurses to handle input handling, which would probably mean rolling our own terminal input parser.

**Comment by dpc** [comment]
I've just checked in standard Vim, and it works the same.

I am using `gnome-shell` if that's what you're asking about.

**Comment by mawww** [comment]
Hum, now I am a bit confused, `<backspace>` *is* `<c-h>` in ascii. IIRC depending on the terminal, the actual backspace key might generate the delete char or the backspace char. According to #1030 I added that pretty recently to fix an issue for a user that had his backspace key generate `<c-h>`.

So yeah, now I am not sure what the correct handling should be, it seemed reasonable to treat `<c-h>` as backspace on terminals as ascii says they are the same, but if we can distinguish the two it would be pretty nice as well.

**Comment by dpc** [comment]
Isn't stuff like that described in terminfo/termcap? In #1030 it was putty used, so maybe `TERM` was not correctly set or something.

The world of terminals is a scary place. :D

**Comment by lenormf** [comment]
>We could eventually fix that by moving away from ncurses

I think we have our topic for the next live stream.

**Comment by dpc** [comment]
For `<c-h>` terminal sends ascii sequence `Execute 08`, and for backspace just `0x7f` byte.
