### ISSUE TITLE
kak does not recognize a new tmux pane

### ISSUE THREAD

**Issue by stevenyvr987** [mawww/kakoune#1280]
I'm using kak in a tmux session.

If I split the screen by creating a new pane in the right-hand side and then try to focus on it, kak complains.
`kak -e 'new nc right; focus right'`
kak shows _**no client named 'right'**_. It appears the original kak client (the left pane) is not aware of the new client. But if I place myself in the left pane and type the focus command, completion shows 'right', and choosing it does place the focus in the right pane.

Another hint is if I echo the window width after creating the new pane:
`kak -e 'new nc right; echo %arg[window_width]'`
kak shows 168, which is the original width, but the pane is clearly half that. Again, if I place myself in the left pane, and type the same echo command, the corrent width is shown.

kak seems to be aware of the new state in interactive context, but not in a scripting context.

**Comment by lenormf** [comment]
Are you using `tmux` >= 2 ?

**Comment by mawww** [comment]
I think you just are witnessing a race, 'new nc right' will launch a tmux command that will create the new pane, and launch a new kakoune client, that will eventually connect to the server and claim the name 'right'. While that is happening, `focus right` gets executed on the server, and nothing is connected.

The solution is to run the `focus` command in the new client context, I think just escaping the `;` will work, as it will make the whole `nc right; focus right` taken as an argument to the `new` command and will get executed by the new client once connected.

**Comment by stevenyvr987** [comment]
lenormf, sorry should have clarified:
`tmux -V` gives 2.1

**Comment by stevenyvr987** [comment]
mawww, thanks for the simple explanation.

`kak -e 'new nc right\; focus right'` does work, in that no error message is shown and focus is on the right.

`kak -e 'new nc right\; echo %arg[window_width]'` still doesn't, in that a width of 168, whereas 84 is expected, shows on the right status line. Is there something else going on besides a race?

For now, I'm putting most commands that needs done on the right pane in a kak function and then passing it into the `new` command, eg, `kak -e 'new nc right\; do_right'`, where `do_right` is the function doing everything that needs done in the right context. 

A more general use case for me will involve three or four panes that are created dynamically; I'll see how far I get before I run into trouble. Trouble might arise if there are cross-pane dependencies, for example, pane 1 actions needing properties of pane 2, but pane 2 is still being created.

**Comment by lenormf** [comment]
I'm not sure this issue should be closed, are we certain nothing can be improved on the editor's side to mitigate this asynchronization?

**Comment by mawww** [comment]
I dont see what we could be doing there, except for waiting for the client to be effectively connected before letting `new` return, but that would be both complex, and unneeded, as we already have a way to write the commands to run when the client connects.
