### ISSUE TITLE
Kill a subprocess that is reading from stdin

### ISSUE THREAD

**Issue by guillaumecherel** [mawww/kakoune#1281]
When doing (by mistake) `!fmt` in kakoune, I get a "waiting for shell command to finish" at the bottom of the screen, and I can't seem to get out of it. `Ctrl-C` doesn't kill the subprocess. I have to kill kakoune. I can kill another process that doesn't wait for stdin like `!sleep 10`.

**Comment by guillaumecherel** [comment]
Ok, after another attempt, it `Ctrl-C` seems to work but only sometimes. On certain attemps I can kill the subprocess at the first `Ctrl-C`, but most the time I have to do it multiple times before it works.
If it's relevant, I'm on os X using iTerm2 and fish as a shell.
I'm not sure we need to leave this issue open though.

**Comment by mawww** [comment]
`Ctrl-C` should send SIGINT to the process group immediatly, so if that does not work on the first try there might be something fishy going on. Would you have a good way to reproduce that ?

**Comment by guillaumecherel** [comment]
The best way I have to reproduce it is to start kak and type `!fmt`. Then try to type `Ctrl-C` and see if it works. It always works eventually, but usually not on the first try. I don't know how to reproduce it in a way that I can predict whether Ctrl-C will works or not.

**Comment by danr** [comment]
Can confirm using `!fmt`. Took about 60 presses of `C-c` to make it give up.
