### ISSUE TITLE
How do I map space to : ?

### ISSUE THREAD

**Issue by AnthonyJacob** [mawww/kakoune#1282]
I would love to use my space key as I do in spacemacs. However I were not able to do it even though I followed the pattern - I tried `:map global normal space :` but it didn't work. 

**Maybe some example in the readme would be useful, because the description isn't completely clear.**

**Comment by alexherbo2** [comment]
``` kak
map global normal <space> :
```

**Comment by AnthonyJacob** [comment]
Thank you!

By the way, is there some place where I could leave feedback on kakoune?

**Comment by alexherbo2** [comment]
There is no official place, but you can write a post and share it on a social network :p

**Comment by casimir** [comment]
@AnthonyJacob you could also visit the IRC channel for more discussions.
