### ISSUE TITLE
Auto-pairs functionality

### ISSUE THREAD

**Issue by BjornMelgaard** [mawww/kakoune#1284]
I want to add [auto-pairs functionality](https://github.com/jiangmiao/auto-pairs), specifically:
1. autoclosing brackets on insert
I have stumbled on ' and " 
```
hook global InsertChar \( 'exec )<left>'
hook global InsertChar \{ 'exec }<left>'
hook global InsertChar \[ 'exec ]<left>'
hook global InsertChar < 'exec ><left>'
hook global InsertChar ' "exec '<left>" # just dont work, without errors, I have tried \' too 
hook global InsertChar \" 'exec "<left>' # error running hook InsertChar(")/: parse error: unterminated string "..."
```
2. delete in pair
How to hook deleting?

**Comment by lenormf** [comment]
Try escaping the first `<` sign, and you can't hook on deletion.

**Comment by BjornMelgaard** [comment]
I think I better off with vim for now, but it was interesting experiment
Thanks anyway :smile:

**Comment by alexherbo2** [comment]
#1295

**Comment by alexherbo2** [comment]
@BjornMelgaard Does it work for you?

**Comment by BjornMelgaard** [comment]
@alexherbo2 [not exactly](https://asciinema.org/a/9q2sg2uzwxvqwy3gbfsr3cc05) :smile:

**Comment by BjornMelgaard** [comment]
And is it actually intended to make pairs to ' and " ?

**Comment by BjornMelgaard** [comment]
P.S. very soon I will get down to kakoune and will pester you how to make plugins :smile:

**Comment by alexherbo2** [comment]
Currently the implementation expects the opener and closer ones be different, but I will add support later.

(I just fixed `<>` :p)

**Comment by alexherbo2** [comment]
I added basic support for quotes

**Comment by bangkemono** [comment]
for those who are wondering, this code makes both quotes work _(at least for me)_. I know i'm super late, and this doesn't really have auto-delete and is very basic, but I hope this helps anyone

```
hook global InsertChar \( 'exec )<left>'
hook global InsertChar \{ 'exec }<left>'
hook global InsertChar \[ 'exec ]<left>'
hook global InsertChar < 'exec ><left>'
hook global InsertChar \" 'exec \"<left>' # double quotes
hook global InsertChar \' "exec \'<left>" # single quotes
