### ISSUE TITLE
How to select lines up?

### ISSUE THREAD

**Issue by BjornMelgaard** [mawww/kakoune#1285]
In order to select 3 lines down one shold do `3X`, how to do the same in up direction?
`2K<a-x>`? Too much keys

**Comment by lenormf** [comment]
That's the proper way. `x` doesn't have a simliar upward key because we generally don't need as often, so it didn't warrant make room on the keyboard for it. You can however bind whatever key you want to emulate this behaviour though.

**Comment by BjornMelgaard** [comment]
@lenormf, you have said that you generally dont select upward, rly? I select upward all the time, with same frequency as downward. And who is using current behavior of `x`? I know it consistent with `web` keys,  but rly, there must be better way. 
Tonight I came up with how I want to select lines in kakoune: make `x` behave like current `X` - select line if none selection or select downward if present, and `X` - select line if none or upward.
Consider this:
1. no selection
2. `x` - select line downward, 1 line selected
3. `2x` - append 2 lines downward, 3 lines selected
4. `2X` - append 2 lines upward, 5 lines selected, cursor now atop.

@lenormf  @mawww  ?

**Comment by alexherbo2** [comment]
``` kak
def -hidden -params 1 extend-line-down %{
  exec "<a-:>%arg{1}X"
}
```

``` kak
def -hidden -params 1 extend-line-up %{
  exec "<a-:><a-;>%arg{1}K<a-x>"
}
```

``` kak
map global normal x ":extend-line-down %val{count}<ret>"
```

``` kak
map global normal X ":extend-line-up %val{count}<ret>"
```

**Comment by BjornMelgaard** [comment]
@alexherbo2 nice, you have made my day, kudos)

**Comment by BjornMelgaard** [comment]
@alexherbo2 I have another one insane idea: made `web` keys discern CamelCase and underscore notation by default, so usually when you move - you distinguish CamelCase, but when you want select word - you select it like textobject
[Actually I have this feature in my vim and I have never regreted the day when I made this](https://github.com/BjornMelgaard/dotfiles/blob/master/nvim/init.vim#L359-L371)

**Comment by alexherbo2** [comment]
``` kak
def -hidden select-next-word %{
  exec /[A-Z][a-z]+|[A-Z]+|[a-z]+|(?<lt>=_)[a-z]+<ret>
}
```

``` kak
def -hidden extend-next-word %{
  exec ?[A-Z][a-z]+|[A-Z]+|[a-z]+|(?<lt>=_)[a-z]+<ret>
}
```

``` kak
map global normal w :select-next-word<ret>
```

``` kak
map global normal W :extend-next-word<ret>
```

**Comment by BjornMelgaard** [comment]
@alexherbo2 , ahahahhh, you genius)) :heart:

**Comment by BjornMelgaard** [comment]
@alexherbo2 , I think we must put your answers to wiki

**Comment by alexherbo2** [comment]
Yep can you add them? :p

**Comment by BjornMelgaard** [comment]
I put it in How to
Doesnt know that I can)

**Comment by BjornMelgaard** [comment]
@alexherbo2 , finally I have tried your scripts))
In extending line script I wanted X to select line like x if none selection or select up if selection exists. Here is result (oh, god, I love that)

```
def -params 1 extend-line-down %{
  exec "<a-:>%arg{1}X"
}
def -params 1 extend-line-up %{
  exec "<a-:><a-;>%arg{1}K<a-;>X<a-;><a-X>"
}

map global normal x ':extend-line-down %val{count}<ret>'
map global normal X ':extend-line-up %val{count}<ret>'
```
but there is error: if lines are containing only newlines - it will select  up and down simultaneously, can you help me with that?

2. And CamelCase motions.....well, it can wait

**Comment by alexherbo2** [comment]
``` kak
try %{
  exec '<a-K>\n<ret>'
  exec '<a-x><a-:><a-;>'
} catch %{
  exec <extend-line-up>
}
```

**Comment by BjornMelgaard** [comment]
```
def -params 1 extend-line-up %{
  try %{
    exec <a-K>\n<ret>
    exec <a-x><a-:><a-\;>
  } catch %{
    exec "<a-:><a-;>%arg{1}K<a-;>X<a-;><a-X>"
  }
}

```
Is that what you mean? I mean like in [this video](https://asciinema.org/a/7v3wrsgy2n5q0024nf0awn43b), if I am on new line it will select in both directions. This snippet is working the same(

**Comment by alexherbo2** [comment]
Nope remove the `X`, etc. commands

The command tries to detect if we are selecting new line to have same behaviour than `x`

**Comment by alexherbo2** [comment]
I updated the command

**Comment by BjornMelgaard** [comment]
Wow, awesome, I have got it, its beautiful

**Comment by BjornMelgaard** [comment]
```
def -params 1 extend-line-down %{
  exec "<a-:>%arg{1}X"
}
def -params 1 extend-line-up %{
  try %{
    exec <a-K>\n<ret>
    exec <a-x><a-:><a-\;>
  } catch %{
    exec "<a-:><a-;>%arg{1}K<a-x>"
  }
}

map global normal x ':extend-line-down %val{count}<ret>'
map global normal X ':extend-line-up %val{count}<ret>'
```

You have forgotten count)))

**Comment by alexherbo2** [comment]
``` kak
def -params 1 extend-line-down %{
  exec "<a-:>%arg{1}X"
}
```

``` kak
def -params 1 extend-line-up %{
  exec "<a-:><a-;>%arg{1}K<a-;>"
  try %{
    exec -draft ';<a-K>\n<ret>'
    exec X
  }
  exec '<a-;><a-X>'
}
```

``` kak
map global normal x ':extend-line-down %val{count}<ret>'
```

``` kak
map global normal X ':extend-line-up %val{count}<ret>'
```

**Comment by evadknarf** [comment]
this should be the default mapping!

**Comment by evanrelf** [comment]
Hi there 👋

I just finished an initial version of a plugin I'm calling `expand-line.kak`, which rebinds `x` and `X` to drag the cursor up and down, line-by-line.

**https://github.com/evanrelf/expand-line.kak**

- You can mash `x` a bunch of times to select lines downwards, and then hit `X` to retract your selection by a line if you go too far.
- Continuing to hit `X` will cause the selection to go from shrinking from below to growing from above.
- You can use numeric prefixes, e.g. `5x` works.
- Multiple selections are supported.

There may be certain edge cases I haven't discovered yet, but in my initial testing and development it's worked great. Feel free to report issues if you run into any.
