### ISSUE TITLE
Feature request - Elixir

### ISSUE THREAD

**Issue by gregpardo** [mawww/kakoune#1287]
Pretty popular language. Syntax is similar to ruby so that might be a good starting point. 

See elixir erlang parser starting point. 
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_parser.yrl

How does one go about testing syntax when creating the kak file?

**Comment by net** [comment]
https://github.com/elixir-lang/vim-elixir/tree/master/syntax

https://github.com/elixir-lang/elixir-tmbundle/tree/master/Syntaxes

**Comment by mawww** [comment]
Hello,

I'll be happy to merge a support file for Elixir highlighting, however as I dont use Elixir myself I wont be trying to write that, as I could not even check its usefulness.

**Comment by zambal** [comment]
I just submitted a pull request for a Elixir code highlighting here #1350

**Comment by igaray** [comment]
Since @zambal 's PR was merge this issue can be closed.

**Comment by igaray** [comment]
Since @zambal 's PR was merge this issue can be closed.
