### ISSUE TITLE
Poor discoverability of aliased commands

### ISSUE THREAD

**Issue by jockus** [mawww/kakoune#1290]
In relation to #817, all aliased commands are no longer shown or autocompleted. You now have to go through the various kak scripts to discover what aliases have been set up.
Would it be a good idea to perhaps combine the aliases with whatever command they point to, and still allow them to be autocompletable?

For example, tmux-repl-horizontal is aliased to repl when running under tmux.

:rep<tab>
could display
repl->tmux-horizontal-repl   x11-repl   tmux-vertial-repl   etc.

With the -> signifying that it is an alias. Both tmux-horizontal-repl and repl should be auto-completable.

**Comment by lenormf** [comment]
Aliases are convenience shortcuts for longer commands, so once you've found the command you need, look at the info box that pops up (if you haven't deactivated it), and the alias for that command will be shown.

I don't see the point in having a way of knowing all the aliases that point to actual commands, as they are prone to change according to the context (e.g. `new` or `focus`).

**Comment by jockus** [comment]
Oh, didn't notice the alias box in the commands! That makes the discoverability issue better, but still won't let them be autocompleted.

**Comment by casimir** [comment]
IMHO fuzzy autocompletion defeats the purpose of aliases. At least for the existing ones, an alias is usually so short the autocompletion ranking isn't really helping.

**Comment by mawww** [comment]
Its a tricky problem to get right, our current decision is that aliases are better left uncompleted, they are supposted to be short and easy to type anyway, and they tend to clutter the completion.

**Comment by jockus** [comment]
I'm closing the issue - didn't realise the aliases were displayed with each command.
