### ISSUE TITLE
Have a completion scope for mappings

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1293]
Hi,

It was recently asked on IRC how to make it so the `<tab>` key could be used to cycle through completion candidates, and I came up with the following:

```
hook window InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <backtab> <c-p>
}

hook window InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <backtab> <c-p>
}
```

Even though the above works, it feels a bit lame as having a scope dedicated to the completion menu would have been more convenient (or am I missing something?).

Thanks.

**Comment by casimir** [comment]
I also use this and stole it from @mawww https://github.com/mawww/config/blob/master/kakrc#L81.

**Comment by lenormf** [comment]
After looking at how completions are implemented, I'm thinking that the current way is not that bad, I'm considering closing the issue.

**Comment by mawww** [comment]
A completion mapping scope would be introducing some kind of 'sub modes' which looks overly complex, so I think for now the current solution is ok.
