### ISSUE TITLE
Execute shell command with arguments in `!`

### ISSUE THREAD

**Issue by mna** [mawww/kakoune#1297]
Hello,

Not sure if this is a bug or misunderstanding on my part, if I manually do this in a kak buffer it works fine (to insert the listing of files in the buffer):

`!ls -a<ret>`

However, in the following function, `ls -a` does not work as expected (doesn't produce any output in the buffer), while using only `ls` works (file listing inserted in the buffer). Any flag added to the `ls` command makes it fail.

```
# implement directory listing
def -hidden -params 0 list_directory %{
  # list directory in a scratch buffer named "*dir*"
  edit -scratch *dir*
  # make buffer read-only
  set buffer readonly true
  # list the content of the current directory
  exec !ls<ret> # <<<<< this works, but replacing "ls" with "ls -a" does not
  # move selection to top of file
  exec gk
}
```

Any idea what may be going on?

Thanks!
Martin

**Comment by lenormf** [comment]
By default `exec` and `eval` will remove the whitespaces of the arguments you pass them, unless they are quoted. In your case, writing `exec !ls -la<ret>` will in reality execute `ls-la` in the shell (there's probably an error in the `*debug*` buffer too).

To use commands that need spaces as separators, you can use a string, e.g. `exec "!ls -la<ret>"`.

**Comment by mna** [comment]
Awesome, thanks!
