### ISSUE TITLE
Command mode?

### ISSUE THREAD

**Issue by AnthonyJacob** [mawww/kakoune#1301]
Vi came with the idea of separating insertion and code manipulation into two distinct modes. 
What is even more important, the code manipulation commands can be composed together similar to sentences in natural language. That is such a powerful yet often underrated feature!

Now I am asking myself why is there nothing like that for editor commands (commands that follow `:`)? 
Is the domain so much different? Or did nobody think about it yet?

**Comment by Delapouite** [comment]
Hi, I think I understand what you mean but could your elaborate with 1 or 2 concrete examples to be sure?

**Comment by AnthonyJacob** [comment]
Say button `c` would bring you into command mode.

Letter `b` would stand for buffer and `w` for window `d` for destroy / delete.

Then by simply hitting `c b d (esc)` you would destroy the current buffer, similar for windows. Hitting `b` repeatedly would jump to next buffer similar `w` jumps to next word.

**Comment by alexherbo2** [comment]
You mean something like that?

``` kak
def -hidden command-mode %{
  info %{
    :: command
    b: buffer
  }
  on-key %{ %sh{
    case $kak_key in
      :) echo exec : ;;
      b) echo buffer-mode ;;
    esac
  }
}}
```

``` kak
def -hidden buffer-mode %{
  info %{
    n: next
    p: previous
  }
  on-key %{ %sh{
    case $kak_key in
      n) echo buffer-next ;;
      p) echo buffer-previous ;;
    esac
  }
}}
```

``` kak
map global normal : :command-mode<ret>
```

**Comment by jockus** [comment]
That is pretty much how spacemacs helm mode works. Leader key style sequences with good on screen info organised in structures aiding memorisation - <space>-f for all file related function like write, find, delete etc.

**Comment by jockus** [comment]
https://github.com/mawww/kakoune/wiki/Implementing-user-mode

Look at the spacefn section for a barebones example.

**Comment by lenormf** [comment]
There aren't enough keys on the keyboard to accomodate editing primitives and modes.

**Comment by leeola** [comment]
Note that i believe https://github.com/mawww/kakoune/issues/1303 impacts custom user mode. The `exec ':buffer<space>'` and etc commands don't bring prompts up, but they do if you bind them directly. So user mode seems a bit bugged atm if you like interactive prompts, fuzzy finding, etc.

**Comment by mawww** [comment]
While this looks like an interesting feature, I do not think we need to have it in Kakoune's core. Command mode commands tend to be used much more rarely than normal mode commands, and are usually more complex, so I think the existing fuzzy completion system is more adapted than a new single key command mode.

Additionally, I believe we have all the necessary building blocks to allow a script to provide such a mode.
