### ISSUE TITLE
Buffer-local definition of words, again

### ISSUE THREAD

**Issue by perpen** [mawww/kakoune#1304]
My last comment on #758 may have been missed.
Working with clojure with words like `my-little-function` or `:keyword` I am unable to use the native movement keys in a natural way.
I think the `completion_extra_word_char` option added via #758 should be rejigged into a proper buffer-local definition of words, which would be used for movement as well as completion.

**Comment by mawww** [comment]
Hello,

What does completion_extra_word_char not solve in this case ? for clojure buffers I'd expect it to be set as `:-` so that `:` and `-` are considered word characters as well. As any option it can be set on the window, buffer, or global scope.

**Comment by perpen** [comment]
If the cursor is at the beginning of `this-thing` then pressing `e` should move it to g, not s.
(Sorry for the long delay of my response, I don't do much work at home atm)

**Comment by perpen** [comment]
Why was this closed?

**Comment by Delapouite** [comment]
Because of the attached commit: https://github.com/mawww/kakoune/commit/f41d78083aa8d3883bcd4ed819e6784e09e69dba which is supposed to fix this issue. (havn't tried it myself yet)

**Comment by perpen** [comment]
Lovely! I'll be testing this shortly, Thanks Bruno
