### ISSUE TITLE
Line text object and unimpaired vim

### ISSUE THREAD

**Issue by BjornMelgaard** [mawww/kakoune#1305]
I want the line text object, so `<a-a>l` will select all characters inside line without end of line character, and `<a-i>l` will do the same without leading spaces

Also I want to `[b` and `]b` (for beginning) to make `buffer-previous` and `buffer-next` accordingly, but without rewriting of present keybindings

P.S. I have put this in same issue because it apply to textobjects, and, as I think, kakoune have limitations on that: you cannot make bindings to <a-i> and <a-a> without making it to [ and ], no?

**Comment by lenormf** [comment]
Those are too easy to implement by yourself to warrant adding them to default bindings.

**Comment by BjornMelgaard** [comment]
No, I didnot warrant to add them, I just didnt find anywhere how to do this
How to map to  `<a-a>l` something like `<a-h><a-l>` (or one textobj), to `<a-i>l` - `gi<a-l>` (or other) and not to add line text obj to [ and ]

And how to make `[b` and `]b` accordingly and not to change `<a-i>` and `<a-a>`

**Comment by danr** [comment]
You could make an `on-key` bound to `<a-a>` and `<a-i>` that executes what you write above on `l` and on any other key _k_ it runs `<a-a>`_k_ and `<a-i>`_k_, respectively.

**Comment by alexherbo2** [comment]
``` kak
def -hidden next-mode %{
  info -title Next %{
    b: buffer next
  }
  on-key %{ %sh{
    case $kak_key in
      b) echo buffer-next ;;
      *) echo $kak_key ;;
    esac
  }
}}
```

``` kak
def -hidden previous-mode %{
  info -title Previous %{
    b: buffer previous
  }
  on-key %{ %sh{
    case $kak_key in
      b) echo buffer-previous ;;
      *) echo $kak_key ;;
    esac
  }
}}
```

``` kak
map global normal ] :next-mode<ret>
```

``` kak
map global normal [ :previous-mode<ret>
```

**Comment by lenormf** [comment]
@BjornMelgaard consider joining IRC too if you want instant answers to your questions, and then create an issue if needs be.

#kakoune @ irc.freenode.org

**Comment by BjornMelgaard** [comment]
Ok, thank you all )
