### ISSUE TITLE
command argument are not self documented

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#131]

**Comment by mawww** [comment]
highlighters and options are documented automatically now.

**Comment by spelufo** [comment]
Is there a way to see the current value of an option, or the current mapping of a key?

**Comment by mawww** [comment]
Hello,

the value of an option can be easily displayed with `:echo %opt{option_name}`.

User mappings are not displayable, default mapping are explained if you put the autoinfo option to 2, where you'll get an info box explaining what the last hited key did.

**Comment by spelufo** [comment]
Thanks!
