### ISSUE TITLE
'map' Failed to parse <c-a-w>

### ISSUE THREAD

**Issue by BjornMelgaard** [mawww/kakoune#1311]
Want to make insert mode word movements compatible with prompt mode

`map global insert <c-a-w> <esc><a-w>\;i` throw error `'map' Failed to parse <c-a-w>`, but this movement works in command line fine

P.S. also noticed that `<c-a-b>` in command line dont work

**Comment by lenormf** [comment]
Multiple modifiers are not supported by the `map` command, it seems.

Other than that, I think you would be better off leaving insert mode and using the mappings already declared within than scope, than declare multiple modifier mappings in the insert mode.

**Comment by BjornMelgaard** [comment]
That's weird, because bindings with multiple modifiers exists in kakoune

I like my own [bindings](https://github.com/BjornMelgaard/dotfiles/blob/master/kak/bindings.kak#L2-L35) more  :smile:

**Comment by lenormf** [comment]
Those keys are implemented in the code directly, the syntax is not supported by the parsing function. Not sure it's worth adding support for it, but it would be consistent.
