### ISSUE TITLE
a-! behaves just like !

### ISSUE THREAD

**Issue by BjornMelgaard** [mawww/kakoune#1314]
[vid](https://asciinema.org/a/6am75ip49mdv8mugj1f5q28d5)

**Comment by ekie** [comment]
hi,

you are mislead because you execute this on an empty line.

> !: insert command output before selection
> 
> a-!: append command output after selection

Type a word, select it and repeat your commands.

**Comment by BjornMelgaard** [comment]
Yes, they behave differently, had a poor sleep

[Can you then explain be why with clipboard they behave differently?](https://asciinema.org/a/f4nc4kz55yrxi5049nn5kq5fkj)


Full: 

```
def -hidden copy_merged_selections %{ nop %sh{
  printf %s "$kak_selections" | sed -e 's/^://g' -e 's/\([^\\]\):/\1\n/g' -e 's/\\\\/\\/g' -e 's/\\:/:/g' | xsel --input --clipboard
} }

map global normal y ':copy_merged_selections<ret>y'

map global normal d \"_d
map global normal c \"_c
map global user   d ':copy_merged_selections<ret>d' -docstring 'yank and delete'
map global user   c ':copy_merged_selections<ret>c' -docstring 'yank and delete and enter insert mode'

map global user p '<a-!>copyq clipboard<ret>' -docstring 'clipboard paste after'
map global user P '!copyq clipboard<ret>'     -docstring 'clipboard paste before'
map global user R '|copyq clipboard<ret>'     -docstring 'clipboard replace current selection'

map global insert <a-p> '<a-;>!copyq clipboard<ret>'

```

**Comment by ekie** [comment]
works for me as intended, the link to the asciinema is broken.

**Comment by BjornMelgaard** [comment]
Lol, ok, I'll describe in words: if select whole line with `x` and copy then  `,p` and `,P` will paste text the same (up) if cursor is on empty line, thats why I was misleaded. I know this is right behavior. I may not to reply.
