### ISSUE TITLE
[feature request] autowrap paragraphs to N columns

### ISSUE THREAD

**Issue by ewtoombs** [mawww/kakoune#1316]
Basically what vim does when you tell it :set fo=atcw, :set columns=79, and the like. I'm sorry to say lack of this ability is hindering what would otherwise be a complete adoption of kak, being vastly superior to vim in every other respect.

**Comment by mawww** [comment]
Hello,

We have a script that provides autowrapping already: `rc/base/autowrap.kak`, you just need to run `autowrap-enable` to enable it in the current window, with the autowrap_column option controling the width.

**Comment by abitofalchemy** [comment]
`autowrap-enable` isn't working on macOS. 
on my system: `Built from source on 2017-09-22 at 12:16:32`

**Comment by mawww** [comment]
Hello, do you have any message in the `*debug*` buffer ? any error displayed ? what happens when you do `:autowrap-enable<ret>` in a buffer then type some text past the 80th column (or whatever value autowrap_column is set to) ? is the `fold` posix tool available on your system ?
