### ISSUE TITLE
Wrong cursor position when entering tmux copy mode

### ISSUE THREAD

**Issue by tripokey** [mawww/kakoune#1318]
When entering tmux copy mode in kakoune the tmux cursor starts in the bottom right of the screen while the kakoune cursor is still visible.

Expected:
tmux cursor should start at the first kakoune cursor and then kakoune's cursor's should be hidden while in tmux copy mode.

**Comment by mawww** [comment]
Thats linked with Kakoune not using the terminal hardware cursor at all (for display), we have another bug in iterm2 due to that, so it might make sense to place the cursor at the current main selection cursor position (even though we still will set it on hidden)

**Comment by tripokey** [comment]
That would be nice

**Comment by lenormf** [comment]
Could that be extended to having the cursor hidden when the window isn't focused on? Or is there no portable way of implementing that?

**Comment by mawww** [comment]
The cursor should be correctly placed now, however we still keep it hidden, the graphical representation is totally Kakoune controlled. This could be changed to let the terminal overlay its own cursor representation on top of the displayed one and give an additional graphical effect on the main cursor.
