### ISSUE TITLE
kakoune unable to split when using custom TMPDIR

### ISSUE THREAD

**Issue by tripokey** [mawww/kakoune#1319]
Window split with :new fails if kakoune is started with custom TMPDIR.

Scenario:
```
$ TMPDIR=$HOME/tmp kak
```

Then attempt a window split with :new 

Expected:
TMPDIR to be propagated to the new kakoune process allowing it to find the session socket.

Actual:
kakoune creates the tmux split but fails to connect the new kakoune process to the session causing the new process to exit.

**Comment by lenormf** [comment]
When `tmux` is started with `TMPDIR` in its environment, splitting works as expected. Applying the following patch (to forward the `TMPDIR` variable to the environment of the child process) fixes the issue:

```diff
diff --git a/rc/base/tmux.kak b/rc/base/tmux.kak
index ba555533..3bdcd364 100644
--- a/rc/base/tmux.kak
+++ b/rc/base/tmux.kak
@@ -24,7 +24,7 @@ def -hidden -params 1.. tmux-new-impl %{
         tmux_args="$1"
         shift
         if [ $# -ne 0 ]; then kakoune_params="-e '$@'"; fi
-        TMUX=$tmux tmux $tmux_args "kak -c ${kak_session} ${kakoune_params}" < /dev/null > /dev/null 2>&1 &
+        TMUX=$tmux tmux $tmux_args "TMPDIR='${TMPDIR}' kak -c ${kak_session} ${kakoune_params}" < /dev/null > /dev/null 2>&1 &
     }
 }
 ```

I'm not sure exporting the `TMPDIR` variable explicitely is the way to go.

**Comment by mawww** [comment]
@lenormf yeah I think it would make sense for any `:new` implementation to propagate TMPDIR.
