### ISSUE TITLE
Tab Completion not supported on buffer?

### ISSUE THREAD

**Issue by Shadowys** [mawww/kakoune#1327]
Is there any sort of tab completion for the text buffer planned?

**Comment by lenormf** [comment]
The `<tab>` key inserts a tab character in insert mode by default, and I don't think there's any plans to change that behaviour. You can however modify the behaviour of default keys with a hook/mapping in your `kakrc` configuration file, for instance the following will allow you to cycle through the completion candidates with `<tab>` and `shift+<tab>`:

```
hook window InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <backtab> <c-p>
}

hook window InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <backtab> <c-p>
}
```

**Comment by Shadowys** [comment]
I see. I guess I'll use that instead then. It works, so that's fine for me 
 
```
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <backtab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <backtab> <c-p> }
```

**Comment by lenormf** [comment]
I forgot to mention that my snippet requires a window context (`hook global WinCreate .* %{ … }`), the two are the same otherwise.

**Comment by sucrecacao** [comment]
Using this snippet I often get the following error that spam my debug buffer:
```
error running hook InsertCompletionShow()/: 3:9: 'map' unable to parse <backtab>
error running hook InsertCompletionShow()/: 3:9: 'map' unable to parse <backtab>
error running hook InsertCompletionShow()/: 3:9: 'map' unable to parse <backtab>
error running hook InsertCompletionHide(6.1,6.17)/: 3:9: 'unmap' unable to parse <backtab>
error running hook InsertCompletionHide(6.1,6.17)/: 3:9: 'unmap' unable to parse <backtab>
error running hook InsertCompletionHide(6.1,6.17)/: 3:9: 'unmap' unable to parse <backtab>
```
I tried with and without the `hook global WinCreate .* %{ … }` but got the same result

**Comment by Screwtapello** [comment]
Since this ticket was closed, the `<backtab>` key was renamed to `<s-tab>` since it's normally accessed by holding Shift and pressing the Tab key, rather than as a separate key.

The updated snippet is on the wiki: https://github.com/mawww/kakoune/wiki/Indentation-and-Tabulation#use-tab-for-both-indenting-and-completion
