### ISSUE TITLE
!xsel broke

### ISSUE THREAD

**Issue by mlinw** [mawww/kakoune#1331]
Commit 52ffa98787dccc0ecd02b81b43df715dd9b6e9fe seams to interfere with the way xsel handles its stdin when using the <insert-output:> (aka !) function. The commit fixed issue 1281, but appears to break using xsel with kakoune.

Running !xsel -b<ret> stopped working for me and debug message is
shell stderr: <<<
xsel: fstat error on stdin: Bad file descriptor
>>>

**Comment by lenormf** [comment]
cc #1330
