### ISSUE TITLE
uncaught exception (N7Kakoune13runtime_errorE)

### ISSUE THREAD

**Issue by jtruchan** [mawww/kakoune#1339]
After I compiled kakoune I tried to start it for the first time and got the following error:
<pre><code>$ ./kak
uncaught exception (N7Kakoune13runtime_errorE):
unable to find a posix shell in /usr/bin</pre></code>
bash is in `/bin`, not `/usr/bin` so I have created a symbolic link, however the issue persists.

**Comment by ekie** [comment]
hi,
it seems like your PATH is not set correctly. kakoune parses _CS_PATH in
https://github.com/mawww/kakoune/blob/master/src/shell_manager.cc#L30 and the error indicates that only  `/usr/bin` is specified on your system.

from man confstr:
```
_CS_PATH
    A value for the PATH variable which indicates where all the
    POSIX.2 standard utilities can be found.
```

**Comment by jtruchan** [comment]
That is my PATH:
```
$ echo $PATH
/usr/lib64/qt5/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/local/games:/home/jarek/.local/bin:/home/jarek/bin
```
Both `/usr/bin` and `/bin` are there. Not sure what is missing?

**Comment by ekie** [comment]
the value is hardcoded in the gnu c library, what OS are you using ?

**Comment by jtruchan** [comment]
OpenMandriva Lx 3.01. `glibc` version 2.25.
If `_CS_PATH` contains `/usr/bin` why did adding the symlink not help?

**Comment by lenormf** [comment]
You don't have an `sh` symlink pointing to your shell in your path.

**Comment by jtruchan** [comment]
Indeed, I've added it and it is working fine now. Thanks.
