### ISSUE TITLE
Don't print the major changes pop-up when `kak` is used as a pager

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1340]
Hi,

When piping contents to `kak`, the window that lists the latest breaking changes will pop up, and I thought we wanted this list displayed only when `kak` was started with no data as input.

Thanks.

**Comment by lenormf** [comment]
This might prove tricky to implement elegantly, as we don't know before entering the loop that processes events/inputs whether there's data on the standard input.

**Comment by mawww** [comment]
create_local_client did check if stdin was a tty or not though, I guess we can decide only to display that message when stdin was a tty.

**Comment by lenormf** [comment]
I don't think that would be enough, as `stdin` would still be a TTY when data is piped to the editor from the command line e.g. `echo a | kak`.

**Comment by mawww** [comment]
I think it would be reasonable to not show the message in that case.

**Comment by lenormf** [comment]
The following fixes the issue, but still leaves the case of piping commands directly into the editor from the CLI open:

```diff
diff --git a/src/main.cc b/src/main.cc
index 845a8ab5..afbb18d2 100644
--- a/src/main.cc
+++ b/src/main.cc
@@ -939,7 +939,7 @@ int main(int argc, char* argv[])
                 auto flags = (parser.get_switch("n") ? ServerFlags::IgnoreKakrc : ServerFlags::None) |
                              (parser.get_switch("d") ? ServerFlags::Daemon : ServerFlags::None) |
                              (parser.get_switch("ro") ? ServerFlags::ReadOnly : ServerFlags::None) |
-                             (argc == 1 ? ServerFlags::StartupInfo : ServerFlags::None);
+                             (argc == 1 and isatty(0) ? ServerFlags::StartupInfo : ServerFlags::None);
                 return run_server(session, init_cmds, init_coord, flags, ui_type, files);
             }
             catch (convert_to_client_mode& convert)
```
