### ISSUE TITLE
Running out of stack space trying to match a regular expression

### ISSUE THREAD

**Issue by rouanth** [mawww/kakoune#1346]
Kakoune crashes consistently when I view a certain file. I didn't have the time yet to distill it into a minimal example that crashes the editor, but maybe the large file will suffice.
[doc.zip](https://github.com/mawww/kakoune/files/968581/doc.zip)

The problem persists even it the latest commit. I've reproduced the problem on two different machines. I have no `kakrc`.

The error I get is:
```
uncaught exception (N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE):
Ran out of stack space trying to match the regular expression.
```

Simply open the file and scroll down using `PgDn` to approximately line 540. When jumping to that line directly, the crash doesn't occur.

**Comment by lenormf** [comment]
Are there any regex in your user configuration?

**Comment by rouanth** [comment]
> I have no `kakrc`

The only configuration I have is the set of scripts that comes with kakoune. Probably the problem is with `latex.kak` from `rc/extra` because when I remove it, the problem doesn't reproduce, as I've checked just now.

**Comment by lenormf** [comment]
I misread your message. Could you please do some trial&error to figure out what specific regex is at fault? I'm assuming it's the one at `latex.kak:23` that needs to be fixed.

**Comment by rouanth** [comment]
You are right, commenting this line out fixed the crash.

**Comment by Delapouite** [comment]
I think this issue may be closed now.

**Comment by mawww** [comment]
Yep, this should not happen anymore, as the new regex engine should not trigger this kind of behaviours.
