### ISSUE TITLE
Corrections for blog post

### ISSUE THREAD

**Issue by nathanl** [mawww/kakoune#1347]
http://kakoune.org/why-kakoune/why-kakoune.html is a really nice blog post and got me interested in Kakoune. After the first time I skimmed it, I thought, "wow, this is like Vim, but even Vimmier! 😆"

I was reading and working through the examples today, and had some corrections and suggestions. I didn't see a repo for the site to make a PR on, so I'm posting here instead.

-----
> The inverse operation could be done by selecting the word, then subselecting the upper case characters with s[A-Z]<ret> lower casing them with ```

The ` needs to be escaped.

> Another example would be parameter swapping, if you had func(arg2, arg1); you could select the contents of the parenthesis with <a-i>(, split the selection on comma with S, <ret>, and swap selection contents with <a-'>.

I had three problems getting this to work:
- First, I wasn't sure what `<a-'`> meant. I guessed "alt + '", but that didn't work, so I thought I was wrong. Explicitly saying "alt" would have made it clear.
- Second, "alt + '" does nothing in iTerm2. Finding issue 997 clarified for me that alt was the intended key and how to make it work. Maybe it would be good to link to that issue from the blog post, or just have a small hint about it?
- Third, `<a-'>` is the wrong keystroke; it should be `<a-">`. I saw the selection changing when I did `<a-'>`, but the text didn't change and I wondered if this was a bug.

> This is only the tip of the iceberg, Kakoune

s/,/.

> Kakoune command line also support shell expansion

s/support/supports

**Comment by mawww** [comment]
Pushed some fixes, regarding `<a-'>`, the keybinding was changed after the publication of that blog post, but I fixed it anyway. For the `<a-...>` meaning alt, and it not working in iterm2, I dont think the blog post is the right place to explain it.
