### ISSUE TITLE
easy motion equivalent

### ISSUE THREAD

**Issue by jwkvam** [mawww/kakoune#1354]
I may be in the minority here but I've come to find the [easymotion](https://github.com/easymotion/vim-easymotion) plugin indispensable for vim. I didn't see it mentioned in the wiki so I thought I would mention it here.

If there is no equivalent, does this oppose kakoune's philosophy? If not would it be possible to implement (e.g. by me) in a plugin? I'm very new to kakoune so apologies if this is naive.

**Comment by jockus** [comment]
@mawww Recently pushed an experimental "range-replace" highlighter that'll give us the ability to mark the screen with target characters.

What parts of easymotion do you find most useful, as it has now grown to quite a flexible plugin?

**Comment by jwkvam** [comment]
I mostly use `easymotion-bd-w` and `easymotion-lineanywhere` to jump bidirectionally by word through the file and bidirectionally on the current line. That's probably 99% of what I use it for. I honestly haven't spent much time trying to learn and use its more advanced features.

**Comment by danr** [comment]
I made a first stab at writing an easymotion plugin: https://github.com/danr/kakoune-easymotion

**Comment by mawww** [comment]
Thanks to @danr there is now a script providing this, and I dont plan to implement that in core any way, so I'll close this issue.
