### ISSUE TITLE
Feature request: Flag for executing command before buffers are created

### ISSUE THREAD

**Issue by tripokey** [mawww/kakoune#1361]
Kakoune currently has the -e flag for executing a command after the buffers for any file arguments are created. This enables project specific configuration with kakoune -e '%sh {cat proj.kak}', however hooks defined in proj.kak will not be executed for the initial buffers.

I suggest a -E flag for executing the command before creating the buffers.

**Comment by danr** [comment]
Try: 

    kak -e 'source proj.kak; edit file.cpp'

**Comment by tripokey** [comment]
Yes that would work for a single specific file.

However it would be nice to be able to set the above command as an alias as pkak that from the command line would behave like kak but with extra config loaded.

**Comment by danr** [comment]
Try:

    function pkak () { kak -e "source proj.kak; edit $@"; }

**Comment by tripokey** [comment]
That would still only work for any single file and the rest of the command line flags and arguments for kakoune would not work either

**Comment by danr** [comment]
Ok, I give up! It's a sensible FR!

**Comment by tripokey** [comment]
:-)

**Comment by cbuschardt** [comment]
What about evaluating the arguments in the order they're seen.  That is if -e is before the file -- it evaluates first.  If it is after, then after?

**Comment by tripokey** [comment]
That would work for my use case. It would however be a breaking change and it might break some other use cases?

**Comment by lenormf** [comment]
Order dependent command line flags doesn't sound very UNIX, I don't think that's the direction to take.

**Comment by cbuschardt** [comment]
What precisely was wrong with:
   kak -e 'source proj.kak; edit file.cpp'

My concern with adding a new type of evaluation option doesn't fit with KISS.  After a few years of these sorts of one-off additions the documentation and code will be very cluttered. 

And yes, I concede that it would be a breaking change.  While there are plenty of examples of order dependent parameters in the Unix world [GCC and LD come to mind] -- it's unusual.

**Comment by mawww** [comment]
Order dependent options will be a pain to implement and to predict, especially as we open files in reverse order at the moment so that the first one is considered the most recent and is the one that gets displayed.

`-E` seems okay, but the given use case can be fixed by just adding some logic in your kakrc, something like:

```
%sh{
    if [ -e proj.kak ]; then echo source proj.kak; fi
}
```

Will source the proj.kak file if its present in the starting directory.

I am on the fence for that feature, I'd like to see more use cases where using command line is clearly more convenient than using the kakrc (which is sourced before opening files).

**Comment by tripokey** [comment]
Having it in the kakrc file introduces a risk of sourcing something implicitly if there happens to be a proj.kak file in $PWD whereas the command line flag only sources the proj.kak file if explicitly asked for.

If it were a simple configuration file and not arbitrary code i would agree with the kakrc approach.

**Comment by mawww** [comment]
Ok, you convinced me.

**Comment by tripokey** [comment]
Shooting my own argument a bit in the foot here but...

The security concern with the kakrc approach could be mitigated by triggering the behaviour on the presence of an environment variable?

**Comment by cbuschardt** [comment]
This solution doesn't appear to be heading to an intuitive solution.  Look at the behavior that's being proposed.  

> kak -E [before] -e [after] first.c second.c third.c 
            
Surprises:
   - [after] operates on first.c
   - [before] operates immediately before third.c
   - argument has different behavior depending on case 
   - files are evaluated right to left *but* evaluate(s) have separate ordering rules

> kak -e [before] first.c second.c third.c -e [after]

Evaluating the arguments in order has the advantage that  **you can execute commands between files**.
