### ISSUE TITLE
Rename the `:` object delimiter into `c`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1362]
Hi,

Since we support arbitrary punctuation sign delimiters for objects, it's become impractical to easily select a colon-delimited object, because the key for custom objects is a colon.

Renaming the custom object delimiter into `c` (or another letter) would allow using `<a-i> :` to do an inner selection of a colon delimited object, whereas right now we need to use `<a-i> : :,:`.

Thanks.

**Comment by Delapouite** [comment]
Your suggestion makes sense for the colon char.
Another improvement could be to also support the underscore char `_` better, which is heavily present in snake_case languages.
Currently, the the `is_punctuation` is used to trigger the fallback behavior:

https://github.com/mawww/kakoune/blob/master/src/normal.cc#L1149

```cpp
        if (is_punctuation(cp))
        {
            auto utf8cp = to_string(cp);
            return select_and_set_last<mode>(
                context, std::bind(select_surrounding, _1, _2,
                                   utf8cp, utf8cp, count, flags));
        }
```

but the `_` char is not considered a punctuation:

https://github.com/mawww/kakoune/blob/master/src/unicode.hh#L32-L47
```cpp
template<WordType word_type = Word>
inline bool is_word(Codepoint c) noexcept
{
    return c == '_' or iswalnum((wchar_t)c);
}

inline bool is_punctuation(Codepoint c) noexcept
{
    return not (is_word(c) or is_blank(c));
}
```
