### ISSUE TITLE
Allow saving a soft-wrapped buffer as-is

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1377]
Hi,

With the new soft-wrapping functionality merged, I'm wondering if it's possible to save a soft-wrapped buffer "as-is", meaning that newline characters are inserted in the buffer where the lines are broken by the `wrap` highlighter.

It would be practical when e.g. writing some text in a scratch buffer with the `wrap` highlighter added to the window (set -say- at col 80), I wouldn't have to rely on manually piping the paragraphs to `fold`, or use the `autowrap` script which I think would be completely deprecated (for the best) if the issue in this issue was to be implemented.

Thanks.

**Comment by mawww** [comment]
I dont think this is a reasonable feature. Either hard line breaks are wanted and auto-wrap or similar should be used, or only soft wraps and wrap highlighting is the way to go.

Besides, its going to be far to complex to get the wrapping state out of the highlighter for saving.
