### ISSUE TITLE
Display the docstring set on an option interactively

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1378]
Hi,

In relation with #1374, I'd like docstrings passed to the `decl` command to be displayed interactively. I'm not sure where they could be displayed, maybe in the info box when assigning a value to an option with `set`?

Thanks.

**Comment by mawww** [comment]
Thats already the case, if you type `set global <option-name>` the docstring of the option will get added in the info box. Or is that failing in your case ?

**Comment by lenormf** [comment]
It does work, however since the pop up window gives information about the `:set` command, I didn't think to read the text shown there carefully. The documentation for the option is mingled with the documentation for `:set`, so it's a bit confusing and hard to know what's what if you don't already know where the `docstring` for a given option is supposed to be displayed.

I don't mind having the docstring for an option displayed in the info box for `:set` (I don't know where else the documentation could be displayed anyway), however formatting could be improved.

**Comment by Delapouite** [comment]
I agree that this is mainly a formatting issue.

This extra info is displayed by a `CommandHelper`: 
https://github.com/mawww/kakoune/blob/master/src/commands.cc#L205-L215
```cpp
struct CommandDesc
{
    const char* name;
    const char* alias;
    const char* docstring;
    ParameterDesc params;
    CommandFlags flags;
    CommandHelper helper;
    CommandCompleter completer;
    void (*func)(const ParametersParser&, Context&, const ShellContext&);
};
```

Beside `set-option` and `unset-option` very few commands use a `CommandHelper`.

Here's the one for `set-option`:
https://github.com/mawww/kakoune/blob/master/src/commands.cc#L1226-L1236
```cpp
static String option_doc_helper(const Context& context, CommandParameters params)
{
    if (params.size() < 2)
        return "";

    auto desc = GlobalScope::instance().option_registry().option_desc(params[1]);
    if (not desc or desc->docstring().empty())
        return "";

    return format("{}: {}", desc->name(), desc->docstring());
}
```

and the one for `add-highlighter`:
https://github.com/mawww/kakoune/blob/master/src/commands.cc#L716-L726
```cpp
    [](const Context& context, CommandParameters params) -> String
    {
        if (params.size() > 0)
        {
            HighlighterRegistry& registry = HighlighterRegistry::instance();
            auto it = registry.find(params[0]);
            if (it != registry.end())
                return format("{}:\n{}", params[0], indent(it->value.docstring));
        }
        return "";
    },
```

They are a bit inconsistent in the way they use `\n` chars. I would suggest to put a new line before and after so something like that: `"\n{}: {}\n"` in the `format` functions.

**Comment by mawww** [comment]
I agree the formatting should be improved to make the option docstring more visible. I still hope to get formatting support in the info box at some point (having multiple faces used in an info box) which should help as well.

**Comment by lenormf** [comment]
Actually I thought not having faces there was nice, otherwise the editor starts looking like a christmas tree with everything bolded out or colorized.
