### ISSUE TITLE
Highlighted column get broken when cursor goes out of the screen.

### ISSUE THREAD

**Issue by neyuki** [mawww/kakoune#1382]
1. Have a column highlighter like `addhl column 120 default,rgb:404040`
2. File with really long line.
3. Move through that line to the end of a screen.

After that column highlighter is broken.

**Comment by lenormf** [comment]
The `column` highlighter is also broken on soft-wrapped lines.

**Comment by neyuki** [comment]
On soft-wrapped lines vertical break (if you mean that) is normal behaviour, at least nearly same as in spacemacs. Additionally showing that this is a single line.
