### ISSUE TITLE
Cursor glitches

### ISSUE THREAD

**Issue by mlinw** [mawww/kakoune#1392]
Commit 91ed57c985a2edb879a1956c75282ff0f6b0448 has introduced a strange cursor glitch that occurs when you move the cursor up or down or scroll or search (probably anytime you update the screen). It looks as if the cursor changes position 5-8 times pr movement before settling at the correct position - or as if many cursors are shown and hidden at random positions. The glitch does not seem to affect anything and is close to instantaneous, it is distractive however.

I am using the st terminal. The glitch does not appear to occur on an xcfe4-terminal or lxterminal, but my color schemes on those terminals are broken (probably 16-color or smth). Update rate is capped at 30 fps I think.

The glitch does not occur in commit 973487abcd469a51a23f0d293a455ed73da7804c.

**Comment by jkonecny12** [comment]
The happens here. I'm using Gnome Terminal and tmux in it.

**Comment by mlinw** [comment]
I'm using tmux too. The glitch does not occur to me without tmux.

**Comment by ManDay** [comment]
I've come across this in tmux in native console (aka tty). I also tried kak in console without tmux and though less apparent, I think it can be seen to happen then, too.

**Comment by mawww** [comment]
Visible hardware cursor has been disabled, so this should be fixed.
