### ISSUE TITLE
Soft-wrapped lines that start on the last row of the window are not entirely visible

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1398]
Hi,

If the last line of the current window is soft-wrapped and data past the last column is supposed to be highlighted (through a search jump with `n`, or simply using `<a-l>`), then the cursor disappears out of view.

Maybe soft-wrapped lines should be displayed fully at all times? Or revealed progressively/as necessary, when the cursor is sent past the last column of the line?

HTH.

**Comment by mawww** [comment]
I cannot reproduce that, can you check if this has been fixed ?

**Comment by lenormf** [comment]
Seems to be working now, after doing a quick test.
