### ISSUE TITLE
Dynamically listing registers content in info box

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1400]
Hi.

I'm attempting to display the content of alpha registers in an info box. Here's my kak script so far : 

```
def registers %{ %sh{
  echo -n info -title registers -- %{
    prefix=kak_reg_
    for letter in {a..z}; do
      eval reg=\$$prefix$letter
      if [ -n "$reg" ]; then
        echo "$letter $reg"
      fi
    done
  echo }
} }
```
If I store something into the `b` register for example and run this command, nothing is displayed.
But If I run this slight variation (notice the explicit `echo $kak_reg_b` at the end), it kind of works:

```
def registers %{ %sh{
  echo -n info -title registers -- %{
    prefix=kak_reg_
    for letter in {a..z}; do
      eval reg=\$$prefix$letter
      if [ -n "$reg" ]; then
        echo "$letter $reg"
      fi
    done
    echo $kak_reg_b
  echo }
} }
```

I mean the info box now displays 2 lines, so if I have `content` in the `b` register:
```
b content
content
```

What am I missing?

**Comment by lenormf** [comment]
The editor doesn't export values that it didn't detected in the code prior to running the shell. If you want `$kak_reg_b` to be expanded, then `kak_reg_b` needs to appear in the code (anywhere). This allows not exporting all of the variables supported by the editor every time a shell scope is spawned.

You could cheat by writing a comment in the code, forcing the editor to export the values all the time:
```
# kak_reg_a kak_reg_b …
```

**Comment by Delapouite** [comment]
Thanks @lenormf 

I never stumble upon this case before. The workaround is a bit unfortunate, but I understand the underlying performance issue.
