### ISSUE TITLE
Multi-syntax highlighting for Vue.js single file component files

### ISSUE THREAD

**Issue by herrbischoff** [mawww/kakoune#1404]
Vue.js supports single file components, effectively merging all needed code for a component into one file. It looks like this:

```
<template>
  <div id="app">
    <img src="./assets/logo.png">
    {{#router}}
    <router-view></router-view>
    {{else}}
    <hello></hello>
    {{/router}}
  </div>
</template>

<script>
{{#unless router}}
import Hello from './components/Hello'{{#if_eq lintConfig "airbnb"}};{{/if_eq}}
{{/unless}}
export default {
  name: 'app'{{#router}}{{#if_eq lintConfig "airbnb"}},{{/if_eq}}{{else}},
  components: {
    Hello{{#if_eq lintConfig "airbnb"}},{{/if_eq}}
  }{{#if_eq lintConfig "airbnb"}},{{/if_eq}}{{/router}}
}{{#if_eq lintConfig "airbnb"}};{{/if_eq}}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

In here are at least three different kinds of syntax requirements: HTML, JavaScript and CSS.

Is there any way `kakoune` can support syntax highlighting for those kinds of files?

More information for reference: https://vuejs.org/v2/guide/single-file-components.html

**Comment by doppioandante** [comment]
Yep, check out html.kak
```
add-highlighter -group /html/style  ref css
add-highlighter -group /html/script ref javascript
```
The /html/style and /html/script rules were defined earlier in the file and they now *ref*er to the javascript and css highlighter.
A similar thing could be done for Vue I guess.

**Comment by herrbischoff** [comment]
Interesting. Am I correct in assuming that I would have to create a `vue.kak` syntax definition that references the respective parts?

Additionally, as Vue.js allows specifying different template languages as XML attributes, how would you go about parsing and switching that?

Example:

```
<template lang="pug">
... stuff ...
</template>

<script>
... stuff ...
</script>

<style lang="stylus">
</style>
```

**Comment by lenormf** [comment]
I did something similar for RiotJS files:

https://github.com/lenormf/kakoune-extra/blob/master/filetype/riotjs.kak#L22,L23

**Comment by danr** [comment]
There is already support in the html highlighter to refer to the js and css highlighters in `style` and `script` tags:

https://github.com/mawww/kakoune/blob/master/rc/base/html.kak#L21

Note also their corresponding `ref` highlighters a few lines down:

https://github.com/mawww/kakoune/blob/master/rc/base/html.kak#L26

I am not sure what the best practices here would be but you could add a pug hl by adding this line to the html regions highlighter: 

    pug     %{<template\h+lang=('pug'|"pug")>\K} (?=</template>) '' \
    
And then this reference

    add-highlighter -group /html/pug    ref pug

You can activate this highligher with `:set buffer filetype html`. Hope this helps in making a proper `vue.kak`.

**Comment by mawww** [comment]
I'll close that, as it looks like there is nothing to do on Kakoune's side.
