### ISSUE TITLE
Is it possible to add custom completion candidates to the auto-completion menu?

### ISSUE THREAD

**Issue by guillaumecherel** [mawww/kakoune#1416]
I use kak for writing emails, and I store all my email adress contacts in a file, on per line, like
    
    Joe Bla <joe.bla@gmail.com>
    G z <g.z@a.com>

I'd like each line to appear as a possible auto-completion candidate. Is this possible?

**Comment by ekie** [comment]
i use something like this:
execute 
```
set window static_words "%sh{tr '\n' ':' < ~/.contacts | cut -b 1-}"
set window completion_extra_word_char @
```
for your desired filetype.

starting with @ in insert mode will give you the complete list to cycle through.

**Comment by Delapouite** [comment]
For people googling this thread, the API changed slightly in https://github.com/mawww/kakoune/commit/f41d78083aa8d3883bcd4ed819e6784e09e69dba

**Comment by mawww** [comment]
Another way would be to use the custom completion system. Detect when the cursor is in a context expecting a mail address (in a To:, Cc: or Bcc: list), and set an option of type `completions` with the list of emails and the correct start position. (And add that option to `completers` option so that it would get used).

**Comment by Delapouite** [comment]
@lenormf made a practical demonstration in his dictcomplete script here : https://github.com/lenormf/kakoune-extra/blob/master/dictcomplete.kak

relevant extracts:

`decl -hidden completions dict_completions`
`set window completers "option=dict_completions:%opt{completers}"`

and then fill `dict_completions` with something like `11.43@2:foo||foo:bar||bar`

Where: `11` is the line, `43` is the column, `2` is the buffer timestamp, `foo||foo` is a `replace|help|menu entry`
