### ISSUE TITLE
Slow autosuggest completion

### ISSUE THREAD

**Issue by mlinw** [mawww/kakoune#1417]
If I am editing a large multi selection (2800 selections) and accept a suggestion from the autosuggestions, insertion is too slow (~5 s). This is strange, because manually inserting the text is fast.

To reproduce, try something like 
`!find . -iname '*.pdf'`
(or something similar that will give you a lot of file paths)
And then replace the first dot in all file paths with /home/user/ (this will prompt the autosuggest)
Like `%s^\.<ret>c/hom<c-n>`
Inserting the text is instant, but the `<c-n>` action will cause a long delay, at least for me.
I am running in debug mode, but since manual insertion performs very well, I am a bit confused why autosuggest appears to perform so poorly.

**Comment by lenormf** [comment]
Could it be that the completer issues system calls to probe the filesystem when generating candidates?
