### ISSUE TITLE
Show Unicode character name and its code under primary cursor in the status line

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#142]

**Comment by lenormf** [comment]
Can this be done by a third party script? How to get the name of a given unicode character in a standard way?

**Comment by Delapouite** [comment]
This is an equivalent of the `:ascii` command in vim.

There's this Tim Pope plugin enhancing this command with extra info : https://github.com/tpope/vim-characterize
It seems to rely on this huge (>1Mo) file listing the main char names : https://raw.githubusercontent.com/tpope/vim-characterize/master/autoload/characterize.vim

**Comment by Screwtapello** [comment]
Displaying the character name would be nice, but requires lugging an up-to-date Unicode character database around, which is non-trivial.

Displaying the code-point under the primary cursor is a lot simpler, requires no external data, and any competent search-engine can take a string like "U+2603" and give you the name and everything else you might care to know. Even without external look-up, it's still a good way to tell ASCII characters from their fancier counterparts, or whether a particular grapheme is a single code-point or a base character + a composing character.
