### ISSUE TITLE
soft-wrap -width option

### ISSUE THREAD

**Issue by nuao** [mawww/kakoune#1424]
To make reading nicer, it would be useful to have a maximum width option for the soft-wrap. Some terminal windows can be wider than a comfortable reading width.

So, instead of only at the window edge, the width option would force each display line to have at most N characters.

**Comment by mawww** [comment]
We can do that but for simplicity reason we will need to wrap at min(window_width, given_width), is that the behaviour you are looking for ?

**Comment by nuao** [comment]
Yes, min(window_width, given_width) is exactly what I had in mind.
Thank you very much for doing this so quickly. Works great.
