### ISSUE TITLE
Superfluous \n when reading from a fifo

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1426]
Hi,

When reading from a fifo there is always an additional empty line at the end of the buffer in comparison to what was written to the fifo. It would be nice to remove it as soon as some data is read.

**Comment by mawww** [comment]
This empty line is actually here for a purpose: allowing the user to have his window scroll while the fifo is being written to, by putting is cursor on that newline. Is that causing some problems for your use case ?

**Comment by occivink** [comment]
Ah then maybe when the fifo has been closed?  My (minor) issue is that when we're writing in a structured way to the fifo that extra newline can slightly break the structure. 
For example in grep.kak you have 1 line <-> 1 match, so moving the cursor up or down will always land you on a match, _except_ if you're on the last match. 
I'm facing this issue with the gdb script where I have similar commands to move up and down the backtrace, except that I don't want to do a search (as in grep.kak) because wrapping wouldn't make sense there. Hopefully I'm being clear.

**Comment by mawww** [comment]
You can easily remove that line with `hook buffer BufCloseFifo %{exec -draft ged}`

**Comment by occivink** [comment]
Yes that's what I was considering but it struck me as worth discussing.
