### ISSUE TITLE
Add confirmation messages in status bar when text is deleted or changed (like yanked 2 selections to register ")

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1427]
Hello

Currently, when we yank selections, a confirmation message is displayed in the status bar:
> yanked 2 selections to register "

https://github.com/mawww/kakoune/blob/master/src/normal.cc#L557-L565
```cpp
void yank(Context& context, NormalParams params)
{
    const char reg = params.reg ? params.reg : '"';
    RegisterManager::instance()[reg].set(context, context.selections_content());
    context.print_status({ format("yanked {} selections to register {}",
                                  context.selections().size(), reg),
                           get_face("Information") });
}
```

delete and change operations remain silent.

I understand that the current behavior makes a lot of sense.
Because when you yank something, you want to have feedback but deleting and changing have a direct (and visual) impact on the buffer, so another confirmation seems extraneous in the status bar.

Some users may feel like adding `erased 2 selections to register "` on each delete operation will add visual noise.
But in some case it could offers valuable information, if you don't use the default register `"`. 

I know the current register is displayed in the mode line, but it's only visible *before* the command has been executed. And sometimes you forget which one you selected after you have pressed `d` or `c`.

So I would like to submit a PR. 3 possible scenarios:

1 - always displaying the message `erased 2 selections to register x`
2 - displaying the message `erased 2 selections to register x` only when the `autoinfo` option is enabled
3 - displaying the message `erased 2 selections to register x` only if register is not `"`

What's your opinion on this?

**Comment by lenormf** [comment]
Never display a message.

**Comment by mawww** [comment]
>  But in some case it could offers valuable information, if you don't use the default register ".

I'd say that this is not very valuable information, the user just typed `"a` to use the register `a`, and the status line was displaying `reg=a`, so I'd expect the user knows what register will be used.

We already have that behaviour (mostly) when `autoinfo` has `normal` set, I dont think we need more than that, but I am curious to see when other users think of that.
