### ISSUE TITLE
Wrapped line numbers should not be duplicated

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1431]

**Comment by occivink** [comment]
There is face for that, `LineNumbersWrapped`, so you can hide or just dim them.

**Comment by mawww** [comment]
I am fine with either keeping the face, or just removing the numbers on wrapped lines, I'd like to avoid making that an option though, what are your opinions ?

**Comment by lenormf** [comment]
Seeing the line numbers by default is the best behavior in my opinion, as it allows users not to have to look for the index of long wrapped line when trying to jump to it.

Example:

```
42|Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum fringilla
   lorem quis orci convallis fringilla. Vivamus justo ipsum, ultrices vitae
   enim ut, placerat tempus justo. Ut lobortis massa dolor, ut ornare mauris
   finibus quis. Morbi finibus congue enim, sagittis fermentum nunc accumsan
   eu. Aliquam dictum dui lorem, sed tempus lorem convallis ut. Quisque libero
   massa, pretium ut nibh a, iaculis volutpat odio. In egestas purus sed purus
   finibus, eu mollis lorem vehicula. Proin interdum lacus ut condimentum
   elementum. Aliquam aliquam nunc non purus fringilla pellentesque. Donec
   lacus neque, molestie et urna quis, tincidunt vulputate est. Nullam in odio
   vel orci venenatis aliquet. Mauris luctus viverra eros. Quisque laoreet
   nunc vel varius consectetur. Donec neque nibh, viverra porta justo eu,
   sollicitudin lacinia felis.
…
52| []
```

In the above example, having the anchor on line 52, a user that wants to jump at a particular location in the wrapped line has to look all the way up to know the line index (42). When the line numbers are shown all the time by default, the index is much more accessible and avoice unecessary eye movement.
