### ISSUE TITLE
Fail silently when hitting the escape key on the marks menu (`<a-z>`/`<a-Z>`)

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1443]
Hi,

Upon hitting the escape key when the marks menu shows up (the `<a-z>`/`<a-Z>` keys), an unelegant error message pops up:

```
unknown combine operator '~B'
```

Users would expect nothing to happen there, as is the case with other menus (e.g. the goto menu).

HTH.

**Comment by occivink** [comment]
The object selection dialog also prompts an error message when `<esc>`ing
