### ISSUE TITLE
Complete static command flags

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1467]
Hi,

It'd be convenient to have the completion engine kick in when interactively typing out command with a known flag, in the prompt - e.g. `:echo -deb<tab>` for `:echo -debug`.

Thanks.

**Comment by Delapouite** [comment]
Somehow related about the way command switches are parsed:

`echo -debug foo`: `foo` is added to the debug buffer
`echo foo -debug`: `foo -debug` is add added to the debug buffer

In the second case I was expecting to only get `foo` as well.

**Comment by mawww** [comment]
@Delapouite: This behaviour is command dependent, `echo` only accept switches at start, like a few other commands, every switches that are not at start are considered as positional arguments. Its necessary for a few commands that needs to distinguish between switches and argument that just start with `-` (usually switches for something else down the line). For echo, its debatable if that is the right behaviour or not.
