### ISSUE TITLE
Allow removing/interpreting ANSI escape sequences

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1477]
Hi,

Sometimes when opening a log saved from a build-system building phase (e.g. the LibreELEC build-system), the file would be littered with ANSI escapes that make it hard to read the actual text.

I guess it's possible to remove them by pre-processing the file (a regex would work I reckon), but I'd be more interested in a way to interpret those sequences as it would potentially open the door to other things, e.g. highlighting a buffer using the `highlight` utility.

Thanks.

**Comment by mawww** [comment]
I am not sure we should do this, sane build systems dont emit ansi escapes if they dont output to a tty, tools should not do that in general. I am not convinced a text editor should start interpretting ansi escapes.

**Comment by lenormf** [comment]
I had in mind the possibility to have an highlighter to do that.

**Comment by lenormf** [comment]
Decision made in #2492, this is implemented by ways of plugins, e.g. https://github.com/eraserhd/kak-ansi
