### ISSUE TITLE
Add <a-o> to open new lines

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1480]
Alternative behavior of `o` command to open new lines, but without entering insert mode or moving selections.

**Comment by lenormf** [comment]
I suppose the answers given to #1175 also applie here.

**Comment by mawww** [comment]
Actually, I think this could make sense, its a pretty common operation to just add an empty line here and there (at least in my worflows), and I know I use far too much the `o<esc>` sequence. I think this could be considered similar to `<a-s>`: yeah we do have another way to express that, but its a common enough use case to warrant its own binding.

Besides, `<a-o>` make lots of sense as a mapping for that, and `o` is `A<ret>` but still has its own binding.

I'd be interested in gathering more opinions.

**Comment by lenormf** [comment]
I can see this issue and #1175 go hand in hand, if one is implemented then I think the other should be as well (I use `<a-d>` regularly, more than `o<esc>`).

**Comment by Delapouite** [comment]
Yes `<a-o>` and `<a-O>` make sense as common operations, especially used with a count.

Equivalent shortcuts are quite popular through Tim Pope's [unimpared.vim](https://github.com/tpope/vim-unimpaired) (they are `[<space>` and `]<space>` over there).

**Comment by ekie** [comment]
i agree with lenormf. though have my own mappings to deal with those issues, providing a default is a nice addition and a problem solved for newcomers.
