### ISSUE TITLE
resolve file path for token being completed in edit command

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#149]
Example

```
foo/
├── bar/
│   └── qux
└── baz/
    └── qux
```

Candidate completion for `:edit f//qux` will be `foo/bar/qux` and `foo/baz/qux`.

**Comment by lenormf** [comment]
The introduction of the `-file-completion` flag has greatly simplified completion on path, is this issue still relevant ?

**Comment by mawww** [comment]
I think the current fuzzy matcher is good enough without needing it to go search in subdirectories eagerly.
