### ISSUE TITLE
formatter.kak does not restore cursor position

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1492]
Hello

I noticed a broken behavior since the last update on `formatter.kak` https://github.com/mawww/kakoune/commit/6376aa6206aefb408fef75ecfb21648418656301
The enclosing `eval` is done in a draft context, therefore I think we do not have access to the correct location for `$x` and `$y` anymore.
The visual effect is that the cursor always ends up at the bottom of file after each formatting.

**Comment by mawww** [comment]
That should be fixed by 580eae03881190b108ffb896197af27d88935177, can you confirm ?

**Comment by Delapouite** [comment]
It works! Thanks to both of you.
