### ISSUE TITLE
Properly set the index register to the current selection's index in an iteration

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1503]
Hi,

When iterating over several selections, the index register `#` is not set to the current selection's index. One possible motivation for fixing that could be dropping all the odd-numbered selections using `$[ $((kak_reg_hash % 2)) -eq 0 ]`.

HTH.

**Comment by Delapouite** [comment]
Note for readers stumbling on this issue through search engines, the above command should now be written:

```
$[ $((kak_main_reg_hash % 2)) -eq 0 ]
```

Since the introduction of `kak_main_reg_` in commit https://github.com/mawww/kakoune/commit/27163106c74fdee8af923daf4345f1c90f9d8b1d (2018)
