### ISSUE TITLE
Add (HJKL) view commands to scroll N% of the size of the window

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#151]

**Comment by lenormf** [comment]
I think this issue can be closed, this can be implemented in a script and wouldn't really fit in the default bindings.

**Comment by mawww** [comment]
Closing as I dont think we really need that, if you want to move by big increment, you probably want <kbd>PgUp</kbd> and <kbd>PgDown</kbd> as you do not want to keep the main selection in place and prevent you from scrolling past it.
