### ISSUE TITLE
echo command: rename flag -color→ -face

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1512]
Hello.

Currently the `echo` command accepts a `-color` flag. This naming dates back from this 2013 commit https://github.com/mawww/kakoune/commit/8bfe2d62e5244ef70931aee66d13e08e0450155e

This is *a bit* misleading since in reality this flag accepts a *face*, so ideally it should be called `-face`.
The doc is correct about what i does, and  I perfectly understand that this name change would probably break a few existing scripts for no real benefits.

So yes, it's not really crucial. It's just that this morning I started writing a `echo` command and asked myself: "Should I write `echo -color red`, or is `echo -color Error` a legal syntax?"

**Comment by mawww** [comment]
I wonder if we could just remove that switch, which is superseeded by `echo -markup` anyway.

**Comment by Delapouite** [comment]
Yes your suggestion is even better.

```kak
echo -color Error foo 
echo -markup {Error}foo
```

are equivalent.

About 20 rc scripts would be impacted by the removal of `-color`: https://github.com/mawww/kakoune/search?utf8=%E2%9C%93&q=-color&type=
