### ISSUE TITLE
Can't map to <c-i> (Jump backwards)

### ISSUE THREAD

**Issue by xash** [mawww/kakoune#1527]
```
map global normal ( <c-i>
map global normal ) <c-o>
```

When saving two jump points with `<c-s>` you can switch between them with `<c-o>/<c-i>`. With the mapping `)` does the same as `<c-o>`, while `(` does nothing.

**Comment by occivink** [comment]
In `normal.cc`, we can see why that is:

```
    { {/*ctrl('i')*/Key::Tab}, {"jump forward in jump list",jump<Forward>} }, // until we can distinguish tab a ctrl('i')
    { {ctrl('o')}, {"jump backward in jump list", jump<Backward>} },
    { {ctrl('s')}, {"push current selections in jump list", push_selections} },
```

Unfortunately, terminal emulators cannot distinguish certain keys, such as <c-i> and <tab>.

**Comment by lenormf** [comment]
I think we can close this issue.
