### ISSUE TITLE
Inconsistent selections with b and W

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1529]
I don't know if there's already a convention for describing kakoune's selections in text, but I'm going to indicate the position of the cursor by drawing `^` on the next line, and the rest of the selection by
drawing `~`s.
                                                                                
For example, if I start with the following text and the cursor on "a":          
                                                                                
    abc def                                                                     
    ^                                                                           
                                                                                
...then I press "w", the cursor moves and selects the space since the previous position:
                                                                                
    abc def                                                                     
    ~~~^                                                                        

**Steps to reproduce**                                                          
                                                                                
  - Create a document containing "abc def" as above, and put the cursor on the space:
                                                                                
        abc def                                                                 
           ^                                                                    
                                                                                
  - press "b" to move back by a word:                                           
                                                                                
        abc def                                                                 
        ^~~                                                                     
                                                                                
  - press "W" to keep the existing selection and move forward by a word:        
                                                                                
        abc def                                                                 
        ~~~^                                                                    
                                                                                
  - OK, so that's how "W" works. Hit ";" to collapse the selection, then "l" to move the cursor to "d":
                                                                                
        abc def                                                                 
            ^                                                                   
                                                                                
  - press "b" again:                                                            
                                                                                
        abc def                                                                 
        ^~~~                                                                    
                                                                                
  - press "W" again to keep the existing selection and move forward by a word   
                                                                                
**Expected results**                                                            

Just as before:

    abc def                                                                     
    ~~~^                                                                        
                                                                                
**Actual results**                                                              

The cursor moves, but the anchor stays in the same place:

    abc def                                                                     
       ^                                                                        

I haven't been using kakoune for very long, so I'm not sure if this a bug or a deliberate design choice.

**Comment by mawww** [comment]
`W` is an `extending` selection primitive, the way that usually works is by only moving the cursor, and keeping the anchor as it was.

So, in your use case, you are seeing the expected behaviour: the selection anchor is on the space, and cursor on the `a`. `w` selects to next word start, but as we use the capital version `W`, we dont move the anchor, only the cursor, and we end up with a cursor and anchor at the same place (on the space).

I believe this is the right behaviour, in particular it allows to tweak the selection start easily (say you select a paragraph, then want to remove a few of the starting words, you can do `<a-i>p` to select the paragraph, `<a-;>` to swap anchor and cursor, then move the cursor a few words forward not touching the anchor with `W`).

**Comment by lenormf** [comment]
>I don't know if there's already a convention for describing kakoune's selections in text

In the unit tests, selections are wrapped with `%(…)` characters, people familiar with the codebase should understand that syntax e.g. `%(a)bc def`, `%(abc )def`.

**Comment by Screwtapello** [comment]
> ...you are seeing the expected behaviour: the selection anchor is on the space, and cursor on the a. w selects to next word start, but as we use the capital version W, we dont move the anchor, only the cursor...

I've experimented a little further. Based on the example in the first comment, I tested pressing `W` after pressing `b` when the cursor was on "c" or "d", producing the following variants:

- cursor on "a", anchor on "c": `W` moves the anchor and the cursor
- cursor on "a", anchor on space: `W` only moves the cursor

It's confusing to me that the behaviour of `W` depends on the position of the anchor as well as the position of the cursor.

(there was a discussion about this on IRC the other day, but I wanted to leave a comment here as a more permanent record)

**Comment by nedp** [comment]
> `W` is an extending selection primitive, the way that usually works is by only moving the cursor, and keeping the anchor as it was.
>
> So, in your use case, you are seeing the expected behaviour: the selection anchor is on the space, and cursor on the a. w selects to next word start, but as we use the capital version `W`, we dont move the anchor, only the cursor, and we end up with a cursor and anchor at the same place (on the space).

This isn't how it works at the moment.

Start:

```
abc def
^~~~
```

Expected, when pressing `W` - cursor moves forward to next word, putting cursor and anchor at same place:
```
abc def
   ^
```

Actual, when pressing `W` - anchor moves to previous cursor location, cursor moves forward to next word, putting anchor and cursor around the current word:
```
abc def
~~~^
```

As far as I can tell this occurs whenever the `W` would move the cursor past the current anchor.

**Comment by mawww** [comment]
Yep thats right, we have a more complex behaviour going on, I am experimenting with the simpler "just keep the anchor wherever it is" behaviour, and it changes a few things, but as far as I see it does not break any use cases (its more that I have some muscle memories that take avantage of the previous behaviour, like `bGl` that needs to be changed to just `b<a-l>`).

I think I'll push that change soon, as it simplifies Kakoune editing model.

**Comment by mawww** [comment]
That has been fixed.
