### ISSUE TITLE
Is it possible to use the popup window for documentation?

### ISSUE THREAD

**Issue by AnthonyJacob** [mawww/kakoune#1530]
The idea, that you can explore ex commands of kak without really opening documentation is game changing.

Could this functionality be expanded for **insert** mode for 

1. Programming languages. (e.g. javadoc)
2. All linux commands and for their **flags** that have `man` available.

Is it possible to achieve this trough `.kak`?

**Comment by mawww** [comment]
Hello,

Improving the auto information system is always something we try to do, however I am not sure what you suggest here.

For *insert* mode, we can always display an info box using the `info` command, so a `javadoc.kak` script file could take care of displaying it, its just a matter of somebody writing that. (For example, linters do use that feature to display diagnostics)

For linux commands, I guess that would be the same, a `auto-man.kak` script file could try to do the same, detect the command being written, and display an info box whose content could come from the man page.

So yeah, if I got what you were asking for right, it should be doable with the current infrastructure Kakoune provides.

**Comment by AnthonyJacob** [comment]
Yes, that is exactly what I meant... Great!
