### ISSUE TITLE
Can't disable auto-completion in insert mode

### ISSUE THREAD

**Issue by blastrock** [mawww/kakoune#1543]
I like having the autocompletion for kakoune commands and path completion, but I don't like having it pop while I am typing code unless I ask for it.

So I wrote this in my kakrc:
```kak
hook global InsertBegin .* %{ set window autoshowcompl false }
hook global InsertEnd .* %{ set window autoshowcompl true }
```

The InsertEnd hook seems to work, but the InsertBegin one does not, I still get completion in insert mode.

**Comment by mawww** [comment]
An alternative would be to set the `completers` option empty, so that no completer would trigger during insertion.

Not sure why the InsertBegin hook would fail, I'll need to investigate that.

**Comment by Delapouite** [comment]
I stumbled upon this issue too.

By looking at the `input_handler` code for the `Insert` mode:
https://github.com/mawww/kakoune/blob/master/src/input_handler.cc#L1037
```cpp
class Insert : public InputMode
{
public:
    Insert(InputHandler& input_handler, InsertMode mode, int count)
        : InputMode(input_handler),
…
          m_autoshowcompl{context().options()["autoshowcompl"].get<bool>()},
          m_idle_timer{TimePoint::max(), context().flags() & Context::Flags::Transient ?
                       Timer::Callback{} : [this](Timer&) {
                           if (m_autoshowcompl)
                               m_completer.update();
                           context().hooks().run_hook("InsertIdle", "", context());
                       }}
    {
…
        context().hooks().run_hook("InsertBegin", "", context());
…
    }
```

The timer checks the value of `m_autoshowcompl` which is set once and for all for this insert session in the initialization list, before the constructor runs the `InsertBegin` hook.

A temporary workaround can be:

```hook global InsertIdle .* %{ exec <c-o> }```

**Comment by Delapouite** [comment]
`auto_complete` is now a flag `insert|prompt` and this should let @blastrock achieve what he wants.
This change was introduced in https://github.com/mawww/kakoune/commit/bde72

So I think this issue can be closed.
