### ISSUE TITLE
Set `termcmd` to distribution specific terminal launchers when possible

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1555]
Hi,

Debian provides with the `x-terminal-emulator` wrapper script that automatically picks the terminal configured by the user, or auto-detect it otherwise. The `i3` window manager also has the `i3-sensible-terminal` utility that basically does the same thing.

Maybe those two (along with other similar utilities I don't know about) should be placed at the top of the list in `x11.kak` to follow the user's system configuration?

**Comment by mawww** [comment]
I dont know about that, `x-terminal-emulator` would probably be fine as its distribution provided, and hopefully various distributions standardize on that name, but using `i3-sensible-terminal` seems a bit far fetched.

**Comment by lenormf** [comment]
What about [xdg-terminal](https://cgit.freedesktop.org/xdg/xdg-utils/tree/scripts/xdg-terminal.in) ? It seems to handle the default terminals for the most popular desktop environments, but I don't know if this script is available by default on those systems to warrant using it.

`x-terminal-emulator` seems to be more well known (at least in the Debian community), I think it's a good fit.

**Comment by mawww** [comment]
I'd accept a PR adding x-terminal-emulator and/or xdg-terminal to `x11.kak` terminal detection code. I expect these would probably need to be the highest priority one. One thing that needs to be checked is that these commands take care of unifying the "command to execute" syntax for the underlying terminal.
