### ISSUE TITLE
File completion should start from the directory containing the edited file

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1562]
Currently (as best I can tell) when `completers` contains `filename`, typing a relative path causes Kakoune to start suggesting possible filenames based on the working directory of the server process.

However, it's quite common (for example, in URLs in HTML and CSS, or filenames `#include "somefile"` in C) for relative paths in a a file to be interpreted *relative to the location of that file*, rather than some fixed, external location.

Perhaps file-completion of relative paths could be changed to always start from the location of the open file, perhaps it could take the union of both locations, perhaps there could even be a list of places to search like the current `path` option (or even re-use the current `path` option).

**Comment by mawww** [comment]
Yeah, I think my favorite way to fix that would be to add something to refer to current buffer directory, like `.` refers to current directory, `..` parent directory... I am not sure what would be a good symbol for it though, maybe something like `.~` or `...`. That way we could just add it to the `path` option (probably as default).

**Comment by lenormf** [comment]
What about `%`?

**Comment by Screwtapello** [comment]
`%` was my first guess too, but I imagine people are going to want to set `path` with Kakoune's regular quoting syntax, and that's going to get pretty complex pretty quickly.

Now that I think about it, if the filename completer respected `path`, this could just be done as:

```
hook global BufOpenFile / %{set-option buffer set-option -add buffer path %sh{dirname "$kak_buffile"}}
hook global BufCreate / %{set-option buffer set-option -add buffer path %sh{dirname "$kak_buffile"}}

```

(or something like that, I don't yet fully understand exactly how scopes work)

Note that the regex is "/" to match all buffers that represent an actual path, and avoid things like `*grep*`.

So that it works out-of-the-box, perhaps those hooks could go into the Kakoune standard library somewhere?

**Comment by lenormf** [comment]
I think the idea behind having a character that expands to the directory path of the current buffer is that we could just add it to the default value of `path` and not be bothered adding code to our local configuration.

**Comment by mawww** [comment]
as you already realized, `%` would be a bit painful to work with as it would need to be escaped. I think the first thing to do would be for the filename completer to respect the path, and then @Screwtapello 's hooks should already provide the functionality (btw its the BufNewFile and BufOpenFile hooks you want, BufCreate is called for every buffer, including the ones that are not linked to a file).

Not sure if we really need to go all the way with a path element that refers to the current buffer directory. I suspect the hook solution is good enough.

**Comment by lisael** [comment]
FWIW, I've solved @Screwtapello's issue with

```
map global user e ":edit-from-file<ret>" -docstring "Edit a file, searching from current file's directory"

def -hidden edit-from-file %{
    %sh{
        dn=$(dirname $kak_buffile)
        echo "exec :edit<space>$dn/"
    }
}
```

**Comment by mawww** [comment]
I realized that we already have some hardcoded logic that does that (for `ga` for example), so I figured it could just be generalized.
