### ISSUE TITLE
Key 'a' begins a selection and extends it while typing. 

### ISSUE THREAD

**Issue by nervecenter** [mawww/kakoune#1575]
The selection begins on the highlighted character, moves to the space after for editing (extending it), enters insert mode, and every additional typed letter extends the selection to include the typed content.

I imagine this is not the intended behavior. I imagine it should behave like 'i' where insert mode begins without a selection being extended, only held if there was one previously.

If the current behavior is intended, apologies.

**Comment by lenormf** [comment]
Hi,

This is documented in the [FAQ](https://github.com/mawww/kakoune/blob/master/doc/manpages/faq.asciidoc#why-does-a-extend-the-current-selection-but-i-leaves-it-untouched-):

>Selections are ranges of characters whose delimiters are an "anchor" and a "cursor", and inserting characters is always done before the cursor in insert mode.

>Consequently, using the append primitive (`a`) nudges the cursor forward to make room for characters, effectively extending the current selection since the anchor remains immobile, even when the anchor and the cursor are at the same location. By opposition, using the insert primitive (`i`) merely adds characters before the cursor, which never modifies the current selection.

**Comment by nervecenter** [comment]
Okay, that makes perfect sense. I'll keep the anchor/cursor scheme in mind going forward.
