### ISSUE TITLE
A (insert at end of line) not moving to end of line

### ISSUE THREAD

**Issue by aver-d** [mawww/kakoune#1580]
Hi, I'm trying to implement an indentation behaviour when the cursor is already positioned on top of a closing brace. I have disabled other indentation hooks to consider this in isolation.

I have a line with content `1234 {}`. The cursor is on the closing brace. In insert mode, I press return. I now want to convert
```
1234 {
}
```
to
```
1234 {
    _
}
```
with the cursor positioned at the underscore, still in insert mode.

Ok, so I set up the following `InsertChar \n` hook, which (almost) works:

```
def indent %~
  try %[
    exec -draft <a-x><a-k>^\h*}\h*$<ret> k<a-x><a-k>\h*\{$<ret> <a-o> JJ <a-\;> <a-&> j <a-gt>

    # Now move to line above and resume insert mode
    exec <esc> k A
  ]
~
```
The problem I'm having is with the final `A`. The cursor always stops one column short of expected – that is, it stops on the final whitespace char (under the number 4), not the position right at the end of the line (after the indentation).

But…, if I comment out the second exec line and instead just manually type the keys

`  <esc> k A`

Then `A` works as I would expect: the cursor is positioned after the indentation.

I also tried other things like adding an extra `<right>`, but the final cursor position is always one to the left of the end of line.

Thanks for any help to get the cursor at the end. Apologies if I'm misunderstanding the expected behaviour, and thanks for all the work in making Kakoune.

**Comment by lenormf** [comment]
It's as if insert mode was left right after the hook was executed, then re-entered immediately after, causing the anchor to be displaced on the last character of the line.

Your code is correct, I think it's a bug.
