### ISSUE TITLE
how do I set tab-width?

### ISSUE THREAD

**Issue by abitofalchemy** [mawww/kakoune#1588]
I edited this file to set the tabwidth to a width of 2: `$MY_KAK_DIR/share/kak/rc/extra/editorconfig.kak` but when I insert a new tab, I get 4 spaces. How do I set my tab-width (indentwidth, tabstop) to 2 universally on my system?

**Comment by Screwtapello** [comment]
The `editorconfig.kak` file is a script that teaches Kakoune to understand [EditorConfig](http://editorconfig.org/) files in the current directory.

If you want Kakoune to use two-space indents all the time, put something like the following into `~/.config/kak/kakrc`:

    hook global InsertChar \t %{ exec -draft -itersel h@ }                      
    set global tabstop 4                                                        
    set global indentwidth 4                                                    

(the "hook" line makes Kakoune expand tabs as you type them)

See [Indentation & Tabulation](https://github.com/mawww/kakoune/wiki/Indentation-&-Tabulation) in the wiki for more details.

**Comment by abitofalchemy** [comment]
Great, this works.

**Comment by hockeybuggy** [comment]
Seems like the up to date wiki page is: https://github.com/mawww/kakoune/wiki/Indentation-and-Tabulation ("and" rather than "&")
