### ISSUE TITLE
Convenience shortcuts in command/prompt mode

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1589]
Hi,

I've grown tired of hitting the backspace key repeatedly when using the `:e<c-r>%` idiom, it'd be nice to have at least this one implemented in the input handler.

Thanks.

**Comment by jkonecny12** [comment]
Yeah, I proposed something similar some time ago and I'm still for this feature.

**Comment by mawww** [comment]
Hum, what exactly are you trying to erase ? we have basic readline support in prompt mode, so you can at least use `<c-b>` and `<c-k>` to remove part of the filename (I assume you want to remove the filename from the path).

**Comment by lenormf** [comment]
It works in that particular case, but I need a mapping to remove the word that precedes the cursor often, and I can't use `<c-k>` for that, in the middle of a command.
