### ISSUE TITLE
compiling on CentOS 7: no matching function for call to `Kakoune::HashMap`

### ISSUE THREAD

**Issue by abitofalchemy** [mawww/kakoune#1592]
This is the error I get when I try to compile on CentOS 7. Does any one have an idea how I can fix the src to get past this error? 

```
alias_registry.cc:27:35: error: no matching function for call to ‘Kakoune::HashMap<Kakoune::String, Kakoune::String, (Kakoune::MemoryDomain)11>::find(Kakoune::StringView&) const’```

**Comment by lenormf** [comment]
What compiler (with version) are you using? Are there other compilation errors (paste the full log please)? Looks like the template wasn't instantiated, which could be a compiler version issue.

**Comment by abitofalchemy** [comment]
These are the versions. Does my `g++` need to be at 4.9* ?
```
$ gcc --version
gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[@CND7182825 ~/Downloads/kakoune/src]
$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by lenormf** [comment]
Yes, according to the documentation:

>A C++14 compliant compiler (GCC >= 5 or clang >= 3.6) along with its associated C++ standard library (libstdc++ or libc++)

**Comment by abitofalchemy** [comment]
will try this and see how it goes.

**Comment by abitofalchemy** [comment]
The error persists, here is a filtered copy of the output. What ever I can do to help, let me know. I have a Zbook with CentOS 7 running.

my new version is:
```
$ g++ --version
g++ (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``

```
$ make >kak.log 2>&1
[@CND7182825 ~/Downloads/kakoune/src]
$ grep -i error kak.log
hash.hh:69:16: error: template declaration of ‘constexpr const bool Kakoune::IsHashCompatible’
string.hh:102:1: error: body of constexpr function ‘constexpr Kakoune::ByteCount Kakoune::strlen(const char*)’ not a return-statement
string.hh:410:37: error: template declaration of ‘constexpr const bool Kakoune::detail::is_string’
string.hh:412:51: error: ‘is_string’ was not declared in this scope
string.hh:412:61: error: template argument 1 is invalid
string.hh:412:64: error: expected unqualified-id before ‘>’ token
string.hh:415:47: error: ‘is_string’ was not declared in this scope
string.hh:415:57: error: template argument 1 is invalid
string.hh:415:60: error: expected unqualified-id before ‘>’ token
string.hh:425:52: error: ‘format_param’ is not a member of ‘Kakoune::detail’
string.hh:433:63: error: ‘format_param’ is not a member of ‘Kakoune::detail’
hash_map.hh:159:9: error: ‘IsHashCompatible’ was not declared in this scope
hash_map.hh:159:51: error: template argument 1 is invalid
hash_map.hh:162:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:162:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:176:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:176:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:179:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:179:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:182:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:182:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:196:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:196:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:209:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:209:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:226:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:226:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:247:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:247:65: error: expected ‘>’ before ‘<’ token
hash_map.hh:254:43: error: ‘EnableIfHashCompatible’ does not name a type
hash_map.hh:254:65: error: expected ‘>’ before ‘<’ token
coord.hh:94:37: error: no matching function for call to ‘Kakoune::LineAndColumn<Kakoune::BufferCoord, Kakoune::LineCount, Kakoune::ByteCount>::LineAndColumn(<brace-enclosed initializer list>)’
coord.hh:101:37: error: no matching function for call to ‘Kakoune::LineAndColumn<Kakoune::DisplayCoord, Kakoune::LineCount, Kakoune::ColumnCount>::LineAndColumn(<brace-enclosed initializer list>)’
alias_registry.cc:13:35: error: no matching function for call to ‘Kakoune::HashMap<Kakoune::String, Kakoune::String, (Kakoune::MemoryDomain)11>::find(Kakoune::String&)’
alias_registry.cc:22:27: error: no matching function for call to ‘Kakoune::HashMap<Kakoune::String, Kakoune::String, (Kakoune::MemoryDomain)11>::remove(Kakoune::StringView&)’
alias_registry.cc:27:35: error: no matching function for call to ‘Kakoune::HashMap<Kakoune::String, Kakoune::String, (Kakoune::MemoryDomain)11>::find(Kakoune::StringView&) const’
string.hh:425:105: error: no matching function for call to ‘Kakoune::ArrayView<const Kakoune::StringView>::ArrayView(<brace-enclosed initializer list>)’
array_view.hh:39:15: note:   no known conversion for argument 1 from ‘<type error>’ to ‘const std::initializer_list<const Kakoune::StringView>&’
array_view.hh:22:15: note:   no known conversion for argument 1 from ‘<type error>’ to ‘const Kakoune::StringView&’
array_view.hh:14:7: note:   no known conversion for argument 1 from ‘<type error>’ to ‘const Kakoune::ArrayView<const Kakoune::StringView>&’
array_view.hh:14:7: note:   no known conversion for argument 1 from ‘<type error>’ to ‘Kakoune::ArrayView<const Kakoune::StringView>&&’
make: *** [.alias_registry.debug.o] Error 1
```

**Comment by danr** [comment]
Did you try it with a GCC version >= 5? That's what the documentation says is required. (Not 4.9.*)

**Comment by mawww** [comment]
@abitofalchemy Kakoune now requires a C++14 compliant compiler, that's means at least gcc 5.1. Unfortunately gcc 4.9 is not supported anymore.
