### ISSUE TITLE
Allow shell scopes to access all of the editor's context

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1605]
Hi,

Spawned by #1604, I wonder if it would be possible to have an elegant way of allowing shell scopes to have access to the editor's context at the time of expansion. In other words, an optional way to have kakoune inject all the `$kak_*` variables to the scope.

I thought about a command flag, or maybe kakoune could create a named pipe, pass its path to the scope in an environment variable, and let the scope read on it? Both these ideas don't sound good for multiple reasons, but the feature itself (however implemented) would allow utilities within shell scopes to access options/data the same way a raw shell scope is.

Example:

```
%sh{
  my_utility_coded_in_cpp "$@"
}
```

As of today, the utility in the above shell scope cannot have access to -say- `$kak_buffile` because this expansion wasn't hardcoded in the scope.

HTH.

**Comment by mawww** [comment]
What's wrong with

```
%sh{
    my_utility_coded_in_cpp "$kak_thing_1" "$kak_thing_2"...
}
```

exposing all possible values through the env seems a bit overkill to me, especially as some can be arbitrary big.

**Comment by lenormf** [comment]
The premise was that a command might need access to many options whose names are decided at runtime, so with the above pattern you would need to expand all of the editor's known options, since you don't know exactly which ones will be needed.

**Comment by Delapouite** [comment]
Related issue https://github.com/mawww/kakoune/issues/1400

**Comment by lenormf** [comment]
I haven't checked, but is this fixed by the “command-fd” feature? https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc#command-and-response-fifo

**Comment by mawww** [comment]
Yep, I think this is done.
