### ISSUE TITLE
How does `yp` on multiple selections work?

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1608]
Re. #829 
> @mawww : If you have multiple selections while pasting, p will paste first yank on first selection, second yank on second selection, third on third.

Given selections where [[ ]] is primary:
```
[foo]
[bar]
[[baz]]
```
-`y` results in an info message that: `yanked 3 selections to register "`.
`p` results in:
```
[foo]baz
[bar]baz
[[baz]]baz
```

How do I instead paste so as to get:
```
[foo]foo
[bar]bar
[[baz]]baz
```

**Comment by mawww** [comment]
Here I with `yp` I get
```
[foo]foo
[bar]bar
[[baz]]baz
```

I do not know how come you do not get this behaviour. One reason I can think of is that you'd have yanked `baz` before creating the multiselection, but that does not match what you describe.

**Comment by lenormf** [comment]
Does anything different happen when you use `\y` and `\p` ?

**Comment by nochiel** [comment]
> Does anything different happen when you use \y and \p ?

I had forgotten that `p` is mapped in my rc to use xclip.

> I do not know how come you do not get this behaviour.

My mistake. I should have checked my `rc` first.

**Comment by nochiel** [comment]
Given the above multiselections, what should `kak_reg_dquote` contain?
Currently it only seems to contain the yank from primary. i.e what
expansion should I use to get all the yanked multiselections' text?

**Comment by mawww** [comment]
Unfortunately, I dont think we have a way to get the full content of a register, only the value for the main selection. Provided there is a good use case for it (and I expect there will be, at least once we try to provide mechanisms for saving/restoring sessions), we should devise a way to do so.
