### ISSUE TITLE
Column highlighters do not align

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1615]
Steps to reproduce:

1. I'm using Kakoune built from 2f251c9861dfdc4c07a60295b6cdfe093dbd7b59 with optimizations (debug=no)
2. Start Kakoune:

        kak -n

3. Insert some simple text:

       
       a
       ab
       abc
       abcd
       abcde
       abcdef
       abcdefg

    (note that blank line at the beginning)
4. Add some column highlighting:

       :addhl column 3 default,blue
       :addhl column 5 default,green
       :addhl column 7 default,red

Expected result:

- Vertical stripes of blue, green and red behind columns 3, 5 and 7 respectively.

Actual result:

![image](https://user-images.githubusercontent.com/1450918/31159762-0fc1ef22-a917-11e7-920b-3519ee25c055.png)

**Comment by lenormf** [comment]
![](https://my.mixtape.moe/nfzaxt.png)

It does look nice.

**Comment by Delapouite** [comment]
Similar issue : https://github.com/mawww/kakoune/issues/1023

**Comment by mawww** [comment]
One column highlighter ought to be enough for everybody...

More seriously, yeah, thats a bug...
