### ISSUE TITLE
Contribution: Bépo remapping

### ISSUE THREAD

**Issue by guillaumecherel** [mawww/kakoune#1616]
I'm working with a bépo keyboard layout and I've created a complete remapping for kakoune so that commands in normal, view and goto mode stay at the same position as they are on a qwerty layout.

I also wrote an awk script that could be reused to easily generate such mapping for other layouts (like dvorak...)

I'd like to make it all available. How can I do?

**Comment by Delapouite** [comment]
Hi.
You could create your own `guillaumecherel/kakoune-bepo` repository on GitHub. Then it would be visible on this list: https://github.com/search?q=topic%3Akakoune&type=Repositories

On a side node, you may be interested in this keyboard layout: http://qwerty-lafayette.org/

**Comment by guillaumecherel** [comment]
I'll do this, thanks!

**Comment by Delapouite** [comment]
For future searches: https://github.com/guillaumecherel/bepo
