### ISSUE TITLE
kak dyld errors after homebrew upgrade

### ISSUE THREAD

**Issue by amckinlay** [mawww/kakoune#1623]
Recently homebrew updated `boost` from 1.65.0 to 1.65.1. Starting `kak` after this upgrade resulted in:

```
▶ kak
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost16re_detail_10650011raw_storage6resizeEm
  Referenced from: /usr/local/bin/kak
  Expected in: /usr/local/opt/boost/lib/libboost_regex.dylib

dyld: Symbol not found: __ZN5boost16re_detail_10650011raw_storage6resizeEm
  Referenced from: /usr/local/bin/kak
  Expected in: /usr/local/opt/boost/lib/libboost_regex.dylib

[1]    96681 abort      kak
```

Does kakoune need to be recompiled every time boost is updated? How would this work if kakoune is ever published as an official homebrew formula? As far as I know, homebrew doesn't have a mechanism to handle this.

**Comment by mawww** [comment]
Hello,

As boost is dynamically linked, it can happen that boost updates would break the compiled Kakoune binary. I am not sure why it happens here, as I would not expect that updating from 1.65.0 to 1.65.1 would break binary compatibility.

In any case, it seems very likely we are going to get rid of boost soon-ish, as the custom regex implementation is now feature complete, and just needs to be more widely tested. Once we will switch to this regex implementation, we will be able to drop boost entirely.

Closing this issue as I dont see how we could fix it on our side, for the time being it seems you'll need to recompile.

**Comment by amckinlay** [comment]
Indeed the missing symbol is an internal Boost.Regex function named `raw_storage::resize` whose namespace [is versioned](https://abi-laboratory.pro/tracker/compat_report/boost/1_65_0/1_65_1/d64da/abi_compat_report.html). I don't understand enough about C++ and linking to know why kakoune links to a private symbol. Thanks for the response.
