### ISSUE TITLE
Cannot build on Solus3

### ISSUE THREAD

**Issue by payasrelekar** [mawww/kakoune#1640]
I am on Solus 3. Here's what I when I try to compile.

In file included from commands.cc:23:0:
regex.hh:9:27: fatal error: boost/regex.hpp: No such file or directory
 #include <boost/regex.hpp>
                                                  ^
compilation terminated.
make: *** [Makefile:75: .commands.debug.o] Error 1

I have libboost installed, but I can't locate it. I am fairly new at this so not sure where else to look.

**Comment by lenormf** [comment]
Try installing `libboost-devel`.

**Comment by payasrelekar** [comment]
Yep, that worked. Thanks. Closing issue.
