### ISSUE TITLE
Add scrollbar

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#165]
Vertical:

```
│
║
│
```

Horizontal:

```
─═─
```

**Comment by jkonecny12** [comment]
I think this should be as an extension not in kakoune core. Basically you don't need scrollbar in command line editor thought.
I'm thinking about creating folder for extensions you don't want after installation but they will be easy to enable. What do you think @mawww ? 
Sorry for OT

**Comment by mawww** [comment]
Hum, we might be able to abuse the flag_lines highlighter to display a scrollbar using only .kak scripting, that would probably be slow and clumsy though.

If we implement that, I think it will be much simpler to have it in the c++ code, however I am far from convinced it is worth it.
