### ISSUE TITLE
Add <a-q> command to repeat last command

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1656]
# Commands

- <kbd>Alt</kbd> + <kbd>q</kbd> to store the (whole) last command in the given or macro register
- <kbd>Alt</kbd> + <kbd>Q</kbd> to store the (whole) next command in the given or macro register

# Use case

## Repeat command-line

``` kak
:buffer-next<ret><a-q>q…
```

## Select next match of the selections

``` kak
/<search><ret><a-q>q…
```

## Save a change or text object to repeat

``` kak
<insert><change><esc><a-q>[…]<insert><change><esc>[…]q
```

``` kak
<text-object><a-q>[…]<text-object>[…]q
```

**Comment by danr** [comment]
My initial reason for wanting the `RawKey` was this use case.
Here's a way to implement your `<a-q>`:

    decl str last
    map global normal <a-q> ':exec -with-maps %opt{last}<ret>'
    hook global RawKey ^(?!<a-q>). %{
      set global last %val{hook_param}
    }

**Comment by danr** [comment]
I realized I had misunderstood what "(whole) command" meant, so my proposed script does not solve this issue.

**Comment by danr** [comment]
Ok so this does what you want (I believe). The RawKey hook has to be used instead of normal mappings because there seems to be no way to execute commands from a `map` without changing the `:` register.
The idea of using the `:` register was @lenormf's.

    decl str last
    hook -group kakrc global RawKey <a-Q> %{
      eval "%opt{last}"
    }
    hook -group kakrc global RawKey <a-q> %{
      set global last "%reg{:}"
      echo "last: %opt{last}"
    }
    unmap global normal <a-q>
    unmap global normal <a-Q>

**Comment by Delapouite** [comment]
A variant I've been using lately:

```
hook global RawKey Y %{ set-register @ ":%reg{:}<ret>"}
```

**Comment by danr** [comment]
Ah, so you can do `Yq` to replay the last command? That's nifty.

**Comment by mawww** [comment]
There seem to be various ways to do that already, and I dont think this would really need to be built-in. Closing.
