### ISSUE TITLE
Select "content on line" surrounding object

### ISSUE THREAD

**Issue by nuao** [mawww/kakoune#1657]
I'd like to suggest an addition to the menu "select inner/outer surrounding object"

This is to select the current line then trim whitespace at either end. Or viewed another way, go to first non-whitespace character on line then extend to final non-whitespace character.

The effect can currently be achieved with `giGl`, but the object menu would be more convenient.

More generally, given the "custom object desc" already exists, it would therefore also be nice to have the ability to customize the list of selectable objects with user-chosen keybindings. This way users could make this type of change independently and have their own list.

Thanks for your consideration.

**Comment by occivink** [comment]
You can actually customize the text objects. For example, you can do 

map -docstring line global object l '<esc>giGl'

The `<esc>` is here to exit the selection menu.

**Comment by nuao** [comment]
Ah, thanks very much. I never knew.
I submitted a possible PR so that the main Readme matches the information given in the map command's info box.
