### ISSUE TITLE
String delimiters ' and " in matching_pairs

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1675]
Right now kakoune always claims `no selections remaining` if you put `':'` or `":"` into the `matching_pairs` option. 

Feature request: make this select the quoted text.

**Comment by mawww** [comment]
Currently matching_pairs is strictly for different open/close character, it will not work for the same character as there is no way to know if what we hit is an opening/closing character (so we do not know which direction to search for the matching char).
