### ISSUE TITLE
CompletionCandidateSelected  hook feature request

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1676]
LSP supports getting the documentation of a completion entry lazily: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completionItem_resolve

I would like a hook that fires when a candidate gets selected in the completion list. The `hook_param` will need to contain which kakoune option the item belongs to, and the entry of the item. 

I could just then set and updated value to the option which contains the extra docstring, so all other functionality to update the documentation on the fly should be in place.

Thanks!

**Comment by danr** [comment]
I think it would be enough to add a hook somewhere around here with information from the `candidate` variable: https://github.com/mawww/kakoune/blob/654e3fcb46338f022284a958b4087162dd148b50/src/insert_completer.cc#L379
Does that sound feasible? Will I need to bring extra context to these functions to be able to run a hook?

**Comment by mawww** [comment]
I think it should work, however the remaining problem is to determine how to identify clearly the completion candidate so that it can be reused by the hook.
