### ISSUE TITLE
Support for # key to populate the selection index in normal params

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1689]
Hello

When using numbers before pressing a key in normal mode, they are designated as a **count**.
Which is fine most of the time. But for some keys, these numbers have another meaning. They are used to designate the *index* of the selection we want to impact.

So we have an ambiguity on *quantity* vs *position*.

https://github.com/mawww/kakoune/blob/master/src/normal.hh#L13-L17
```
struct NormalParams
{
    int count;
    char reg;
};
```

what about adding a `int index` to this struct ?

The `#` is still free and already denotes the selection index meaning in registers.
This way we could to stuff like that : `3#4<space>`.  "clear 3 selections starting from index 4".

This value would also be displayed in the status bar.

**Comment by alexherbo2** [comment]
The design of parameters is currently same than the one of vi.

vi implemented the count support, and Kakoune took from it.

vi has a single cursor, so the deal with indexes doesn’t exist.

When we think of multi-selection, it makes sense to support both count and index to commands.

So you have my big :smile_cat: for the proposal.

Showing the path of an index support is now up to Kakoune.

**Comment by mawww** [comment]
So, what would we do with commands that use count as an index at the moment (like `<space>`), do we make them require pressing `#` as well ? Do we treat count as an index even though we have a separate concept for the index ? what do we do when both count and index are specified ?

**Comment by alexherbo2** [comment]
Count could have an identifier as well.

So that we can default to count or index when no identifier is specified.

**Comment by mawww** [comment]
I think we already have a nice way to index selections in many cases: The main selection. We can move the main selection with <kbd>'</kbd>, maybe it would make more sense to change the few commands that use `count` as an index to use it as a count (<kbd>&lt;space&gt;</kbd> for example). You example <kbd>3#4&lt;space&gt;</kbd> would then be (assuming main selection is the first one) <kbd>2'4&lt;space&gt;</kbd>.

Do you have some other use cases that would be much easier with <kbd>#</kbd> than using the main selection ?

**Comment by mawww** [comment]
I dont think I'll introduce this, especially now that we can change the main selection in two directions with `(` and `)`.
