### ISSUE TITLE
Unable to reconnect a suspended client

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1690]
Hi,

Here's how to reproduce the issue:

* start `kak`
* create a new client with `:new`
* suspend the first client with `^Z`
* close the second one with `:q`
* resume process execution of the first client with `fg`, the following error message appears:

```
connect to /tmp/kakoune/user/1234 failed
disconnecting
```

HTH.

**Comment by mawww** [comment]
Ok I see what is going on here, when we suspend the first client, which is both client and server, we fork the server in the background, as we have another client (the second one) to serve. But when that second client quits, the server ends up with no clients connected (the first client is now suspended, waiting to resume before reconnecting to the server as a plain client), so it quits, and on resume the first client finds no server waiting for it.

I'll see how that can be fixed, but this single process client mode starts to be more and more complex, maybe its time to bite the bullet and always have clients running as a separate process.
