### ISSUE TITLE
selection union/merge for disjoint selections

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1691]
Summary: Given n number of current disjoint selections, I'd like to merge the regions between all of them. (I think I'm misunderstanding how selections are supposed to work.)

Consider the text:
```
|
fun frob { ...}
fun borf1 {...}
fun frob {...}
fun borf2 {...}
fun frob {...}
fun borf3 {...}
```

I would like to be able to do something like: `/fun frob<ret>NN<a-M>` to select everything from the first to the last selection inclusive.

Currently, if I do: `/frob<ret>NZN<a-z>u`, I don't get the result I'm looking for.

What's the correct way to do this?

**Comment by mawww** [comment]
So, if I understand correctly, you want something that would replace the set of current selection with a single selection starting at the minimum point of that set and finishing at the maximum point of them ?

**Comment by nochiel** [comment]
>  if I understand correctly, you want something that would replace the set of current selection with a single selection starting at the minimum point of that set and finishing at the maximum point of them ?

Yes, exactly.

**Comment by alexherbo2** [comment]
Kakoune exposes the range of the selections in `selections_desc` [expansion][Expansions], which looks like:

```
<anchor-line>.<anchor-column>,<cursor-line>.<cursor-column>[:]…
```

A long side `selections_desc`, you also have the `:select` [command][Commands], which takes a selection description.

``` kak
define-command merge-selections -docstring 'Merge selections' %{ %sh{
  echo select ${kak_selections_desc%%,*},${kak_selections_desc##*,}
}}
```

[Commands]: https://github.com/mawww/kakoune/blob/master/doc/pages/commands.asciidoc
[Expansions]: https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc

**Comment by nochiel** [comment]
@alexherbo2: Thanks. I thought I might have missed an obvious way to do it with default commands.
