### ISSUE TITLE
Jsx Support

### ISSUE THREAD

**Issue by ZehCnaS34** [mawww/kakoune#1700]
I would like to create a jsx highlighter, are there any tips I should know before I start? I've looked at that way markdown handles nested highlighters, but I think jsx would be a bit more complex since it can handle recursive highlighters e.g. js>html>js>html. Any help would be greatly appreciated.

**Comment by Delapouite** [comment]
related issue about js template strings : https://github.com/mawww/kakoune/issues/1670

**Comment by danr** [comment]
I made an attempt some time ago, maybe you can get some inspiration from there:

https://github.com/danr/kakoune/commit/26d5e57b729f1f262d68a9646da3a68e6e92c21f

**Comment by mawww** [comment]
JSX support has been merged.
