### ISSUE TITLE
Cannot scroll down with mouse wheel in gnome-terminal

### ISSUE THREAD

**Issue by whereswaldon** [mawww/kakoune#1701]
Problem:
When running kakoune inside of gnome-terminal, I can scroll up in the open buffer using a two-finger scroll on my trackpad, but I cannot scroll down. Nothing happens.

Kakoune version: `386f595a494f2fca3d52388a9d64c35bfd8bb3c6`
Distro: Pop!_OS (essentially Ubuntu 17.10)
Gnome Terminal version: GNOME Terminal 3.24.2 Using VTE version 0.48.4 +GNUTLS -PCRE2

I don't have this problem in other terminal emulators, so I'm willing to believe that it's gnome-terminal's fault. I just wanted to document this problem and to check whether it was on the emulator side or not.

Thanks for making kakoune!

**Comment by Screwtapello** [comment]
The traditional ncurses API (ncurses v5) was designed to support four buttons, back in the days when most mice only had three or fewer. These days, they wind up mapped to left-click, middle-click, right-click and scroll-up.

The new ncurses API (ncurses v6) is updated to support five buttons, but [it is not yet packaged in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=230990), which means it's generally not available in Debian-derived distros like Ubuntu and Mint (and, apparently, Pop!_OS).

I'm surprised to hear that you don't have that problem in other terminal emulators... in which terminal emulators does Kakoune support scroll-down on Pop!_OS?

**Comment by mawww** [comment]
@whereswaldon One thing you can try is to play with `set global ui_options ncurses_wheel_down_button=<number>` to see if in gnome-terminal, wheel down gets bound to another button than the default one (5).

**Comment by whereswaldon** [comment]
@Screwtapello 
Thanks for the thorough explanation! That makes a lot of sense. I think that I actually would have this problem in any terminal emulator on Pop!_OS. I was mistakenly generalizing because I've used other distros on this hardware and didn't experience the problem, but every time I've used GNOME (only Ubuntu and Pop!_OS) I've had the issue. Your explanation completely answers my questions. I assumed the problem was GNOME, not the distro underneath it. On Arch it works fine, but because of a newer ncurses, not my choice of DE.

@mawww  I'll play with that, thanks for the tip!

You can probably close this issue. It's clearly not a kakoune problem.
