### ISSUE TITLE
alt+J doesnt works (on OSX at least)

### ISSUE THREAD

**Issue by radare** [mawww/kakoune#171]

**Comment by mawww** [comment]
Can anybody using Kakoune on OSX comment if this issue is still present ?

**Comment by elegios** [comment]
It seems to work for me. There is a setting in the terminal to send the option key as meta, which isn't necessarily on (I believe i had it turned off), but that doesn't sound like what was the problem here. So I guess raw fixed it?

**Comment by mawww** [comment]
Thanks for the report, closing this one.

**Comment by guillaumecherel** [comment]
I had to select 'Left Option key acts as "+Esc"' for alt to work on os X Yosemite.
