### ISSUE TITLE
Unify the syntax of the highlighter add/remove commands

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1712]
Hi,

There's a slight discrepancy between the syntax expected by the `add-higlighter` command and that expected by the `remove-highlighter` command:

```
add-highlighter window …
```

and

```
remove-highlighter window/…
```

Could this be modified, to unify the syntax better?

Thanks.

**Comment by mawww** [comment]
While I agree that is an unfortunate inconsistency in the syntax, I hope explaining it will make it a bit less surprising:

`add-highlighter` first parameter is a *group* (or, in filesystem lingo, a *directory*) in which to put the newly created highlighter. So  `add-highlighter window ...` means "add a new highlighter inside the `window` group), and `add-highlighter window/foo/bar ...` would mean "add a new highlighter inside the `window/foo/bar` group.

That newly added highlighter will have an *id* (*filename*), and its path will be `<group>/<id>`. That id is automatically generated from the parameter passed to the highlighter.

`remove-highlighter` removes an highlighter identified by a *path*. We could have that separated into a *group* and and *id* parameter, but I thought it was pretty artificial to do that when we could reference that highlighter with a direct path in other contexts.

Various possibilities exists to change that. We could chose the id explicitly, but that would be impractical, as most of the time we do not care about that, and choosing one id is just lost time. Its been proposed to add syntax to mean "autogenerate", but I think that will just add confusion.

Until we find a satisfying alternative, I think the status quo is good enough, and while it may surprise at first, it makes a bit more sense once we see the first parameter of `add-highlighter` as the group in which to put that new highlighter.

**Comment by lenormf** [comment]
I understand the reason why the syntax is the way it is, and it's fine by me, but that might scare some users away from making their own highlighters? Those who don't care about the technical reasons why the syntax is different will only see that removing is harder than adding, because the `id` comes out of nowhere and is used in a path rather than a -simple- unique argument.

Nothing needs to be changed right now, but maybe allowing a name to be picked might be a possibility in the future.
