### ISSUE TITLE
<a-A>: extend text-object by repeating the previous one.

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1715]
Hi.

On the following example, the cursor is on Wesminster:
```
…
{
  "user": {
    "address": {
      "street": "10 Downing Street",
      "city": "Westminster"
    }
  }
},
…
```

Using text-objects, I would like to select the whole object.
One way to do it is `3<a-a>{`. But in this case I need to know (or calculate) the count in advance, which is not always handy in deeply nested structure.

So I can do it step by step: `<a-a>{`, `<a-a>{` and again `<a-a>{`. It's quite interactive but a bit cumbersome to type.

What about typing `<a-a>{` the first time and then kakoune remembers that the `{` was the last text-object I used, so that it will be used again when doing a `<a-A>` ?

This way:
`<a-a>{<a-a>{<a-a>{` turns into:
`<a-a>{<a-A><a-A>`

At first it may seems that we only saving 1 key stroke by "step". True, but that's also the case of many other kakoune normal commands that are just variant of other primitives.
I think that the capital `A` indicates clearly that we want to *extend* and it follows kakoune convention.

But the real gain is that you keep the `Shift` and `Alt` keys down and only press consecutive `A` without having to do some fingers gymastic to repeat the same selector (`{` in our scenario) again and again.

**Comment by occivink** [comment]
`<a-.>` repeats the last text object selection

**Comment by Delapouite** [comment]
Thanks occivink. Brilliant answer.
I'm going back to bed now, this way I'll say less silly stuff. :)
