### ISSUE TITLE
:execute-keys gives different output

### ISSUE THREAD

**Issue by samuel1** [mawww/kakoune#1719]
`:execute-keys s a b 'c'` produces a prompt with `select:abc` when it should be `select: a b 'c'`

Equally

`:execute-keys <a-|>  printf  "he      llo"` produces `pipe-to:printfhe     llo`

**Comment by mawww** [comment]
Commands are parsed in a similar way the shell parses them. so in your example,  `execute-keys` sees 4 arguments: `s`, `a`, `b` and `c`. `execute-keys` behaviour with multiple arguments is to concatenate them as set of keys. This is pretty useful with complex commands as it means we can group keys together for ease of understanding.

For example we can isolate the regex in `execute-keys s foo.*bar <ret>` to make it easy to see.

To have whitespaces inside your keys, there are two solutions: either quote the whole set of keys: `execute-keys "s a b 'c'"` or use explicit `<space>` `execute-keys s<space>a<space>b<space>'c'`.
