### ISSUE TITLE
execute-keys capture groups wrong

### ISSUE THREAD

**Issue by samuel1** [mawww/kakoune#1721]
Start a file with the line:
`a    hello`

Then entering `1gxsa *([^\n]*)<ret>j"1P` in normal mode will put `hello` on the next line

But entering the same text preceded with `:execute-keys_` will put `____hello` on the next line, where _ denotes whitespace (markdown is stripping spaces out)

I believe this is happening for the same reason as #1719. Since `:execute-keys /a *([^\n]*)` becomes `search:a*([^\n]*)`

**Comment by lenormf** [comment]
`execute-keys` will join up all the parameters you pass to the command, so if you're trying to select data with a regex containing whitespaces, then it needs to be wrapped in double quotes:

```
:exec "1gxsa *([^\n]*)<ret>j"1P"
```

If you don't, the space gets removed, the regex becomes `a*([^\n]*)`, and that's how you end up only with "hello" being captured.

**Comment by mawww** [comment]
An alternative is to write whitespaces explicitely, as `<space>`, when you use whitespace like you did, they are parsed as argument separator, like the shell would do. So, either quote the string so that whitespaces are part of the argument, or write `<space>` expicitely instead of just a ` `.
