### ISSUE TITLE
3 crashes

### ISSUE THREAD

**Issue by samuel1** [mawww/kakoune#1722]
Kakoune crashed 3 times this week when typing random keystrokes

I'm afraid I don't have stack traces, or useful information, other than that those keypresses were probably meaningless gibberish, the result of someone beginning to learn the key mappings

**Comment by mawww** [comment]
Thats pretty bad for Kakoune if it crashed like that, however without any informations its hard to track the root cause.

Could you install xmessage on your system, that way Kakoune will display a message on crash/assert fail. Please post the callstack displayed in that message next time.
