### ISSUE TITLE
Problem with pipe alias

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#1724]
I pipe to `xargs -n 1 expr 1 +` to increment a number that is in a selection.

For quick access I created the following alias
```
alias inc='xargs -n 1 expr 1 +'
```

Piping to inc in kakoune does not return anything. The text will be deleted.

Typing `inc` or `xargs -n 1 expr 1 +` give me the exact same behaviour in my shell (zsh).

`echo $SHELL` prints the same shell `bin/zsh` in kakoune and in the interactive shell.

I could not track this issue down further so some help would be greatly appreciated :)

**Comment by Delapouite** [comment]
Not directly related but if you intend to reproduce vim's `<c-a>` and `<c-x>` to increment and decrement numbers, have a look at this wiki page on bc https://github.com/mawww/kakoune/wiki/Bc

**Comment by Screwtapello** [comment]
Is the problem that `|inc` in Kakoune doesn't increment the selected number? And `inc` is a shell alias defined in `.zshrc`, correct?

For performance reasons, a non-interactive zsh (such as one started by Kakoune's pipe operator) does not read `.zshrc`. If you want quick access to your increment command, probably the best thing is to use Kakoune's `:map` command to bind your xargs command to a key, as described in @Delapouite's link.

**Comment by mawww** [comment]
shell aliases are unlikely to be present in `%sh{...}` as kakoune does not even use your login shell, it uses a shell that is guaranteed to be posix according to the standard, which usually ends up being `/bin/sh`.

Note that we cannot use the user specified login shell as this can be non posix (could be `fish` for example).

We get the shell from the `_CS_PATH` configuration string, which gives us a list of directories that are guaranteed to contain posix compliant utilities, and find the `sh` utility in that. This is the only method we found that was really portable to get a posix shell.

**Comment by FranzSkuffka** [comment]
@Screwtapello - Yes, that is the problem. I updated my issue.

@mawww - Echoing $SHELL in kakoune gives me zsh.

@Delapouite - I do not want to bind to a key.

**Comment by Screwtapello** [comment]
You could make `inc` a shell-script rather than an alias, then it would be available to Kakoune. You'd have to put it somewhere on $PATH, of course.

**Comment by FranzSkuffka** [comment]
Thanks! Done.

https://github.com/FranzSkuffka/dotfiles/blob/master/increment.sh

**Comment by mawww** [comment]
@FranzSkuffka I suspect your `/bin/sh` is a symlink to `/bin/zsh`. The explanation I gave (with _CS_PATH) makes Kakoune a "good unix citizen" in the sense that if we do not end up with a posix shell, its not Kakoune's fault but the distribution that does not respect Posix. The problem is that posix itself does not guarantee that `/bin/sh` will be a posix shell, but it says whatever `sh` you find through `_CS_PATH` should be.

All that said, I suspect `zsh`, when launched as `sh` will be posix compliant (more or less).

**Comment by occivink** [comment]
You can also do `expr 1 + $kak_selection`

**Comment by FranzSkuffka** [comment]
I just love this editor. Can't tell you how much.

**Comment by kaddkaka** [comment]
> You can also do `expr 1 + $kak_selection`

Could you explain that in more detail? Where do type this?

**Comment by occivink** [comment]
After selecting a number, go into pipe mode with `|`, and then run `printf %s $((kak_selection + 1))`

**Comment by FranzSkuffka** [comment]
@kaddkaka here is a demo. Use the pipe `|` in normal mode and then type it there.

https://asciinema.org/a/J5m4mbcGbdz9bGSAuOnFYXoCg

**Comment by kaddkaka** [comment]
What difference does the `printf %s` do?
