### ISSUE TITLE
Support `<a-r>`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1727]
Hi,

We can't preserve the copy register when doing a replacement, so we always have to use `<a-c>` and then type in the replacement text.

HTH.

**Comment by mawww** [comment]
Not sure what you mean, `R` does not yank..

**Comment by lenormf** [comment]
I thought it happened to me yesterday, because maybe `r` was simply `d` then `i`? I just tried again and the copy register isn't modified.
