### ISSUE TITLE
Add ^F and ^B to scroll to next/prev page

### ISSUE THREAD

**Issue by radare** [mawww/kakoune#173]

**Comment by cvlmtg** [comment]
I'd like some default binding for pageup/down too, as e.g. macbooks (and probably other laptops) don't have pageup/down keys
I usually use <c-d> and <c-u> in vim so I created those mappings, but for newcomers or people just curious to try kakoune those two keymaps should make the first experiences a bit more pleasant :)

**Comment by mawww** [comment]
Ok, you convinced me, I'll add that.

**Comment by cvlmtg** [comment]
thanks :)

btw I see only now that my previous messages looks strange... it should have had ```<c-d>``` and ```<c-u>``` in it, but I always forget github doesn't escape angle brackets by default.
