### ISSUE TITLE
add <a-del> to delete word

### ISSUE THREAD

**Issue by valerdi** [mawww/kakoune#1732]
hi,

it would be nice if a-del deletes whole words in insert mode, : and !

**Comment by lenormf** [comment]
You can declare a mapping that binds `<a-del>` to whatever keys you want.

Refer to [the FAQ](https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#why-arent-widely-known-command-line-shortcuts-such-as-c-w-or-c-u-available-in-kakoune-) to know more about why this type of shortcuts isn't a default in insert mode.

**Comment by valerdi** [comment]
ah ok, thanks
