### ISSUE TITLE
shortcut to kakrc

### ISSUE THREAD

**Issue by valerdi** [mawww/kakoune#1740]
i made this command to open quickly my conf

def edit-config -command-completion -docstring "Edit config file kakrc" %{
	e .config/kak/kakrc
}

and also an alias :ec, it could be edit-kakrc also. I found it very handy, maybe we could insert it in core.

**Comment by alexherbo2** [comment]
@valerdi How about #1742?

**Comment by valerdi** [comment]
I think we could have both, i got the idea from spacemacs where you press "SPC fed" to open the config but i also like [#1742](#1742 ) because i also found myself editing autoload files so a shorcut in way ~~/ comes really handy.

**Comment by TeddyDD** [comment]
I'm using `,d` Not sure if it's really needed in core since it's easy to write it yourself.

**Comment by mawww** [comment]
I am not keen on having an hard coded shortcut for that, however we could have an expand for kakoune's config directory. Currently `%val{runtime}` (`$kak_runtime` in shells) expands to the runtime directory (usually `/usr/share/kak`), we could have a similar `%val{config}` that would expand to the configuration directory (which is `${XDG_CONFIG_HOME:-${HOME}/.config}`). Your shortcut could then be implemented in a robust fashion with `edit "%val{config}/kakrc"`.
