### ISSUE TITLE
scrolloff makes invisible the end of the lines

### ISSUE THREAD

**Issue by valerdi** [mawww/kakoune#1741]
Hi, i put a scrolloff of 2,14 but makes disappear the end of the lines if the cursor is at the beginning of the line. The beginning of the lines doesn't disappear if the cursor is far away. The situation is worse with a | tmux pane.

**Comment by mawww** [comment]
Hello,

I did not manage to reproduce your problem here, could you describe more precisely how to reproduce it ? Do you have wrapping on ?

Cheers,

Maxime.

**Comment by valerdi** [comment]
i don't have wrapping on, just opening a file with kak -n and then :set global scrolloff 0,20 for example i get the following 
before:
![screenshot from 2017-12-13 23-01-09](https://user-images.githubusercontent.com/16702295/33964880-4bf8c8ec-e05a-11e7-9770-a49957dfcac7.png)
after:
![screenshot from 2017-12-13 23-01-44](https://user-images.githubusercontent.com/16702295/33964888-527594c0-e05a-11e7-9c69-15410be5ca19.png)

only if i move the cursor near the end of the line the characters appear:
![screenshot from 2017-12-13 23-02-07](https://user-images.githubusercontent.com/16702295/33964909-65841e2e-e05a-11e7-976b-2a3ab184c7a1.png)
