### ISSUE TITLE
Add support to prefix path to the configuration directories

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1742]
How about [mpv’s prefix paths][mpv/manual/paths]?

Where the prefix `~~/` expands to the configuration directory.

[mpv/manual/paths]: https://mpv.io/manual/master#paths

**Comment by mawww** [comment]
We now have `%val{config}` to get the config directory.

**Comment by alexherbo2** [comment]
It’s not as easy to get interactively.

**Comment by mawww** [comment]
That is true, but I think this is good enough, accessing the config directory is not the most common operation either.
