### ISSUE TITLE
Add goto indent begin/end

### ISSUE THREAD

**Issue by notramo** [mawww/kakoune#1749]

**Comment by lenormf** [comment]
Not sure what this issue is about, since there's no message, but there's already `gi`, `ge`, `[i` and `]i` to play with if you need to make your own mappings.

**Comment by notramo** [comment]
Example:
```crystal
# Some lines of code
loop do
    first_line
    second_line
 ▯ line_of_cursor # The cursor is on this line
    another_line
    last_line
end
# More code
```
When the user hits *goto indent begin*, the cursor would jump to the `loop`  statement, and when hits *goto indent end*, the cursor would jump to the `end` statement.
Similar to `[i` and `]i`, but it should jump one more line, remain on the *same column*, and *shouldn't select*, only jump.

**Comment by mawww** [comment]
This is not strictly goto indent begin that you want, use custom text objects for that (you likely want to set them as a mapping)

`map global object l cdo,end<ret>` will make `l` text object handle nicely do ... end objects (including nesting)

**Comment by notramo** [comment]
This wouldn't select the text, only place the cursor on the line before indent start, or the next line after indent end (in the same column).
The `do` and `end` statements are only example. This wouldn't depend on what text is in the target line. It would depend only on indentation.

**Comment by TeddyDD** [comment]
@notramo Maybe something like that would do the job? (map it to some key)
```
# begin
<a-i>i<a-:><a-;>k<a-h>
# end
<a-i>i<a-:>j<a-h>;
```

**Comment by mawww** [comment]
What I understand here is that you want a feature to select to the first line that is less indented than the current line, this should be already doable by going to current indent first line with `[i` then reverse searching for a non empty line with `<a-/>[^\n]`. I dont think we need a builtin object representing that.
