### ISSUE TITLE
Edit current selection primitive

### ISSUE THREAD

**Issue by TeddyDD** [mawww/kakoune#1750]
My proposal is to add switch that would modify insert and append commands to work only for primary selection (similarly how `\` switch disables hooks in insert mode)
This would make working with multiple cursors/selections more powerful without need to select everything multiple times. Using Z is not an option since it always sets last selection as primary. 

I know @occivink wrote plugin with similar functionality but I never managed make it work and I think this feature would fit nicely into "stock" Kakoune.

**Comment by alexherbo2** [comment]
The `#` parameter (suggested by @Delapouite) followed by `i` or `a` command could be used to edit the main selection (assuming `#` with no count is `1` and relative to the main selection).

- #1323
- #1324
- #1689

**Comment by lenormf** [comment]
I would rather have `Z` fixed to restore the primary selection properly, and then allow user to have their own binding to only apply changes to the primary selection (using `Z`/`z`/`space`).
