### ISSUE TITLE
Suggestion: Store ncurses_assistant(s) in text files?

### ISSUE THREAD

**Issue by whereswaldon** [mawww/kakoune#1753]
Today I discovered the ncurses_assistant ui_option, and I love it. I've been using kakoune for almost a year now, but I didn't realize that there were options beyond clippy.

I was wondering what @mawww  and others would think about storing the assistants in text files somewhere in the existing kakoune file hierarchy. Maybe in `/usr/share/kak/assistants` or something like that. This would make it easy to create new ones without bloating this repo. I personally might import a bunch of asciiart and then randomly select one whenever kakoune started, but perhaps this would only be amusing to me.

Clearly this isn't an important feature. I'd be happy to try to implement it myself if there's interest, but I don't want to start down that road if nobody wants it.

**Comment by lenormf** [comment]
This was considered when I added the Dilbert assistant, but it's just too much work for a simple ASCII art.

**Comment by danr** [comment]
This spurred a bit of conversation on #kakoune@irc.freenode.net, pasting it here for those who don't follow that channel:

    10:47 < danr> lol @ the two issues related to the ncurses_assistant
    10:47 < alex``> I noticed another bug, is that file-completion don’t work with `:` characters
    10:47 < danr> maybe I should start using clippy again
    10:49 < ironzorg> mawww   I'd say from now on you have to be a long time contributor for your assistant pull request to be considered :D
    10:49 < occivink> clippy draws too much attention when you want to show something to somebody
    10:49 < danr> occivink: agreed
    10:50 < occivink> the fairy IS pretty cool though
    10:51 * alex`` needs a Kirby assistant
    10:52 < danr> kirby is cute :)
    10:52 < alex``> If someone knows how to draw it
    10:52 < Franciman> Hi
    10:52 < Franciman> alex``, https://www.facebook.com/unk.org/posts/10153778718727072
    10:52 < Franciman> here you go
    10:52 < alex``> <('-'<)
    10:52 < occivink> that's the bad kind of ascii art though
    10:52 < alex``> (>'-')> !
    10:52 < occivink> I had found a website with thousands of nice art recently
    10:53 < danr> the linux tux is a reasonable assistant too I guess
    10:53 < Franciman> https://www.gamefaqs.com/boards/949625-kirby-super-star-ultra/47058915 this one i cute
    10:53 < alex``> Wow
    10:53 < alex``> This Kirby lol
    10:53 < occivink> ah there it is
    10:53 < occivink> http://www.chris.com/ascii/joan/www.geocities.com/SoHo/7373/
    10:53 < alex``> Kirby or Sonic
    10:53 < occivink> license is weird but eh
    10:54 < occivink> (if you keep the assistant for yourself I mean)
    10:54 < Franciman> provided that nobody does the spy
    10:55 < alex``> Couldn’t assistant be extracted from the C++ part?
    10:55 < danr> that's one of the issues submitted today
    10:55 < danr> to have it in text files
    10:59 < Screwtape> http://zork.net/~st/sadmac.txt <-- it's a pity this is too large to be an assistant, I should redraw it smaller.
    10:59 < ironzorg> a gameboy!
    10:59 < occivink> too large?
    11:00 < Screwtape> occivink: well, it's a lot wider and taller than clippy, for example.
    11:01 < occivink> it's about the same dimensions as dilbert
    11:01 < Screwtape> Hm, fair enough.
    11:02 < Screwtape> I do like the idea of dynamically loading assistant images from .txt files in the same search path as .kak files.
    11:03 < occivink> me too
    11:03 < ironzorg> that would add a fairly big amount of code for not much though

**Comment by danr** [comment]
This is from a much earlier IRC conversation on the same topic, from `2017-03-10',:

```
alex``  why don’t have the assistant on the config side ? 
alex``  rather than in the cpp source code
ironzorg        because we don't want to write error handling code just for that
alex``  is really the reason?
ironzorg        yes, also it takes away some of the "easter egg" aspect if it turns into an actual feature
ironzorg        so if you want your own ascii art merged upstream, pay mawww just like I did
mawww   Yeah, and the assistant is a ncurses_ui specific feature, its not in the core Kakoune code at all
mawww   But it could be changed relatively easily: 'set global ui_options ncurses_assistant=custom:<text>'
mawww   Not sure we need to go all this way for the assistant feature though
mawww   I already think having 3 different assistant is a bit overkill
```

**Comment by whereswaldon** [comment]
So, to sum up:
* There are people around who think it would be fun
* It has been discussed in the past and ruled to be bloat by the core team
* @mawww did suggest implementing a "custom" option that just accepted a string once, which does seem easier than text files, but is still considered overkill

I take it then, that I should not pursue this because the long-time contributors are not interested?

**Comment by mawww** [comment]
As extracted from this irc log, my favourite solution, if we really want to support more assistant, is to make them user defined, likely through ui_options. I dont think we should have text files defining them, assistants are kind of an easter egg feature gone a bit too far already (it used to be hidden as an undocumented `-assist` switch to the info command). I dont think we should introduce too much complexity to support this.
