### ISSUE TITLE
[REGRESSION] `ignored_files` is not applied anymore

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1755]
Hi,

I have the following line in my configuration:

```
set-option global ignored_files '^(\.\.?|.+\.o)$'
```

However, dot-files still show up in the completion menu when I use `:edit`.

HTH.

**Comment by mawww** [comment]
Your ignored_files regex is wrong, it does not prevent dot files from appearing, only `.`, `..` and object files.

What happened is that punctuation is now sorted before alpha numeric characters in ranked matches, so you see them appear early in the list when they are not hidden and match as well as other (so usually when you dont have entered any text yet)

**Comment by lenormf** [comment]
The actual regex in my configuration file is longer, I messed up while editing it for this issue.

**Comment by mawww** [comment]
Do you mean there is still an issue ?

**Comment by lenormf** [comment]
The regex in the original message wasn't going to work in any case, but the issue was present and has been fixed.
