### ISSUE TITLE
Remove `.` and `..` candidates from file-name completion

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1756]

**Comment by lenormf** [comment]
Dupe of #1755?

**Comment by mawww** [comment]
If thats in insert mode, I just fixed it, if it was the same a #1755, its probably the same problem with your ignored_files regex.

**Comment by lenormf** [comment]
Since dot files are normally hidden in command mode, I don't think we need to go the extra mile and specifically exclude `.` and `..` from completion.

**Comment by mawww** [comment]
Yeah, we have `ignored_files` for that.
