### ISSUE TITLE
ZN7Kakoune13get_user_nameEiE13invalid_index

### ISSUE THREAD

**Issue by joelburget** [mawww/kakoune#1758]
I get this exception when I simply start `kak`.

```
❯ kak
uncaught exception (ZN7Kakoune13get_user_nameEiE13invalid_index):
invalid index '0'
```

* I'm running on current master
* macOS High Sierra 10.13.1
* `uname -a`: `Darwin dublin.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`

**Comment by Delapouite** [comment]
This seems related to recent commit https://github.com/mawww/kakoune/commit/274367116a57c5788cc4b30861dcd94f54fba60e

**Comment by joelburget** [comment]
Indeed. When I reset to that commit's parent, `kak` starts successfully.
