### ISSUE TITLE
feature request: `"ay`  `"Ay` overwrites register a but should append to register a.

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1762]
# steps
- Consider the buffer below with the primary selection in the positions indicated :
```
⌷a⌷
b
```
- <kbd>"ay</kbd>
- message: `yanked 1 selection to register a`
```
a
⌷b⌷
```
- <kbd>"Ay</bd>
- message: `yanked 1 selection to register A`
```
a
b
⌷
```
- <kbd>"ap</kbd>
```
a
b
⌷b
```
- <kbd>"Ap</kbd>
```
a
b
⌷⌷bb
```

# observed
- `"ay`  `"Ay` overwrites register a.

# expected
- Like Vim, [A-Z] registers should append to [a-z] registers. Thus my final result should be
```
a
b
⌷⌷abab
```

**Comment by Delapouite** [comment]
Related pull request : https://github.com/mawww/kakoune/pull/1630 ;)

**Comment by nochiel** [comment]
@delapouite: Aha!  Well done and thank you!
