### ISSUE TITLE
Add an option to disable clippy

### ISSUE THREAD

**Issue by radare** [mawww/kakoune#177]
Clippy may be fun and helpful to new users, but it have some caveats:

* it distracts the eye
* appears in most of the daily-use keybindings
* refresh too much screen

As long as I find the help message useful, i would like to have an option to disable clippy and display the help message at the bottom of the screen, like the autocomplete commands, but with different background color

**Comment by mawww** [comment]
Note that you now can disable clippy (while still getting the info box) by adding ncurses_assistant=none in ui_options.

```
:set global ui_options ncurses_assistant=none
```

Reformating the text while still keeping it legible is a tricky task and would require interpreting some markup in docstrings, which seems too complex to be worth it.

**Comment by adamdavislee** [comment]
A quick update for those who stumble on this thread in the future, the option has been renamed to _terminal_assistant_
```
set global ui_options terminal_assistant=off
```
