### ISSUE TITLE
Crash when the current user's name isn't in /etc/passwd

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1770]
Hi,

I tried using the editor on a server that uses LDAP authentication (meaning none of the user's names are in `/etc/passwd`), and the editor crashed:

```
uncaught exception (ZN7Kakoune13get_user_nameEiE13invalid_index):
invalid index '0'                                                
```

274367116a57c5788cc4b30861dcd94f54fba60e probably needs to be completely reverted.

HTH.

**Comment by mawww** [comment]
This has been fixed
