### ISSUE TITLE
add generic ModeChange hook with old_mode-new_mode filtering

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1772]
Hello

Currently we have `NormalBegin`, `NormalEnd`, `InsertBegin` and `InsertEnd` hooks.

I think they could be all united in a more powerful and complete abstraction.

We could have a single `ModeChange` hook with a filter in the form of `old_mode-new_mode`.
In this scenario we can still represent the current hooks:

- `NormalBegin` → `ModeChange .*-normal %{…}`
- `NormalEnd` → `ModeChange normal-.* %{…}`
- `InsertBegin` → `ModeChange .*-insert %{…}`
- `InsertEnd` → `ModeChange insert-.* %{…}`

But we easily target non existing hooks like:
- `PromptBegin` → `ModeChange .*-prompt %{…}`

Or even more specific transition:
- `NormalEndInsertBegin` → `ModeChange normal-insert %{…}`

`NormalBegin` and co would therefore be *deprecated* to let the users some time to migrate their scripts.

**So what's the gain of this proposal?**
- increased orthogonality in the design (it's currently arbitrary that there is no `PromptBegin` hook for example)
- more control for script creators
- *potentially* simpler code (The current hooks are triggered in the `InputMode` `on_enabled` and `on_disabled` functions, which are themselves called by the `InputHandler` `push_mode()` and `pop_mode()` functions.)

**Comment by mawww** [comment]
Thats a nice idea, I'll take a look at how it can be implemented
