### ISSUE TITLE
Have `m` and `M` work across lines

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1774]
Hi,

Is there a reason why `m` and `M` will stop at the end of the current line?

Thanks.

**Comment by mawww** [comment]
Those are among the first commands that were implemented in Kakoune, so the fact the stop at an end of line is mostly historical. I am used to that behaviour and tend to think `m` and `M` can get a bit hard to predict if they can search for any nesting character for current position till the end of the buffer (or should the search wrap ?).

I am not opposed to that change, however I'd like to gauge support for both alternatives.

**Comment by Screwtapello** [comment]
My favourite use for `M` is to select a block of code, like this:

    int main(int argc, char **argv) {
        /* stuff */
    }

Put the cursor on the `i` of the first `int`, hit `M`, select the entire function. On the other hand, some code-bases use a different brace-placement style:

    int main(int argc, char **argv)
    {
        /* stuff */
    }

...which completely breaks this use of `M`. So, for general usefulness, I support `m` and `M` searching beyond the current line for the first nesting character.

As for the unpredictability of searching the rest of the file, maybe just restrict the search to what's on-screen, or however far Kakoune searches back and forward for syncing syntax highlighting.

**Comment by mawww** [comment]
@Screwtapello if you hit `M` on the first int, you'll select the argument list, not the whole function, regardless of where the `{` lies.

I think I'll go ahead and do this change, as I dont think any scripts will rely on `m` failing if there is no matching chars on the line. If it proves to be a bad idea, we can revert it later.
