### ISSUE TITLE
insert mode: `<a-;>\i` does not disable hook for the next insert mode

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1775]
# steps
- <kbd>i</kbd>lorem ipsum<kbd>\<a-;></kbd><kbd>\\</kbd>
  - reported: `[no-hooks]`
- <kbd>i</kbd>

# observed
- hooks are re-enabled for the insert session.

# expected
- hooks should remain disabled for the insert session

The documentation says: 
> <a-;>
>    escape to normal mode for a single command
> [...]
> Any normal mode command can be prefixed with **\\** which will disable hook execution for the duration for the command (*including the duration of modes the command could move to, so **\\i** will disable hooks for the whole insert session*).

**Comment by mawww** [comment]
Yep, this seems like a bug, as I explained in #1776 Kakoune uses a stack of mode, for some reason the single command normal mode does not seem to forward the `no-hooks` flag to the insert mode it introduces.

I'll see how that can be fixed.
