### ISSUE TITLE
Config regex parsing issue

### ISSUE THREAD

**Issue by dgrisham** [mawww/kakoune#1777]
**Type**: Bug, or possibly just something that needs documentation

**Severity**: Low

**Version**: The one on the AUR https://aur.archlinux.org/packages/kakoune-git

**Description**

I came across this issue while trying to update [this line in `markdown.kak`](https://github.com/mawww/kakoune/blob/master/rc/base/markdown.kak#L23) from:

    printf '%s    ```\h*%s\\b   ```   "" ' "${lang}" "${lang}"

to

    printf '%s    ```\h*(\{\.)?%s\\b   ```   "" ' "${lang}" "${lang}"

The goal was to get syntax highlighting when using [Pandoc's fenced code attributes](https://pandoc.org/MANUAL.html#fenced-code-blocks) (scroll down a bit from where that links to).

However, the `{` in the regex caused a weird issue where kakoune seemed to think `{` was opening a new block. The resulting error looks like:

```
/home/grish/dotfiles/kak/autoload/autoload/base/markdown.kak:parse error: 13:3: unterminated string '%sh{...}'
```

I assume this has something to do with the fact that this is within a string that's being automatically generated within a `%sh{ .... }` block and the escape characters are being removed or something, but I'm not quite sure how to fix it (neither one nor two `\` before the `{` seemed to help).

**Edit**: typos

**Comment by lenormf** [comment]
That's a parsing quirk of the editor, you can reproduce it with the following:

```
:echo %{{}
```

All opening braces have to be closed off within a `%{}` string (or, for instance, a `%sh{}` scope), so you could add a commented brace on the next line to fix that.

The cleaner way would however be to change the punctuation character used to create the scope to something else, e.g. a square bracket:

```
:echo %sh[ printf '{' ]
```

**Comment by danr** [comment]
To follow up on @lenormf's comment, you can change the `{` to some other delimiter (like `[`) starting on this line:

https://github.com/mawww/kakoune/blob/969f4160270acfb5226e2a3174ab15eb82097520/rc/base/markdown.kak#L14-L36

Another alternative would be to use a symbol that is not used anywhere in the shell script. For example tilde would do the trick here (`%sh~ ... ~`).

**Comment by dgrisham** [comment]
@lenormf @danr Switching to `%sh[...]` worked for me, thanks! This is a relatively unsatisfying solution in the larger scope though, is there currently a plan to fix the parser of this quirk?

**Comment by mawww** [comment]
@dgrisham This is not a quirk, rather a feature, `%{...}` style strings dont need any escaping of their closing character (which would get more and more painful when they get nested, which is common in command definitions), in exchange for not needing for the closer to be quoted, they require the pair of opening/closing char to be balanced inside the string.

If you'd rather escape, you can use `'...'` strings, or `%!...!` style strings (when the opening/closing are a single punctuation character instead of a matching pair, the character can be escaped, as no nesting is possible).

**Comment by dgrisham** [comment]
@mawww Ah, okay, gotcha. Thanks for the explanation!
