### ISSUE TITLE
Regex highlighter '\n\z' acting strange

### ISSUE THREAD

**Issue by Xiaogrill** [mawww/kakoune#1778]
With `addhl global regex '\n\z' 0:default,red` in my WinCreate hook I get "random" highlighted characters on file load, that disappears when editing the file.

An asciinema file showing the behavior:
https://transfer.sh/STuCO/1513859544.json

**Comment by mawww** [comment]
This is due to how regex highlighters work, by only parsing a few lines above/below the viewed region, and caching the results. I'll check how to fix that.
