### ISSUE TITLE
Don't fully parse the files on startup

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1781]
Hi,

Running `perf` on the editor with the #1780 patch revealed that files are fully parsed when they are first opened, which proves to be a major time sink (even when files near the 2G mark).

Could the lines of the currently opened file be parsed as parts of it come into view? I.e. if I open a file, jump to the middle of it and quit the editor, only roughly two windows' height worth of lines should be parsed: the lines that are in view when I open the file, and those in view when I jump in it.

HTH.

**Comment by lenormf** [comment]
Consequently, and assuming incremental parsing would be implemented, I'd like to see a hook triggered when the view was changed, to allow custom scripts that add their ranges to the buffer to not have to parse the whole buffer.

**Comment by mawww** [comment]
This would be a huge architectural change for Kakoune, and would break region highlighting which rely on the whole buffer being available to correctly compute regions. Trying to be faster at reading files would be a better solution IMHO.

I think loading a 2G+ file can reasonably take a few seconds, Kakoune is simply not designed as a huge file editor, it is mainly a code editor, and code files tend to be small. Working with huge files should be doable, but its more important to be as performant as possible on small files than on huge files.
