### ISSUE TITLE
Add location hints for movement keys

### ISSUE THREAD

**Issue by plurry** [mawww/kakoune#1789]
Is there something like [vim-snipe](https://github.com/yangmillstheory/vim-snipe) for Kakoune? For me it's such a superior way of working that I wish it was standard. But for now, just a plugin would be a godsend.

**Comment by Delapouite** [comment]
Hello. There's https://github.com/danr/kakoune-easymotion for now.

**Comment by mawww** [comment]
I think kakoune-easymotion is your best bet, closing this issue.
