### ISSUE TITLE
Is it possible to implement something like ActualVim using Kakoune? 

### ISSUE THREAD

**Issue by danieltanfh95** [mawww/kakoune#1790]
ActualVim: 
https://github.com/lunixbochs/ActualVim

I saw the JSON UI docs and was wondering if there were more information.

**Comment by mawww** [comment]
It should be possible to do that, might be tricky and we might miss some features, but Kakoune should be embedable in another application using the existing extension model and the json-rpc UI. 

I'd be interested to know if there are any blockers to such an effort.
