### ISSUE TITLE
Proposal: Swap q and Q in <a-i>/<a-a>

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#1791]
I'm quite new to `Kakoune`, and find it highly interesting, still experimenting with it, so don't judge hard.
I propose to swap object aliases `q` and `Q` for `'` and `"` respectively. Let me explain why.
Single quote `'` is first class citizen, I mean there is no need to press shift to type it, and its current object alias `q` is also first class citizen. Two first class citizens describe same object. IMO it would be much better to let `"` object to have first class citizen alias `q` instead. In that case both objects are accessible without having to press shift. I mean whenever one needs double quote object selection, there will be option to press just <kbd>q</kbd> or <kbd>shift</kbd>+<kbd>'</kbd>. I would certainly prefer pressing just <kbd>q</kbd>.

Sorry in advance, if this is changeable in user settings.

**Comment by danr** [comment]
You can remap these in the `object` map:

```
map global object q Q
map global object Q q
```

**Comment by vbauerster** [comment]
Excellent! Thank you!

**Comment by mawww** [comment]
I think both defaults (<kbd>q</kbd> = <kbd>'</kbd> or <kbd>q</kbd> = <kbd>"</kbd>) make sense and can be justified, so I'd rather keep the status quo.
