### ISSUE TITLE
Without pkg-config installed, build fails

### ISSUE THREAD

**Issue by jeferrier** [mawww/kakoune#1792]
I started with a fresh debian 9 install, the first thing I did after installing sudo was start installing kak. I ran into this issue, and it was not very clear what the issue was. I did figure it out after reading through the Makefile.

### Steps 
1. Do not have pkg-config installed.
2. Follow the commands to install kak using Ubuntu (the same commands work for debian).

### Outcome 
During make, the build fails on ncurses_ui.cc: `fatal error: ncurses.h: No such file or directory`
This is because pkg-config does not return a valid list of libraries to be included for compilation.

### Expected 
Some indication that pkg-config is the issue, and not ncurses.h or ncurses_ui.cc

**Comment by mawww** [comment]
Hello, thanks for this issue, I guess we should check for pkg-config in some way inside the Makefile so that we can complain if it is not found.

**Comment by lenormf** [comment]
According to the error you're showing, the issue seems to be that you didn't install `libncursesw-dev`. If a program wasn't found in the PATH at the time of the execution of the command by `make`, you will already get an error saying just that:

```
make: pkg-config: Command not found
make: *** [Makefile:2: all] Error 127
```

**Comment by jeferrier** [comment]
That's not what I experienced though. The installation instructions say to install `libncursesw5-dev`, which I did install.

During troubleshooting, when I instead installed `libncursesw-dev`, and then ran `make` again, there were errors from compilation regarding references to methods that are not defined in `libncursesw-dev` (but which presumably are defined in `libncursesw5-dev`).

I will try to emulate this tonight, and get the output from that case as well.

**Comment by lenormf** [comment]
I see what happened now: `make` does show a non-critical error if `pkg-config` isn't in the PATH, it's the very first line displayed but is somewhat overshadowed by the subsequent compilation commands. However, since the call is only made within the scope of a variable initialization, the `all` target will be executed anyway:

```
lenormf@5d157d4e0f79:~/kakoune/src$ make
make: pkg-config: Command not found

[…]

ncurses_ui.cc:14:21: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
                     ^
compilation terminated.
Makefile:80: recipe for target '.ncurses_ui.debug.o' failed
make: *** [.ncurses_ui.debug.o] Error 1
```

I've made a pull request to address that.

**Comment by jeferrier** [comment]
Thank you both for addressing this so quickly!
