### ISSUE TITLE
`+n:` doesn't work when kak is in a pipe.

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1793]
### Steps 

- In a terminal: `printf %s\\n {1..10} | kak +5:`

### Outcome 
- kakoune opens a \*stdin\* buffer with the cursor at the beginning of the buffer.

### Expected 
- kakoune should open \*stdin\* buffer with the cursor on line 5.

---

(possibly related to: https://github.com/mawww/kakoune/issues/759)

**Comment by mawww** [comment]
Unfortunately, it would be tricky to do that with the current way the `*stdin*` buffer is handled:

`*stdin*` is a fifo buffer, which means Kakoune reads it continuously, without blocking. That means when Kakoune opens, `*stdin*` is empty, and we read it progressively as the data becomes available. This also means we do not have the fifth line available (in the `+5` case) at startup, it might become available only once its written by the process connected to stdin, which can take an arbitrary amount of time. Deferring the jump to the specified line until the line appears seems like a pretty complex solution, so I am not sure trying to fix would be worth it.
