### ISSUE TITLE
No syntax highlighting, when autoload is empty

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#1798]
When `autoload` dir is empty, syntax highlighting doesn't work for any file type.
Following is my config tree:
```
~/.config/kak
❯ tree
.
├── autoload
├── colors
│   ├── dracula.kak
│   ├── gotham.kak
│   ├── gruvly.kak
│   ├── seagull.kak
│   └── yumh.kak
└── kakrc
```
If I remove `autoload`, then it is ok.
PS: I use macos version, installed via homebrew.

**Comment by SolitudeSF** [comment]
[from README](https://github.com/mawww/kakoune#configuration-autoloading)

> If the `$XDG_CONFIG_HOME/kak/autoload` directory exists, load every `*.kak` files in it, and load recursively any subdirectory.
>If it does not exist, falls back to the site wide autoload directory in `../share/kak/autoload/`.

**Comment by vbauerster** [comment]
Thanks!
