### ISSUE TITLE
Allow cancelling writing to and sourcing from fifos

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1799]
When the file is a fifo `write` and `source` hangs kakoune until someone writes to or listens to the fifo. If this never happens Kakoune is indefintely blocked. It would be nice to introduce a cancellable timer just like long-running %sh{...}-blocks

### Steps

```
d=$(mktemp -d)
f="$d/fifo"
mkfifo $f
kak -e "source $f"
```

```
d=$(mktemp -d)
f="$d/fifo"
mkfifo $f
kak -e "write $f"
```

### Outcome 

Kakoune hangs

### Expected 

That a timer is started after a while with a Ctrl-C cancel opportunity similar to `source %sh{cat $kak_opt_fifo_file}` and eh... `eval -draft %{ exec \%; %sh{echo "$kak_selection" > $kak_opt_fifo_file}}` or something of the likes.

**Comment by lenormf** [comment]
Isn't it the expected behaviour already?

**Comment by danr** [comment]
Nope, not here, tried with a recompile without debug and `-n` to `kak`.

**Comment by lenormf** [comment]
I meant that blocking is to be expected considering the steps described, I'm not sure anything needs to be done here.

**Comment by danr** [comment]
I see and I disagree: I am expecting the user to be given the opportunity to cancel the block.

**Comment by mawww** [comment]
I wonder if we should use a timer here, providing a mapping to cancel the write/read from the filesystem, or just refuse to read/write from fifos, eventually suggesting to use a fifo buffer (for the read case). I suspect there are some legitimate cases where we want to read/write from fifo, but I am not sure what those would be. Any examples ?

**Comment by danr** [comment]
I write to and source from fifos to decrease the amount of shell scopes spawned. 
It's the approach I use in danr/kakoune-easymotion: 

https://github.com/danr/kakoune-easymotion/blob/master/easymotion.kak#L25-L27

As well in the new "libkak" that I'm slowly working on:

https://github.com/danr/kakoune-languageclient/blob/0144d10510249262904d6ab8f3a69de99b16c28f/src/libkak.ts#L109
https://github.com/danr/kakoune-languageclient/blob/0144d10510249262904d6ab8f3a69de99b16c28f/src/libkak.ts#L125

However I see that it could be adding unneccessary complexity to the code-base since shell scopes could be used for this instead (and sketches for doing this is included in the first post of this issue).

**Comment by sebsebmc** [comment]
I'm using a fifo to communicate with an external program. I'm only writing to it from Kakoune, but it makes it simple to send commands through the fifo.
https://github.com/sebsebmc/kakoune-languageclient
Specifically, https://github.com/sebsebmc/kakoune-languageclient/blob/master/client.go#L43

**Comment by mawww** [comment]
@sebsebmc Nice. However I dont quite get why you'd need to write a buffer to a fifo. We already have various ways to do that which will allow cancellation: `%sh{ echo command | /path/to/fifo }` or `<a-|>cat >/path/to/fifo`.

**Comment by sebsebmc** [comment]
You're right, I'm not writing buffers to fifos. I misunderstood the issue, thinking this was about writing to fifos in general, not using the `write` command. I essentially use `%sh{ printf string  >> path/to/fifo }` right now.

**Comment by mawww** [comment]
So, to recap my position on this issue. I think it would effectively be nice to be able to cancel a blocking `:write`, `:edit` or `:source` command (due to a fifo or otherwise). However this is going to be pretty complex as it needs we now have to handle events while reading/writing, and I think it stays pretty low priority as we can write a buffer to a fifo with cancelation easily through `<a-|>cat /path/to/fifo<ret>`.

**Comment by danr** [comment]
Ok, let's close this issue then as workarounds are readily available.
