### ISSUE TITLE
Document that keys that launch commands support shell escapes

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1805]
The contents of `:doc expansions` explain that`%sh{}` expansions support special `$kak_*` variables that will be added to the environment if Kakoune sees them mentioned. It doesn't say anything about other ways Kakoune can launch shell commands, such as the `|`, `!` and `$` keys.

Likewise, the documentation for those keys says that they prompt for a shell command, but they don't mention the extra environment variables available.

The "Shell expansions" documentation should mention that these environment variables are available anywhere Kakoune runs a shell command, not just in `%sh{}` expansions. The documentation for `|`, `!` and `$` should link to the "Shell expansions" section.

**Comment by Delapouite** [comment]
Yes it makes sense to alleviate any confusions about this.
