### ISSUE TITLE
Support truecolour output with ncurses

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1807]
Kakoune has (deliberately) limited support for applying colour-schemes with it's default ncurses-based UI. On one hand, ncurses really wants applications to use colour-indexes into the terminal's standard palette; on the other hand, every other modern display API wants 8-bits-per-channel RGB triples in the sRGB colour-space, and mawww is uncomfortable with designing Kakoune's colour-scheme API around the limitations of ncurses.

The current compromise is that Kakoune supports a few named colours that happen to map to the standard 8 terminal colours in the ncurses UI, arbitrary #rrggbb colours are passed to `init_color(3N)`, modifying the entries in the terminal's 256-colour palette. This has it's downsides; as well as being impolite (the user might have configured those palette entries themselves, and Kakoune stomps on them) there are terminals that don't support modifying the 256-colour palette at all (the Qt terminal widget being a notable example).

Some terminals have added a 24-bit or "direct colour" mode so an application can set an arbitrary colour at any time without having to declare it beforehand; in particular, libvte (used by `gnome-terminal`), `tmux` and `xterm` (since version 331). People have previously suggested using this with Kakoune, but nothing has ever come of it because there was no way to ask or trick ncurses into taking advantage of this mode. However, support is being added to ncurses 6.1 libraries, I've spent some time trying to figure out how it's all supposed to work, and I wanted to write that information down somewhere before I forgot.

### terminfo and ncurses

A new fragment has been added to the terminfo database, named [xterm+direct](http://invisible-island.net/xterm/terminfo-contents.html#tic-xterm_direct), along with an entry named `xterm-direct` that layers the `+direct` fragment on top of the standard `xterm` entry.

This fragment rewrites the `setab` (set ANSI background) and `setaf` (set ANSI foreground) rules to directly accept a 24-bit colour rather than a palette index. Actually, it's a bit more complex than that: if I understand correctly, the darkest 8 shades of blue (i.e. `#000000` through `#000007`) are taken to mean the standard 8 terminal colours rather than indistinguishable shades of black, so programs that blindly send `setaf 2` will get the traditional green text instead of effectively-black. It also sets the `RGB` flag to signal that `setab` and `setaf` do not follow the traditional behaviour.

### applications

Since most classic curses APIs take colour values as `shorts`, they can't be used with direct colour. You'll have to use ncurses extended APIs instead. For example, `init_extended_pair(3N)` instead of `init_pair(3N)`.

Looking at the changes in `xterm+direct`, I'm guessing most palette-related ncurses functions like `init_color(3N)` and `init_extended_color(3N)` will just break. `extended_color_content(3N)` is a notable exception: if the terminfo `RGB` flag is set, it can get the RGB fields of a colour through masking and shifting instead of consulting the palette.

I'm not sure if there's a good way for an application to detect whether `init_extended_pair(3N)` wants palette-indexes or raw colours. Perhaps if calling `tigetflag(3N)` with "RGB" returns anything other than 0 (that is, if it's boolean true, or if it's present but not a boolean), that's the best heuristic?

### users

This ncurses direct-colour mode is only available if `$TERM` is set to the name of a terminal-entry that contains the appropriate configuration. Right now, that's only true if `$TERM` is set to `xterm-direct` on a machine with a sufficiently-modern copy of ncurses installed (and by "sufficiently-modern" I mean "newer than January 2018"). Even on machines that have the `xterm-direct` entry in the terminfo database, users might not want to use it, since it will probably break applications designed to work with 256-colour support, and it deliberately excludes a bunch of other useful fragments like `xterm+tmux` (which declares extra xterm features tmux uses) and `xterm+sl` (declares a sequence for setting xterm's title text). Therefore, it will probably be a while before this mode is widely available, let alone the default.

**Comment by Screwtapello** [comment]
I confirmed my understanding [on the ncurses mailing list](https://lists.gnu.org/archive/html/bug-ncurses/2018-04/msg00011.html).

It looks like teaching Kakoune to use ncurses' direct-color support will require something like this:

1. Where Kakoune currently calls `init_pair()`, call `init_extended_pair()` instead. This can be wrapped in `#if NCURSES_PATCH >= 20170401` (the first version that included that function) to maintain compatibility with older versions of ncurses.
2. When the ncurses UI is initialised, check for the terminfo field `RGB`. If present, it means this terminal uses direct color, and we should [interpret it](https://github.com/ThomasDickey/ncurses-snapshots/blob/master/ncurses/base/lib_color.c#L263) to figure out how many bits per channel.the terminal wants, and store that information.
      - this code should also be wrapped in a similar `#if` check, since using the `RGB` field requires `init_extended_pair()`.
3. Still during initialisation, if the `RGB` terminfo field is present, update the `m_colors` field so Kakoune's 16 named colours are mapped to specific RGB values (with the correct bits per channel for the current terminal) rather than palette indexes.
4. In Kakoune's `get_color()` method, if we have stored bits-per-channel information we should use it to fabricate a colour number directly, rather than bothering with palette stuff. Otherwise, fall back to the existing code.

Drawbacks:

- extra work
- unlike 256-color mode, direct-colour mode isn't likely to "just work" with existing applications, so adoption for `xterm-direct` (etc.) is likely to be much slower than `xterm-256color` adoption was
- still won't make things Just Work inside tmux, because there's not (yet) a `tmux-direct` terminfo database entry for inside tmux, to match `xterm-direct` (or `vte-direct`, or whatever) outside tmux.

Alternatives:

- status quo, where we mess with the 256-color palette to simulate true-colour output: least work, but doesn't work on all terminals and can be fussy to get working with, say, tmux.
- drop ncurses, switch to [libtickit](http://www.leonerd.org.uk/code/libtickit/) or similar: most work, but likely to give the best experience to end-users.

@mawww, would you be interested in Kakoune supporting ncurses' direct-color mode, or would you rather not?

**Comment by lenormf** [comment]
If the changes required involve adding pre-processing directives to support different versions of `ncurses`, I'm not sure it's worth it considering the feature is already sort of there, but implemented in another more portable way (with OSC).

**Comment by mawww** [comment]
One thing that should be kept clear is that we already do support true color output, yes we use the palette, but we change it so that it contains exactly the RGB value we want. We do rely on terminal support for changing colors in order to do that, and not all terminals do.

Additionally, some terminals (urxvt, xterm) approximates 24bit colors to a 256 colors palette. Which means you actually will get "true colors" using the palette changing approach (as you set the color exactly) instead of the 24bit color approach (which will get approximated).

tmux recently added support for palette change, so 24bit/palette change are going to work as well with it (the problem is the same in both cases: out of date terminfo).

That means that, in my view, there is few real advantages to using 24bit color support in Kakoune, I dont think we have any colorscheme that uses more than 256 distinct colors, so the palette works great. We have palette restoring code in as well, and that code is generally mature.

If I was writing the ncurses UI today, I'd probably go with 24bit because its simpler, and nowadays there is good enough support. But we already have a well working palette based true color support, and the real problem user run into is not 24bit/palette change support, its out of date terminfo files that prevent Kakoune from using that feature.

All that to say I am not very keen on adding all that new complexity to support 24bit colors, which, in my view, are not significantly better than the existing solution.

**Comment by Screwtapello** [comment]
Possibly the biggest benefit of 24bit support would be people who use terminals based on the KDE terminal widget (Konsole/QTermWidget) or [st](https://st.suckless.org/), which do support direct-colour but don't support modifying the 256 color palette. Of course, neither of those are very popular terminals, and ncurses' direct-color support feels very weird and hacked-on and difficult to integrate cleanly with existing applications, so I agree it's probably not worth implementing.
