### ISSUE TITLE
Use register with <a-k> and <a-K>

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1808]
Currently they don't have any associated register, which makes them harder to use in scripts, as we cannot rely on this pattern:
```
set-register REG 'some_value'
exec <a-k><ret>
````
Expanding the register in the 'exec' command is not as robust, as the register cannot contain any `<`.

As default register, there are still that could be used, such as `$`, `&`, or `*`. I like `&`.

**Comment by danr** [comment]
As a temporary workaround you can use `<c-r>r` to paste some register `r` in any prompt.

**Comment by lenormf** [comment]
How about making it use the selection register, by default?
