### ISSUE TITLE
Disable mouse events while suspended

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1816]
### Steps 

 1. Start Kakoune in an xterm or gnome-terminal
 2. Press `<c-z>`
 3. Focus another window and back

### Outcome 

Terminal beeps every time it loses or gains keyboard focus

### Expected 

Nothing happens.

### Notes

This is because in `NCursesUI::enable_mouse()`, as well as calling the standard ncurses functions to enable mouse events Kakoune also squirts hard-coded escape sequences at the terminal. Because those escape sequences weren't sent by ncurses, the standard ncurses `SIGTSTP` handler doesn't disable them again before suspending Kakoune. Those custom modes stay enabled while Kakoune is in the background, so the terminal keeps sending focusin/out events, bash/readline don't know what to do with them, and so they just beep.

The urxvt terminal emulator has different symptoms caused (I think) by the same issue: I don't think it supports focus events, and (I think) it supports a different mouse-protocol than xterm/libvte do. Under urxvt, when you hit `<c-z>`, it doesn't beep on focus in/out, but trying to use the mouse to select text types mouse-event-gibberish into the bash prompt instead.

**Comment by tadzik** [comment]
In addition to focus, in my experience it also prints garbage characters to the terminal when you try to click around the terminal window – probably the symptom of the same problem.

**Comment by lenormf** [comment]
I'm using `termite` and I've been complaining about this for years without knowing what to blame (`i3` and `tmux` would always highlight the workspace/pane in which a suspend `kak` process is). Thanks for looking into it!
