### ISSUE TITLE
tmux-repl.kak does not handle tmux-master

### ISSUE THREAD

**Issue by jacobdufault** [mawww/kakoune#1827]
I modified `shell_manager.cc` to dump `cmdline` if there is stderr content. It let me identify that `tmux-repl.kak` is emitting an error if `tmux -V` does not contain numbers, ie

```bash
$ tmux -V
tmux master
```

Here are the raw logs:
```
shell cmdline: <<<

        if [ -n "$TMUX" ]; then
            VERSION_TMUX=$(tmux -V)
            VERSION_TMUX=$(expr "${VERSION_TMUX}" : 'tmux \([0-9]*\).*')

            if [ "${VERSION_TMUX}" -gt 1 ]; then
                echo "
                    alias global repl tmux-repl-horizontal
                    alias global send-text tmux-send-text
                "
            else
                echo "
                    alias global repl tmux-repl-disabled
                    alias global send-text tmux-repl-disabled
                "
            fi
        fi
    >>>
shell stderr: <<<
/bin/sh: line 5: [: : integer expression expected
>>>
```

Would a PR for the change in shell_manager.cc be accepted? Or is there another way to debug shell stderr messages? Because the stderr by itself often not illuminating. Ideally it'd be great to trace it back to where the message came from originally but I suspect that is tricky.

**Comment by jacobdufault** [comment]
Nifty, looks like this already has a PR at https://github.com/mawww/kakoune/pull/1826.

**Comment by nochiel** [comment]
@jacobdufault Had you tried putting `set global debug shell` in `$INSTALLPATH/share/kak/kakrc`? It ensures kak prints the contents of the shell script when it runs.  

Please do submit your modification to `shell_manager.cc`.  I, for one, would like the default to be that the problematic shell script is printed to \*debug\* when there's a stderr message.
