### ISSUE TITLE
Merge all the current buffer's change history into one node

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1828]
Hi,

Is it possible to merge all the changes made to a buffer into a single history node? Could it be implemented?

Thanks.

**Comment by occivink** [comment]
Something granular would be nice, for example merge every change made in an eval/exec block.

**Comment by mawww** [comment]
Do you mean forget all buffer history up to the current point ? It seems that would be the effect of merging all the change history to a single node. Can you explain your use case to give me a better idea of what you are looking for ?

**Comment by lenormf** [comment]
The history wouldn't be forgotten, just entirely compressed and undo-able with a single undo:

* open a file with code in it
* modify it to implement a feature
* merge all the history into a single node
* I can now have a before/after view using only one `u`/`U` keystroke

I generally use `git` for such things, but since that feature was requested by a couple other users, I figured I would create this issue, maybe they'll have more compelling use cases.

**Comment by lenormf** [comment]
Looks like it's `<c-u>` in insert mode.
