### ISSUE TITLE
Make the plugins page on the site grab plugins with the "plugin" topic

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1833]
Hi,

Right now the [plugins page](http://kakoune.org/plugins.html) fetches all the repositories that have the `kakoune` topic set, and that produces several false positives.

I suggest that the site instead uses both a `kakoune` and `plugin` topic (and document that on the plugins page), but that should be agreed upon by the maintainers of the several plugins that already have their repository on Github.

@danr @alexherbo2 @Delapouite @occivink ?

**Comment by danr** [comment]
I support this idea.

**Comment by Delapouite** [comment]
Good idea. I have added the `plugin` topic on all my relevant kakoune repos.

**Comment by danr** [comment]
Same here

**Comment by lenormf** [comment]
@alexherbo2 it turns out that github doesn't allow for logical operators in the search query that could allow the plugins page to select repositories that have the `plugin` and/or `extension` set, so none of your repositories are currently displayed on the site.

You'll have to add the `plugin` topic to your repositories I think.
