### ISSUE TITLE
Option to remove buffer padding indicators

### ISSUE THREAD

**Issue by notramo** [mawww/kakoune#1839]
I couldn't find an option to remove buffer padding indicators (`~`).

If the terminal background is transparent, setting the buffer padding characters color to the same as the background don't work, because the characters aren't transparent.

If line numbers are used, these indicators are not much usable, because the lack of line numbers in a part of the window indicates the file end.

**Comment by lenormf** [comment]
That was implemented in the [PR](https://github.com/mawww/kakoune/pull/593/files#diff-ddaa7d6e643bc0d374add600b02445beR256) that improved on buffer padding, unfortunately the option didn't make it upstream.

**Comment by notramo** [comment]
@mawww Why was it removed?

**Comment by mawww** [comment]
I try to avoid too much feature creep in Kakoune, and I considered that hiding/showing the buffer padding indicators was a feature we could do without. You need a very specific set of circumstances to really need that feature (which you happen to have, unfortunately), namely using transparant background and wanting to hide the padding indicators. In other cases, hiding the indicators through the face is fine.

**Comment by notramo** [comment]
OK, I understand it.
I solved it for my use case by replacing the `~` character in the source code to a space. It's very little effort so I will close this issue.
