### ISSUE TITLE
Semicolon after w

### ISSUE THREAD

**Issue by h-youhei** [mawww/kakoune#1841]
It is intuitive that semicolon after w select first character of next word.

What do you think?

### Current behavior
```
[a]bc abc
type w
[abc ]abc
type ;
abc[]abc
```

### Suggested behavior
```
[a]bc abc
type w
[abc ]abc
type ;
abc [a]bc
```

**Comment by MilanVasko** [comment]
I don't think you can achieve this behaviour without introducing inconsistencies. That said, typing `l` (lowercase L) instead of a semicolon does exactly the thing you're describing, doesn't it?

**Comment by h-youhei** [comment]
You're right.
I should have stated its use case.

Selection is great.
But I delete a char or replace a char after w,b,e frequently.
So I tried
```
map global normal '<del>'  \;d
map global normal '<backspace>' hd
map global normal '<esc>' '<backspace>'
map global normal r \;r
map user r r
```
With this mappings I'm happy except with w.
After that, I felt suggesting behavior is intuitive.
But I rethink it. It involves unneeded complexity.

I write wrapper command for me.
But it doesn't work. Can you help me?
Also I want to know how to use \<mod-key> in pattern match.
```
declare-option -hidden global bool after_w
hook global NormalChar [^w|W] 'set-option global after_w false'
hook global NormalChar w|W 'set-option global after_w true'

define-command -hidden semicolon %{ %sh{
  if [ $after_w = true ]; then
    execute-keys -no-hook l
  else
    execute-keys -no-hook \;
  fi
}}

map normal '<del>' ':semicolon<ret>d'
```

### Goal
```
[a]bc abc
type w
[abc ]abc
type delete
abc [b]c
```

### Now
```
[a]bc abc
type w
[abc ]abc
type delete
[a]bc
```

**Comment by h-youhei** [comment]
> Also I want to know how to use <mod-key> in patterns.

It can be written as is `w|W|<a-w>|<a-W>`
However in character set `[^wW]` matches no alt key.
`[^wW]|<a-[^wW]>|<[^a]-.+>|<.[^-]?.*>` is the answer.

**Comment by MilanVasko** [comment]
There may be a better way to do this, (I'm still pretty much a Kakoune novice) but I took your configuration and tried to make it work:

```
declare-option -hidden bool after_w false
hook global NormalKey [^w|W] 'set-option global after_w false'
hook global NormalKey w|W 'set-option global after_w true'

define-command -hidden semicolon %{ %sh{
  if [ $kak_opt_after_w = true ]; then
    echo "execute-keys -no-hooks l"
  else
    echo "execute-keys -no-hooks \;"
  fi
}}

hook global NormalKey <del> %{ execute-keys -no-hooks :semicolon<ret>d }
```

It seems to be working on my side, let me know if this works for you.

**Comment by h-youhei** [comment]
That works.
Thanks a lot.

**Comment by mawww** [comment]
I believe this has been solved, closing.
