### ISSUE TITLE
Document -shell-completion token_to_complete and pos_in_token

### ISSUE THREAD

**Issue by jacobdufault** [mawww/kakoune#1845]
It looks like there are some environment variables that are not documented when doing `define-command -shell-candidates`, namely `token_to_complete` and `pos_in_token`.

I found them by reading `extra/git-tools.kak`.

https://github.com/mawww/kakoune/blob/f3c19ba7fa437a2512db5261742a494769f46b56/src/commands.cc#L923-L947

**Comment by Delapouite** [comment]
You're right. It should probably be added to https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc#shell-expansions and/or https://github.com/mawww/kakoune/blob/master/doc/pages/commands.asciidoc#declaring-new-commands

**Comment by mawww** [comment]
I agree, somebody ought to write a PR to improve the docs ;)
