### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by Stockton-pr** [mawww/kakoune#1856]
Should a local ie in the root of my project editorconfig file get read? Not working for me yes, I have the load hook in my kakrc

**Comment by doppioandante** [comment]
You also need the editorconfig binary.

**Comment by Stockton-pr** [comment]
yes got that through apt install. Is there a default config preloaded? if so where is it? can it be overridden?

**Comment by mawww** [comment]
You need to enable editorconfig via a hook. `editorconfig.kak` provides the `editorconfig-load` command, if you want to run it for every file kakoune opens or create, add the following lines to your kakrc:

```
hook global BufOpenFile .* editorconfig-load
hook global BufNewFile .* editorconfig-load
```

**Comment by Stockton-pr** [comment]
thanks for the reply that's done, will that load the default in extra or look for something that I put in the root of my project( I assume that is the case?). Sorry for being bothersome in all other regards Kakoune is totally delightful just babysteps/ tripping

**Comment by doppioandante** [comment]
There's no default, the editorconfig binary will traverse your directories until it finds a  editorconfig file (and it can go further it is not marked as root).
If you have no .editorconfig nothing will happen.

**Comment by mawww** [comment]
`editorconfig-load` passes the buffer path to the `editorconfig` binary, which will then recursively consider all parent directories in that path until it finds a root `.editorconfig` file.

**Comment by Stockton-pr** [comment]
ok thanks for all the help got confused but there eventually.
