### ISSUE TITLE
Newline characters used as-is in the prompt

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1865]
### Steps 

Open a new buffer:

* <kbd>*</kbd>
* <kbd>/</kbd> <kbd>ctrl-r</kbd> <kbd>/</kbd>

### Outcome 

The newline character appears in the prompt as `␤`.

### Expected 

That doesn't have an impact on the functionality, i.e. the pattern is still usable, but it would probably be more convenient if `\n` appeared instead.

**Comment by lenormf** [comment]
I suppose having a function that converts non-printable characters into their escape form could be used in `input_handler.cc`.

**Comment by mawww** [comment]
Displaying `␤` for newline characters in the command line is a voluntary behaviour, why do you think `\n` would be better ? We would then need to highlight it specially to show that its a single character, and not a `\` followed by a `n`.

**Comment by lenormf** [comment]
In prompts that accept a regex, it's visually more consistent as I almost never insert a raw newline or tab character when I want to match them. In other cases (like in a command prompt), the current behavior (WYSIWYG) is better.

**Comment by mawww** [comment]
Why would you write a literal newline in a regex prompt ?

**Comment by lenormf** [comment]
Sometimes muscle memory trained in the shell kicks in and I use <kbd>c-v</kbd>. But when I paste a register (whose value was set from raw data) into a prompt that takes a regex as input, I find it more consistent to have everything encoded as escapes.

**Comment by mawww** [comment]
That seems like a very specific feature for a very specific corner case, I believe `␤` is good enough, and might make more sense as we can see that its a raw new line instead of the escape sequence (I think the regex engine will accept raw newlines).

**Comment by lenormf** [comment]
Alright, closing!
