### ISSUE TITLE
[markdown.kak] a code spans within a list item causes the entire list item highlighting to change.

### ISSUE THREAD

**Issue by nochiel** [mawww/kakoune#1870]
A code span in a list item changes the highlighting of the whole list item.

### Steps 

Consider the file below:
```sh
cat > test0.md
Use: colorscheme default
- a foo bar bar
- a foo and `a code span bar`.
- a foo and a bar.
- a bar foo bar
^D
```
### Outcome 

The entire list item is highlighted in the code span face.

```markdown
Use: colorscheme default, base16, solarized-dark

- `a foo and a code span bar`
- a foo and a bar
```
### Expected 

Only the code span should be highlighted in a different face.

```markdown
Use: colorscheme default, base16, solarized-dark

- a foo and `a code span bar`
- a foo and a bar
```

**Comment by mawww** [comment]
Hum, I cannot reproduce that here (although the current markdown highlighting does seem pretty fragile)

**Comment by nochiel** [comment]
>  I cannot reproduce.

Strange, now I seem to be getting a different result, still incorrect.  See attached.

![kak-markdown-codes-span-highlighting](https://user-images.githubusercontent.com/284914/36954314-2637427e-2032-11e8-8bad-9b259cc91ab1.png)
