### ISSUE TITLE
Scripting Guide

### ISSUE THREAD

**Issue by staab** [mawww/kakoune#1880]
When I got into Vim, it was only a month of struggling with its primitives (like their particular flavor or regex, `normal!`, etc) before I found [Learn Vim the Hard Way](http://learnvimscriptthehardway.stevelosh.com/), which is a great, practical book on how Vim works under the covers. I'd love to see the same sort of thing for kakoune, that goes beyond just the philosophy document; so far my experience has been characterized by wandering through somewhat terse documentation. Learning kakoune well enough to use was taken care of by [TRAMPOLINE](https://github.com/mawww/kakoune/blob/master/contrib/TRAMPOLINE), but I'd love to get to know the underlying mental model better.

EDIT: right after I posted this I found the [doc](https://github.com/mawww/kakoune/tree/master/doc) directory, which has some really good stuff. So maybe my suggestion would be to surface that a bit better. It's a little disorienting navigating between a fat readme, a sparse wiki, and source-controlled documentation.

**Comment by Delapouite** [comment]
Hello.

As you said, there are 3 main buckets of knowledge: README, /docs and the wiki, which is not that much.

Many duplicated info between README and /docs have been fused into /docs in the past. This situation can still be improved of course. In the end README should only be a short introduction, pointing to the relevant doc pages. The advantage of having almost everything in /docs is that it's accessible right from kakoune using the `:doc` command.

The wiki is more for extra topics, completing what's found in /docs. Excerpt from its front page:

    It offers extra knowledge complementing common topics covered in the README and in the official kakoune doc. So be sure to read those documents beforehand.

Also, kakoune insists on discoverability with a live autoinfo system, where vim keeps you in the dark. There are way less concept to understand but the real difficulty is to know shell scripting well enough to develop plugins.

**Comment by staab** [comment]
Cool, that's helpful. I've since read through most of the docs at this point and have a better idea of what's still going on, though I'd still read something like Learn Kakoune the Hard Way. I'm not sure if you want to leave this open for something like that or whether that should happen entirely external to the kakoune core project/repo anyway.

**Comment by Delapouite** [comment]
Possibly related: https://github.com/mawww/kakoune/issues/1122

**Comment by gspia** [comment]
As a new-comer to the editor and its scripting, if there had been a short(ish) intro, it probably would have saved my time and also made first steps not so hard, and in overall it would make the transition from the earlier editors easier.

It could contain something like 

- an intro to pre-installed kakoune-scripts (base, core, extra) with few words about how the most important of those scripts are related to other
- a short walk-through with some of the basic techniques to get things done (like parameterizing a command, running a shell-tool with the parameter, how to process it, to create a fifo-thing, and get something back to editor), 
- how to develop those scripts, some basic techniques/hints, like "generate the output with the example parameters first, then process it with awk separately to make sure it works, before starting to do things in the kak-scripts" etc. If doing this is normal/ok, then is there things to be aware when putting the awk into a kak-scripts, etc.

**Comment by mawww** [comment]
We do have `doc/interfacing.asciidoc` and `doc/writing_scripts.asciidoc` that already contain quite a bit of scripting information, there is also `doc/autoedit.asciidoc` that concentrates on how to write auto indentation hooks.

I think it would be pretty nice to cleanup those documents, and move them in doc/pages so that they are available through the `:doc` command. We could then introduce a scrpting.asciidoc page that would link to those. (We would not necessarily keep the current structure of the files, it might make more sense to reorganize that in a different set of documents).

**Comment by lenormf** [comment]
Is think this can be closed?
