### ISSUE TITLE
Go to last cursor location

### ISSUE THREAD

**Issue by staab** [mawww/kakoune#1887]
In vim, `<C-o>` jumps your cursor to the last location. I use this all the time for when I want to check something really quick then go back to what I was doing. `ga` is great when I need to go to a different buffer, but is there a good story for doing this within a single file?

**Comment by occivink** [comment]
You're in luck, vim's jump list also [exists in kakoune](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#jump-list)

**Comment by staab** [comment]
Beautiful, thank you!
