### ISSUE TITLE
Mapping to dash

### ISSUE THREAD

**Issue by staab** [mawww/kakoune#1897]
I'm trying to map to the  dash character, but I'm getting "'map' unknown option '-'". If I try escaping the dash, with a back slash, I get "'map' only a single key can be mapped". Wrapping either variation in quotes doesn't change anything. Also doing `<->` doesn't work, and `:doc mapping` doesn't say anything about dashes.

Related: is there a way to map to alt-dash?

**Comment by danr** [comment]
Use `--` like so:
```kak
map global normal -- - ' :echo dash was pressed!<ret>'
```

**Comment by occivink** [comment]
The convention that `--` signifies the end of switch also applies here. You can do `map global normal -- - <keys>` or `map -- global normal - <keys>`. 
As for mapping alt-dash you can use <a-minus>

**Comment by staab** [comment]
Awesome, thank you both!

**Comment by staab** [comment]
Also, it looks like <minus> also works for dash.
