### ISSUE TITLE
strange case of 'not enough elements in tuple' for set-options

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [mawww/kakoune#1908]
edit: whoops. Nevermind. I made some erronous assumptions about the datastructure of set-option and i was using the racer.kak completion plugin, but it was broken, and has been fixed as of one day ago. 

I thought set-option would be some kind of per buffer hashmap, mapping strings -> strings. But I guess the value data structure is a little more complicated. I still don't really understand why this error was happening or why what I did fixed it. 

## old issue submission:

for some reason kakoune is negating an argument because of the presence of a ':'

### Steps 

Just open up kakoune and paste in this command:
`set-option current racer_completions %@2.5\@45:year||{default+e}year{default+d} year:@`

### Outcome 
You will get an error 'not enough elements in tuple'
### Expected 
it should assign the option.

Also, try editing the command 

`set-option current racer_completions %@2.5\@45year||{default+e}year{default+d} year:@`

works, BUT. it removes the ':' on the end

`echo %opt{racer_completions}` -> `2.5@45year||{default+e}year{default+d} year`

**Comment by mawww** [comment]
Hello,

Just to give you a bit more info, Kakoune's options are actually typed, and a completions option is actually a `prefixed list of tuple of <string, string, string>`. The `|` separator delimits fields in a tuple, so I suspect you had one element of your completion list (elements are delimited by `:`) no following the syntax <string 1>|<string 2>|<string 3>.
