### ISSUE TITLE
Auto-create option associated with line_flags, ranges and replace-ranges if not already declared

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#1913]
Hi

```
add-highlighter window ranges foo
```
currently complains with an error : `1:1: 'add-highlighter' option not found: foo` which means we always have to pair this highlighter creation with an option declaration:

```
declare-option range-specs foo
add-highlighter window ranges foo
```

This is a bit redondant. In this case the `ranges` hl can only work with options of type `range-specs`.

So if `foo` is not already declared, I think `add-highlighter` should create the option on the fly instead of triggering an exception.

**Comment by mawww** [comment]
Nope, I think this is too error prone, it means we wont get an error if we mistype the name of the range option we want. range options are seldomly used interactively, so I dont think the convenience benefits outweights the costs.
