### ISSUE TITLE
Prompt completion for shared highlighters suggests incorrect candidate

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1914]
### Steps 

`:rmhl shared/ty<tab>`

(where `<tab>` means to press the actual tab key)

### Outcome 

`:rmhl shared/typescript/`

### Expected 

`:rmhl shared/typescript`

Why do I expect this? because if you try to remove `shared/typescript/` you get the error message `'rmhl' this highlighter do not hold children`, whereas removing `shared/typescript` works.

**Comment by Delapouite** [comment]
Potentially related: https://github.com/mawww/kakoune/issues/1712

**Comment by mawww** [comment]
I think the completion is correct, we do want to complete highlighting groups with a trailing slash, as we want to complete directory names with a trailing slash.

I'd say rmhl should consider that `rmhl shared/typescript/` means the same as `rmhl shared/typescript`.

**Comment by danr** [comment]
@mawww Ah right, that's a much better fix.
