### ISSUE TITLE
Segmentation Fault when creating docstring with ">>> """

### ISSUE THREAD

**Issue by Felix5721** [mawww/kakoune#1920]
When creating a docstring for sphinx, kakoune will crash as soon as you add space behind the >>>, if there is nothing behind it.

### Steps 
1. create docstring and add >>> to the beginning
2. add space after >>> 

### Outcome 
kakoune crashes with a segmentation fault

### Workaround
add the code first in the docstring, then prepend the >>> to it

**Comment by mawww** [comment]
I am not very familiar with sphinx docstrings, could you describe the file content to reproduce that ? I assume the filetype is set to python, is that correct ?

**Comment by Felix5721** [comment]
you can do the following: 
1. kak test.py
2. insert """>>> """

as soon as type the last of the three closing quotes kakoune crashes

**Comment by mawww** [comment]
Thanks, this is a tricky one, the python highlighting defines mutually recursive regions (docstring regions can contain python regions, which themselves can contain docstring regions).

The problem we run into is that:
```
""">>> """
       ^ HERE
```

We have both the python and a potential docstring region starting at HERE, and Kakoune ends up recursing infinitely between the two... I am trying to see what the best way to fix that would be.

**Comment by mawww** [comment]
Thanks for that report, should be fixed now.
