### ISSUE TITLE
Regex engine does not fully support POSIX regex syntax

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#1928]
### Steps 

 1. Create a test file:

         $ echo 'abc]def' > /tmp/test.txt

 2. Search for `]` characters with grep:

        $ grep '[]]' /tmp/test.txt
        abc]def

 3. Search for `]` characters with Kakoune:

        $ kak -n -e 'execute-keys / []] <ret>' /tmp/test.txt

### Outcome 

Kakoune prints an error:

> 1:1: 'execute-keys' regex parse error: unexpected ']' at '[]\<\<\<HERE>>>]'

### Expected 

Kakoune selects the `]` 

### Notes

It turns out that you can get this to work in Kakoune by backslash-escaping (`[\]]`) but it would be nice if it worked without a backslash too:

  - The [POSIX regular expressions definition](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html) says "The <right-square-bracket> ( ']' ) shall lose its special meaning and represent itself in a bracket expression if it occurs first in the list (after an initial <circumflex> ( '^' ), if any)."
  - The [Boost Regex docs](http://www.boost.org/doc/libs/1_66_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html#boost_regex.syntax.perl_syntax.character_sets) don't say either way, although they link to [the Perl regex docs](http://perldoc.perl.org/perlre.html) which say "If you want either "-" or "]" itself to be a member of a class, put it at the start of the list (possibly after a "^" ), or escape it with a backslash."
  - [Vim's documentation](http://vimdoc.sourceforge.net/htmldoc/pattern.html#/\]) says "To include a literal ']', '^', '-' or '\' in the collection, put a backslash before it [...] (Note: POSIX does not support the use of a backslash this way). For ']' you can also make it the first character (following a possible "^")"
  - [Python's documentation](https://docs.python.org/3.5/library/re.html?#regular-expression-syntax) says "To match a literal ']' inside a set, precede it with a backslash, or place it at the beginning of the set."
  - The [PCRE2 documentation](http://www.pcre.org/current/doc/html/pcre2pattern.html#SEC9) says "If a closing square bracket is required as a member of the class, it should be the first data character in the class (after an initial circumflex, if present) or escaped with a backslash."

**Comment by mawww** [comment]
I looked at that, and implementing support for it is very easy. However, Kakoune's regex do not follow posix or perl, it follows ECMAScript regex, as documented in `:doc regex`. That syntax does not allow un-escaped `]` in character class.

We already do deviate slightly from the standard, mostly by being stricter in what needs to be escaped (because we support a few more escapes, such as `\h` or `\A`). So I am on the fence on that, I think ECMAScript is a good fit, its a clean syntax, its what standard c++ regex use as well. On the other hand, its such a small change, and lots of regex engine do support that...

**Comment by Screwtapello** [comment]
I didn't realise ECMAScript regexes (and other variants) had drifted from POSIX; I'd assumed they were all just additive. Looking at some comparisons now, I can see that it's not really practical to make Kakoune's regex library a proper superset of POSIX (for one, POSIX requires that all backslashes in a character set are taken literally).

Given Kakoune is dependent on the POSIX environment and uses POSIX `sh` heavily, I just kind of assumed Kakoune's regexes would be close enough to POSIX EREs or Perl REs that my existing habits would work, and I suspect that's true for a lot of Kakoune's potential user-base.

Considering that a purely empty character class should fail to match any string and is therefore not useful, while an empty negated character class (`[^]`) is equivalent to `.` and therefore not useful, would it be difficult to add a special rule to Kakoune's regex parser to raise an error when it detects such a thing and say "it looks like you're trying to use POSIX-style character classes, but Kakoune follows the ECMAScript syntax; put other characters into the character class or escape the closing square bracket with a backslash"?

**Comment by eraserhd** [comment]
Just found this looking up another issue, so here's the spec link that disallows `[]]` for reference, http://www.ecma-international.org/ecma-262/6.0/#sec-classatomnodash

**Comment by Screwtapello** [comment]
At this point, I'm used to Kakoune's regex engine by now, it's documented, and the POSIX incompatibility doesn't seem to be a pressing issue (not nearly as many dupes for this issue as, say, the ones about smarttabs) so I'm happy to close it.
