### ISSUE TITLE
Implement a builtin `documentation` face

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1944]
Hi,

Some frameworks and languages allow writing embedded documentation, generally using comment blocks e.g. doxygen strings.

It'd be nice to highlight those differently than comments to improve readability, using a builtin `documentation` face that the builtin colorschemes would initialize.

Thanks.

**Comment by mawww** [comment]
I´d accept a PR that adds a `documentation` face to all provided colorcheme.
