### ISSUE TITLE
Odd session names result in blank '$kak_session' variable

### ISSUE THREAD

**Issue by daboross** [mawww/kakoune#1946]
### Steps 

Start kakoune with `kak -s "#named_session"`

Enter command `:echo %sh{ echo "\"the session is '${kak_session}'\"" }`

### Outcome 

The command results in `the session is ''`

### Expected 

I expected the command to result in `the session is '#named_session'`

---

Getting the session via the `$kak_session` shell variable seems to work for most regular session names, but fails if the session name has a space in it (`-s "named session"`), or starts with `#`. `kak -l` does correctly list the session as `#named_session`.

If the best solution to this would be disallowing `#` at the start of session names and whitespace within session names, it seems like it's always possible to do a more general project name like `language-#...`.

`/bin/sh` is `dash`, and I'm running kakoune compiled from git revision bec849ae14ae5db6a793d23b4a1b3095d484fcc2.

**Comment by lenormf** [comment]
I wonder if that's not simply an injection of a commented string into the command, i.e. `:echo the session is #abc` would result in "the session is".

**Comment by daboross** [comment]
yeah, I had to do a bit of experimenting with various combinations of `echo` and quotations to get it right.

`echo %sh{ echo "\"the session is '#named_session'\"" }` does correctly display `the session session is '#named_session'`, though, so I'm fairly certain the variable is empty.
