### ISSUE TITLE
Wiki command to wrap at 80 chars gives "'exec': no selections remaining" debug error

### ISSUE THREAD

**Issue by DaanDeMeyer** [mawww/kakoune#1959]
### Steps

Add the following command mentioned in the Wrapping wiki page to kakrc: https://github.com/mawww/kakoune/wiki/Wrapping

hook buffer InsertChar [^\n] %{
   exec -draft "Gh<a-k>.{80,}<ret><a-;>bi<ret><esc>"
}

### Outcome

The hook correctly inserts newlines after 80 characters on a line but on every character insert I get an "'exec': no selections remaining" message in the debug buffer.

### Expected

No error messages in the debug buffer

**Comment by danr** [comment]
You need a `try` around that exec. The error comes from the `<a-k>` (which is not copied correctly to your issue) not matching any selections. I have updated the wiki.

**Comment by DaanDeMeyer** [comment]
Works perfectly. Thank you for the quick response!
