### ISSUE TITLE
Kakoune opens empty buffer when waiting for shell command

### ISSUE THREAD

**Issue by alyssais** [mawww/kakoune#1973]
### Steps 

Try running this custom command:

https://github.com/alyssais/dotfiles/blob/e09838d7461c65a9a6e0f9b1c527e3adf0f71a6d/.config/kak/kakrc#L40-L44

### Outcome 

After about a second, kakoune opens a new empty buffer.
Once the shell command is complete, it will additionally open the selected file.

### Expected 

Kakoune waits for the shell command to return and opens the selected file with no intermediary empty buffer.

**Comment by mawww** [comment]
Ok, I see whats happening.

As you open the fzf tmux window, the kakoune window gets resized, as such, the ncurses ui loses its display buffer as its now out of sync with window  size. So this looks like an empty buffer has been opened, but its just the ncurses UI not having any data on what to display for the buffer (it still has that for status line and info box, as those are not dropped on resize). I'll see how we can fix that.
