### ISSUE TITLE
`gi` on a multiline selection

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1984]
I'm not sure if this is a bug along the same lines of #1964, or if this is how <kbd>g</kbd><kbd>i</kbd>
 behaved like since the beginning.

### Steps 

* Create a multiline selection
* Jump to the beginning of the line with <kbd>g</kbd><kbd>i</kbd>

### Outcome 

The jump is made on the line relative to the cursor.

### Expected 

The jump is made on the line relative to the anchor. I think this is unexpected because <kbd>I</kbd> jumps to the anchor.

### Example

With the cursor on `f`, and the anchor on `a`:

```
%(abc
def)
```

<kbd>g</kbd><kbd>i</kbd> selects `d`, not `a`.

**Comment by mawww** [comment]
Hum, yeah this is a tricky one, I am not sure what behaviour seems the best one there, I quite like the fact that <kbd>g</kbd><kbd>i</kbd> is only dependent on the cursor position, but at the same time, I do agree that having it do something different from what <kbd>I</kbd> does seems surprising.
