### ISSUE TITLE
Scrolling in inactive window on buffer edit

### ISSUE THREAD

**Issue by tripokey** [mawww/kakoune#1989]
### Steps 
1. Open a file containing enough text to fill several screens. 
2. Go to the middle of the file. 
3. Create a new window w2 with the same buffer any go to the beginning of the file in w2.
4. Add some lines in w2.

### Outcome 
Window w1 scrolls, or rather stays fixed on the same line number. 

### Expected 
W1 not to stay fixed on the line numbers but instead change the view based on the number of lines added in W2 giving the illusion of staying fixed.

**Comment by Delapouite** [comment]
Related commands/options in vim: [scrollbind](https://neovim.io/doc/user/scroll.html#scroll-binding) and [cursorbind](https://neovim.io/doc/user/options.html#'cursorbind')
