### ISSUE TITLE
Keep the entire history of 'previous buffer'

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#1993]
Currently only the last buffer is recorded (accessible via `ga` or by deleting the current buffer) so if you delete two buffers in succession, the client will jump to the first buffer in the list (because there is no "last buffer" at this point). 

It would be nicer if the whole history was kept, so that deleting buffers in succession would be more predictable.

**Comment by Delapouite** [comment]
I think this feature could be implemented if the jump-list was exposed somehow. (so it's a bit like the issue on exposing the undo history tree nodes)
