### ISSUE TITLE
Building auto-complete cache for pipe or similar commands is very slow

### ISSUE THREAD

**Issue by jacobdufault** [mawww/kakoune#1997]
The first time I invoke `|` or similar kakoune freezes for 20+ seconds as it discovers programs to execute. Can this be made async/faster?

**Comment by lenormf** [comment]
Yes, get and SSD!

**Comment by jacobdufault** [comment]
This is on an SSD :)

**Comment by lenormf** [comment]
20 seconds sounds like a lot, do you have a very long `PATH`? Does it contain network-mounted directories? Are you using a debug build -if yes, does the release build go any faster?

If you profile the code (.e.g with `perf`), how much time does the `complete_command()` function take (this should be the bottleneck, if generating candidates is what's taking too long)?

**Comment by jacobdufault** [comment]
Hmm, it seems that even `ls /usr/bin` is slow. Likely an issue with my system.

**Comment by jacobdufault** [comment]
stat on one of the files was taking an extremely long time. Is kakoune using a timeout, and/or can it be shortened/made configurable?

**Comment by lenormf** [comment]
No timeout is implemented, and the overhead is probably not worth it. If calling `stat` on a file that's stored on your system takes a long time for seemingly no reason, I think that's a filesystem issue, and thus not really the editor's concern.

I guess you could do a partition check, or use the following to see what's taking too long:

```
$ strace -vvv -T -- stat /usr/bin/<file>
```

**Comment by jacobdufault** [comment]
Yea, I was able to trace down the stat issue using strace (due to a forced fuse filesystem). I figured out a work-around for the time being until the issue is gets correctly fixed.

Thanks for the time :)
