### ISSUE TITLE
Can't figure out how to lint

### ISSUE THREAD

**Issue by ervasive** [mawww/kakoune#2003]
Hi everyone, sorry if it's a stupid question (and I'm sorry to post it in the issue tracker, I didn't find any other place to get help), but I'm trying to enable linting in kakoune and sadly can't quite figure it out.

In my case, I'm trying to lint a JavaScript/React project. For example, this is the steps I follow:
1. [Initialize project](https://github.com/facebook/create-react-app#quick-overview)
    `npx create-react-app kakoune-lint-example && cd kakoune-lint-example`
2. [Install formatter](https://github.com/Delapouite/eslint-formatter-kakoune#install)
    `npm install --save-dev eslint-formatter-kakoune`
3. [Create eslint config](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#displaying-lint-output-in-the-editor)
    `echo "{\n\t\"extends\": \"react-app\"\n}" > .eslintrc`
4. Introduce lint error
    `echo error >> src/index.js`

When I run the linter from the terminal with the following command:
```
./node_modules/.bin/eslint --format=node_modules/eslint-formatter-kakoune src/index.js
```

It seems that it works as intended. Here's the output I get:

```
/home/ruslik/Playground/kakoune-lint-example/src/index.js:9:1: Warning: Expected an assignment or function call and instead saw an expression. (no-unused-expressions)
/home/ruslik/Playground/kakoune-lint-example/src/index.js:9:1: Error: 'error' is not defined. (no-undef)
2 problems
```

Then I open the file in Kakoune:
```
kak src/index.js
```
and set the `lintcmd` command:
```
set-option buffer lintcmd 'node_modules/.bin/eslint --format=node_modules/eslint-formatter-kakoune'
```
I also tried to provide the absolute path:
```
set-option buffer lintcmd '/home/ruslik/Playground/kakoune-lint-example/node_modules/.bin/eslint --format=node_modules/eslint-formatter-kakoune'
```
but when i run `lint` I have no output neither in `*lint-output*` nor `*debug*` buffers.

Can someone please point me in the right direction with this, thanks.

---

kakoune version: AUR installed 2018.04.13-1

**Comment by lenormf** [comment]
Before calling `lint`, enable debug flags to see what's executed:

```
set global debug shell
```

You can also have a look at the [syntastic](https://github.com/lenormf/kakoune-extra/blob/master/syntastic.kak) script.
