### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by Superpat** [mawww/kakoune#2004]
Currently it's not compiling on openbsd 6.3-current.

I believe the two main culprits are the Makefile and file.cc

I was able to get the Makefile working by copy pasting the entry for dragonfly and changing it to openbsd, but that doesnt work for file.cc (it will compile, but it will abort) 

Obviously this is due to openbsd working differently than dragonfly, I'll investigate further when I have time, but I'm opening an issue here to track my progress and / or get the ball rolling.

For the record, the makefile error was that it could not find ncursesw, but that error disappeared after copy pasting the dragonfly / freebsd entry. Not sure if it should be adapted to openbsd yet.

The file.cc error is `finding executable path is not supported on this platform" in this case, copying the freebsd / dragonfly entry makes it compile, but abort at runtime. I'm fairly sure the abort is due to file.cc mod and not the makefile mod.

**Comment by mawww** [comment]
If things compile, the Makefile must be ok.

Kakoune needs a way to find the path of its binary, and there is no standard posix way to do that, and from a quick research, it would seem OpenBSD does not provide any way to do that. We need it for two reasons, both of which are linked to making Kakoune work even if not installed:

* We find Kakoune resource files using a relative path from the bin (../share/kak)
* We add Kakoune binary directory to the PATH to ensure scripts can use the `kak` command.

We could do those using compile time paths, as is traditional on unix, but I dont really like that practice. We might have to for OpenBSD if we cannot find a way to get that path.

**Comment by Superpat** [comment]
Yeah, seems like openbsd considers that a bit of a security issue. The mailing list says to hardcode it so that's what I'll try.

**Comment by dahlbaek** [comment]
In view of #2131 I suppose this should be closed.
