### ISSUE TITLE
%reg{#} is slow with many selections

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#2008]
### Steps 

On a debug build, create many (5k+) selections and do `:echo %reg{#}<ret>`

### Outcome 

The command takes seconds to complete.

### Expected 

The message is printed instantaneously, much like with `:echo %reg{.}<ret>`

**Comment by Delapouite** [comment]
Is the situation better with this commit: https://github.com/mawww/kakoune/commit/2d96fbed7c68dc43e0551a1576d29c922e73705f ?
