### ISSUE TITLE
Rename and move TRAMPOLINE

### ISSUE THREAD

**Issue by inquisitiv3** [mawww/kakoune#2023]
I propose that we move the file `contrib/TRAMPOLINE` to `doc/pages/tutorial.asciidoc`.

It would be more clear what the document actually is. Renaming it to `tutorial` would make it easier for other people to find it when searching. I'd to ask in the IRC channel to find the file.

I would also like the file to be referred in the README for making it easier to find it.

A small detail: All the other documentation files in the repo is named with only lowercase letters. Let's follow the pattern.

I haven't checked if moving the file to the specified directory will create problems.

**Comment by mawww** [comment]
This would require to rewrite the trampoline to be valid asciidoc, it seems pretty tricky to manage to get the same rendering.

**Comment by lenormf** [comment]
I specifically wrote the `TRAMPOLINE` file to be:

* a tutorial that is *not* documenting all of the primitives available or their quirks
* a user-maintained (as in, not touched by the maintainer unless they want to) overview of the editing language

I think `contrib` is the right directory for the document, and its current format makes it more readable than asciidoc (although it looks blocky).

**Comment by inquisitiv3** [comment]
> This would require to rewrite the trampoline to be valid asciidoc, it seems pretty tricky to manage to get the same rendering.

That's fair. I concede that the document don't have to be written in ASCIIDOC.

> I specifically wrote the TRAMPOLINE file to be:
> 
>     a tutorial that is not documenting all of the primitives available or their quirks
>     a user-maintained (as in, not touched by the maintainer unless they want to) overview of the editing language
> 
> I think contrib is the right directory for the document, and its current format makes it more readable than asciidoc (although it looks blocky).

Is the file still accessible if it's located in the contrib directory? The important part is that the document should be accessible from within the editor. Which directory the file is located isn't important if there's no difference for the end-user.

I still think that the file should be renamed to `tutorial` or something similar. The name `TRAMPOLINE` doesn't describe well what the actual content is.

**Comment by lenormf** [comment]
It's not a tutorial.

**Comment by inquisitiv3** [comment]
@lenormf What you mean? To quote your earlier comment:

> I specifically wrote the TRAMPOLINE file to be:
> 
> * a tutorial that is not documenting all of the primitives available or their quirks

And what is it, if not a tutorial?

**Comment by lenormf** [comment]
Your definition of the world seems to be "take the user by the hand through several steps to teach them how to use the editor".

I used this term for lack of another better one, but this document is more of a flat summary of the most common primitives, and as such it sits somewhere between watered down documentation an actual tutorial.

If something has to be included with the builtin documentation pages, it should be more thorough and descriptive than what I wrote, making this file a builtin `:doc` page and calling it a tutorial is a shortcut that works around the fact that there's nothing else yet.

**Comment by mawww** [comment]
I am still waiting for volonteers who want to write a kaktutor :)

**Comment by Delapouite** [comment]
Related discussion about kaktutor: https://github.com/mawww/kakoune/issues/1122

**Comment by inquisitiv3** [comment]
@lenormf When I misinterpreted your intentions with the document.

As I started this discussion thinking that the TRAMPOLINE was the community's small but existing equavalent to `vimtutor` I think that I should end the discussion here and continue in the issue that @Delapouite linked.
