### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by Vm900** [mawww/kakoune#2024]
Hi folks,
I have been trying to build kak but i keep getting the following error:
![kakouneerror](https://user-images.githubusercontent.com/9399631/39486898-340d5380-4d6d-11e8-9b1c-9e2283e7d181.png)
Please Help
Thanks

**Comment by gebulmer** [comment]
What does `g++ --version` output?

in the build requirements it's listed: `A C++14 compliant compiler (GCC >= 5 or clang >= 3.9) along with its associated C++ standard library (libstdc++ or libc++)`

Taking a quick look at the slitaz repositories it seems (disappointingly) that they only have gcc 4.x in

**Comment by Vm900** [comment]
@gebulmer  Yes,i have them installed
![gpp](https://user-images.githubusercontent.com/9399631/39495282-2c3d76b4-4d89-11e8-8fcb-b34331955229.png)

**Comment by mawww** [comment]
This is due to a too old gcc, as the README indicates, Kakoune requires at least gcc 5.

**Comment by Vm900** [comment]
@mawww This is what i have on my system
![kakcompiler](https://user-images.githubusercontent.com/9399631/39525101-f6927b88-4e12-11e8-90d3-71dc36f60764.png)
For some reason it keeps picking the old one in the list.I removed the old g++ and it broke other things,had to reinstall the whole os from scratch.

**Comment by Screwtapello** [comment]
Try `make PREFIX=$HOME/.local CXX=g++-63`

**Comment by Vm900** [comment]
@Screwtapello Sir you're flipping genius.I am cooking now.Thanks a million
