### ISSUE TITLE
[RFC] Explicit reparsing

### ISSUE THREAD

**Issue by mawww** [mawww/kakoune#2029]
In the explicit-reparsing branch is a proposal for the following change:

`%sh{...}` are not reparsed automatically, i.e. they expand to a single token, so `echo %sh{printf "foo; echo bar"}` displays "foo; echo bar" instead of "bar".

`%..{...}` strings are reparsed explicitely when using two `%` (so `%%sh{...}` will have the same behaviour `%sh..{...}` used to have).

The goal of this change is to make the command language more regular, and make reparsing explicit so that users know whats going on, reducing the risk of bugs due to unexpected reparsing.

Alternatively, we could keep the status quo, reparsing is disableable by quoting in double quotes: "%sh{...}" is always a single token. My main issue with that is that the "safe" behaviour is opt-in, rather than opt-out. Also, reparsing only %sh{...} seems a bit inconsistent. However the status quo does not break existing scripts, and is a bit closer to what the shell does.

This change is inspired by tcl's {*} feature, as it seems Kakoune's command language is pretty close to tcl's (including the "everything is a string even if we have typed data internally" model).

I'd like some feedback on such a change.

**Comment by occivink** [comment]
I think that'd be useful, `"%sh{...}"` is not super practical currently because you have to escape all `"` inside the shell block and these are very common.

**Comment by mawww** [comment]
@lenormf @danr @Delapouite @Screwtapello @alexherbo2 Any opinions on that ?

**Comment by Screwtapello** [comment]
I don't feel experienced enough with Kakoune's scripting to have an informed opinion on the matter, but sure, let's give it a try.

**Comment by ekie** [comment]
i think it is a good change, simplifying and improving the readability of the command language,  especially for new users.

**Comment by lenormf** [comment]
It's probably more intuitive to users, considering how many questions we've had about why `:echo %sh{ls}` showed "command not found".

**Comment by mawww** [comment]
The new direction for that is just to fix evaluate-commands so that reparsing can be done with it, the goal is to make `evaluate-commands %sh{...}` virtually equivalent to the old `%sh{...}`. This is reflected in the current explicit-reparsing branch.

That makes things simpler and more regular, it also interacts well with my plans regarding exec/eval (namely make them diverge in their defaults, eval should default to with-hooks (with-maps is irrelevant, and shouldn't arguably be part of eval switches), exec should default to `-without-maps` and probably `-without-hooks`).

**Comment by mawww** [comment]
This is pending as `evaluate-commands %sh{...}`, will come together (hopefully) with the command line parsing overhaul to group breaking changes in one go.
