### ISSUE TITLE
Shift Insert doesn’t work anymore

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2031]

**Comment by Screwtapello** [comment]
What terminal are you using?

**Comment by alexherbo2** [comment]
[Alacritty](https://github.com/jwilm/alacritty)

**Comment by Screwtapello** [comment]
Looks like Alacritty deliberately disabled shift-insert when mouse-events are enabled in [their latest commit](https://github.com/jwilm/alacritty/commit/5be0e3ad8fcde5d8dec98c0e71a2b495294d03be). I think they forgot that there are non-mouse-based ways to trigger the "paste selection" action; you'd better file an issue about it.

In the mean time, you should be able to restore shift-insert handling with `set-option -add global ui_options ncurses_enable_mouse=false`

**Comment by mawww** [comment]
Looks like this is not a Kakoune bug, closing.
