### ISSUE TITLE
3d does only deletes one character

### ISSUE THREAD

**Issue by jacobdufault** [mawww/kakoune#2033]
I'm not sure if this is intentional. `2Ld` does what I'd expect `3d` to do.

In comparison, `3o` opens 3 lines

**Comment by lenormf** [comment]
It's intentional, the paradigm of Kakoune is "selection first". The `o` primitive is not really comparable because it adds new characters, whereas the `d` one removes the current selection - as opposed to "remove the character under the cursor" in other modal editors.

**Comment by Delapouite** [comment]
@jacobdufault I think this issue can be closed.
