### ISSUE TITLE
stack trace

### ISSUE THREAD

**Issue by samuel1** [mawww/kakoune#2034]
uncaught exception (N7Kakoune13assert_failedE):
assert failed "is_valid(coord)" at buffer.cc:182
[Debug Infos]
pid: 22
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x2b) [0x8731cb]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x33) [0x8726b1]
kak(_ZNK7Kakoune6Buffer11iterator_atENS_11BufferCoordE+0x38) [0x874eac]
kak(_ZN7Kakoune12get_iteratorERKNS_6BufferENS_11BufferCoordE+0x183) [0x949039]
kak(_ZNK7Kakoune11DisplayAtom6lengthEv+0x68) [0x9493a8]
kak() [0xb435f4]
kak(_ZNK7Kakoune6Window12buffer_coordENS_12DisplayCoordE+0x3ad) [0xb43fed]
kak(_ZN7Kakoune10InputModes12MouseHandler10handle_keyENS_3KeyERNS_7ContextE+0x12a) [0x9cf632]
kak(_ZN7Kakoune10InputModes6Insert6on_keyENS_3KeyE+0xcb) [0x9d906b]
kak(_ZN7Kakoune9InputMode10handle_keyENS_3KeyE+0x51) [0x9cf1fb]
kak(_ZN7Kakoune12InputHandler18repeat_last_insertEv+0x22b) [0x9cc971]
kak(_ZN7Kakoune18repeat_last_insertERNS_7ContextENS_12NormalParamsE+0x24) [0xa6e5d9]
kak(_ZN7Kakoune10InputModes6Normal6on_keyENS_3KeyE+0x953) [0x9d0ec9]
kak(_ZN7Kakoune9InputMode10handle_keyENS_3KeyE+0x51) [0x9cf1fb]
kak() [0x9cd329]
kak(_ZN7Kakoune12InputHandler10handle_keyENS_3KeyE+0x20c) [0x9cd538]

**Comment by mawww** [comment]
Thanks for reporting this, it should be fixed now.
