### ISSUE TITLE
How does one override a script in /share/kak/?

### ISSUE THREAD

**Issue by Laaas** [mawww/kakoune#2035]
I can not seem to find a way to do this, e.g. making a file at the identical path in my configuration directory.
This would be very useful, because some times the defaults do not fit one at all, and as far as I can see, there is no good way to remove hooks that don't have a group defined.

**Comment by mawww** [comment]
The current best way to do that is to create your own autoload folder in `~/.config/kak/autoload` and symlink every bundled scripts but the one you want to override inside that folder.
