### ISSUE TITLE
formatter.kak: Cursor position lost after executing the format command

### ISSUE THREAD

**Issue by fsub** [mawww/kakoune#2037]
### Steps 

- :set-option buffer formatcmd "clang-format --assume-filename ${kak_buffile}"
- open some C++ source file
- move the cursor to line x, column y
- :format

### Outcome 

- the cursor is placed at the end of the current buffer

### Expected 

- the cursor should be located at its original position, i.e. line x, column y (see #1492)

**Comment by Screwtapello** [comment]
This happened to me the other day with `rustfmt` set up as `formatcmd`. But I think that was in a long-running Kakoune instance so maybe the running Kakoune binary was out of sync with the `.kak` files on disk... I didn't have the patience to look deeper. Perhaps I was wrong, though.

**Comment by fsub** [comment]
@Screwtapello Thank you for the hint. In my case, the problem can be reproduced even with a fresh kakoune session and with `cat` as `formatcmd`. But the issue seems to be related to my config.

**Comment by Screwtapello** [comment]
If you figure out what the problem was, let me know!

**Comment by fsub** [comment]
`apply_diff()` in `normal.cc` has a fixed internal size limit. If this limit is exceeded, instead of performing a detailed diff, the buffer is cleared and rewritten.

**Comment by mawww** [comment]
This is actually related to pipe and size, we apply a diff algorithm to determine what changed after a pipe, but as this can get slow, Kakoune limits it to 100KB, if the selection is bigger, it will just erase and replace, leading to the behaviour you experience.

That 100KB limit was added to avoid those slow downs. I guess we could raise that slightly.

**Comment by lenormf** [comment]
The `ko.cpp` file is only 62KB, even if bumping up the hard-coded limit works for this file, it's not unusual to have source files as big as a few hundred KBs. Is there a way to make this algorithm more efficient, or to use one that crunches more data?

**Comment by mawww** [comment]
We can probably make the algorithm much more efficient by diffing lines first, then diffing characters (or maybe just at the word level ?). Right now we are diffing at the character level, which is what makes this much slower than say reloading a file (where we do diff the buffer state and the filesystem state at the line level).

**Comment by fsub** [comment]
I originally experienced the problem when trying to format about 10k lines of C++ code. Bumping the limit from 100KB to 5000KB seems to work for my expected use cases. For me, a small amount of lag is acceptable. It seems hard to tell if there is a good choice that serves most users. If there is an improved algorithm it could relax the situation.

**Comment by Screwtapello** [comment]
This just bit me on a 52KB file. Bumping the limit seems like a good first step, and the algorithmic change to diff by lines seems like a good avenue for future improvement.
