### ISSUE TITLE
Text Substitution Performance

### ISSUE THREAD

**Issue by fsub** [mawww/kakoune#2038]
### Steps 
- open [test.txt](https://github.com/mawww/kakoune/files/1991855/test.txt)
- <kbd>%</kbd><kbd>s</kbd><kbd>Space</kbd><kbd>Enter</kbd><kbd>c</kbd><kbd>Space</kbd><kbd>Space</kbd><kbd>Esc</kbd>

### Outcome 
- kakoune should be ready within a second

### Expected 
- kakoune takes at least tens of seconds to finish this operation

**Comment by lenormf** [comment]
Can't reproduce:

```
$ time kak -n -e 'exec \%s<space><ret>c<space><space><esc>;quit!' a.cc
kak -n -e 'exec \%s<space><ret>c<space><space><esc>;quit!' a.cc  0.32s user 0.07s system 98% cpu 0.397 total                                                                                                       
$ time kak -e 'exec \%s<space><ret>c<space><space><esc>;quit!' a.cc
kak -e 'exec \%s<space><ret>c<space><space><esc>;quit!' a.cc  0.83s user 0.26s system 104% cpu 1.045 total
```

Try a release build, with the `-n` flag. Otherwise, please upload a profiling report (`perf`) and maybe the output of `time`.

**Comment by fsub** [comment]
@lenormf My regularly used version of kakoune should be optimized. To be sure, I compiled a fresh clone of the master branch with `debug=no` and used default configuration settings.
```
$ time kak -n -e 'exec \%s<space><ret>c<space><space><esc>;quit!' test.txt 

real	0m0.440s
user	0m0.369s
sys	0m0.071s
```
Performance of the command
```
$ time kak -e 'exec \%s<space><ret>c<space><space><esc>;quit!' test.txt 
```
is actually worse than originally described. It takes minutes or possibly hours rather than tens of seconds. I cannot give exact numbers due to a lack of patience.
You can find some perf output in [perf.txt](https://github.com/mawww/kakoune/files/1992468/perf.txt). Please let me know if you need a different thing.

I tried to track down which settings cause the problem. I can reproduce it with `autoload` stripped down to `base/file.kak` and `core/c-family.kak`.

Another observation is that performance seems to be okay for large files that contain simple text (instead of C++ source code).

**Comment by fsub** [comment]
I had a look into `c-family.kak`. I don't know why but removing `objc` from line 128 solves the performance issue for me.

**Comment by lenormf** [comment]
I still can't reproduce the issue, even with autoload enabled.

I'm wondering if your issue doesn't stem from f99f0020dce5c447886c4a21b082a02daf595ac7. Do you still experience the bug, if you revert the file back to fea6bc952488cb8e897bc9e921a5408378d9b99d, or 5c247bf1dd66a46b3263f232f353e7949e8aafd0 ?

A problem I *do* hit however, is that the editor pegs the CPU at 100% if I hit `u` after doing the replacement shown as reproducer of this issue :p

**Comment by mawww** [comment]
This is indeed a performance bug, I think various things are going on, but I suspect the root of the problem is `-itersel`, which runs commands/keys for each selection separately. I would like to explore what could be done to remove that. The initial rationale for `-itersel` was to prevent selection being merged if they went overlapping, there might be a better way to do that (after all, we do allow overlapping selections in various cases, it might make sense to temporarily allow that in certain special cases).

**Comment by fsub** [comment]
@lenormf Using older versions of `c-family.kak` does not help. My current environment is GNU/Linux 4.16.8, glibc 2.27, and gcc 8.1.0.

**Comment by mawww** [comment]
Things should be better on latest master, although there are still other cases where we might have the same slowdowns (fixing that would require to rework itersel).

**Comment by fsub** [comment]
@mawww Thanks, works perfectly. On my low performance machine I now get the following timings:
```
$ time kak -e 'exec \%s<space><ret>c<space><space><esc>;quit!' test.txt

real	0m0.846s
user	0m0.719s
sys	0m0.133s
```
