### ISSUE TITLE
file must end in newline

### ISSUE THREAD

**Issue by samuel1** [mawww/kakoune#2039]
It is not possible to save a file with no characters, or a file which doesn't end in a newline

Not sure if, or how to solve that -- I was testing out a parser, but couldn't create files to test it's error handling at file-end

**Comment by mawww** [comment]
Yeah, Kakoune assumes all buffers have at least one line, and all lines have an end of line. This is a pretty strongly entrenched assumption, and I think it make sense for Kakoune domain (code editing).

This assumption makes a lot of the code much simpler, for example we always have at least 1 selection in Kakoune, and a selection is always lying on a valid range of characters. If we remove that assumption, then either we need to handle the case where we have no selection, or we have to handle the case where a selection does not lie on any valid character (as there are no characters in the buffer at all).

**Comment by samuel1** [comment]
Mmm, you're right, and some tools require a line-ending file

I'll only make a suggestion for the sake of consideration -- I probably would not implement it

Enforce the file to contain at-least one (any) character, but move new-line characters to the start of the visual line

This would mean users would know when they're on a new-line character -- since it would be the only character that can start a line

Then the rest of the line could be made up of any characters

**Comment by mawww** [comment]
Moving the newlines to the start of visual lines would be a huge change, I dont think it would make a lot of sense for Kakoune to modify that.
