### ISSUE TITLE
Add or Delete One Column of text, like visual mode in VIM

### ISSUE THREAD

**Issue by sittim** [mawww/kakoune#2049]
I want to make change to table like so:

```
Start               Finish
  V                   V

| table  |     | table       |
|--------|     |-------------|
| rec 1  |     | rec 1       |
| rec 2  |     | rec 2       |
```

In VIM I can use the visual mode, select 1 vertical column, yank and paste it five times.  Can you do a vertical column selection in kak, select it and paste it multiple times?  Likewise, can you select a column and delete it?

**Comment by occivink** [comment]
There are multiple ways you could do that. The most ergonomic I can think of would be to select the entire table (with paragraph selection for example), split it by line (`<a-s>`), reduce to cursor (`<a-;>`) move the cursors to the desired column and then `yp`

Or you could place the cursor at the top of the target column, do `XC` (where X is the number of lines the table spans) and `yp`.

**Comment by sittim** [comment]
Wow, that does work well...
