### ISSUE TITLE
<a-;> in prompt mode

### ISSUE THREAD

**Issue by hcnelson99** [mawww/kakoune#2060]
Would it be possible to support insert mode's <a-;> in prompt mode?

This is potentially related to #801 but could be a less major change while still allowing for comparably complex bindings.

**Comment by mawww** [comment]
This would be pretty tricky and has the same problems as a general support for Kakoune normal mode on the command line: it can trigger a recursive prompt (imagine editing a command, and using `<a-;>/` to search, this needs to display a search prompt somewhere, and that prompt would naturally need to be providing support for `<a-;>`...

**Comment by occivink** [comment]
I think this would also solve #1958 (and #1217 which is related): by combining `prompt -on-change` and `<a-;>` in prompt-mode it would be possible to re-implement incremental search cleanly. 

Regarding recursive prompts, this issue already exists if you do `<a-;>i` multiple times in insert mode. It's not clean, but it doesn't seem like a huge issue.

**Comment by mawww** [comment]
@occivink I am not sure we got the same understanding of this issue, my understanding is that <a-;> would provide access to normal mode to edit the *prompt* content. If it is a way to go back temporarily to normal mode, as I think you understood it, then it should be much easier to implement, and could make sense.

@hcnelson99 Which interpretation is correct ?

**Comment by hcnelson99** [comment]
Amazing! Thank you so much for this great editor @mawww !
