### ISSUE TITLE
Using kak for C++ development

### ISSUE THREAD

**Issue by sittim** [mawww/kakoune#2063]
There used to be a tutorial on how to get started with C/C++ development.  The tutorial seems to be gone.  I would love to start using kak, but I do not know enough about it to be able to learn how to setup completion and other clang functions from the source file: https://github.com/mawww/kakoune/blob/master/rc/extra/clang.kak
Can someone point me in the direction of how to setup code completion and clang bug highlighting?

**Comment by occivink** [comment]
I've had good success combining [kak-lsp](https://github.com/ul/kak-lsp) and [cquery](https://github.com/cquery-project/cquery) for C++, more so than with ctags / clang. The setup was pretty simple too.

**Comment by mawww** [comment]
Hello,

Basically what you need for basic C/C++ with clang.kak is to enable it in your kakrc with something like:

```
hook global WinSetOption filetype=(c|cpp) %{
    clang-enable-autocomplete 
    clang-enable-diagnostics
}
```

This will trigger clang completion on `.`, `->` and `::`. It will also make clang diagnostics visible. To manually run a clang based linting (that will give you error/warnings), run `clang-parse` (here I have `<c-p>` mapped to `:clang-parse<ret>`).

Finally, clang.kak uses the `clang_options` option to pass switches to the clang compiler.

All that said, as @occivink noted, kak-lsp and cquery provide a faster a much more advanced C/C++ environment.

**Comment by lougxing** [comment]
How to add include path ? @mawww

**Comment by krobelus** [comment]
you can set `clang_options`
