### ISSUE TITLE
Disable the assistant by default

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2064]
Hi,

It looks like most users that have talked about the assistant seem to disable it (the ASCII art itself, not the auto-info). I don't know if that's representative of most Kakoune users, but if that was the case, maybe the assistant should be disabled by default?

HTH.

**Comment by robertmeta** [comment]
Additionally, it is very wasteful of screen real estate.  Those working on small screens lose multiple lines of space when it is open.  Example: 
![mhlt38v](https://user-images.githubusercontent.com/91007/40317347-3477db60-5cef-11e8-9ae7-393fa39e158f.png)

So it isn't just clippy -- it is any of the assistants that grow the window with empty space are a problem.

**Comment by TeddyDD** [comment]
I keep it enabled all the time. It's like Ocelot in Metal Gear Solid V - old enemy now helping you :wink:

**Comment by robertmeta** [comment]
>  I've disabled it now, which might be a good thing: it gets users to edit the config and start customizing it to their liking.

This could be an argument for any amount of poor defaults couldn't it?

**Comment by mawww** [comment]
I think this is one subject on which I'll let my feelings take precedence, Clippy has been here for long, he is part of the Kakoune family, and is (relatively) easy to disable. I believe it to be the only instance of "fantasy" in the hard, efficient world of Kakoune.

See him as this slightly awkward, but still lovable family member you have conflicted feelings about 😆
