### ISSUE TITLE
Configurable delay for info prompt

### ISSUE THREAD

**Issue by robertmeta** [mawww/kakoune#2066]
The info prompt is profoundly useful, but when you know exactly what you are trying to do -- it can just be a bit of a flashing annoyance.  I tried to capture a good example using https://asciinema.org but the window was open for so little time it doesn't appear to have been recorded at all!

Basically, when I know I am going to hit like ]p for example -- and I do it quickly, would be great if the info prompt didn't try to display for $x milliseconds.  Possibly a configurable delay?

**Comment by Delapouite** [comment]
Spacemacs has this kind of delay for the main `space` menu which often triggers nested menus also respecting this value.

**Comment by robertmeta** [comment]
Additionally worth noting when over remote connection that obviously has a minor cost -- haven't had to deal with it on a high latency link yet.

**Comment by Delapouite** [comment]
Other issue about the "flashing info", but in macros: https://github.com/mawww/kakoune/issues/1491
