### ISSUE TITLE
<a-.> versus . 

### ISSUE THREAD

**Issue by robertmeta** [mawww/kakoune#2067]
This might just be a misunderstanding or a preference thing.  I think . and <a-.> should be swapped.  Is there some reason or consistency why they are setup the way they are?  It might just be my usage patterns, but I use <a-.> far more often then . and it feels like a bit more effort than it should be.

**Comment by robertmeta** [comment]
Sure, this is as much an issue about clarification and thinking as about the specific bindings.

**Comment by mawww** [comment]
I seldomly use `<a-.>` but use `.` very, very often. I am surprised to see it is the other way around for you. That said, I should probably force myself to use `<a-.>` more.

I am not sure if one is more important than the other, so I would be more in favor of the status quo, as I believe `.` behaviour to be closer to what vim `.` does than `<a-.>`. That is not a very strong opinion though, so feel free to challenge it.

**Comment by robertmeta** [comment]
I don't have a very strong opinion (except maybe I am not using . as often or as correctly as I should), so I will close this!
