### ISSUE TITLE
suggestion: add another key to clear selection

### ISSUE THREAD

**Issue by co-dh** [mawww/kakoune#2073]
First, just start kak this weekend, and really love it.
It's fast, simple.
 I'm already able to write a syntax color for q. 
And thank you for bring this great tool into the world.

Currently, only space can clear multiple selection ( except main). 
If the user map space to , (user mode), he will have trouble to quit multiple selection.
Can we add another key to exit multiple selection? like <c-c> or <ret>?
Thanks

**Comment by Screwtapello** [comment]
If you map `<space>` to `,`, you can map something else to `<space>` and it won't cause an infinite loop. Kakoune mappings always behave like Vim's "noremap" mappings, if you're familiar with those.

**Comment by mawww** [comment]
Key bindings are a very scarce resources in Kakoune, very few keys are left available so I dont think I will allow any feature to be bound to multiple keys at the same time. Remapping the key should fix your problem.
