### ISSUE TITLE
Disable showing words with s select

### ISSUE THREAD

**Issue by nuao** [mawww/kakoune#2081]
I've noticed that when pressing `s` for select a list of words in the buffer appears.
I think it's this commit here: 0b773ac26.

I'm not quite clear on what this is for, perhaps just get a sense of what's in the buffer before selecting a word.

In any case, can showing these words be disabled? The reason is that it takes up a lot of space, and I'd prefer just to see the buffer.

**Comment by Delapouite** [comment]
You can use `<c-o>` to disable autocompletion for this prompt.

**Comment by nuao** [comment]
Ok, thank you. Yes, this seems to work:

    map global normal s s<c-o>

I don't mind the idea of having extra information when performing select (though maybe at most one line), but I'm not sure an alphabetical word list on many lines is useful here.

**Comment by mawww** [comment]
the point of this word for regex search is that they can be selected using Kakoune's fuzzy matching, which provides a very nice way to search for a specific word in the buffer without having to type it fully.

**Comment by Screwtapello** [comment]
From playing with the JSON UI, I've learned that Kakoune understands a "window" size, and that the window is normally the size of the terminal, minus one row for the command/status line. It seems reasonable to me that when the command-completion menu is open and occupying the bottom *N* rows of the terminal, Kakoune should resize the display window to the size of the terminal, minus *N* rows for the menu, minus one row for the command/status line. That way, the thing you're searching for will never be obscured by the menu (but it still might be obscured by the info panel?).

**Comment by alexherbo2** [comment]
#2086
