### ISSUE TITLE
[RFC] Option Parsing overhaul

### ISSUE THREAD

**Issue by mawww** [mawww/kakoune#2087]
# Option Parsing Overhaul

In the continuation of #2046, I would like to refactor the way options are parsed to make them more well defined, consistent and easy to work with.

## The current state

Option parsing is pretty ad-hoc, lists are `:` separated, tuples and flags are `|` separated. Escaping behaviour is not clearly defined and is not consistent with the upcoming 'doubling-up' escaping behaviour of command line strings. Finally the current escaping makes it hard to work with lists from the shell because there is no nice way to iterate over a `:` separated list with escaping: We need to split on `:` preceeded by an even number of `\\` which is not something we can express cleanly without lookaround assertions.

## What we want

1. Easy to write option values interactively

2. Ability to write arbitray values with minimum complexity

3. Practical to work with from the shell (iterating over a list option, adding/removing a value to that list should be easy).

4. Consistency with the rest of Kakoune

## Possible directions

Using doubling-up escaping for list and tuple separators seemed like an obvious solution, but it fails at the following case: `elem1:::elem2`, there is an ambiguity: is that 'elem1:' and 'elem2', or 'elem1' and ':elem2' ?

Using backslash escaping works and would be close to what we already do, but is tricky to work with robustly in the shell, and has a bit of an "escaping-hell" problem with list of tuples, as lists need to escaped `\\` and tuples need it as well.

We could change lists syntax to use the newly well defined command syntax for element separation, this means making lists elements be defined by words. Setting a list option would hence follow the syntax `set-option <scope> <option-name> <element1> <element2>...`

This would satisfy constrains 1, 2 and 4. Regarding constraint 3 things get fuzzier. If we just were to use the same escaping to generate a string from the list, we would end up with a list of Kakoune escaped words, which would not translate nicely to the shell. A solution would be to have `$kak_opt_...` expand to a shell-specific syntax (for example, a shell-escaped list that would make `eval set -- $kak_opt_blah` correctly set positional parameters to each value).

This approach has multiple problems by itself, the use of shell specific syntax is a bit unfortunate, as it means `%sh{ python <<EOF ... }` now needs to shell-unescape the string. It would be fair game if that shell syntax was also the actual Kakoune syntax, but it seems established by #2046 that this is undesirable. Requiring non-shell languages to be able to apply a subset of shell escaping logic to correctly parse Kakoune's values might go a bit too far.

We could alternatively change lists to be newline separated, this would be the best format to work with in the shell (newline separation is the unix way to split entries). But it needs to come with a way to escape newline that still plays nice with the shell, and is not easy to use interactively (I do not think users wants to have to type `<c-v><ret>` between each elements of the `path` option when setting it manually. It could then make sense to use the elements-as-command-line-word approach from within Kakoune, but have `$kak_opt_...` expand as a newline separated list.

As this is a pretty hard problem to find a satisfying solution for, I'd be happy to get feedback or alternative ideas.

**Comment by mawww** [comment]
@danr @Delapouite @ul @lenormf @casimir @Screwtapello @Franciman @ekie @occivink @alexherbo2 

Opinions ?

**Comment by Screwtapello** [comment]
> ...`%sh{ python <<EOF ... }` now needs to shell-unescape the string.

That's not *such* a bad thing; Python has [shlex.split()](https://docs.python.org/3.6/library/shlex.html#shlex.split) and [shlex.quote()](https://docs.python.org/3.6/library/shlex.html#shlex.quote) for exactly this reason. I can imagine it being a problem for other languages, but at least shell syntax is not a custom Kakoune thing so there's probably a library for it already.

Basically, you want a list syntax that supports arbitrary content and works with traditional shell tools, but traditional shell tools don't really support arbitrary content (the best you'll get is something like `find -print0` and `xargs -0`) so I don't think there's a *really* good solution anywhere.

So, +1 from me for word-separated list items, using Kakoune quoting syntax in `evaluate-commands` contexts, and shell quoting syntax in shell-script contexts.

**Comment by occivink** [comment]
I think 1. is overrated and 2. and 3. are the most important points. I don't think I've ever set option lists by hand, they're always either implementation details or wrapped in easy-to-use commands.

Currently the biggest pain I have with lists is that they require convoluted shell code to iterate over  (and 10x more convoluted if they contain arbitrary contents). I'm not familiar with the `eval set -- ...` constructs but if that allows simple and robust shell iteration then I'm very much in favor.
I also don't think it's very important to make this easy for other languages than shell, as long as it's possible.

From inside kakoune I'm happy with using command syntax (I like the consistency). I suppose `%opt{some_list}` would expand as multiple arguments, but what would  `"prefix_%opt{some_list}suffix_"`  expand to?

**Comment by mawww** [comment]
@occivink `%opt{some_list}` should expand to multiple words, if inside double quotes, I am not sure what it should expand to, it should be a single word in the end, but the format to which it should expand is not clear to me (should we quotes each list elements ?).

`eval set -- $kak_opt_some_list` would set positional arguments to elements of `some_list`. As a more general thing, we could call arbitray shell functions with each list elements as a separate argument with `eval some_function $kak_opt_some_list`. This would make robust iteration with `shift` possible.

@ManDay forgot to add you, sorry.

**Comment by mawww** [comment]
I have been experimenting with that solution, and I think it works pretty nicely, see 718a749c04d977355c1b3ca8fcf0fc59f458d7f4 for an example of how scripts need to be refactored (the new version are cleaner IMHO). It is still not perfect, as we emit strings in Kakoune escape format, so `eval "set -- $kak_opt_my_list"` will loose the `'`s inside each elements (they are going to be written as `''`, which for the shell will just close and reopen the string).

That leads us to another question, following up on that: tuple syntax.

Currently tuples are written separated by `|`, and those `|` can be backslash escaped. Now that `:` is free, it might make more sense to migrate to it (AFAIR we only use tuples inside lists, so any scripts that uses them are already required to be refactored). Their might be a better syntax altogether...

@occivink @lenormf @danr @alexherbo2 As maintainers of various scripts, I'd be happy to get some feedback on that, it would be nice if you could start to convert one script to this (in a separate branch) to gather experience.

My plan is to stabilize the (newly renamed) `big-breaking-tidy-up` branch, have major scripts/utilities that are maintained outside of Kakoune to be converted to it (in their own separate branch), then after some time testing for motivated early adopters, switch master to it and make a new release.

@ul I plan to convert `kak-lsp` to that branch myself, as I work with it a lot, I'll submit a pull request that can be merged in a separate branch once this is stabilized.

I am starting to see the end of this big tidy up push, I think it was necessary to do all those breaking changes to the command language to make it cleaner and easier to work with, and in particular make it robust when used as an rpc mechanism from complex external scripts (Looking at you `kak-lsp`).

**Comment by doppioandante** [comment]
I'll also ping @Franciman as I recall him writing a pretty hefty piece of kak script to interact with LSP too.

**Comment by casimir** [comment]
This syntax is more or less the same as [fish's list](https://fishshell.com/docs/current/tutorial.html#tut_lists). For what it's worth this is the first feature that convinced me to experiment with this shell.
This syntax makes lists easy to manipulate and print/read. In fish it's paired with some builtins but it's easy to work with POSIX syntax nonetheless, I'm thinking about `for` loops.

About the tuple syntax, I don't see why `:` would be better than `|` so I would keep the former.

**Comment by occivink** [comment]
>we emit strings in Kakoune escape format, so eval "set -- $kak_opt_my_list" will loose the 's inside each elements

Any chance to reconsider that, and emit shell-safe escapes? There are not many languages that are suitable for kakoune's extension model (i.e. spawn processes frequently) and I would prefer if the de facto extension language was easier to write. I think it's important to be able to iterate over `kak_selections` safely without having to care about its content.

>Currently tuples are written separated by |, and those | can be backslash escaped

What about literal backslashes, must they be escaped too? If not, the "can't-have-backslash-at-end-of-string" problem is still there, right?

I'll migrate my scripts in a branch and report back, but I don't expect much trouble.
