### ISSUE TITLE
Should line-specs type be a map instead of a list?

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#2089]
Hi

The current format of the `line-specs` type is a list of tuples prefixed by a timestamp. Ex:

`stamp:1|foo:2|bar`… where `1` is a line number and `foo` the flag text.

The thing is in this scenario:

`stamp:1|foo:1|qux`, `foo` and `qux` both competes for the line `1` but only `foo` will be displayed. In other word, the first tuple win.

My use case is in `link.kak` where a line may contain several errors. So my initial idea was to display a counter instead of the colored `█` block, like so:

`stamp:42|1:42|2`. In this case I was expecting the flag on line `42` to display `2` but it displays `1`, which is the first tuple.

The `-add` switch of the `set-option` command appends a new tuple to the list which does not really have an impact.

Would there be any disadvantage to turn line-specs into a map? Something like:

`stamp:1=foo:2=bar`

This way by using `set-option -add` it will replace the key-value pair on a given line.

**Comment by mawww** [comment]
That could make sense, I need to check the various uses of line-specs to verify they would be well served with a map.

**Comment by mawww** [comment]
I took a look at that, and in the end using a list is better for implementation reasons. The thing is we sort that list and always treat it as a sorted list afterwards, which makes updating the list on buffer change more efficient. Moving to a map would loose this property, or would require some additional logic to make it look like a map to the option while keeping a sorted list for the implementation.

I dont think it is worth it.
