### ISSUE TITLE
feature request: -attributes

### ISSUE THREAD

**Issue by co-dh** [mawww/kakoune#2095]
One of the most annoying thing for me in the text console is the cursor cannot change shape.
I lost track of which state is it now a lot.
One solution is to add underline to PrimaryCursor face in insert mode.
However, there is no way to remove that attribute when switch to normal mode, 
nor it's possible to get current PrimaryCursor value.
It would be nice to add [-<attributes>], so set-face window PrimaryCursor -u  will remove under that added.

**Comment by maximbaz** [comment]
I think we should just have a proper implementation of different cursor shapes and not come up with hacks like juggling faces in runtime (#2194), but I agree having different cursor shapes is super convenient.

**Comment by co-dh** [comment]
ncursor has no api to change cursor shape. In fact, application cannot change terminal cursor, it's usually controlled by the terminal emulator like xterm and putty.

**Comment by maximbaz** [comment]
This might change, see https://github.com/kovidgoyal/kitty/issues/720

**Comment by kovidgoyal** [comment]
There are standard escape codes to change cursor shapes. ncurses might not support them, but they exist and are widely implemented in most terminal emulators. Documented here http://invisible-island.net/xterm/ctlseqs/ctlseqs.html  (search for cursor style)

**Comment by co-dh** [comment]
I end up with make white space and line return visible in insert mode, and make tmux border more obvious. (active border background color)
