### ISSUE TITLE
Rotate main selection without leaving prompt

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#2096]
Hi

vim 8 introduced two new useful key-mappings that could also benefit Kakoune. Currently (I may be wrong) there seems to be no easy way to mimic this feature.

`<c-g>` and `<c-t>` in command mode: https://neovim.io/doc/user/cmdline.html#c_CTRL-G

The use case in Kakoune, is when you're crafting selections by using `%s` and typing in the prompt, the main selection is always the last one. But sometimes you need to see what's going on with the other selections off screen. Rotation with `(` and `)` only work in normal mode.

What about having `<a-(>` and `<a-)>` in prompt mode to rotate the main selection without leaving this mode?

**Comment by occivink** [comment]
Maybe insert mode's `<a-;>` should also exist for prompt mode, so that one could easily remap that.

**Comment by Delapouite** [comment]
About `<a-;>` see https://github.com/mawww/kakoune/issues/2060

**Comment by occivink** [comment]
This doesn't seem to work for regex-prompts, the selections are restored after a short delay, I suspect that incsearch is involved somehow.

**Comment by lenormf** [comment]
@occivink can you still reproduce this?

**Comment by occivink** [comment]
Yes, it's as easy as doing `/<a-;>(` with multiple selections

**Comment by lenormf** [comment]
We should probably open a new issue for that bug, if that wasn't done already.
