### ISSUE TITLE
Errors in test

### ISSUE THREAD

**Issue by Prazola** [mawww/kakoune#2105]
I get this running the test suite after compile, also "clippy" is showed with wrong symbols.

```      unicode
--- /MAKEDIR/kakoune-git/src/kakoune-git/test/./compose/unicode/out     2018-06-04 14:50:50.364513499 +0200
+++ out 2018-06-04 15:20:06.789405349 +0200
@@ -1 +1 @@
-MAÏS MÉLANGE BIENTÔT
+MAïS MéLANGE BIENTôT
```
I'm running archlinux and kak compiles fine on my server with the same distro, can someone help me to figure out this issue?
Ty in advance.

**Comment by Screwtapello** [comment]
What does the `locale` command print when you run it in a terminal?

**Comment by Prazola** [comment]
Holy moly i had it_IT locale written as it_lT, I'm so bad :(
Ty screwtapello, case closed :D
