### ISSUE TITLE
Bold/Italic sections in markdown are not highlighted properly

### ISSUE THREAD

**Issue by ybden** [mawww/kakoune#2111]
### Steps 

1. `kak foo.md`
2. Insert the following:

```markdown
**test** **test** **test** **test** **test** **test* **test** **test** **test** **test** **test**

**test** **test** **test** **test** **test** **test* **test** **test** **test** **test** **test**

**test** **test** **test** **test** **test** **test* **test** **test** **test** **test** **test**
```

### Outcome 

The words are highlighted inconsistently. The same thing occurs with highlighting this with underscores used instead, or italics (single asterisks/underscores).

### Expected 

Each of these should have been highlighted.

**Comment by ricochet1k** [comment]
Here's what I see when I follow the instructions above: 
![kak-md](https://user-images.githubusercontent.com/76901/41042917-d6404e90-6970-11e8-90b6-e7182fa600cd.png)

**Comment by ybden** [comment]
Every line except the first appears to be highlighted on/off/on/off/etc. The first line is especially weird, and only occurs if on the very first line of the file.

**Comment by henrebotha** [comment]
Potentially related: the italics highlighting is broken. https://github.com/mawww/kakoune/blob/master/rc/base/markdown.kak#L45 Specifically, when an inline code snippet (in backticks) contains an underscore or asterisk, that underscore or asterisk is treated as forming part of an italics/bold markup. Write something like this to see:

    Hello `hi_there` this shouldn't be italics `but_it is`
