### ISSUE TITLE
Python hooks indent when they shouldn't

### ISSUE THREAD

**Issue by ybden** [mawww/kakoune#2112]
### Steps 

1. `kak foo.py`
2. insert the following:

```python
class Foo:
    pass
```

3. place the cursor at the beginning of the first line, go into insert mode, hit enter a few times

### Outcome 

The second line rapidly disappears off to the right side of the screen

### Expected 

This, uh, not happening? :p

**Comment by notramo** [comment]
There is a `x` key in the last `try` statement of the `python-indent-on-new-line` command in `python.kak`. It should be replaced by `<a-x>`.

**Comment by kevindirect** [comment]
I'm having a problem with python indentation after colons. So far I've only had this happen in python files.
I'm not doing anything special with tabs in my kakrc except a couple standard hooks for tab completion, removing them doesn't change the behavior. Removing my python filetype hooks doesn't change anything either.

**Steps**
This happens in insert mode when I press `enter` from a line ending in colon or I add lines underneath from normal mode (using `o`).

**Outcome**
The new indented line has four spaces prepended to it even though I'm using tabs in the file, like so:
(`.` is a space, `>-------` is a tab)
```
>------->-------if foo:
....>--->-------# indent ends here
```
**Expected**
```
>------->-------if foo:
>------->-------# indent ends here
```
or
```
>------->-------if foo:
>------->------->-------# indent ends here, even better
```

**Comment by Screwtapello** [comment]
Kakoune has two relevant settings you might want to check: `tabstop` sets the width of each tab character (inserted with the `<tab>` key), and `indentwidth` sets the number of spaces inserted or removed by the `>` and `<` commands.

If you're the kind of person who hates tabs for indentation and only wants to use spaces, you'll probably want to map `<tab>` to something else, and control the amount of indenting by setting `indentwidth`.

If you're the kind of person who hates spaces for indentation and only wants to use tabs, you'll probably want to set `indentwidth` to 0 (which means "indent with a tab, not spaces") and control the amount of indenting by setting `tabstop`.

**Comment by lenormf** [comment]
C.f. #2168

**Comment by kevindirect** [comment]
@Screwtapello 

Works perfectly, thanks!

Mind if I quote your answer on the wiki page on Indentation and Tabulation? Might save people time in the future

**Comment by Screwtapello** [comment]
Go ahead!
