### ISSUE TITLE
When editing OCaml code, pressing Enter in the insert mode deletes text in front of the cursor

### ISSUE THREAD

**Issue by a-nikolaev** [mawww/kakoune#2115]
Editing OCaml code does not seem working correctly: pressing Enter in the insert mode deletes text before the cursor.
### Steps 
1 Start editing an OCaml file (or start a new file with ml extension: `$ kak prog.ml`)
2 In the insert mode, press Enter to go to the next line

### Outcome 
After pressing Enter, all text before the cursor gets deleted

### Expected 
The cursor should move to the next line (and indent appropriately)

#### Comments
I just started learning the editor, so not sure whether this is an issue on my side or an error in the editor. Editing code in other languages (I tried C and Lua) works fine and as expected. I observe the bug in both, my distribution version of the editor, and after building it from sources. The "/rc/base/ocaml.kak" file that's installed in my system is identical to the one in the Github repo. Thank you.

**Comment by notramo** [comment]
Autoindentation is done by piping buffer content through the `ocp-indent` external command. Is this tool installed? If a selection is piped to a nonexistent external program, then the selection content is replaced by an empty string.

**Comment by a-nikolaev** [comment]
I see, yes, I don't have ocp-indent installed, there was no error message or anything. Thanks.

**Comment by lenormf** [comment]
#1726
