### ISSUE TITLE
Deleting buffer content causes assertion failure

### ISSUE THREAD

**Issue by alyssais** [mawww/kakoune#2119]
### Steps

1. Get a buffer with text. I think it possibly has to be larger than the height of the window.
2. Type `%d`

### Outcome

Kakoune crashes

This was introduced in 0d3a1b59.

### Expected

Kakoune does not crash

**Comment by mawww** [comment]
This should be fixed by ee19497d3787e1ec2f144dd33ea628d42af0f255.
