### ISSUE TITLE
Manual completion instead of automatic in insert mode

### ISSUE THREAD

**Issue by cglogic** [mawww/kakoune#2121]
How to disable automatic completions and trigger them manually by keybinding?

**Comment by Delapouite** [comment]
Hello.

Use `<c-o>` and then `<c-x>`

More info in this doc page: https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#insert-mode-completion

**Comment by cglogic** [comment]
If I use `<c-o>` and then `<c-x>` completion not updated automatically when I typing next char. I think solution is keybindings to enable and disable automatic completion. So if `<c-o>` disable automatic completion then how enable it again?

**Comment by mawww** [comment]
Yeah, I guess it would make sense to have another binding that would do the contrary of `<c-o>` (`<c-i>` comes to mind, as during normal mode `<c-o>` and `<c-i>` are opposite actions, although totally unrelated to completion), then you could hook on InsertCompletionShow/InsertCompletionHide to enable/disable auto-completion.

**Comment by Delapouite** [comment]
This issue can be closed now that the corresponding PR is merged.

**Comment by cglogic** [comment]
Thank you!
