### ISSUE TITLE
[Feature] menu command select by typing

### ISSUE THREAD

**Issue by JJK96** [mawww/kakoune#2124]
In the menu command it is currently (as far as I know) only possible to select an entry by repeatedly pressing tab. 

My suggestion would be to enable "as you type" matching. 

This could be done fuzzy or prefix.

**Comment by TeddyDD** [comment]
as reference, @mawww's response from IRC
```
mawww_imc (IRC)
06:17
:menu is *old*
it actually supports some filtering by regex, hit '/' while in menu mode, and you can enter a regex to filter matches
I have been tempted to get rid of :menu, nothing really uses it in the core code, and AFAIK only ctags.kak uses it in scripts
```

**Comment by JJK96** [comment]
spell.kak also uses it. What would be the alternative for selecting an item from a list? Dmenu?

**Comment by TeddyDD** [comment]
`:prompt -command-completion` might do the trick I guess

**Comment by JJK96** [comment]
That doesn't cut it. I need a mapping from a word to a series of keys that will be executed.

**Comment by JJK96** [comment]
For now using / to search in a menu solves this issue
