### ISSUE TITLE
/tmp directory littered with files

### ISSUE THREAD

**Issue by JJK96** [mawww/kakoune#2137]
after working for a while, the /tmp directory contains a lot of tmp.xxxxx files with contents of text files opened by kakoune.

I assume that this is some kind of swapfile system.

I think it would be better to move those files to a /tmp/kak folder, so that /tmp can stay relatively clean.

**Comment by lenormf** [comment]
I don't think those are created by the editor, as the prefix for temporary files is alway `kak-`.

**Comment by occivink** [comment]
Yes, I'm inclined to think these are generated by a badly-behaved script, look for calls to `mktemp`

**Comment by JJK96** [comment]
After some more looking around, it seems to be kak-lsp.
