### ISSUE TITLE
Make `!` re-evaluate its shell context for each selection

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2138]
### Steps 

In a buffer that has several lines:

* <kbd>%</kbd><kbd>a-s</kbd><kbd>H</kbd>
* <kbd>!</kbd>`echo "$kak_selection"`<kbd>ret</kbd>

### Outcome 

The contents of the main selection is inserted before every selection.

### Expected 

The primitive behaves as expected, but it'd be nice to have it re-evaluate the command within the context of the current selection, rather than run once and paste the same output everywhere.

That way the reproducer above would duplicate every line in the buffer (by expanding `$kak_selection` with the contents of the current selection), as opposed to prepend the main selection to all of them.

### Usecase

A list of paths in a buffer, and use `%<a-s>H <a-!>git diff --stat HEAD~1 HEAD -- "${kak_selection}"` to insert statistics after every path.

I did it using `exec -itersel %{<a-!>…}`, but the operation could be made less cumbersome, assuming that we would want that primitive to be behave that way more often than the current behavior.

**Comment by eraserhd** [comment]
I just hit this when, with 91 selections, I did `!uuidgen |tr -d '\n'`.  I approve.
