### ISSUE TITLE
improving syntax highlighting quality

### ISSUE THREAD

**Issue by matthewvilim** [mawww/kakoune#2141]
I'm looking at switching to Kakoune, but one annoyance is the relatively poor quality of syntax coloring compared to my config in Vim.

![colors](https://user-images.githubusercontent.com/3943274/41745356-886b1776-755b-11e8-9c09-c775c5adab9a.png)

For example, types and variables are not being detected in Scala (the same holds for other languages); although, FWIW Vim also does a poor job with its built-in highlighters.

Kakoune's color schemes do support all the neccesary features (i.e. face global type, face global variable, etc.), but the language parsers don't seem to take advantage of all of them. Do you have any interest in accepting a pull request for this?

**Comment by mawww** [comment]
I am always happy to get more precise syntax highlighting, so do not hesitate to improve scala.kak so that it highlights types/variables/functions correctly.

**Comment by matthewvilim** [comment]
Cool, thanks.

**Comment by ervasive** [comment]
Some kind of a syntax theme converter would be super handy I think.

I'm looking into highlighting mechanisms in `kakoune` right now and try to figure out if it's possible and not too cumbersome to map syntax related concepts of TextMate themes, which are used by `vscode` and `sublime` and have plenty of high-quality syntax themes already. Another option would be the translation of vim syntax themes.
I think it would be a good design choice to manage syntax related code outside the core in a plugin like `vim-polyglot` and handle never-ending languages changes in the more independent and flexible way and if a tool is able to automate syntax conversion from other sources it can be quick and easy.

**Comment by JakeHL** [comment]
sorry to revive such a dead issue, but did anyone ever get anywhere with converting textmate grammars? I've been working on such a project lately but if someone has already done the work then I'd be more inclined to use that.

I really enjoy kakoune but I'm a very visual person and rely on detailed syntax highlighting. I used helix as my daily driver for that reason. It has tree sitter built in.

**Comment by sidkshatriya** [comment]
In 2022, I think syntax highlighting by kakoune is not so important anymore. Let me explain:

If you use kak-lsp in kakoune, many language servers will now do syntax highlighting themselves via the semantic tokens feature in the LSP protocol. So basically your language server will provide the highlighting based on the AST structure of the language rather than brittle regexes by kakoune.

kak-lsp supports semantic tokens. Make sure you enable it if your LSP supports it e.g. rust analyzer and others.

**Comment by JakeHL** [comment]
Thanks for coming back to me. I do use kak-lsp with syntax highlighting, I even modified the toml file and themes that I use to add all the extra tokens that aren't there by default but I find that is still not quite as robust as other options.

I do understand why for most people this isn't as much of a pressing issue, however. I think I'll carry on my work with converting textmate grammars. Hopefully I can make it work.

**Comment by sidkshatriya** [comment]
If you find syntax highlighting via semantic tokens not very robust in kak-lsp at times, do report the specific issue. I have generally noticed that the maintainer of kak-lsp is very prompt in fixing issues.

**Comment by JakeHL** [comment]
I have seen they are pretty responsive too. Unfortunately, the problems I have run into are more when the language server itself hasn't implemented a specific token or where it's not even part of the LSP spec.

Here's a side-by-side of helix (left) and kak (right). The main things that are different are operators and punctuation (such as the braces etc). On kak they default to the base text color, whereas in helix they have their own color.

![image](https://user-images.githubusercontent.com/9119973/176892196-bf3e819d-6fe3-4ea7-80d7-c1ee6f0265cd.png)

Both of these themes are using the Catppuccin colors and I've hand picked the colors to best match the same tokens in each editor where possible. so ideally they'd look the same but they don't.

While this may be easy to solve on a language by language basis by adding more regex rules I think if we could convert existing textmate grammars it would become much less of a headache. I'm writing a tool to parse and convert them so I don't think it would be a far stretch to release that as a plugin for kakoune. I tend to get burned out quite quickly though so we'll see how far I get lol.

**Comment by krobelus** [comment]
There's also https://github.com/ul/kak-tree/issues/8

**Comment by JakeHL** [comment]
I have seen that, but unfortunately I think it looks like abandonware.

**Comment by sidkshatriya** [comment]
> I have seen that, but unfortunately I think it looks like abandonware.

The toughest part of building and executing the tree-sitter idea for kakoune has been accomplished by `kak-tree`.

Even though the project has not received updates in a long time, I would suggested that reviving that project may actually be not that tough. Building something from scratch is many times harder. `kak-tree` might be a great base to build upon so that kakoune can deliver fine grained syntax highlighting that you desire.

**Comment by sidkshatriya** [comment]
(and I don't think kakoune regexes can give you the control that tree-sitter based kak-tree will able to give you). Helix also uses tree-sitter pervasively as you might already know.

**Comment by JakeHL** [comment]
Yeah you're not wrong. I was aware that helix used it, but I wasn't aware quite how far along kak-tree had gotten. I thought it might be a little out of my remit rather than just pulling regexes out of textmate grammars but I'll explore kak-tree for a little while.

Thanks for the discussion!

**Comment by sidkshatriya** [comment]
Not to extend the discussion -- just wanted to clarify that `kak-tree` actually _does still work_ with kakoune on master branch. 

I just checked. You may need to temporarily do `:lsp-auto-hover-disable` if you issue commands like `:tree-node-sexp` though.

**Comment by phaazon** [comment]
> I have seen that, but unfortunately I think it looks like abandonware.

I’ve been making phaazon/kak-tree-sitter for this exact reason. :slightly_smiling_face:
