### ISSUE TITLE
Need to edit/add info to README.asciidoc for Ubuntu 18.04

### ISSUE THREAD

**Issue by dixonge** [mawww/kakoune#2142]
### Steps 

Follow instructions for Ubuntu 16 in README

### Outcome 

Error in final make install

### Expected 

No error

-------------------------------------------------

Was prompted to add 'env' in front of the final command. This successfully completed the command. In the README, for Ubuntu 18.04 (not sure about prior versions) the final step should read as follows:

```
env PREFIX=$HOME/.local make install
```

**Comment by Screwtapello** [comment]
What error did you get, specifically?

**Comment by dixonge** [comment]
don't recall the specifics, just was told to use 'env' up front...

**Comment by lenormf** [comment]
There's no reason you should set `$PREFIX` unless you have a reason to in the first place, these instructions have been wrong for a while now.

Post the output of `make install`, after making sure you got `g++` >= 5 or `clang++` >= 3.9 installed.

**Comment by dixonge** [comment]
well that seems to work just fine - no errors. Thanks!

**Comment by lenormf** [comment]
Glad it worked, could you close the issue if you have no further questions please?

**Comment by dixonge** [comment]
Gladly. Actually looked everywhere for how to do that yesterday. Just now see the large, obvious 'Close and comment' button... LOL
