### ISSUE TITLE
kak starts noticeably slower than neovim

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2152]
Install `kakoune` on Arch Linux from the official repo.

Run `kak -n` — kakoune starts instantly (perfect).
Run `kak` — kakoune starts noticeably slowly, even though I didn't even create `~/.config/kak/` folder yet.
I use `neovim` with lots of plugins and huge config file, and it starts faster than `kak`.

Given that I open and close editor many times during the day, it is essential to have the editor start as fast as possible.

I'm not sure how I can provide more information to narrow down the cause of slowness. What does `kak` do, that `kak -n` doesn't?

**Comment by TeddyDD** [comment]
You could try to measuer startup time like this:
```
time -p kak -e 'quit'
real 0.48
user 0.21
sys 0.31
```
It takes about half a second to lanuch in my case, and I have shitload of plugins. I wonder how long it takes in your case.

**Comment by SolitudeSF** [comment]
manually sourcing each file from kakrc is faster than load same files from autoload.
autoloading all default `kak` files takes `~115ms` while when putting them in autoload takes `~170ms`.
why is that?

**Comment by maximbaz** [comment]
I did some additional benchmarking:

---------------

nvim with no config: `25ms`

```
❯ time (repeat 100 nvim -u NONE -c 'quit')
1.33s user 0.87s system 88% cpu 2.490 total
```

nvim with huge config and lots of plugins: `114ms`

```
❯ time (repeat 100 nvim -c 'quit')
9.20s user 1.61s system 94% cpu 11.390 total
```

`kak -n`: `7ms` (awesome result!)

```
❯ time (repeat 100 kak -n -e 'quit')
0.35s user 0.35s system 99% cpu 0.703 total
```

`kak` with no custom config (except whatever ArchLinux package ships): `400ms`

```
❯ time (repeat 100 kak -e 'quit')
31.48s user 12.14s system 108% cpu 40.057 total
```

-------------

So before I even start configuring `kak`, it already takes almost 4 times longer to load than my fully customized `nvim` — let's try to get this number down 😉 

`:echo %val{runtime}/autoload<ret>` outputs: `/usr/share/kak /autoload`

I don't have the folder `/autoload`, but I do have the folder `/usr/share/kak` present.

Creating a folder `~/.config/kak/autoload` does make `kak` load much faster, as if I provided the `-n` argument. However, I do want to have all those files loaded 🙂 

------------------

Neovim is probably fast because it can load configs based on a file type, can we have the same in kakoune? For example, I probably don't really need the file `rc/base/haskell.kak` loaded until I actually open a haskell file.

-----------

Merging the files together as @TeddyDD suggested does provide a huge benefit, I get the startup time decreased from `400ms` down to `176ms` (although `nvim` is still faster even with all custom configs and plugins, again probably because it doesn't have to load _everything_ on startup).

```
❯ time (repeat 100 kak -n -e 'source /usr/share/kak/rc/mega.kak;quit')
( repeat 100; do; kak -n -e 'source /usr/share/kak/rc/mega.kak;quit'; done; )  14.99s user 4.76s system 112% cpu 17.583 total
```

**Comment by TeddyDD** [comment]
Well, Kakoune doesn't have to load everything as well. I can imagine we could put source  commands into hooks so Kakoune would load language support only when file with specific extension is opened:
```
hook global BufCreate .*\.go$ %{
    source /usr/share/kak/go.kak
    source /usr/share/kak/go-tools.kak
}
```
Of course this hook won't work in Kakoune in current form.
This solution would require quite a lot changes in scripts. First - we need a way to check if file was already sourced, second - language initialization should be handled after sourcing (usually language script does it in BufCreate hook, but in this case buffer already exists).

I don't think it's hard but it's a lot of work.

**Comment by SolitudeSF** [comment]
merging everything into one file and sourcing it on *every* start is faster than normal autoloading.

**Comment by TeddyDD** [comment]
I think the reason why merging is faster is just less file seeks (107 file reads vs 1) but I might be wrong.

**Comment by SolitudeSF** [comment]
im talking about performing merge on every startup

**Comment by TeddyDD** [comment]
Oh, I see. You right, megre operation is blazing fast while autoloading is way slower. Interesting

**Comment by boj** [comment]
Semi-related, I was experimenting with different terminals today and noticed that kak loads quickly with `urxvt`, but has a noticeable loading time in `termite`. Any particular reason for that?

**Comment by mawww** [comment]
Kakoune can help measuring what takes time by adding a `set global debug profile` command on top of the `share/kak/kakrc` file (not the user config one, the bundled one). This will output various timings in the debug buffer.

I agree this is a performance bug, Kakoune should be able to start faster than that, and I dont see a really good reason for a massive performance difference between loading lots of small files from loading a single big file, except if we are already IO bound, which I doubt.

**Comment by co-dh** [comment]
You can use dash instead of bash as /bin/sh, 
https://wiki.archlinux.org/index.php/Dash.


Also, I think kakoune need a lazy loading mechanism.  There is no point to load go.kak while I'm not working in go at all. 
Maybe something as simple as fish's functions/ folder, where a function named a reside in functions/a.fish, and get loaded on the first time.

**Comment by mawww** [comment]
With latest code, you should be able to profile startup by running 

```
kak -debug 'profile|shell' -e 'b *debug*; w debug; q'
```

This will write the content of the debug buffer post startup filled with timing information and what shell scripts are executed.

**Comment by lenormf** [comment]
I would add the `-n` flag to the above command, as some of us (erm) have a rather substantial amount of scripts that are loaded at started, which could falsify results reported here.

**Comment by mawww** [comment]
The whole point of this is to profile script loading, starting with -n needs to be profiled differently (I use perf here)

**Comment by mawww** [comment]
We dont have the same performance either, on my laptop Kakoune loads in less than 200ms almost always, on a more beefy desktop it was taking up to 400ms (probably due to bash), hopefully we can pinpoint potential improvements to the startup time. I suspect setting /bin/sh to symlink dash is a pretty good start.

**Comment by mawww** [comment]
> sourcing '/usr/share/kak/kakrc' took 171574 us (this alone is already slower than entire nvim loading)

This is the whole loading, all the other sourcing of scripts is nested inside this one.

What shell is at /bin/sh on your system ? What difference do you get if you make it point to a lightweight shell (dash) ?

**Comment by maximbaz** [comment]
> This is the whole loading, all the other sourcing of scripts is nested inside this one.

Ah, I see, so in reality `c-lang.kak` is the slowest script.

> What shell is at /bin/sh on your system ? What difference do you get if you make it point to a lightweight shell (dash) ?

It was bash, and dash is giving me a very good perf improvement, thanks for the idea @co-dh!

------------

Time for some perf runs! The results are averaged for 100 executions of `kak -e 'quit'`.

1. `sh -> bash`: `242ms`
2. `sh -> bash`, removed `c-family.kak`: `179ms`
3. `sh -> dash`: `98ms`
4. `sh -> dash`, removed `c-family.kak`: `88ms` !!!

Woohoo, we are finally beating neovim! 

----------

Can we still consider lazy-loading language-specific configs? Still not sure if this could be as simple as wrapping all top-level `evaluate-command` calls into a `WinSetOption filetype` hook, or there's more to it.

**Comment by mawww** [comment]
For a final boost, you can try to replace the `sed` you added to autoload_directory with just `xargs cat`. There might be some slight performance improvements in the latest commits (a5f53dccb7cab0bf4d5292dbad5e624690bb4a3b)

**Comment by maximbaz** [comment]
Just tried your idea, there's no visible improvement between the two. The commit a5f53dc has some tiny improvement, around 3ms, but at least it seems to be consistent and not a statistical fluke.

Having `c-family.kak` lazy loaded would provide much better value 😛 

Having dash is cool, but not everyone can afford changing their shell, and I'm dreading the time when dash 0.5.10 gets released for Arch Linux and stops being compatible with kakoune (https://github.com/mawww/kakoune/issues/2242)

**Comment by SolitudeSF** [comment]
i dont think anyone needs bash for their login shell. you can use dash for that and whatever shell for interactive use.

**Comment by occivink** [comment]
Also note that the login shell is independent from /bin/sh, you could set bash directly if you wanted to.

The biggest breakage you might experience with symlinking /bin/sh to dash is with scripts which use bashisms unknowingly, but even that's an easy fix.

**Comment by maximbaz** [comment]
In theory - yes, in practice there could be problems. Arch Linux for example comes with bash as /bin/sh, until recently it was not recommended to change /bin/sh as it was breaking a bunch of system scripts (or at least I was told this story). 

Regardless, all I'm saying is that dash does provide perf improvement and it's great to have it, but kakoune shouldn't be enforcing people to change to dash. Even with bash it should be starting at least as fast as neovim. And right now it isn't the case yet, and the lack of lazy loading is the main causing factor in this issue.

**Comment by maximbaz** [comment]
I'm not sure why everyone is so carefully avoiding the topic of lazy-loading, it gives the great perf boost and is a very simple thing to do.

I made an example for `c-family.kak`: https://github.com/mawww/kakoune/pull/2255/files?w=1

Do you see any issues with this approach?

**Comment by mawww** [comment]
In my view, lazy loading is the last resort, I'd much rather ensure that we are quick to load even without.

That said, I have a plan on how lazy loading would work, which is related to the "modules" system that would solve the dependency between script problem.

The idea for the "modules" system is to introduce 2 new commands:

`provides` or `module` or similar, that takes a single parameter which is an arbitrary string identifying a module, I expect most bundled `.kak` files to start with that. That command will stop sourcing the current file if its parameter has already be given to a preceeding `provides` command.

```
# File c-family.kak
provides c-family
# following commands will only be executed once, even if this file is sourced many times
```

`requires` or similar, which takes a name as a parameter, and loads a file matching that name from the script path (script path being a list of directories in which we might have scripts, like /usr/share/kak/rc and ~/.config/kak/rc).

```
# File blah.kak
requires c-family.kak # sources /usr/share/kak/rc/c-family.kak, which will stop at the provides line if it was already loaded
# Now we know commands provided by c-family.kak are available
```

The link with lazy loading is that we can have

```
hook global BufSetOption filetype=(.*) %{ requires "%val{hook_param_capture_1}.kak" }
```

There are still problems to solve (for example, sourcing python.kak would add hooks that want to run on BufSetOption filetype=python, and those would not run currently on the file that triggers the loading of python.kak), but thats the general direction I had in mind.

Comments ?

**Comment by co-dh** [comment]
I would like to have a dictionary of loaded modules saved some where, so requires c-family.kak will check if c-family.kak already loaded, and do not need to read c-family.kak.
same as python's import.
In this case, you actually don't need the provides.

**Comment by maximbaz** [comment]
I think you are over-complicating this @mawww, my tiny PR just adds 6 lines and it _already works_, all hooks are running, there no issues to solve as I can see, and I experience the full speed-up as expected.

<details>
<summary> Achieving lazy-loading in 5 lines of code </summary>

![image](https://user-images.githubusercontent.com/1177900/43247378-d73cae86-90b4-11e8-8429-23d625de31be.png)

</details>

---------

Is there a real example when one module depends on another module? If yes, tell me the name and I'll try my proposed approach on that module. If no, let's not spend time solving a non-existing problem.

**Comment by occivink** [comment]
The benefit of modules is also to be able to share code between various scripts. Right now a lot of language scripts have copy-pasted logic to handle auto-indentation and auto-insertion of delimiters, it's rather fragile and I'm pretty sure some obscure language scripts are just outdated.

**Comment by maximbaz** [comment]
Gotcha, thanks for explaining this bit. But I don't want to mix refactoring scripts into modules with what I'm proposing here, modularization is a much bigger change with different goals.

Let me perhaps ask a different question: do you see any issues with this change? Would you merge it? It is 6 new lines that don't break anything and improve loading time by `60ms` on bash and `10ms` on dash.

https://github.com/mawww/kakoune/pull/2255/files?w=1

**Comment by mawww** [comment]
I am not really keen on merging this change, It does improve startup time, which is good, but I dont see any reason to give c-family a special treatment, and I am not really convinced we want to have this pattern appear in all language support files.

Regarding the `provides` command, the reason behind it (rather than just making require use a set of already required modules) was to play well with autoload/sourcing, so that a file would not get sourced multiple times (once because it was in autoload, and a second time when its "required" for the first time).

**Comment by maximbaz** [comment]
> but I dont see any reason to give c-family a special treatment, and I am not really convinced we want to have this pattern appear in all language support files.

That would have been my second proposal, I can do this same change for all other files. Why do you not like this pattern, do you see some issue with it?

**Comment by mawww** [comment]
Not with the pattern itself, but with repeating the same thing in each of the 92 .kak files we have. This is why I suggested a "modules" solution, as it allows to move files out of autoload, and have a single hook that tries to autoload those files based on filetype.

Another (minor) concern is that by wrapping all that in a command, we keep the full text content of the command in memory, for something we ultimately want to run only once. It is solvable by adding a way to undefine a command, and do that as well after removing the hook, but its not exactly elegant.

**Comment by maximbaz** [comment]
I see, and just to be clear, I don't disagree with the modular approach, especially because it brings other benefits as @occivink has mentioned — I would love to see the "modules" solution! But it is a complicated change that you leave as the last resort and don't plan to do right now, while what I'm proposing is a simple thing for which I can make a PR today and close this ticket for good. 

I think we can iteratively improve in this case, once we get to implement modular approach, deleting 6 lines per file is not the most difficult cleanup to do — and on a positive side, we will be able to measure the perf impact of "modules" solution, our goal would be not to decrease the performance comparing to "lazy loading" in its currently proposed form.

**Comment by maximbaz** [comment]
I'll close the "showcase" PR, if you agree that we should implement this pattern in all files (at least until you get time to work on modular approach), let me know and I will gladly prepare a PR for all files.

**Comment by maximbaz** [comment]
@mawww given that now we have `hook -once`, how do you feel about having the following pattern in all rc files? I can still make a PR if you have no objections to merge this 🙂 

```patch
diff --git a/rc/core/c-family.kak b/rc/core/c-family.kak
index def12daa..01f65a6b 100644
--- a/rc/core/c-family.kak
+++ b/rc/core/c-family.kak
@@ -126,6 +126,8 @@ define-command -hidden c-family-insert-on-newline %[ evaluate-commands -itersel
     ]
 ] ]
 
+hook -once global WinSetOption filetype=(c|cpp|objc) %[
+
 # Regions definition are the same between c++ and objective-c
 evaluate-commands %sh{
     for ft in c cpp objc; do
@@ -271,6 +273,8 @@ evaluate-commands %sh{
     "
 }
 
+]
+
 hook global WinSetOption filetype=(c|cpp|objc) %[
     try %{ # we might be switching from one c-family language to another
         remove-hooks window c-family-hooks
```

**Comment by mawww** [comment]
I am still unsure I would merge it, but if you want to give it a go, I'd love to get some timings and see how much startup time this would save.

**Comment by maximbaz** [comment]
I can convert a few heaviest files to get some estimates, I'm a bit hesitant to convert everything because it will take some time (e.g. I would want to manually test every syntax), and because of whitespace diffs it will quickly become outdated if other PRs will touch the same files.

Can we maybe discuss your concerns first?

Previously you mentioned two things: repeating the same thing in 92 files and creating many new commands that will remain in memory. Now commands are no longer being created, and all these 92 files already have `WinSetOption filetype` hooks anyway, so I would argue this change will not add any new repetition.

Are you maybe concerned that this change will break a particular syntax? I can start by sending a PR just for that one (or for those few) syntaxes, and then you and I can do some more thorough testing.

I don't want to rush you, I want you too to be happy and confident with the change, but if we agree to do this, I would ask you to review & merge it quickly to avoid wasted effort and possible conflicts 😛

**Comment by joakim-noah** [comment]
I'm seeing this on the native Android/AArch64 build in Termux, fairly extreme:
```
$ time kak -n -e 'quit'
real    0m0.041s

$ time kak -e 'quit'
real    0m1.312s
```
I'll see if I can track down where the biggest slowdown is.

**Comment by maximbaz** [comment]
Make sure to try setting `/bin/sh` to point to `dash` (instead of `bash`), and enabling lazy-loading on at least some rc files [like I showed above](https://github.com/mawww/kakoune/issues/2152#issuecomment-413614352) — doing that on `c-family.kak` alone wins for me 60ms on `bash` and 10ms on `dash`.

**Comment by joakim-noah** [comment]
Running the command @mawww gave above in Termux for Android/AArch64, I got these worst offenders:
```
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/x11.kak' took 15288 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/iterm.kak' took 16960 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/tmux-repl.kak' took 17861 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/go-tools.kak' took 18453 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/kitty.kak' took 19237 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/tmux.kak' took 19962 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/git-tools.kak' took 20860 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/core/sh.kak' took 22383 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/screen.kak' took 23520 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/restructuredtext.kak' took 23562 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/core/kakrc.kak' took 24588 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/core/makefile.kak' took 27656 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/markdown.kak' took 28042 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/core/python.kak' took 30928 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/nim.kak' took 32209 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/perl.kak' took 32756 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/protobuf.kak' took 34743 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/d.kak' took 34916 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/pony.kak' took 36093 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/dart.kak' took 36550 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/go.kak' took 36580 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/dockerfile.kak' took 37730 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/ruby.kak' took 42599 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/ocaml.kak' took 43719 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/sql.kak' took 46452 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/sql.kak' took 46452 us
hook 'BufCreate(*scratch*)' took 49988 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/base/clojure.kak' took 113046 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/core/c-family.kak' took 133646 us
sourcing '/data/data/com.termux/files/usr/share/kak/autoload/extra/scheme.kak' took 146976 us
sourcing '/data/data/com.termux/files/usr/share/kak/kakrc' took 1234156 us
```
Shell execution takes most of the time for all of these, those timings omitted from the log I pasted above. I took out 19 of those `.kak` files for languages I don't use, and cut startup time in half to 0.63 s, still noticeable.

I thought I'd compare to kakoune running on other hardware. In a linux/x64 VPS with a fast SSD, I got a best startup time of 64 ms, 6ms with kakrc disabled. I then tried it in the [Anbox Android/x64 container](https://anbox.io) on the _exact same hardware_, and got a best startup time of 302 ms, 10 ms with kakrc disabled.

This implies there's something slow about Android or Termux itself, with the linux/x64 startup slowdown becoming much more noticeable in Termux. It would be nice if kakoune were optimized further for this issue, rather than just assuming everybody's running on a fast SSD and loading all the slower kak language files.

Maybe check the file extension and load the language accordingly?

**Comment by joakim-noah** [comment]
@maximbaz, `dash` is already the default in Termux, `bash` slows kakoune startup down another 130 ms, after ditching those couple dozen kak files.

**Comment by maximbaz** [comment]
File type is the source of truth, not file extension, but in principle you are right and this is exactly what I'm proposing to implement as well.

**Comment by laelath** [comment]
A problem that I encountered when trying to implement my idea is that some highlighters reference highlighters of other filetypes (such as `kakrc` using `sh` highlighting). The filetype of `sh` never gets set, so the hooks to load them wouldn't get triggered, and if you manually triggered a load, you would need to store that somewhere so that it doesn't attempt to load `sh` again later if you open a shell file.

**Comment by maximbaz** [comment]
If we consider my approach, we could go with only wrapping top-level `evaluate-commands %sh{` blocks in `hook -once`, my observation shows that those are the slowest pieces of code to execute anyway. Having top-level `add-highlighters` not being lazy loaded is acceptable in my mind, and solves this dependency problem that you mention.

**Comment by laelath** [comment]
This would work for most of the languages, but `c-family.kak` has a lot of it's highlighters added within those top-level `evaluate-commands %sh{}` blocks.

**Comment by maximbaz** [comment]
Different idea (untested), what if we make the syntax file explicitly initialize its dependencies in this very brutal way (example for kak syntax):

```
hook global BufCreate (.*/)?(kakrc|.*.kak) %{
    set-option buffer filetype sh    # set shell syntax for a moment to force load it
    set-option buffer filetype kak   # finally set the correct syntax file
}
```

**Comment by laelath** [comment]
One option could be to change the behavior of `source` to be more like python's import, as kakoune will check if the file has already been sourced. I agree that the filetype changing, while it would work, is pretty hacky, and runs the risk of triggering user hooks unexpectedly.

**Comment by mawww** [comment]
@maximbaz @laelath There are different approaches I have in mind for that dependency problem:

1. `source -require file.kak` which would source that file only if it was not sourced yet. It would probably require to look for the file in some set of paths, as we cannot really guarantee where the script is going to be, and we likely want to permit overriding a bundled script (by sourcing it in advance)

2. Some similar `source -special-switch` mechanism that does only the path lookup part of that previous command, combined with a `module <identifier>` command that is expected to be put at the beginning of a file and stops sourcing if that identifier was already seen.

2. requires us to read the script again on each sourcing, whereas 1. does not, but 2. makes it easier to override a script without needing files to match their name (so we can even override a module directly in the user kakrc)

In both cases, a script that requires another script can just do that special `source` command call to ensure that script is loaded, so its mostly in how we prevent multiple loading that they differ.

**Comment by laelath** [comment]
Option 2 seems a bit more kak-y to me, and the extra cost is most likely negligible. However there's still the question of the detection hooks for the language files, which need to be auto-defined so they can trigger the loading of the language highlighting and hooks. Maybe the module command could have behavior like this?
```
hook global BufCreate (.*/)?(kakrc|.*.kak) %{
    load-module kakrc
    set-option buffer filetype kak
}
module kakrc %{
    load-module sh
    ... definitions ...
}
```
This is more of a solution for lazy-loading without a central coordinating file than the dependency issue.

**Comment by supermarin** [comment]
> In my view, lazy loading is the last resort, I'd much rather ensure that we are quick to load even without.

@mawww one issue with even super fast script/module loading is - bloat. Sometimes I'm just editing a git commit, or a text file; I really don't want to see arbitrary clang completions or rust commands when pressing `:`.

I'd much prefer to see something like @laelath described above, where the editor loads lang specific stuff only in buffers (or clients) when a file of that kind is open.
Loading & caching per session would also keep the bloat problem.

**Comment by mawww** [comment]
@supermarin I am not sure that hidden bloat would be less bloat, lazy loading to hide those functions means we now need to guess if the users needs them or not. sometimes its easy (clang-complete is unlikely to be needed if we have no buffer whose filetype is c, cpp or objc), sometimes less so (we are in tmux, would it make sense to provide a way to open a x11 window as well, or not ?)

It is possible for users to disable scripts they do not need, and it is possible to write their own lazy loading hooks relatively easily. The missing part is a way to autoload dependencies, to avoid putting on users the burden of knowing what depends on what.

**Comment by maximbaz** [comment]
This is fixed in `master` by lazy loading implemented by @laelath in https://github.com/mawww/kakoune/pull/2782, thanks a lot everyone!

The final numbers:

nvim with no config: 25ms

```
❯ time (repeat 100 nvim -u NONE -c 'quit')
1.33s user 0.87s system 88% cpu 2.490 total
```

nvim with huge config and lots of plugins: 114ms

```
❯ time (repeat 100 nvim -c 'quit')
9.20s user 1.61s system 94% cpu 11.390 total
```

kak -n: 7ms

```
❯ time (repeat 100 kak -n -e 'quit')
0.35s user 0.35s system 99% cpu 0.703 total
```

kak with no custom config in `v2019.01.20`: 70ms

```
❯ time (repeat 100 kak -e 'quit')
7.11s user 1.91s system 115% cpu 7.812 total
```

kak with no custom config in `master`: **20ms**

```
❯ time (repeat 100 kak -e 'quit')
1.77s user 0.72s system 120% cpu 2.060 total
```

20ms beats neovim's 25ms, the issue is solved 🙂

**Comment by CBenoit** [comment]
kakoune is indeed plenty fast when started with no config (`kak -n`), however when starting with a few plugins, it is way more slower than my nvim config with more plugins. :thinking: 

kakoune with a few plugins:
```
❯ time (repeat 100 kak -e 'quit')
( repeat 100; do; kak -e 'quit'; done; )  59.99s user 23.15s system 103% cpu 1:20.35 total
```

nvim with a bigger config and more plugins:
```
❯ time (repeat 100 nvim -c 'quit')
( repeat 100; do; nvim -c 'quit'; done; )  6.84s user 0.90s system 97% cpu 7.961 total
```

I guess nvim greatly improved loading speed for heavy configs

**Comment by occivink** [comment]
Would be helpful to know which / how many plugins you're using.

**Comment by CBenoit** [comment]
Hi! Sure,
- [plugins.kak](https://github.com/CBenoit/dotfiles/blob/master/kak/.config/kak/plugins.kak) [17 plugins]
- [plugins.vim](https://github.com/CBenoit/dotfiles/blob/master/neovim/.config/nvim/plugins.vim) [27 plugins]
I just came back to kakoune after using neovim for a while, I'm currently updating my config and just pushed my current changes for reference.

Here is a profile I got with your command: [profile.txt](https://github.com/mawww/kakoune/files/6472757/profile.txt)

Most of the time is indeed spent in the plugins.kak file:
```
sourcing '/home/auroden/.config/kak/plugins.kak' took 477831 us
```

**Comment by SeerLite** [comment]
Not sure if it's still the case, but from experience andreyorst's plug.kak tends to be pretty slow on startup because it calls the shell on every `plug` command. You could probably speed it up a bit by setting your `KAKOUNE_POSIX_SHELL` to `dash`, which is known to be real fast.

Also, have you tried [alexherbo2's plugin manager](https://github.com/alexherbo2/plug.kak)? It shouldn't have this issue

**Comment by CBenoit** [comment]
Thank you SeerLite, I'll try that!

**Comment by CBenoit** [comment]
I was able to get good performance using alexherbo2's plugin manager :+1: 

```
❯ time (repeat 100 kak -e 'quit')
( repeat 100; do; kak -e 'quit'; done; )  24.58s user 2.74s system 134% cpu 20.344 total
```
