### ISSUE TITLE
multi-line selection should be commented on the same level with `comment-line`

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2156]
Let's use this code snippet:

```python
1: def main():
2:     for i in range(5):
3:         print(i)
4:     print('done')
```

--------------

<details>
<summary>Case 1: Select everything with <code>%</code>, run <code>comment-line</code>.</summary>

Expected:

```python
1: # def main():
2: #     for i in range(5):
3: #         print(i)
4: #     print('done')
```

Actual:

```python
1: # def main():
2:     # for i in range(5):
3:         # print(i)
4:     # print('done')
```
</details>

-------------

<details>
<summary>Case 2: Select lines 2-4, run <code>comment-line</code>.</summary>

Expected: 

```python
1: def main():
2:     # for i in range(5):
3:     #     print(i)
4:     # print('done')
```

Actual:

```python
1: def main():
2:     # for i in range(5):
3:         # print(i)
4:     # print('done')
```
</details>

-----------------

I was hoping to make a PR instead of an issue, but I got stuck at coming up with a smart way to make this selection.

Currently the selection is being trimmed with `<a-s>gi<a-l>`, but it leads to the "Actual" behavior that I want to avoid. So far I was thinking to also trim the selection with `<a-s>gi`, but then to align cursors with the most _left_ one - kind of like the opposite of `&` operator. But there is no such operator, as far as I can see... Maybe there is another way to achieve what I want?

**Comment by shachaf** [comment]
I had a similar issue and wrote my own comment-line -- this the current state of it, with the description of the behavior I want in the comment. Does this sound like the behavior you want as well?

```
# To comment/uncomment a selection containing multiple lines:
# Drop blank lines, unless any line contains unindented text.
# Find the leftmost non-whitespace column among all lines.
# If every line has a comment string starting at this column, delete them.
#   (Optional: Among the lines not ending at the comment string,
#    find the smallest number of spaces shared by all of them
#    immediately after the comment string, and delete that as well.)
# Otherwise insert a comment string before this column.
def comment-line-better %{
  eval %sh{[ -z "$kak_opt_comment_line" ] && echo "fail '%opt{comment_line} not set!"}
  eval -draft -itersel -save-regs '/"a' %{
    exec '<a-x><a-s>gi"aZ'
    try %{
      exec -itersel 'gh<a-K>\S<ret>' # Fail if any line is unindented.
      exec '"az<a-K>^$<ret>"aZ' # Drop blank lines.
    } catch %{
      exec '"az'
    }
    align-cursors-left
    exec '"aZ<a-l>'
    try %{
      reg / "\A\Q%opt{comment_line}\E"
      exec -itersel 's<ret>' # Fail if if any line fails to match.
      exec '<a-d>'
      try %{ # Optional: Remove common whitespace.
        exec '<a-l><a-K>\A$<ret><a-;>;"aZ<a-l>s\A +<ret>'
        align-cursors-left
        exec '"a<a-z>u<a-d>'
      }
    } catch %{
      exec '"az'
      reg '"' %opt{comment_line}
      exec P
    }
  }
  # Maybe instead of maintaining the existing selection, this should select the
  # comment column or the following whitespace, so that you can insert/delete
  # whitespace yourself if you want, <a-J>-style.
}

def align-cursors-left \
  -docstring 'set all cursor (and anchor) columns to the column of the leftmost cursor' \
  %{ eval %sh{
  col=$(echo "$kak_selections_desc" | tr ' ' '\n' | sed 's/^[0-9]\+\.[0-9]\+,[0-9]\+\.//' | sort -n | head -n1)
  sels=$(echo "$kak_selections_desc" | sed "s/\.[0-9]\+/.$col/g")
  echo "select $sels"
}}
```

**Comment by shachaf** [comment]
A few more details:

If there are blank lines, I want them to remain blank, rather than introducing a comment string -- *unless* the whole selection is unindented, i.e. the comment string is on the leftmost column, in which case I want to comment the blank lines as well.

So:

<details>
Commenting out lines 5-7 of

```
1: def main():
2:   print(1)
3:   if True:
4:     print(2)
5:     print(3)
6:
7:     print(4)
8:   print(5)
```

Should produce

```
1: def main():
2:   print(1)
3:   if True:
4:     print(2)
5:     #print(3)
6:
7:     #print(4)
8:   print(5)
```

But commenting out lines 1-8 should produce

```
1: #def main():
2: #  print(1)
3: #  if True:
4: #    print(2)
5: #    print(3)
6: #
7: #    print(4)
8: #  print(5)
```

</details><br>

There might be a better way to phrase it without referring to blank lines explicitly, in terms of whether a character can be inserted at column n, but this should work if you don't have trailing whitespace (or an odd use of tabs).

Another change from the current comment-line is that I don't want to insert whitespace after the comment string.

I couldn't figure out how to make align-cursors-left work without %sh.

**Comment by maximbaz** [comment]
@shachaf huge thank you for sharing your work! I took your approach of aligning the cursors to implement the behavior I want, and I'll try to get this merged in master 😉 

The behavior you described stays with one difference: the whitespace will be inserted after the comment string, because this is how master is currently working, and because I prefer this behavior as well.

**Comment by shachaf** [comment]
The spaces were only added to master recently, in <https://github.com/mawww/kakoune/commit/e1c720000cd8228655b2a30c53f92446ee0a11ba>, and I don't like it: I prefer to add a space after the comment string for human-readable text only, not for code. If there's no option for not adding a space I'll have to keep maintaining my own version. Maybe a second option? That seems like too much configuration for such a small feature, though.

(If you do add a space, by the way, you probably want to drop eol cursors first, so as not to add trailing whitespace.)

**Comment by maximbaz** [comment]
Good point, I don't want to introduce trailing whitespaces. So this makes it another difference to your implementation, the unindented lines are not treated specially and all blank lines are always dropped. 

I'll leave it to you to investigate if not adding a whitespace after the comment-char should be a new option, I prefer the current behavior in master 😉

**Comment by shachaf** [comment]
Oh, what I meant was to add something like `'<a-K>\A$<ret>'` before inserting the whitespace. You still want the comment character, I think.

**Comment by shachaf** [comment]
One option, which I mentioned in a comment, is to select the inserted comment string or the column it was deleted from, so that you can insert/delete the whitespace yourself easily (like <a-J>). I had an implementation of this at one point but I think I went back to the old behavior.

**Comment by shachaf** [comment]
What you really want is to find the leftmost column, and then insert a comment string at that column at every line where that column exists. Dropping blank lines is a good approximation of this.

> By the way, do you by any chance happen to own a Mac?

I don't. I see that your align-cursors-left is different from mine: It only sets the anchor column, and leaves the cursor column unchanged. I'm not sure why -- this seems more fragile to me? -- but if you stick with that behavior, you should fix the docstring (and the name, since it doesn't actually change the cursors).

**Comment by maximbaz** [comment]
Your `align-cursors-left` somehow didn't work for me out of the box, so I started reverse engineering its behavior and realized that I don't have to cancel the existing selection, I can just extend the selection to the left to get the proper alignment. I guess it's pretty much the same in the end 🙂 But good point on the name and docstring, I'll adapt.

**Comment by maximbaz** [comment]
Thanks for the heads-up on the separator character 🙂 Well, hopefully my PR brings the `comment-line` in the right direction towards your implementation, once it's merged you may want to consider implementing the option for adding or not adding a whitespace.
