### ISSUE TITLE
Feature request: vertical (block) selection

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2158]
I know that every scenario can be achieved using existing functionality, but I still want to request block selection just for the sake of convenience and more natural editing.

Example:

Copy-paste a snippet from a random PR in this repo (`|` represents cursor):

```
+    inline_docstring /// $ '' \
+    comment '/\+' '\+/' '' \
+    comment '/\*' '\*/' '' \
+    comment '//' $ ''
|
```

Now the task is to delete the leading `+` and all whitespaces in front of every line. 

I could of course select the lines above with `kKKK`, then fix the selection with `<a-x>`, then split cursors with `<a-s>`, then move them to the beginning with `gj`, and then finally delete stuff with `ddddd`. But this sounds too artificial, isn't it? Is there a better way that I'm unaware of?

I imagine a more natural approach would be to start the block selection with some kind of `<a-K>`, select more lines upwards with `KKK`, then select the whitespaces to the right with `lll`, and then delete the selected block with `d`. That's kind of what I would do in vim. 

What do you think?

**Comment by Screwtapello** [comment]
I think you're looking for `C` and `<a-C>`.

**Comment by mawww** [comment]
`C` and `<a-C>` are the way to go for a similar to block selection functionality. I dont plan to add block selections on top of that, as they are too similar to justify having both, it might however make sense to tweak `C` behaviour if you have a use case which is not served well by its current behaviour.

**Comment by maximbaz** [comment]
Wow, yes, `C` and `<a-C>` are precisely what I was looking for, thanks!
