### ISSUE TITLE
The selected lines should be uncommented only if all of them were commented

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2161]
Suppose you have the following snippet:

```yaml
abc:
    # def: ha
    eg: bla
```

You want to comment it all, so you select everything with `%` and execute `comment-line` command.

Expected:

```yaml
# abc:
#     # def: ha
#     eg: bla
```

Actual:

```yaml
abc:
    def: ha
    eg: bla
```

I tried to come up with a solution in order to make PR, but stumbled upon a couple of roadblocks. Below is the snippet I could get to myself, and it has a couple of issues:

1. `Z` and `z` don't seem to have any effect within the command, so I cannot test whether all lines are commented with `<a-K>` and then safely restore the selection.
2. The `execute-keys <a-K>\A\Q%opt{comment_line}\E\h?<ret>` doesn't seem to raise an error when there are no lines left, so the code doesn't go into `catch` block, even though when testing manually I do see a red error message in the bottom saying that "no selections remaining".

Please point me in the right direction, or make your own PR, I don't mind as long as I can get the functionality in `master` :)

```kak
define-command comment-line -docstring '(un)comment selected lines using line comments' %{
    %sh{
        if [ -z "${kak_opt_comment_line}" ]; then
            echo "fail \"The 'comment_line' option is empty, could not comment the line\""
        fi
    }
    evaluate-commands -draft %{
        # Select the content of the lines, without indentation
        execute-keys <a-s>gi<a-l>

        try %{
            # Keep non-empty lines and save the selection
            execute-keys <a-K>\A\s*\z<ret>Z

            try %{
                # See if there are any uncommented lines in the selection
                execute-keys <a-K>\A\Q%opt{comment_line}\E\h?<ret>

                # There are uncommented lines, so restore the selection and comment everything
                set-register '"' "%opt{comment_line} "
                execute-keys zP
            } catch %{
                # All lines were commented, so restore the selection and uncomment them
                set-register / "\A\Q%opt{comment_line}\E\h?"
                execute-keys zs<ret>d
            }
        }
    }
}
```

**Comment by occivink** [comment]
>Z and z don't seem to have any effect within the command, so I cannot test whether all lines are commented with <a-K> and then safely restore the selection.

That's because of the `-save-regs` flag of `exec`: the value of the `^` register is restored directly after exec. However, you don't need to use marks in this case, you would instead use `exec -draft` 

>The `execute-keys <a-K>\A\Q%opt{comment_line}\E\h?<ret>` doesn't seem to raise an error when there are no lines left, so the code doesn't go into catch block, even though when testing manually I do see a red error message in the bottom saying that "no selections remaining".

I think this is just a matter of quoting, the `%opt{...}` need to be by itself or in a ""-string to be expanded.

FInally, when you have arbitrary input like here, you should prefer setting the search register to the value before calling `exec <a-K><ret>`, that's because any `<` has to be written as `<lt>` in an exec.

So in the end you want to do something like this (untested):
```
# See if there are any uncommented lines in the selection
set-register / "\A\Q%opt{comment_line}\E\h?"
execute-keys -draft <a-K><ret>
```

**Comment by maximbaz** [comment]
This is just perfect, thanks a lot @occivink! It needs some extra polishing, but I'll try to take it from here 😉
