### ISSUE TITLE
show_whitespaces highlighter can't be used to show only a single type of whitespace

### ISSUE THREAD

**Issue by StanislavNikolov** [mawww/kakoune#2166]
### Steps
Put `addhl global/ show_whitespaces -tab ·` in kakrc or enter directly.

### Outcome
Every whitespace was shown, although I want only tabs. This is a bug, because there is no way to say for example "show tabs and spaces, but not line feeds". One can't simply provide "ignore" byte, or even space for that matter (`<space>` does not work).
![](https://cukii.me/stjo/other/bugs/2018-06-28-21:44:48.png)

### Expected
Tabs to be shown with the special character provided, every other whitespace to be shown as before.
Maybe a workaround would be to let `addhl global/ show_whitespaces -tab · -lf <space> -spc <space>` do the obvious thing.

**Comment by occivink** [comment]
`" "` works instead of `<space>`

**Comment by StanislavNikolov** [comment]
Nope, now the character for tabs is ignored
![](https://cukii.me/stjo/other/bugs/2018-06-28-22:00:21.png)

**Comment by mawww** [comment]
Here `addhl global/ show_whitespaces -tab · -lf ' ' -spc ' ' ` works as expected. Is that still broken for you ?

**Comment by StanislavNikolov** [comment]
Yes, `addhl global/ show_whitespaces -tab · -lf ' ' -spc ' '` works as expected. I still feel like this should be documented somewhere, but it's good to know it's possible.

**Comment by Delapouite** [comment]
@StanislavNikolov can this issue be closed?

**Comment by StanislavNikolov** [comment]
Yes, sorry, forgot it was my job :D
