### ISSUE TITLE
Problem with ruby lint with rubocop

### ISSUE THREAD

**Issue by artero** [mawww/kakoune#2189]
This is my first issue in the project. I like a lot Kakune, an awesome job!

### Steps
In the `kakrc` file I configure the ruby lint with rubocop in this way:

```
hook global WinSetOption filetype=ruby %{
  set window lintcmd "rubocop"
  lint-enable
}
````

Then I open the file `app/models/user.rb` (that has a lot of offenses) and execute the command `:lint`

### Outcome

The output format is not valid to view the offenses in the file buffer, but when I open the `*lint-output*` buffer I can see:

```
app/models/user.rb:0 files inspected, no offenses detected
app/models/user.rb:Inspecting 0 files
```

This message is like if rubocop doesn't find any file.

### Expected

I expected to get the errors in the `*lint-output*` buffer like I see when I execute the same command in the terminal for that file.

```
rubocop app/models/user.rb
```

**Comment by lenormf** [comment]
I think you could try `set window lintcmd "rubocop --format emacs'`.

The reason what you tried didn't work is that the `:lint` command expects a [formatted output](https://github.com/mawww/kakoune/blob/master/rc/base/lint.kak#L2,L3), which isn't respected by `rubocop`'s default formatter.

If that doesn't work, you could also consider writing a wrapper script for `rubocop` that uses a [custom format](https://rubocop.readthedocs.io/en/latest/extensions/#using-a-custom-formatter-from-the-command-line).

**Comment by artero** [comment]
Thank you for your answer. I tried this but not fix the problem, the problem is not an unknown format error. Is more like if rubocop don't find the file.

The rubocop output says "Inspecting 0 files" Rubocop prints this output when doesn't find the specified file.

**Comment by lenormf** [comment]
I got linting to work with the following:

```
set window lintcmd "rubocop -f emacs <"
```

One weird issue with `rubocop` is that it won't analyze files that don't have the `.rb` extension, which is exactly what `lint.kak` does (it passes a `buf` file, without any extension). You might want to report that to `rubocop`, as it's really not convenient.

**Comment by artero** [comment]
You're right. The problem was rubocop doesn't analyze files with extensions not specified in the rubocop.yml file.

[The default extensions do not include the .kak](https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml#L17) files I fixed this adding in my rubocop.yml the next code:

```
AllCops:
  Include:
    - '**/*.kak'
```

Thank you very much.

**Comment by mawww** [comment]
We could change lint.kak to try to preserve file extension to avoid such problems.
