### ISSUE TITLE
Things that are broken in master after big-breaking-tidy-up

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2191]
Making a list as I wouldn't be able to look into these right now, maybe someone has a chance to have a look:

- [x] `git show-diff` now silently fails. The issue is probably here:

https://github.com/mawww/kakoune/blob/b06ad0650747f79034e64dce60832ff824b3cb84/rc/extra/git-tools.kak#L188

- [x] `'lint-enable' 2:6: 'add-highlighter' no parent in path`

The above is fixed with #2192 

----------

More issues:

- [x] `'go-disable-autocomplete' 2:6: 'set-option' invalid completer description: '''filename' 'word=all'''`
- [ ]   `lint`:
    ```
    error running command 'set-option "buffer=/path/to/code.go" lint_flags 1
    set-option "buffer=/path/to/code.go" lint_errors 1
    set-option "buffer=/path/to/code.goo" lint_error_count 0
    set-option "buffer=/path/to/code.go" lint_warning_count 0
    evaluate-commands -client  lint-show-counters
    ': 5:484: 'evaluate-commands' wrong argument count
    ```
- [x] `lint`: even if I "fix" the above by replacing `${kak_client}` with `${kak_client:-default0}`, I see the lint highlighters in the gutter, and I see all the issues in `*lint-output*` buffer, but navigation with `:lint-next-error` doesn't work, it prints an error `no lint diagnostics`.

**Comment by maximbaz** [comment]
I looked into `lint` issue, the problem is with command:
```
evaluate-commands -client  lint-show-counters
```

In the code it looks as `-client $kak_client`, and as you can see the parameter `$kak_client` got expanded to an empty string.

I think it's some kind of race condition, I have `lint` call running in `hook global WinSetOption filetype=XX` because I want to immediately lint a buffer that I've just opened (or if I change its filetype). It used to work before the tidy-up, but now the kak_client is not set during WinSetOption hook.

@mawww does it ring any bell, why $kak_client is not set during WinSetOption hook? Was it an accidental or intended change?

**Comment by maximbaz** [comment]
Regarding $kak_client I've just stumbled upon #1872, except I think my case is different. First of all, it definitely worked before the big-breaking-tidy-up. But also I only have one window, and I have issues with missing $kak_client even if I open kak first, and then open the file with `:e file.go` (so the window definitely exists at that time).

**Comment by mawww** [comment]
Looking at the code, I dont think we ever had `$kak_client` set in there. However, I see we have everything we need to set it to the actual client name, as Window has a back-pointer to the client that display it (if any), so we could access its name (or even run directly in its context). That is not fool proof though, as Windows might be in the free window list, hence not associated with any clients.

**Comment by lenormf** [comment]
Aren't all those fixed by now?

**Comment by maximbaz** [comment]
One more left, the noise in `*debug*` buffer when you have lint enabled in WinSetOption filetype hook, e.g. like so:

```
hook global WinSetOption filetype=sh %{
    set-option window lintcmd 'shellcheck -x -fgcc'
    lint-enable
    lint
}
```

I don't recall it being an issue before, but I might be wrong. I can create a separate issue for setting `$kak_client` at the time the hook runs and close this ticket if that's what you prefer.

**Comment by maximbaz** [comment]
Very relevant, but I'm okay tracking it via #1872
