### ISSUE TITLE
Navigate completions list by columns, not by rows

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2199]
I cannot get used to navigating kakoune completions horizontally:

![kak-completions-navigation](https://user-images.githubusercontent.com/1177900/42423425-402fa9d4-82fa-11e8-92a3-751336c8a24b.gif)

Everywhere else I know a column navigation is used instead, e.g. here's `zsh`:

![vertical-list-navigation](https://user-images.githubusercontent.com/1177900/42423340-0d3f224e-82f9-11e8-97fd-2686d3b0d3cd.gif)

Bash also draws completions vertically:

![image](https://user-images.githubusercontent.com/1177900/42423548-6330f10c-82fc-11e8-87dc-fa49613c70db.png)

`ls` and `exa` also order files in columns:

![image](https://user-images.githubusercontent.com/1177900/42423561-849f9d02-82fc-11e8-9c7c-772d6e435585.png)

Can we please make the completions list in kakoune also conform to this pattern? At least optionally.

It's much easier to compare alphabetically-sorted files when they are drawn in columns, if I'm looking for the file "client.cc", it is easy to see at a glance that files whose names start with a letter "c" are in the second column.

Related: #1508

**Comment by lenormf** [comment]
We read text from left to right, and then go to the next line downwards, which makes the current implementation _theoretically_ more intuitive.

This issue has probably more to do with habits than an actual problem we can solve using logic (neither layout seem fundamentally flawed, they're just a design choice).

**Comment by maximbaz** [comment]
I'll be happy as long as any way to choose the vertical layout, so an option as proposed in #2212 sounds like a perfect solution 😉

**Comment by maximbaz** [comment]
Fixed with #2286
