### ISSUE TITLE
Copy to clipboard adds single quotes

### ISSUE THREAD

**Issue by boj** [mawww/kakoune#2202]
### Steps 

After building from commit f89ea657ef83d66a43608d8177a39247c0bc1f88 the other day I noticed that doing any kind of select + `y` with the clipboard macro now adds a single quote around the entire text, and escapes any additional single quotes in the text with another single quote.

```
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_reg_dquote" | xsel --input --clipboard
}}
```

### Outcome 

```
'I am a bunch of text, but don''t mind me I won''t hurt you.
'
```
### Expected 

```
I am a bunch of text, but don't mind me I won't hurt you.
```

**Comment by occivink** [comment]
That's because `$kak_reg_*` now prints the full contents of the register (which are lists). If you only care about the content of the main selection (as it used to be), you can use `$kak_main_reg_*`.

**Comment by mawww** [comment]
This should probably be added to the changelog
