### ISSUE TITLE
Colors are off no matter what

### ISSUE THREAD

**Issue by Quelklef** [mawww/kakoune#2207]
Sorry I couldn't give a more descriptive title; I can't pinpoint the issue.

No matter what I try, my kakoune colors seem to be off. Solarized-dark looks like this:

![2018-07-11-011945_1920x1080_scrot](https://user-images.githubusercontent.com/14851215/42552538-cfa3382c-84aa-11e8-81f6-656ed6434443.png)

- On Ubuntu 17.10
- Issue persists on suckless-terminal as well as gnome-terminal (no others tested)
- Not running tmux
- `$TERM` is `st-256color`
- [This](https://gist.github.com/XVilka/8346728) true color test succeeds

I can't seem to find a whole lot of documentation about similar cases. Most color issues seem to be related to tmux or $TERM.

**Comment by Screwtapello** [comment]
Kakoune does not use your terminal's true-colour output; instead, it uses the `initc` terminfo capability to modify the 256-colour palette to match what the theme requires.

```sh
$ infocmp -1 st-256color | grep initc
	initc@,
```

Since `st-256color` un-sets the `initc` capability with `@`, that indicates it doesn't support modifying the palette, only using the standard palette without modification.

It *should* work with `gnome-terminal`, but make sure `$TERM` is set to `vte-256color` or (if that's not available) try `xterm-256color`; it may default to something like `xterm` which only declares support for 8 fixed colours.

```sh
$ infocmp -1 vte-256color | grep initc
	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
```

**Comment by Quelklef** [comment]
Curiously, my machine outputs:

```
λ ~: infocmp -1 st-256color | grep initc
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
```

**Comment by Screwtapello** [comment]
You mean `TERM=xterm-256color`, right?

I think you also need the `ccc` capability ("Can Change Color") before `initc` can be used. What does this shell-script do for you?

```sh
if tput ccc; then
    # Set colour 16 to a nice bright orange (#FF7F00)
    tput initc 16 1000 500 0
    # Tell the terminal to draw text in colour 16
    tput setaf 16
    # Write something
    echo orange
    # Tell the terminal to draw text in the default colour
    tput sgr0
else
    echo "No colour-change support"
fi
```

**Comment by Quelklef** [comment]
Sorry, yes, `TERM`, not `PATH`. I am tired.

The given script outputs `orange` in orange:

![2018-07-11-034715_66x17_scrot](https://user-images.githubusercontent.com/14851215/42557669-1fb62e34-84bd-11e8-8894-cf91b0482114.png)

**Comment by Screwtapello** [comment]
To the best of my knowledge, that's all that Kakoune needs to use custom colour-schemes.

I'm running low on ideas here, but just to double-check I understand what's going on: you described your initial screenshot as "Solarized-dark looks like this", but it's a screenshot of the *source* of the "solarized-dark" colour scheme, while the right-hand window suggests Kakoune is trying to use a colour scheme called "dracula" (which isn't part of the official Kakoune distribution) and the actual colours visible in the screenshot bear a strong resemblance to the "gruvbox" palette (which *does* come with Kakoune).

If you just run `kak -e "colorscheme solarized-dark"` what does that look like?

**Comment by Quelklef** [comment]
_Sigh_.

It appears I was running using the dracula theme this whole time. I don't know how I managed to avoid realizing that for literal hours. I'm really sorry about this. Cheers to a correctly-working application.

Solarized-dark does look a little off after all, but I'm 99% sure it's due to font, font size, and bolding and the colors are working perfectly.
