### ISSUE TITLE
:ranger doesn't work on macOS in iTerm2

### ISSUE THREAD

**Issue by whereswaldon** [mawww/kakoune#2211]
It looks like `ranger.kak` doesn't handle the case where it is running within iTerm2.

### Steps
- `brew install kakoune`
- `brew cask install iterm2`
- Launch iterm
- `kak`
- `:ranger`

**Note**: I tried to build the master branch to verify whether the problem was present there, but #2210 got in the way.

### Outcome
Ranger does not open in a new iTerm tab/pane/window

### Expected
Ranger should open using the native iTerm capabilities that Kakoune can already use (`:iterm-*`).

### Versions
```
$ brew info kakoune
kakoune: stable 2018.04.13 (bottled)
Selection-based modal text editor
https://github.com/mawww/kakoune
/usr/local/Cellar/kakoune/2018.04.13 (118 files, 3.0MB) *
  Poured from bottle on 2018-06-25 at 11:22:31
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kakoune.rb
==> Dependencies
Build: asciidoc, docbook-xsl
```
```
$ brew cask info iterm2
iterm2: 3.1.7
https://www.iterm2.com/
/usr/local/Caskroom/iterm2/3.1.7 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/iterm2.rb
==> Name
iTerm2
==> Artifacts
iTerm.app (App)
```
```
$ brew info ranger
ranger: stable 1.9.1, HEAD
File browser
https://ranger.github.io
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ranger.rb
==> Options
--HEAD
	Install HEAD version
```

**Comment by ekie** [comment]
hej,

do you get some output in the debug buffer ?

**Comment by alexherbo2** [comment]
#1450

**Comment by whereswaldon** [comment]
@ekie It doesn't output in debug, it's a silent failure.

@alexherbo2 Could you elaborate on how to use your extensions to achieve the same thing? I've watched your screencast and read the READMEs for connect.kak and shell.kak, but I'm still a little bit lost on the correct usage.

**Comment by whereswaldon** [comment]
After further reflection and analysis, I think I follow how to do it:
- use the `:terminal` command suggested by `shell.kak` to open `ranger` (so that the `$KAK_{SESSION,CLIENT}` environment variables are set. This will make ranger open in a new instance of your terminal emulator with the aforementioned environment.
- If `$EDITOR` in `ranger` is set to `kak-connect`, then `ranger` will open files in the client where you ran `:terminal`.

That's cool, and it does seem to replace the current functionality of `:ranger`.
I do wish that it handled tmux and friends as transparently as the current `:ranger`, but you can't have everything I guess.

Anyway, does #1450 mean that this particular issue won't be fixed? If so, feel free to close this issue.

**Comment by alexherbo2** [comment]
@whereswaldon I think it’s just matter of a one-liner for `:terminal` to handle _tmux_ – by checking if `$TMUX` is set and opening a _tmux_ pane instead.

**Comment by Delapouite** [comment]
As `ranger.kak` has been removed from `rc/tools`, I think this issue can be closed.

**Comment by whereswaldon** [comment]
I agree

**Comment by alexherbo2** [comment]
@whereswaldon The plug-in has quite changed and doesn’t need configuration now.  Just `connect ranger` and it works.
