### ISSUE TITLE
How is * working

### ISSUE THREAD

**Issue by co-dh** [mawww/kakoune#2214]
I'm kind of confused by how star ( * ) is working. 
It says: (automatically detects word boundaries), but It seemed do nothing.
It do  not expand the selection to the end of word or beginning of word as in vi, and it's the same as <a-*>
Is it a bug? I'm expecting it expand selection to current word under cursor.

**Comment by co-dh** [comment]
Ok, I figure it out by read the source:
if cursor is at the end of a word, it add \b to the pattern. same for beginning of word.
To get vi's *, you need:
map global normal * be*n

**Comment by co-dh** [comment]
map global normal * lbe*n
This is the correct version

**Comment by net** [comment]
`<a-i>w*`
