### ISSUE TITLE
`:go-enable-autocomplete` is broken on master

### ISSUE THREAD

**Issue by whereswaldon** [mawww/kakoune#2215]
### Steps 
- Get latest version of kak (I'm on commit c58457a3c0)
- Ensure you have `gocode`, `gogetdoc`, `goimports`, and `jq` installed
- Open a go source code file:
```
$ cat > main.go <<EOF
package main

import "fmt"

func main() {
}
EOF
$ kak main.go
```
- Run `:go-enable-autocomplete`
- Type `fmt.` in the body of the main function

### Outcome 
No completions are offered.

In the debug buffer, you see:
```
*** This is the debug buffer, where debug info will be written ***
error while trying to run completer: option not found: 'gocode_completions:'filename' 'word=all''. Use declare-option first
```
### Expected 
Symbols defined in the `fmt` package should be offered as completions.

### Partial Fix
I've debugged this as far as I can on my own. if make this change to `go-tools.kak`:
```
diff --git a/rc/extra/go-tools.kak b/rc/extra/go-tools.kak
index 9ea17562..9d2ff717 100644
--- a/rc/extra/go-tools.kak
+++ b/rc/extra/go-tools.kak
@@ -42,7 +42,7 @@ define-command go-complete -docstring "Complete the current selection with gocod
 }

 define-command go-enable-autocomplete -docstring "Add gocode completion candidates to the completer" %{
-    set-option window completers "option=gocode_completions:%opt{completers}"
+    set-option window completers "option=gocode_completions" %opt{completers}
     hook window -group go-autocomplete InsertIdle .* %{ try %{
         execute-keys -draft <a-h><a-k>[\w\.].\z<ret>
         go-complete
```
Then the debug error stops (presumably because it is now able to recognize the `option=gocode_completions` completer as an individual list element). However, completions from gocode are still not offered to the user (completions from `word=all` do show up though).

This makes me think that the value of `gocode_completions` is malformed, but I can't find the problem. I checked it against the documented syntax, but it seems correct. For instance, here it is after typing `fmt.` in the example that I provided at the top:
```
6.9@69:Errorf(||func Errorf(format string, a ...interface{}) error:Fprint(||func Fprint(w io.Writer, a ...interface{}) (n int, err error):Fprintf(||func Fprintf(w io.Writer, format string, a ...interface{}) (n int, err error):Fprintln(||func Fprintln(w io.Writer, a ...interface{}) (n int, err error):Fscan(||func Fscan(r io.Reader, a ...interface{}) (n int, err error):Fscanf(||func Fscanf(r io.Reader, format string, a ...interface{}) (n int, err error):Fscanln(||func Fscanln(r io.Reader, a ...interface{}) (n int, err error):Print(||func Print(a ...interface{}) (n int, err error):Printf(||func Printf(format string, a ...interface{}) (n int, err error):Println(||func Println(a ...interface{}) (n int, err error):Scan(||func Scan(a ...interface{}) (n int, err error):Scanf(||func Scanf(format string, a ...interface{}) (n int, err error):Scanln(||func Scanln(a ...interface{}) (n int, err error):Sprint(||func Sprint(a ...interface{}) string:Sprintf(||func Sprintf(format string, a ...interface{}) string:Sprintln(||func Sprintln(a ...interface{}) string:Sscan(||func Sscan(str string, a ...interface{}) (n int, err error):Sscanf(||func Sscanf(str string, format string, a ...interface{}) (n int, err error):Sscanln(||func Sscanln(str string, a ...interface{}) (n int, err error):Formatter||type Formatter interface:GoStringer||type GoStringer interface:ScanState||type ScanState interface:Scanner||type Scanner interface:State||type State interface:Stringer||type Stringer interface
```
The above was generated by `:echo -debug %opt{gocode_completions}`. I can't tell what's wrong with it, but perhaps someone else can spot it.

Thanks!

**Comment by maximbaz** [comment]
A bit off-topic, but if you haven't tried [kak-lsp](https://github.com/ul/kak-lsp) with [go-langserver](https://github.com/sourcegraph/go-langserver) yet, do consider using those instead. No need to install `gocode`, `gogetdoc` and `goimports`, works on the current `master` and having `kak-lsp` configured makes it super easy to install langservers for more languages when needed 😉

**Comment by swdunlop** [comment]
I think you were close, @whereswaldon, but we also have to patch the `set-option` passed back from the completion via `kak -p`.

The following works for me, as of 2018.09.04:

```diff
diff --git a/rc/extra/go-tools.kak b/rc/extra/go-tools.kak
index 9ea17562..e1c87877 100644
--- a/rc/extra/go-tools.kak
+++ b/rc/extra/go-tools.kak
@@ -35,16 +35,17 @@ define-command go-complete -docstring "Complete the current selection with gocod
             header="${kak_cursor_line}.$((${kak_cursor_column} - $column_offset))@${kak_timestamp}"
             compl=$(echo "${gocode_data}" | sed 1d | awk -F ",," '{print $2 "||" $1}' | paste -s -d: -)
             printf %s\\n "evaluate-commands -client '${kak_client}' %{
-                set-option buffer=${kak_bufname} gocode_completions '${header}:${compl}'
+                set-option buffer=${kak_bufname} gocode_completions '${header}' '${compl}'
             }" | kak -p ${kak_session}
         ) > /dev/null 2>&1 < /dev/null &
     }
 }
 
 define-command go-enable-autocomplete -docstring "Add gocode completion candidates to the completer" %{
-    set-option window completers "option=gocode_completions:%opt{completers}"
+    set-option window completers "option=gocode_completions" %opt{completers}
     hook window -group go-autocomplete InsertIdle .* %{ try %{
         execute-keys -draft <a-h><a-k>[\w\.].\z<ret>
+        echo 'completing..'
         go-complete
     } }
     alias window complete go-complete
```

(I highly recommend sneaking in a `| tee /tmp/...` to debug these `kak -p` exchanges.  That's how I compared the broken Go completer to the working C completer.)

I will put together a pull request.

**Comment by swdunlop** [comment]
Got it.  Each completion must be an individual argument to `set-option`.  Since the gocode completions will contain whitespace, they must be quoted individually, not the entire array.  Things appear to be working well, now, which means I can actually get some work done today. :)

**Comment by Delapouite** [comment]
@whereswaldon can this issue be closed?

**Comment by whereswaldon** [comment]
Yes it can. Thanks @swdunlop!
