### ISSUE TITLE
Separate ncurses title from mode line

### ISSUE THREAD

**Issue by yshui** [mawww/kakoune#2217]
Currently the window title is the mode line with ' - Kakoune' appended to it. This is not very nice. Since mode line generally has much more real estate than the window title.

A window title is more likely to be used for just identifying the window, while the mode line is expected to contain as much useful information as possible.

Given that, it would be nice if we can set the title and mode line separately.

**Comment by lenormf** [comment]
You want the window title to be more generic, e.g. `Kakoune - buffer.c` ?

**Comment by yshui** [comment]
@lenormf Yes. But it's more preferable for it to be configurable.

**Comment by dmerejkowsky** [comment]
I had the same problem so I wrote a quick and dirty patch here:
https://github.com/dmerejkowsky/kakoune/commit/ff4c40cc270de032655bbe49998f83d869b2f580

I'm not sure how we can make this configurable. Any thoughts ?

**Comment by hacktivista** [comment]
#2249

**Comment by lammermann** [comment]
It seems I'm a bit late, but as mawww likes feedback who would use this https://github.com/mawww/kakoune/pull/4265#pullrequestreview-767644760 here is my use case:

I'd like to use the window title to have the full file path. This way I can use [arbtt](http://arbtt.nomeata.de/) to track which are the folders I'm currently working in. In the modeline the full path would often clutter the information for me.

**Comment by korreman** [comment]
I'll add in my two cents as well in the hopes that this feature gets merged soon.

I use a tiling WM to put kakoune clients in tabs. I don't want the cursor position, line count, current mode, file type, directory, and git status to be part of tab names. I'd also like to put the buffer name all the way to the right in the modeline, so it doesn't jump around every time I press a key. A customizable terminal title would allow me to improve both tab names and the modeline.

Generally, I think the terminal title should mostly be used to identify a terminal by the process attached to it. This is different from the modeline, an infobar displayed inside the process UI. Both of these just happen to include the buffer name when the attached process is an editor.
