### ISSUE TITLE
int-list: first item is printed with quotes

### ISSUE THREAD

**Issue by fsub** [mawww/kakoune#2223]
### Steps 
```
decl int-list blub
set global blub 1 2 3
eval %sh{ printf "echo %s\\n" "$kak_opt_blub" }
eval %sh{ printf "echo (%s)\\n" "$kak_opt_blub" }
eval %sh{ printf "echo ( %s )\\n" "$kak_opt_blub" }
```
### Outcome 
```
1 2 3
('1' 2 3 )
( 1 2 3 )
```

### Expected 
```
1 2 3
(1 2 3)
( 1 2 3 )
```

Not sure if my expectation is reasonable.

**Comment by lenormf** [comment]
It does sound reasonable that the expansions shouldn't use quotes if they're not needed. That way you could just use `for n in ${kak_opt_blub}; do…`.

**Comment by shachaf** [comment]
I think the confusion here is with how Kakoune interprets the echo command, not the strings it generates. In every case lists are encoded with each element surrounded in `'`s; adding special cases for integers seems to only make it harder to parse.

The commands that are being generated are:

```
echo '1' '2' '3'
echo ('1' '2' '3')
echo ( '1' '2' '3' )
```

In the case one, the arguments to echo are being parsed as these four strings: `"('1'" "2" "3" ")"`

If you want to echo a string exactly, you're probably better off escaping it (surround with `'`s and replace each `'` with `''`).

**Comment by fsub** [comment]
@shachaf Yes, I think there are multiple aspects involved. Quoting elements of integer lists seems to complicate interaction with the shell. For string lists, however, quoting seems to be necessary. So we need a way to deal with it. Example
```
eval %sh{ printf "echo \"(%s)\"\n" "${kak_opt_blub}" }
eval %sh{ printf "echo \"(%s)\"\n" "${kak_opt_blub//\'/}" }
eval %sh{ printf "echo \"(%s)\"\n" "$(eval echo ${kak_opt_blub})" }
```
yields
```
('1' '2' '3')
(1 2 3)
(1 2 3)
```
But this only works in simple cases. Given
```
decl str-list slist
set global slist "Item 'A'" "Item 'B'"
```
the commands
```
eval %sh{ printf "echo \"(%s)\"\n" "${kak_opt_slist}" }
eval %sh{ printf "echo \"(%s)\"\n" "${kak_opt_slist//\'/}" }
eval %sh{ printf "echo \"(%s)\"\n" "$(eval echo ${kak_opt_slist})" }
```
yield
```
('Item ''A''' 'Item ''B''')
(Item A Item B)
(Item A Item B)
```
How can I get the following?
```
("Item 'A'" "Item 'B'")
```
Is there a simple way to convert between kakoune and shell style quoting/escaping?

**Comment by shachaf** [comment]
This commit broke quoting for some types, e.g. line-specs (as used in clang.kak).

I wasn't a fan of making quoting different for int-lists because only makes it more irregular and harder to parse (and it doesn't solve the issue here anyway). But now quoting is off by default and opt-in for specific types, which is even more error-prone.
