### ISSUE TITLE
Adding a new key for appending without extending selection

### ISSUE THREAD

**Issue by yshui** [mawww/kakoune#2227]
Pressing 'a' will extend selection by 1 character and then enter insert mode, which can be useful at times, but might not always be what the user wants.

Can we have a key that just move the cursor to the right and enter insert mode, disregarding the selections?

**Comment by maximbaz** [comment]
Sure, it's very easy:

```
map global normal a '<a-:>li'
```

**Comment by yshui** [comment]
Yes, but can we have a key mapping like that by default? (Not mapped to 'a', of course).

**Comment by yshui** [comment]
@maximbaz Yes, but can we have a key mapping like that by default? (Not mapped to 'a', of course).

**Comment by maximbaz** [comment]
Do you want this purely for cosmetic reasons (to not see the selection while typing) or there is actually a real case where this will be useful? I can't speak for everyone, but right now this doesn't sound like something that would be useful for everyone, and it's very easy to configure locally.

**Comment by yshui** [comment]
@maximbaz Mainly cosmetic. Having the selection can be really annoying when you have code highlighting. There are scripts highlighting compilation errors and such, and I won't be able to see them if the code is selected.

**Comment by maximbaz** [comment]
I'll leave this for you and others to decide, but if I were you, I would just put this in local config and move on with life — there are more interesting things to do than convincing others to include your favorite key binding in the default distribution 😜 Cheers!

**Comment by yshui** [comment]
@maximbaz Indeed. I will do that, but I want to leave this issue open.

**Comment by mawww** [comment]
Free keys are a very scarce resource nowadays, and we already have more than enough default bindings to enter insert mode. I believe this should be user config, especially as the visual problem can be corrected another way (Make selection highlighting and error highlighting work nicely together, by using say underline for one and bg color for the other, or fg color for one and bg color for the other...)
