### ISSUE TITLE
set-register does not support empty argument list

### ISSUE THREAD

**Issue by fsub** [mawww/kakoune#2228]
### Steps 
```
set-register x
```
### Outcome 
```
error: 'set-register' wrong argument count
```
### Expected 
No error.

Use case: store a potentially empty list in a register and restore it later.

**Comment by lenormf** [comment]
I use `:reg / ''` regularly, and it's never caused any issues, is that what you're looking for? Semantically, not having a third argument is incorrect, so I think the error makes sense.

**Comment by fsub** [comment]
The [changelog](https://github.com/mawww/kakoune/blob/master/doc/pages/changelog.asciidoc) says:
> `set-register` now take an arbitrary number of parameters and sets the register to multiple strings. `%reg` expands to a list of strings.

My reading of this is that registers now behave like list options. `set-option` accepts zero arguments after the options's name:
```
declare-option int-list mylist
set-option buffer mylist
```
As far as I can see, `set-register x` should set register `x` to the empty list, and `set-register x ''` should set `x` to a list that contains exactly one element: the empty string.

My concrete use case:
```
evaluate-commands -draft -save-regs x %{
   set-register x %opt{extra_word_chars}
   set-option current extra_word_chars
   try %[ execute-keys <a-i>w:mark-word-impl<ret> ]
   set-option current extra_word_chars %reg{x}
}
```
This fails if `extra_word_chars` happens to be empty.
