### ISSUE TITLE
underscore is not allowed in face names

### ISSUE THREAD

**Issue by fsub** [mawww/kakoune#2229]
### Steps 
```
set-face global my_face red
```
### Outcome 
```
error: 'set-face' invalid face name 'my_face'
```
### Expected 
No error. From a user's perspective I don't see why this restriction is necessary.

**Comment by lenormf** [comment]
As far as I can remember, face names are either single lowercase words, or camel-case multiple words, e.g. `string`, `PrimarySelection` etc.

I don't think there's any specific reason why underscores are not allowed.
