### ISSUE TITLE
Buffer opened after running `:ctags-search` in `exec` isn't highlighted

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2231]
### Steps 

* open `commands.cc`
* select `add_face`
* run `exec %{: ctags-search<ret>}`

### Outcome 

The newly opened buffer isn't highlighted, even though the correct selection is made in it.

No errors in the debug buffer.

### Expected 

The newly opened buffer should be highlighted.

**Comment by shachaf** [comment]
This is because `exec` defaults to `-no-hooks` as of 24d8a58b0d8b1d5b72faa55910cc2caa27883149.

Similarly `exec i` behaves like `\i` -- I went through several of my `exec`s and added `-with-hooks` after that change.
