### ISSUE TITLE
:cd %sh{dirname ${kak_reg_percent}} bug

### ISSUE THREAD

**Issue by co-dh** [mawww/kakoune#2235]
### Steps 
open a file with a path, then
:cd %sh{dirname ${kak_reg_percent}}
### Outcome 
'cd' unable to change to directory ''/a/dir/with/extra/quote/'

### Expected 
expecting kak change to current directory of buffer file.
There is an extra single quote in the directory returned by dirname, which failed cd command.
The above code used work 1 month ago.

~

**Comment by lenormf** [comment]
From the changelog:

>  - the $kak_reg_* environment variable is now a list, $kak_main_reg_* provides the previous behaviour.

Use `$kak_main_reg_percent`.

**Comment by co-dh** [comment]
@lenormf  Thanks.
