### ISSUE TITLE
Info box is not sized correctly when tab characters are inserted

### ISSUE THREAD

**Issue by JJK96** [mawww/kakoune#2237]
Reproduce:

:info %sh{echo -e '\t\t\t\ttest'}

Expected result: 
Info box containing four tabs and the word 'test'

Actual result:
Info box contains only whitespace and the word 'test' is beyond the right edge.

**Comment by Delapouite** [comment]
The issue is about the `bubble_width` computation:

https://github.com/mawww/kakoune/blob/master/src/ncurses_ui.cc#L978-L979

```
StringView{"\t"}.column_length()
```
It returns `1` but it's not the room it takes when visually displayed.

**Comment by Delapouite** [comment]
A few places in the code have special handling for the tab char, like here in buffers.utils:

https://github.com/mawww/kakoune/blob/master/src/buffer_utils.cc#L25-L29

```
if (*it == '\t')
{
    col = (col / tabstop + 1) * tabstop;
    ++it;
}
```

**Comment by Delapouite** [comment]
This behavior is still reproducible after commit introducing `-markup` to info command:
https://github.com/mawww/kakoune/commit/cb1b03c0db91d85db3545a49f68d63fad0fe137c
