### ISSUE TITLE
allow multiline regexes in regions highlighter

### ISSUE THREAD

**Issue by lammermann** [mawww/kakoune#2247]
I'm trying to improve the asciidoc highlighter. Now I'm stuck with adding support for code blocks

### Steps 
When I add
```
add-highlighter shared/ regions -default content asciidoc \
  ...
  sh '^\[source, sh\]\.{3,}\n' '\n\.{3,}\n' '' \
  c '^\[source, c\]\n\.{3,}\n' '\n\.{3,}\n' '' \
  ...
```
the one for sh works but the one for c not (which spans more than one line). The same seems to apply if the closing regex spans more than one line.

### Outcome 

this highlights only sections like (not correct asciidoc syntax)

```
[source, sh]...............................................
my code
.........................................................
```

### Expected 

It should highlight sections like

```
[source, c]
...................................................
my code
..................................................
```

**Comment by mawww** [comment]
As much as I'd like to, the limitation of regions highlighter to a single line for each match is crucial for it to maintain reasonable performances. Knowing that matches never cross line boundaries means that we can update matches on lines that get modified while keeping all the other ones intact, avoiding a full reparse of the buffer at each modification.

I do agree it makes it hard to find a nice solution to the asciidoc highlighting problem, I'd love to find a way to have those properly parsed as a region, but making regions highlighter able to match accros line boundaries will be too costly.
