### ISSUE TITLE
Add a buffer flag system

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2248]
- Add `flag-buffer` command and `flag` alias.
- Add `-flag` switch to `evaluate-commands`, `execute-keys` and buffer-related commands.
- Add hooks on flags.
  We can imagine some hooks on flags, so that buffers could be customized per flag, as the built-in `scratch`, `debug` and `read-only` buffers.
  Or crazier, be used to replace the current file-type mechanism.

# Prototypes

```
flag-buffer [-add] [-remove] [-toggle] [!]<name-list>
```

```
evaluate-commands -flag [!][name-list] <commands>
```

```
execute-keys -flag [!][name-list] <keys>
```

Buffer-related commands:

- `buffer`
- `buffer-next`
- `buffer-previous`

# Examples

Delete all buffers not marked as important:

``` kak
evaluate-commands -flag ! important delete-buffer
```

Play a macro on marked buffers:

``` kak
execute-keys -draft -flag marked q
```

Search a C++ buffer:

``` kak
buffer -flag cpp █
```

Next buffer used for documentation:

``` kak
buffer-next -flag doc
```

Next buffer not marked as scratch or debug:

``` kak
buffer-next -flag ! scratch debug
```

**Comment by mawww** [comment]
How about:

```
declare-option str-list flags

evaluate-commands -buffer * %{
    evaluate-commands %sh{ echo $kak_opt_flags | grep -q my-flag || echo fail }
    ...
}
```

No need for yet another custom system for handling flags, just use the existing option system, hooks on options and shell expand to manage that. I suspect you can wrap that into a script to hide those implementation details.

**Comment by alexherbo2** [comment]
The `buffer-next` and `buffer-previous` commands could also benefit from flags.

# Examples

Next C++ buffer:

``` kak
buffer-next -flag cpp
```

Next buffer used for documentation:

``` kak
buffer-next -flag doc
```

Next buffer not marked as scratch or debug:

``` kak
buffer-next -flag ! scratch debug
```

**Comment by mawww** [comment]
Flags seems to be just a set of words, a str-list option (I might be nice and add a str-set option type if really needed) would do the trick. All those commands you suggest can be implemented already, how about just dropping the space before `-flag` ? (`:buffer-next-flag ...`).

BTW the last one is very ambiguous, as `debug` can be either a flag or a buffer name, and it would be surprising that the implicit `or` operator would take precedence over the `!` operator.

**Comment by alexherbo2** [comment]
https://github.com/alexherbo2/flag.kak
