### ISSUE TITLE
Colour Column 80

### ISSUE THREAD

**Issue by davidaciko** [mawww/kakoune#225]
Can we highlight column 80?

**Comment by mawww** [comment]
As of 9f1b129053f3f2f957746c7a0a35958da975fb6f you can now highlight column 80 with grey background using
```
:addhl column 80 default,rgb:404040
````

More usefully, the column is a string that gets interpreted as commands (%sh/%opt/%reg/%val are expanded), so if you have a `textwidth` option you could do:

```
addhl column '%opt{textwidth}' default,rgb:404040
```

**Comment by jpe90** [comment]
The command has changed; you now need to specify the group for the highlighter. You can add the following to your kakrc to accomplished what's described in the above comment.

```
declare-option int textwidth 80
addhl global/ column '%opt{textwidth}' default,rgb:404040
```

Then can override the default on a per filetype basis. The following will display the colorcolumn at line 72 in emails.

```
hook global WinSetOption filetype=mail %{
    set window textwidth 72
}
```

**Comment by Screwtapello** [comment]
Even better than inventing a new option, you can use the existing `autowrap_column` option, as [described in the wiki](https://github.com/mawww/kakoune/wiki/Highlighters#highlight-a-column). You don't have to enable autowrap mode, but if you do, you'll be able to see where the wrapping will occur.
