### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by co-dh** [mawww/kakoune#2251]
I noticed that after a few days use of Kak, it's memory (RES) increased to 440M.
There is no client. It stays the same after I close all buffers.
There must be memory leak somewhere. Can we run some C++ memory leak check ?

```
PID USER      PRI  NI        VIRT    RES      SHR S CPU% MEM%   TIME+  Command
3830  username    20   0  573M  440M  3620 S  0.0  0.2  1:10.11 kak -s foo

```

**Comment by lenormf** [comment]
Maybe you're seeing the symptoms of the leak fixed in 0d6e042 ?

**Comment by co-dh** [comment]
let me get the latest code.

**Comment by co-dh** [comment]
It lookes that 0d6e042 fixed it.
The resident memory stay around 7M the second.
