### ISSUE TITLE
Support large strings in info box

### ISSUE THREAD

**Issue by ul** [mawww/kakoune#2257]
At the moment, if content passed to `info` command doesn't fit window then info box is not displayed at all. It would be nice to show truncated content instead.

**Comment by Delapouite** [comment]
Other issue about markup and `info`: https://github.com/mawww/kakoune/issues/2552

**Comment by alexherbo2** [comment]
On [Termux] I don’t see what I’m typing with [LSP].

[Termux]: https://termux.com
[LSP]: https://github.com/ul/kak-lsp

**Comment by TeddyDD** [comment]
Infoboxes could be scrollable as well

**Comment by clad26** [comment]
@mawww Can you somehow make the info box scrollable?
