### ISSUE TITLE
n (next match) didn't added to jumplist

### ISSUE THREAD

**Issue by co-dh** [mawww/kakoune#2262]
### Steps 
search a word (foo), press n to find next match a few times, press c-o to jump back
### Outcome 
It jump back to the position before foo is searched
### Expected 
each position of foo should be in the jumplist.

**Comment by nuao** [comment]
Hi, in case you didn't know, there's a command `<a-n>` (move back to select the previous search match) if that helps you here.

I think the current system works well. Not storing each match avoids cluttering the jumplist with irrelevant matches that are just skipped over when using `n`, and we can still use `<a-n>` if we need to.

**Comment by mawww** [comment]
I think the current behaviour is better, for the reasons nuao explained. You can easily opt-in your preferred behaviour by remapping `n` to `<c-s>n` (`<c-s>` does an explicit push of current selections to the jump list).
