### ISSUE TITLE
"no such command" when running ':%sh{ echo echo tchou }'

### ISSUE THREAD

**Issue by atomrc** [mawww/kakoune#2263]
### Steps

(this example can be found in the `README` https://github.com/mawww/kakoune#41-basic-commands)

- Open Kakoune (latest version of `master` branch)
- type in `:%sh{ echo echo tchou }`
- press `enter` key

### Outcome

`no such command: 'echo tchou'`

### Expected

`tchou`

**Comment by alexherbo2** [comment]
It’s due to the recent breaking changes.

``` kak
evaluate-commands %sh(echo echo tchou)
```

**Comment by atomrc** [comment]
Awesome. Thanks for the fast reply @alexherbo2  :+1:
