### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by a-concerned-citizen** [mawww/kakoune#2267]
Ubuntu 16.04.1

    g++ -DKAK_DEBUG -D_GNU_SOURCE -I/usr/include/ncursesw -pedantic -std=gnu++14 -g -Wall -Wextra -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -MD -MP -MF .commands.debug.d -c -o .commands.debug.o commands.cc
    commands.cc: In instantiation of ‘auto Kakoune::{anonymous}::map_key_completer<false>’:
    commands.cc:1548:5:   required from here
    commands.cc:1501:13: error: use of ‘Kakoune::{anonymous}::map_key_completer<false>’ before deduction of ‘auto’
     static auto map_key_completer =
                 ^
    commands.cc: In instantiation of ‘auto Kakoune::{anonymous}::map_key_completer<true>’:
    commands.cc:1581:5:   required from here
    commands.cc:1501:13: error: use of ‘Kakoune::{anonymous}::map_key_completer<true>’ before deduction of ‘auto’
    cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
    cc1plus: warning: unrecognized command line option ‘-Wno-unknown-attributes’
    cc1plus: warning: unrecognized command line option ‘-Wno-noexcept-type’
    Makefile:86: recipe for target '.commands.debug.o' failed
    make: *** [.commands.debug.o] Error 1

I don't know shit about C++, but given the line numbers I'm guessing this has to do with https://github.com/mawww/kakoune/commit/2c9daf2378c6d794ea01c9da2b02b42e3faca09e

This is just a driveby from some random wanting to try kak on a whim, will probably not follow up.

**Comment by a-concerned-citizen** [comment]
Yeah built just fine with https://github.com/mawww/kakoune/commit/f8198b3022ecea707ca595eff88cf45efc0c9566 in same environment

**Comment by lenormf** [comment]
Try building with `g++` v6.

@mawww Travis now depends on `g++` v6, have the minimal requirements changed since that merged PR? If so, we should update the README.
