### ISSUE TITLE
Regex engine: documentation inconsistency

### ISSUE THREAD

**Issue by MarSoft** [mawww/kakoune#2271]
In the `README.asciidoc` there is a phrase:
> The regex syntax supported by Kakoune is the Perl one and is described here [Regex syntax].
> -- (section 3.13, Multi Selection)

But in the [Regex syntax] paragraph (7.5) it is told that Kakoune uses ECMAScript syntax (ECMA-262 standard).

For me it looks like the above phrase about Perl syntax is outdated. I would make a PR but am not sure if it is mentioned somewhere else and if the `README.asciidoc` file is possibly generated from something else.

**Comment by ekie** [comment]
hi,
you are correct, this part of the README is outdated. A quick search reveals another mention in contrib/TRAMPOLINE . Go for the PR. Note the wording that the implementation is based on ECMA-262
since kakoune already deviates from the standard.
