### ISSUE TITLE
Fix comment char in *.conf files

### ISSUE THREAD

**Issue by maximbaz** [mawww/kakoune#2272]
Since https://github.com/mawww/kakoune/pull/2246/ all my *.conf files started having a wrong comment char when I use `:comment-line`: `;` instead of `#`. This happened because `.conf` is now considered a systemd file bound to `ini` filetype.

There are no rules as to how `*.conf` file is formatted, some use `ini` style, some don't. But one thing I know is that all of them use `#` as a comment char.

I'm not sure how this should be handled.

`nvim` has a dedicated `conf` syntax, maybe that's what we should do.

We could also just force `#` for all `ini` files by removing `|ini` from this line, since we bound so many different file types to `ini`:

https://github.com/mawww/kakoune/blob/1c0cc61ccc1e9bdbfbe3bafb1d2470f38f2fe21b/rc/core/comment.kak#L52-L54

This is what I did locally.

@lenormf what do you think?

-----------

Some of `.conf` files from my own dotfiles:

| file | looks like `ini` | comment char | contents | syntax detected by my `nvim` |
|-|-|-|-|-|
| `.tmux.conf` | no | `#` | full-blown tmux commands | `tmux` |
| `compton.conf` | yes | `#` | equals-separated entries with semicolon | `conf` |
| `.i3status.conf` | no | `#` | kinda like ini, but has `{}` blocks and `+=` | plain text |
| `gpg.conf` | no | `#` | gpg commands | `gpg` |
| `pacman.conf` | yes | `#` | normal `ini` file | `conf`|

**Comment by mawww** [comment]
I think `systemd.kak` should not detect every .conf files as systemd config files, it should have a stricter matching rule.

**Comment by maximbaz** [comment]
That's probably the best option, considering how different all these `.conf` files are. Let's just not make the rule too strict — assuming all systemd rules will be equally strict, I would for example like the file under this location still to be highlighted as `service`: `~/.dotfiles/etc/systemd/system/reflector.service`.

**Comment by maximbaz** [comment]
Actually, this won't be enough. Looking at some files in `/etc/systemd`, the expected comment char is `#` there as well.

**Comment by lenormf** [comment]
I didn't think about that, I think we could add `.*/systemd/.*` in the pattern of the hook in `systemd.kak`, all the `.conf` files within that directory are guaranteed to use the INI syntax.
