### ISSUE TITLE
Question: [linting] add file extension to the temporary file

### ISSUE THREAD

**Issue by atomrc** [mawww/kakoune#2283]
Hey guys,

I was wondering if it could be a good idea to add the file extension to the tmp file we try to lint?

The problem I have right now is with `eslint` and the `prettier` plugin. Since this one uses the file extension to guess which parser it should use, I cannot lint my files in kakoune. (I am basically running into this issue https://github.com/prettier/prettier/issues/4759)

Would it make sense for kakoune to add the file extension on the temporary file that will be linted?
Here probably https://github.com/mawww/kakoune/blob/1c0cc61ccc1e9bdbfbe3bafb1d2470f38f2fe21b/rc/base/lint.kak#L23

I'd be happy to create a PR is you guys think it is a good idea.

Let me know

**Comment by Delapouite** [comment]
Hi. Isn't that the case with this recent commit: https://github.com/mawww/kakoune/commit/eee0035a0fb8b98105d89c1ccbcbda897ce53def ?

**Comment by atomrc** [comment]
Oh yeah true @Delapouite this commit should actually do that :) I'll try with a fresh version then :+1: 

@maximbaz yes `prettier` is a formatter but there is also a `eslint` plugin that exists https://github.com/prettier/eslint-plugin-prettier

I have no problem with the formatting part, only the linting is a problem here. But, anyway, I didn't know about the `--stdin-filepath` option and it's definitely a good one, so thanks for that :)

**Comment by atomrc** [comment]
Hummm so, this did fix a few issues I had, but not all of them.
Now `eslint-plugin-prettier` can detect the filetype, that part is cover.
Thing is, because the file is in the `tmp` dir and not in the project, then the `.prettierrc` file cannot be read, thus the config for `prettier` are not applied (and because we are not reading from `stdin` for linting, I cannot use the `--stdin-filepath` option and I am not even sure it will be forwarded to `prettier` anyway)

**Comment by atomrc** [comment]
Will close the issue though, because https://github.com/mawww/kakoune/commit/eee0035a0fb8b98105d89c1ccbcbda897ce53def actually fixes my first report :)

**Comment by maximbaz** [comment]
@atomrc you can try to cheat with something like this (not tested):

```
set-option buffer lintcmd 'run() { cat "$1" | prettier --stdin-filepath "$kak_buffile" } && run'
```

**Comment by atomrc** [comment]
I could try that, but first I need to be sure that `eslint` will forward the `--stdin-filename` to the `eslint-plugin-prettier`. Else it won't work (`prettier` wont find the `prettierrc` file).

Basically what is happening is:

- I call `eslint` (say with the `--stdin*` options)
  - `eslint` calls `prettier` (not sure if the `--stdin*` options will be forwarded?)

I don't call `prettier` directly for linting

**Comment by maximbaz** [comment]
I see, I'm actually curious what are the reasons for lint.kak to copy file to a temp dir, why not just execute the `lintcmd` directly on `$kak_buffile` in the project root? @lenormf, @mawww do you know/remember?

**Comment by SolitudeSF** [comment]
because it copies the content? so you could run lint not only on save.

**Comment by maximbaz** [comment]
Heh, good point

**Comment by atomrc** [comment]
Good point indeed. But then linting from `stdin` could also solve that (but not sure what could be the other side effects of this).

**Comment by maximbaz** [comment]
It doesn't really matter if kakoune itself passes the buffer on stdin or as a temp file, you can always locally convert to one or another way, e.g. like I showed earlier: https://github.com/mawww/kakoune/issues/2283#issuecomment-410201251

**Comment by atomrc** [comment]
Won't the command fails because `lint.kak` is adding a bunch of other params to the command run (https://github.com/mawww/kakoune/blob/1c0cc61ccc1e9bdbfbe3bafb1d2470f38f2fe21b/rc/base/lint.kak#L39)

Might work but seems pretty hacky to me. If some additions are made to the `lint.kak` file it might very well break

**Comment by maximbaz** [comment]
I think it will work just fine, the basic building block is `eval $cmd $file`, piping and the rest is just post-processing, even if it ever changes, your command will keep working.

**Comment by atomrc** [comment]
Will try that soon then. Thanks

**Comment by atomrc** [comment]
@maximbaz so, you suggestion worked out of the box!! Impressive :D 
Thanks
