### ISSUE TITLE
Block Selection

### ISSUE THREAD

**Issue by edenkl8** [mawww/kakoune#2285]
Hi :)
A few days ago I discovered kakoune and I like it very much.
Just wanted to ask if there is a block selection like vim's <c-v>?
It would be a LOT of help in lots of cases for multiple selections.

Thank you :)

**Comment by ekie** [comment]
hello,

does `C` and `<a-C>` fit your use case?

**Comment by mawww** [comment]
Yep, `C` and `<a-C>` are the closest Kakoune will provide to Vim's block selections, they are not strictly the same, but should be good enough for most use cases.

**Comment by edenkl8** [comment]
What does <a-C> do?
<a-c> does what seems to be just like c
And <a-C> seems to not do anything.

**Comment by mawww** [comment]
`<a-C>` copies the selection "geometry" on the previous line, `C` copies it to the next line. You might have tried `<a-C>` with a selection on the first line of the buffer if you did not see any effect.
