### ISSUE TITLE
regex problems with add-highlighter .. regex

### ISSUE THREAD

**Issue by cduret** [mawww/kakoune#2289]
I have noticed many regex do not catch highlighting with add-highlighter .. regex

### Steps
One example is in base/lisp.kak :

line 21 :  add-highlighter shared/lisp/code/ regex \b(([':]\w+)|([*]\H+[*]))\b 0:variable

### Outcome
the quote symbol is never highlighted as a variable in lisp code.

**Comment by cduret** [comment]
got it thanks

**Comment by lenormf** [comment]
I think you could leave this issue open, until a PR is made that addresses your problem.

**Comment by lenormf** [comment]
Could you give #2300 a try, see if it fixes your problem please?
