### ISSUE TITLE
Use a register's value set in a client from another

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2295]
### Steps 

* open two clients on the same file
* `:exec -client client0 <a-*>; exec -client client1 n`

### Outcome 

An error is printed `'exec' no search pattern`

### Expected 

The value of the register set by `client0` is used immediately by `client1`.

**Comment by lenormf** [comment]
The error is `no such pattern` when the search register is originally empty, but if it's already set the error will be `no matches found: …`.

**Comment by mawww** [comment]
This is just the register saving kicking in, `exec -save-regs '' -client client0 <a-*>; exec -client client1 n` works.

**Comment by lenormf** [comment]
Sigh.
