### ISSUE TITLE
[CODE] Highlight significant digits in non-decimal literals, etc

### ISSUE THREAD

**Issue by davidaciko** [mawww/kakoune#230]
I wouldn't know where to put this (rather, I don't know which programming languages besides [Obj]C[++] support C-like hex/octal literals) or else I'd just make a pull request, but I made some helpful regex if you're interested:

```
face value red
face signif red+b
# Highlight significant hex digits:
addhl regex "(\<|[+-]\s*)(0[Xx])(0*)(0|[1-9A-Fa-f][0-9A-Fa-f]*)([Uu]?[Ll][Ll]?\>|[Ll]{0,2}[Uu]\>|\>)" 1:value 2:value 3:value 4:signif 5:value
# Highlight significant octal digits:
addhl regex "(\<|[+-]\s*)(0)(0*)(0|[1-7][0-7]*)([Uu]?[Ll][Ll]?\>|[Ll]{0,2}[Uu]\>|\>)" 1:value 2:value 3:value 4:signif 5:value
```

They highlight like this by default:
-0x00123e0ull => -0x00 **123e0** ull
+0003710LL => +000 **3710** LL
0x0f => 0x0 **f**
But you can tweak which parts get highlighted by changing the parameters (you shouldn't need to modify the regex).  For example, if you want it highlighted like this instead:
-0x00123e0ull => - **0x** 00 **123e0** ull
+0003710LL => + **0** 00 **3710** LL
0x0f => **0x** 0 **f**
Then just change `2:value` to `2:signif`.  The capture groups are:
0: The entire number.
1: The sign (_eg_ `-`)
2: The base specifier (_eg_ `0x`)
3: Leading zero padding
4: The significant part of the number, or the single final zero if whole number is zero
5: The literal suffix (_eg_ `ull`)

**※ No backtracking whatsoever in case kakoune switches to a finite-state regex engine in the future.**
- Don't want `+` highlighted?  Change the first capture group from `(\<|[+-]\s*)` to `(\<|-\s*)`.
- Don't want the sign highlighted unless it's touching the number?  Change it to `(\<|[+-])`
- `+` has to touch the number but `-` can have spaces?  Change it to `(\<|-\s*|\+)`

**Comment by JJK96** [comment]
I think this issue can be closed, this is not the place for sharing code snippets/ plugins. Maybe it could be added to the wiki if it still works on the latest version.

**Comment by mawww** [comment]
Yep, closing, btw we are now usinga a non backtracking regex engine ;)
