### ISSUE TITLE
Alt in combination with other modifier keys can cause problems

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2310]
I've searched over open and closed issues, and these are quite similar: https://github.com/mawww/kakoune/issues/998, https://github.com/mawww/kakoune/issues/1016. However I didn't find anything about this situation.

One of the most spread way of changing keyboard layouts is <kbd>Alt</kbd>+<kbd>Shift</kbd> (Thanks Microsoft). Apple has its own way <kbd>cmd</kbd>+<kbd>space</kbd>. Linux distros, BSDs, and others mostly depend either on some defaults for desktop environment, like Gnome's <kbd>win</kbd>+<kbd>space</kbd>), or user configuration. Since I used windows for long time (1995-2008, and still game on it sometime) I've used default <kbd>Alt</kbd>+<kbd>Shift</kbd> combination since 1995 in all my desktop environments.

Why does this matter? I'm pretty long `(Neo)?Vim` user, and never before encountered modifier overlaps in it. However in Kakoune I actually did. Since some actions require both <kbd>Alt</kbd> and <kbd>Shift</kbd> pressed, like `<a-)>` is actually 3 keys: <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd>, I can't execute it, because input language changes on <kbd>Alt</kbd>+<kbd>Shift</kbd> press. I'm not sure why it is so, because `9` and `0` are not changing in both layout, but maybe DE steals those keys, or focus from kakoune, and gives it back after layout change. <kbd>Alt</kbd>+<kbd>\`</kbd> is default in my DE (KDE) to switch windows of active application and so on. 

So far I've encountered problems with these shortcuts:

Requires <kbd>Shift</kbd>:  
- <kbd>Alt</kbd>+<kbd>X</kbd>
- <kbd>Alt</kbd>+<kbd>?</kbd>
- <kbd>Alt</kbd>+<kbd>N</kbd>
- <kbd>Alt</kbd>+<kbd>:</kbd>
- <kbd>Alt</kbd>+<kbd>O</kbd>
- <kbd>Alt</kbd>+<kbd>P</kbd>
- <kbd>Alt</kbd>+<kbd>R</kbd>
- <kbd>Alt</kbd>+<kbd>J</kbd>
- <kbd>Alt</kbd>+<kbd><</kbd>
- <kbd>Alt</kbd>+<kbd>|</kbd>
- <kbd>Alt</kbd>+<kbd>!</kbd>
- <kbd>Alt</kbd>+<kbd>U</kbd>
- <kbd>Alt</kbd>+<kbd>&</kbd>
- <kbd>Alt</kbd>+<kbd>@</kbd>
- <kbd>Alt</kbd>+<kbd>)</kbd>
- <kbd>Alt</kbd>+<kbd>"</kbd>
- <kbd>Alt</kbd>+<kbd>(</kbd>
- <kbd>Alt</kbd>+<kbd>Z</kbd>
- <kbd>Alt</kbd>+<kbd>*</kbd>
- <kbd>Alt</kbd>+<kbd>S</kbd>
- <kbd>Alt</kbd>+<kbd>C</kbd>
- <kbd>Alt</kbd>+<kbd>K</kbd>

Reserved by my DE by default:  
- <kbd>Alt</kbd>+<kbd>`</kbd> - scroll through active application windows
- <kbd>Alt</kbd>+<kbd>space</kbd> - global search

I understand the choice of <kbd>Alt</kbd> as a primary key for actions, since it is easily accessible with left  thumb, but I just feel that as it is widely spread in various desktop environments as a default key for some actions, using it with another modifier keys should be avoided.

I've seen that previously swapping contents of selections were done with <kbd>Alt</kbd>+<kbd>'</kbd> shortcut, which doesn't involve pressing <kbd>Shift</kbd> key, but not it is changed to weird <kbd>Alt</kbd>+<kbd>)</kbd>. I don't know was it intentional, but seems like old one isn't used when selection is active, although executing a <kbd>Alt</kbd>+<kbd>"</kbd> would still require <kbd>Shift</kbd>.

I know that I can fix this issue by simply changing my layout switch combination to something different, like <kbd>Ctrl</kbd>+<kbd>space</kbd>, but again, Vim doesn't have such problems, and I think that there are more shortcuts.

About keyboards...

![image](https://user-images.githubusercontent.com/19470159/44264668-06bb5080-a22c-11e8-8860-bd9cbd8eac2a.png)

As you can see, I was quite limited in DE shortcuts, since I use keyboard manufactured in1984, and It has no win button, and most DE shortcuts use win (move, resize window, etc). So I've swapped <kbd>CapsLock</kbd> and <kbd>Ctrl</kbd>, and <kbd>Ctrl</kbd> with <kbd>Win</kbd>. So now my <kbd>Win</kbd> key is actually a <kbd>CapsLock</kbd>, and since it doesn't exist, **I NEVER USE CAPSLOCK** (sorry, I couldn't resist). Any way, my layout looks like so:
```
┢━━━━━━━━━━━┓
┃           ┃
┃           ┃
┃ Tab       ┃
┣━━━━━━━━━━━┻━┓
┃             ┃
┃             ┃
┃ Ctrl        ┃
┣━━━━━━━━━┳━━━┛
┃         ┃
┃         ┃
┃ Shift   ┃
┣━━━━━━━━━┻┳━━━━━━━━━━┳━━━━━━━━━┓
┃          ┃          ┃         ┃
┃          ┃          ┃         ┃
┃ Win      ┃ Nothing  ┃ Alt     ┃
┗━━━━━━━━━━┻━━━━━━━━━━┻━━━━━━━━━┛
```

I have more comfortable usage of <kbd>Ctrl</kbd>, and since most of Vim's shortcuts use either <kbd>Ctrl</kbd> or <kbd>Shift</kbd>, I did them mostly with my pinky finger.
There are also users of [75% keyboards](https://duckduckgo.com/?q=75%25+keyboard&t=ffab&iax=images&ia=images) which usually have less keys, and can involve usage of extra <kbd>Fn</kbd> key to reach some buttons. It's rare, but it's exist.

So my point is, that shortcuts that use modifiers, should be avoided, if another modifier is required. There is nothing can be done about system default shortcuts, like <kbd>Alt</kbd>+<kbd>`</kbd> from kakoune side, but not using alt and shift together can be avoided - it is harder to execute because it uses 3 fingers, and it can cause conflicts, since these are one of the most common modifier combination. Or if we could chose modifier to use Ctrl for example, this could solve some problems. However It still will involve combining two modifier keys, and I know many people who use <kbd>Ctrl</kbd>+<kbd>Shift</kbd> to switch layout, so this will be still a workaround.

Also It's likely that there are a typo in doc:
https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc
![image](https://user-images.githubusercontent.com/19470159/44264336-db843180-a22a-11e8-8cd9-aeb81d54d6f8.png)

**Comment by maximbaz** [comment]
Just a small note, <kbd>Ctrl+Shift</kbd> is usually a modifier for terminal emulator itself, meaning that <kbd>Ctrl+Shift+\<key\></kbd> will not be passed to applications running in the terminal at all.

Personally I was also using <kbd>Alt+Shift</kbd> to switch layouts for a long time, but recently I finally gave up and changed my shortcut to be <kbd>Shift+Shift</kbd>.

**Comment by andreyorst** [comment]
>Just a small note, <kbd>Ctrl+Shift</kbd> is usually a modifier for terminal emulator itself, meaning that <kbd>Ctrl+Shift+<key></kbd> will not be passed to applications running in the terminal at all.

Now that you said it I'm trying to remember if I ever pressed <kbd>Ctrl</kbd>+<kbd>Shift</kbd> in Vim. Probably not, but I use it for pasting with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd>, so I assume you right, and it will not work in Vim as a shortcut.

> Personally I was also using <kbd>Alt+Shift</kbd> to switch layouts for a long time, but recently I finally gave up and changed my shortcut to be <kbd>Shift+Shift</kbd>

Yeah, I did it too, to <kbd>win(ctrl)</kbd>+<kbd>Space</kbd>, but the whole point was, that in vim there were no need for such workaround, and it sounds to me as a sort of design flaw of Kakoune. I think that there is no situation where you need more than one modifier in Vim.

# 

A small note on keyboards in general, looking at [doc/keymap](https://github.com/mawww/kakoune/blob/master/doc/keymap), I can see extra key, to the left of <kbd>Z</kbd> which is not part of my keyboard, since I use ANSI104 standard (and pretty much in our country), and this key commonly exist on ISO 105. I'm not sure how this key is used, since it can contain both <kbd><</kbd><kbd>></kbd> or <kbd>\`</kbd><kbd>~</kbd> on different models.

**Comment by andreyorst** [comment]
> To be fair to this editor, using modifier keys was a design choice and kakoune is built around this idea. Just like it's incorrect to say that emacs is flawed by design because it requires more modifier keys contrary to vim

I agree, and it's not about comparison to vim, it's just about the fact that usage of more than one modifier at the same time isn't great choice, because:

  - most modifier key combinations are widely used and known by nearly everyone for a very long time, like for example <kbd>Alt</kbd><kbd>Shift</kbd> or <kbd>Alt</kbd><kbd>Tab</kbd> (latter isn't used, however it could be, because why not), and users often rely on those, so editor shouldn't force to redefine them, like I did with layout change shortcut in order to use these features
  - using combinations of modifiers can me really awkward, like with <kbd>Alt</kbd><kbd>Shift</kbd><kbd>z</kbd>, when your left hand clutters to the bottom corner, or with <kbd>Alt</kbd><kbd>Shift</kbd>+<kbd>5</kbd> or <kbd>6</kbd> when you need to stretch your index finger with bent thumb and busy pinky, which is not really comfortable either, but *not violates* the rules of touch typing.

Don't get me wrong, I enjoy kakoune and I do not mean that it should be similar or act exactly like vim. I've updated the set of keybindings that require <kbd>Shift</kbd> in the top comment, and it is pretty huge, so, for me it seems that it just lacks one more `mode`, that will redefine most of keys, like in vim, but will make possible to not use extra <kbd>Shift</kbd> dependency.

**Comment by maximbaz** [comment]
By the way, you can create this mode yourself, try this 😉 

```
declare-user-mode shift
map global shift <a-n> '<a-N>' -docstring 'select previous match'
map global shift <a-k> '<a-K>' -docstring 'keep not matching'
...
map global normal '<space>' ':enter-user-mode shift<ret>'
```

**Comment by andreyorst** [comment]
now that's the power! I'll try this as soon as possible

**Comment by andreyorst** [comment]
Turns out that this isn't as comfortable as default mappings, so I'd stick with different layout changing shortcut for now. If I'll come with different thought about this kinda problem, I'll reopen this issue.
