### ISSUE TITLE
How do I view the current value of an option?

### ISSUE THREAD

**Issue by henrebotha** [mawww/kakoune#2320]
I've done my best to find a command that lets me see the value of an option, but no dice. If there is no such feature, that seems like a pretty glaring omission.

**Comment by henrebotha** [comment]
Perfect, thank you! Perhaps we should add this to `:doc options`?

**Comment by lenormf** [comment]
If the option's value is particularly long, or if you have a narrow terminal, you can also use `:echo -debug %opt{…}` and read the value directly from the `*debug*` buffer.
