### ISSUE TITLE
Cannot set filetype from command line args

### ISSUE THREAD

**Issue by henrebotha** [mawww/kakoune#2326]
### Steps

1. In gitconfig, set `core.pager = kak -e "set buffer filetype diff"`.
2. In any Git repo with unstaged changes, do `git diff`.

### Outcome

Kakoune opens the diff with no highlights, and gives an error:

```
1:1: 'set' wrong argument count
```

The same happens regardless of whether we use `current`, `buffer`, `window`, or `global`.

### Expected

Kakoune opens the diff and highlights it.

---

This doesn't surprise me too much; I suspect it might have something to do with the order in which things are executed on startup (perhaps `buffer` is blank at the time it is referenced, resulting in the actual command being `set filetype diff`).

**Comment by maximbaz** [comment]
Try single quotes, `kak -e 'set buffer filetype diff'`, I still see some escape codes but at least filetype is being set correctly.

**Comment by henrebotha** [comment]
Ah, silly! Thanks. (The escape codes thing is an issue with using Vim as pager too, but easily fixed by setting `color.pager = false`.
