### ISSUE TITLE
Problem with using options in sh expansions

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2328]
I'm writing [plugin manager](https://github.com/andreyorst/plug.kak) somewhat similar to vim-plug, that will load plugin files recursively for plugins specified in any particular Kakoune config file. Right now it can asynchronously download and update plugins from GitHub, and clean plugins that were downloaded, but not presented in any config file.

However I've encountered a weird issue with using options in `%sh{` expansions, consider making a directory:
```sh
if [ ! -d /path/to/plugin_install_dir ]; then
    mkdir /path/to/plugin_install_dir
fi
```
I would like to set this path in option, so user could configure where plugins should be installed, so I declare an option like so:
```kak
declare-option -docstring "path where plugins should be installed" \
    str plug_install_dir '$HOME/.config/kak/plugins'
```
Now user may change it, and my plugin should respect it, so I change previous `mkdir` part to:
```sh
if [ ! -d $kak_opt_plug_install_dir ]; then
    mkdir $kak_opt_plug_install_dir
fi
```
And turns out that this doesn't work as expected, resulting to weird info in `*debug*` buffer:
```
shell stderr: <<<
mkdir: cannot create directory ‘$HOME/.config/kak/plugins’: No such file or directory
>>>
```
I've tried manually creating an option in cmdline, and evaluating a simple `nop` followed by shell expansion:
```
:declare-option str path '$HOME/.config/kak/plugins'
:nop %sh { mkdir $kak_opt_path }
```

Still the same error. I'm not sure what causing it, but I've managed to find a workaround:
```
:nop %sh { mkdir $(eval echo $kak_opt_path) }
```
This actually works, but I'm avare of portability, and it feels like a bug for me. The resulting code of making a dir would be:
```sh
if [ ! -d $(eval echo $kak_opt_plug_install_dir) ]; then
    mkdir $(eval echo $kak_opt_plug_install_dir)
fi
```
Is this intended to be like so, and should be documented, or is it a bug with using options in shell expansions?

**Comment by Screwtapello** [comment]
Normally, when you execute a command like:

    mkdir -p $HOME/.config/kak/plugins

...the shell expands `$HOME` and then actually executes:

    mkdir -p /home/andreyorst/.config/kak/plugins

...or whatever your `$HOME` is set to.

When you tell Kakoune to execute something like:

    set global plug_install_dir $HOME/.config/kak/plugins
    nop %sh{ mkdir -p $kak_opt_plug_install_dir }

...it sets the environment variable and invokes the shell with your command:

    mkdir -p $kak_opt_plug_install_dir

...which the shell expands to:

    mkdir -p $HOME/.config/kak/plugins

...and executes, producing the error you see. Specifically, the shell does *one* round of variable expansion (expanding `$kak_opt_plug_install_dir`) but it doesn't *repeat* the variable expansion step—that's just not how the shell is designed to work. You can manually force it to apply another layer of expansion with `eval`, as you've discovered, but that's not a great idea: each additional layer of `eval` means the user has to apply an additional layer of quoting to protect special characters in the option.

I recommend you define your option like this:

    declare-option -docstring "path where plugins should be installed" \
        str plug_install_dir "%val{config}/plugins"

That way, the default value will be expanded by Kakoune at the time the option is defined, instead of making the shell re-expand the value every time the option is used. Also, Kakoune already handles the situation where `$XDG_CONFIG_DIR` is not set to `$HOME/.config`, so your default will be even more correct.

**Comment by andreyorst** [comment]
The main point is that user may set option for example to `$HOME/.cache/kak_plugins` or `~/Git/kak_plugins`, etc. It is not associated with config folder at all, so handling proper expanding of variables should be expected behaviour, and using `$(eval echo $kak_opt_name)` to get actual value to be passed to command feels like hack.

>When you tell Kakoune to execute something like:
>```
>set global plug_install_dir $HOME/.config/kak/plugins
>nop %sh{ mkdir -p $kak_opt_plug_install_dir }
>```
>...it sets the environment variable and invokes the shell with your command:
>```
>mkdir -p $kak_opt_plug_install_dir
>```
>...which the shell expands to:
>```
>mkdir -p $HOME/.config/kak/plugins
>```

I understand that shell doesn't recursevly expand variables, and does it only once, but I think that kakoune should send actual contents of options when interpreting shell commands, so when I ask Kakoune to use option in shell, Kakoune should be avared that shell will not expand content's of option.

Using absolute path as a workaround isn't good idea, since people who share same config over several PCs may struggle since username may differ.

>I recommend you define your option like this:
>```
>declare-option -docstring "path where plugins should be installed" \
>    str plug_install_dir "%val{config}/plugins"
>```
>That way, the default value will be expanded by Kakoune at the time the option is defined, instead of making the shell re-expand the value every time the option is used. Also, Kakoune already handles the situation where $XDG_CONFIG_DIR is not set to $HOME/.config, so your default will be even more correct.

I don't quite get how this will work in case when user sets the option `plug_install_dir` to `$HOME/somepath` from the kakrc file

**Comment by andreyorst** [comment]
IIUC I can do this:
```sh
if [ ! -d %val{plug_install_dir} ]; then
    mkdir %val{plug_install_dir}
fi
```
right?

**Comment by alexherbo2** [comment]
**1**

``` kak
set-option global plugins "%val(config)/plugins"
```

**2**

``` kak
set-option global plugins "%val(client_env_XDG_CONFIG_HOME)/kak/plugins"
```

**3**

``` kak
set-option global plugins "%val(client_env_HOME)/.config/kak/plugins"
```

**Comment by andreyorst** [comment]
I still don't get how does this connect to my willing of handling expansion of option inside the plugin manager code which I do currently with weird `$(eval echo $kak_opt_plug_install_dir)`, and not at user side?
Keeping in mind that you need to use expansions when you set a simple path option is tedious, I know that typical user would like to use the easiest way as possible to have universal path to homedir on every machine, such as `~/` or `$HOME/`

**Comment by andreyorst** [comment]
I've checked that this `eval` trick works fine in dash, and ash, and generally a [posix compatible](https://www.unix.com/man-page/posix/1posix/eval/), therefore I'd stick with it for now, since it doesn't bring any undefined behavior to path handling if no expandable variables contained in the string.

**Comment by andreyorst** [comment]
@alexherbo2 there's no `path` type described in the [doc/options](https://github.com/mawww/kakoune/blob/master/doc/pages/options.asciidoc), and there's no actual type `path` in kakoune. Only an option `path`:

```
path str-list
    default ./:%/:/usr/include
    directories to search for gf command and filenames completion %/ represents the current buffer directory 
```

**Comment by alexherbo2** [comment]
It was a suggestion for a new type option.

**Comment by andreyorst** [comment]
Path is essentially a string. Having a separate type for a strings that contains paths exclusively isn't a generally good idea, since it will lead to segmentation in generally same type of options. And it is about variables in general, not just path variables, so there's needed different method of handling options in `%sh{` expansions.

I think that when Kakoune interpreters shell expansions It should just substitute `$kak_opt_variables` to their actual values before execution.

**Comment by andreyorst** [comment]
>Kakoune does set $kak_opt_variables to their actual values before execution, it's just that Kakoune doesn't expand shell-variables either - if you put a dollar-sign in a Kakoune option, it will make it through to wherever it needs to be, unscathed.

In the last message I mean that Kakoune should instead of setting `$kak_opt_variables` *for shell*, use substitution and replace actual `$kak_opt_variables` with actual value *in the code* before execution. Something similar to preprocessor in C - we can `#define VAR` to something, but it is just substitutions and no real `VAR` exists anywhere except the text of the program.

Because what essentially happens when you do `declare-option str home '$HOME'` is:
```sh
$ kak_opt_home=\$HOME
$ echo $kak_opt_home
$HOME
$ eval echo $kak_opt_home
/home/andreyorst
```
Ideally It would be great if Kakoune acted like shell acts when we assign variables:
```sh
$ kak_opt_home=$HOME
#$HOME gets expanded
$ echo $kak_opt_home
/home/andreyorst
```
But since Kakoune doesn't expand shell variables, preprocessor like substitution will be easier to do I think.

**Comment by alexherbo2** [comment]
@Screwtapello I don’t support expanding environment variables through the `path` type option either.

**Comment by alexherbo2** [comment]
@andreyorst A `path` type option would be transparent from the user point and rather obvious in intent when you write the extension though.

**Comment by andreyorst** [comment]
> A path type option would be transparent from the user point and rather obvious in intent when you write the extension though.

A `shell` type would be more general purposed then. Since not only path can be expanded, but variables of any kind, including path variables

**Comment by alexherbo2** [comment]
I don’t think a `shell` can be considered as a type…

**Comment by andreyorst** [comment]
Why not? It is a string that should be interpreted by the shell directly, without nesting it in another variable.

**Comment by andreyorst** [comment]
The more code I see using `eval` makes me feel like it is normal way. Closing
