### ISSUE TITLE
Make :change-directory back to server’s working directory by default

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2342]
How about `:change-directory` with no argument returning to the session’s directory (instead of home).

That is useful when you enter in a project, then change to a sub-directory to just `:change-directory` to return to the root project.

**Comment by mawww** [comment]
There is no such thing as the "server working directory", or, put another way, the "server working directory" is the only current directory in Kakoune, `:change-directory` changes the *server* process CWD, client processes CWD are irrelevant and not used anywhere.

**Comment by lenormf** [comment]
Populate an option in the `KakBegin` hook, which will be `cd`'d to from another command that you've declared.

**Comment by alexherbo2** [comment]
@mawww Initial working directory, the value that was when Kakoune started.

**Comment by Delapouite** [comment]
@alexherbo2  This is the function I use:
```
# only works for git now, use `hg root` for mercurial
define-command change-directory-project-root -docstring 'cd to project root dir' %{ %sh{
  project_root=$(git rev-parse --show-toplevel)
  echo "cd $project_root"
}}
```

**Comment by occivink** [comment]
What I do is drop an `init.kak` file at the root of my projects. It contains project-specific variables and commands, and gets loaded automatically by my kakrc with this snippet: 
```
hook global KakBegin .* %{
    try %{ source %sh{
        while :; do
            if [ -f init.kak ]; then
                printf "%s/init.kak" "$PWD"
                exit
            fi
            [ "$PWD" = / ] && exit
            cd ..
        done
    }}
}
```
You could use this to define the 'root' of your project and then have a command that cd's to it.

**Comment by alexherbo2** [comment]
@Delapouite @occivink Why add additional code for a workflow that could work with no code

**Comment by Delapouite** [comment]
"Why add additional code for a workflow that could work with no code?"

This sentence could apply to the all .kak scripts in existence. It's always hard to draw the line between what should be in the core or not.

**Comment by alexherbo2** [comment]
Hm…  But what is the value for `:change-directory` to go back to the user home directory, instead of the initial working directory?

**Comment by mawww** [comment]
@alexherbo2 Thats the same behaviour the shell has, cd without parameters goes to HOME directory. Changing that to something else is going to be pretty arbitrary, and the initial directory proposal adds complexity as we now need to track the startup directory (which might, or not make sense, depending on the user workflow), the traditional Kakoune way is to keep base behaviour simple.
