### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by John-Colvin** [mawww/kakoune#2344]
See https://github.com/Homebrew/homebrew-core/pull/31540 and https://github.com/Homebrew/homebrew-core/pull/28622

Even a beta release (e.g. `v0.1.0-beta.1`) would be very useful, as I could add a `devel` entry to homebrew which would be a bit more up to date.

**Comment by maximbaz** [comment]
I support this very much, please release often!

Also, I would highly recommend switching from date-based releases to [semantic versioning](https://semver.org/): 
- Define version as MAJOR.MINOR.PATCH
- Bump MAJOR if this release that breaks backwards compatibility.
- Bump MINOR if you add functionality in backwards-compatible manner.
- Bump PATCH if you are making a backwards-compatible bug fix.

I think there's no need for explicit `beta` or `devel` suffixes, you can simply mark releases as "pre-release" on Github if you want to have a few weeks of testing. So, for example, a version `2.3.5` could be the last "official" release and at the same time a version `3.0.7` could be the last "pre-release".

**Comment by lenormf** [comment]
A new release will be made once the issues with quoting (from/to shell expansions) will be sorted out.

As for the release version format, the `youtube-dl` format (for lack of better name) was picked on purpose:

>mawww   If I need to think if that release need to increment major or minor, I'll just postpone releasing
>mawww   If its just today's date, releasing is a simple process with no arbitrary decision to make besides releasing
>mawww   "Lets do a release" -> release done, vs "Lets do a release" -> "Okay, what version should that release be" -> "Not sure" -> "Oh look, a nice looking butterfly"

**Comment by lenormf** [comment]
>ironzorg        mawww: what if you release a version, then 12h later you remember you forgot to merge some important patch and do another release; how will users that installed the first one know that a second release was made (if the version numbers are the same)?
>mawww   I think for the eventual case where there is an hotfix on the same day, its going to be YYYYMMDD-hotfix or YYYYMMDD-N

**Comment by John-Colvin** [comment]
That's not the same circumstance I am describing.

**Comment by lenormf** [comment]
It looks like the only thing to do is wait?

**Comment by John-Colvin** [comment]
I'd say that would represent a clear failure of the release process.

Anyway, that failure hasn't happened yet, people don't tend to change their minds until they actually feel the pain so I guess I'll just wait and see.

**Comment by lenormf** [comment]
Making a fake release won't help create "a consistent record of releases from upstream", I reckon `homebrew` isn't going to restore building from `HEAD` until the project reaches a number of releases in the double digits.

**Comment by John-Colvin** [comment]
I wasn't hoping for a fake release, I was hoping that a good release was possible and a bit of prodding would help persuade it to happen. "It's not ready, we need to fix some bugs" is a perfectly reasonable response, hence me closing this issue.

**Comment by mawww** [comment]
Hello,

To give a bit of context, this release is a bit special, I decided to make a lot of breaking changes in one go because there were various issues that I wanted to sort out before we could have a regular stream of release (and having breaking changes that would require users to update their config at each release seemed a bit harsh).

I hope to make a release in the coming days now that the problem is sorted, and to have much more regular releases after that (because breaking changes will become less common/less impactful), 4 month is a **very long** time, I hope to have at least a release every month, maybe every two weeks (depending on commit activity and nature of the changes).

**Comment by maximbaz** [comment]
Thank you for publishing a new release and understanding that we need them more often 😉

**Comment by maximbaz** [comment]
1.5 months and 147 commits since the last release, just a friendly reminder @mawww 😉

**Comment by maximbaz** [comment]
> have a look at the pending pull requests to identify the small/easy ones that should be a no brainer to merge and have been forgotten for no specific reasons.

Good idea, hope this helps 🙂 

No-brainers: #2265, #2309
Relatively simple and very useful but unfortunately lack attention: #2336, #2286, #2458, #2273

**Comment by lenormf** [comment]
Also labels.
