### ISSUE TITLE
Translation of webpage

### ISSUE THREAD

**Issue by notramo** [mawww/kakoune#2354]
Is there any way to translate the homepage of the project?

**Comment by notramo** [comment]
I want to translate to Hungarian.
What about translating the HTML pages, and simply redirecting to `index_fr.html` or `index_hu.html` with a few lines of JS?

**Comment by lenormf** [comment]
That's already what we're doing (minus using javascript, we only need a `href` for that).

Feel free to post your translation in this issue, so it can be used when the translator has been implemented.

**Comment by lenormf** [comment]
Website translations have been merged, you can now create a PR with your own translation!

**Comment by notramo** [comment]
Could you provide short instructions for translating?
E.g. is it enough to insert another key-value pair to the translations hash, or it needs other modification too?
I'm not familiar with JS.

**Comment by lenormf** [comment]
Add the identifier for the language you want to add, i.e. "hu" for Hungarian, to the `translations` object, in `js/translate.js`:

```javascript
    var translations = {
        "en": {},
        "hu": {
        },
[…]
```

The keys in that new object are the identifiers of the strings that need to be translated, they are used directly in HTML, e.g.:

```html
        <title tid="head:indexPageTitle">Kakoune - Official site</title>
```

Simply assign translations to that `hu` entry, using the `tid` attribute used in the HTML:

```javascript
    var translations = {
        "en": {},
        "hu": {
            "head:indexPageTitle": "Kakoune - Hivatalos oldal",
        },
[…]
```

Do that for all `tid` attributes used in the HTML files that use translation (index, gallery, plugins), you could just copy them from the `fr` entry.

Now there are some entries in the french translation that are not pure text, e.g.:

```javascript
            "feature:multipleSelectionsText": $("[tid-fr='feature:multipleSelectionsText']").html(),
```

The value of this entry uses jQuery to fetch the translations directly stored into the HTML document, when the text to translate has markup in it, or is simply too long to be stored as a string in `js/translate.js`. In those cases, locate the HTML element with the same `tid`:

```html
                            <div class="mb-3 text-justify" tid="feature:multipleSelectionsText">
                                Multiple selections are the central way of
                                interacting in <i>Kakoune</i>, with powerful
                                handling primitives (regex matches, filtering,
                                splitting, aligning, text objects etc).
                            </div>
```

Now below this tag, create another tag that will be invisible on the page itself (when rendered by the browser), but that still allows us to keep the translation close to the original text. Just give it the `d-none` class, and a `tid-hu` attribute that holds the identifier of the translation:

```html
                            <div class="mb-3 text-justify" tid="feature:multipleSelectionsText">
                                Multiple selections are the central way of
                                interacting in <i>Kakoune</i>, with powerful
                                handling primitives (regex matches, filtering,
                                splitting, aligning, text objects etc).
                            </div>
                            <span tid-hu="feature:multipleSelectionsText" class="d-none">
[…]
                            </span>
```

Once that's done in the HTML file, create an entry for this translation ID by adjusting the selector:

```javascript
    var translations = {
        "en": {},
        "hu": {
            "head:indexPageTitle": "Kakoune - Hivatalos oldal",
            "feature:multipleSelectionsText": $("[tid-hu='feature:multipleSelectionsText']").html(),
        },
[…]
```

And that's pretty much all there is to it, you can base your own translations on the french one I wrote (copy the identifiers/selectors and adapt them).

**Comment by lenormf** [comment]
Also add a link to the dropdown that triggers translation, the hyperlink has to have a `translate` attribute containing the target language identifier (in your case, "hu"):

```html
<a class="dropdown-item text-nowrap" href="javascript:void(0)" translate="hu">
```

**Comment by lenormf** [comment]
I got the flags from [countryflags.io](https://countryflags.io/), their license file is in the repository.

The flag you want: ![](https://www.countryflags.io/HU/shiny/24.png)

**Comment by lenormf** [comment]
@notramo any progress?

**Comment by notramo** [comment]
I'll open a PR soon. It's harder to translate it correctly than I thought.
One thing I noticed that the **ő** character is not included in the font that the page uses.

**Comment by notramo** [comment]
@lenormf I opened #2526
