### ISSUE TITLE
Kakoune erratically freezes on quit or kill

### ISSUE THREAD

**Issue by leeola** [mawww/kakoune#2357]
OS: OSX 10.13.6
Kakoune Version: Kakoune v2018.04.13-469-g373858f9

### Steps 

1. open kakoune
2. open several panes. ie split the kakoune window to new tmux panes
3. `:quit` or `:kill` a kakoune pane that is the non-spawning tmux pane. *(ie, the tmux split that spawns kakoune seems unaffected by this issue)*

### Outcome 

~20% of the time the kakoune pane that called `:quit` will be unresponsive, and not closed. The frozen split appears to consume 100% of that CPU/thread as well.

Other panes/splits of kakoune are responsive. Only the split where `:quit` was ran actually freezes.

### Expected 

Not to freeze at all :)

NOTE: I cannot reproduce this 100% of the time. As mentioned, it only happens roughly 1 in 5 times. Sometimes much less, sometimes more. Likewise I've not seen any error, because it doesn't actually crash or anything.. it just becomes unresponsive.

I've not looked at that session's debug buffer though, so I'll look at that next once I encounter the freeze again. Any tips to help debug this issue would be appreciated.

**Comment by occivink** [comment]
What you might want to do is run a debug build, and when the freeze happens, attach a debugger to see where kakoune is hanging.

**Comment by Delapouite** [comment]
May be related to https://github.com/mawww/kakoune/issues/2126

**Comment by lenormf** [comment]
Please try on the latest stable version.

**Comment by leeola** [comment]
Does the release version matter? I built from the release commit,

```
lee ~/t/k/src> kak -version
Kakoune v2018.09.04
```

and still encountered the issue

**Comment by mawww** [comment]
Reproduced it, got a fix incoming.
