### ISSUE TITLE
grep error: 'hook' unknown option '-always'`

### ISSUE THREAD

**Issue by benekastah** [mawww/kakoune#2361]
### Steps 
I used the `:grep` command. Any invocation I've come up with produces the issue, but an example invocation is:

```
:grep path my_dir/
```

### Outcome 
Got error message `1:1: 'grep' 1:1: 'evaluate-commands' 5:232: 'hook' unknown option '-always'`. The command still worked otherwise (meaning I got my grep results in the *grep* buffer and could navigate to the results).

### Expected 
No error message.

**Comment by mawww** [comment]
What version of Kakoune are you using, it seems like a mismatch between the grep.kak file and the built Kakoune binary.

**Comment by benekastah** [comment]
Looks like version 2018.04.13:

```
$ brew info kakoune
kakoune: stable 2018.04.13 (bottled)
Selection-based modal text editor
https://github.com/mawww/kakoune
/usr/local/Cellar/kakoune/2018.04.13 (118 files, 3.0MB) *
  Poured from bottle on 2018-08-20 at 12:57:48
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kakoune.rb
==> Dependencies
Build: asciidoc ✘, docbook-xsl ✘
```

**Comment by mawww** [comment]
Seems the grep.kak file you have is more recent than that, as that feature was added on the 17th of april. There has been a new version released last week, updating to it should fix that problem.
