### ISSUE TITLE
Unify scrolling of autocompletion menus

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#2362]
Currently when you scroll through the prompt suggestions, the behavior is slightly different when going up or down. If you go down, the suggestions are changed page by page as you reach the bottom, but when going up it happens line by line. 
It'd be nice if the behavior was the same in both directions, and I think it's nicer when going line by line (which is also how you scroll in the buffer).

The same applies to autocompletion suggestions in insert mode.

Here is an asciicast to show what I'm talking about: https://asciinema.org/a/jlABLLnBdEo6tsM8TZRhfobmZ

**Comment by alexherbo2** [comment]
The link does not work.

**Comment by mawww** [comment]
I am not sure unifying on line by line scrolling is better, first it is going to make single column completion hard to use, as once you hit the last displayed element, each tab makes only the next element both selected and visible. It seems to me that in a completion context, if none of the displayed candidates are the one the user is looking for, displaying a whole new set of candidates makes more sense than keeping part of those unwanted ones visible.

**Comment by occivink** [comment]
I quickly tested in vim, they do line by line with a scrolloff. I prefer line-wise than page-wise because then I don't have to look at all the new candidates at once, instead I can just do it progressively and keep my eyes at the same location.
Maybe people could test the patch and give feedback.

**Comment by lenormf** [comment]
Is this not a sign that we should probably have a set of mappings to cycle individual candidates, and another to skip entire pages?

The current behaviour seems to be a combination of the two, but obviously that doesn't seem to suit some users.
