### ISSUE TITLE
Kakoune incorrectly highlights '-' lines in COMMIT_EDITMSG

### ISSUE THREAD

**Issue by daboross** [mawww/kakoune#2371]
### Steps 

Set `kak` as `$EDITOR`.

Use `git commit` in a git repository with pending changes.

Enter text with a list like:

```
Made some changes.

Notable changes I made include:
- Add files
- Remove files
- Do other things
```

### Outcome 

The lines starting with a dash are highlighted red, as if they were subtracted lines in `git diff` output.

### Expected 

The lines starting with a dash are unhighlighted or highlighted the same as lines not starting with a dash, as they are regular text.

**Comment by lenormf** [comment]
The way patches are handled is lazy, the entire buffer is highlighted as a diff, and some regex highlight comments and file changes on top.

A region should be defined that grabs the trailing patch and highlights it as a diff, instead of highlighting the entire file as such.
