### ISSUE TITLE
Backslashes in the documentation are mis-handled

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2377]
### Steps 

* `:doc command-parsing non-quoted-words`

In the asciidoc source, the sentence reads:

```
If they start with `\\` followed by `%`, `'` or `"`, then that leading
`\\` character is discarded.
```

### Outcome 

The sentence is rendered as:

```
If they start with \` followed by `%, ' or ", then that leading `\` is discarded.
```

**Comment by ManDay** [comment]
See also section *Disabling Hooks* under `:doc keys` and `:doc hooks`. Both render incorrectly. One could say, the feature is therefore not documented.

**Comment by lenormf** [comment]
Fixed.
