### ISSUE TITLE
Supply multiple groups to the remove-hooks command

### ISSUE THREAD

**Issue by Delapouite** [mawww/kakoune#2380]
Hi

Currently the `remove-hooks` command can accept only 1 group at a time.

In many `rc` scripts, there is the following pattern in almost all languages files:

```
hook global WinSetOption filetype=(?!c)(?!cpp)(?!objc).* %[
    remove-hooks window c-family-hooks
    remove-hooks window c-family-indent
    remove-hooks window c-family-insert
    …
]
```

What about being able to supply multiple groups? Example: 

```
hook global WinSetOption filetype=(?!c)(?!cpp)(?!objc).* %[
    remove-hooks window c-family-hooks c-family-indent c-family-insert
    …
]
```

**Comment by alexherbo2** [comment]
Plus it makes sense as the name suggests.

**Comment by lenormf** [comment]
Do you need to be able to use a regex?

**Comment by alexherbo2** [comment]
Not that I’m suggesting it, but while thinking about multiple groups I’ve thought about regex.
