### ISSUE TITLE
static_words not reset

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#2381]
Most syntax files set `static_words` on the window, not the buffer.  We could change them to set these on the buffer.  It's possible (though less likely) that the buffer type will change.

We could try to remove them the same way highlighting is removed, except we'd need some kind of `-remove` option to `set-option`, unless we're OK with just nuking `static_words` when the buffer type changes.

### Steps

```
:e file.kak
:e file.clj
iexec
```

### Outcome

Autocomplete shows `execute-keys` (which is not a Clojure object).

### Expected

Autocomplete shows only Clojure completions.

**Comment by mawww** [comment]
The problem with resetting static_words is that there is no guarantees on the order filetype hooks are going to run (at least, its not practical to rely on that), so the hook that unsets static_words might run after the new filetype hook updated it to the new language value.

I still plan to solve this with an additional "custom" scope system. The basic idea would be to define "shared" scopes (the same way we define shared highlighters), which could then be enabled in a window/buffer. Most language support would then live in those shared scopes, and enabling a language support would just be adding that scope to the "additional scopes" of the current window. Designing that in a nice way is still tricky, but it would solve various ordering problems and possibly simplify various scripts.

**Comment by eraserhd** [comment]
@mawww This sounds nice!

Shall we keep this issue open until then?

**Comment by mawww** [comment]
I think we can close this issue, I have that feature on the back of my mind, and it is not specific to static_words.
