### ISSUE TITLE
`:doc` command doesn't work with version 2018.09.04 installed from homebrew

### ISSUE THREAD

**Issue by benekastah** [mawww/kakoune#2386]
### Steps 
I ran `brew upgrade kakoune`. When I ran `kak`, my configuration no longer worked (which makes sense). Clippy told me to see `:doc changelog` for a list of changes.

### Outcome 
An error like "no such command: doc." No way of running `:doc` worked for me, and it did not show up in autocomplete at all either. I even tried with `kak -n` to skip loading my config, in case my config broke things with no change.

### Expected 
`:doc` command should be a recognized command.

### Other notes

I couldn't find this reported, sorry if I missed it. If you run into this and you uninstall all versions of kakoune and reinstall to see if it fixes things (it doesn't), you can get the old version back like this:

```
# check out the commit before the upgrade patch in homebrew
$ git -C "$(brew --repo homebrew/core)" checkout 086121c153c5c031a93aaaab2857b4174429d6ab~
$ brew unlink kakoune
$ HOMEBREW_NO_AUTO_UPDATE=1 brew install kakoune
```

**Comment by benekastah** [comment]
**Update**: Reinstalling the old version as I outlined above didn't fix it. Could be something about the homebrew formulas?

FWIW, many other commands are missing (all the tmux-related ones for instance, which previously worked for me on version 2018.04.13)

**Comment by benekastah** [comment]
Ok, I described the issue incorrectly (has nothing to do with homebrew). I had previously checked out the kakoune repository at ~/local/kakoune a while back before brew installing was easy. I removed it earlier today because I thought I no longer needed it. Apparently those files are being used by the homebrew version of kakoune. To test this, I checked out the repository again in the same location, and things are working again. I bet that's what was happening with #2361 as well.

Any idea why kakoune is looking there for command definitions and such? How can I have it point to the files installed by homebrew instead?

**Comment by Screwtapello** [comment]
When Kakoune starts up, it reads the files in `~/.config/kak/autoload` *or* the files in the system-wide install; in order to use the system-wide defaults plus local customisations, it's typical to put a symlink to the system-wide defaults into `~/.config/kak/autoload`.

My guess is: your autoload directory contains a symlink to `~/local/kakoune/rc`, and you need to point it at... wherever Homebrew installs things.
