### ISSUE TITLE
Support new lines in info boxes

### ISSUE THREAD

**Issue by laelath** [mawww/kakoune#2403]
![screenshot_20180918-173514](https://user-images.githubusercontent.com/9309437/45724241-0a632f80-bb6a-11e8-8cf7-cf7f7d1c2dbc.png)
As shown in the image newlines are not currently shown in info boxes which messes with the formatting of diagnostics output.

**Comment by mawww** [comment]
Newlines are supported in the info box, here it seems for some reason the literal newline character has been replaced with `\n`.

**Comment by laelath** [comment]
Ahh okay, I'll look into fixing that then
