### ISSUE TITLE
Is there any way to detect focus change inside one client?

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2406]
I've written several kakoune commands, that make several tweaks to my `.tmux.conf`, making it work like vim's airline when kakoune is opened:
![tmux_bar](https://user-images.githubusercontent.com/19470159/45752980-ecf09d00-bc1f-11e8-8654-5953e60de1d0.gif)
Tmux bottom status bar is moved to the top on kakoune launch and recolored to look like it is part of kakoune (sort of).

However there is a problem, There's a way to detect that new file is opened, but no way to detect if current window was focused. I can't get `FocusIn` and `FocusOut` hooks to work. `NormalIdle` hook can be used instead:
![hook](https://user-images.githubusercontent.com/19470159/45753251-d0a13000-bc20-11e8-80b8-50a203509932.gif)
But it results in renaming window every time I stop doing things, which is unnecessary, and noticeable performance impact (I use kakoune in Termux on android, and can feel it).
So is there any arbitrary way of doing such thing? I don't want rename window every time `normalidle` hook gets executed, because it is too many calls to tmux.

**Comment by Screwtapello** [comment]
To be complete:

- I'm running tmux 2.7 with "focus-events on" and a Kakoune from the past few days.
- I set up the following hook:

        hook global FocusIn .* %{ echo -debug focus in }

- I switch to the `*debug*` buffer and then play with focus to watch whether events arrive.

Inside an outer terminal that does *not* support focus events (urxvt), if I run Kakoune directly, I never get any focus events (no surprise). If I run tmux in that terminal and Kakoune inside tmux, I still don't get any focus events when I focus or de-focus the terminal (again, no surprise), but I *do* get focus events when I switch panes within a window, or switch windows (by which I mean tmux's definition of "window").

Inside an outer terminal that *does* support focus events, the above still works, but now Kakoune gets a focus event when the outer terminal gets a focus event, if and only if Kakoune is the focussed pane of the focussed window at the time.

> I'd like to have something like BufferFocusIn or WinFocusIn hook

Well, `FocusIn` and `FocusOut` do give you the name of the client that received or lost the focus as te hook parameter, so you could do some kind of:

    echo "evaluate-commands -client $kak_hook_param %{ do a thing }" | kak -p -s "$kak_session"

...to get the client that gained or lost focus to do a thing, with whatever context the client has (like `$kak_bufname`)

**Comment by andreyorst** [comment]
Strange. Now `FocusIn` works fine. Thanks for explanations. Closing.
