### ISSUE TITLE
Analog of Vim's set path+=**

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2413]
Is there any analog of Vim's path `**` feature? This feature allows Vim's find command search for files recursively. It also affects Vim's <kbd>g</kbd><kbd>f</kbd> command, making it easy to navigate in some projects.

Because I didn't find anything about it I did implemented `:find` command for Kakoune and a new <kbd>g</kbd><kbd>f</kbd> mapping, which recursively searches in all path options, and mapped <kbd>g</kbd><kbd>Alt+f</kbd> to default now non-recursive behavior:
```sh
define-command -docstring "find file recursively searching for it under path" \
find -params 1 -shell-candidates %{ find -type f } %{ evaluate-commands %sh{
    for buffer in $kak_buflist; do # first we check if file exist in buffer list, as gf initially does
        buffer="${buffer%\'}";  buffer="${buffer#\'}"
        if [ -z "${buffer##*$1}" ]; then
            echo "buffer $buffer"
            exit
        fi
    done
    if [ -e "'$1'" ]; then # check if absolute path given
        echo "edit -existing '$1'"
        exit
    fi
    for path in $kak_opt_path; do
        path="${path%\'}"; path="${path#\'}"
        case $path in # in default path configuration current kak dir goes before current buffer dir
            "./") path=${kak_buffile%/*};; # swap './' and '%/' since '.%' has fewer scope to search
            "%/") path=$(pwd);;
        esac
        if [ -z "${1##*/*}" ]; then # if path contains '/' treat it as absolute path
            test=$(eval echo "'$path/$1'")
            [ -e "$test" ] && file=$test
        else # search for file recursively
            file=$(find -L $path -xdev -type f -name $(eval echo $1) | head -n 1)
        fi
        if [ ! -z "$file" ]; then
            echo "edit -existing '$file'"
            exit
        fi
    done
    echo "echo -markup '{Error}unable to find file ''$1'''"
}}
```

Tested it in bash, zsh, dash, and busybox environvent v1.29. [AFAICS](https://acronyms.thefreedictionary.com/AFAICS) there's no bashisms, and it should be fully POSIX compatible.

I think this may be helpful, but curious if I should include this to the wiki.

**Comment by lenormf** [comment]
`if [ ! "x$file" = "x" ]; then` is `if [ -z "$file" ]; then`.

Otherwise, the wiki is editable by anybody and largely un-moderated, you can add anything you think is relevant to it without asking for permission !

**Comment by andreyorst** [comment]
> if [ ! "x$file" = "x" ]; then is if [ -z "$file" ]; then.

Thanks!

However the main point was, are there any plans for supporting such feature native? Just adding `**` in vim can be used in far more places rather in single `:find` command.

**Comment by lenormf** [comment]
I think the current stance is that the prompt should not become a Kakoune shell that re-implements all things we're used to in `*sh`.

Regarding your particular question, I think you're better off spawning a file explorer or something like `fzf` to reach the file you want, instead of trying to import diluted features from those tools.

**Comment by andreyorst** [comment]
> I think the current stance is that the prompt should not become a Kakoune shell that re-implements all things we're used to in *sh.

Can you elaborate please?
