### ISSUE TITLE
Various C types are not highlighted

### ISSUE THREAD

**Issue by ybden** [mawww/kakoune#2438]
Currently, only a few types are highlighted. It would be good if this could be expanded to include all the types used by C (and probably POSIX). A few of these I can find off the top of my head: `bool`, `FILE`, `ssize_t`, `uintX_t`. Suggested reference: Annex B of the latest C standard, Chapter 13 (Headers) of the latest POSIX standard.

**Comment by andreyorst** [comment]
I have this hook in my config:

	hook global WinSetOption filetype=(c|cpp) %{
		# Custom C/Cpp types highlighting
		add-highlighter window/ regex \b(v|u|vu)\w+(8|16|32|64)(_t)?\b 0:type
		add-highlighter window/ regex \b(v|u|vu)?(_|__)?(s|u)(8|16|32|64)(_t)?\b 0:type
		add-highlighter window/ regex \b(v|u|vu)(_|__)?(int|short|char|long)(_t)?\b 0:type
		add-highlighter window/ regex \b\w+_t\b 0:type
	}

`bool` and `FILE` can be added in the same fashion.

**Comment by lenormf** [comment]
That's because those types are part of the standard library, but not part of the language.

We had the same issue/request with the python script, I guess we could compliment the list of symbol highlighted.

**Comment by Delapouite** [comment]
@ybden hi. Can this issue be closed now that #2453 is merged?
