### ISSUE TITLE
Rust syntax should always use block indenting

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#2439]
### Steps 

1. Open a file with the `.rs` extension:

        $ kak /tmp/foo.rs

2. Type something that looks like the beginning of a function call

        some_long_method_name(something,

3. Press `<ret>`

### Outcome 

Kakoune indents the next line so the cursor starts just underneath the `(` character.

### Expected 

Kakoune indents the next line by one `%opt{indentwidth}`, like if you hit `<ret>` immediately after the bracket.

### Notes

Once upon a time, it was fairly common in the Rust community to use "visual" indenting; that is, to indent wrapped lines so they line up with the opening bracket of the function call. However, since then there was a community-wide consultation and [the official formatting guidelines](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/expressions.md#multi-line-calls) now recommend "block" indenting everywhere; that is, always indenting by exactly one `%opt{indentwidth}`.

The `rustfmt` tool that comes with the compiler cleans this up nicely, but I'm not always working in a codebase that uses fully-automatic formatting, and it's always nicer to avoid creating a problem than to clean it up.

I believe that [these lines](https://github.com/mawww/kakoune/blob/93f913705abafbd7341e4fdd897bef5f6ef4c0dd/rc/base/rust.kak#L55-L56) are responsible for the behaviour, but I don't have time to decipher how that works right now, so I'm filing this ticket in case somebody else wants to fix it before I get around to it.

**Comment by andreyorst** [comment]
I'd say that overall improvement of automatic indentation in Kakoune is needed. There are many cases where indentation just doesn't work right. Using formatter every time should not be considered normal, because editor should not stand in the way when you write code.
