### ISSUE TITLE
Builtin option aligntab behaviour

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#2441]
When `aligntab` option is set to `true`, I expected that indent selected lines key `>` will fill with tabs, however that is not true. In other words, `>` fills with spaces regardless of `aligntab` option.
Do I misunderstand this builtin option? If I do, what is it for then?

**Comment by alexherbo2** [comment]
`aligntab` is the option used by commands (<kbd>&</kbd> for example) to _align selections_ with spaces (by default) or tabs – when true.

`indentwidth` is the option used by commands (<kbd>&gt;</kbd> for example) to _indent_ with the given number of spaces or one tab – if set to zero.

``` kak
set global indentwidth 0
```

**Comment by vbauerster** [comment]
@alexherbo2 Thank you for explanation!
