### ISSUE TITLE
Create Directory When Directory Doesnt Exists

### ISSUE THREAD

**Issue by midnio** [mawww/kakoune#2459]
When I run `kak ~/a/folder/that/not/exists/okk.cc` then run `:write`, it gives error `"No such file or directory"`. Maybe it should create it automatically.

**Comment by maximbaz** [comment]
Maybe it should be a core functionality, maybe it shouldn't, right now I use this:

```
hook global BufWritePre .* %{ nop %sh{ mkdir -p $(dirname "$kak_hook_param") }}
```

**Comment by Delapouite** [comment]
Related issue : https://github.com/mawww/kakoune/issues/1919

**Comment by mawww** [comment]
My stance on that is that the hook system makes it easy to opt-in into the "smart" behaviour (creating the directory automatically) as showing in @maximbaz comment.

For users who prefer to be notified that the directory does not exist (might be an error, or say a `git pull` might have moved files around and renamed a directory...) I think it makes sense to keep the built-in command "dumb".

**Comment by mawww** [comment]
@occivink what I do here sounds  pretty similar to that, except that I use a separate command:

```
define-command mkdir %{ nop %sh{ mkdir -p $(dirname $kak_buffile) } }
```

If a write fails, I just `:mkdir` and write again

**Comment by occivink** [comment]
just for reference, the escaping-correct version would be:
`define-command mkdir %{ nop %sh{ mkdir -p "$(dirname "$kak_buffile")" } }`
