### ISSUE TITLE
[fix] } sould not extend selection

### ISSUE THREAD

**Issue by robinmoussu** [mawww/kakoune#246]
Hi,
"}\*" (with "\*" is any valid select command) should not extend selection (but "}*" must) to be consistent with other commands.
Furthurmore, their is no ":set \<scope\> selection \<key\> \<key\>" options

As an addition "{\<alt-key\>" could select in both direction (left and right) and "{\<alt-maj-key\>" extend selection in both direction.

**Comment by mawww** [comment]
not sure what you mean with `}*`, `]*` is 'select to object end' while `}*` (`}` is `shift-]`) is 'extend to object end'

for both direction, `<a-a>*` is 'select surrounding object' and `<a-i>*` is 'select inside surrounding object'

**Comment by robinmoussu** [comment]
Sorry my exemple was not clear.

So, suppose we have that text :

    aaaa bbb ccc
    d eeee

My cursor is on the first "b". I use a move command like "w", so "bbb " is selected. After that I stroke "}p". What I was expecting is that "ccc d eeee" is selected and my cursor at the end of the paragraph. But "bbb" is also selected, so the old selection was keep.
If I stoke "}P", it can be normal.

**Comment by mawww** [comment]
Yep, if you do not want to extend the selection, use `]` not `}`, it makes more sense on a qwerty keyboard because `}` == `shift-]`

**Comment by robinmoussu** [comment]
ok. The lake of a « :help » command confused me. Sorry for the noise.
