### ISSUE TITLE
Store revision

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2460]
To know the commit hash of the Kakoune we are running.

**Example**

``` kak
echo %val(revision)
```

❯ 93f913705abafbd7341e4fdd897bef5f6ef4c0dd

Maybe also refer to it in the greeting title (in place of the version).

(We already have the last version information in the greeting message)

**Comment by Delapouite** [comment]
Related feature: see if we're running a debug build or not.

**Comment by Screwtapello** [comment]
`%val{version}` provides the version in standard `git describe --tags` format:

    v2018.09.04-101-g551021d6
    -+--------- -+-  -+------
     |           |    |
     |           |    +- truncated commit hash
     |           |
     |           +- commits since latest tag
     |
     +- latest tag

We could concievably run `git describe --tags --dirty` instead, which will add a `-dirty` suffix if the working tree has any uncommitted changes at build time.

> see if we're running a debug build

`:debug info` prints "build: release" or "build: debug" to the debug buffer.

**Comment by mawww** [comment]
Yeah, I think `%val{version}` is good enough, could tweak to use the --dirty flag if asked for it, although I am not sure its that important.
