### ISSUE TITLE
Support references to captured groups in regex

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2486]
### Steps 

In a buffer containing `aa`:

* select `aa`
* use <kbd>a-k</kbd> `(.)\1` <kbd>ret</kbd>

### Outcome 

An error is displayed:

```
regex parse error: unknown atom escape '1' at '(.)\1<<<HERE>>>'
```

### Expected 

The selection is kept.

HTH.

**Comment by mawww** [comment]
This is not implementable with a virtual machine approach to regular expression, which gives us guarantees on worst case performance. It would require a rewrite of the regular expression matching, which I do not plan to do.
