### ISSUE TITLE
2 separate kak instances should cooperate when editing the same file(s)

### ISSUE THREAD

**Issue by dumblob** [mawww/kakoune#250]
Open file `f1.txt` in one terminal, then in another terminal open the file again and I'd expect it to open it in `:new` mode, but it's completely independent :( . Btw Vim forbids this (issues a dialog asking whether to proceed).

**Comment by mawww** [comment]
That would be very complicated to support, `:new` runs a kakoune instance in client mode, which means it only provides user interface while the editing backend is provided by the server kakoune process.

Detecting a file opened by multiple kakoune process could be done, but that would require adding some lock files somewhere on the filesystem, which is always tricky to get right.

**Comment by dumblob** [comment]
Well, I got an impression, that it should be sufficient to enhance the remote communication protocol. But if it's not feasible, then I'd go for the lock files - there might be an issue with concurrent create & check, but it shouldn't be so common problem as *kak* is IMHO supposed to open files with low frequency (mostly initiated by the user) and if it happens, it won't break anything - it'll just say *can't open the file more than once, use `:new`*.

**Comment by mawww** [comment]
Yeah, the communication protocol is actually very simple, the UI sends keys, the editing server sends display commands (show an info box, show a menu, display that text with these colors...). Now between different editing servers things would get much more complicated.

I can look into locking, that said Kakoune already supports detecting that a file is changed externally, I am not sure it is worth it to add this locking mechanism (I mean, the file can still get modified by loads of other programs anyway).

**Comment by dumblob** [comment]
>I am not sure it is worth it to add this locking mechanism (I mean, the file can still get modified by loads of other programs anyway).

Right. Still, from the user perspective, it's much more error prone to have two instances of kak editing the same file (it's hard to spot) than having kak and some other program modifying the file.

**Comment by ekie** [comment]
as "Crash recovery support (swap files)" is on the TODO list the first step could be to use the swap file as locking mechanism.

**Comment by maximbaz** [comment]
Since kakoune detects external file changes and offers to update the buffer (or can be configured to always update), does this issue still need to be open?

**Comment by mawww** [comment]
Yeah, no plans to add anything more complex than what we already have, closing.
