### ISSUE TITLE
Add a delimiter between the prompt and its input

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2502]
``` kak
prompt 'Say something' 'echo %val(text)'
```

```
Say something: ▌
```

The same applies for the built-in prompts.

**Comment by lenormf** [comment]
A space can already be appended to the prompt passed to the command already, I don't think it's worth it enforcing that by default.

**Comment by mawww** [comment]
Yeah, just use `prompt 'Say something: '`
