### ISSUE TITLE
Request to add pregenerated man page to release tarball

### ISSUE THREAD

**Issue by t6** [mawww/kakoune#2504]
Hi,

I have a small request for the next release.  Can the man page be generated and added to the release tarball you publish?  It would eliminate the asciidoc build dependency Kakoune currently has.

**Comment by mawww** [comment]
Hello,

I would love to get rid of that dependency, especially as it is now only relevant for the man page generation. I think we might actually just convert the man page to a hand written man-db one, not using asciidoc there, as most of the documentation is in the doc/pages/ integrated help anyway, and the man page should stay pretty light.

It is mostly a matter of taking the time to do it...

**Comment by lenormf** [comment]
Is it really worth it? Raw nroff can be pretty brutal, asciidoc keeps the page readable even in its un-compiled form.

Also now that more and more distributions ship packages for the editor, virtually only contributors and package maintainers are going to have that dependency installed, which isn't such a big deal considering how many projects already use asciidoc rendering.

**Comment by mawww** [comment]
@lenormf packaging will not solve the problem for source based distro. I agree raw nroff is ugly, but its a single file which is not updated very often (kak.1.asciidoc was only touched by 3 commits in the whole git history).

**Comment by lenormf** [comment]
I guess it's not that bad after all, I rescind my comment.
