### ISSUE TITLE
variable name construction via shell behaves ambiguous

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2512]
I'm trying to dynamically construct a variable name. It works in dash, bash, and zsh:
```sh
kak_opt_var=value
echo $(echo var | sed 's:^:$kak_opt_:')
# prints '$kak_opt_var'
eval echo $(echo var | sed 's:^:$kak_opt_:')
# prints 'value'
```
However this doesn't working in Kakoune. Command-line example:
```kak
decl str var 'value'
echo %sh{eval echo $(echo var | sed 's:^:$kak_opt_:')}
```

Prints nothing. **But this**:

```kak
decl str var 'value'
echo %sh{eval echo $(echo var | sed 's:^:$kak_opt_:'); echo $kak_opt_var}
```
Prints:
```
value␤value
```

Appending or prepending `echo` of non-constructed variable *"fixes"* the issue, if getting a value twice can be called a "fix". Constructed variable name magically begins to work if real variable is specified in the command. Appending or prepending another variable doesn't fix constructed one.

**Comment by lenormf** [comment]
The full name of the expansion has to appear in the scope before hand (in the code, or a comment - anywhere) in order for the server to inject its value in the environment.

You can't dynamically expand variables.

**Comment by Screwtapello** [comment]
This comes up often enough that I wonder if maybe Kakoune should scan the scope for `\b\$?kak_\b` or at least `\b\$?kak_opt_\b` and if found, print a warning to `*debug*` along the lines of "spotted "kak_" or "kak_opt_" fragment in %sh{} expansion; note that dynamically constructed variable names cannot work"

**Comment by andreyorst** [comment]
I've thought that options and values are exported to the shell at the moment of creation. That's why I've expected it to work in the first place.

**Comment by lenormf** [comment]
C.f. #2241
