### ISSUE TITLE
x11-new broken on FreeBSD

### ISSUE THREAD

**Issue by t6** [mawww/kakoune#2520]
setsid is used in x11.kak which is not available on FreeBSD.

Removing setsid seems to work, but this is probably not right.

Is there a portable solution to this or do I need to provide a setsid package?

### Steps 

Run `:x11-new` in Kakoune on FreeBSD.

### Outcome 

Nothing happens

### Expected 

Open a new terminal window with current Kakoune session

**Comment by lenormf** [comment]
I think we can do without this particular program, could you please try the following patch?

```diff
diff --git a/rc/base/x11.kak b/rc/base/x11.kak
index 1c4f6df6..ad5a5a72 100644
--- a/rc/base/x11.kak
+++ b/rc/base/x11.kak
@@ -32,7 +32,7 @@ The optional arguments will be passed as arguments to the new client} \
            exit
         fi
         if [ $# -ne 0 ]; then kakoune_params="-e '$@'"; fi
-        setsid ${kak_opt_termcmd} "kak -c ${kak_session} ${kakoune_params}" < /dev/null > /dev/null 2>&1 &
+        { eval "${kak_opt_termcmd} \"kak -c ${kak_session} ${kakoune_params}\""; } </dev/null >/dev/null 2>&1 &
 }}
 
 define-command -docstring %{x11-focus [<client>]: focus a given client's window
```

**Comment by t6** [comment]
Yes, this seems to work fine!

**Comment by t6** [comment]
I've updated FreeBSD's [sysutils/ssid](https://www.freshports.org/sysutils/ssid) port to provide `setsid` as well and added it as a run dependency for the Kakoune package for now. It's tiny so that isn't a big deal.

If there is no portable in-shell solution to this as suggested by @mawww in #2521 then I consider this solved from my point of view.
