### ISSUE TITLE
how to use non-default register with custom yank/delete mappings?

### ISSUE THREAD

**Issue by logol** [mawww/kakoune#2522]
Consider this:
1. add new mapping
`map global normal D 'Gld' -docstring 'delete/cut from cursor to end of line'`
2. use mapping with null register
`"_D`
in theory this should execute: `"_Gld` or lets say `Gl"_d`
3. paste on another line
`p`

somehow I expect nothing (or something from a previous "-yank) to be pasted, but 
I realized due to kakoune's different design  `"_ ` is withdrawn upon the `G` command and set back to default register " (dquote) ...

so my question since the `"_` needs to be inserted before the `d` how can I achieve that in a dynamic mapping where I could use `<register-selection>D`

edit: makes more sense with delete than yank command

**Comment by Screwtapello** [comment]
map global normal Y 'Gl%val{register}y'

See [:doc expansions](https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc) for details.

**Comment by mawww** [comment]
@Screwtapello I am not sure this would work, as %val{...} expansions are not expanded as part of executing a mapping, The issue is actually tricky to solve without introducing an indirection through the command line: `map global normal Y ':exec Gl%val{register}y`.

**Comment by logol** [comment]
Thank you guys,

@mawww  your example returned `1:1: 'exec' no selections remaining`
so I had to adjust it a little but:

`map global normal Y 'Gl:exec %val{register}y<ret>'`
`map global normal D 'Gl:exec %val{register}d<ret>'`

which now works flawless with something like `"_D`

next challenge would be to default to `""` if no register is given at all^^

**Comment by andreyorst** [comment]
> it seems like everything goes to null register with these mappings, behavior is the same when using exec manually e.g.
> 
>     <a-i>w select a word
>     :exec ""y
>     p
> 

is this a bug?
try `exec -save-regs '' '""y'`

**Comment by logol** [comment]
@andreyorst  `map global normal D 'Gl:exec -save-regs %val{register}d<ret>'` does not work too, but I'm not sure if I'm using this correctly

**Comment by Screwtapello** [comment]
It's specifically `-save-regs ''` (or if you're already inside single quotes, `-save-regs ""` or Kakoune's nestable string-quoting syntax `-save-regs %{}`). Normally `:exec` saves the value of certain registers before executing keys and restores them afterward, but `-save-regs ''` means "save the contents of all the registers listed in this empty string" i.e. none of them.

**Comment by logol** [comment]
Okay, but for me it seems like that even with save-regs the mapping will not work if there is a `Gl` at the beginning
`map global normal A ':echo "%val{register}"<ret>'`
typing `""A` echoes `"`
`map global normal B 'Gl:echo "%val{register}"<ret>'`
typing `""B` echoes ` ` (nothing) but selects from cursor to end of line

so this works as expected
`map global normal Y ':exec -save-regs "" """%val{register}"y<ret>'`
`map global normal D ':exec -save-regs "" """%val{register}"d<ret>'`
but this doesnt
`map global normal Y 'Gl:exec -save-regs "" """%val{register}"y<ret>'`
`map global normal D 'Gl:exec -save-regs "" """%val{register}"d<ret>'`

**Comment by mawww** [comment]
@logol `map global normal D 'Gl:exec -save-regs "" """%val{register}"d<ret>'` has the same issue you originally had, the register value is eaten by the `Gl` command, the whole point of using `exec` is that now the value of the register is eaten by the `exec` command itself, which can then reuse it at the proper place.

`map global normal Y ': exec -save-regs "" "Gl""%val{register}y"<ret>'` should do the trick (note the space between `:` and `exec` so that the command does not end up in command line history).

**Comment by logol** [comment]
ah I see, yes the space is pretty important .. thanks for the help!
