### ISSUE TITLE
progress indicator for grep command

### ISSUE THREAD

**Issue by co-dh** [mawww/kakoune#2527]
The grep command has no indicator if it finished, or still running, and this is frustrating.
I have to switch to terminal many times when grep gives no result.
Some indicator in status bar would be enough, like finished, found no result.

**Comment by Delapouite** [comment]
I though about it a while ago.
My idea is that we should be able to declare new hooks in userland.

This way, in grep.kak:
```
declare-hook GrepEnd
```
at the beginning of the file.

And then something like this when the grep command finished:
```
run-hook GrepEnd optional_arg
```

And then in your kakrc, you can listen to this event like a regular hook:
```
hook global GrepEnd .* %{
  // update modeline for example
}
```

The same pattern could be applied to lint.kak, kak-lsp, or any plugins that want to communicate stuffs during its lifecycle.

Currently it can somehow be emulated with `GlobalSetOption` but it feels less clean.
