### ISSUE TITLE
Menus don't get automatically resized anymore

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2529]
### Steps 

* spawn a menu that has many candidate (e.g. lookup a tag)
* hit <kbd>s-tab</kbd>

### Outcome 

When the amount of candidates isn't congruent to the maximum height of a menu, there's a lot of empty space:

![](https://my.mixtape.moe/udyimj.png)

![](https://my.mixtape.moe/swynfp.png)

### Expected 

The height of the menu adjusts automatically to the amount of candidates being displayed.

**Comment by Delapouite** [comment]
Has to be related to the recent menu refacto: https://github.com/mawww/kakoune/commit/7c00165c23ecffb365b997e3dced3b66b47f30f5

**Comment by lenormf** [comment]
Yes, I reckon as well.

**Comment by lenormf** [comment]
The screenshot was lost during the migration to Microsoft servers, and I can't really reproduce the issue.

Closing until the issue pops up again, if it ever does.
