### ISSUE TITLE
Choose other font for webpage

### ISSUE THREAD

**Issue by notramo** [mawww/kakoune#2530]
`ő U+0151 LATIN SMALL LETTER O WITH DOUBLE ACUTE` and `ű U+0171 LATIN SMALL LETTER U WITH DOUBLE ACUTE` doesn't render properly with current font.
Nimbus Sans looks cool and it has both letters.
#2526 
![current](https://user-images.githubusercontent.com/26059643/47602589-58791780-d9e1-11e8-8ab9-c78d28eb72f5.png)

**Comment by lenormf** [comment]
I have a commit ready that uses the light version of Noto, I'll create a PR once your translation has been pushed.
