### ISSUE TITLE
[Discussion] Flipping selections with Tab

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2539]
**Current positions**

<kbd>Alt</kbd> <kbd>;</kbd> → Flip the selections’ direction
<kbd>Alt</kbd> <kbd>:</kbd> → Ensure selections are in forward direction

**Changes**

<kbd>Tab</kbd> → Flip the selections’ direction
<kbd>Alt</kbd> <kbd>Tab</kbd> → Ensure selections are in forward direction

**Comment by Delapouite** [comment]
I reckon the `tab` key is way too brittle in terminals with the whole `Ctrl+I` mess. (and the conflict with the jumplist)

Moreover, to deal with flipping or reducing to anchors and cursors, I'm pretty pleased with the user-mode I described on the forum recently: https://discuss.kakoune.com/t/anchor-mode/84

**Comment by mawww** [comment]
Yeah, closing this.
