### ISSUE TITLE
compilation warnings  and «error in compiling notice [debian stable + clang official repositories]

### ISSUE THREAD

**Issue by bmorel** [mawww/kakoune#254]
Sorry for bad title: used the wrong key, and can't edit title.

About the «error» in compiling notice: on Debian, it does not compile with the package libncursesw5-dev, only with the libncurses5-dev package. Otherwise, the makefile does not find the ncurses.h file.

About warnings:
I have some compiling warnings in Debian, with clang 3.5. Here they are, but forgive me for the absence of correct presentation: I have no idea how I could say to github that this is actually terminal quotes.
Those warnings are really, really trivial to fix, so I really doubt it is worth cloning the repo to fix them. Plus, for the first one, I have no idea if the function should be used or not, and if yes, where it should be.

clang++ -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -pedantic -DKAK_DEBUG -MD -MP -MF .selection.d -c -o .selection.o selection.cc
selection.cc:53:11: warning: unused function 'update_erase' [-Wunused-function]
ByteCoord update_erase(ByteCoord coord, ByteCoord begin, ByteCoord end)
          ^

clang++ -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -pedantic -DKAK_DEBUG -MD -MP -MF .string.d -c -o .string.o string.cc
string.cc:121:25: warning: format specifies type 'unsigned long' but the argument
      has type 'size_t' (aka 'unsigned int') [-Wformat]
    sprintf(buf, "%lu", val);
                  ~~~   ^~~
                  %zu

**Comment by mawww** [comment]
Hello, thanks for the report, I fixed the size_t warning, the unused function is kept for reference for now.

Regarding the Debian ncurses dependency, that is unfortunate, some distributions only have the ncurses.h, other only the ncursesw.h, and I want to avoid having a ./configure like phase just to get ncurses header. However I do not have a nice solution besides needing both ncurses-dev and ncursesw-dev on debian, which is not optimal...
