### ISSUE TITLE
[Proposal] Separate language support files to allow lazy loading

### ISSUE THREAD

**Issue by laelath** [mawww/kakoune#2543]
It has been noted by some (such as @occivink) that the inclusion of so many `.kak` files means a significantly slower startup time than editors like vim, especially on lower end hardware. However, I do think that the amount of out-of-the-box support that kakoune has is one of its strong points. With the current architecture more language support always comes at the cost of extra start up time.

This drastic proposal is an attempt to allow for extensive language support without as large of an impact on start up time.

I propose we load a universal index file that contains the hooks for recognizing the filetype, then source the actual language support file as needed. Also create a way to add to this index list in user kakrcs so people could still load custom language files. This could also have the affect of making it easier for people to load custom language files instead of the global ones if they wish, as I think the current system of creating a custom autoload and copying all the system files but the one you want to change is rather cumbersome.

**Comment by maximbaz** [comment]
I'm campaigning for a while for a [much simpler way](https://github.com/mawww/kakoune/issues/2152#issuecomment-413614352) to address this problem, but unfortunately it hasn't managed to pick up anyone's interest yet. Hope your proposal gets some attention. I support any lazy loading approach, doesn't have to be my implementation.

**Comment by laelath** [comment]
Closed in lieu of updated proposal #2772
