### ISSUE TITLE
Ability to detect current colorscheme (and colors)

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2549]
AFAICS there's no option or value which stores current color-scheme name. I'm writing a plugin for modeline, similar to powerline in Vim, and I'd like to keep it in sync with current theme, but it seems impossible to do. Ideally I'd like to have something like `%val{colorscheme}` or `%opt{colorscheme}`.

Also having ability to access to custom theme colors (beyond default `red`, `green`, `cyan`...) would be very good option.

**Comment by Delapouite** [comment]
https://github.com/mawww/kakoune/pull/2496

**Comment by Screwtapello** [comment]
"custom theme colours" are what Kakoune calls "faces", no?

**Comment by Screwtapello** [comment]
"custom theme colours" are what Kakoune calls "faces", no?

**Comment by andreyorst** [comment]
> #2496

This is sad. Defining command that looks like builtin but acts differently isn't good solution for me.

> "custom theme colours" are what Kakoune calls "faces", no?

Yes. I mean that if I create a color scheme with some colors that are not default ones, I won't be able to share them with any other non-colorscheme aware thing in Kakoune. Though I can use faces in modeline, I can't set them as values of some variables. And especially can't use part of face value like only foreground. So if I need color I either use whole face, or take color code from source of colorscheme.
