### ISSUE TITLE
wrap marker color

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2550]
Why wrap highlight marker is using `MenuInfo` color? I think it should share whitespace color or better use the same color as line numbers.

**Comment by TeddyDD** [comment]
`{{context_info}}` in modeline should have separate face as well instead of using `information`

**Comment by Delapouite** [comment]
This was added in https://github.com/mawww/kakoune/commit/f1c1de834a7b19143be6497b4c3685c030c3e18f and it looks like the marker uses the `StatusLineInfo` face https://github.com/mawww/kakoune/blob/master/src/highlighters.cc#L674

There was a discussion about which face to use in the original discussion https://github.com/mawww/kakoune/issues/2065

**Comment by Delapouite** [comment]
@andreyorst looks like this issue can be closed now that the `WrapMarker` face has been commited: https://github.com/mawww/kakoune/commit/0f292d343b17a404f560308d8ac6bf6af52add3a

Other ref https://github.com/mawww/kakoune/issues/3149
