### ISSUE TITLE
Support -markup switch in info command

### ISSUE THREAD

**Issue by ul** [mawww/kakoune#2552]
Some plugins could benefit from support of faces in info box content, e. g. kak-lsp: https://github.com/ul/kak-lsp/issues/73

**Comment by TeddyDD** [comment]
Command's docstrings could use that too

**Comment by Delapouite** [comment]
Faces in info box do increase the readability. 

Here's a screenshot from LSP + neovim, with different faces for warning/error inside the info box: 
![image](https://user-images.githubusercontent.com/39315/68756515-9061f580-060a-11ea-9f89-f315323d25a5.png)

A short video here: https://www.reddit.com/r/neovim/comments/dvd8sz/builtin_language_server_with_my_preferred_style/

**Comment by mawww** [comment]
The main reason I have not tackled this yet is that info boxes are currently expected to be reflowed by the UI, and passing a DisplayBuffer for info instead of a string would break this. But that does not seem such a hard problem so might take a look soon.
