### ISSUE TITLE
Cannot map <c-space>

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#2553]
### Steps 

1. `kak -n`
1. `:map global normal <c-space> ": echo ctrl space<ret>"`
1. Press `<c-space>`

### Outcome 

Nothing happens.

### Expected 

"ctrl space" should appear in the bottom-left of the terminal.

### Notes

`<c-space>` is not actually a character that appears in an ASCII table, but by the convention that the Control key means "clear the top three bits of the character", `<c-space>` produces ASCII NUL, and in fact most terminals will send NUL when the user presses `<c-space>`. Run `cat` and try it yourself.

In slightly more conventional notation, NUL could also be written as `<c-@>`, but that form doesn't work either (and is much, much more awkward to type). At least with `gnome-terminal`, I can also send NUL with `<c-2>` and ctrl-backtick which I can't type in markdown.

I also can't make `<c-space>` do anything if I prefix it with `<c-v>`, or type it in insert mode.

Other non-alphabetic control characters like `<c-^>` (aka `<c-6>` and `<c-~>`) and `<c-_>` (aka `<c-7>`) also can't be mapped, but I can type them on the command-line with `<c-v>` and I can type them in insert mode.

**Comment by andreyorst** [comment]
well, actually `<c-_>` (`<c-/>`, <c-7>) and `<c-^>` (`<c-6>`, `<c-~>`) can be mapped by using <kbd>Ctrl+v</kbd> to directly insert keycode as `map` argument because as you've mentioned, they actually produce a code. And Ctrl+Space doesnt do that. I use this in my config for long time already: 
```kak
map global normal '' ': comment-line<ret>' -docstring "<c-/> to comment/uncomment selection"
                   ^
                   Ctrl+v Ctrl+/ were used here to insert this
```

**Comment by Screwtapello** [comment]
It turns out that, at least on the builtin-terminal-ui branch, NUL is interpreted as ``<c-`>``, and a mapping for that key can be triggered by all the other keypresses that send NUL.

As a matter of predictability, I think NUL should be decoded as `<c-space>` since that's the easiest way to type it.
