### ISSUE TITLE
[Question] GitHub, kakscript name, highlihgting, language search filter, etc

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2558]
Are there any plans to make GitHub treat kakoune scripts as some language? Highlighting will be useful too, since right now reading kakoune scripts on web is messy task. There is also search that can filter projects per language, which is useful to search plugins that do not define `Kakone` and `Plugin` tags for some reason.

https://help.github.com/articles/about-repository-languages/

Also how to call language in which kakoune scripts are written? Kakscript? Kaksh? Kakconf?

**Comment by Delapouite** [comment]
It's been discussed in the past, but the Kakoune ecosystem (in number of repositories) was not that huge back then. There are currently 133 so I think it's more relevant nowadays.

**Comment by lenormf** [comment]
This has been discussed a couple of times, it's just such a boring/obnoxious process that nobody has spent any time on it.

`kakscript` is probably the most accurate name.

**Comment by caksoylar** [comment]
I looked into adding support for new languages in Github a bit more following Andrey's link and the way to do it currently seems to be to add the kakscript language to the [linguist repository](https://github.com/github/linguist). There is a handy guide here: https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language. Here is a recent example PR: https://github.com/github/linguist/pull/4901

Sounds like the most difficult part would be to add an Atom/TextMate language grammar for Kakoune syntax for which there is a guide here: https://gist.github.com/Aerijo/b8c82d647db783187804e86fa0a604a1. It supports features like embedded languages so I'd imagine all Kakoune syntax elements would be possible to implement.

Finally we'd need a name (like `kakscript`) and a color to represent the language (orange of the logo?).

**Comment by Delapouite** [comment]
lenormf contribution for KakouneScript has been merged into linguist in July : https://github.com/github/linguist/commit/ec1b82930dac3b798f9eff05420752caf52463e8

So I guess we can close this issue now.
