### ISSUE TITLE
[c-language] Parens in character literals cause incorrect indentation.

### ISSUE THREAD

**Issue by ghost** [mawww/kakoune#2565]
1. Open a new file w/ C file-type (`kak foo.c` will do the trick)
2. Insert the following:

```c
void foo(void) {
	if ('a' == '(') {}
}
```

3. Note how pressing enter after the closing brace of the if-statement causes spurious indentation

This is a pretty minimal test-case; the bug appears to be that kakoune treats the paren inside the character literal as part of the syntax.

**Comment by GrantMoyer** [comment]
This also occurs for:

```
    if ("foo" == "bar(") {}
```

It should be possible to check for an unmatched `'` or `"` with regex such as `"(([^"]*"){2})*`.
