### ISSUE TITLE
Insert completion menu error with select previous keybinding

### ISSUE THREAD

**Issue by rasch** [mawww/kakoune#2568]
### Steps 

1. Open Kakoune using `kak -n <file>`
2. Enter insert mode and start typing until completion menu opens
3. Press `<c-p><c-p>` 

### Outcome 

The key press `<c-p>` does nothing the first time and the second key press goes to a
previous selection but skips an entry.

I have mapped `<tab>` to `<c-n>` and `<s-tab>` to `<c-p>` on `InsertCompletionShow` hook
in my kakrc. This works as expected but `<c-p>` still doesn't work properly.

NOTE: I built Kakoune from the Master branch in a Docker image using alpine:latest

**Comment by Delapouite** [comment]
I was not able to reproduce. Could it be related to a conflicting mapping you have at the terminal, tmux or even OS level?

**Comment by rasch** [comment]
After looking at this again, it seems that my issue is caused by docker intercepting the <c-p> key press, and not an issue with Kakoune. Thanks!
