### ISSUE TITLE
User modes should be pushed to the mode stack

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#2569]
If I start Kakoune and type `i<a-;>i`, Kakoune winds up with a stack of four modes:

- the base normal mode
- insert mode
- a "temporary" normal mode that exits after one command
- another insert mode.

However, if I have a mapping:

    map global user f ': enter-user-mode -lock foo<ret>' -docstring "foo mode"

...and then I type `,f` to activate it, the mode stack (as revealed by logging ModeChange hooks) looks like this:

- the base normal mode
- a mysterious "next-key" mode

By analogy with the first example, I would have expected something like this:

- the base normal mode
- a "temporary" user mode that exits after one command
- foo mode (not temporary, because of `-lock`)

Because user modes aren't pushed to the mode stack like regular modes, they interact weirdly with hooks and mappings:

- you can't have a hook that executes when exiting a user mode (`ModeChange next-key:normal` is triggered every time a mapping is executed in a locked mode)
- a user mode can't have a mapping that includes an `<esc>` to pop a locked mode

This makes user modes, especially with `-lock`, much less useful than they could otherwise be.

**Comment by Screwtapello** [comment]
This is related to #1855 and maybe #2278.

This issue came from [a forum post](https://discuss.kakoune.com/t/mode-hooks-and-user-modes/169) and also IRC discussion.

**Comment by FlyingWombat** [comment]
Any update on this?

I think it would be useful to have this, so we can enter other modes from within user modes.  
For example:
```
map global user f ": enter-user-mode foo<ret>"
map global foo b ": enter user-mode-bar<ret>"
```
Currently you can make the mapping, but it doesn't really work.

There was also some other discussion [in the forum](https://discuss.kakoune.com/t/avoiding-modifier-chording/107/4?u=flyingwombat) about enhancing user modes, that brought me here.

**Comment by aldanor** [comment]
Interested about it as well, any thoughts/updates on this? (or on the viability of this)

**Comment by laelath** [comment]
I made a pull request that added hooks that expose the stack structure #2545, but @mawww wants to see real use cases before adding yet another hook that handles changing modes.

**Comment by Screwtapello** [comment]
Does PR #2545 include user-modes as first-class modes, or just provide new hooks that represent the same state-transitions as `ModeChange`?

**Comment by laelath** [comment]
It represents the same state transitions, but allows differentiation on whether the mode is being pushed, or being returned to from a mode higher on the stack. I'm not sure how user modes are currently exposed to ModeChange.

**Comment by Delapouite** [comment]
> I'm not sure how user modes are currently exposed to ModeChange.

They are not exposed https://github.com/mawww/kakoune/issues/1855
