### ISSUE TITLE
Colors changed on exit in terminator

### ISSUE THREAD

**Issue by rixx** [mawww/kakoune#2584]
This bug seems to be a weird edge case (that I've encountered with one other interactive terminal tool, too: neomutt). I'm not sure if the fault is with my setup, with kakoune, or with the terminal emulator involved. It goes like this:

Using terminator with zsh and a variaton on the agnoster theme, upon exiting kakoune, some of my terminal colours, but at least `blue` are changed. This change persists after any more uses of kakoune.

Things I know:

- It's happening with terminator, but not with urxvt.
- It's **not** happening with terminator in a tmux session.
- ``TERM`` is ``xterm-256color``

Before the reset:

![deepinscreenshot_select-area_20181120102146](https://user-images.githubusercontent.com/2657547/48763707-1c6a6700-ecae-11e8-92e5-92ecfb904298.png)
![deepinscreenshot_select-area_20181120102437](https://user-images.githubusercontent.com/2657547/48763865-7ec36780-ecae-11e8-841d-4059c1fb8a40.png)

After the reset:
![deepinscreenshot_select-area_20181120102507](https://user-images.githubusercontent.com/2657547/48763889-8f73dd80-ecae-11e8-9b74-c210693fbdc5.png)
![deepinscreenshot_select-area_20181120102534](https://user-images.githubusercontent.com/2657547/48763932-a3b7da80-ecae-11e8-83b7-1ee179182a15.png)

**Comment by Screwtapello** [comment]
Are you using a non-default theme in Kakoune?

When you say "a variation on the agnoster theme" does that variation include changing the colours? If so, to what?

Without running Kakoune, does the command "tput oc" have the same effect?

Can you post screenshots of the output of this command before and after the reset?

    for c in {0..15}; do printf "%s%02d%s" $(tput setab $c) $c $(tput sgr0); done; echo

**Comment by rixx** [comment]
> Are you using a non-default theme in Kakoune?
> 
> When you say "a variation on the agnoster theme" does that variation include changing the colours? If so, to what?

I just tested it and the same issue occurs with the agnoster theme. For reference, my variation of the theme is here: https://github.com/rixx/dotfiles/blob/master/zsh/oh-my-zsh/custom/ttb.zsh-theme

> Without running Kakoune, does the command "tput oc" have the same effect?

Yes, it has exactly the same effect.
 
> Can you post screenshots of the output of this command before and after the reset?

> ```
> for c in {0..15}; do printf "%s%02d%s" $(tput setab $c) $c $(tput sgr0); done; echo
> ```

Before:
![deepinscreenshot_select-area_20181120110525](https://user-images.githubusercontent.com/2657547/48766190-327b2600-ecb4-11e8-8de1-147f640f711c.png)

After:
![deepinscreenshot_select-area_20181120110601](https://user-images.githubusercontent.com/2657547/48766228-458df600-ecb4-11e8-992e-e21cce6d9cec.png)

**Comment by Screwtapello** [comment]
OK, so: terminals have a default set of 256 colours that they load at start up, and whenever they receive the "original colours" control sequence (which is what `tput oc` sends, what Kakoune sends when it exits, and one of the things that `tset` and `reset` send). Judging from your "After" screenshots, your terminal is using the "Tango" palette, which I think is the libvte/gnome-terminal default, and is configured on the "Colors" tab of the terminal profile.

However, your "Before" screenshot shows a different set of colours. I don't recognise it, and it can't be the configured defaults because otherwise they would survive `tput oc`. I don't know where it comes from, or how to get it back. :(

**Comment by rixx** [comment]
Right, I'll open a bug in terminator, then, because it obviously screws around with the color handling. I'm not sure why using tmux makes a difference. Thank you for helping figure this out, and explaining the color thing to me!

**Comment by rixx** [comment]
Just for reference, the tracking issue is https://bugs.launchpad.net/terminator/+bug/1804215

**Comment by Screwtapello** [comment]
tmux is basically its own separate terminal emulator, that insulates the outer terminal from the program inside. I'm not too surprised that tmux changes terminal behaviour.
