### ISSUE TITLE
All video links broken on philosophy page of kakoune.org

### ISSUE THREAD

**Issue by provBarryTolnas** [mawww/kakoune#2589]
Videos on https://kakoune.org/why-kakoune/why-kakoune.html use WebM format and therefore don't play on Safari browsers.

### Steps 

Load https://kakoune.org/why-kakoune/why-kakoune.html in Safari browser.

### Outcome 

<img width="536" alt="image" src="https://user-images.githubusercontent.com/27735368/48954660-64cc9380-eeff-11e8-91a4-5dca30dc4c9b.png">

### Expected 

Video preview image is visible and video plays when clicked.

**Comment by cliffspradlin** [comment]
For what it's worth, they're working for me. In what way are they broken for you?

**Comment by Delapouite** [comment]
Works fine here too (Firefox/Linux). These videos are in the `.webm` format. What's your browser?

**Comment by provBarryTolnas** [comment]
When I reported the problem I was using Mobile Safari from an iPhone.  I just tried on a laptop with Safari 12.0.1 (13606.2.104.1.2) and have the same Issue. I can see now that the issue is [Quicktime (therefore Safari) doesn't support .webm](http://appleinsider.com/articles/10/05/20/steve_jobs_says_no_to_googles_vp8_webm_codec) so Safari users can't view the videos without possibly installing some sort of third-party support.

Feel free to close this issue if it is a conscious decision to not support Safari browser.

**Comment by lenormf** [comment]
Can you see the videos on http://kakoune.org/ ? If I remember correctly I encoded MP4s specifically for Safari users.

**Comment by provBarryTolnas** [comment]
Yes, I _do_ see the videos on the top level homepage at http://kakoune.org. They autoplay and I can see in the HTML source that there are both .webm and .mp4 assets.

```
<video autoplay="" loop="">
                                    <source src="video/align.webm" type="video/webm">
                                    <source src="video/align.mp4" type="video/mp4">
                                    <span tid="error:noVideoTag">Your browser does not support the <code>video</code> element.</span>
                                </video>
```

**Comment by lenormf** [comment]
I re-encoded the videos from the page, could you please verify if you can play them on Safari?

align.mp4           https://my.mixtape.moe/emgbge.mp4
args-swap.mp4       https://my.mixtape.moe/cjwooe.mp4
async.mp4           https://my.mixtape.moe/huwjfc.mp4
camel.mp4           https://my.mixtape.moe/eadqix.mp4
completion.mp4      https://my.mixtape.moe/nstbgc.mp4
cpp-completion.mp4  https://my.mixtape.moe/imhfex.mp4
discoverability.mp4 https://my.mixtape.moe/psgnsj.mp4
external.mp4        https://my.mixtape.moe/hjcscs.mp4
filters.mp4         https://my.mixtape.moe/dqcvoh.mp4
global-replace.mp4  https://my.mixtape.moe/ezyizd.mp4
regroup.mp4         https://my.mixtape.moe/rgtupj.mp4

Command used:

```
$ ffmpeg -y -i "${i}" -c:v libx264 -vprofile baseline -level 3.0 -pix_fmt yuv420p "${i%.*}".mp4
```

**Comment by provBarryTolnas** [comment]
Yes, those look great. I verified each one on Mac OS Safari, and a few of them on Mobile Safari.

**Comment by lenormf** [comment]
Is this still occurring?

**Comment by provBarryTolnas** [comment]
Sorry for leaving this open so long. It fell off my radar.
