### ISSUE TITLE
Long startup time in directories with many files

### ISSUE THREAD

**Issue by shachaf** [mawww/kakoune#2604]
kak takes a long time to start up in directories with many files (e.g. almost 4s in a directory with ~26k files). There seem to be multiple causes. The biggest one is clojure.kak, which has an escaping issue:

```
    static_words="$static_words $(for word in $static_words; do printf 'clojure.core/%s ' "$word"; done)"
```

`static_words` includes `*` so the loop goes through every file in the current directory.

This isn't the only issue because even without clojure.kak startup takes several hundred ms longer to start up in the large directory.

**Comment by mawww** [comment]
I believe this has been fixed now.
