### ISSUE TITLE
static word completion broken for scheme filetype

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2607]
Pressing any key shows completion popup with every candidate:

![image](https://user-images.githubusercontent.com/19470159/49162310-ab752000-f33b-11e8-97c1-917c528a5ddf.png)

**Comment by Screwtapello** [comment]
Looks like the Scheme plugin needs to be updated to use space-delimited items instead of `:`-delimited.

**Comment by andreyorst** [comment]
yes, I've compared it with other kak scripts, however I couldn't make it, because some error shows up about shell redirection. Seems like concatenating messes up with some symbols.
