### ISSUE TITLE
prompt command does nothing inside "eval -draft"

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#2618]
### Steps 

 1. Start a fresh Kakoune with no config:

        kak -n

 1. Type the following command:

        :eval -draft %{ prompt foo nop }<ret>

### Outcome 

Nothing happens.

### Expected 

A prompt "foo" appears, which asks for a string then ignores it.

The same command without `-draft` works fine:

    :eval %{ prompt foo nop }<ret>

**Comment by lenormf** [comment]
Don't you need to pass a `-client` flag to `eval` in that case, to access the UI?

**Comment by Screwtapello** [comment]
`eval -draft -client %val{client}` doesn't behave any differently than `eval -draft`.

If this is a deliberate design limitation, then I guess it should be mentioned in the `:prompt` docs.

**Comment by mawww** [comment]
This does not put the client in prompt mode for the same reason `exec -draft i` does not put the client in insert mode. This mode change takes place in the draft context, if you want to be interacting with the client context, you need either not to use -draft, or to use another `eval -client %val{client}`

**Comment by Screwtapello** [comment]
I wish there were documentation for the different kinds of contexts the same way that `:doc scopes` describes the different kinds of scopes.

I'll make a PR for the `:prompt` docs, at least.
