### ISSUE TITLE
[Feature Request] middle word completion

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2621]
Not sure if it is an issue or a feature request.
Imagine we have some code:
```c
int some_variable;
int variable;

some_variable = 100;
variable = 10;
```

So for example I need to convert a `variable` to `some_variable`, so I place a cursor in the beginning of the last line, and in insert mode type `s`. A popup shows up, with a candidate:
![image](https://user-images.githubusercontent.com/19470159/49601471-f542b380-f996-11e8-8520-f1cf01819123.png)
I'm expecting a completed variant of some_variable on `<c-n>` but get a `some_variablevariable` instead:
![image](https://user-images.githubusercontent.com/19470159/49601526-1a372680-f997-11e8-8bea-7136d1ad6c2a.png)

Vim acts the same here, but a neovim plugin called [deoplete.nvim](https://github.com/Shougo/deoplete.nvim) handles that:
![image](https://user-images.githubusercontent.com/19470159/49601793-da247380-f997-11e8-829b-8a3dda541cb7.png)

The example is dumb, but this situation is happening to me quite often. I've used deoplete for long time and this feature has become something obivious to me. This is really useful, since you don't need to clean the mess after completion. It would be nice to have such behavior in Kakoune. Auto completion should be about efficiency, so a bit of smartness wouldn't harm here.

**Comment by mawww** [comment]
I remember that I wanted that feature, but could not really decide what to do with multiple selections where the suffix did not match (for prefix, we only complete the selection that share their prefix with the main selection).

I am sure we can devise a nice behaviour for that, but thats the main question that made me move to other issues when I was designing the completion behaviour.

**Comment by andreyorst** [comment]
Well. I see it this way: We want every cursor to complete an item from the menu so text after cursor would be the same at every cursor. We look up if any cursor can do reduced completion based on suffix and do a "separate" completion for them with prefix only:

```
█var
█variable
█hello
```
so after completing all
```
some_variable█var
some_variable█ # but we need to remember suffix for this one in case we change candidate
some_variable█hello
```
If we select another candidate and all suffixes doesn't match:
```
something_else█var
something_else█variable
something_else█hello
```

**Comment by andreyorst** [comment]
Just checked bunch of editors. Sublime cant do this.
Atom does this just as I've described:
![mc_compl](https://user-images.githubusercontent.com/19470159/49629342-299b8b80-f9fa-11e8-8bd0-2e24c86f3769.gif)
VSCode seems to disable completion with mc.

**Comment by lenormf** [comment]
This behaviour is not always wanted when inserting data in arbitrary places of the buffer. The `InsertCompletionSelect` hook seems like a good candidate to implement that (it needs the coordinates of the selection when the completion was triggered).

**Comment by andreyorst** [comment]
> This behavior is not always wanted when inserting data in arbitrary places of the buffer

Can you add more details on that? I mean what are non-arbitrary places?
