### ISSUE TITLE
Some typo in README

### ISSUE THREAD

**Issue by benoit-intrw** [mawww/kakoune#263]
Thank you for reorganizing the README file, it's really usefull.

Following some typo I notice

* following line can be found two times
```
<: deindent selected lines Two times 
```
* Bad escape of backquote in following lines, need space around the midle one like this `` ` ` ` ``
```
```: to lower case
```
```
```: select the enclosing grave quoted string
```

* In following block, `highlighter_name` is first use then `highlighter_id`
```
:addhl <highlighter_name> <highlighter_parameters...>

and

:rmhl <highlighter_id>
```

**Comment by mawww** [comment]
Thanks for the issue.
