### ISSUE TITLE
[Question] Tmux Relative Pane Switching

### ISSUE THREAD

**Issue by insipx** [mawww/kakoune#2631]
I'm new to Kakoune and I wanted to setup some commands for relative tmux pane switching. Looking at tmux.kak I saw the built-in `tmux-new-impl` command, and attempted to use that.

```

define-command tmux-move-left -command-completion -docstring "Move to the tmux pane on the left" %{
    tmux-new-impl 'select-pane -L'
}

define-command tmux-move-right -command-completion -docstring "Move to the tmux pane on the right" %{
    tmux-new-impl 'select-pane -R'
}

define-command tmux-move-up -command-completion -docstring "Move to the tmux pane above the current pane" %{
    tmux-new-impl 'select-pane -U'
}

define-command tmux-move-down -command-completion -docstring "Move to the tmux pane below the current pane" %{
    tmux-new-impl 'select-pane -D'
}

define-command tmux-cycle-layout -command-completion -docstring "Cycle through tmux layouts" %{
    tmux-new-impl 'next-layout'
}
```

However the commands don't seem to do anything. Not sure if I misunderstand something about how Kakoune works or these kinds of commands aren't supported in some way.

**Comment by lenormf** [comment]
The `:tmux-new-impl` doesn't just forward whatever argument you pass to it to `tmux`, it also passes a command that spawns a new `kak` client.

You'd need something like the following in your wrapper commands:

```
nop %sh{ env TMUX="${kak_client_env_TMUX}" tmux select-pane -L}
```

**Comment by insipx** [comment]
that worked, thanks!
