### ISSUE TITLE
Consider retiring the `ncurses_wheel_up_button` and `ncurses_wheel_down_button` UI options

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2642]
Hi,

As far as I know, the `ncurses_wheel_up_button` and `ncurses_wheel_down_button` UI options were introduced to make up for the inconsistency of the local ncurses implementation between distributions.

I think everybody has had time to upgrade to ncurses6, maybe we can now remove support for these two options?

HTH.

**Comment by occivink** [comment]
Ubuntu 18.04 still ships an ncurses that has incomplete mouse support. I fully agree with you that they had plenty of time to upgrade, but it's not like these options are hurting anybody.

**Comment by lenormf** [comment]
If some users still need the options, then that's fine, but leaving them if they are unused would not be healthy.

**Comment by Screwtapello** [comment]
Have those options ever been useful to anybody? The problem with the ncurses v5 API is not that it sends *different* button numbers for mouse-wheel events, it's that it *doesn't* send anything for scroll-down.

**Comment by mawww** [comment]
At some point I had a terminal where I would have to set the up wheel button to 3, dont remember exactly which terminal emulator was needing that (along with the ncurses version). In any case, it would be good to remove some code if its not used anymore.

**Comment by lenormf** [comment]
If #2651 doesn't get resolved, I'll close this issue since we still need the option to this day.

**Comment by mawww** [comment]
Seems #2651 got resolved by updating ncurses, so it looks possible to remove those.

**Comment by gustavo-hms** [comment]
I'm on the Solus distro with ncurses version 6.1 and I can't scroll down without setting the `ncurses_wheel_down_button` option.

**Comment by mawww** [comment]
Thanks for giving feedback on that.

**Comment by Screwtapello** [comment]
So far as I can tell, [Solus includes ncurses 6.1, but builds ncurses-5-compatible libraries](https://dev.getsol.us/source/ncurses/browse/master/package.yml$52).

[Apparently](https://dev.getsol.us/R2143:19d899fe1cca77687aa05fd341d2a46103182086) decided to stick with the version 5 ABI in 2017 for compatibility with then-current packages, and nobody's thought about updating it since. It might be worth asking the Solus maintainers to update things.

**Comment by gustavo-hms** [comment]
Thanks for the fast reply. I will do it.

**Comment by lenormf** [comment]
Are the options still relevant with the terminal UI?

**Comment by mawww** [comment]
It would be good to see if anybody uses them, I'd be happy to remove those options.

**Comment by gustavo-hms** [comment]
Well, personally, I don't use those options anymore.

**Comment by Screwtapello** [comment]
Nearly a month ago, I asked on IRC, on Discord, [on the forum](https://discuss.kakoune.com/t/does-anybody-use-the-ncurses-wheel-up-button-or-ncurses-wheel-down-button-ui-options/1831) and [on Reddit](https://www.reddit.com/r/kakoune/comments/p1fcyp/does_anybody_use_the_ncurses_wheel_up_button_or/), and got no positive replies at all. That's not a *guarantee* that nobody uses these options, but I'd be very, very surprised.
