### ISSUE TITLE
The parser gets confused when using %«» strings

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2652]
### Steps 

* `:echo %«a»`

### Outcome 

* `Error: parse error: 0:6: unterminated string '%«...«'`

Note that both brackets characters are the same in the error message.

### Expected 

`a` is printed on the status line.

**Comment by Screwtapello** [comment]
`:help command-parsing` says:

> If a word starts with %X with X a nestable punctuation character (one of (, [, { and <)...

...so I guess it's specifically expecting ASCII punctuation. There's probably a Unicode character property that tells you which Unicode characters are nestable punctuation, maybe some combination of `Bidi_Paired_Bracket` and `Bidi_Paired_Bracket_Type`.

**Comment by lenormf** [comment]
`:echo %’a’` works as expected.

**Comment by lenormf** [comment]
Nervemind, I understand what you mean now.
