### ISSUE TITLE
Impossible to automate prompts

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2656]
From: https://github.com/alexherbo2/portal.kak/blob/master/rc/portal.kak

``` kak
define-command -hidden portal-evaluate-commands -params .. %{
  …
  select-keep-not-matching %reg(L) %{
    …
  }
  # Filter current buffer and *scratch* buffers
  execute-keys "\Q%opt(portal_entry_point)\E|[*](.+)[*]"
}
```

Adding <kbd>Return</kbd> validates the prompt, but with no content.

**Comment by mawww** [comment]
Can you prepare simpler reproduction steps that dont involve the interaction of both select.kak, portal.kak and the provided script ?

That would be good for #2657 and #2658 as well.

**Comment by alexherbo2** [comment]
It was due to `execute-keys` not being executed with `-save-regs` empty.
