### ISSUE TITLE
Improve buffer list handling

### ISSUE THREAD

**Issue by ekie** [mawww/kakoune#266]
@mawww @jkonecny12 

Following up on 6e5e831ce68f51a0e0cf45c433ad20117247b284. As discussed on IRC the implementation can be improved by:

* keeping the list static, ordered by creation
* a single last buffer pointer that is stored per context
* maybe move the cycle_buffer logic to buffer_utils and add gn & gp to the goto context

**Comment by mawww** [comment]
Did not do the gp/gn thing, open an issue for that if you really want it.
