### ISSUE TITLE
Using Kakoune as background-engine for GUIs

### ISSUE THREAD

**Issue by astier** [mawww/kakoune#2660]
Hi. Is there an API which enables using Kakoune as the background-engine for GUIs? Usecases would be:
- Writing Kakoune-GUI
- Writing Plugins for existing editors and IDEs (VSCode, JetBrain products, etc.)

**Comment by mawww** [comment]
Hello,

New GUIs can be implemented through the json-rpc api described in doc/json_ui.asciidoc. This is mostly tailored towards full Kakoune GUI, but combined with the existing remote support (sending arbitrary commands through `kak -p`) it should give pretty a pretty extensive way to use Kakoune from external applications.
