### ISSUE TITLE
Command read which writes text to the buffer

### ISSUE THREAD

**Issue by astier** [mawww/kakoune#2663]
Hi. Would it be possible to implement a command *read* which would behave like *echo*, however instead of printing the received text to the statusline it would write the text into the buffer under to cursor.

**Comment by eraserhd** [comment]
The usual way to do this is `!cat FILE<ret>`.

**Comment by astier** [comment]
Or contradicts it the [Orthogonality](https://github.com/mawww/kakoune/blob/master/doc/design.asciidoc#orthogonality) principle?

**Comment by mawww** [comment]
@astier `exec '!echo test<ret>'` will do the trick.

**Comment by astier** [comment]
Thank you.
