### ISSUE TITLE
Z not applied with exec

### ISSUE THREAD

**Issue by aver-d** [mawww/kakoune#2665]
**Steps**

    $ kak -n  # master e2f2503d (latest)
    :exec Z

**Outcome**
The message `Saved 1 selections to register '^'` appears, but the register is not set: `echo %reg{^}` returns the empty string, and command `z` results in the error message `register '^' does not contain a selections desc`

**Expect**
Register `^` set to `*scratch*@1@0 1.1,1.1` (or similar)

Notes:
In the case where the `^` register is not empty, then `exec Z` has no effect and the register retains its current value.

A variation I tried with a similar effect is adding a (subsequent) mark using `exec <a-Z>a`. Again, there is no change in the mark register when using `exec`.

**Comment by occivink** [comment]
This is because exec automatically restores certain registers by default: "/^!@
You can use `exec -save-regs ''` if you do not want that to happen.

**Comment by aver-d** [comment]
Ah, yes, those special registers… now I remember. Thanks for the information, occivink.
