### ISSUE TITLE
paste previous yank

### ISSUE THREAD

**Issue by dvc94ch** [mawww/kakoune#2675]
Hi,
I couldn't find this in the docs, but in spacemacs I was able to `y` `y` `p` `<c-p>` to get the first yank.
Thanks

**Comment by Screwtapello** [comment]
You may be interested in @alexherbo2's [yank-ring](https://github.com/alexherbo2/yank-ring.kak) plugin.

**Comment by dvc94ch** [comment]
@alexherbo2 That is awesome! thank you

**Comment by alexherbo2** [comment]
I plan to remove [Select] dependency and use an incremental prompt with <kbd>Tab</kbd> to cycle through the matching yanks.

[Select]: https://github.com/alexherbo2/select.kak
