### ISSUE TITLE
disable keys

### ISSUE THREAD

**Issue by L-Briand** [mawww/kakoune#2687]
Is it possible to disable a key ?  
Example: disabling `<left>`, `<right>`, `<up>`, `<down>` keys in insert mode.

**Comment by SolitudeSF** [comment]
`map global insert <left> ''` probably

**Comment by Delapouite** [comment]
You can also map to the `nop` command to be more explicit.

**Comment by Delapouite** [comment]
@L-Briand can this issue be closed?

**Comment by zigmd** [comment]
hello @Delapouite, I'm getting started with Kakoune and would like to know the complete `nop` command to disable arrow keys in normal mode.

**Comment by Screwtapello** [comment]
If you're just getting started with Kakoune, don't worry about disabling the arrow keys, Kakoune doesn't have the same prejudice against them that the vi community has.

If you still want to disable them, the command in https://github.com/mawww/kakoune/issues/2687#issuecomment-453825408 still works. If you want to disable them in normal mode rather than insert mode, change "insert" to "normal" in that command.

**Comment by zigmd** [comment]
thanks @Screwtapello the command works. 

On using an arrow key, I'm seeing "no search pattern" at the bottom left of the buffer. Is there a way I can not show this message (like `.` and `,` which don't do anything but also don't show a message)?

**Comment by Screwtapello** [comment]
Are you trying something like this?

    map global insert <left> nop

That does not map to the `nop` command, that maps to the sequence of keys:

- `n` - jump to next match of the last search pattern
- `o` - open a new line below the cursor and enter insert mode
- `p` - type a `p` (in insert mode)

The behaviour of `n` is why you're getting the "no search pattern" error.

The easiest solution is to just change `nop` back to an empty string, a described in the comment I linked to. To actually invoke the `nop` command, you need the mapping to open the prompt with `:` (just as you would interactively), type `nop` and hit Return:

    map global normal <left> ':nop<ret>'

That does more work for no particular benefit, so I'd just go with the empty string myself.

> like `.` and `,` which don't do anything

Actually, both of them do something, but it may not be obvious in simple testing.

`.` repeats the last change made in insert mode, usually by inserting the same text again. You can test this with `ihello<esc>.`

`,` drops all secondary selections, leaving only the main selection. You can test this with `ihello<esc>...xso<ret>aworld<esc>,a!<esc>`

**Comment by zigmd** [comment]
thanks for the breakdown !
