### ISSUE TITLE
Counter-intuitive buffers order

### ISSUE THREAD

**Issue by vivien** [mawww/kakoune#2705]
When opening multiple files with e.g. `kak 1.txt 2.txt 3.txt 4.txt`, Kakoune will correctly open buffer *1.txt* first, but then `:buffer-next` will jump to buffer *4.txt*, then *3.txt*, then *2.txt*, then back to *1.txt*.

`:buffer-previous` would iterate from buffer *1.txt* to *2.txt*, then *3.txt* and *4.txt*.

The expected behavior would be the opposite: from buffer *3.txt*, `:buffer-next` must jump to buffer *4.txt*, while `:buffer-previous` must switch to buffer *2.txt*.

**Comment by Delapouite** [comment]
Related issues about buffers order/history https://github.com/mawww/kakoune/issues/2559
