### ISSUE TITLE
Weird regex highlighter behavior

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2711]
I've used to have these highlighters in my C/Cpp/Rust/Java buffers:
```kak
hook global WinSetOption filetype=(c|cpp|rust|java) %{
    add-highlighter buffer/functions      regex \w+(\h+)?(?=\() 0:function
    add-highlighter buffer/child          regex ((?<=\.)|(?<=->))[a-zA-Z](\w+)?\b(?![>"\(]) 0:child
    add-highlighter buffer/child_function regex ((?<=\.)|(?<=->))[a-zA-Z](\w+)?(\h+)?(?=\() 0:function
    add-highlighter buffer/namespace      regex [a-zA-Z](\w+)?(\h+)?(?=::) 0:namespace
}
```
But after latest update all text became the `nampesace` color for me. I've checked this regex `[a-zA-Z](\w+)?(\h+)?(?=::)` in the search, and it only matches everything before`::` in `this_kind::of_pattern`, but in the highlighter section it basically applied to everything. Furthermore, if I remove the `namespace` highlighting, all text will be colored like `function`, and if I remove `function` it will be colored as `child`. Something changed in highlighters in latest update, but looking at the docs it seems the same. `0` still matches whole regex pattern, and capture groups are numbered from `1`. I don't use capture groups names, since I can parse regexes by looking on those fairly easily.

That's how it looks with latest commit 3e89148d74c3d4a9ba075b0d9218457e845982e6:
![image](https://user-images.githubusercontent.com/19470159/51861990-a7bb4500-234e-11e9-9256-51060a690547.png)
That's how it looked in previous stable and current stable:
![image](https://user-images.githubusercontent.com/19470159/51862478-c837cf00-234f-11e9-9255-51a2cec22dc0.png)

Problem commit: 77b1216aceb0a1642ee90fa68963817cc9949fa7
Before it everything works fine.

**Comment by andreyorst** [comment]
Problem commit: 77b1216aceb0a1642ee90fa68963817cc9949fa7
Before it everything works fine.

**Comment by andreyorst** [comment]
No it's still the same.

**Comment by andreyorst** [comment]
Minimal configuration to reproduce the issue:

```
set-face global child rgb:fb4934,default+b
set-face global delimiters rgb:aa3a03,default
set-face global namespace rgb:be8019,default

hook global WinSetOption filetype=(c|cpp|rust|java) %{
	add-highlighter "buffer/%val{hook_param_capture_1}_functions"      regex \w+(\h+)?(?=\() 0:function
	add-highlighter "buffer/%val{hook_param_capture_1}_child"          regex ((?<!\.\.)(?<=\.)|(?<=->))[a-zA-Z](\w+)?\b(?![>"\(]) 0:child
	add-highlighter "buffer/%val{hook_param_capture_1}_child_function" regex ((?<!\.\.)(?<=\.)|(?<=->))[a-zA-Z](\w+)?(\h+)?(?=\() 0:function
}
```

minimal file to test:
```
int main()
{
        foo.bar;
        foo.bar().baz;
} 
```

**Comment by mawww** [comment]
Should be good now

**Comment by andreyorst** [comment]
Thanks!
