### ISSUE TITLE
Aliases should be available in prompt mode only

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2712]
Aliases are needed to simplify writing commands in prompt mode, where horisontal space is limited by screen width and vertical space is limited by single line. Aliases also make writing commands in prompt mode a lot faster, because we don't have to write long names like `define-command`. 

In scripts however, we don't limited with single line, and can have really long lines just fine.  So the only meaning of aliases there is to write shorter commands. But
- this is error prone
- aliases doesn't have syntax highliting
- aliases can be misunderstood in shell expansions when reading, like `set` in shell and `set-option` aliased to `set`.

And user can break all scripts that use aliases by simply changing or removing any alias.
For example I've broken my whole setup just by placing `unalias global def` at the beginning of kakrc. I also use plugin [edit-or-dir](https://github.com/TeddyDD/kakoune-edit-or-dir) by @TeddyDD, and I've aliased it to `e`, to call ot from command line. What will happen if some plugins decide to call `e` instead of `edit` to open files? Hopefully they won't break because `edit-or-dir` works fine, but that's doesn't guarantee anything.

In my opinion aliases should be available only in prompt mode, and nowhere else. Vim also have aliases (abbreviations), but the are not allowed to use inside vimscript, and everyone is fine with it. Sure this change will break hell lot of plugins, but it is better to do it now, and don't have problems later.

**Comment by Screwtapello** [comment]
Aliases are also a way for users to configure how things work. For example, `terminal` is an alias for `x11-terminal`, `tmux-terminal-window`, or `screen-terminal-window` depending on what environment Kakoune is running in. It's specifically an alias so that user configuration can override what it does, and have all their terminal-using plugins automatically respect that decision without having to update them individually.

On the other hand `define-command` has an `-override` switch that could be used for the same thing, and there's precedent in that `execute-keys` does not respect mappings.

On the other, other hand, since `define-command -override` is a thing, preventing scripts from using aliases doesn't make them much less fragile, since a user could override important commands like `terminal` anyway.

**Comment by andreyorst** [comment]
my main complain is more about Kakoune's aliases, that are not commands on the first place, like:
```sh
def # python has def for functions
set # sh has set
rmhl
addhl
eval # sh has eval command
```

I don't see why they are either mutable, or even exist

**Comment by andreyorst** [comment]
`terminal` can be implemented as a command instead of an alias with `-override`, and if user uses `override` switch it is explicitly mentioned by him, that he is overriding something. When using alias we'rejustsaying that we aliasing something,it shouldn't break anything. Scripts should rely on commands insteadof aliases.

**Comment by andreyorst** [comment]
BTW, using `define-command terminal %{echo vaiv}` when `terminal` alias already defined doesnt result in any error, and we can't use this command until we remove alias.

**Comment by mawww** [comment]
Aliases have a few features that make them different from commands:

* They are scoped, which means aliases can redirect to different commands say based on filetype (by setting the alias in buffer or window scope).
* They are immediately linked to the command, meaning you get the command completion, and information when using the alias (using `define-command my-alias -params .. %{my-command %arg{@}}` would not provide my-command completion, nor its info box...).

I agree there are pain points with them, or even with command overrides (did you know, you can override built-in commands and they are lost foreever)... I'd be happy to improve the design, or to merge them into commands (make commands scoped, add a way to easily define a "forwarding command" that inherists docstring and completion from the underlying one).

**Comment by Delapouite** [comment]
> […] merge them into commands ([…] add a way to easily define a "forwarding command" that inherits docstring and completion from the underlying one)

fishshell has a similar approach. The `function` command (equivalent of kakoune's `define-command`) has a `--wraps` flag: 

```
-w WRAPPED_COMMAND or --wraps=WRAPPED_COMMAND causes the function to inherit completions from the given wrapped command.
```

https://fishshell.com/docs/current/commands.html#function

So in the end, as they recap in the [doc](https://fishshell.com/docs/current/commands.html#alias): 
```
alias rmi="rm -i"

# This is equivalent to entering the following function:
function rmi --wraps rm --description 'alias rmi=rm -i'
    rm -i $argv
end
```
