### ISSUE TITLE
Assigning register `l` to a macro does not play the macro after n attempts

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#2728]
### Steps 

Record the macro by assigning `l` <key>

     `"` `l` `Q` test `<esc>`

### Outcome 

test 

But after _n_ attempts, the macro for `l` is not replayed. No longer plays.

### Expected 

test 

Regardless of _n_ replays

Sorry if this is something that I may have overlooked on the documentation.
For example, `<a-l>` moves to line end, whereas `<ctrl-l>` redraws the screen
on Normal mode, and `l` by itself to the right. But I haven't used any key combinations.

The above was tested on different terminals and the outcome was always the same.

**Comment by Screwtapello** [comment]
Just to clarify:

- you record a macro to insert the word "test" into register `l`, something like `"lQitest<esc><esc>`
- you repeatedly replay the macro with `"lq` over and over
- eventually replaying the macro stops working

When it stops working, is there any particular error message? Does it insert no text? The wrong text?

**Comment by nonumeros** [comment]
> When it stops working, is there any particular error message? Does it insert no text? The wrong text?

There are no error messages. No text is inserted. 

Consistency is also a problem.  Initially, the macro played successfully, and then after the second or third attempt, it stopped working altogether. 

I started a new session, and even under a different terminal, it exhibited however, the same behavior than before. Of course, other registers were used at the time, and that was precisely the reason that caught my attention. Other registers - unlike `l` - played correctly, or as expected.

 I reverted to hunt and peck style typing to make sure I wasn't carelessly entering the keystrokes. But to no avail.

**Comment by lenormf** [comment]
Could you reproduce the issue in `kak -n`? How many times does it take (more or less) to reproduce the issue?

I couldn't reproduce the issue after replaying the macro about 20 times.

**Comment by nonumeros** [comment]
> Could you reproduce the issue in kak -n? 

I can't reproduce with the `-n` option. By reading the manual tthe `-n` option does not load any resource files. Thanks. Didn't even think about it because my init file is comprised of only a few items.

I noticed though by commenting out  - so far
      
     hook global WinCreate .* %{
	     auto-pairs-enable
	     }

Oddly enough, a few days ago, the macro with register `l` would replay for say two or three times and then stop. Never received any error messages whatsoever.

A few minutes ago  though, the same thing happened as before, except it was only once. One time replay, then stop. This is of course, with the above on the init file.
