### ISSUE TITLE
How to make it support Chinese characters? 

### ISSUE THREAD

**Issue by YuMu233** [mawww/kakoune#2729]
How to make it support Chinese characters? I use it to get garbled, is it a coding problem?

**Comment by Screwtapello** [comment]
What kind of garbled? Can you post a picture?

Kakoune supports Unicode, so it *should* handle Chinese characters just fine as long as your terminal supports them and you have appropriate fonts installed.

I don't know how to read or write Chinese myself, but here's a screenshot where I pasted some text from Chinese Wikipedia into Kakoune:

![screenshot from 2019-02-08 01-05-45](https://user-images.githubusercontent.com/1450918/52416467-c2a36b80-2b3d-11e9-97a8-40d18e7643e8.png)

**Comment by YuMu233** [comment]
This is a screenshot. Thank you for your answer. I think it should be a problem with my terminal. Thank you. 
[https://i.loli.net/2019/02/09/5c5e332b7ce6a.png](url)

**Comment by Screwtapello** [comment]
The red-question-mark-in-a-box shows up when the file's contents aren't proper UTF-8 Unicode.

If you need to edit files written in another encoding (BIG5? GB2312? I'm not sure) you may need to convert them to UTF-8 first:

    iconv -f big5 -t utf-8 input.txt > output.txt

If that red question mark was a result of trying to type text, you might need to ensure your terminal/IME is running in a UTF-8 based locale. The `/usr/bin/locale` command should tell you what locale you're running - if it doesn't mention "UTF-8" anywhere, it's not a UTF-8 based locale.

**Comment by YuMu233** [comment]
Thank you, it works. I apologize for my recklessness. @Screwtapello
