### ISSUE TITLE
Kakoune hangs, when shell expansion requires input

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2734]
This is related to my [plugin manager][1]. Recently, these two issues were opened: [andreyorst/plug.kak#47][2], and [andreyorst/plug.kak#50][3].

In short, when I try to clone git repository via https, and this repository is private, git asks for username and a password to authenticate. We can't input those directly from Kakoune, but it shows the prompt inside the buffer for some reason and hangs, like so:

![image][4]
(the 1st line)

Any key-press clears the prompt, and after that Kakoune becomes irresponsible, until killed, or timeout reached inside git command.

I'm currently adding a workaround by testing `GIT_TERMINAL_PROMPT` to be empty, and if it is I'm setting it to `0`, but if it is possible to migrate this issue without setting `GIT_TERMINAL_PROMPT` to `0`, or modifying `GIT_ASKPASS` directly, I'd like to add this to plug.kak. Or maybe this should be handled by Kakoune instead in a more generic state?

[1]: https://github.com/andreyorst/plug.kak
[2]: https://github.com/andreyorst/plug.kak/issues/47
[3]: https://github.com/andreyorst/plug.kak/issues/50
[4]: https://user-images.githubusercontent.com/19470159/52638872-fb4b9800-2ee3-11e9-99bf-2be1c333ad9a.png

**Comment by lenormf** [comment]
Related #660.

**Comment by andreyorst** [comment]
Closing as duplicate.
