### ISSUE TITLE
No way to access `%val{count}` from an object mode mapping to a command

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#2735]
### Steps 

I've tried the following:
```
map window object e '<esc>: clojure-text-object element %val{count}<ret>'
```

And also accessing `$kak_count` in a shell expansion inside clojure-text-object.

I invoke this with `2<a-a>e`.

### Outcome 

The value is always `0`.

### Expected 

The value should be `2`.

**Comment by Delapouite** [comment]
Possibly related to https://github.com/mawww/kakoune/issues/2635
