### ISSUE TITLE
SIGSEGV on WinDisplay hook

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2737]
```
'Received SIGSEGV, exiting.
Pid: 31100
Callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x19) [0x5616ea1229e9]
kak(_ZN7Kakoune14signal_handlerEi+0x65) [0x5616ea1fa515]
/usr/lib/libc.so.6(+0x37e00) [0x7f272861de00]
kak(_ZN7Kakoune6BufferD1Ev+0x46) [0x5616ea122ec6]
kak(_ZN7Kakoune13BufferManager18clear_buffer_trashEv+0x5d) [0x5616ea130d1d]
kak(_ZN7Kakoune10run_serverENS_10StringViewES0_S0_NS_8OptionalINS_11BufferCoordEEENS_11ServerFlagsENS_6UITypeENS_10DebugFlagsENS_9ArrayViewIKS0_EE+0xac1) [0x5616ea201931]
kak(main+0x1d22) [0x5616ea120852]
/usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f272860a223]
kak(_start+0x2e) [0x5616ea12103e]
```

This may be very hard to reproduce, but I don't want to lose this message. I'll update the issue when there will be more info.

In short, I'm developing a plugin, and I receive this error when I try to declare a `WinDisplay` hook with plugin's custom command.

Any suggestions on possible debug way, so I could provide additional info in case I wouldn't able to provide a step by step repro recipe?

## Edit
Minimal repro script:
```kak
hook global WinDisplay .* %{
    foo
}

define-command foo %{ evaluate-commands %sh{
    tmp="${TMPDIR:-/tmp}/test"
    [ ! -d $tmp ] && mkdir $tmp
    fifo="${tmp}/fifo"
    mkfifo $fifo
    printf "%s\n" "try %{ delete-buffer *test* }
                   edit! -fifo ${fifo} *test*
                   try %{ hook -always global KakEnd .* %{ nop %sh{ rm -rf ${tmp} } } }
                   map buffer normal '<ret>' '<a-h>;/:<c-v><c-i><ret><a-h>2<s-l><a-l>:<space>test-jump $kak_bufname<ret>'"
}}
```

If I remove any line from `printf` call the issue dissapears.

**Comment by andreyorst** [comment]
on Kakoune v2019.01.20 I recieve this message:
```
free(): invalid size
~                   [1]    8302 abort (core dumped)  kak ~/.config/kak/kakrc
```

**Comment by mawww** [comment]
I have been taking a look, its a tricky one, basically hooks end up running on objects that are dying, and the current "buffer trash" and "window trash" that defer those objects destructions is not enough to avoid the bugs... Properly fixing it would require to reorganize all that and ensure hooks run at more controlled times, which is a sizeable amount of work, but I think would improve robustness.

**Comment by andreyorst** [comment]
I've lost count on how many segmentation faults I've seen during development of the plugin.
Basically when some hook tries to execute deletion of buffer, another hook executes (even if I remove those before deletion) and tries to create such buffer, and Kakoune crashes.

**Comment by mawww** [comment]
Hooks are pretty tricky, because once you run one anything could have happened, the buffer you were using might have been deleted, the context might have switched buffer, the window might be gone as well, any option might have changed value or got removed... Many recent crashes we had are linked to that, some Kakoune state being mutated by a hook when we did not expect it (a pretty common case is a list we are iterating on that gets mutated by a hook).

**Comment by andreyorst** [comment]
Yeah. I've simplified the code, and removed some hooks so the plugin is pretty stable right now. The only thing left is this situation #2741, when user closes tagbar improperly.
