### ISSUE TITLE
[Feature request] add -skip switch to edit command

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2739]
I'm making a plugin called tagbar.kak, which will work similar to [tagbar](https://github.com/majutsushi/tagbar) Vim plugin. Interesting thing about Vim's tagbar is that it acts like a panel. We can't select tagbar buffer with `:bnext` or `:bprevious` commands (unless some weird bug happens).

So to achieve similar panel-like behavior (in tmux it would use split, and in X it will use a separate terminal) I need a way to skip `*tagbar*` buffer when cycling with `:buffer-next` or `:buffer-previous`. I'm aware of #1059, and about a [possible workaround](https://github.com/mawww/kakoune/issues/1059#issuecomment-269023271), but I don't think that plugin should override builtin command just to migrate a buffer, that is created by a plugin.

So It would be cool if we could mark some buffers as skipable, unless they are called explicitly, with `:buffer *bufname*`. Just like `*debug*` buffer behaves.

For example `edit -skip -fifo path/to/fifo *fifobuffer*` will create a buffer that will not appear when user executes `:buffer-next` or `:buffer-previous` commands, but `buffer *fifobuffer*` will display it.

**Comment by lenormf** [comment]
I think you need `:edit -debug`, buffers with the debug flag are not cycled over with `:buffer-{next,prev}`.

**Comment by occivink** [comment]
What about renaming `-debug` to `-hidden` so that it mirrors `define-command` and `declare-option`? Besides, it's not clear what a debug buffer is supposed to help you debug, and why that would cause it to be hidden from the buflist.

**Comment by andreyorst** [comment]
> I think you need `:edit -debug`, buffers with the debug flag are not cycled over with `:buffer-{next,prev}`.

I've thought that this switch is used to create new `*debug*` buffer in case you've deleted default one with `delete-buffer *debug*`, so you still could see output of commands like `echo -debug "vaiv"`. 

> What about renaming `-debug` to `-hidden`

If this is the true meaning of `-debug` then it should be renamed, as original name is kind of misleading.

**Comment by mawww** [comment]
A debug buffer does a bit more than being ignored in buffer cycling.

* Their content is not considered for word completions with `word=all` completers
* Hooks are not always run (like the BufCreate/BufClose hooks)
* Display profiling is disabled

I guess adding a hidden flag would make sense to split that behaviour out.

**Comment by andreyorst** [comment]
> - Their content is not considered for word completions with word=all completers
> - Hooks are not always run (like the BufCreate/BufClose hooks)
> - Display profiling is disabled

Hm. Now when you said that, I guess that `-debug` buffer suits me better, since I don't need completions from panel-like buffer. However I'd like to have ability to watch for that buffer with `BufClose` and `WinClose` hooks, so if user closes them manually, hook could call a command that removes global hooks related to that buffer. Is that possible?

**Comment by andreyorst** [comment]
Perhaps I can close this, since I'm fine with what `-debug` provides. Although the name is a bit misleading, I don't think that this is an issue.
