### ISSUE TITLE
prompt shell-script-candidates and completions

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2754]
currently `prompt` command supports these completion variants:
```
-file-completion
-client-completion
-buffer-completion
-command-completion
-shell-completion
```
Why these two aren't included?
```
-shell-script-completion <arg>
-shell-script-candidates <arg>
```
I wanted to make simple project handler using prompt, but wasn't able to list project names with shell script.

**Comment by laelath** [comment]
I've attempted to do this, but it appears there are some structural differences with how the command and prompt completions work, and I lack enough knowledge of kakoune's completion system to get it working non-jankily. I agree this would be a good feature to add.
