### ISSUE TITLE
Shell variable substitutions highlighted as comments

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2763]
**Example**

``` sh
echo ${parameter#word}
```

`#word}` is highlighted as a comment.

**Comment by andreyorst** [comment]
Interestingly enough,
```sh
echo "${parameter#word}"
```
Is highlighted as a variable in quotes: 
![image](https://user-images.githubusercontent.com/19470159/53726399-ed53bc00-3e7e-11e9-9843-7688da623ded.png)
