### ISSUE TITLE
Setting the terminal alias for iTerm

### ISSUE THREAD

**Issue by grtlr** [mawww/kakoune#2764]
### Steps 
Run `kak` in iTerm (kakoune v2019.01.20) _without tmux_
Call `:new`

### Outcome 
`The 'terminal' alias must be defined to use this command`

I have tried setting it to `iterm-terminal-horizontal`, `iterm-terminal-tab` and `iterm-terminal-window`, but it leads to a broken pipe in each scenario.

### Expected 
According to `iterm.kak`:

> The default behaviour for the `new` command is to open an vertical pane in
> an iTerm session if not in a tmux session.

It seems like other terminal specific files, such as `kitty.kak` define the `terminal` alias. What would the eqivalent be for iTerm?

Thank you very much!

**Comment by occivink** [comment]
This was probably caused during #2617, I did some refactor but wasn't able to test the iterm script properly. The automatic aliasing to 'terminal' is just a simple omission, but the broken pipe is probably due to some wrong escaping logic somewhere.
If you have time to do some testing I can try to fix this.

**Comment by grtlr** [comment]
I would love to help you fix this!

Running `iterm-terminal-horizontal kak -c %val{session}` also leads to a broken pipe. Unfortunately, the window closes, before I can grab further information.

**Comment by occivink** [comment]
Ok, then I'll set up a branch on my fork and ping you when I have some changes for you to test, I'll try to get started on this this evening

**Comment by grtlr** [comment]
That sounds great! I have set up profiles for the current stable release and the nightly channel of iTerm—hopefully, we only have to do this once 😄.

**Comment by grtlr** [comment]
I think we can close this, as PR #2768 has been merged.
