### ISSUE TITLE
Client (dis)connected hooks

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2765]
There was a discussion of it here #1716, and I'm experiencing similar problems wich require this feature, it as described [here](https://discuss.kakoune.com/t/how-to-get-client-name-after-startup/333/5?u=andreyorst). 

There's a PR #2500 for this feature, but no active issue, so I'll create one.

**Comment by andreyorst** [comment]
I guess c8839e79041ef37849a4cb8ac5017eadc8ec9653 fixes this as well, right @mawww?

**Comment by mawww** [comment]
Yep, it should.

**Comment by andreyorst** [comment]
Super, `ClientClose` hook works perfectly! Thanks!
