### ISSUE TITLE
Color scheme reverts after close

### ISSUE THREAD

**Issue by DomHudson** [mawww/kakoune#2771]
### Steps 
1. Open kakoune
2. Set colorscheme through the `colorscheme` command.
3. Close kakoune.
4. Open kakoune.

### Outcome 
When reopening kakoune the colour scheme has changed back to the default.

### Expected 
I expect either for it to change back but for their to be a clear way to set it permanently (apologise if I have missed this?) or for the `colorscheme` command to persist between sessions.

**Comment by Screwtapello** [comment]
To set the colour scheme permanently, put a line like:

    colorscheme gruvbox

into your `~/.config/kak/kakrc` file.

**Comment by DomHudson** [comment]
Thank you!
