### ISSUE TITLE
get a key from a mapping

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2776]
something like `%val{key}` expansion would be usable in mappings. For example if we call a command from a mapping that should behave slightly differently depending on what key was pressed.

```sh
map global normal "a" ": command %val{key}"`
map global normal "<tab>" ": command %val{key}"`
```
instead of:
```sh
map global normal "a" ": command 'a'"`
map global normal "<tab>" ": command 'tab'"` # we also need to remove the `<' and `>' from
                                             # the key because it will cause an error
                                             # and handle it inside a command.
```

Or `%val{key}` could store the last key, so it wouldn't necessary to pass it via parameter.

**Comment by Delapouite** [comment]
Also, you can not really depend on the `RawKey` hook to try to emulate this feature since all "last key typed" are not recorded: https://github.com/mawww/kakoune/issues/2523
