### ISSUE TITLE
Mouse not working on xfce4-terminal

### ISSUE THREAD

**Issue by jcpetruzza** [mawww/kakoune#2778]
When I run `kak` from `xfce4-terminal` and enable the mouse, clicking and scrolling result in gibberish being input. The mouse works fine for me on `vim` started from the same terminal, and on `kak` started from `xterm`.

### Steps 

1. Launch `xfce4-terminal` and run `kak`
1. Enable the mouse with `set -add global ui_options ncurses_enable_mouse=yes`
1. Switch to insert mode and type a few lines
1. Without leaving insert mode, click on any of the previous lines

### Outcome 

Something like `M $"M#$"` is inserted where the cursor was

### Expected 

The cursor moved where clicked, without any text being input :slightly_smiling_face:

**Comment by Screwtapello** [comment]
You shouldn't have to manually enable the mouse, it should be enabled by default (at least in the stock version of Kakoune; if you're using a build from a Linux distro they might have changed things).

`xfce4-terminal` is built on `gnome-terminal`'s `libvte`, which very definitely supports all the cool mouse protocols.

What is the `$TERM` environment variable set to, before Kakoune starts? For `libvte`, it should probably be the first available option out of`vte-256color`, `xterm-256color`, `vte` or `xterm`.

**Comment by jcpetruzza** [comment]
Yes, mouse is enabled by default; I had to disable it first thing from `kakrc` or it would make kakoune hard to use, so it crept in my steps to reproduce, sorry for the confusion!

My `TERM` is set to `xterm-256color`, I get the same behavior with `xterm` or `vte`.

I'm using kakoune from nixkpgs and see this behavior both under nixos and ubuntu. However, when built from sources on ubuntu, the mouse did work. I see the nixpkgs version is built with ncursesw 6 while ubuntu's with ncursesw 5, but don't know if this makes any difference.

**Comment by mawww** [comment]
Gave it a try here, I can enter insert mode and click around fine on Fedora 29 with ncurses 6. I am not sure what could be causing this issue, is the mouse support working fine outside of insert mode ?

**Comment by jcpetruzza** [comment]
It doesn't work in normal mode either. Insert mode just makes it more reproducible: in normal mode, clicking the mouse or scrolling will also send garbage as if it were keyboard input; so sometimes nothing happens (the garbage results in an invalid command), and sometimes the garbage manages to switch on insert mode and then you see the rest of the garbage.

Thanks for trying to reproduce, btw. I've seen this in two boxes, the only thing in common being i) xfce, and ii) kakoune being installed using [nix](https://nixos.org/nix/). I've seen it working on xfce on one of the boxes after building from source (Ubuntu),  so I guess it has to be related to the way it's packaged for nix?

**Comment by mawww** [comment]
From a quick look at the code, my initial idea is that ncurses does not recognize those sequences (`M $"M#$"` assuming this is what you actually got on the term) as mouse events, which would point to the terminfo data not matching the terminal. Could you experiment with other values for TERM, based on what you have in your terminfo database on the machine ?

**Comment by Screwtapello** [comment]
In particular, some versions of ncurses use the `XM` terminfo string (see `infocmp -1x | grep XM=`) to enable mouse reporting, but it's possible that the your terminal's `XM` string sets up a mouse mode that ncurses doesn't know how to interpret.

Looking at xterm's [Mouse Tracking mode docs](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking), it seems ncurses is enabling  "Normal tracking" or maybe "Button event tracking" modes, so`M $"` would be a left-mouse-down event at column 4, line 2, and `M#$"` would be a mouse-up event at the same coordinates. This is odd for two reasons:

  - if you're using a vte-based terminal, ncurses should be able to use the modern SGR mouse tracking mode, which reports all the events and doesn't break in terminals wider than 224 columns
  - "Normal tracking" is the oldest and best supported mouse-tracking mode, so it's surprising that ncurses doesn't recognise it.

**Comment by jcpetruzza** [comment]
> so `M $"` would be a left-mouse-down event at column 4, line 2, and M#$" would be a mouse-up event at the same coordinates

I can confirm this is indeed the case. It is clicking on line 2, col 4 that produces `M $"M#$"`.

What I find puzzling is that the mouse does work in vim, on the same terminal; and both kakoune and vim are using the same version of ncurses (ncursesw 6.1)

**Comment by Screwtapello** [comment]
Vim doesn't actually use ncurses, it only uses the lower-level terminfo library (`libtinfo.so.6`) and re-implements much of ncurses' functionality itself. That means Vim has to do a lot more work, but it also means Vim can hard-code support for various things that aren't provided in the standard terminal descriptions.

**Comment by jcpetruzza** [comment]
Yes, was trying `ltrace` to compare the outputs and see if anything obvious would show up and noticed just that... :)

**Comment by jcpetruzza** [comment]
Given that vim isn't really using ncurses, I looked for another ncurses-based program with mouse support I could try, and I now think that this is not a kakoune problem: I can get exactly the same weird behaviour with `htop`: mouse actions are interpreted as keyboard input on xfce4-terminal, but work well on xterm...

Thanks for your help!

**Comment by jcpetruzza** [comment]
In case anyone ever lands here, the issue seems to be that curses 6.1 made changes to the xterm definition that break mouse support in vte 0.28 (the version my xfce4-terminal was linked to). See [this discussion](https://bugzilla.redhat.com/show_bug.cgi?id=1573676) for more details.
