### ISSUE TITLE
Close popup command

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2780]
Popup completion in Kakoune is shown in insert mode almost always when the cursor is next to anything that can be completed. For example, if we put our cursor `█` to the end of the `alg` word and enter insert mode, the completion popup will appear.

```
algorithm
alg█
```
![image](https://user-images.githubusercontent.com/19470159/54187922-a473b700-44bf-11e9-8fe0-5be2b76ac4e3.png)

My <kbd>Tab</kbd> key is remapped to cycle completions, and usually it is fine, because I use spaces for alignment, but sometimes I want to place `\t` character after a word, when I edit assembly files:
![image](https://user-images.githubusercontent.com/19470159/54188073-00d6d680-44c0-11e9-820f-fe92866e4ffe.png)
Because we use such formatting in assembly at work. And here's a problem: there's no way to close popup but to leave insert mode as far as I know. In Vim I could use arrow key to move to the next symbol which canceled popup as it appears only on insertchar hook. In Emacs there's a <kbd>Ctrl+g</kbd> shortcut that cancels everything, including popup:
![image](https://user-images.githubusercontent.com/19470159/54190584-29150400-44c5-11e9-8803-24f73ea8701e.png)

To workaround the problem I press <kbd>Ctrl+v</kbd> and hit <kbd>Tab</kbd> to insert a tab character, but I don't think that this is a perfect solution. Often I just want a popup to disappear because I can't see the code behind it, but I don't really want to leave insert mode because I was in the middle of typing.

**Comment by Delapouite** [comment]
What about `ctrl+o` in insert mode? Does it fit your need?

**Comment by andreyorst** [comment]
It disables completion entirely until I exit insert mode. Although it can be used, but I don't think that this is a proper way.

**Comment by andreyorst** [comment]
Also, despite Emacs nature, <kbd>Ctrl</kbd> + <kbd>g</kbd> seems a good candidate to cancel various things, and it's not bound to anything now. Like <kbd>Ctrl</kbd> + <kbd>[</kbd> works as <kbd>Esc</kbd>, <kbd>Ctrl</kbd> + <kbd>g</kbd> could represent something like canceling current operation.

**Comment by mawww** [comment]
I am not sure <kbd>Ctrl</kbd>+<kbd>g</kbd> would work that well, because insert mode completion will retrigger as soon as a new character is inserted or the cursor moves. For it work nicely it would need to have a concept of "completion session" to disable itself just during that time, but defining what a "completion session" is seems pretty hard (like, could be until the cursor leaves the current word), but that adds quite a bit of smartness to insert completion, which I am not sure is worth it for such a corner case, which already has two workarounds (<kbd>Ctrl</kbd> + <kbd>o</kbd> and <kbd>Ctrl</kbd> + <kbd>v</kbd>)

**Comment by andreyorst** [comment]
> because insert mode completion will retrigger as soon as a new character is inserted or the cursor moves.

Why even show popup on movement? This doesn't seem very useful if I've typed something, and moved backwards one letter, for example to correct misspelling, with arrow key the popup will be meaningless for me. But this involves recomputation of the list, which may be a significant task when using LSP with huge projects.

> For it work nicely it would need to have a concept of "completion session"

I don't think that such concept is really needed. Most editors will display popup on keypress only. If we want to trigger completion, we could raise popup directly with <c-x> or call a command in a way how it is done for `clang-complete`. 

I In case of Kakoune, I suppose it will be enough to display completion in these situations:
- User entered `insert` mode and cursor is positioned at whitespace, while previous cell contains a complete-able character, or
- User pressed a non-movement key.
- Otherwise do not display popup

I've mentioned a complete-able character, because it is meaningless to display completion popup after punctuations or operators.

More importantly, in current state, displaying completion popup while moving through the word is meaningless, because #2621 isn't a thing right now.
