### ISSUE TITLE
Copy text between buffers

### ISSUE THREAD

**Issue by ericricky** [mawww/kakoune#2786]
Is there a way to yank selections in one buffer and paste in another buffer without using the system clipboard?

**Comment by andreyorst** [comment]
you simply yank it with <kbd>y</kbd> and paste with <kbd>p</kbd>.

Are you sure you have different buffers and not different sessions?

**Comment by ericricky** [comment]
@andreyorst  Thanks, I figured it out. I was confused because I was trying to copy multiple selections from one buffer to another buffer with only one active selection. Is there a quick way to paste multiple selections without manually creating the same number of selections in the target buffer?

**Comment by andreyorst** [comment]
<kbd>Alt</kbd>+<kbd>p</kbd>

**Comment by ericricky** [comment]
@andreyorst Fantastic, thanks.

**Comment by andreyorst** [comment]
There's a "forum" at https://discuss.kakoune.com
You can find a lot of help here.

**Comment by ericricky** [comment]
@andreyorst Thanks, I'll check it out!
