### ISSUE TITLE
Add cursor_display_column state variable

### ISSUE THREAD

**Issue by FlyingWombat** [mawww/kakoune#2788]
I propose the addition of a `cursor_display_column` state variable, that would represent the visual column of the cursor on the display. This would have to take into account multi-width chars and tabstop value.

For example:  
Say the tabstop is 8.  
If my cursor is at col 10 on one line, and moves down to a tab indented line below.  
`cursor_display_column` would still be 10 after it has moved down, rather than 3 for `cursor_column` (bytes) and `cursor_char_column`.

This change would help a lot with [vertical cursor highlighters](https://github.com/insipx/kak-crosshairs/pull/11).

**Comment by mawww** [comment]
Currently `cursor_column` is defined as the byte offset of the cursor, it would not really make sense to respect tabstops without changing that into the display column of the cursor, which needs also to take into account the display width of the characters displayed before the cursor position. This would probably be exposed as a `cursor_display_column`, and it might make sense, for clarity sake, to get rid of `cursor_column`, renaming it to `cursor_byte_column`.

**Comment by FlyingWombat** [comment]
Ok, I wasn't sure what "byte" meant for `cursor_column`; I'm still a noob at this.  
Do you think `cursor_display_column` would be a worthy addition, or is there not really a use case for it other than what I've described here?

(Edited title for this)

**Comment by eraserhd** [comment]
@FlyingWombat `parinfer-rust`, which I maintain, would benefit.  It currently doesn't handle unicode well (I hit this today, in fact).

See #2724 .  (I haven't gotten to working on that yet.)
