### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Vm900** [mawww/kakoune#2795]
Hi,
I failed to install kak.
![kakerror](https://user-images.githubusercontent.com/9399631/54775951-f24a9680-4c06-11e9-988c-c89fad64582f.png)

However,i do have directory on my pc
![kakbase](https://user-images.githubusercontent.com/9399631/54776005-1d34ea80-4c07-11e9-8b4b-b95814942755.png)

Thanks

**Comment by laelath** [comment]
This is an issue with the new rc directory layout update. It looks like the makefile didn't get updated.

**Comment by Vm900** [comment]
Ok.Thanks
