### ISSUE TITLE
Add rustfmt to filetype

### ISSUE THREAD

**Issue by pickfire** [mawww/kakoune#2801]
### Steps 

Need to manually add to config from what is shown in wiki https://github.com/mawww/kakoune/wiki/Languages.
```
hook global WinSetOption filetype=rust %{
  set window formatcmd 'rustfmt'
}
```

### Outcome 

Nothing but need to manually add `formatcmd`

### Expected 

Rust filetype are expected to use `rustfmt` by default. Possible to add it to https://github.com/mawww/kakoune?

**Comment by Delapouite** [comment]
Same could be done for `gofmt` I think. These 2 tools are standards in their respective ecosystem.

**Comment by andreyorst** [comment]
I think that `c-family` can test if either `clang-format` or another supported formatter is installed and set `formatcmd` accordingly.

**Comment by maximbaz** [comment]
@Delapouite not sure about `gofmt` being standard, there's also `goimports` 😉

**Comment by mawww** [comment]
This is now fixed.

**Comment by pickfire** [comment]
@Delapouite @andreyorst I had already added for rust, feel free to add one for go and c. (I need to fix the wiki as well)
