### ISSUE TITLE
Repeat 'f' and 't' with… 'f' and 't'

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2824]
How about changing the behaviour of <kbd>f</kbd> and <kbd>t</kbd> to support repeating with themselves?

<kbd>f</kbd> searches a character and repeats with <kbd>f</kbd> and <kbd>t</kbd>.  When moving the cursor with another key, the repeatability ends.

I found this gem on [clever-f.vim].

Related issues:
- #1077
- #1637

[clever-f.vim]: https://rhysd.github.io/clever-f.vim/

**Comment by Delapouite** [comment]
Can this behavior be emulated by a kak script without involving changes in C++?

**Comment by alexherbo2** [comment]
Yep

**Comment by mawww** [comment]
I dont think this should be the default behaviour, it would make total sense to want to go to "the next { after the next (" which would be `f(f{` with the current behaviour and would need some added `hl` convulution with the proposed change.

**Comment by andreyorst** [comment]
Also repeating `t` with <kbd>t</kbd> makes little sense, since it will stuck before the first match anyway. Unless second press works like `move forward 1 char, repeat t`
