### ISSUE TITLE
Auto-correct selections passed to :select

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2827]
Auto-correct selection direction by honoring the main selection direction.

**Prototype**

```
select [<anchor-line>.<anchor-column>,<cursor-line>.<cursor-column>]…
```

**Example** – With selection direction messed:

``` kak
select 1.10,1.20 2.20,2.10 3.20,3.10
```

The main selection is in forward direction (cursor after anchor) while the secondary selections are in backward direction (cursor before anchor).

**Example** – Merging two option values:

https://github.com/alexherbo2/phantom.kak/blob/e438f67828e1de177c58c72ee1a2561a29a2fa32/rc/phantom.kak#L30

**Comment by occivink** [comment]
I don't agree with this, the current behavior is more flexible in that you have full control over the direction over the selections. 
It might not make too much sense to have mixed forwards and backwards selection at the same time, but it's also easy to re-orient them however you like before you call `select`, or to simply do `exec <a-:>` afterwards. Besides, `select` is a low-level command that you wouldn't call interactively, so I think it's better that it stays dumb, but flexible.

**Comment by mawww** [comment]
Yeah, I dont think the select command is the correct place to try to fix that. Either pre-process the list, or maybe we should make it a stronger invariant of Kakoune that selections should always have the same direction in a list (having different directions is usually quite confusing, and cannot come up with good examples where having separate directions makes sense). In any case I dont think changing select would be a good move.
