### ISSUE TITLE
can't map '-'

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2838]
when trying to map <kbd>-</kbd> like this:
```kak
map global user '-' ': command<ret>'
```
I get such error message:
```
Error: 1:1: 'map' unknown option '-'
```
I don't think that options can go in strings, that makes little sense.

And if I try to escape it with backslash like so:
```kak
map global user \- ': command<ret>'
```
the error is:
```
Error: 1:1: 'map' only a single key can be mapped
```

**Comment by alexherbo2** [comment]
``` kak
map global user -- - ': command<ret>'
```

**Comment by andreyorst** [comment]
Can you explain why this works? From my POV there are too many arguments for map command, which accepts these arguments:
```
map [<switches>] <scope> <mode> <key> <keys>
```

So executing this should fail:
```sh
  map   -docstring '-'   global  user  --   -  ': command<ret>'
#  |         |      |      |      |    |    |         |
# map      [<swithces>]  scope  mode  key  keys      ???
```

But it works

**Comment by occivink** [comment]
That's because `--` is interpreted as a switch (or rather, as a special switch that indicates there are no more switches afterwards) and switches can be put in any position, not just right after `map`. For example, this works `map global user b -docstring "some doc" ': command<ret>`

**Comment by andreyorst** [comment]
Ah, I know that position doesn't matter, but I thought that `map` command will understand only single type of switch, which is `-docstring` and `--` will not be accepted. Good to know that Kakoune commands accept `--` as "no more switches". Thanks

**Comment by alexherbo2** [comment]
Sometimes switches matter e.g. `-add` is only recognized right after `set`.
