### ISSUE TITLE
Mark system similar to vim

### ISSUE THREAD

**Issue by jkonecny12** [mawww/kakoune#284]
Hi all,

In Vim users can by pressing ``m + <lowercase letter>`` save mark for actual position in the code and then by pressing ``' + <the letter>`` jump to line or by pressing `` ` + <the letter>`` to jump to line and column where the mark was saved. More in [vim wiki](http://vim.wikia.com/wiki/Using_marks).

I think this feature is missing in kakoune. There are jumps but it's not the same. When I talked to @mawww we agreed to combine this approaches.

I'm also thinking that it would be nice to have contextual help for this (like in 'g' GoTo commands) and the best would be if this help shows your already saved marks. Hard to say if this is reasonable for implementation. What do you think @mawww ?

**Comment by mawww** [comment]
Hello, I pushed an initial version, bound to ^ for save selections to register, and alt-^ for restoring. I am not very happy with these bindings, so suggestions are welcome.

**Comment by jkonecny12** [comment]
Yeah it's little complicated shortcut but I thing I get used to it. I'll try to find better bindings. To that time I think it's working like a charm now. 
Thank you @mawww good work.
Btw sorry it took so long to me to look on this.

**Comment by alexherbo2** [comment]
How about `z` to load and `Z` to create marks?

It’s easier to type.  Plus `z` makes a good mnemonic, since it’s more like pages of a book.

As a side note, `z` and `Z` suit well with `q` and `Q` used for macros.

**Comment by mawww** [comment]
Hum, yeah, why not, I was saving z for something undetermined, but I guess marks are as good as any.

**Comment by jkonecny12** [comment]
Nice idea @alexherbo2
