### ISSUE TITLE
Use 'info' for ':echo'

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2840]
Sometimes lengthy multi-line options need to be viewed when writing kaksctipt.
`:echo %opt{long_option}` isn't much useful, because contents are displayed within the modeline. `:echo -debug %opt{long_option}` is little more useful, but newline characters are not parsed in debug, yet at least we are able to see whole option.

Maybe make it available to use info box to display echo? If option content length exceeds modeline length, or option contains newlines, info box could be used.

**Comment by Screwtapello** [comment]
Wouldn't that just be `:info %opt{long_option}` ?

**Comment by andreyorst** [comment]
I understand that this is possible (yet you need to quote option), but my main point is that echoing long options to the modeline isn't useful at all, and if I want to check some option I often don't know it's content so falling back to info would be nice

**Comment by mawww** [comment]
I dont quite get the need for echo to make that decision, `info` will do the job just fine for long and short options, so why not just use it ?

**Comment by andreyorst** [comment]
in Vim and emacs echo area is expanded and support scrolling in case echo information is too big for single line mode.

**Comment by mawww** [comment]
Vim and emacs dont really have an `info` equivalent though, so they need echo to support multiline strings, but in Kakoune case I dont see a lot of interest in doing that. I still dont quite understand the problem with just using `info` directly in your use case.
