### ISSUE TITLE
View mode movement restricted by cursor placement

### ISSUE THREAD

**Issue by losnappas** [mawww/kakoune#2844]
How do I make view mode "unlock" the cursor? If I open a file so my cursor is on line 1, then go into view lock mode with `V` and try scrolling down with `j`, it doesn't move since the cursor is at the top.

Same thing happens somewhat inconsistently with mouse scrollwheel, too. I scroll upwards/downwards, and at some seemingly random point it just locks until I place the cursor somewhere else.

I'm not sure if this is a tmux or kakoune problem.

**Comment by andreyorst** [comment]
I'm using tmux, and I confirm that scrolling upwards is blocked if the cursor is positioned at the bottom line of the screen. Scrolling down works fine.

**Comment by andreyorst** [comment]
Myunderstanding of scroll mode is that it should allow main cursor go off screen, so it doesn't moved when scrolling, like in GUI editors. This way this mode would me really useful.

**Comment by blobject** [comment]
Just started using kakoune and I'm also noticing the scroll restriction (version 2020.09.01, with alacritty, no tmux). Scolling down with "vj" always works but scrolling up with "vk" blocks sometimes if the cursor is at the bottom of the view.

Don't know anything about the internals but the blocking seems to happen when the "current viewport" contains wrapped lines. If the current viewport has no wrapped lines but if the line immediately above the viewport is wrapped, then scroll-up is blocked. Disabling wrapping altogether allows scroll-up (and -down) to work (well, work like vim or emacs, where the cursor gets shifted).

In any case, looking forward to the reworking of the selection-visibility and accompanying logic.

**Comment by lenormf** [comment]
@blobject you're right there are issues with wrapped lines, c.f. #1517

**Comment by ManDay** [comment]
See also https://github.com/mawww/kakoune/issues/4124 and https://github.com/mawww/kakoune/issues/3951
