### ISSUE TITLE
Provide colors to create faces based on current color scheme

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2862]
This issue is about different way of looking on themes in Kakoune.

The problem is, that defining faces isn't versatile enough. Different scripts need different faces, and adding all these faces to all themes isn't good solution, but there's no way to script to get currently used colors, so script could define it's own meaningful set of faces.

The problem occurs currently in such scripts like [grep.kak](https://github.com/mawww/kakoune/blob/06d4ee578e5955d3d444bbe9dd03285df958cdd1/rc/tools/grep.kak#L29) which uses term colors, to color different groups in `regex` highlighter. My theme for kakoune uses a bit different colors, from what I'm using in the terminal, and this results in inconsistent colors in `*grep*` buffer. Basically every user plugin that wants to match a particular theme needs to [create duplicated themes](https://github.com/andreyorst/powerline.kak/tree/master/rc/themes).

This issue can be solved if themes will declare colors, not faces. Kakoune could provide 16 different clolors, accordingly to default sixteen colors in the terminal: `black`, `red`, `green`, `yellow`, `blue`, `magenta`, `cyan`, `white bright-black`, `bright-red`, `bright-green`, `bright-yellow bright-blue`, `bright-magenta`, `bright-cyan`, `bright-white`. So for example default theme will look like this:
```kak
set-option kak_color_black          "black"
set-option kak_color_red            "red"
set-option kak_color_green          "green"
set-option kak_color_yellow         "yellow"
set-option kak_color_blue           "blue"
set-option kak_color_magenta        "magenta"
set-option kak_color_cyan           "cyan"
set-option kak_color_white          "white"
set-option kak_color_bright_black   "bright-black"
set-option kak_color_bright_red     "bright-red"
set-option kak_color_bright_green   "bright-green"
set-option kak_color_bright_yellow  "bright-yellow"
set-option kak_color_bright_blue    "bright-blue"
set-option kak_color_bright_magenta "bright-magenta"
set-option kak_color_bright_cyan    "bright-cyan"
set-option kak_color_bright_white   "bright-white"
```
This color set could be extended with some named colors, like `background` and `foreground`, in the same way how most terminals are configured. And another theme will set all these colors to another values, like `rgb:AABBCC`. 

Doing it this way will allow each script to define it's own set of faces using these colors. This will make it easy to write support scripts, because you'll not be limited to existing faces, you'll be able to use any attributes with those colors, and your scripts will never get out of sync with Kakoune look.

## Pros:
1. All scripts will use same set of colors, and will never look out of sync with any colorscheme.
2. Making `colorschemes` will be more like making color schemes, and not themes, because we just define color scheme.
3. Scripts will declare semantically correct faces themselves. `c-family.kak` can declare, `function` and `type`, but it doesn't need `variable`. `sh.kak` doesn't need `type`, but needs `function` and `variable`. `markdown.kak` doesn't need programming stuff at all, so it could declare various headings, lists and other Markdown related stuff.

## Cons:
1. Scripts would need to declare very similar set of faces within each one, prefixing those like variables, like `set-face markdown_title` and `troff_title`
1. Scripts will be restricted to fewer colors, compared to current way of making colorschemes, where more then 16 colors are available

**Comment by TeddyDD** [comment]
This won't work. Base16 uses similar method. Take a look at https://github.com/leira/base16-kakoune/

Most of the themes created with this method looks mediocre. Few is unreadable, very few look good. Base16 works for Vim but vim does not need 4 distinct colors for selection alone to be usable.

On the other side I think It would be good idea for themes to provide selection of colors as Kakoune options. Those colors would have specified and documented meaning (for example: 'bg, bg_highlight, high_contrast_fg1..3, low_contrast_fg_1..3' - something like [this](https://github.com/hundredrabbits/themes)). This way scripts could create custom faces consistent with given theme without designing themes around limited set of colors.

There is one issue with my idea — we wound need theme change hook to recreate faces outside the theme.

**Comment by Screwtapello** [comment]
As an example of prior art, it's worth looking at Vim. In addition to setting (the Vim equivalent of) a Face to a foreground and background colour, it can also link one Face to another Face, possibly overriding the foreground/background/etc.

Vim ships with a bunch of very high-level generic faces like "Heading" and "Comment" and "Literal", and filetype plugins will make their own faces based off the most appropriate generic face (perhaps `pyComment` is based on `Comment`, for example). That way, a color-scheme author *can* set custom colors for every face of every filetype if they really want everything to be perfect, or they can just set custom colours for the high-level generic faces and get something that's "good enough".

To follow that path, Kakoune would need the ability to make one face build off another, and it would probably need a richer set of default faces, even if most of them were linked to other default faces by default. For comparison, Vim seems to have about 100 default faces, although `String`, `Character`, `Number` and `Boolean` (for example) are all linked to `Constant` by default.

**Comment by andreyorst** [comment]
@TeddyDD I disagree, Nothing will change actually, because currently available colorschemes have roughly 16-18 colors in general, with some exceptions (zen).  Scripts will have the same set of colors in the end: 18 colors - 8 normal, 8 bright, 1 bg, 1 fg.

I've realized that several colors should be defined for Kakoune internals like line numbers, selections, cursors colors, because scripts do not define those, and it should be a part of colorscheme, and perhaps don't visible to the scripts, as they don't really need those.

@Screwtapello Vim's way to define colors and faces is a real pain when creating or modifying an existing theme. I think if Kakoune wants to be minimal in some aspects, the palette of colors can be provided for scripts, and scripts will decide how to use it. Creating another hundred of faces in themes is a bad decision in my opinion.

But I agree on one point: faces should be able to use other faces as a base face and alter their colors. This also will mean that if I want to define a face that shares the same set of colors, but I want it to be bold, I just could use a face and apply `+b` to it, which isn't possible currently.

**Comment by andreyorst** [comment]
Since the 4e24ba86cc95c51f78ebe9e77f1848b6760dbeb5 is a thing now, and we are able to create new faces based on other faces, I still think that lack of colors will be a problem.

Currently there's no way to create new face with two colors if both of those colors are not used in base face. For example:

    set-face global face1 rgb:cc6666,rgb:223322
    set-face global face2 rgb:aa33ee,rgb:0d542f

For example I really want to create an `OK` face that uses `rgb:0d542f` as a foreground and `rgb:223322` as a background, and `Error` face, that is red on magenta. Current syntax doesn't allow it, it only allows mutation, so only left solution is to use colors provided by terminal:

    set-face global Ok brigt-green,green
    set-face global Error bright-red,red

Which can lead to this:

![image](https://user-images.githubusercontent.com/19470159/56893644-0d24ec00-6a8c-11e9-8990-b6c2869eadc5.png)

Black text is actually has face that uses `green` color from terminal, but terminal is set up to use only black and white, while the Kakoune colorscheme defines `rgb:XXXXXX` colors for everything.

If colors were available to us as (for example) options, we could just define those in color scheme:

    declare-option str green rgb:0d542f
    declare-option str dark-green rgb:223322
    declare-option str red rgb:cc6666
    declare-option str magenta rgb:aa33ee

And declare our faces like this:

    set-face global face1 red,dark-green
    set-face global face2 magenta,green

---

The way I see it is that mutation of faces is needed but only when you want to declare a face that is similar to existing one, e.g. `comment` and `docstring-comment`, and colors are needed to create new faces while still staying consistent with current color scheme.

**Comment by basbebe** [comment]
I also would like the ability to reference colors and have more faces by default a lot
