### ISSUE TITLE
need to create empty directories through git init 'unknown command'

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#2865]
Based on https://github.com/mawww/kakoune/blob/master/rc/tools/git.kak I don' t see any `init` option to create empty directories 

I'm assuming that https://github.com/mawww/kakoune/issues/128 in which git-tools.kak is brought up is indeed referring to git.kak

**Comment by lenormf** [comment]
The point of this file is to interact with Git commands that return data that is meaningful to the editor.

It's not a 1:1 wrapper that allows using the editor as a shell, but if you want then I think you could define a command into your user directory:

```
define-command -params .. -shell-completion -docstring %{
Forward all arguments to a shell for evaluation
} shell %{
    nop %sh{ eval "$@" }
}
alias global ! shell
```

Usage: `:! git init /tmp/test`

**Comment by nonumeros** [comment]
@lenormf  thanks for letting me know. 

So the whole purpose of having it is to interact with meaningful content to the editor

But why it wouldn'  be meaningful since I'm using the editor?  So something like https://github.com/mawww/kakoune/pull/2867 would ' be feasible? 

I think I follow you in your statement, but in all honesty I don'.

**Comment by nonumeros** [comment]
What I'm trying to say, and I can't disagree with you there, is that other git commands are not really meaningful to whatever content is there, but I sometimes have cgit running and I like to create these empty directories . This is not about github or gitlab or any other hosting service. But for my personal use.
