### ISSUE TITLE
Named parameters?

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2885]
currently commands provide `-params` switch, that can specify amount of parameters supported by command, and later those parameters can be accessed via `%arg{N}` syntax and `$N` if we're using `%sh{}` expansions.

When writing scripts, I often create commands that accept parameters in certain order, which almost always is shown in function docstring, for example:

    define-command some-command -params 2 -docstring "some-command <param1> <param2>"

But when I write the body of this command, if the command is complex, I don't like to refer to those parameters via `$N` or `%arg{N}` syntax, because it is hard to observe and to remember every time which parameter is I'm currently dealing with.

What about `%arg{NAME}` syntax? It will allow to use parameters with names directly in the body, and in case of shell expansions it could be `$kak_arg_NAME`, so there will be no need to do:

```bash
important_param=$1
less_important_but_still=$2
meaningful_argument=$3
# ...
```

At the beginning of each command body.

**Comment by Delapouite** [comment]
Let's try to flesh out a prototype with an example.

The native `:info` command has 3 optional switches: `anchor`, `style` and `title`.
If we were to redefine it in a kak-script, what about using a new `define-command` switch called `switches`? :

`define-command info -switches 'anchor style title' -params 1 -docstring 'info…' %{ … }`

**Comment by andreyorst** [comment]
`swithces` is a confusing name. Switch usually starts with `-` followed by a name. These are parameters, so I think that the `params` switch should accept number of parameters, or `str-list` of parameter names like so:

    define-command info  -params %{'anchor' 'style' 'title'} -docstring 'info...' %{ ... }

**Comment by Delapouite** [comment]
Ah ok. Sorry, I misunderstood your initial request. It is about having named parameters given in a specific order and non-optional.
So yes, you're right in this case, the `-switches` I proposed has nothing to do with this feature.
