### ISSUE TITLE
Crash when trying to open a specific file using :e

### ISSUE THREAD

**Issue by ssbl** [mawww/kakoune#2900]
### Steps 

1. `./kak`
2. `:e ~/src/uemacs/eval.c`

### Outcome 

Kakoune crashes due to a segmentation fault. This is on Ubuntu 18.04 LTS with the development version (commit `92972be`) compiled using g++ 7.4.0.

---

So this is kind of weird, but this consistently happens when I try to open this specific file. I also get the same behavior using the eval.c file in the emacs source code. I got the uemacs source [here](https://github.com/torvalds/uemacs) and emacs [here](https://github.com/emacs-mirror/emacs). Running this with valgrind produces [this output](https://github.com/mawww/kakoune/files/3159083/log.txt).

I looked into it a bit and it seems the crash happens because of an invalid iterator in the `execute_single_command` function in command_manager.cc, maybe because the hashmap is resized sometime before the iterator is used.

I haven't had this problem after applying this [patch](https://github.com/mawww/kakoune/files/3159088/patch.txt), but I don't know if the problem is actually fixed.

**Comment by mawww** [comment]
Thanks for the thourough bug report,

It seems this bug has been lurking around for a long time, what happens is that the `ParameterParser` object we pass to commands keeps a reference to the `ParameterDesc` object describing the command switches. This `ParameterDesc` object is owned the `CommandManager::m_commands` hash map, which can get mutated if we add new commands.

Up to now, its been pretty rare that running some command would trigger the mutation of that hash map besides at startup, but with the apparition of the module system, it became much more common as running a common might trigger a module load, which would define a set of new commands that would be inserted in that hash map, potentially moving `ParameterDesc` objects in memory.

An easy fix would be to just copy the ParameterDesc, but I'd be happier if we could void this overhead, I'll take a look at the possible alternatives.

**Comment by ssbl** [comment]
Looks like it's fixed now. Thanks @mawww !
