### ISSUE TITLE
c-family multiline macros syntax highlighting

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2903]
Emacs:
![image](https://user-images.githubusercontent.com/19470159/57615462-6ad53000-7584-11e9-9ed8-8ac4129cce76.png)

Kakoune:
![image](https://user-images.githubusercontent.com/19470159/57618014-f356cf00-758a-11e9-83a4-7528611a9f28.png)

I'd like to have syntax highlighting in complex macros, since it makes them easier to read. I think it can be done with region highlightier in the same way how it is done in markdown, but I don't know if it could be done with this kind of syntax:

```c
#define something \
                  \
macro body        \
                  \ /* highlighting as C till empty line */

/* ordinary code highlighting */
```

Maybe just ignore highlighing of multiline macros?

**Comment by Jackojc** [comment]
Would also like this see this.
