### ISSUE TITLE
Bash {1...10} for loop notation doesn't work?

### ISSUE THREAD

**Issue by josephrocca** [mawww/kakoune#2921]
I press `Shift+1` (i.e. `!`) to output the result of a bash command, and it brings up a prompt: `insert-output:`. So I type in this bash command to output a list of 4 numbers:

```
for i in 1 2 3 4; do echo $i; done
```
And it works perfectly:
```
1
2
3
4
```
But now I try to make it a bit shorter using `{1..4}` notation:
```
for i in {1..4}; do echo $i; done
```
and it simply outputs:
```
{1..4}
```

I thought maybe it wasn't using `bash`, but it outputs this when I type `!$SHELL --version`:

```
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
...
```

**Comment by Screwtapello** [comment]
A user might have any shell configured (using a tool like `chsh`), there's no guarantee that whatever's in `$SHELL` behaves the way Kakoune and its plugins expect. Therefore, wherever Kakoune mentions a shell (like the "insert-output" command, or `%sh{}` expansion, etc.) it's always talking about POSIX shell, `/bin/sh`.

`bash` is backwards-compatible with `/bin/sh`, so a lot of things are the same, but `bash` adds a lot of extra features, including `{1..4}` range expansion. For more information on POSIX shell, see [the official specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html), Ubuntu's [list of bashisms](https://wiki.ubuntu.com/DashAsBinSh#I_am_a_developer._How_can_I_avoid_this_problem_in_future.3F), [shellcheck's portability warnings](https://github.com/koalaman/shellcheck#portability), documentation for a minimalist POSIX shell like [dash](https://linux.die.net/man/1/dash), etc.

**Comment by josephrocca** [comment]
Ah, okay, I figured that might be the case. And I'll assume by your comment that there's no way to switch it to use `bash` (would be handy for me if this were possible). If that assumption is correct then this issue can be closed. Thanks for the response!

**Comment by nonumeros** [comment]
When braces are used, the matching ending brace is the first ‘}’ not escaped by a backslash or within a quoted string, and not within an embedded arithmetic expansion, command substitution, or parameter expansion. See https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html#Shell-Parameter-Expansion

so your issue can be reproduced by

     $ kak -n
     $ echo \{1..4}

which returns

      {1..4}

**Comment by nonumeros** [comment]
@josephrocca i don't know if you tried again to run `echo {1..4} ` 

Was it there as before?

**Comment by nonumeros** [comment]
@mawww  in my case after running `echo \{1..4} ` the issue never came back

so `echo {1..4}` matches the terminal

**Comment by nonumeros** [comment]
**dash**

The $ character is used to introduce parameter expansion, command substitution, or arithmetic expansion.

where expression consists of all characters until the matching ''}''. Any ''}'' escaped by a backslash or within a quoted string, and characters in embedded arithmetic expansions, command substitutions, and variable expansions, are not examined in determining the matching ''}''.

Source https://linux.die.net/man/1/dash

**bash**

The ‘$’ character introduces parameter expansion, command substitution, or arithmetic evaluation. The parameter name or symbol to be expanded may be enclosed in braces, which are optional but serve to protect the variable to be expanded from characters immediately following it which could be interpreted as part of the name.

When braces are used, the matching ending brace is the first ‘}’ not escaped by a backslash or within a quoted string, and not within an embedded arithmetic expansion, command substitution, or parameter expansion.

Source: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html#Shell-Parameter-Expansion

**Regardless if you escape the matching closing brace, anything after will be interpreted.**

source: me, unverified of course!
