### ISSUE TITLE
Provide some way to expand selection?

### ISSUE THREAD

**Issue by bollu** [mawww/kakoune#2926]
Something like [`vim-expand-region`](https://github.com/terryma/vim-expand-region) would be great to have inbuilt into kakoune, due to its heavy focus on these selection combinators. 

Also, I don't understand how to replicate something like `ciw` or `ci{` in kakoune. What am I missing?

**Comment by Screwtapello** [comment]
You may be interested in https://github.com/Delapouite/kakoune-expand-region or https://github.com/occivink/kakoune-expand

Vim's `ci{` would be `<a-i>{c` in Kakoune.

**Comment by bollu** [comment]
Thank you!

Is it just me, or does `ci{` feel much "lighter" than `<a-i>{c` ? I find the latter much harder to type.

**Comment by alexherbo2** [comment]
You have `<a-i>B` too.

**Comment by lenormf** [comment]
Could we close this?
