### ISSUE TITLE
Counter-intuitive paste behavior

### ISSUE THREAD

**Issue by josephrocca** [mawww/kakoune#2931]
In the following video I delete and yank the lower line and try to `p`aste it above the upper line:

https://i.imgur.com/GhActMh.mp4

But something strange happens and the pasted line appears before the line below. Is this expected behavior? Hard to imagine that I've discovered a bug here given that this is a common operation, so I'm guessing that I just misunderstand how the pasting operation works.

**Comment by occivink** [comment]
What happens is that `p` pastes after the current selection. Since the selection at this point is just the newline character, the text you yanked appears after that character, i.e. on a new line. 
If you use `P`, it pastes before the current selection, which in this case will be where you want it.

**Comment by josephrocca** [comment]
Ah, thanks for that!
