### ISSUE TITLE
When disk is full, Kakoune crashes and truncates file, potentially losing data

### ISSUE THREAD

**Issue by curtmack** [mawww/kakoune#2932]
### Steps 

1. Create a nearly full filesystem: `mkdir ramdisk && sudo mount -t tmpfs -o size=4k tmpfs ramdisk`
2. Open Kakoune on a file in your nearly full filesystem and type enough text that the file will not fit. (The raw contents of README.asciidoc suffice.)
3. Save the file.

### Outcome 

```
terminate called after throwing an instance of 'Kakoune::file_access_error'
[1]    509 abort (core dumped)  kak ramdisk/a
```

The contents of the buffer are truncated to wherever the last successful write ended; anything that was in the buffer after that point is lost. The terminal is also left in raw mode.

### Expected 

Vim fails safely in this case; the editor remains open, no data is lost, and the error message makes it clear to the user what happened:

```
"ramdisk/a" E514: write error (file system full?)
WARNING: Original file may be lost or damaged
don't quit the editor until the file is successfully written!
```

**Comment by mawww** [comment]
Thanks a lot for reporting this.
