### ISSUE TITLE
Improper buffer redraw on word search

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#294]
Hi,

Kak will not properly the content of a file when searching for a word in a buffer, and then scrolling with the down arrow key.

How to reproduce the bug:
- Open kakoune/src/main.cc in a new client (:new command)
- search for "main" (with the '/' key)
- after you've hit the return key, hit the down arrow key several times
You should see a bunch of empty lines being randomly displayed. This problem also occurs when you repeat the search with an empty pattern.

Related issue:
Assuming ctrl-l is for redrawing the buffer entirely, it will sometimes fill the terminal with empty lines after completing the above steps.

EDIT: it looks like this issue only impacts windows created with the ```:new``` command

**Comment by mawww** [comment]
Hello,

I could not reproduce this bug here, is it under tmux or a X11 window manager ?

I'll try under X11 once I get home.

**Comment by lenormf** [comment]
I couldn't reproduce it in tmux either.

I'm using i3 in X11, that's where the bug occurs.

**Comment by mawww** [comment]
What terminal emulator do you use ? did not manage to reproduce with rxvt-unicode.

**Comment by lenormf** [comment]
I use termite, and I could reproduce the bug with xterm as well. Tested against the current HEAD.

**Comment by mawww** [comment]
So, I tried with xterm, did

`kak main.cc` then `/main<ret>jjjj` and I did not see any black lines.

control-l however is broken, pull request #300 contains a fix.

Did I miss something to get that bug to reproduce ?

**Comment by mawww** [comment]
(did try with a xterm client created using `:new` as well)

**Comment by lenormf** [comment]
Maybe I should have precised that the empty lines appear when hitting the down arrow key makes the buffer scroll down :/

i3: 4.10.2
termite: v10
Xorg: 1.17.2

I made a capture that shows exactly what happens: https://u.teknik.io/G4NFig.mkv

Note that as soon as the bug has been "triggered", the rendering is broken beyond repair: scrolling upward/downward creates even more artifacts, and hitting ^L will redraw correctly the buffer a couple times, after that the entire window turns black.

**Comment by lenormf** [comment]
Fixed by eb4ac85fb195b119ff86cf5c2b9741bb7fdd2d37.
