### ISSUE TITLE
BufReadFifo hook parameter is incorrect on first read

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#2946]
##### `foo.kak`
```kak
hook global BufCreate '\*stdin\*' %{
    hook buffer BufReadFifo .* %{echo -debug BufReadFifo: %val{hook_param}}
    evaluate-commands -draft %{
        execute-keys '%'
        echo -debug BufCreate: %val{selection_desc}
    }
}
```

```sh
$ ( echo hello; sleep 10; echo goodbye ) | kak -n -E foo.kak -debug hooks
```

### Outcome

`*debug*`:
```
*** This is the debug buffer, where debug info will be written ***
hook BufCreate(*stdin*)/
BufCreate: 1.1,1.1
hook BufReadFifo(2.1,2.1)/
BufReadFifo: 2.1,2.1
hook BufReadFifo(2.1,3.1)/
BufReadFifo: 2.1,3.1
```

### Expected

The first `BufReadFifo` should start at 1.1.

**Comment by eraserhd** [comment]
It also seems to be the case that an extremely short piece of text will not trigger `BufReadFifo` at all.

Work arounds for both these are present in https://github.com/eraserhd/kak-ansi now.

**Comment by eraserhd** [comment]
*And also*, piping a very long output (say `git log` on NixOS/nixpkgs, which is 1,445,439 lines), caused the first `BufReadFifo` to be `2.1,1046.8` and the last `BufReadFifo` to be `1444132.43,1445134.51`, meaning the first line and the 305 lines were missed.

(It was also unresponsive and using 100% of a CPU during this time.)

**Comment by mawww** [comment]
Thanks for debugging that and providing a fix, much appreciated.
