### ISSUE TITLE
help won't find pages

### ISSUE THREAD

**Issue by agarrubio** [mawww/kakoune#2949]
Installed in Linux Mint 19.1 Tessa using apt-get:
%> sudo apt-get install kakoune

### Steps 
:doc keys
### Outcome 
No such doc file: /usr/share/kak/../doc/kak/manpages/keys.gz

### Expected 
Help on keys

**Comment by Screwtapello** [comment]
I know Linux Mint has some complex genealogy back to Debian, but I don't know which Mint releases correspond to which Debian releases.

Debian Stable currently has a very, very old version of Kakoune (from 2016!). Debian Testing, which will become Stable later this year, has a more up-to-date version (January 2019), but there's likely to be at least one new Kakoune version released before then, so it'll still be out of date.

**Comment by agarrubio** [comment]
Thanks! How can I tell which version of kak I'm using?

**Comment by Screwtapello** [comment]
Try:

    apt-cache policy kakoune | grep "Installed"

**Comment by mawww** [comment]
`kak -version` should also output some version information, provided the binary is recent enough. The path you have displayed suggests the kakoune binary is in /usr/share/kak/ which is a bit strange.

**Comment by lenormf** [comment]
Is this still a problem? Should the issue be closed?

**Comment by mawww** [comment]
Closing for now.
