### ISSUE TITLE
grep.kak doesn't provide output with rg --glob feature

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2959]
my `grepcmd` is set to:

    rg -L --hidden --with-filename --column

And calling `:grep something` works. But I want to exclude `git` and `svn` from search with `--glob` parameter:

    rg -L --hidden --with-filename --column --glob '!.git/*' --glob '!.svn/*'

With current value of `grepcmd` nothing is shown in `*grep*` buffer. However this command works fine in `dash`.

**Comment by mawww** [comment]
Hello,

I suspect this is an escaping issue, can you try the following:

Change `grep.kak` to make `grepcmd` a str-list, and change your kakrc to set each argument as an element in the list (it should be necessary to manually quote the glob patterns).

I have been tempted to change those commands (grepcmd, makecmd, ...) to str-lists as I believe it should solve escaping issues as those are used inside "eval" calls.

Please report if that fixes it.

**Comment by lenormf** [comment]
Having globbing characters in `grepcmd` works as expected here:

```
$ env KAKOUNE_POSIX_SHELL=/usr/bin/dash ./kak -e "set global grepcmd %{ag --column --ignore '\\.git/.*'}"
#  `ag --column --ignore '\.git/.*' …` is executed
```

I used the following patch to verify that:

```diff
diff --git a/rc/tools/grep.kak b/rc/tools/grep.kak
index 9e6ed5ab..6dba0a12 100644
--- a/rc/tools/grep.kak
+++ b/rc/tools/grep.kak
@@ -11,7 +11,7 @@ All the optional arguments are forwarded to the grep utility} \
      output=$(mktemp -d "${TMPDIR:-/tmp}"/kak-grep.XXXXXXXX)/fifo
      mkfifo ${output}
      if [ $# -gt 0 ]; then
-         ( ${kak_opt_grepcmd} "$@" | tr -d '\r' > ${output} 2>&1 ) > /dev/null 2>&1 < /dev/null &
+         { set -x; { ${kak_opt_grepcmd} "$@" | tr -d '\r' > ${output}; } 2>/tmp/test; } > /dev/null 2>&1 < /dev/null &
      else
          ( ${kak_opt_grepcmd} "${kak_selection}" | tr -d '\r' > ${output} 2>&1 ) > /dev/null 2>&1 < /dev/null &
      fi
```

**Comment by supermarin** [comment]
RG supports (not sure as of how recently) a [config file](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file) that accepts syntax like `--glob=!git/*` and works OK with Kakoune
