### ISSUE TITLE
$kak_buffile fails to return no selections remaining while executing external command

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#2961]
### Steps 

```
./kak -n
:edit some/path/somewhere/file.tex
:keep pipe tex $kak_buffile
```

### Outcome 

Output is written on tip of pwd

### Expected 

`no selections remaining`

both `$kak_bufname` and `$kak_buffile` should return the same `no selections remaining` values.

**Comment by Screwtapello** [comment]
What is `:keep`?

**Comment by nonumeros** [comment]
>What is :keep?

Hello @Screwtapello  

I meant `:keep pipe` as in the key `$` so the external program is called out.

But I'm closing this issue too. No need to report anything. Everything is working fine.

**Comment by nonumeros** [comment]
@Screwtapello  I may have been wrong with this issue.. 

And let's forget about that `$kak_buffile` and `$kak_bufname` 

But under the same directory I have 
```
-rw-r--r-- 10test.tex
-rw-r--r-- 11test.tex
-rw-r--r-- 12test.tex
```
so it tells me the list of files can be `read`

but if I were to invoke kak from the home directory, it doesn't autocomplete the filename for those specific files. the dir has an  `r-x` permission

I understand the files can't be written, but why not opening the file at the very least... I just don't get it.

**Comment by nonumeros** [comment]
Got that last behaviour - or so I think

```
mkdir -p testdir2
./kak -n 
:edit pathto/testdir2/1test.tex
:wq
```

then

```
kak -n
:edit pathto/testdir2/      <--- it wouldn't autocomplete the filename even though has r--r-- permissions
:quit
```

If on the other hand I would just `cd` to the pwd where the filename resides, then it would open the file with just an `edit` operation...Else it won't.

**Comment by nonumeros** [comment]
@lenormf please,  if you can verify the last comment. 

```
edit pathsomewhere/newfile.tex                 <--file created from the home directory
saved file
```

```
edit pathsomewhere/    <--filename can't be autocompleted unless `cd` ing to pwd first 
```

Is that the expected normal behavior?

**Comment by lenormf** [comment]
It's not the expected behaviour, but directories need `r-x` permissions to be list-able.
