### ISSUE TITLE
kak should honor ENV variables.

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#2962]
### Steps 

```
./kak -n $ENVIRONMENT_VARIABLES
```

### Outcome 

```
error while opening file $ENVIRONMENT_VARIABLE
: is a directory
```

### Expected 

Recognize the $ENVIRONMENT_VARIABLES

e.g. with current outcome

```
./kak -n $CATANDMOUSE
**debug**
error while opening file: /home/c/catandmouse/
:is a directory
```

**Comment by lenormf** [comment]
What is `$ENVIRONMENT_VARIABLES` expanding to? Is your shell not expanding it because it's not defined? Trying to understand how that's an editor-related issue.

**Comment by nonumeros** [comment]
> Trying to understand how that's an editor-related issue.

let's forger about the shell, that's a different aminal with expansion

Would it be fair to compare this behaviour with other editors? vim and its variants, and emacs recognize them. Even micro, another editor, does. Why would  be any different with kakoune?

**Comment by TeddyDD** [comment]
It works in Kakoune as well - unless $ENVIRONMENT_VARIABLES is path to directory. Kakoune does not open directories.
```
kak $GOPATH/src/github.com/TeddyDD/bPix/main.go # works
kak -n $GOPATH/src/github.com/TeddyDD/bPix/main.go # works
kak $GOPATH/src/github.com/TeddyDD/bPix # error
```

**Comment by nonumeros** [comment]
forget about the opening a directory part. And forget about MAX_PATH too, and forget about whatever was taught in school.  I'm talking about  honoring, recognizing the ENV Variables, as other editors do.

**Comment by lenormf** [comment]
Environment variables are handled by your shell, which Kakoune is not. It's still unclear what your problem actually is, do you expect the prompt to expand environment variables?

**Comment by nonumeros** [comment]
The PATH environment variable , and whatever number of directories has been set for that given variable, is not being recognized by kakoune. Unlike other editors, kakoune is perhaps the only editor so far which I have tested  that does not pick it up. Because it wasn't even considered. Like a million things that have slipped through without further ado. Perhaps is the only editor that does this. I haven't tested enough editors. But the few I have, does this without a problem. Vimscript, Lisp, and even lesser known editors do not have this problem.

**Comment by lenormf** [comment]
The `$PATH` is taken into account by primitives that run shell commands, such as `!` or `$`.

Your last comment only increases the confusion as to what exactly is the problem, assuming it's not just that you're wrongly expecting the editor to expand shell variables, as is the shell's purpose.

@TeddyDD has already given an answer that explains the error you reported in the first message.

**Comment by nonumeros** [comment]
@lenormf have you tried to `set` a **PATH** environment variable?

**Comment by TeddyDD** [comment]
Do you trying to set env variable using `set-option`?

**Comment by Screwtapello** [comment]
If I launch Vim with:

    $ FOO=foo.txt vim

...and then type:

    :edit $FOO

Vim edits `foo.txt`. If I try the same with Kakoune, Kakoune edits a file literally called `$FOO`. In that sense, Kakoune doesn't honour environment variables, although I guess in Kakoune you could always `:edit %sh{echo $FOO}` to obtain the same effect. However, that's got nothing to do with editing directories, and nothing to do with `$PATH`, or feature parity with other editors.

@nonumeros, I understand you've encountered some missing behaviour that seems fairly basic and obvious to you, but different people use tools in different ways, and it's quite possible that a simple and straight-forward thing you do every day is something I've never even thought to try. Can you please write down the exact, specific thing you're trying to do, describe what happens when you do that thing, and what you expected to happen instead?

**Comment by nonumeros** [comment]
@occivink by reading your reaction to @lenormf comment that follows:

>Environment variables are handled by your shell, which Kakoune is not.

My question to you is;

what is the path but another environment variable? Without which kakoune wouldn't even exist. What is the shell by which those environment variables depend upon? That should be the premiss from which anything follows. 

If you can't put that together. I can't help you. 

A question to everyone is:

What does `set` entails by calling out that very same environment variable [path]? 

if I were to `set $CATANDMOUSE` as a path environment....

How would kakoune behave if that were the case? Would calling out all the very same variable parameters that were set with taht path, return the same expected behaviour? Would `kak *` and `kak $*` and `kak $@` be the same - with or without `-n`? 

But the oinly conclusion I can arrive by looking at the remainder reactions, reactions which I think are genuine - genuine for the simple fact that I want to think I am dealing with clever guys overall - is that any outstanding issue that is brought up within this project - just now or in the past -  is sometimes, not all the time though, handled with scavenging reactions, as if the individual bringing up an issue was doing it by discrediting or disparaging the goals of the project.

**Comment by Delapouite** [comment]
@nonumeros Don't get paranoid please. You have genuine requests but your writing style is quite unusual by Internet standards where people usually go straight to the point.
So to summarize, we'll always try to help you but often have to decipher what is the real problem behind the poetry.

**Comment by nonumeros** [comment]
> Don't get paranoid please

@Delapouite you're right. You're right. I just got frustrated by my own stupidity and removed something from the system that I wasn't looking forward to. Mixed with the confused reactions by other folks , I said 'fuck it'.

Anyhow. For example, let's say there's a directory  entitled `Catandmouse` under the home directory

From the terminal (no gui)

```
export CATANDMOUSE=~/home/c/Catandmouse
set $CATANDMOUSE
kak $@ $CATANDMOUSE
```
`**debug** buffer will show you two `Catandmouse` dirs.
the same thing can be done with the home directory 

The above is something that I don't think it can just be shrugged off, and put aside

the other [issue](https://github.com/mawww/kakoune/issues/2961) that I opened before this one, and closed right after, should not be put aside either. IN this issue if `$kak_buffile` is allowing `write` operations from an external program, then it should  behave more like `$kak_bufname`. There should be no exceptions to this rule, for consistency's sake.

**Comment by lenormf** [comment]
The use of environment variables in your reproducer seems to be redundant, @TeddyDD addressed that in [their comment](https://github.com/mawww/kakoune/issues/2962#issuecomment-501171043) already:

>Kakoune does not open directories.

@Screwtapello had a good shot at guessing what you're really on about with regards to the comments about environment variables, is this whole thread only about opening directories?

**Comment by nonumeros** [comment]
but why should `kak *` allow me to just open a file with `:buffer <filename>` for the heck of it and let me write it afterwards? What's the point of `editing` that file then?

**Comment by nonumeros** [comment]
If the argument goes like  'you should `edit` a file before a `write` operation occurs in that file' then that in itself contradicts the simple operation of `kak *` with its redundant message that it can't open a  file, if this last action lets me just change buffer with `:buffer` <filename> and write that file.

**Comment by lenormf** [comment]
If you pass the path to a directory to the editor, then the editor should show a warning that it can't open it.

Do you want the editor to automatically create directories that don't exist yet, e.g. `kak $HOME/notexist/foo.txt`, and `notexist` would be created upon calling `:write`?

**Comment by nonumeros** [comment]
no.And you're right. But I wouldn't expect a simple `set $CATANDMOUSE` to have a `buffer name is already in use` either with the no less surprising `/home/c/home/c/Catandmouse` stacking up on top of one another . This last part has to do with the no less inefficient  real_path and compact_path

**Comment by lenormf** [comment]
I think I understand, if I do:

```
$ kak /etc/passwd /etc/passwd
```

then an error is shown in the debug buffer:

```
*** This is the debug buffer, where debug info will be written ***
error while opening file '/etc/passwd':
    buffer name is already in use
```

which is inconsistent with the way `:edit` works, is that it?

**Comment by nonumeros** [comment]
Thank you, I wasn't thinking of that

**Comment by nonumeros** [comment]
But what about the path variable? I don't want to open a directory but  `cd` [kak] should recognize ti  

If it's a parity feature as @Screwtapello names it, then why not the feature?

**Comment by lenormf** [comment]
Do you want `:cd $SOME_VARIABLE` to work from the editor's prompt, where `$SOME_VARIABLE` is defined in the environment of the `kak` process? As described in [this reply](https://github.com/mawww/kakoune/issues/2962#issuecomment-501298715)?

**Comment by nonumeros** [comment]
> Do you want :cd $SOME_VARIABLE to work from the editor's prompt, where $SOME_VARIABLE is defined in the environment of the kak process? As described in [this reply](https://github.com/mawww/kakoune/issues/2962#issuecomment-501298715)?

Yes, that'd be great. But I couldn't follow @Screwtapello 's reply. He said `edit %sh{echo $FOO}`

Of course, if `edit` and `cd` would work, then it'd be excellent.

On my `**debug** buffer when I try to it says
```
*** This is the debug buffer, where debug info will be written ***
shell stderr: <<<
sh: /home/c/catandmouse: Is a directory
>>>
Error: 1:1: 'cd' unable to change to directory: ''
```

**Comment by lenormf** [comment]
If you want to access shell variables from within the prompt, then spawning a shell with a `%sh{}` is the preferred way, as described by the earlier reply. You can also expand the scope on the fly by hitting <kbd>a-!</kbd> (in the prompt).

**Comment by nonumeros** [comment]
thanks for clarifying it
