### ISSUE TITLE
Duplicate buffer name error when passing the same path as argument to the editor

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2964]
Splitting #2962.

### Steps 

```
$ kak /etc/passwd /etc/passwd
```

### Outcome 

In the debug buffer:

```
*** This is the debug buffer, where debug info will be written ***
error while opening file '/etc/passwd':
    buffer name is already in use
```

### Expected 

No errors, as if the paths passed on the CLI were passed to `:edit`.

**Comment by mawww** [comment]
I dont know, this error kind of make sense, opening from the command line is not exactly the same as the `edit` command. I think it might actually be useful, as it might hint at some other issue if the same buffer name is passed multiple times on the command line, and it does not break any functionality anyway.

**Comment by lenormf** [comment]
I understand, feel free to close this issue if not relevant, I just created it to split apart several user complaints aggregated into #2962.
