### ISSUE TITLE
'`' highlighted wrong in D

### ISSUE THREAD

**Issue by John-Colvin** [mawww/kakoune#2970]
### Steps 
Type '\`'
in a .d file
### Outcome 
The \` is interpreted by the highlighting as starting a verbatim string
### Expected 
The entire '\`' should be highlighted as a character literal

Some sort of precedence issue I'm guessing.

**Comment by lenormf** [comment]
I made a fix, could you please verify highlighting is not broken on regular (i.e. reasonably long) code files?
