### ISSUE TITLE
Plans for preparing the next release

### ISSUE THREAD

**Issue by grtlr** [mawww/kakoune#2972]
Are there any plans to create a new release of Kakoune that package managers like `brew` can pick up?

The last release was back in January, and as far as I can tell quite some things have changed in the meantime.

**Comment by nonumeros** [comment]
I don't think there are releases, this is a rolling editor.

**Comment by Luflosi** [comment]
I'm very sure, that there are releases: https://github.com/mawww/kakoune/releases.

**Comment by nonumeros** [comment]
You're correct. I don't know then. I don't know. Take it up with your manager. What is this? A charitable organization?

If I type `kak -version`  it returns `Kakoune v2019.06.14`

![Screenshot_2019-06-14_19-28-34](https://user-images.githubusercontent.com/11535575/59543937-1f43d800-8edc-11e9-8056-a5b1312d8fe7.png)

**Comment by grtlr** [comment]
Here is a link to the PR which adds a reference to HEAD to homebrew: https://github.com/Homebrew/homebrew-core/pull/40982

If there is a new release of Kakoune on GitHub (@Luflosi provided the link) I can push the necessary changes.

GitHub releases can be created by contributors using `git tags`.

**Comment by Screwtapello** [comment]
On 2019-06-11, on IRC:

> 09:35 < mawww_imc> Next release is soon, I want to finish and merge the register-based-history branch first

**Comment by lenormf** [comment]
We can probably close this now.

**Comment by ajgrover** [comment]
@grtlr or someone, can you update the formula with Homebrew? it's still on the 2019.01 release so lots of things (like `plug.kak`) don't work. I gave it a shot but `brew bump-formula-pr` is broken for me atm.

**Comment by danr** [comment]
ping @alyssais

**Comment by grtlr** [comment]
I might be able to take a look at it sometimes this week. Up until then you can install the nightly version of Kakoune using:

     brew install kakoune --HEAD -s

**Comment by alyssais** [comment]
> ping @alyssais

I'm no longer using Homebrew.
