### ISSUE TITLE
gocode is not maintained

### ISSUE THREAD

**Issue by pltrz** [mawww/kakoune#2976]
from `rc/tools/go/go-tools.kak`:

> ```
> # Provides integration of the following tools:
> # - gocode for code completion (github.com/nsf/gocode)
> ```

from `github.com/nsf/gocode`:
> this project is not maintained anymore, look for alternatives or forks if you need Go autocompletion tool

Now, that project has a maintained fork at [mdempsky/gocode](https://github.com/mdempsky/gocode), and there is also a fork of mdempsky's fork that supports Go modules at [stamblerre/gocode](https://github.com/stamblerre/gocode).

The natural thing to do first of all is to switch tho go-tools.kak comment to use mdempsky's fork. Then, we might consider if we want to use stamblerre's fork after, since it would allow for Go modules

**Comment by nonumeros** [comment]
> The natural thing to do first of all is to switch tho go-tools.kak comment to use mdempsky's fork. Then, we might consider if we want to use stamblerre's fork after, since it would allow for Go modules

sounds good for anyone who needs it, but then what?

I've found it pestering to have 

```
#evaluate-commands %sh{
#    for dep in gocode goimports gogetdoc jq; do
#        if ! command -v $dep > /dev/null 2>&1; then
#            echo "echo -debug %{Dependency unmet: $dep, please install it to use go-tools}"
#        fi
#    done
#}
```
not commented out by factory settings. And when I see that sort of shit I really start wiping  that shit  out to the point that even `xorg -b` fails.

**Comment by nonumeros** [comment]
When a pressing issue comes up on the `**debug**` buffer letting you know that 
```
Dependency unmet: gocode, please install it to use go-tools
Dependency unmet: goimports, please install it to use go-tools
Dependency unmet: gogetdoc, please install it to use go-tools
Dependency unmet: jq, please install it to use go-tools
```
Then a quick search by modern 'standards' returns:

https://github.com/ul/kak-lsp/issues/155

and 

https://github.com/mawww/kakoune/issues/1612

something tells me that some piece of code is not doing what's supposed to do. And guess what? 

yep. I'd love to be wrong. But That piece of code is part of it.

**Comment by lenormf** [comment]
@pltrz have the forks changed the API of the tool? If not it might be simpler to remove the address between parenthesis, let users pick an implementation themselves.

**Comment by pltrz** [comment]
Just to preface: I am pretty new to kakoune, and I'm still trying to understand how things work in it etc. I also never used LSP (and go-langserver, kak-lsp by extension) until now, and on that end, I also don't really understand how it all works.

Now, I just tried kak-lsp and now it kind of seems like the whole go-tools.kak is redoing the work of kak-lsp, am I wrong? Now, I don't know what to think or do.

@lenormf I really do not know if the API changed between forks

**Comment by nonumeros** [comment]
> have the forks changed the API of the tool? If not 

If yes? it's my vacuous understanding that this is highly likely.

@lenormf  in all fairness though, you'd probably be better off by watching (what a punishment for me that was, since they couldn't even provide in this time and age a decent transcript of the whole thing and if there's one I couldn't even find it, but just some slides along the way) https://www.reddit.com/r/golang/comments/blcxb4/go_pls_stop_breaking_my_editor_rebecca_stambler/

>go 1.10 came up because go code broke with go 1.10 because a build hash was added 

>fortunately an engineer rewrote it and forked it to his own repository

>but go 1.11 modules were released.

>go tools broke again.

>forked from mdempksy, a version that fixes the modules.  

>so three different versions. 

>gopls gopels released a language server

>it's built on top of the go package APIII

>so it will work for all build systems

>it's built on top of lsp so it will work on all editors

**Comment by pltrz** [comment]
@nonumeros watched the talk. Very interesting. It'd be great to try and get `gopls` to work with kak-lsp, that would solve a number of the existing problems, and make it simpler on our end. Even though it's still alpha, I think it's still worth experimenting with.

**Comment by pltrz** [comment]
As an aside, just by having a quick glance into go-tools.kak, it seems to run `gocode -f=godit` in at least one instance. This flag option is available in the original gocode but not in the fork, so not 100% compatible at the very least.

**Comment by nonumeros** [comment]
> gopls to work with kak-lsp, that would solve a number of the existing problems, and make it simpler on our end

@pltrz  but while you're thinking of that, I'm thinking on the side-effect that some code from go-tools.kak - out of all the files from the arsenal - has had and currently has on the editor. It's like a saying in Spanish that goes something like: 'Una cosa es lo que piensa el borracho, y otra cosa es lo que piensa el bodeguero.' (The drunkard thinks how he'll get away with the drink, while the store owner thinks whether the drunkard will pay for that drink.) It doesn't really matter who the drunkard or the store owner in this case is. That's not relevant.

Of course, this is not game theory. But what really is relevant is that whenever some changes occur, everything should be taken into consideration.

And there may be other questions about this extension from the Go Team, that the devs might have.

As I understand, Go developing moves at a relative fast rate. 

What fork - out of the three - are the devs form the Go Team using?

Let's ask someone who might give some further insights about this.

@stamblerre hello. You're a cute face :)  And I followed the talk you gave about the extension. I tried to highlight on the previous message some of the keys of this extension you mentioned. 

But have you ever used kak (short for kakoune)?

What are the plans for this extension? Long term?

**Comment by pltrz** [comment]
Would also love to hear from @stamblerre about this

**Comment by stamblerre** [comment]
The latest information on `gopls` is available here: https://github.com/golang/go/wiki/gopls. The Go team is developing `gopls` as a replacement for `gocode`, `godef`, `gorename`, and a variety of other Go tools, so I would definitely recommend moving towards `gopls` as the replacement. It is still relatively unstable, but the alpha version can be installed via `go get -u golang.org/x/tools/gopls@latest`. VSCode-Go uses `gopls` by default in module mode, as does vim-go.

**Comment by nonumeros** [comment]
> The Go team is developing gopls as a replacement for gocode, godef, gorename, and a variety of other Go tools

So I'm assuming that with the same token, ` goimports gogetdoc jq` will eventually be replaced as well

> https://github.com/golang/go/wiki/gopls

thanks for the link 

> VSCode-Go uses gopls by default in module mode, as does vim-go.

Good to know. Thanks again!

**Comment by pltrz** [comment]
ul/kak-lsp/issues/210
