### ISSUE TITLE
Compilation warning in definition of the ArrayView type

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2985]
The following warning is being printed when compiling with `g++` v9 (`clang++` v8 doesn't show it):

```
g++  -O3 -pedantic -std=c++17 -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-address -MD -MP -MF .alias_registry.opt.d -c -o .alias_registry.opt.o alias_registry.cc
In file included from unicode.hh:7,
                 from utf8.hh:5,
                 from string.hh:7,
                 from alias_registry.hh:5,
                 from alias_registry.cc:1:
array_view.hh: In instantiation of ‘constexpr Kakoune::ArrayView<T>::ArrayView(const std::initializer_list<_Tp>&) [with T = const Kakoune::StringView]’:
string_utils.hh:117:18:   required from ‘Kakoune::String Kakoune::format(Kakoune::StringView, Types&& ...) [with Types = {Kakoune::String}]’
string_utils.hh:132:44:   required from here
array_view.hh:39:48: error: initializing ‘Kakoune::ArrayView<const Kakoune::StringView>::m_pointer’ from ‘std::initializer_list<const Kakoune::StringView>::begin’ does not extend the lifetime of the underlying array [-Werror=init-list-lifetime]
   39 |         : m_pointer(v.begin()), m_size(v.size()) {}
      | 
```

I think the following documentation paragraph is relevant ("since C++14"):

[cppref](https://en.cppreference.com/w/cpp/utility/initializer_list)

>The underlying array is a temporary array of type const T[N], in which each element is copy-initialized (except that narrowing conversions are invalid) from the corresponding element of the original initializer list. […]

The problem might be fixed by turning the internal pointer in question into an rvalue reference?

[cppref](https://en.cppreference.com/w/cpp/language/reference_initialization#Lifetime_of_a_temporary)

HTH.

**Comment by mawww** [comment]
This warning looks spurious to me, in C++ temporary object lifetime ends at the end of the full expression that triggers their creation, in other words, 'at the semicolon'. That means the temporary initializer_list (and backing array) are alive until the end of the format call, and do outlive the ArrayView.

Seems g++-9 gets confused about that somehow, or their might a C++ subtlety being triggered here.

**Comment by mawww** [comment]
Yeah, it seems g++ is over-eager in warning there, it would be a good warning if we were creating a variable of type ArrayView, as it would out-live the temporary initializer_list that it references. But all cases where this warning triggers are legitimate, the ArrayView itself is a temporary, so its lifetime cannot outlive another temporary its initialized from (their lifetime ends at the same point, in reverse order of creation).
