### ISSUE TITLE
additional modeline-like area?

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#2989]
We can display status messages in modeline, but if there's too much going on in modeline it becames cluttered and less usable. Vim and Emacs have the second modeline like area on the top which is hidden by default but can be shown to display additional info that should stay on the screen. Like opened tabs in Vim:

![image](https://user-images.githubusercontent.com/19470159/60044961-39e03300-96cc-11e9-8c0c-4f314393bf35.png)

It's nice visual queue what buffers are currently open, which of those have changes, e.t.c. Since there's [kakoune-buffers](https://github.com/Delapouite/kakoune-buffers), that provides convenient list of buffers through the info box I guess people will be interested in a more persistent way to display this info. Maybe.

Or in Emacs if you open package menu, you'll see this top line:

![image](https://user-images.githubusercontent.com/19470159/60045085-94798f00-96cc-11e9-8bc6-5c3866ac52fa.png)

You can see in the modeline that I've scrolled thorugh 62% of the file, and this top line is still the top one, since it's not the part of the buffer.

So this is kind of area which plugins could utilize in order to provide their additional information.

**Comment by TeddyDD** [comment]
Probably related #1942

**Comment by andreyorst** [comment]
another request that may benefit from it a bit: https://github.com/mawww/kakoune/issues/2727

**Comment by lenormf** [comment]
Would this area render the value of a new option, like `modelinefmt` except named something else?

Would the bar be a UI widget, which would make the option mentioned above a simple field in `ui_options`, or should the protocol be extended to support it in the UI API?

Would the bar collapse (i.e. not be rendered at all and replaced by a line from the buffer's contents) when there's no data to render?

Would formatting of the data (e.g. spaces between the words in it) be the responsibility of the user, or are there expectations from the editor?

**Comment by andreyorst** [comment]
> Would this area render the value of a new option, like `modelinefmt` except named something else?

I think this is the way to go.

> Would formatting of the data (e.g. spaces between the words in it) be the responsibility of the user, or are there expectations from the editor?

In my opinion it should just render as is. Plugin would set a buffer local value of the option and fill it as it needs.

> Would the bar collapse (i.e. not be rendered at all and replaced by a line from the buffer's contents) when there's no data to render?

I don't think so. I think the line should be explicitly made visible or hidden by user settings. Possibly have a buffer local value, so in one buffer where it should display column names it is wisible, and in another buffer where it is empty it is hidden or shown depending on user settings, like `hidden`, `shown`. Not sure about this though.
