### ISSUE TITLE
How to rebind "?

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#299]
I'm trying to rebind `"`. But

    map global normal x "

gives unterminated string error, and

    map global normal x \"

sends `\`, no hooks, and then `"`

I've tried using `:exec`, but I cannot avoid getting it to complain about unterminated strings as well.

Thanks,
Dan

**Comment by ekie** [comment]
hello,

`map global normal x "\""`
or
`map global normal x '"'`

**Comment by danr** [comment]
Thanks, that was simple!
