### ISSUE TITLE
Rename ModuleLoad hook to ModuleLoaded

### ISSUE THREAD

**Issue by codesoap** [mawww/kakoune#2991]
When learning about the `ModuleLoad` hook I was uncertain whether the hook runs before or after the specified module is loaded. The documentation says:

> Triggered when a module is evaluated by the first require-module call

which still sounds somewhat ambiguous to me.

After trying it out and thinking for a second it became clear, that the hook is run after the module has been sourced, but maybe renaming the hook to `ModuleLoaded` would prevent any confusion for future readers.

What do you think? I could prepare a pull request if there is a consensus, that this change would be a good idea.

**Comment by lenormf** [comment]
Make a PR anyway!

**Comment by Delapouite** [comment]
To alleviate this ambiguity, we could follow this existing pattern: `BufWritePre` vs `BufWritePost`.
So in this case `ModuleLoad` would become `ModuleLoadPost`

**Comment by laelath** [comment]
@Delapouite I'm not sure having a hook run before a module loads would be too helpful. It was added to have a point where options declared by modules could be known to exist and be changed, which only makes sense after the module is loaded. Unless there's a use case I'm not seeing.

**Comment by codesoap** [comment]
@Delapouite I see, that it would be more consistent to use `ModuleLoadPost`, but after thinking about it for a bit I found that it introduces new ambiguity. If I didn't see `BufWritePre` and `BufWritePost` before, I could imagine the `Post` to be irritating, since it has several meanings in the englisch language.

I have created #2992.

**Comment by codesoap** [comment]
#2992 is merged.
