### ISSUE TITLE
Highlighters not working

### ISSUE THREAD

**Issue by Julian-Mentasti** [mawww/kakoune#3007]
### Steps 
Upgraded to the latest Kakoune release, now If I load any file with kak, for example `main.go` none of the highlighters will pop up -`int` stays the same color.

### Outcome 
In the debug buffer I see the following
```
plug.kak: Can't declare highlighters for kakrc.
          Detailed error: 2:6: 'add-highlighter' no such id: 'kakrc':
```
### Expected 
The highlighting used to be working fine. 

### ENV:
Kakoune v2019.07.01
Arch Linux

**Comment by Julian-Mentasti** [comment]
I removed the autoload folder and it began to work.

**Comment by laelath** [comment]
Has the highlighting issue been resolved? As for the `plug.kak` errors, it appears like @andreyorst hasn't merged the dev branch that has the module changes yet.

**Comment by andreyorst** [comment]
correct, please use plug.kak on dev branch for now. I'll have time only next week to update all my plugins

**Comment by andreyorst** [comment]
@Julian-Mentasti just letting you know that I've updated master branch of plug.kak so you sould not experience that error message form plug.kak anymore

**Comment by mawww** [comment]
Seems thats fixed, closing.
