### ISSUE TITLE
Colorschemes as commands, or configurable path to them

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#3009]
There was a discussion at plug.kak repo: https://github.com/andreyorst/plug.kak/issues/65 and I've thought about small colorscheme related refactoring that could make colorschemes more generic and easier to maintain.

>Themes, on the other hand are not loaded. When you use `colorscheme` command it looks up for available theme files located at specific places: in your `%val{config}/colors` and `%val{runtime}/colors` and provides those file names as completions to that command. Unfortunately we cant extend the list of places where to look for themes, so `colorscheme` could find themes installed by plug.kak. If we could though, we will not need to copy theme files to `%val{config}/colors`. There was a feature request for this somewhere at Kakoune, and I'm not sure why it wasn't done in the same way how we can extend the `%opt{path}` option. With this change the theme maintenance process will be pme much much easier for plugins.
>
>Another approach for a theme would be to implement a command, and add it to list of theme commands, that will be used as completions for `colorscheme`, and it will simply call a command that will set the colors. This way we well not even need to distinguish themes and plugins, since there's no difference anymore, and we will not need the `%val{config}/colors` and `%val{runtime}/colors` at all, and it will make plugin manager simpler a lot. 

So the problem is, that the only reliable way to install external theme is to copy it to `%val{config}/colors` or add a symbolic link to this directory, in order to be able to update theme. I don't really understand why it was chosen to separate themes to their own directory outside of the `rc` in the first place, so I'm proposing two different ways how we can simplify external theming a little bit.

One way is to allow managing the list of paths where `colorscheme` command looks for themes, here:

https://github.com/mawww/kakoune/blob/eba40028b983f1698dc79aae779f2d8eda8918c4/share/kak/kakrc#L3

Or.

Completely change how themes are defined:
- Wrap themes into the `define-command -hidden` block:
  ```
  define-command -hidden gruvbox-theme %{ face ... }
  ```
- Add the name of the command to the global `colorschemes` option to provide completions:
  ```
  set-option -add global colorschemes 'gruvbox-theme'
  ```
- change `colorscheme` to call the command instead of sourcing theme file:
  ```
  define-command colorscheme \
  -shell-scipt-candidates %{
      eval "set -- $kak_quoted_opt_colorschemes"
      # maybe there's a better way though
      for theme in "$@"; do
          printf "%s\n" "$theme"
      done
  } -params 1 %{ evaluate-commands %arg{1} }
  ```

I've already used the second method in my [powerline.kak](https://github.com/andreyorst/powerline.kak) plugin, to load modeline themes by calling their commands through a wrapper function:

```
define-command -docstring "powerline-theme <theme>: apply theme to powerline" \
-shell-script-candidates %{ eval "set -- ${kak_quoted_opt_powerline_themes}"; while [ "$1" ]; do echo $1; shift; done} \
powerline-theme -params 1 %{ evaluate-commands %sh{
    echo "powerline-theme-$1"
    echo "powerline-rebuild"
}}
```

The first way will be a workaround for others who want to store their themes in a separate directory, e.g. in plugin installation directory, and in general will require less changes to the overall ecosystem.

The second way will make it possible to load themes at startup, so they can be safely moved to the `rc/colors` directory, and plugin managers will be able to add installed themes to the global theme list. This change will require to rework all themes a bit, and if you don't mind I can actually do that. But this also will require other themes that are not part of Kakoune to adapt to this mechanism, so it may be little painful.

I want to hear your thoughts on these approaches, and the situation in general.

**Comment by mawww** [comment]
I think my idea at it time I put themes separately is that conceptually only one colorscheme is enabled at one time. We switch colorchemes, we do not enable one on top of another.

In practice though, this is exactly what happens, colorschemes are just a set of commands that are run when we switch to it, and there is no guarantee a colorscheme will no leak some state into the next. It is already the case whenever a colorscheme sets some "extended" faces that another does not.

I guess the root of the question is shall colorschemes be considered a kind of plugins, or are they something different. My intuition is that they are different, but are they different enough to warrant the additional complexity of handling them specially.

So no big answer here, happy to discuss that further.
