### ISSUE TITLE
extra_word_chars and codepoints beyond 128

### ISSUE THREAD

**Issue by ganwell** [mawww/kakoune#3010]
I'd like to complete words containing characters beyond codepoint 128, Latin-1 in my case, for example "öäü". This works in the current buffer, but not for other buffers, because this filter removes the words containing Latin-1 characters: (Update: it seems the filter function is not unicode-enabled)

https://github.com/mawww/kakoune/blob/2ff9fd8d9262e9fd1361dd2c0e873277aabad663/src/insert_completer.cc#L139

In vim "\k" includes word-characters from many scripts. I tried: German, French, Japanese and Chinese. I wonder if implementing '\k' is beyond the scope of kakoune, or if an option to turn this filter off would be acceptable. I guess I can live with patching the source. Or maybe there is a workaround, of course I could also patch extra_word_chars in the relevant filetypes. Most of the code-bases I work with don't have German messages and comments, but some do, and completing message-texts is a great remedy against typos.

So my question is: If this is an issue that should be fixed in kakoune, if so, how? Depending on the complexity I might be able to do a PR.

**Comment by ganwell** [comment]
I found this workaround. I just started learning kakoune, so there is probably a better solution. But this seems to add umlauts to any filetype.

```bash
hook global BufSetOption extra_word_chars=.* %{
    evaluate-commands %sh{
        if [[ ! "${kak_hook_param}" =~ "ä" ]]; then
            echo set-option -add buffer extra_word_chars ö ä ü Ö Ä Ü
        fi
    }
}
set-option -add global extra_word_chars ö ä ü Ö Ä Ü
````

**Comment by Screwtapello** [comment]
If you set an option at the global scope, it's automatically available at the buffer and window scopes (unless they override it). So it should be enough to put just the last line in your `kakrc`:

    set-option -add global extra_word_chars ö ä ü Ö Ä Ü

**Comment by lenormf** [comment]
I think the issue comes from the fact that `rm.candidate()` points to a string that stores characters as `char`, which will cause false negatives when gathering candidates for completion - the bug can be reproduced with other characters whose value require more than `sizeof(char)` to be stored.

You can work around that by using `extra_word_chars`, but obviously that doesn't fix the problem.

**Comment by ganwell** [comment]
> set-option -add global extra_word_chars ö ä ü Ö Ä Ü

This doesn't work unfortunately.

> You can work around that by using `extra_word_chars`, but obviously that doesn't fix the problem.

I first expected giving extra_word_chars a complete list of chars would work, but didn't try it, because I was already thinking about a more general solution (the \k regex match). I think - as @lenormf said - the filter isn't unicode-enabled.

**Comment by mawww** [comment]
You correctly identified the issue, that filter is iterating on each bytes in the candidate string instead of iterating on the decoded codepoints. Just pushed a fix.

**Comment by ganwell** [comment]
Thanks that works, I updated the script to set the extra_word_chars. Hopefully its POSIX-compatible and better kakoune style:

```bash
declare-option -hidden str-list extra_word_extension ö ä ü Ö Ä Ü é à è É À È
hook global BufSetOption extra_word_chars=.* %{
    evaluate-commands %sh{
        if ! expr "${kak_hook_param}" : ".*ä.*" > /dev/null; then
            echo set-option -add buffer extra_word_chars %opt{extra_word_extension}
        fi
    }
}
set-option -add global extra_word_chars %opt{extra_word_extension}
```

**Comment by lenormf** [comment]
The issue you reported was a bug in the editor, you don't need to add anything to your user configuration to get completion candidates from other buffers to show up. Have you re-compiled and tried again?

**Comment by ganwell** [comment]
> The issue you reported was a bug in the editor, you don't need to add anything to your user configuration to get completion candidates from other buffers to show up. Have you re-compiled and tried again?

@lenormf  Yes. Thanks. The script isn't needed.

Update: Accepting Latin-1 Codepoints is kakoune's **default.** There is no need to configure anything.
