### ISSUE TITLE
How to change default keybindings

### ISSUE THREAD

**Issue by blueray453** [mawww/kakoune#3020]
I want to replace

```
h: select the character on the left of selection end
j: select the character below the selection end
k: select the character above the selection end
l: select the character on the right of selection end
```
With arrows.

`d: yank and delete current selection`
With <c-x>

How can I do that?

**Comment by Screwtapello** [comment]
Arrows should already work, including with the Shift and Alt modifiers.

For your other example, you want something like:

    map global normal <c-x> d

...but be aware that Kakoune's "yank" does not store the yanked text on the system clipboard, but only in its own internal clipboard (that is designed to handle multiple selections). For system clipboard integration [see the wiki](https://github.com/mawww/kakoune/wiki/Registers---Clipboard).

**Comment by blueray453** [comment]
Sorry, I am new to Kakoune. What did you mean by "Shift and Alt modifiers". Can you please elaborate a little bit.

**Comment by Screwtapello** [comment]
I mean pressing <kbd>→</kbd> moves the cursor right by one character, and pressing <kbd>Shift</kbd>+<kbd>→</kbd> extends the selection rightwards by one character. It turns out I mis-remembered about Alt—<kbd>Alt</kbd>+<kbd>l</kbd> jumps to the end of the line (like <kbd>End</kbd>), but <kbd>Alt</kbd>+<kbd>→</kbd> doesn't do anything (I guess since <kbd>End</kbd> does the same thing and is easier to press).

**Comment by blueray453** [comment]
Thanks. Now I understand.

**Comment by blueray453** [comment]
Please help me out a bit. I am trying to use ctrl+a to select all.

I tried:

`map global normal <c-a> %`

and also 

`map global normal <c-a> <s-5>`

not working/

**Comment by SeerLite** [comment]
It's the first way you did it (there's no "shift" modifier in Kakoune), but you have to escape the `%` because it's used for expansions (`:doc expansions`).

You can use either:
```kak
map global normal <c-a> '%'
```
or
```kak
map global normal <c-a> \%
```
to prevent Kakoune from trying to expand `%`.

**Comment by blueray453** [comment]
Thank you very much.

**Comment by blueray453** [comment]
One more question please. The following works:

`map global normal y '<a-|> xsel --input --clipboard <ret>'`

But the following does not:

`map global normal <c-c> '<a-|> xsel --input --clipboard <ret>'`

Is there any reason for that?

**Comment by SeerLite** [comment]
I found [this](https://github.com/mawww/kakoune/issues/797#issuecomment-649494417). It looks like `<c-c>` can't be mapped :/.

**Comment by blueray453** [comment]
Thank you very much.

**Comment by blueray453** [comment]
I am trying to unbind few keys in normal mode. However, the following is apparently not working.

```
unmap global normal <a-d>
unmap global normal j
unmap global normal k
unmap global normal l
unmap global normal H
unmap global normal J
unmap global normal K
unmap global normal L
unmap global normal <a-h>
unmap global normal <a-l>
```
Is there any reason for that?

**Comment by Screwtapello** [comment]
If you use `map` to layer some other behaviour on top of the defaults, you can use `unmap` to remove that behaviour and return to the defaults. You can't unmap the defaults, they're the defaults.

You could concievably map those keys to the empty string, though, or some do-nothing sequence like `:<esc>`.

**Comment by blueray453** [comment]
Thank you very much.

So can I do things like:
`map global normal l ~`

I mean 'l' for lower case.

**Comment by Screwtapello** [comment]
Kakoune's `~` command makes things upper-case, so it would seem odd to map `l` to that... but sure, you could do that.

**Comment by blueray453** [comment]
I have keybindings like the following.

```
map global normal ( <a-i>(
map global normal [ <a-i>[
map global normal { <a-i>{
```
So, if I press <kbd>(</kbd> in normal mode, it select the enclosing parenthesis....

How can I make it so that <kbd>[</kbd> in normal mode will enclose <kbd>(</kbd> or <kbd>{</kbd> or <kbd>[</kbd> or <kbd><</kbd> or <kbd>"</kbd> or <kbd>'</kbd> or <kbd>`</kbd>

**Comment by blueray453** [comment]
One more thing please. The following is not working
```
map global normal <c-l> '`'
```
Is it just me or `<c-l>` is not actually bindable.

**Comment by Screwtapello** [comment]
I'm not sure what you mean by "enclose <kbd>(</kbd> or <kbd>{</kbd> or <kbd>[</kbd> or <kbd><</kbd> or <kbd>"</kbd> or <kbd>'</kbd> or <kbd>`</kbd>". If you had all those symbols in a row and pressed <kbd>[</kbd>, what would you expect to happen?

As for `<c-l>`, I can certainly bind it here, but if you bind it to backtick then it won't do anything most of the time - it squashes the selection to lowercase, so on already-lowercase text, or numbers or symbols, nothing happens.

**Comment by blueray453** [comment]
@Screwtapello thank you very much.

What I meant is: when we press `<a-i>` there are options like:

```
b, (, )

    select the enclosing parenthesis
B, {, }

    select the enclosing {} block
r, [, ]

    select the enclosing [] block
a, <, >

    select the enclosing <> block
Q, "

    select the enclosing double quoted string
q, '

    select the enclosing single quoted string
g, `

    select the enclosing grave quoted string

```
So, <kbd>(</kbd>'s enclosing part is definitely <kbd>)</kbd>
<kbd>{</kbd>'s enclosing part is definitely <kbd>}</kbd>
<kbd>[</kbd>'s enclosing part is definitely <kbd>]</kbd>
<kbd><</kbd>'s enclosing part is definitely <kbd>></kbd>
<kbd>"</kbd>'s enclosing part is definitely <kbd>"</kbd>
<kbd>'</kbd>'s enclosing part is definitely <kbd>'</kbd>

So, I do not what to manually select the enclosing character. I always want to press <kbd>[</kbd> so that it selects till the enclosing part.

In algorithm, what I am looking for is:

if current selected char is <kbd>(</kbd> select till <kbd>)</kbd>
if current selected char is <kbd>{</kbd> select till <kbd>}</kbd>
if current selected char is <kbd>[</kbd> select till <kbd>]</kbd>
....

That way it will not occupy all those chars in my normal mode (and I also will not have to frequently go to the Object mode):

```
map global normal ( <a-i>(
map global normal [ <a-i>[
map global normal { <a-i>{
....
```
I am open to write some code as well, if you tell me what to do. However, I think if we can use [multiple commands](https://github.com/mawww/kakoune/blob/master/doc/pages/commands.asciidoc#multiple-commands) then the problem can be solved without writing any code. 

Please let me explain. There are most probably [commands](https://github.com/mawww/kakoune/blob/master/doc/pages/commands.asciidoc) associated with [keys](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#objects-types).

Suppose,

the command associated with the key `<a-i>(` is `select-the-enclosing-parenthesis` 
the command associated with the key `<a-i>(` is `select-the-enclosing-block-a`
the command associated with the key `<a-i>(` is `select-the-enclosing-block-b`
.....

Then we can do something like:
```
define-command select-till-enclosing-part select-the-enclosing-parenthesis;select-the-enclosing-block-a;select-the-enclosing-block-b
map global user [ ': select-till-enclosing-part<ret>'
```
I hope this will work. Because, one char at a time can not be multiple things. So, it will either be <kbd>(</kbd> or <kbd>{</kbd> or <kbd>[</kbd>.... So, though we have chained multiple commands only the appropriate one is supposed to work.

**Comment by Screwtapello** [comment]
> There are most probably commands associated with keys.

No, there aren't. The name of the "select within parenthesis" command is `<a-i>(` (or possibly `<a-i>)` or `<a-i>b`). Even in the C++ code there's no specific name for that action, it's just part of the general `select_object()` function.

That said, I think there's an easy way to do what you want:

    map global normal [ ': execute-keys <a-i> %val{selection}'

That way, whenever you hit [, Kakoune will type `<a-i>` followed by whatever you have selected - if your cursor's on `[`, it'll select inside `[`. If your cursor's on `"`, it'll select inside `"`.

**Comment by blueray453** [comment]
I am super greatful. Thank you very much.

**Comment by blueray453** [comment]
@Screwtapello  have you noticed something. if we use `map global normal [ ': execute-keys <a-i> %val{selection}'` the prompt shows like `map global normal [ ': execute-keys %val{selection}'`. It removes `<a-i>`.

**Comment by blueray453** [comment]
this works: `map global normal [ ': execute-keys <lt>a-i<gt> %val{selection}'`. However, it would be great if I did not have to press `<ret>`.

**Comment by Screwtapello** [comment]
Ah, right, sorry. I ran `execute-keys <a-i> %val{selection}` interactively, but I didn't actually try it in a mapping and forgot the extra changes needed. Replacing `<` with `<lt>` is one of them, the other is adding `<ret>` at the end:

    map global normal [ ': execute-keys <lt>a-i<gt> %val{selection} <ret>'
