### ISSUE TITLE
delimeter face?

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#3023]
There's `operators` face in colorschemes, but no `delimiter` face. It would be nice to have one

**Comment by mawww** [comment]
What kind of delimiters do you have in mind ?

**Comment by lenormf** [comment]
There's commas in CSV.

A global face is probably not needed, the (few?) languages that actually have the delimiter concept can declare the face in their own support script.

**Comment by andreyorst** [comment]
theme creators might want to be in control of the faces. Me personally want to be able to highlight braces, colons, and other symbols that act as delimiter in C++, as well as operators. I guess the language servers or tree sitter might share the concept of delimiter for some languages, and it's very basic concept, so the face might be needed

**Comment by andreyorst** [comment]
Also highlighting regular expressions requires face for delimiters, I guess:

![image](https://user-images.githubusercontent.com/19470159/61619386-6bbaca00-ac77-11e9-88ff-20635b717ca2.png)

Here Emacs highlights group delimiters in regular expression making it easier to read.

**Comment by mawww** [comment]
I am not sure if the distinction between delimiters and operators is strong enough to warrant two faces, I suspect it will be very hard to agree on whether something is one or the other.

**Comment by andreyorst** [comment]
No problem!)
