### ISSUE TITLE
Can not build on Ubuntu

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#303]
When running <code>make</code> in <code>src</code> I receive the following error:
<pre><code>make
g++ -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -pedantic -DKAK_DEBUG -MD -MP -MF .input_handler.d -c -o .input_handler.o input_handler.cc
In file included from option_manager.hh:9:0,
                 from scope.hh:7,
                 from buffer.hh:7,
                 from selection.hh:4,
                 from context.hh:4,
                 from input_handler.hh:5,
                 from input_handler.cc:1:
regex.hh:9:27: fatal error: boost/regex.hpp: No such file or directory
 #include <boost/regex.hpp>
                           ^
compilation terminated.
Makefile:43: recipe for target '.input_handler.o' failed
</code><pre>

**Comment by mawww** [comment]
Hello,

you need boost development packages to be installed I think they are called libboost-all-dev on ubuntu.

**Comment by FranzSkuffka** [comment]
Ok, I will update the docs once I find the time, maybe even write an install script. Are there similar dependencies on other linux distributions?

By the way, this looks very promising and makes me wish I knew how to write C. Thank you for your work!

**Comment by mawww** [comment]
You are welcome, boost and ncurses are requiered on all distribution to compile kakoune.

**Comment by FranzSkuffka** [comment]
after installing libncurses5-dev i still get
<code>/usr/bin/ld: cannot find -lncursesw</code>

linuxbrew fails on some dependencies too,
can you help me out? Would really love to use this at work too.

**Comment by mawww** [comment]
you need to install ncurses dev packages (libncursesw5-dev)

**Comment by FranzSkuffka** [comment]
Ah I got it. Need libncurses with wide character support.
