### ISSUE TITLE
Broken c-falmily indent on if-else statement

### ISSUE THREAD

**Issue by cglogic** [mawww/kakoune#3032]
### Steps 
Just type the following code in a C/C++ file. Brackets after the _else_ are misaligned.

`kakoune version: 2019.07.01`

### Outcome 
```C++
if ()
{
}
else
        {
        }
```
### Expected 
```C++
if ()
{
}
else
{
}
```

**Comment by andreyorst** [comment]
I guess that happens because there's indent on return after `else` and it's not canceled with the `{`

**Comment by cglogic** [comment]
> I guess that happens because there's indent on return after `else` and it's not canceled with the `{`

Indeed. I have tried to fix it in #3035.
