### ISSUE TITLE
Write Cheatsheet

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#304]
An isolated guide including a cheatsheet and possibly a diff of this and vim would be a great way to get many people started properly.

**Comment by mawww** [comment]
there is already the doc/keymap file and VIMTOKAK one for helping new users (as well as the README)

**Comment by zakgreant** [comment]
I was hoping to find some similar resources. I'm using the Colemak layout on a US keyboard and an unlabelled keymap for a non-US keyboard isn't as helpful for me as it could be. :)

So, I wrote a small script to pull keys and descriptions of out [src/normal.cc](https://github.com/mawww/kakoune/blob/master/src/normal.cc#L1480), and dropped the results onto the wiki at https://github.com/mawww/kakoune/wiki/Normal-mode-commands

**Comment by mawww** [comment]
Thats quite nice, would you mind putting the script somewhere (a pull request to add it in contrib/ would be welcome) so that we can update the page from time to time ?

**Comment by zakgreant** [comment]
I'm glad it's useful! I'll tidy up the script and then send a pull request.
