### ISSUE TITLE
Markdown: Incorrect syntax highlighting across lists

### ISSUE THREAD

**Issue by benburk** [mawww/kakoune#3041]
### Steps 
Open a buffer containing:
```
- _foo
- bar_
```

### Outcome 
`_foo\n- bar_` is highlighted as italics.

### Expected 
It should not be matched. I believe the bug also occurs for other markdown syntax such as bold.

**Comment by mawww** [comment]
Just took a look, this is actually quite a rabbit hole, regex highlighters do not respect the regions they apply to as they should, so even though each bullet should be a separate region, we end up highlighting across them.
