### ISSUE TITLE
New rust highlighting doesn't handle braces in strings in meta attributes

### ISSUE THREAD

**Issue by daboross** [mawww/kakoune#3043]
### Steps 

Compile and install the latest kakoune from git, from the commit https://github.com/mawww/kakoune/commit/550feb1706e248edd4fe0cf526c12cdefbfab7ce.

Create a new file, `test.rs`, and enter the following code:

```rust
#[doc = "See: [std::result::Result]."]
fn function() {

}
```

### Outcome 

The code is highlighted as though the inner `]` ends the meta block, and then the following `"` starts a new string.

![screenshot-20190802-134422](https://user-images.githubusercontent.com/1152146/62397778-a4865900-b52b-11e9-99ab-b2e8e004a6ea.png)

### Expected 

I would expect that the meta-color highlighting continues until the final `]`, and then the function is highlighted as normal. Something like what happens if I have a string in a meta block which doesn't contain `[]`:

![screenshot-20190802-134446](https://user-images.githubusercontent.com/1152146/62397796-b23bde80-b52b-11e9-93d3-8590620ce494.png)

Running kakoune compiled from https://github.com/mawww/kakoune/commit/e840140b38f5e690b61016f5f982c1765165328e, directly before #3027 was merged, also results in correct (but slightly less nice) highlighting:

![screenshot-20190802-135053](https://user-images.githubusercontent.com/1152146/62398087-8d943680-b52c-11e9-9ff7-b564e00e5248.png)

---

I should say that I do like the new highlighting better overall, and this is definitely an edge case. But this is correct rust code, so it'd be nice if it was highlighted as such.

**Comment by daboross** [comment]
I'm guessing this has the same underlying issue as #3024 with nested scopes.

**Comment by andreyorst** [comment]
> But this is correct rust code, so it'd be nice if it was highlighted as such.

I've changed that highlighting from `regex` to a `region`. I wasn't aware of such construct. This probably would be easy to fix. I'll check this out

**Comment by andreyorst** [comment]
On a side note, previous implementation didn't handle this case as wall. You can see that `#[doc = ` and closing `]` lacks highlighting
