### ISSUE TITLE
what is <gt> what is <lt> and what is <a> in the docs?

### ISSUE THREAD

**Issue by NikosEfthias** [mawww/kakoune#3050]
docs mention keys like <a-j> but what is <a> i tried alt which doesn't seem to work
and about <lt> and <gt> i have no clue what they are i dont have such special eys on my keyboard at least

**Comment by Screwtapello** [comment]
[`:doc keys`](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc) describes the syntax Kakoune uses for keys.

**Comment by NikosEfthias** [comment]
I now checked again it doesnt have any information about this @Screwtapello

**Comment by NikosEfthias** [comment]
the doc just assumes i know magically what the keys are

**Comment by SolitudeSF** [comment]
`<gt>` is `>`
`<lt>` is `<`
`<a>` is alt, but it can't be used by itself.

**Comment by NikosEfthias** [comment]
@SolitudeSF none of the alt keybinding work for me why do you think it can be ?

**Comment by SolitudeSF** [comment]
do they work in other programs?

**Comment by NikosEfthias** [comment]
@SolitudeSF im using mnemonics everywhere possible so yes it works

**Comment by NikosEfthias** [comment]
Now i found that soe of them work some doesnt. For example <a-j> doesnt work but <a-i> seems to be working but thats the only one worked so far among all the alt mappings

**Comment by SolitudeSF** [comment]
which one?

**Comment by NikosEfthias** [comment]
`<a-j>` doesn't work but `<a-i>` works previous time i didn't quote `<>` so they disappeared from the output sorry

**Comment by lenormf** [comment]
Could you please close this now?

**Comment by NikosEfthias** [comment]
@lenormf still i cant figure out why some alt binding does not work but i guess its topic for another bug report

**Comment by lenormf** [comment]
Create another issue with the exact steps you followed, and which version you're using.
