### ISSUE TITLE
disable mouse

### ISSUE THREAD

**Issue by irevoire** [mawww/kakoune#3058]
Hello,
I wanted to disable the mouse, I see no option for mouse in the `set global` menu.
Also I found this issue with the exact same problem #1191
But now the `set global ui_options ncurses_enable_mouse=false` does not exist anymore 😦 

Was this option removed?

**Comment by Screwtapello** [comment]
I just tried the current HEAD (commit f104718) and that command definitely disables mouse support.

`ncurses_enable_mouse` doesn't appear in the tab-completion menu (the blue-and-white text across the bottom of the screen) unless that key already exists in the `ui_options` map, which it doesn't by default.

`ncurses_enable_mouse` *does* appear in the tool-tip that appears after you type `ui_options`, but that tooltip is too large to be shown in a standard 80x25 terminal. It looks like you need at least 28 lines or 132 columns in order for that text to be visible.

**Comment by irevoire** [comment]
Oh ok thanks I was just dumb and didn’t try more when I’ve seen no autocompletion under the ui_options menu.
Thanks a lot for the quick answers!
