### ISSUE TITLE
Cannot bring Kakoune back to foreground

### ISSUE THREAD

**Issue by vivien** [mawww/kakoune#3061]
When Kakoune is triggered by an ncurses application like bower-mail or tig, it cannot be brought back to foreground one it is sent to background with ^Z.

**Comment by lenormf** [comment]
If that's the same thing that happens when Git  spawns the editor, you need two ^Z before you can call `fg`.

Also next time please use the template for reporting issues, one liners take less time to write but generally spawn more questions from people who can help.

**Comment by vivien** [comment]
> If that's the same thing that happens when Git spawns the editor, you need two ^Z before you can call fg.

OK got it. Is it expected though? Why other applications like Vim don't require that?

> Also next time please use the template for reporting issues, one liners take less time to write but generally spawn more questions from people who can help.

Sure, I wrongly thought that it was straight-forward enough for a oneliner.

**Comment by lenormf** [comment]
Explanation from klange and Screwtape on IRC: the editor needs to forward the signal to the entire process group whenever it's being suspended!

My PR should address the issue.

**Comment by vivien** [comment]
Thank you my lords.
