### ISSUE TITLE
Obtain argument with original quotes in shell

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#3063]
It would significantly improve small scripts that pass arguments here and there to evaluate those later, for example:

```sh
define-command eval-buffers -params 1 %{
    evaluate-commands %sh{
        arg="$1"
        eval "set -- $kak_quoted_buflist"
        while [ $# -gt 0 ]; do
            printf "%s\n" "evaluate-commands -buffer $1 $arg"
        done
    }
}

eval-buffers %{ set-option buffer some-opt "some-value" }
```

This will not work, unfortunately, because we need to wrap `$arg` into some quotes:

```sh
printf "%s\n" "evaluate-commands -buffer $buffer %{ $arg }"
```

But this is error prone, since user may call it like so:

```
eval-buffers %& set-option buffer some-opt %@&&}@ &
```

So we need to wrap this in easy escapable characters:

```sh
[ -z "${arg##*&*" ] && arg="$(echo "$arg" | sed "s/&/&&/g")"
printf "%s\n" "evaluate-commands -buffer $buffer %& $arg &"
```

Now we have everything escaped properly. But the thing is - user already specified all delimiter escaping the way it should be, so we just doubling the work here. If we could get the string in it's original state: `%& echo %@&&}@ &` and not in it's evaluated state `echo %@&}@` we could just pass it to the command inside as `$arg` without quoting.

For that I think Kakoune could add `$kak_argN` and `$kak_raw_argN` environment variables. The `$kak_argN` would be a shorthand for `$N`, so `$kak_arg1` is the same as `$1` and `$kak_arg@` is the same as `$@`, and `$kak_raw_arg1` would contain first argument in it's original state. `$kak_argN` can be used to get quoted value as well, e.g. `$kak_quoted_arg1`.

I'm writing a lot of wrapper code in kakscript that executes ordinary kakoune code on certain conditions, like plug.kak does with user configuration and post-update hooks, or kakoune commands that are being run by fzf.kak after we get result from `fzf`. This will make code simpler and probably little bit faster, as we will not need to test strings and escape those with sed or Perl.

**Comment by occivink** [comment]
The easier solution is to not expand `$1` in the shell, but to keep it as `%arg{1}` such that the expansion will be done by the outer `eval`, so: 
```
printf "%s\n" "evaluate-commands -buffer %{$1} %arg{1}"
```
Though the escaping of the buffer name is still problematic in this example

**Comment by mawww** [comment]
As part of the `$kak_quoted_...` change, we have all the necessary infrastructure to require other style of quoting. We could introduce a `$kak_kuoted_...` (obviously wrong name to be bikeshedded) that provides Kakoune style quoting. We could even add json or whatever well known format if we wanted.

I would be ok with adding that (at least the kakoune style quoting), but we need a good name. Discuss !

**Comment by andreyorst** [comment]
> keep it as %arg{1}

such args cannot be shifted, which makes it harder to manipulate.

>I would be ok with adding that (at least the kakoune style quoting), but we need a good name. Discuss !

- kakstring
- raw

**Comment by andreyorst** [comment]
I guess this issue is related https://github.com/mawww/kakoune/issues/2353?

**Comment by occivink** [comment]
In that case, it would be nice to be able to quote multiple times such as `kak_shquoted_kakquoted_buflist` so that we could iterate in shell over arrays and pass back the content cleanly to kakoune
I also suggest `shquoted` and `kakquoted`, although that's a breaking change

**Comment by andreyorst** [comment]
> We could even add json or whatever well known format if we wanted

Also I think that json quoting will be extremely good for plugins that use json formatted communication already.

> I also suggest shquoted and kakquoted, although that's a breaking change

Maybe it's just me, but I really like `raw` for this type of quoting, because we essentially get the untouched data as it was produced by the user. This way we can keep `quoted` as well:

```sh
define-command test -params 1 %{ evaluate-commands %sh{
    printf "%s\n" "echo -debug -- $kak_raw_quoted_arg1" # echo -debug -- '%&&& &&&'
    printf "%s\n" "echo -debug -- $kak_raw_arg1"        # echo -debug -- %&&& &&&
    printf "%s\n" "echo -debug -- $kak_quoted_arg1"     # echo -debug -- '& &'
    printf "%s\n" "echo -debug -- $kak_arg1"            # echo -debug -- & &
}}
test %&&& &&&
```

will display:

    %&&& &&&
    & &
    & &
    & &

in debug buffer.

**Comment by occivink** [comment]
I think exposing the raw string would be a layering violation. Currently if you do any of these
```
custom-command %{abc}
custom-command 'abc'
custom-command abc
```
`custom-command` will see exactly the same argument `abc`, and since the command parsing rules apply to every command it's predictable. If you let a command see the "raw" string, it could use its own parsing rules which could become confusing.
Of course a sane command would probably not do it, but I think it's valuable to have the guarantee that it won't happen.

Exposing a kak-quoted value is sufficient for solving the problem imo

**Comment by danr** [comment]
I think @occivink is on to something. This could happen by accident, a user notices that `$kak_arg1` doesn't contain enough escape symbols and just tries the others randomly. Can we end up in a situation where many of them work but some for the wrong reasons, making scripts start failing in new edge cases?

**Comment by andreyorst** [comment]
I've checked this and it works, so I guess @occivink is right that exposing `kak_quoted` to arguments would solve the issue here.

```sh
define-command test -params 1 %{
    declare-option str arg %arg{1}
    nop %sh{ (
        printf "%s\n" "evaluate-commands $kak_quoted_opt_arg" | kak -p $kak_session
    ) >/dev/null 2>&1 </dev/null & }
}

```
