### ISSUE TITLE
Face attributes on double width characters don't work

### ISSUE THREAD

**Issue by murashitas** [mawww/kakoune#3067]
### Steps
`kak -n` and declare following highlighter:
```
add-highlighter global/ regex あ 0:red+u
```

### Outcome

![outcome](https://user-images.githubusercontent.com/6524359/63680926-a04e1280-c82f-11e9-8ef5-23d6be9abb99.png)

### Expected
![expected](https://user-images.githubusercontent.com/6524359/63680940-a5ab5d00-c82f-11e9-81f4-c29fbc3cb3f7.png)

### Environment
* macOS 10.14.6
* iTerm2 3.3.2
* kakoune: cb26478

**Comment by mawww** [comment]
It seems bold works, but for some reason underline does not, according to a quick debugging session we do set the attribute when pushing the string down to ncurses, so I suspect it is something inside ncurses that disables underlining.

**Comment by murashitas** [comment]
Thanks you for investigation!
But in my environment, it seems other attributes (bold, italic, dim...) don't work too.

![attr](https://user-images.githubusercontent.com/6524359/63908052-aa068e80-ca58-11e9-8abf-d33d2f79e066.png)

I'm not sure it helps you (because I don't know much about ncurses/kakoune impl), app like below works fine for me.

```c
#include <ncurses.h>
#include <locale.h>

int
main(void) {
  setlocale(LC_ALL, "");
  initscr();
  printw("こんにちは Hello\n");
  attron(A_BOLD);
  printw("こんにちは Hello\n");
  attroff(A_BOLD);
  attron(A_UNDERLINE);
  printw("こんにちは Hello\n");
  attroff(A_UNDERLINE);
  getch();
  endwin();
}
```

![attron](https://user-images.githubusercontent.com/6524359/63908869-aa545900-ca5b-11e9-9b07-942363661eaa.png)

**Comment by mawww** [comment]
To make sure this is not a regex matching issue, can you confirm the display issue is still there if you use `.*` as the highlighter regex ?

**Comment by murashitas** [comment]
@mawww Thanks! I confirmed it. It doesn't seem a regex matching issue.

I declared `add-highlighter global/ regex .* 0:+ub`. On the other hand `abcdefghij` and `\n` are bolded/underlined, but `あいうえお` are displayed as normal face.

![attr](https://user-images.githubusercontent.com/6524359/64086953-e34f3f00-cd75-11e9-9f14-20ec7671ee07.png)

**Comment by Screwtapello** [comment]
Using `gnome-terminal` on Linux, I ran:

    add-highlighter global/ regex x[^\n]* 0:+ub

As you can see, both underline and bold work:

![image](https://user-images.githubusercontent.com/1450918/64114862-7cf80a00-cdd1-11e9-9cbe-6af05323cb65.png)

The same is true in `xterm`:

![image](https://user-images.githubusercontent.com/1450918/64114950-bd578800-cdd1-11e9-820c-1ec94cb8493c.png)

...and in `st`:

![image](https://user-images.githubusercontent.com/1450918/64115129-2ccd7780-cdd2-11e9-806e-383a7325cbc3.png)

`urxvt` doesn't seem to handle underlining:

![image](https://user-images.githubusercontent.com/1450918/64115034-fe4f9c80-cdd1-11e9-851a-0e332fb85e21.png)

`qterminal` clearly attempts it, but doesn't get it quite right:

![image](https://user-images.githubusercontent.com/1450918/64115329-a7969280-cdd2-11e9-8356-539995cc668e.png)

Printing escape-sequences directly obviously works, but what about using the `tput` command?

    tput bold; echo あA; tput sgr0
    tput smul; echo あA; tput sgr0

**Comment by murashitas** [comment]
I tried `tput` command. Both underline and bold work!

![tput](https://user-images.githubusercontent.com/6524359/64137170-8913b400-ce31-11e9-812c-c762800e4ea7.png)

**Comment by murashitas** [comment]
Thanks to you, I came to think this isn't an issue for kakoune. Fortunately it isn't so important to underline/bold CJK characters in my usage.

So feel free to close this issue if you think so too.

**Comment by murashitas** [comment]
Oh, I found underline/bold work fine when linking kak with OS default ncurses 5.4. The screenshot below is of 6d085f99.

![ncurses_default](https://user-images.githubusercontent.com/6524359/65094665-daf33700-d9f8-11e9-91c7-0f291d633196.png)

- 6d085f99 with OS default ncurses 5.4: seems ok👌 
- current HEAD (271b1d4)  with OS default ncurses 5.4: broken (like below; maybe related #3087)
- current HEAD (271b1d4)  with [brewed](https://formulae.brew.sh/formula/ncurses) ncurses 6.0: seems ok, but underline/bold don't wok

![broken](https://user-images.githubusercontent.com/6524359/65095112-c7e16680-d9fa-11e9-8d00-902566c08bfc.png)

**Comment by murashitas** [comment]
OK, here is a summary:

|| 6d085f9 | HEAD |
|----|----|----|
|ncurses 5.4 (OS default)| 🙆 / attr:😄  | 🙅‍♂ |
|ncurses 6.1 (Homebrew)| 🙆 / attr:😢  |  🙆 / attr:😢  |

Environment:
- macOS 10.14.6
- iTerm2 3.3.3 (But it results in the same with Terminal.app.)

**Comment by murashitas** [comment]
I've [commented](https://github.com/mawww/kakoune/issues/3067#issuecomment-526009868) like this before:

> I'm not sure it helps you (because I don't know much about ncurses/kakoune impl), app like below works fine for me.

At that time, I used OS default nucurses (`g++ -lncurses main.cc`) 🙇. Now I tested with brewed ncurses, underline/bold don't work on double-width character.

**Comment by mawww** [comment]
Thanks for investigating that in details, I am keen on fixing OSX default ncurses support, I suspect the bold/underline issue is something going on inside ncurses 6.1 as there is no difference Kakoune side on how double/single width character are handled (we just pass them as-is to ncurses).

**Comment by murashitas** [comment]
I've built and tested 9c2d2ad with brewed/bundled ncurses. Both work fine 😎

Although bold/underline issue still exists in brewed ncurses (Yes, it's ncurses issue!), now I can use the bundled one by minor tweaking Makefile. And we'll get rid of ncurses for not only input but also rendering before long  (#2554). So I close this issue.

Thank you for your hard work!

**Comment by mawww** [comment]
You are very welcome, thanks for all those details.
