### ISSUE TITLE
:comment-line inserts wrong character in asciidoc documents

### ISSUE THREAD

**Issue by Invarianz** [mawww/kakoune#3068]
Using `:comment-line` in an asciidoc document does insert a `#` character instead of the correct `//` comment character. 
Also the syntax highlighting for comments in asciidoc documents does not work correctly. Commented lines show the same highlighting as normal text lines.

**Comment by murashitas** [comment]
It seems [rc/tools/comment.kak](https://github.com/mawww/kakoune/blob/master/rc/tools/comment.kak) doesn't set a `comment_line` option for asciidoc. Nor does [rc/filetype/asciidoc.kak](https://github.com/mawww/kakoune/blob/master/rc/filetype/asciidoc.kak) declare a highlighter for comment.

It's a chance for contribution 😋.  Or you may work around it by adding following hooks to `.kakrc`.

```
hook global BufSetOption filetype=asciidoc %{
    set-option buffer comment_line '//'
}

hook global WinSetOption filetype=asciidoc %{
    add-highlighter shared/asciidoc/ regex //[^\n]* 0:comment
}
```
