### ISSUE TITLE
Insert mode: <c-x> l/L completion candidates should ignore indentation

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#3071]
Complete line in insert mode will not list matching candidates because it treats same lines with different indentation levels to be different.
```
// I have this line with indentation
    PRINTLN()

// next I type PRI without any indentation followed by <c-x>l
// sadly but there's no complete candidate, unless I begin the line with same indentation
PRI
```
I reckon lines should be trimmed in order to populate matching candidates, otherwise it's not so useful.

**Comment by Delapouite** [comment]
You're right, this could be improved to work like in vim.

Here the current comparison used to select completion candidates:

```
StringView prefix = buffer[cursor_pos.line].substr(0_byte, cursor_pos.column);
// then in loop over every lines
if (prefix == line.substr(0_byte, prefix.length()))
```

https://github.com/mawww/kakoune/blob/master/src/insert_completer.cc#L356

**Comment by AndrewVos** [comment]
Yeah just came here to report this as a bug: 
![image](https://user-images.githubusercontent.com/363618/99272562-d81fec00-281f-11eb-8edc-156331d851e7.png)
