### ISSUE TITLE
kakrc fails because source command isn't working

### ISSUE THREAD

**Issue by newmankyle** [mawww/kakoune#3077]
### Summary
I'm new to kakoune and I'm having some trouble debugging this. For some reason, kakoune's ':source' command isn't working. 
### Steps 
I'm using WSL (Ubuntu), and using Fish as my shell.
I've created a kakrc file in ~/.config/kak/kakrc with a single line.

I've confirmed that I get the same output using Fish and Bash.
I've confirmed that I get the same output sourcing kakoune via apt-get (v2016.12.20.1) and via git (master).
I've confirmed that uninstalling and reinstalling doesn't fix the problem (no errors on install either).
Just in case kakoune relies on the shell builtin, I've confirmed that the source builtin works in both Fish and Bash.

### Outcome 
/usr/share/kak/kakrc throws an error when {userconfig}/kakrc exists

calling ':source <userconfig>/kakrc' results in:  
    1:1: 'source' // : no such command
### Expected 
Unfortunately, this prevents /usr/share/kak/kakrc from sourcing my {userconfig}/kakrc file...

**Comment by Screwtapello** [comment]
Kakoune's `source` command is unrelated to the commands provided by `fish` or `bash`.

If you move your `kakrc` aside and create a completely empty file:

    printf "" > ~/.config/kak/kakrc

...does Kakoune still have the same error?

When you say you "created" a `kakrc` file, did you create it with Kakoune, or some other editor like Windows Notepad?

**Comment by newmankyle** [comment]
I created the kakrc file via ```touch kakrc```, then edited the file using kakoune.

Actually, it seems to be working today. Maybe rebooting the computer did something reinstalling/rebooting WSL didn't?
