### ISSUE TITLE
Scroll to bottom after format

### ISSUE THREAD

**Issue by bburdette** [mawww/kakoune#3079]
### Steps

0) be using Kakoune v2019.01.20

1) install elm-format.
I'm using elm-format 0.8.1.

2) Add this to kakrc
```
# elm format-on-write
hook global WinSetOption filetype=elm %{
  set window formatcmd 'elm-format --stdin'

  hook buffer BufWritePre .* %{format}
}
```

3) format the file with :format, or by saving.

### Outcome 
With a sufficiently large file, the editor scrolls to the bottom after the format.  This file triggers the problem:
https://github.com/mdgriffith/elm-ui/blob/1.1.5/src/Internal/Model.elm

This file is small enough to format without the problem happening:
https://github.com/mdgriffith/elm-ui/blob/1.1.5/src/Element.elm

### Expected
I'd expect the scroll position of the document to stay the same after formatting.

**Comment by Screwtapello** [comment]
See #2037.

**Comment by Screwtapello** [comment]
(In particular, that bug was marked fixed on 2019-01-22, just after your 2019-01-20 version of Kakoune was released. The fix is in the 2019-07-01 version)

**Comment by bburdette** [comment]
Thanks.  I got 2019-07-01 installed and now it works.
