### ISSUE TITLE
toggle case ~ broken with kak -n

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#3084]
Run `kak -n`  press `~` on any character in normal mode.
It toggles lower case to upper, but not the other way.

Surprisingly, it works correctly when run without `-n` with my config, however if remap to something else like `map global normal = ~`, new mapping doesn't toggle as well.

I use `Kakoune v2019.07.01-98-g64511bac` on macOS Mojave.

**Comment by occivink** [comment]
`~` is not supposed to be a toggle, it's switch to upper case. `` ` `` is switch to lower case

**Comment by vbauerster** [comment]
ok, I see now.

**Comment by mawww** [comment]
`` <a-`> `` is the toggle case command.
