### ISSUE TITLE
Mac OS Alt Key

### ISSUE THREAD

**Issue by ovidius72** [mawww/kakoune#3086]
I'm trying to use kakoune but I'm unable to use commands mapped with the ALT key.
Everything which uses ALT, <a-j>, <a-f> and so on doesn't work. I see no effect. 
Tried with iTem2 and Kitty terminal with the same result. Is there any known issue with the Mac ?
Thanks

**Comment by Screwtapello** [comment]
I don't know about iTerm2 and Kitty, but traditionally on macOS the option/alt key is used for typing special characters, and so it isn't available for use with shortcuts by default. The standard macOS Terminal application has an option that allows Option to be used with shortcuts, I assume other macOS terminals do too.

**Comment by eraserhd** [comment]
Most Mac terminal emulators have an option for it, with varying degrees of completeness.  If your Mac terminal emulator doesn't support it, or doesn't support it well enough (my emulator, Alacritty, has some problems), it's possible to use Karbiner-Elements to simulate pressing "Esc" before each key when Option is held.

**Comment by ovidius72** [comment]
Thanks everyone. I found this option available in the kitty terminal but not i iTerm2.
`macos_option_as_alt yes`

**Comment by murashitas** [comment]
In case of iTerm2, make sure of "Profiles" -> "Keys"-> "Left/Right Option Key: Esc+" being checked.
![iterm_option](https://user-images.githubusercontent.com/6524359/65026540-ba34ce00-d973-11e9-95f7-b33d51c44ddb.png)

**Comment by ovidius72** [comment]
@murashitas Thanks.

**Comment by nstrappazzonc** [comment]
With this config found
![image](https://user-images.githubusercontent.com/43709338/103694780-d1019880-4f9b-11eb-8c48-42300168fcfc.png)
