### ISSUE TITLE
Highlight special characters

### ISSUE THREAD

**Issue by sebastien** [mawww/kakoune#309]
Vim allows to display invisible characters (tabs, leading spaces, EOLs, etc) using `listchars` as illustrated below.

```
set       list listchars=tab:»-,trail:·,eol:¬,extends:¬,precedes:¬
```

It would be great to allow kakoune to style these characters.

**Comment by mawww** [comment]
Hello,

the show_whitespaces highlighter provides that (although not configurable like vim does).

**Comment by sebastien** [comment]
Oh, I didn't see that. Any tips on how to use it? I don't see it listed in `:face`

**Comment by mawww** [comment]
to add it manually: `addhl show_whitespaces` will add it to the current window. if you want to enable it for every window, you can add a hook:

```
hook global WinCreate .* 'addhl show_whitespaces'
```

**Comment by jnturton** [comment]
Note for others users that land on this thread: I had to use `addhl window/ show_whitespaces` to add the highlighter to the current window.

**Comment by familyfriendlymikey** [comment]
Thanks jnturton.

Another note for others, adding this line to my kakrc worked for me:

```
hook global WinCreate .* 'addhl window/ show-whitespaces'
```

Note that it's a a `-` and not a `_`.
