### ISSUE TITLE
Marks do not work when `@` is in the buffer path

### ISSUE THREAD

**Issue by BestFriendChris** [mawww/kakoune#3091]
### Steps 
```sh
$ mkdir /tmp/@foo
$ echo "quux\nbaz" > /tmp/@foo/bar
$ kak /tmp/@foo/bar -e 'exec eZjz'
```

### Outcome 
The following error message:
```
1.1: 'exec' expected <buffer>@<timestamp>@main_index
```

### Expected 
The word `quux` selected and the following info message:
```
Restored 1 selections from register '^'
```

### Analysis
The `^` register has the following content:
```
/tmp/@foo/bar@1@0
```
which is being split into 4 sections instead of the expected 3 at [read_selections_from_register()](https://github.com/mawww/kakoune/blob/271b1d4f2ff85668be6e1228b3a3fc957a740adf/src/normal.cc#L1761-L1791)

### Proposed Fix
I think the best solution would be to only split on the last 2 `@` signs since the `timestamp` and `main_index` portions are defined internally to be integers.

Alternatively, when saving and restoring a mark, any `@` characters in the buffer name could be escaped in some way.

**Comment by Delapouite** [comment]
@BestFriendChris can you check if your problem is resolved on master and close this issue if that's the case? thanks

**Comment by mawww** [comment]
Should be fixed, closing, re-open if still an issue.
