### ISSUE TITLE
Access a specific selection's contents

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#3092]
I'm trying to write a small plugin, and I'm wondering:

How do I access the contents of a specific selection? I see that `%reg{#}` gives me the index of each selection, and that `%reg{.}` gives me the content of all selections all at once. How do I access the contents of just the first selection. Is there a special separating char in between items of `%reg{.}`? The selections will likely contain spaces & newlines, which is why I don't think there is an easy way for me to parse `%reg{.}`'s output to get what I want.

Is there a specific register for this?

**Comment by Screwtapello** [comment]
`%val{selections}` expands to a list of the contents of the current selections; `%val{selection}` (singular) expands to the content of just the main selection. You can select which is the main selection with `execute-keys '('` and `execute-keys ')'`

**Comment by enricozb** [comment]
Thank you, this is what I needed.
