### ISSUE TITLE
Better docs for registers

### ISSUE THREAD

**Issue by ZakharEl** [mawww/kakoune#3093]
Registers that are set using the normal mode key sequence "?Z where ? is the register in question have the output with echo %reg{?} as %val{buffile}@%val{timestamp}@?? %val{selection_desc}. Example: /home/zachary/.config/kak/kakrc@0@0 1.4,3.14. What is the number immediately after the last @ symbol?

**Comment by Delapouite** [comment]
https://github.com/mawww/kakoune/blob/master/src/normal.cc#L1905
https://github.com/mawww/kakoune/blob/master/src/normal.cc#L1771

It appears to be the index of the main selection.

**Comment by ZakharEl** [comment]
Thanks! Though as a suggestion this should probably be in the register docs (:doc registers) somewhere. I really like this editor it seems to have so much potential and power than vim and is smaller in size just want help make it better in some way.

**Comment by Delapouite** [comment]
@ZakharEl the PR https://github.com/mawww/kakoune/pull/3245 seems to address your problem. If that's indeed the case, can you close this issue please ?

**Comment by ZakharEl** [comment]
Thanks!
