### ISSUE TITLE
Prevent replacement of key literals in kakrc

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#3094]
Sorry if this is a dumb question, but I can't seem to understand how key "literals" work in `kakrc`. 

I can manually type while in a buffer `:execute-keys '<a-w>'`, and here i'm not pressing alt-w, i'm literally typing `<` then `a` then `-`, etc. I want this behavior from a keypress. So I tried
```
map global normal I %{:execute-keys '<a-w>'}
```
However, this is "typed" as if someone pressed Alt+w when typing in the command. So I just get `:execute-keys ''` in the prompt. How do I get the behavior that I described above, while typing this in manually?

**Comment by Screwtapello** [comment]
If you want to actually type `<` instead of beginning an extended key name, say `<lt>`.

**Comment by enricozb** [comment]
Wow. Thank you.
