### ISSUE TITLE
Pipfile types not recognised by default

### ISSUE THREAD

**Issue by clar-cmp** [mawww/kakoune#3096]
`Pipfile`s should be recognised as TOML and `Pipfile.lock`s should be recognised as JSON.

**Comment by lenormf** [comment]
What software uses this file?

**Comment by Delapouite** [comment]
python: https://github.com/pypa/pipfile

**Comment by lenormf** [comment]
Thanks for that.

Since those files are not endorsed officially, it's probably best to wait on builtin support in the editor for a little longer.

The following lines (to append to the `kakrc` file) should highlight the files properly:

```
hook global BufCreate (.*/)?Pipfile %{
    set-option buffer filetype toml
}

hook global BufCreate (.*/)?Pipfile.lock %{
    set-option buffer filetype json
}
```

**Comment by clar-cmp** [comment]
Fair enough.
