### ISSUE TITLE
(ncurses_) status_on_top and assistant are incompatible

### ISSUE THREAD

**Issue by tonkou-roi** [mawww/kakoune#3098]
`ncurses_status_on_top` set to 'yes'/'true' will always set `ncurses_assistant` to 'clippy'.
`ncurses_assistant`, even if assigned 'clippy', will always set `ncurses_status_on_top` to 'no'/'false'. These settings should not clash.

**Comment by danr** [comment]
Either use the `-add` flag to `ui_options` or set both options at once. If you clear the `ncurses_assintant` in the `ui_options` str-str map kakoune will reset the `ncurses_assistant` to `clippy`.

    set global ui_options ncurses_assistant=clippy ncurses_status_on_top=true

**Comment by tonkou-roi** [comment]
Thank you. I tried add but it had not worked, but your line did worked.
