### ISSUE TITLE
Haskell functions lose syntax highlighting after single quote in name

### ISSUE THREAD

**Issue by evanrelf** [mawww/kakoune#3106]
### Steps 

Open Haskell file containing a function with a single quote in its name.

```haskell
-- Test.hs

foo :: Int -> Bool
foo _ = True

foo' :: Int -> Bool
foo' _ = False
```
```shell
$ kak Test.hs
```

### Outcome 

The name of the `foo` function is highlighted the correct color in it's function signature, while the name of the `foo'` function is not highlighted.

![image](https://user-images.githubusercontent.com/887196/65470645-e7c0c200-de20-11e9-9a4d-67e25177b545.png)

### Expected 

The names of the functions in their function signatures are both highlighted the same color.

**Comment by evanrelf** [comment]
Looks like function names also lose highlighting when indented (e.g. in a `let` binding):

```haskell
foo :: Int -> Bool
foo x =
  let
    -- The text `isTwo` in the line below
    isTwo :: Int -> Bool
    isTwo 2 = True
    isTwo _ = False
  in
    isTwo x
```

**Comment by lenormf** [comment]
Why close the issue?

**Comment by evanrelf** [comment]
I realized I was talking about a bug in my own extra highlighters for Haskell 🤦‍♂ I have since fixed the bug, if anyone is interested in richer highlighting for Haskell:

```kakoune
# Highlight function name in type signatures
add-highlighter shared/haskell/code/ regex ^\h*(?:(?:where|let|default)\h+)?([_a-z]['\w]*)\s+::\s 1:meta
# Highlight function name in function definitions
# add-highlighter shared/haskell/code/ regex ^\h*(?:(?:where|let|default)\h+)?([_a-z]['\w]*)(\h+['\w\[\]\(\),:\{\}\.]+)*\h+=\s 1:meta
# Highlight curly braces, square brackets, and commas
add-highlighter shared/haskell/code/ regex [\{\}\[\],] 0:operator
# Highlight quasiquotes
add-highlighter shared/haskell/quasiquote region \[\b[\w]['\w]*\| \|\] fill string
```

**Comment by lenormf** [comment]
Sounds like these should be built-in (except for the braces/brackets/commas? maybe?), could you please create a new PR?

**Comment by evanrelf** [comment]
Sure, I can make a PR. My only hesitation is that I haven't tested the regexes on a lot of different Haskell code, so I'm not sure they're perfect.

**Comment by danr** [comment]
```
# Highlight function name in function definitions
add-highlighter shared/haskell/code/ regex ^\h*(?:(?:where|let|default)\h+)?([_a-z]['\w]*)(\h+['\w\[\]\(\),:\{\}\.]+)*\h+=\s 1:meta
```
This is very ambitious! You're missing (at least) infix constructors `f (x :+: y) = e x y`

**Comment by evanrelf** [comment]
@danr You're right! That's what I mean when I say I haven't tested it 🙂

There's also the question of whether it should highlight all function names in definitions, including those in `let` and `where` clauses (like it does now), or only top-level function names?

**Comment by lenormf** [comment]
If you have a regex that doesn't spawn false positives, and the buffer isn't too cluttered visually, throw it in!

**Comment by evanrelf** [comment]
https://github.com/mawww/kakoune/pull/3114
