### ISSUE TITLE
coredump on exec inside InsertEnd

### ISSUE THREAD

**Issue by d3m1gd** [mawww/kakoune#311]
The only kak rc file in directory $HOME/.config/kak/autoload, named bug.kak with contents:

    hook global WinCreate .*\.c %{
    	hook buffer InsertEnd .* %{ exec <esc>wd }
    }

No symlink to any other file or dir.

Steps to cause crash:

    kak some.c
    i<esc>i

Sometimes crash happens directly after `<esc>`, sometimes editor lives a bit longer.

**Comment by d3m1gd** [comment]
some more experimenting revealed, that combinations of `exec` with `<esc>` are quite buggy

**Comment by d3m1gd** [comment]
I notices weird behaviour of exec in context of `InsertEnd` in general. Without `-draft` the keys are replayed in insert mode, and trying to leave with `<esc>` causes all sorts of crashes. With `-draft` the keys are replayed in normal mode, as expected.

**Comment by mawww** [comment]
-draft creates a new context, which always starts in normal mode, whereas no -draft use the current context (and the current mode), so the behaviour is expected.

Whats triggering the crash here is that <esc> triggers leaving insert again, which triggers the InsertEnd hook again... Not sure what the correct fix would be, could be leaving InsertMode before triggering InsertEnd, we probably want to prevent recursive hook calling (a hook triggering itself), although detecting problemetic cases might not be easy.

**Comment by d3m1gd** [comment]
I can propose disabling recursive hooks in commands, that are executed in hooks, if it makes sense.

    exec -no-hooks %{<esc>}

gives the following

    assert failed "m_mode_stack.back() == mode" at input_handler.cc:1200
    [Debug Infos]
    pid: 15549
    callstack:
    kak(_ZN7Kakoune9BacktraceC1Ev+0x2b) [0x7cea71]
    kak(_ZN7Kakoune16on_assert_failedEPKc+0x24) [0x7b6a2d]
    kak(_ZN7Kakoune12InputHandler8pop_modeEPNS_9InputModeE+0x4a) [0x79fd68]
    kak(_ZN7Kakoune9InputMode8pop_modeERNS0_9KeepAliveE+0x46) [0x7a0fb8]
    kak(_ZN7Kakoune10InputModes6Insert6on_keyENS_3KeyENS_9InputMode9KeepAliveE+0x281) [0x7a915b]
    kak(_ZN7Kakoune9InputMode10handle_keyENS_3KeyE+0x3f) [0x7a0ecb]
    kak(_ZN7Kakoune12InputHandler10handle_keyENS_3KeyE+0x17c) [0x7a0680]
    kak(_ZN7Kakoune6Client22handle_available_inputENS_9EventModeE+0x155) [0x7f76cf]
    kak() [0x7f1d8d]
    kak() [0x7f31fc]
    kak(_ZNKSt8functionIFvN7Kakoune9EventModeEEEclES1_+0x48) [0x7bb464]
    kak() [0x7c2e77]
    kak() [0x7ca3dc]
    kak(_ZNKSt8functionIFvRN7Kakoune9FDWatcherENS0_9EventModeEEEclES2_S3_+0x60) [0x7d053a]
    kak(_ZN7Kakoune9FDWatcher3runENS_9EventModeE+0x29) [0x7cf0db]
    kak(_ZN7Kakoune12EventManager18handle_next_eventsENS_9EventModeEP10__sigset_t+0x575) [0x7cf9b5]
    '
    pid: 15562
    callstack:
    kak(_ZN7Kakoune9BacktraceC1Ev+0x2b) [0x7cea71]
    kak(_ZN7Kakoune16on_assert_failedEPKc+0x24) [0x7b6a2d]
    kak(main+0x1152) [0x6a7cd5]
    /usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f9224dfb790]
    kak(_start+0x29) [0x6a2129]
    
    sh: xmessage: command not found
    terminate called after throwing an instance of 'Kakoune::assert_failed'
