### ISSUE TITLE
MacOS alt/option

### ISSUE THREAD

**Issue by shterrett** [mawww/kakoune#3123]
I assume I'm missing something obvious, but it could also be some weird config thing I've accidentally set. Anyway -- I'm having trouble with all of the `<a-...>` commands. I'm assuming that the `<a-(some key)>` means press `some key` while holding `alt`, which is also `option`.

For Instance
### Steps 

Inside a set of parentheses
```
<a-a>
)
```

### Outcome 
The (single character cursor) selection is unchanged.

### Expected 
I expect the entire parenthetical expression to be selected

### Notes

When I use `]` or `[` etc and then `)` to select to the end or beginning of a parenthetical block, it works as expected. 

I'm currently using iTerm2 v3.3.5beta2 on macOS Mojave 10.14.6. I'm not aware of having customized the binding for `option`, and System Preferences says the `option` key sends `option`, which I understand to be the same keystroke as `alt`.

**Comment by Screwtapello** [comment]
Is this the macOS option-types-special-characters thing? [From the wiki](https://github.com/mawww/kakoune/wiki/Normal-mode-commands):

> For iTerm2, you can set the option key as meta by going to iTerm > Preferences > Profile > (Active Profile) > Keys and you can see at the bottom of the pane there are radio choices for the options keys. Use +Esc to properly bind as the Alt-key.

Not quite sure it's on the "Normal mode commands" page instead of a special macOS page (an equivalent for the [Windows tips](https://github.com/mawww/kakoune/wiki/Windows-tips) page), but oh well.

**Comment by shterrett** [comment]
@Screwtapello That was indeed the problem. Thanks!
