### ISSUE TITLE
Let the user teach words that the completion engine must know when editing certain buffers

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#313]
Hi,

I would like kak to be able to give me suggestions when I open a new buffer and type words in it that have an obvious completed equivalent.

Example: when opening a *.c buffer, I want kak to suggest '#include' if I type '#incl' (or any substring of '#include' big enough to generate suggestions), even when I haven't typed '#include' before.

I quickly mentioned the idea on IRC, and the temporary solution that d3m1gd came up with is to write the words I want to be completed into in *scratch* when opening a target buffer (and eventually pipe that buffer to `sort -u | uniq`, to avoid dupes).

I don't have any suggestions as to what the regular (non hacky) kakrc command should look like, but I would like to be able to select certain words to be completed into only for certain buffer types ('#pragma' only in .h files, '#include' in both .c and .h files etc). There could also be language-dependant defaults included in the rc .kak files.

**Comment by d3m1gd** [comment]
I support this idea.

Also, just as a probable pointer: we already have a set of keywords in language highlighters, maybe those could help

**Comment by mawww** [comment]
This is now supported through the `static_words` option, however it does not solve the given example because `#include` is not a word (due to the `#`) and changing the definition of a word just for that would be tricky.
