### ISSUE TITLE
Extra selection after undoing automatic un-indent of a tab

### ISSUE THREAD

**Issue by krobelus** [mawww/kakoune#3130]
### Steps
```sh
printf '\tfi\n' | kak -e 'set global filetype sh'
```
Then type `o` to open a new line, `<esc>` and `u` to undo the edit.

### Outcome
There are two selections, one on each line.

### Expected
There should be only one selection, probably on the second line

**Comment by eraserhd** [comment]
Duplicate of #753 and #1184 (which affect me frequently).
