### ISSUE TITLE
way to track `pwd` change?

### ISSUE THREAD

**Issue by andreyorst** [mawww/kakoune#3135]
Is there a way to monitor change of `pwd` via `cd` command?

If there's none, a hook like `WorkingDirectoryChanged` would be nice to have.
More simple solution would be to store `pwd` in some option and `hook` on its changes. This may require to alter how `cd` works.

**Comment by Delapouite** [comment]
Related to https://github.com/mawww/kakoune/issues/2091

**Comment by tmccombs** [comment]
It is possible to get the working directory using:

```
:echo %sh{pwd}
```

**Comment by andreyorst** [comment]
it is not the problem to obtain current working directory, but to track
when it was changed and automatically perform some action before or after
the change

чт, 4 июн. 2020 г., 08:24 Thayne McCombs <notifications@github.com>:

**Comment by andreyorst** [comment]
closing in favow of #2091

**Comment by Delapouite** [comment]
For people coming from a search engine, the `EnterDirectory` hook now exists
https://github.com/mawww/kakoune/blob/master/doc/pages/hooks.asciidoc#:~:text=EnterDirectory
