### ISSUE TITLE
Redraw artifacts in Alacritty when searching/selecting

### ISSUE THREAD

**Issue by jwhett** [mawww/kakoune#3144]
## Steps 

![example text](https://user-images.githubusercontent.com/4229885/66157307-843d4e00-e5f1-11e9-8326-b34749160ab5.png)

1. on Fedora 30
1. open [Alacritty](https://github.com/jwilm/alacritty/releases/tag/v0.3.3); ensure `alacritty` terminfo
1. open file with `kak`
1. begin a search
1. accept the search
1. scroll through results with `n`; optionally extending selection with `N`
1. observe artifacts left behind on some lines you pass

### Outcome 

Scrolling through search results with `n` leaves behind strange artifacts. Also, the command menu has some small artifacts such as when typing `:q`.

Examples of bug:

![first example](https://user-images.githubusercontent.com/4229885/66155783-628e9780-e5ee-11e9-95fa-b1ce0f5605c8.png)

![second example](https://user-images.githubusercontent.com/4229885/66156020-d7fa6800-e5ee-11e9-8f8b-9e0eed64578c.png)

### Expected 

Scrolling through search results with `n` should not leave behind redraw artifacts.

### Additional Info

I first opened an [issue with Alacritty](https://github.com/jwilm/alacritty/issues/2842) after I pulled updates and rebuilt Kakoune and Alacritty. I admittedly didn't do much research or problem determination at the time. I also ran normal system updates through `dnf` so it's possible something else could've changed in the environment unexpectedly. 

* I cannot replicate this issue with `gnome-terminal`.
* This bug does not appear when running in `tmux` with `screen-256colo` as the terminfo.

I've done a bisect while running the [latest Alacritty release](https://github.com/jwilm/alacritty/releases/tag/v0.3.3) and I think I found the [commit](1d9a9bc3087f45989fec3d36c800a6a23472d6c6):

```
1d9a9bc3087f45989fec3d36c800a6a23472d6c6 is the first bad commit
commit 1d9a9bc3087f45989fec3d36c800a6a23472d6c6
Author: Maxime Coste <mawww@kakoune.org>
Date:   Thu Sep 26 20:14:08 2019 +1000

    Remove unneeded NCursesUI::Window::mark_dirty and redraws

    A bug in client.cc was always forcing full redraws of the windows,
    leading to much more terminal output traffic than necessary.

:040000 040000 969d93f4732cdeb4ed450eec9575a3f943b05471 2297875129cd185922eba2a4959750680b27d8fa M	src
```
[Bisect log](https://github.com/mawww/kakoune/files/3744068/bisect-log.txt) just in case.

Please let me know what I may do to provide more accurate information.

Thanks,
Josh

**Comment by Screwtapello** [comment]
Is the `alacritty` terminfo entry written by alacritty's maintainer, or by ncurses' maintainer? If it's written by alacritty's maintainer, it wouldn't surprise me that there's some historical quirk of the way ncurses uses terminfo capabilities that the alacritty terminfo entry doesn't account for.

**Comment by whereswaldon** [comment]
Seems like the `ncurses` maintainer has rewritten the `alacritty` terminfo. It's available [here](https://invisible-island.net/ncurses/terminfo.src-entries.html#tic-alacritty). Perhaps test with that?

**Comment by jwhett** [comment]
Thanks, for finding that @whereswaldon.

**Comment by jwhett** [comment]
I'll give it a shot with that terminfo

**Comment by jwhett** [comment]
Yea, the terminfo from ncurses solves the problem. Good find, @whereswaldon. I'll take this back to Alacritty in the issue I mentioned above.

**Comment by jwhett** [comment]
x-posting seems to be fixed. could've been a combination of things, might have been my alacritty config: https://github.com/jwilm/alacritty/issues/2842

Closing this issue.
