### ISSUE TITLE
t/T is not repeatable with <a-.>

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#3148]
Family of till verb (`t`, `<a-t>`, `T`, `<a-T>`) is not repeatable with `<a-.>`. I'm not sure if it is bug or design feature, but in my opinion it should be repeatable as it is with `f` family verb.

**Comment by alexherbo2** [comment]
If the cursor is already before the target character we could move next, but it will make context dependent.  The keyboard is already crowded, so not sure if it’s possible to provide a smart and non smart version.

**Comment by lenormf** [comment]
Dupe #2824

**Comment by Delapouite** [comment]
Note: same behavior with vim.

Pressing several times `tx` `tx` `tx` will stop the cursor just before the next `x` char on the line and won't move further, even if there are more `x` chars after.

@vbauerster do you mind closing this issue? Thanks

**Comment by vbauerster** [comment]
I don't.
