### ISSUE TITLE
The `wrap` highlighter should have its own dedicated face marker

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3149]
Issue reported originally by @vbauerster in #3146.

### Steps 

Add the `wrap` highlighter with a marker, open a buffer that contains a wrapped line.

### Outcome 

The marker is highlighted with the `StatusLineInfo` face, which seems inappropriate.

### Expected 

The marker should have its own face, similar to the way whitespace are highlighted with the `Whitespace` face by the `show-whitespaces` highlighter.

**Comment by vbauerster** [comment]
There is one more ui component sharing its face with `StatusLineInfo`, which is recently used command in the command prompt. It is yellow on the screenshot and looks confusing. It would be nice to have dedicated face for this component.
[![Screenshot-2019-10-21-at-22-10-19.png](https://i.postimg.cc/3wDdBJ3R/Screenshot-2019-10-21-at-22-10-19.png)](https://postimg.cc/Tyfd2xLM)

**Comment by lenormf** [comment]
Closed by 0f292d343b17a404f560308d8ac6bf6af52add3a.
