### ISSUE TITLE
Add a why-kakoune.asciidoc document

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3165]
Add [Why Kakoune] to [documents].

[Why Kakoune]: https://kakoune.org/why-kakoune/why-kakoune.html
[Documents]: https://github.com/mawww/kakoune/tree/master/doc

**Comment by lenormf** [comment]
Why? This isn't documentation, it's an opiniated blog article piece.

**Comment by alexherbo2** [comment]
Added in the [`gh-pages`] branch.

[`gh-pages`]: https://github.com/mawww/kakoune/tree/gh-pages

https://github.com/mawww/kakoune/blob/gh-pages/why-kakoune/why-kakoune.asciidoc
