### ISSUE TITLE
Some literals with escape sequences cannot be parsed inside a character class

### ISSUE THREAD

**Issue by caksoylar** [mawww/kakoune#3172]
It looks like there is an issue with parsing certain literals that are escape sequences when used inside a character class. I confirmed below fails with `\cX`, `\xXX` and `\uXXXX` sequences, but works with fixed ones like `\n` and `\t`.

### Steps and outcome
- Open the scratch buffer
- Search for `\x61` with `/\x61<ret>`, observe it matches "a" characters
- Similarly search for `[\x61]`, observe error `regex parse error: unknown character class escape 'x' at '[\x<<<HERE>>>61]'`

These sequences in character classes are very useful when working with unicode files to search for ranges, e.g. `[^\x00-\x7F]` matches any non-ASCII character. Would be nice if they were supported.

**Comment by eraserhd** [comment]
I remember looking at this a while back when it bit me, but I guess I didn't fix it.  This is legal according to ECMAScript 6.  http://www.ecma-international.org/ecma-262/6.0/#sec-classescape

**Comment by caksoylar** [comment]
Works as expected, thanks @mawww ! `[\cX]` is not covered but I am just noting it for completeness' sake; others cover my actual uses cases.
