### ISSUE TITLE
User modes corrupt ModeChange parameter

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#3192]
Now that #2569 (User modes should be pushed to the mode stack) is fixed, I wanted to try out the new system. Stupidly, I didn't put reproduction instructions in the original issue, so I had to try and recreate them.

### Steps 

1. Launch Kakoune with a user mode, and a hook that logs mode changes:

        kak -n -e "
            declare-user-mode foo
            map global foo x ': echo blort<ret>'
            map global normal = ': enter-user-mode -lock foo<ret>'
            hook global ModeChange .* 'echo -debug ModeChange: %val{hook_param}'
        "

1. Hit <kbd>=</kbd> to enter the "foo" user-mode
    - Note the title of the info box is "foo (lock)"
1. Hit <kbd>x</kbd> to echo a message to the status line

### Outcome 

- Title of the info box becomes "Mod (lock)"
- When re-entering the user-mode (because it's locked), the `*debug*` buffer logs:

        ModeChange: pop:next-key[user:Mod]:normal

### Expected 

- Title of the info box stays "foo (lock)"
- The `*debug*` buffer should log the proper name of the mode::

        ModeChange: push:normal:next-key[user:foo]

### Notes

- Things work as expected without the ModeChange hook.
- If I change the hook name from "foo" to "abcdefghijk", then after pressing <kbd>x</kbd> the info box title changes to "ModeChange: (lock)"
- If I change the hook name to "abcdefghijklmnopqrstuvwyxz", then after pressing <kbd>x</kbd> the info box title changes to ridiculous things, like "M-@M-;RM-."

**Comment by mawww** [comment]
First thing I see here is that my choice of format is bad as `user:<blah>` makes it unnecessarily hard to split on `:` to get mode change information. Will switch to something else (maybe `user.<blah>`).
