### ISSUE TITLE
The test suite randomly freezes

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3196]
Hi,

Ever since `e888f434` was merged, the test suite has been randomly freezing, both on Travis (our C.I.) and the [Fedora COPRS](https://copr.fedorainfracloud.org/coprs/jkonecny/kakoune/builds/).

Now and then, a machine on Travis would fail, I've always dismissed those errors as being Travis-related (we're used to that by now), but there might be more to it.

HTH.

**Comment by jkonecny12** [comment]
Thanks for opening this. From now on I'll start cancelling my daily builds because maintainer of COPR asked me to do that. If you need to test fix for these changes just give me repository and I'll run my mega builds a few times to test this race condition.

**Comment by jkonecny12** [comment]
It may not be probably the problematic one but between the last stable build and failed build is also this commit 2b1ca433 just in case.
