### ISSUE TITLE
Highlight 'FIXME', 'TODO' or 'XXX' comments in source code files

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#320]
Hi,

I'd like kak to highlight comments that are prefixed with a few keywords, to catch my attention on certain parts of the code.

Example:
```
// FIXME: fix some things
// TODO: implement something
// XXX: some remark
```

Highlighting the prefix rather than the entire comment would be better visibility wise IMO.

**Comment by jkonecny12** [comment]
It will be better to change existing highlithers or add new one for comments?

**Comment by mawww** [comment]
A new .kak could be written, that creates a name highlighter group, and adds them to windows. Should be simple enough.

**Comment by jkonecny12** [comment]
I like that idea.

**Comment by lenormf** [comment]
@mawww You need to be able to target specifically comments, and not only the words, otherwise you'll end up highlighting those keywords anywhere in the buffer (in strings for example). Don't you have to add highlighters in all the language kak files, to be able to know how a comment is written in a given language ? A new seperate file would only match the words no matter the context in which they were written, am I right ?

**Comment by alexherbo2** [comment]
Actually this won’t happen, because highlighters are hierarchical.

That means, you can create your GTD group highlighter apart

```
addhl -group / group gtd
```

```
addhl -group /gtd regex todo 0:magenta
addhl -group /gtd regex fixme 0:yellow
addhl -group /gtd regex xxx 0:blue
```

and tap in CPP comments for example

```
addhl -group /cpp/comment ref gtd
```

**Comment by lenormf** [comment]
Oh I see, thanks for the clarification !

**Comment by lenormf** [comment]
As discussed on IRC, I decided to close this issue, and add the code snippet I posted previously to the [appropriate wiki entry](https://github.com/mawww/kakoune/wiki/How-To#highlight-fixmetodoxxx-keywords-in-comments).

Cheers.
