### ISSUE TITLE
Double-wide character handling

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#3200]
### Steps

Editing `⓵⓵⓵`

### Outcome

![Screen Shot 2019-11-12 at 12 02 32 PM](https://user-images.githubusercontent.com/147284/68693027-870e5580-0544-11ea-99cd-d24a3771b98f.png)

### Expected

The characters don't overlap.

It seems like this affects expansions like cursor_display_column and the new selections_display_column_desc.

**Comment by mawww** [comment]
This is not really a kakoune issue, ⓵ seems to be of different width depending on the font, Kakoune asks for the witdth using `wcwidth` which knows nothing about the font you are using.

Here `😄😊😉😍😘😚😜😝😳😁😣😢😂😭😪😥😰😩😰🦄` ar all double width and correctly handled in kakoune.

**Comment by Screwtapello** [comment]
[Apparently](https://github.com/komagata/eastasianwidth/blob/master/eastasianwidth.js#L207), that Unicode character has an `East_Asian_Width` property of "A" for "Ambiguous" - it's usually 1 cell in Western locales and 2 cells in East Asian locales. Most terminal emulators have an option to set whether ambiguous characters should be drawn as 1 cell or 2 (but of course it doesn't change what `wcwidth()` returns, so it usually just makes things *differently* messy).

**Comment by mawww** [comment]
Yeah, and we could be displayed in different terminal emulators at the same time, using different display width...

I dont think there is much we can do Kakoune side for those.

**Comment by eraserhd** [comment]
Oh boy :(
