### ISSUE TITLE
selections_display_column_desc, select -display-column don't account for tab width

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#3201]
### Steps

Edit `xyz123456` following a literal tab.  Place the selection on `x`.
Run `:echo %val{cursor_display_column} %val{selections_display_column_desc}<ret>`.
Then `:select -display-column 1.9,1.9<ret>`

### Outcome 

Echos `9 1.2,1.2`, selects `5`.

### Expected 

Echos `9 4.9,4.9`, selects `x`.

Note also that `:select -display-column 100.100,100.100<ret>` says `coordinate 99.99 doesn't exist in buffer`.

**Comment by eraserhd** [comment]
I'll pick this one up later today if I have time.

**Comment by mawww** [comment]
You want to use get_column/get_byte_to_column from buffer_utils.hh instead of the ones provided by string.hh so that tabstops are taken into account.
