### ISSUE TITLE
Git rebase todo command colors are the same

### ISSUE THREAD

**Issue by camsteffen** [mawww/kakoune#3208]
In vim, there are different colors for `pick`, `fixup`, `squash`, etc. But in kakoune, the colors are the same. I tried different colorschemes.

This feature is important to me because, when I use autosquash, I want the fixups to stand out.

Kak:
![image](https://user-images.githubusercontent.com/5565418/68890632-e6a36700-06e4-11ea-8165-fd2a7e1f62b8.png)

Vim:
![image](https://user-images.githubusercontent.com/5565418/68890479-99bf9080-06e4-11ea-9e4e-f9cf587f20a6.png)

Reproduce:
```
mkdir temp
cd temp
git init
echo foo > foo
git add .
git commit -m foo
echo bar > foo
git commit -a --fixup=HEAD
echo baz > foo
git commit -am baz --squash=HEAD
VISUAL=kak git rebase --autosquash --root -i
```

**Comment by lenormf** [comment]
You can customize colors to your liking with something along the following user configuration commands (untested):

```
hook global WinSetOption filetype=git-rebase %{
    addhl window/ regex ^(?:(?<fixup>fixup)|(?<pick>pick)|(?<squash>squash))\b fixup:red pick:green squash:blue
}
```

**Comment by camsteffen** [comment]
Would this be a welcome contribution for the builtin `git-rebase` module? If it seems like too many colors and therefore too opinionated, maybe a good compromise would be to add just one color for all commands other than `pick`?

**Comment by lenormf** [comment]
Maybe highlighting `pick` differently makes sense, because it's virtually a no-op.

Highlighting all commands differently with individual faces would probably not go so well, there aren't that many builtin faces and the outcome would be inconsistent visually.

Users who do want that can easily use the snippet above, and it will suit their needs perfectly.
