### ISSUE TITLE
exec Z doesn't work correctly

### ISSUE THREAD

**Issue by losnappas** [mawww/kakoune#3213]
Open up a new file with `kak -n test`, and use command `:exec Z`. You'll get the "Saved 1 selections to register '^'" message. Now hit `z`, and you'll get "register '^' does not contain a selections desc," even though it was just saved.

I was trying to bind `Z` to `<a-Z>a`, but it was buggy and so I think this one is related/cause.
Same problem with the rest of z-family.

**Comment by occivink** [comment]
That's because `exec` doesn't preserve changes to certain registers by default, so that you don't accidentally overwrite common registers when scripting. This can be controlled with the `-save-regs` flag: if you call `:exec -save-regs '' Z` it should do what you expect.

**Comment by alexherbo2** [comment]
You can look at [execeval.asciidoc] in addition.

[execeval.asciidoc]: https://github.com/mawww/kakoune/blob/master/doc/pages/execeval.asciidoc

**Comment by losnappas** [comment]
I see! thanks

**Comment by mawww** [comment]
More precisely, the default register that `Z` uses is `^` which is in the set of saved-by-default registers for the `:exec` command.
