### ISSUE TITLE
Scrolling from json_ui does not move cursor as cursor wheel in ncurses does

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#3219]
### Steps 

Use the json_ui, open a long document, set the cursor at the top of the viewport in the middle of the document and send `scroll` down.

### Outcome 

Nothing happens, nothing scrolls and the cursor does not move. Presumably because scrolling would have to move the cursor.

### Expected 

The document scrolls down (and the cursor is at the top of the viewport). This is what happens in the ncurses ui.

HTH (as ironzorg says)

**Comment by mawww** [comment]
Could not reproduce with a regression test, could you check that commit to tell me what I am doing wrong ?

**Comment by danr** [comment]
Mistake was at my side! Sorry.
