### ISSUE TITLE
tmux error after startup

### ISSUE THREAD

**Issue by bonds** [mawww/kakoune#3237]
### Steps 

1. $ git clone https://github.com/mawww/kakoune
1. \# cd kakoune; gmake install
1. $ kak
1. :buffer \*debug\*

### Outcome 

````
*** This is the debug buffer, where debug info will be written ***
shell stderr: <<<
tmux: unknown option -- V
usage: tmux [-2Cluv] [-c shell-command] [-f file] [-L socket-name]
            [-S socket-path] [command [flags]]
>>>
````

````
~ ❯❯❯ uname -a                                                                      Sun 2019-12-01 15:35:41 -0800
OpenBSD maybe.ggr.com 6.6 GENERIC.MP#3 amd64
~ ❯❯❯ kak -version                                                                  Sun 2019-12-01 15:35:43 -0800
Kakoune v2019.07.01-333-g0749ec9b
 
````

### Expected 

No errors at startup.

**Comment by alexherbo2** [comment]
It looks a tmux error.  What is your version of tmux?

**Comment by bonds** [comment]
It's the version of tmux that ships with the base install of OpenBSD 6.6 amd64. It does not support the -V flag and I didn't see anything in the man page about getting it to report its own version.

https://man.openbsd.org/OpenBSD-current/man1/tmux.1

**Comment by caksoylar** [comment]
Interesting, the [non-portable version of tmux](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/tmux/) (for OpenBSD) indeed doesn't have a version switch. I guess its versioning supposed to be tied to the OpenBSD releases, so either (a) a case could be made to the tmux author to include `-V` for better interop with other tools or (b) OpenBSD version can be checked if `-V` fails.

**Comment by lenormf** [comment]
I would argue that it's now become counter-productive to validate the version number. There are several version formats, (apparently) no standard way of getting the version string, and the parsing takes up several lines.

Let's just set the aliases if `tmux` is in the PATH *regardless*, errors will be reported to the `\*debug\*` buffer in any case. Tmux v2 should now be widespread enough across distributions that we don't need to handle legacy versions.

**Comment by bonds** [comment]
Just in case the 'parse the OpenBSD version' solution is chosen, without commenting on the wisdom of doing so, it looks like tmux v2.0 [was released 2015-06-04](https://github.com/tmux/tmux/releases/tag/2.0) and OpenBSD v5.8 [was released 2015-10-18](https://www.openbsd.org/58.html) and so it probably includes the tmux v2.0 (or later) features.

**Comment by lenormf** [comment]
Should an issue be created on OBSD's tracker, to ask them to merge the [relevant upstream commit](https://github.com/tmux/tmux/commit/1a4d78c7af5826e653ae1a3c010ef2171dcdb822)?

**Comment by Screwtapello** [comment]
It looks like [people have asked for `-V` on OpenBSD before](https://github.com/tmux/tmux/issues/1141) and been declined.

At this point I think it's probably safe to just document the tmux v2 dependency and not bother checking at runtime.
