### ISSUE TITLE
100% CPU usage after terminal dies

### ISSUE THREAD

**Issue by emilazy** [mawww/kakoune#3242]
### Steps 

1. Have terminal with kak (2019.07.01) open
2. Have the terminal/pty die somehow

### Outcome 

Nondeterministically, and rarely, I sometimes half an hour later notice the fans on my laptop have spun up, run `top` and learn that a zombie kak process is using up all of one core.

### Expected 

`kak` dies gracefully.

I remember seeing this issue mentioned by other people in `#kakoune` once or twice before, and apparently there's not a current bug report for it, so here it is.

**Comment by mawww** [comment]
Could you update to latest master and check if that happens there as well, there were quite a few changes that might have fixed that.

**Comment by emilazy** [comment]
I'll try and see if I can get it to reproduce on a newer version and get a stack trace. For what it's worth, it's easy to reproduce behaviour like this (again on the current release) with something like `!yes<ret>` and then killing the terminal, though I suspect something subtler is happening in the cases where I actually observe it.

**Comment by lenormf** [comment]
Could not reproduce with the development version, I tried killing the terminal and the shell individually.

**Comment by emilazy** [comment]
```emily@renko ~> kak -version
Kakoune v2019.12.10```

kak no longer uses 100% CPU when I kill it after `!yes<ret>`, but it does stay alive and uses CPU forever. I think kak should quit if its terminal disappears.

**Comment by lenormf** [comment]
Possibly related #3288.

**Comment by deviant** [comment]
I have experienced the same thing. I think I've had this happen before and just killed it, but was curious this time and decided to poke around and figure out what was going on.

The PTY master has indeed been closed, and kakoune is in an endless loop trying to read from stdin. Given that it would have received a SIGHUP when the master was closed (which should have triggered its shutdown sequence), I am inclined to believe that there is a race condition in kakoune's signal handling code. Sending a SIGHUP manually caused it to exit correctly.

While debugging, I tried connecting another client to its session, which displayed a blank screen and did not respond to input. When I shut down the first process, the new client immediately sprang to life, and I was able to continue working in the session as if nothing had happened. Nothing interesting was visible in the debug buffer.

Sample strace output in htop:

```
strace: Process 21092 attached
05:14:48.573046 pselect6(5, [0 3 4], [], [], {tv_sec=0, tv_nsec=0}, {NULL, 8}) = 1 (in [0], left {tv_sec=0, tv_nsec=0}) <0.000021>
05:14:48.573336 select(1, [0], NULL, NULL, {tv_sec=0, tv_usec=0}) = 1 (in [0], left {tv_sec=0, tv_usec=0}) <0.000009>
05:14:48.573388 read(0, "", 1)          = 0 <0.000009>
05:14:48.573424 pselect6(5, [0 3 4], [], [], {tv_sec=0, tv_nsec=0}, {NULL, 8}) = 1 (in [0], left {tv_sec=0, tv_nsec=0}) <0.000013>
05:14:48.573470 select(1, [0], NULL, NULL, {tv_sec=0, tv_usec=0}) = 1 (in [0], left {tv_sec=0, tv_usec=0}) <0.000019>
05:14:48.573532 read(0, "", 1)          = 0 <0.000009>
05:14:48.573590 pselect6(5, [0 3 4], [], [], {tv_sec=0, tv_nsec=0}, {NULL, 8}) = 1 (in [0], left {tv_sec=0, tv_nsec=0}) <0.000017>
05:14:48.573643 select(1, [0], NULL, NULL, {tv_sec=0, tv_usec=0}) = 1 (in [0], left {tv_sec=0, tv_usec=0}) <0.000009>
05:14:48.573679 read(0, "", 1)          = 0 <0.000008>
05:14:48.573710 pselect6(5, [0 3 4], [], [], {tv_sec=0, tv_nsec=0}, {NULL, 8}) = 1 (in [0], left {tv_sec=0, tv_nsec=0}) <0.000009>
05:14:48.573750 select(1, [0], NULL, NULL, {tv_sec=0, tv_usec=0}) = 1 (in [0], left {tv_sec=0, tv_usec=0}) <0.000009>
05:14:48.573786 read(0, "", 1)          = 0 <0.000009>
[...]
```

And a peek at the fdtab:

```
   FD TYPE    MODE DEVICE           SIZE       NODE  NAME
    0 CHR     u    0x15                          14  /dev/pts/11 (deleted)
    1 CHR     u    0x15                          14  /dev/pts/11 (deleted)
    2 CHR     u    0x15                          14  /dev/pts/11 (deleted)
[...]
```

Additional information:
- kakoune: 2020.09.01
- alacritty: 0.7.1
- sway: 1.5.1

**Comment by emilazy** [comment]
@deviant Thanks for looking into this! It looks like 94ac3084e156b87869f8b336ae0a3fd752743179 (which i newer than 2020.09.01) might have fixed this? (But I haven't had the environment where this happened regularly on hand to test with for a while.)

**Comment by deviant** [comment]
Oh, I think you're right! I don't have a reproduction for this however, so I'm not sure how to test the patch (and `!yes<ret>` is a different issue, as it's waiting for the process to exit forever).
