### ISSUE TITLE
Add saveas command

### ISSUE THREAD

**Issue by camsteffen** [mawww/kakoune#3243]
Add the `:sav[eas]` feature (from Vim).

    :saveas my-file.txt

This is largely to improve workflow for scratch buffers. See #1496 and #3115. The common use case is: open kak with no arugments, enter some text, save as a file, continue editing.

It basically combines `:write` and `:rename-buffer`. This provides a convenient solution for a common use case without breaking orthogonality of existing commands (see #2424). Of course it would also be useful for some cases that do not involve the scratch buffer. It's very analogous to "Save As..." in many GUI applications.

From Vim help (I'm not sure how much of this applies to kakoune):

							*:sav* *:saveas*
	:sav[eas][!] [++opt] {file}
				Save the current buffer under the name {file} and set
				the filename of the current buffer to {file}.  The
				previous name is used for the alternate file name.
				The [!] is needed to overwrite an existing file.
				When 'filetype' is empty filetype detection is done
				with the new name, before the file is written.
				When the write was successful 'readonly' is reset.
				{not in Vi}

**Comment by Screwtapello** [comment]
Kakoune has two relevant buffer attributes: `%val{buffile}`, which is the absolute, canonical path to the file on disk, and `%val{bufname}`, which is a short name automatically-generated to be unique in the current session. `%val{bufname}` is *usually* the basename of the file, except if you open two different files with the same basename.

`:rename-buffer` changes `%val{bufname}`, but it does not change `%val{buffile}`, so it wouldn't be possible to build `:saveas` on top of it.

Maybe there could be a `:move-buffer` command to change `%val{buffile}`, but there would also need to be some kind of `BufMove` hook to notify plugins that a buffer's filename has changed. For example, my [kakoune-state-save](https://gitlab.com/Screwtapello/kakoune-state-save) plugin keeps separate state for every file opened in Kakoune, so if `%val{buffile}` ever changes, it may need to update its configuration to save things to the right place.

**Comment by mawww** [comment]
That is not exactly right, internally buffers have only a single name. Depending on if the buffer has the `File` flag, they are treated slightly differently. `%val{buffile}` always gives us the buffer name unmodified. `%val{bufname}` gives us a "display friendly name" which is going to be a relative path, or a `~` compressed path for File buffers, and just the plain name for non-file buffers.

`:rename-buffer` does change the buffer name, and hence both of those. 

I would be ok with a `-rename` switch to pass to `:write` to notify that the buffer should be renamed to point to the given target file, this could enfore the `File` flag on the buffer as well, allowing to convert scratch buffers to file ones.

**Comment by camsteffen** [comment]
> I would be ok with a `-rename` switch to pass to `:write`

That sounds good. Can I create an alias with a switch? (`:saveas = :write -rename`)

**Comment by Screwtapello** [comment]
I'm sure I'd tried renaming buffers previously, but I guess I hadn't tested extensively enough. Thanks for the correction!

**Comment by mawww** [comment]
Just introduced a `-file` and `-scratch` switch to rename-buffer, which means `saveas` can now be implemented as `def saveas -params 1 -file-completion %{ rename-buffer -file %arg{1}; write }`

**Comment by camsteffen** [comment]
@mawww I really appreciate your commitment to simple consistent design. You found the elegant solution here. Looking forward to watching this project grow.

**Comment by mawww** [comment]
Thank you :)
