### ISSUE TITLE
"new file" flag does not appear after renaming a buffer.

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#3244]
### Steps 

1. Start Kakoune in an empty directory, and edit a file that does not (yet) exist:

        cd $(mktemp -d)
        kak -n foo

1. Observe the "new file" flag in the status line.
1. Create the file on disk with `:w<ret>` and observe the "new file" flag goes away.
1. Make the buffer point at a different file that does not (yet) exist:

        :rename-buffer bar

### Outcome 

`%val{buffile}` points at a file that does not exist, but the "new file" flag does not appear in the status line.

### Expected 

The "new file" flag should appear in the status line.

**Comment by Screwtapello** [comment]
Commit 4209420 was intended to fix this issue (thanks!), but the commit message misspelled "Fixes" so Github didn't actually close the issue.

I re-tested the instructions in the OP, and now the outcome is that the "new file" *and* "modified" flags are set, even though the buffer wasn't modified before it was renamed. Was that intentional?

**Comment by mawww** [comment]
Modified was intentional, as the buffer state does not match what is currently on disk. I figured we would want Kakoune to prevent `quit` from proceeding if we have a unsaved renamed buffer.

**Comment by Screwtapello** [comment]
Right now, if I `kak -n bar` (which doesn't exist) and insert some text, that's exactly the same ("new" + "modified") as if I `kak -n foo`, insert some text, and `:rename-buffer bar`, as it should be.

But if I `kak -n bar` (which doesn't exist) and *don't* insert some text, that's a different from if I `kak -n foo` and `:rename-buffer bar` - in the first case, it's just "new", but in the second case it's "new" + "modified".

I guess that's a pretty obscure corner-case, though. and not a big deal.
