### ISSUE TITLE
format.kak - missing error message if external program failed

### ISSUE THREAD

**Issue by mzanibelli** [mawww/kakoune#3254]
Version: `Kakoune v2019.12.10`

### Steps 

External program used as formatter fails (returns non-zero code)

### Outcome 

No error message is displayed

### Expected 

The error message `formatter returned an error <code>` is displayed

**Comment by Screwtapello** [comment]
Steps to reproduce:

- Start Kakoune without a file, so it defaults to the scratch buffer which doesn't have any autoformatting config by default
- Set a formatter that always fails:

        :set window formatcmd /bin/false

- Run the formatter:

        :format

Actual outcome:

- The `*debug*` buffer gets new messages:

        error running command 'eval -client client0 %{ fail formatter returned an error 1 }
        ': formatter returned an error 1

Expected outcome:

- The error should be displayed to the user.

The strange error message comes from the way `formatting.kak` returns the error message to Kakoune. It runs the formatter asynchronously, then to report the result does the moral equivalent of:

    echo eval -client $kak_client %{ fail formatter returned an error $? } |
        kak -p $kak_session

If I run these commands directly inside Kakoune, they both appear in the status line:

    echo blort
    fail blort

If I run these commands directly inside Kakoune, they both appear in the status line:

    eval -client client0 echo blort
    eval -client client0 fail blort

If I run these commands from the shell, the `echo` appears in the status line, but the `fail` only appears in `*debug*`:

    echo eval -client client0 %{ echo blort } | kak -p failsess
    echo eval -client client0 %{ fail blort } | kak -p failsess

If I run these commands from the shell, the `echo` does not appear, but the `fail` appears in `*debug*`:

    echo eval %{ echo blort } | kak -p failsess
    echo eval %{ fail blort } | kak -p failsess

It seems like `fail` always throws an error in the current client, even when `eval -client` is trying to execute it in the context of a different client.

This change was introduced with 5b1f9255a1bf87b94d1ccb208ba676fbb4ef64ec which switched from `echo -markup {Error}` to a real `fail`. I think using a real `fail` makes sense, but apparently it doesn't work the way we expected.

**Comment by lenormf** [comment]
The `spell` module suffers from the same bug. Reproducer: `:spell xx`.

**Comment by mzanibelli** [comment]
@Screwtapello thanks for such a detailed bug report! I was in a hurry...

Indeed, `throw failure` coming from `fail` seems to be handled differently depending on the current execution context. That's easily fixed by editing RC scripts with simple `echo`s while the bug is still present.

Cheers!

**Comment by Screwtapello** [comment]
I think this would be fixed by https://github.com/mawww/kakoune/issues/2292
