### ISSUE TITLE
Feature request: mappings for sequences of keys

### ISSUE THREAD

**Issue by gemath** [mawww/kakoune#3259]
How about supporting mappings like this one

`map global insert jj <esc>`

which would allow me to exit insert mode with a double-tap of the `j` key like nvim does. I'm not a big fan of the `<esc>`, `<ctl>` and `<alt>` keys (long time vim/nvim user with stiff hands :o) and would like to see this dimension added to the key mapping space.

The general rule would be: keep reading keys pressed within a short (configurable) interval of time starting with the last key press to get the sequence, then map. Think double-clicking a mouse button. This should obviously only be done for keys which actually have a sequence mapping to avoid introducing lag for other keys.

**Comment by Screwtapello** [comment]
It's [already possible](https://github.com/mawww/kakoune/wiki/Avoid-the-escape-key) to leave insert mode with `jj`, although it's difficult to invent if somebody hasn't already shown you the trick.

**Comment by andreyorst** [comment]
@gemath I've defined two commands for you:

```
define-command -docstring "map-sequence <scope> <sequence> <command>: map <sequence> of keys to <command> in insert mode." \
map-sequence -params 3 %{ evaluate-commands %sh{
    keys=$(printf "%s" "$2" | sed "s/\([&|]\)/\1\1/g")
    cmd=$(printf "%s" "$3" | sed "s/\([@&|]\)/\1\1/g")
    printf "%s\n" "hook -group $2-seq $1 InsertChar ${2##${2%%?}} %|
        try %&
            execute-keys -draft h<a-B> <a-k>$keys<ret> s$keys\z<ret> d
            evaluate-commands %@$cmd@
        &
    |"
}}

define-command -docstring "unmap-sequence <sequence>: unmap <sequence> of keys in insert mode." \
unmap-sequence -params 1 %{
    remove-hooks "%arg{1}-seq"
}

map-sequence global jj %{exec <esc>}
map-sequence global time %{echo %sh{date}}
```

This will allow mapping any sequence to any command with ease. What do you think?

**Comment by mawww** [comment]
mapping sequence of keys is not something I plan to implement in the core, I think the various pieces we have make it possible to implement them in scripts if they are really needed (through `on-key` or user modes).

**Comment by gemath** [comment]
Sry for the late reply guys, hope it's ok to comment on a closed issue.

@mawww yes, didn't know enough of kak's potential to understand that.

@Screwtapello @andreyorst Thx for your solutions, they have two drawbacks though:
- no easy way to actually input "jj"
- my global hook to change the cursor on switching out of insert mode is not triggered

After diving into the docs, I came up with the following:
```set global idle_timeout 200
hook global InsertChar j %{
  map buffer insert j <backspace><esc>
  hook -once buffer InsertIdle .* %{
    unmap buffer insert j
  }
}
```
Seems to do what it's supposed to do, does it have drawbacks I don't understand?

**Comment by occivink** [comment]
This is something that timers (#2337) could help with, if you wanted to have it timing dependent

**Comment by gemath** [comment]
Should have mentioned in my last post that it took
```
set global idle_timeout 200
```
to make the "double-tap" interval viable. Would something like #2337 be implemented, maybe `idle_timeout` wouldn't have to be "abused" for that.
