### ISSUE TITLE
Exception uncaught after usnig autocomplete

### ISSUE THREAD

**Issue by shrit** [mawww/kakoune#3270]
To reproduce this bug on Kakoune last version 

### Steps 
Try to replace a word using %sword\<ret>c\word2
Instead of writing the word2, choose a suggestion by the autocomplete using ctrl-n

### Outcome 
uncaught exception (St9bad_alloc):
std::bad_alloc

**Comment by mawww** [comment]
bad_alloc suggest that you are getting out of memory, what kind of system does Kakoune run on ?

I cannot reproduce here, could you try to get a backtrace when the exception is thrown ? (use the `catch throw` command in gdb to break on exception thrown, then `backtrace` to get a backtrace).

**Comment by shrit** [comment]
I am using arch linux with 32 GB of Ram and two xeon processor. However, you are right, actually, it is true that I am running out of memory because of kak-lsp. I have started another issue on kak-lsp (you can see here https://github.com/ul/kak-lsp/issues/271).

**Comment by rf-** [comment]
I can reproduce this reliably with `kak-lsp`, but it doesn't seem like it's actually an EOM, unless it's kakoune hitting some kind of self-imposed limit—I have a lot of free memory, and I can trigger it immediately after starting the editor.

I haven't tried to come up with a minimal repro yet, but with my current configuration the repro steps are:
1) Open a file with LSP enabled
2) Use `<C-n>` to choose a completion from LSP
3) Hit `<C-w>`, which is defined as:
```
map global insert <c-w> '<left><a-;><a-B><a-;>"_d'
```

This crashes with the same output @shrit reported. I tried running through the `<c-w>` mapping by hand but wasn't able to get the same behavior, and I also don't see a crash with the LSP plugin turned off.

**Comment by rf-** [comment]
This is my gdb session with a fresh build of `kak` from source. Is there something I need to do differently to get a backtrace?
```
Reading symbols from src/kak...
(gdb) catch throw
Catchpoint 1 (throw)
(gdb) run ~/src/pry/lib/pry/repl.rb
Starting program: /Users/rfitz/src/vendor/kakoune/src/kak ~/src/pry/lib/pry/repl.rb
[New Thread 0x2603 of process 13529]
[New Thread 0x1a03 of process 13529]
warning: unhandled dyld version (16)
uncaught exception (St9bad_alloc):
std::bad_alloc
[Inferior 1 (process 13529) exited with code 0377]
(gdb) backtrace
No stack.
```

**Comment by rf-** [comment]
So far, the most minimal `kakrc` I've been able to repro with is:
```
map global insert <c-w> '<a-;><a-B><a-;>d'

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "ul/kak-lsp" config %{
  set global lsp_cmd "kak-lsp --config %val{config}/kak-lsp.toml -s %val{session}"
  lsp-enable
}
```

**Comment by vnagarnaik** [comment]
I am experiencing this crash as well. It has happened 3 times now and always seem to happen when autocompleting some identifier. However, I don't have kak-lsp in my config.

It started happening after updating to the latest release version:
```
kak -version
Kakoune v2019.12.10
```


The machine has lots of free memory around and kakoune is not restricted in any way.

The error message:
```
uncaught exception (St9bad_alloc):
std::bad_alloc
```

**Comment by mawww** [comment]
@rf- I am surprised gdb does not stop when the exception is thrown, what you are doing seems correct to me.

**Comment by mawww** [comment]
Does that issue happens on latest master as well ?

**Comment by rf-** [comment]
Yes, my gdb session was with latest master.

**Comment by mawww** [comment]
seems you are on Mac, maybe lldb would give a better result with catching exception being thrown.

**Comment by mawww** [comment]
(I did try to reproduce that with no success so far)

**Comment by vnagarnaik** [comment]
I have a consistent repro with version:
```
> kak -version
Kakoune v2019.12.10
```

I am running kakoune on `debian testing` with kernel based on `5.2.17`.

Create a file `a.cc` with the following contents:
```
class Test {
 public:
  Test(bool inject_a_really_long_bool_causes_alloc_failure)
      : inject_a_really_long_bool_causes_alloc_failure_(replace_me) {}

 private:
  bool inject_a_really_long_bool_causes_alloc_failure_;
};
```

Then replace `replace_me` with `inject_a_really_long_bool_causes_alloc_failure` using the following operation:
```
/replace^MEcinje<Tab>)
```

`kak` crashes when entering the last `)` character and at the same time as lines are being reformatted to wraparound. I can also repro the crash if the last character is `,` instead of `)`. Basically anything that causes a reflow of the current line.

My C++ options are:
```
hook global BufSetOption filetype=cpp %{
    set-option buffer tabstop     2
    set-option buffer indentwidth 2
}
```

**Comment by mawww** [comment]
@vnagarnaik What triggers that reformatting ? are you using autowrap ?

**Comment by vnagarnaik** [comment]
> @vnagarnaik What triggers that reformatting ? are you using autowrap ?

Yes, I have enabled autowrap for all files.

```
hook global WinCreate .* autowrap-enable
```

**Comment by mawww** [comment]
Ok, got it, I can reproduce that here, I see whats going on, will fix that soon.

Thanks a lot for the repro steps.
