### ISSUE TITLE
Request for C# syntax highlighting and autocomplete

### ISSUE THREAD

**Issue by BanchouBoo** [mawww/kakoune#3271]
Lack of C# support is the one thing holding me back from using Kakoune, would love to see support for it so I can justify using it as my main editor.

**Comment by andreyorst** [comment]
would be useful to have some links on official list of keywords, code style, e.t.c.

**Comment by BanchouBoo** [comment]
[Keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/)
[Coding conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)

Emac's [csharp-mode](https://github.com/josteink/csharp-mode) may also be useful for reference.

For autocompletion, [omnisharp](https://github.com/OmniSharp) is what you would use. The Github page has implementations for multiple editors (including vim and emacs) that also may be useful for reference.

**Comment by ilserd** [comment]
@BanchouBoo why did you close this issue?

**Comment by BanchouBoo** [comment]
> @BanchouBoo why did you close this issue?

It's been three years so I don't remember the exact reason but I don't use C# anymore and I've since quit using kakoune, and I no longer use syntax highlighting or autocomplete either, so this is about as far from being relevant to me as it could possibly be. Feel free to open a new issue on the subject if you feel this is something that's still needed.

**Comment by ilserd** [comment]
> > @BanchouBoo why did you close this issue?
> 
> It's been three years so I don't remember the exact reason but I don't use C# anymore and I've since quit using kakoune, and I no longer use syntax highlighting or autocomplete either, so this is about as far from being relevant to me as it could possibly be. Feel free to open a new issue on the subject if you feel this is something that's still needed.

Thank you for the quick reply! (and you left me wondering why would you stop using syntax highlighting or autocomplete).
I've opened another issue.

**Comment by BanchouBoo** [comment]
> (and you left me wondering why would you stop using syntax highlighting or autocomplete)

I personally find it easier to read code without all the different colors, it feels like a more cohesive, easier to understand whole instead of a bunch of disparate parts. As for autocomplete, it's an interruption that ruins my flow and also relying on it means that things don't stay in my head as easily, since I can just search through the autocomplete entries for it, so forcing myself to look at documentation when I don't know how to do something helps it stick better in my mind. Results on both fronts will obviously vary per person and per language, I won't claim that just because it's been good for me that everyone should do it, although I think everyone should at least give it an fair attempt because even if you don't stick with it you'll have a better understanding of the things you prefer and why and that's always positive.
