### ISSUE TITLE
5000 process of kak-lsp

### ISSUE THREAD

**Issue by shrit** [mawww/kakoune#3274]
I left kakoune running during the night. Today, checking the `htop` for memory, I have noticed at least 5000 processes of `kak-lsp`
Here is a screenshot of a part of these processes.
Best regards,

![2019-12-27-123519_1366x768_scrot](https://user-images.githubusercontent.com/15039782/71516004-c4396780-28a6-11ea-9ea1-26660853fb01.png)

**Comment by Screwtapello** [comment]
You should probably report that to the [kak-lsp issue tracker](https://github.com/ul/kak-lsp/issues), since kak-lsp isn't actually part of Kakoune.

**Comment by shrit** [comment]
Ok I see, I will open a new one there and close this one.
