### ISSUE TITLE
"extend line to end" vs "extend line to begin"

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#3279]
I can continuously extend line to end with `}x`. However that's not the case with extend line to begin with `{x`. I expected both `{x` and `}x` behave in the same manner.
I wish I could shrink my multiline selection with `{x` continuously instead of `K` in order to reserve `K` for something else.

**Comment by mawww** [comment]
Hello,

I dont quite understand your issue here, `}x` is not a kakoune command, is that part of a plugin you are using ?

**Comment by vbauerster** [comment]
You're right!
It turns out it is part of [kakoune-text-objects](https://github.com/delapouite/kakoune-text-objects) plugin. My bad, I should be a bit attentive before opening this.
Anyway thank you @mawww for kakoune and happy new year!

**Comment by mawww** [comment]
Happy New Year !
