### ISSUE TITLE
ALT key ignored in ALT + SHIFT + key combinations

### ISSUE THREAD

**Issue by renkenn** [mawww/kakoune#3303]
# Steps
1. Open kakoune `kak`
2. `<a-K>`

### Outcome
1. `<a-k>` keep matching

### Expected 
1. `<a-K>` keep not matching

# Information
### Versions tested
* v2019.07.01-329-gb765fb49
* Kakoune v2020.01.16

### System information
* OS: GNU/Linux Debian buster (stable) `Linux siga 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux`
* DE: Xfce4
* WM: Xfwm4
* Terminal: xfce4-terminal `$TERM=xterm-256color`, st `$TERM=st-256color` and kitty `xterm-kitty`
* No multiplexer
* Keyboard works properly.

### Note
This seems to affect every ALT+SHIFT+Key combination such as `<a-K>`, `<a-)`, `<a-(`, `<a-">`

**Comment by Screwtapello** [comment]
Do Alt+Shift+key combinations work in other terminal apps?

What happens if you run `/bin/cat` and press those keys? On my machine, where Kakoune works well, `<a-k>` produces `^[k` and `<a-K>` produces `^[K`.

**Comment by renkenn** [comment]
It seems that the issue exists outside of kakoune as well. On `/bin/cat` both `<a-k>` and `<a-K>` produce `^[k`.

Thanks @Screwtapello, I'm closing this issue as it's outside of kakoune's scope.
