### ISSUE TITLE
Killing headless sessions by name

### ISSUE THREAD

**Issue by bb010g** [mawww/kakoune#331]
It would be nice to be able to kill a headless session by name for cases like a systemd service. Could be as simple as `-k <arg>: kill given session`.

**Comment by jordan-yee** [comment]
In case anyone is looking for how to do this:

```
# List existing sessions:
kak -l
# Kill a session by name:
echo kill | kak -p <session name>
```

> You can list existing sessions with kak -l, you can start a new session with kak -d, you can terminate a session with echo kill | kak -p.

The above quote is from [this other issue](https://github.com/mawww/kakoune/issues/3686#issuecomment-683276938).
