### ISSUE TITLE
actual and display position of cursor mismatch in ncurse ui

### ISSUE THREAD

**Issue by Dead-User** [mawww/kakoune#3316]
# 1. What the bug is like
when moving the cursor in ncurse ui, sometimes the cursor and characters following it will be duplicated. For example, given the text:
```
abcdef[g]hi
```
when moving the cursor from right to left, the displayed text becomes:
```
a[f]gdef[g]hi
```
Say the cursor is moving from character a to character b, In effect, the following things happen:

> 1. the 'real' displayed cursor block did not move (still at a), but colum number shows that the cursor is already at b

> 2. a 'fake' a, b and cursor appears two characters after b, but the 'fake' cursor block is correctly displayed at b(fake)

> 3. if continues moving, the 'real' cursor's behaviour is corrected, but the 'fake' cursor remains displayed. When the 'real' cursor meets the 'fake' cursor, the fake one disappeard (but mis-placed characters ('fake' a and b) won't disappear

# 2. What version of kak ?
I am running kak 2020.01.16-12-g27490931, built from the app-editors/kakoune-9999 portage on gentoo 4.19.97. I have another machine running archlinux (up-to-date when writing this issue) with kak 2020.01.16 installed using pacman, where the bug does *not* present.

I use the ncurse ui, the json ui is not tested yet.

# 3. further information
After some experiments, I have found some interesting facts about this bug:

> 1. running kak -n in the default buffer without opening a file *can* reproduce this bug -- not a problem of my config or a broken file

> 2. both character-based and word-based movement can trigger this bug

> 3. this bug can, and perhaps can only be triggered when moving from right to left, from *displayed* colum 10 to *displayed* colum 9 (I just have no idea why)

**Comment by lenormf** [comment]
How do you move the cursor? With <kbd>h</kbd>?

What terminals did you try to reproduce this on? Do you modify `$TERM`?

Do you use any multiplexers (e.g. Tmux)?

**Comment by Dead-User** [comment]
Further test done. Using alacritty + i3, no multiplexer.
The bug only present when using terminal emulator, and can be reproduced using GNU nano.
ncurse or alacritty, anyway, not kak. Good catch, I'll close the issue.
