### ISSUE TITLE
Wiki's yank fook for tmux fails when starting with '-'

### ISSUE THREAD

**Issue by dooglius** [mawww/kakoune#3320]
### Steps 
Add the following (from [here](https://github.com/mawww/kakoune/wiki/Registers---Clipboard)):
```
hook global NormalKey y|d|c %{ nop %sh{
  if [ -n $TMUX ]; then
    tmux set-buffer "$kak_main_reg_dquote"
  fi
}}
```

Now attempt to copy something starting with a dash, say `-foo`

### Outcome 

Nothing happens, and I get the following in my debug buffer:
```
shell stderr: <<<
tmux: unknown option -- f
usage: set-buffer [-a] [-b buffer-name] [-n new-buffer-name] data
>>>
```

### Expected 

The text is copied to my tmux buffer, and I get no errors in the debug buffer

**Comment by alexherbo2** [comment]
Add `--` to stop option parsing.

**Comment by caksoylar** [comment]
Thanks that works, edited the wiki page now.

**Comment by danr** [comment]
Thanks! Close the issue too if this is resolved please.
