### ISSUE TITLE
`git {next,prev}-hunk` don't wrap around the file

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3321]
### Steps 

* modify a file under versioning in a Git repository
* place the cursor after that change
* run `:git next-hunk`

### Outcome 

Nothing happens.

### Expected 

The hunk above the selection is jumped to.

**Comment by Anfid** [comment]
Sorry for late follow up. Not wrapping around the file was the intended behavior. I am not sure about the correct way to handle it though. One way is to behave like a regular search command, but I could not find if there is a way to disable wrapping around the buffer. Another one is to make it togglable via flag or option with search behavior by default. I don't feel like completely removing option to disable wrapping is a good idea. What are your thoughts on this?

**Comment by lenormf** [comment]
Wrapping around the buffer is the default that was adopted for e.g. the search primitive, cycling through linting/spelling… diagnostics etc.

It's convenient because it allows user to answer "are there any more interesting lines in the buffer?", wherever the cursor is. In the case of Git hunks, it's an easy way to verify whether the  current file still has unstaged hunks, after a `git add -p` or `git checkout -p` for example.

Controlling this behaviour through an option doesn't seem worth it, are there cases where wrapping is very inconvenient, or prevent a certain workflow that cannot be implemented with the existing features?

**Comment by Anfid** [comment]
I don't consider wrapping very inconvenient, just prefer it less. However, I will update it to keep it consistent with regular search command.
