### ISSUE TITLE
[Feature Request] Add support for matching Unicode categories with regex

### ISSUE THREAD

**Issue by BanchouBoo** [mawww/kakoune#3328]
https://www.regular-expressions.info/unicode.html#category
In particular I think this would be useful for accurate syntax highlighting

**Comment by lenormf** [comment]
What's your usecase?

**Comment by BanchouBoo** [comment]
C# has specifications for what characters can be used as identifiers for class names and whatnot. For highlighting things dynamically with regex being able to easily assign specific groups of characters like that instead of manually specifying every valid character manually makes it very easy to highlight things accurately.

**Comment by lenormf** [comment]
From looking at [this comment](https://stackoverflow.com/a/950651), it does seem complicated.

But even if those character groups were available, wouldn't it be simpler to simply use `\w+`? It's more maintainable, and there's only so much you can do to validate data with regex; having the occasional false positive wouldn't hurt (Are there really C# devs who use unicode class names?).

**Comment by BanchouBoo** [comment]
Simpler for sure, just not as accurate to the specs. If you think it's unnecessary or out of scope feel free to close the issue.

**Comment by mawww** [comment]
In order to do that we would need to introduce an unicode database inside Kakoune to be able to get those definitions (AFAIK there is no posix way to do that, or maybe `wctype` is well defined with a UTF-8 locale ?). That is a lot of additional complexity for a relatively niche use case.

**Comment by eraserhd** [comment]
After a small bit of research, I concur.

We can do _POSIX_ character classes (e.g. `[[:alnum:]]`) using (http://www.cplusplus.com/reference/cwctype/wctype/)[wctype], but it doesn't support the other Unicode classes supported by `\p`, and there doesn't seem to be a way to do that without maintaining a database or using an external library which does.
