### ISSUE TITLE
[builtin-terminal-ui] Glitches occur when tab characters are part of a prompt/menu

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3333]
### Steps 

* run a client using the `builtin-terminal-ui` branch
* insert a tab character into the prompt: <kbd>:</kbd><kbd>c-v</kbd><kbd>tab</kbd>

### Outcome 

The screen glitches out.

### Expected 

A tab character is displayed where it was inserted.

Note that this bug can also be triggered with a menu whose items contain tab characters.

HTH.

**Comment by Delapouite** [comment]
I confirm this glitch. Visually, the modeline is "eaten" almost entirely, and only the `[session]` remain on the line.

**Comment by lenormf** [comment]
This issue is still reproducible on the latest branch.
