### ISSUE TITLE
Weird redraw failures when using gnome-terminal + tmux

### ISSUE THREAD

**Issue by daboross** [mawww/kakoune#3335]
### Steps 

Install gnome-terminal 3.34.2, tmux 2.9a, kak v2020.01.16 on a new Fedora 31 system.

Configure tmux per the wiki - put this in `~/.tmux.conf`:

```
set -g default-terminal "screen-256color"
```

Launch `tmux`. Launch `kak` inside.

Open a large file, one which you can scroll up/down multiple times. Use ctrl-d a few times to go down. Then use ctrl-u a few times to move back up.

### Outcome 

On scrolling down, everything works fine. But when scrolling back up, the contents in the bottom half of the screen is unchanged, and only some of the characters in the top half are overwritten.

A recording of this happening:  https://asciinema.org/a/JZifPTGqHpLBHT9DrGniWA5Dc

And a screenshot of the upper half of the screen after after scrolling up:

![image](https://user-images.githubusercontent.com/1152146/73604774-095a5480-454b-11ea-81f7-9ee18b4f02e0.png)

### Expected 

When scrolling up, the content cleanly changes, and shows exactly the file.

---

Any help figuring out what's causing this, or fixing my setup if it's that problem, is appreciated. Thanks!

**Comment by daboross** [comment]
Looks like manually building & using tmux 3.0a fixes this!

**Comment by benekastah** [comment]
This is worth reopening, IMO. Here is the bug report I was writing up when I discovered this issue:

### Steps 
I'm using iTerm2 and tmux 2.9a.
1. Check out `v2019.12.10` or later (I used current master).
1. Open a file with enough content to have a few pages of scroll. I used `src/json.cc`.
1. Press `ctrl-d` a few times, then press `ctrl-u` until you are back at the top.

### Outcome 
Screen corruption, as seen here:
![kakoune bug demo](https://user-images.githubusercontent.com/740268/79598917-8cdf0880-8099-11ea-81a1-2c302938c7a8.gif)

### Expected 
It should display only the contents of the file for the screen position. The last version that seems to work is `v2019.07.01`.

**Comment by Screwtapello** [comment]
Does the problem occur outside of tmux, inside iTerm2? Does the problem occur inside tmux in Terminal.app? Does the problem occur outside of tmux in Terminal.app?

What is `$TERM` set to in the environments where the problem occurs? Have you installed a custom terminfo entry, like [the one in Kakoune's contrib directory](https://github.com/mawww/kakoune/blob/952aa0ed0a58fc35e23dd3ca8bfa7a68ce2ea342/contrib/tmux-256color.terminfo) that makes custom colour schemes work in tmux? If you have, does the problem persist if you move it aside?

**Comment by asmarcz** [comment]
> Does the problem occur outside of tmux, inside iTerm2? Does the problem occur inside tmux in Terminal.app? Does the problem occur outside of tmux in Terminal.app?
> 
> What is `$TERM` set to in the environments where the problem occurs? Have you installed a custom terminfo entry, like [the one in Kakoune's contrib directory](https://github.com/mawww/kakoune/blob/952aa0ed0a58fc35e23dd3ca8bfa7a68ce2ea342/contrib/tmux-256color.terminfo) that makes custom colour schemes work in tmux? If you have, does the problem persist if you move it aside?

Installing terminfo entry resolved the issue in Alacritty + tmux setup.
