### ISSUE TITLE
It should be possible to lint a portion of a buffer

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#3336]
In 82d99aa, the `format` command was split into `format-selections` and `format-buffer` (which selects the whole buffer then runs `format-selections`). I propose the same change for the `lint` command, splitting it into `lint-selections` and `lint-buffer` commands (with a `lint` alias for compatibility).

As well as linting part of a buffer, this allows different linters to be used on different parts of the buffer. In particular, it would allow [shellcheck](https://www.shellcheck.net/) to check for portability problems in `%sh{}` blocks in Kakoune scripts.

I want to work on this, but before I get too far into it I figured I should file an issue so other people have a chance to say "no, that's a bad idea" or "make sure you keep in mind this particular thing".

**Comment by Screwtapello** [comment]
One thing I'm curious about: currently the linter has a line-specs option (line number and text) to store the flags for a given line, and a range-specs option (start line, start byte, end line, end byte, and text) to store the message for a given line. However, the `lint-show` command (that displays the tooltip for the current line) only ever uses the "start line" and "text" fields.

It'd be simpler to keep the lint messages in a line-specs option, but I worry whether some third-party scripts might be trying to use that information.

**Comment by Delapouite** [comment]
Should this issue be closed now that #3347 was merged?

**Comment by Screwtapello** [comment]
I thought I put the right incantations in the commit to auto-close this issue when the PR was merged, but apparently not. Thanks for the reminder!
