### ISSUE TITLE
Tmux :terminal with multiple programs

### ISSUE THREAD

**Issue by losnappas** [mawww/kakoune#3337]
### Steps 
Running `terminal 'bash;fish'` with tmux doesn't work.
### Outcome 
Nothing of note happens.
### Expected 
First fires up bash, then on exit starts fish.
### Cause
Tracked down to the `env TMPDIR="$TMPDIR"` here https://github.com/mawww/kakoune/blob/master/rc/windowing/tmux.kak#L23 . If I remove it, then things work as expected. This didn't happen before (everything worked), so maybe tmux (or fish) changed something.

```
$ tmux -V
2.9a
```
and kakoune at `Kakoune v2019.07.01-51-g1c6aa9ba`

**Comment by mawww** [comment]
The comment just above that line suggest that escaping semicolons would be desirable, did you try to add that (escaping of semicolon in tmux.kak ?)

**Comment by occivink** [comment]
@losnappas the `terminal` command tries to run its arguments as a single program, with the first being the name of the executable itself. To achieve what you want, try `terminal sh -c 'bash;fish'`

@mawww The comment only applies to simply `;`, so if you were to do `tmux-terminal-vertical bash ';' fish` the lone semicolon would be misinterpreted (ignoring the fact that it's a nonsense command).

**Comment by losnappas** [comment]
Alright, thanks!

`sh -c` version works, even without touching the `env TMPDIR` part. Kind of odd how that one breaks it, but whatever.
