### ISSUE TITLE
The case insensitive flag doesn't apply to lowercase character ranges

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3345]
### Steps 

* select "ABC"
* run: <kbd>s</kbd> `(?i)[a-z]+` <kbd>ret</kbd>

### Outcome 

* error `nothing selected`

### Expected 

* "ABC" remains selected

HTH.

**Comment by nonumeros** [comment]
Good observation. If I were to select "abc"

run `s` (?I)[A-Z]+ `ret` would return the same message

it seems a spurious closing parentheses causes it not to return an error

`(?i))`

**Comment by nonumeros** [comment]
it's fascinating nonetheless how a simple case insensitive search and match  with  say "observation" in uppercase would fail to return the same error message `search` than when using other delimiters such as a closing bracket or brace.

so `(?i)observa)` behaves as it should with the ignorecase flag
