### ISSUE TITLE
Can't build on raspbian, make error

### ISSUE THREAD

**Issue by amiceli** [mawww/kakoune#335]
I tried to compile kakoune on my raspberry pi and I've an error with make command.

The error is very long so I hosted it, you can see the full error [here](http://textuploader.com/a5xtr)

My GCC version is 4.7 and I've installed libboost

Thanks for your help

**Comment by mawww** [comment]
latest code + update to gcc 4.8 should fix that.

**Comment by amiceli** [comment]
Thank you it works now.
