### ISSUE TITLE
Add support for +number on the command line

### ISSUE THREAD

**Issue by glandium** [mawww/kakoune#336]
Gdb can invoke an editor and conveniently making it go at the right line straight away, but it relies on a command line argument that kakoune doesn't support, so kakoune can't be used an editor for gdb. Gdb invokes $EDITOR +line file
See https://sourceware.org/gdb/onlinedocs/gdb/Edit.html

**Comment by FranzSkuffka** [comment]
Did you take a look at `kak foo.bar -e 'exec <lineNumber>g'`. @glandium does this help you?

**Comment by glandium** [comment]
The problem is that gdb invokes a specific command line. At best, I'd need a wrapper script. That would kind of suck.

**Comment by FranzSkuffka** [comment]
Try this wrapper function:

`function gdbkak (){
    lineNo=$(echo $1 | cut -c2-)
    kak -e "exec $(echo $lineNo)g" $2
}`

**Comment by glandium** [comment]
I'm not going to set EDITOR differently just for gdb. So a slightly more involved wrapper would be required. I'm perfectly capable of writing such a wrapper. The point is that I shouldn't have to.

**Comment by FreeFull** [comment]
gdb isn't the only program that does this, either. Another example would be the idris repl.
