### ISSUE TITLE
Regression test `0-nothing-selected-on-prompt-initial-shift-tab` expects the wrong outcome

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3361]
Regression test `0-nothing-selected-on-prompt-initial-shift-tab` expects the last of its command's completion candidate to be selected after hitting <kbd>s-tab</kbd> twice in prompt mode.

### Steps 

* run the following command from the `src` directory:

```
$ ./kak -n -e 'source ../test/regression/0-nothing-selected-on-prompt-initial-shift-tab/rc; exec :my-command<space><s-tab>'
```

### Outcome 

No completion candidates are highlighted.

### Expected 

Suggestion `ccc` is highlighted.

At runtime, typing out <kbd>:</kbd> `my-command` <kbd>space</kbd> <kbd>s-tab</kbd> results in `ccc` being highlighted, as expected - but not in `exec`.

The `0-nothing-selected-on-prompt-initial-shift-tab` seems to rely on this bug to run - unless there's an explanation why the first hit on <kbd>s-tab</kbd> is being ignored?

Note that using <kbd>tab</kbd> instead doesn't highlight anything either.

**Comment by jkonecny12** [comment]
This test is failing on Fedora Rawhide for some reason. Not happening on any other Fedora version.

**Comment by jkonecny12** [comment]
This is still happening a new Fedora 32 is in beta freeze. It should be released on Tue 2020-04-28. It would be great to fix this before release.

https://download.copr.fedorainfracloud.org/results/jkonecny/kakoune/fedora-32-x86_64/01279166-kakoune/builder-live.log.gz

**Comment by jkonecny12** [comment]
Downstream bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1799560

**Comment by eraserhd** [comment]
I'm not sure if this is the problem, but I have just discovered that if I press `<ret>` while a very slow completion script is running, with `-menu`, Kakoune waits for the completion script, but does not select the only entry.  This means there could be a race between handling the keyboard and completion results.

**Comment by mawww** [comment]
completion triggers on idle, which does not happen in `:exec` as we dont have any delay between keystrokes. This is why the test does two `<s-tab>`, the first one triggers the completion engine manually, the second one selects the previous result.

**Comment by mawww** [comment]
This seems to be due to a compiler bug in gcc-10, reported it at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94041

**Comment by jkonecny12** [comment]
Great work @mawww. Thanks a lot for finding this.

**Comment by lenormf** [comment]
@jkonecny12 looks like the bug was fixed.

**Comment by jkonecny12** [comment]
Yep this seems to be fixed. Only waiting until it gets to Fedora 32 then everything will be OK.

Thanks a lot for your help guys, you're the best!
