### ISSUE TITLE
Feature request: Show clippy after a delay

### ISSUE THREAD

**Issue by 6112** [mawww/kakoune#3365]
When quickly using a command that shows Clippy (eg. `[p`), Clippy just quickly flickers in the corner of my screen. This is distracting

If we add a small delay before showing Clippy (like 0.5s), then it reduces flickering, but Clippy can still give me hints when I don't know what key I should press next

**Comment by Delapouite** [comment]
Related to https://github.com/mawww/kakoune/issues/2066
