### ISSUE TITLE
Mouse scroll support

### ISSUE THREAD

**Issue by devinplompier** [mawww/kakoune#337]
Would be awesome if you implemented a mouse scroll support feature like vim does. Maybe it exists but I didn't find it.
Thanks.

**Comment by mawww** [comment]
Scrolling with mouse wheel is supported, or are you refering to something else ?

**Comment by devinplompier** [comment]
Actually it works only to go up and only in command mode.

**Comment by mawww** [comment]
Sorry for the delay, you can try to fix it with the ncurses_wheel_down_button ui option, which can be set with

```
set global ui_options ncurses_wheel_down_button=<integer>
```

For the insert mode scrolling, that is still missing.
