### ISSUE TITLE
Character encoding breaks in alacritty

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#3372]
### Steps
On Mac OSX 10.14.6
alacritty: 0.4.1
kakoune: stable 2020.01.16 (bottled), HEAD
### Outcome
<img width="416" alt="image" src="https://user-images.githubusercontent.com/7485959/74611987-3be67e80-5101-11ea-9d34-6464ad5caaab.png">

### Expected

<img width="413" alt="image" src="https://user-images.githubusercontent.com/7485959/74611992-4acd3100-5101-11ea-8626-9ef3707b6ea6.png">

Please help :)

**Comment by Screwtapello** [comment]
We gotta start writing a FAQ for debugging this particular problem. Off the top of my head:

- Your terminal needs to use the UTF-8 encoding
- Kakoune needs to be linked with `libncursesw`, not `libncurses` (use `otool -L /path/to/kak` on macOS, or `ldd /path/to/kak` on Linux)
- Your locale needs to use the UTF-8 encoding - run "locale" in the terminal and check that each line of output mentions "UTF-8"

**Comment by FranzSkuffka** [comment]
Thank you! It was the locale problem.
I added `export LC_ALL=en_US.UTF-8` to my `.zshrc`.
