### ISSUE TITLE
Feature suggestion: list mapped keys

### ISSUE THREAD

**Issue by CharlesGueunet** [mawww/kakoune#3383]
Hello,

Would it be possible to have a command to list all mapped keys ?
We could do it **vim-like** using the already existing `map` command. When called without argument (or only with a scope or with a scope/mode) it list all available mapping in the current context, or in the corresponding scope/mode.

**Comment by Delapouite** [comment]
Hi.

There's a first step in this direction using the command `debug mappings` and then having a look at the `*debug*` buffer.
