### ISSUE TITLE
Bang symbol not display correctly in status bar

### ISSUE THREAD

**Issue by CharlesGueunet** [mawww/kakoune#3386]
Hello,

I have a minor issue, the symbol "!" is not displayed correctly on my status bar. It is replaced with a small [del] symbol.

### Steps

Enter command mode by tapping :
Enter a command with a bang, like edit!

### Outcome

![example](http://charles.gueu.net/doc/bug.png)

### Expected

simply `:edit!` in the bar :)

This is not life changing but wanted to see if I am the lonely one.

Reproduced on Gentoo / Arch, using GCC and Clang.

**Comment by Delapouite** [comment]
Confirmed by @eraserhd yesterday on IRC

> 17:19:33         eraserhd | :kill! appears :kill␡ on the command-line, also :)

**Comment by alexherbo2** [comment]
There were a change recently to display codepoints (bc8a9d82c3f028681c3f78075110bdd17326d679).

**Comment by mawww** [comment]
Should be fixed by af6885c0c9c56ee5c58a0088f9f4b87eb5148191 sorry about that
