### ISSUE TITLE
Freeze on using existing session for Pager

### ISSUE THREAD

**Issue by roselandgoose** [mawww/kakoune#3394]
Following [pager.kak](https://github.com/alexherbo2/pager.kak) I have successfully changed my pager to kak by setting my man-pager to the script:
```sh
#!/bin/sh
col -b -x | kak -e 'set buffer filetype man'
```

This setup however starts a new session for each instance of the pager (this works as desired). I would like however to have every pager create a buffer in an existing session, so I can share registers,etc. I always have a `kak -d` in the background, so I tried:
```sh
col -b -x | kak -c SERVER -e 'set buffer filetype man'
```
with the correct server name, and ran `man kak`.

### Outcome
Man opens a client in the correct session and correctly displays the manpage contents, but does not update the name of the buffer displayed in the lower right. The buffer also enters insert mode, and then kak freezes, not responding to <c-c> but obeying <c-z>.

![man_kak_froozen](https://user-images.githubusercontent.com/6899154/75741806-51e36a00-5cd1-11ea-997d-8f824f61b479.png)

### Conditions
```sh
kak -version
↳ Kakoune v2020.01.16-99-gf682d8c0
```
```sh
uname -osrm
↳ Linux 5.3.0-40-generic x86_64 GNU/Linux
```
```sh
lsb_release -dc
↳ Description:	        Ubuntu 19.10
↳ Codename:        	eoan
```

### Discussion
Might this be related to ansi escape codes https://github.com/mawww/kakoune/issues/759 and addressed with [kak-ansi](https://github.com/eraserhd/kak-ansi)? Everything was displayed correctly so I guessed the problem lies elsewhere.

**Comment by roselandgoose** [comment]
[kakrc.txt](https://github.com/mawww/kakoune/files/4279246/kakrc.txt)

**Comment by roselandgoose** [comment]
Running the working, duplicate sessions setup has this in the debug buffer:
```
*** This is the debug buffer, where debug info will be written ***
$HOME/.config/kak/kakrc:90:1: 'add-highlighter' no parent in path
$HOME/.local/share/kak/kakrc:28:1: 'evaluate-commands' 108:1: 'source' 90:1: 'add-highlighter' no parent in path
error while parsing kakrc:
    1:1: 'source' 28:1: 'evaluate-commands' 108:1: 'source' 90:1: 'add-highlighter' no parent in path
error running hook WinResize(55.211)/man-hooks: 1:2: 'man-impl' wrong argument count
```

**Comment by mawww** [comment]
I think the reason this happens is that kakoune does not currently read input from the terminal, as it just reads the output from `col -b` on stdin. It should be made smarter and try to open the actual tty. This is done in non-client mode, but not in client mode.

**Comment by mawww** [comment]
Ok, actually Kakoune does not even read stdin in this case.

In order to make this use case work, we would need to make Kakoune client able either to transmit their stdin fd to the server (which means kakoune remote protocol would only work through a unix socket, which might be fine), or make them able to stream data from stdin through their conneciton to the server.

This will make it possible to display data from the client stdin in the server.

We also need to fix the fact that clients do not detect that stdin is not a tty and do not re-open the tty for their UI, but this is relatively trivial to do.
