### ISSUE TITLE
Add -select-mode option to evaluate-commands and execute-keys commands

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3396]
Select modes:

- `replace`
- `extend`
- `append`

**Example** – Derive `Gi` from `gi`:

``` kak
execute-keys -select-mode extend gi
```

**Example** – Derive select modes from a user command:

``` kak
define-command user-command %{
  do-something
}

map global user x ': user-command<ret>'
map global user X ': evaluate-commands -select-mode extend user-command<ret>'
map global user <a-x> ': evaluate-commands -select-mode append user-command<ret>'
```

That way, we don’t have to explicitly implement all select modes.

The idea came from [Discuss#902/4].

[Discuss#902/4]: https://discuss.kakoune.com/t/solved-how-to-move-expand-to-the-beginning-of-line-non-blank-depending-on-where-your-cursor-is/902/4

**Comment by mawww** [comment]
That is currently impractical as there is nothing inside Kakoune that tells it G is the "extend" version of "g", we would first need to go through a big redesign of normal mode commands to clearly define relationship between them.

Moreover this would be a pretty complex feature to understand, if the user command does some checks inside some draft context, Kakoune needs to decide if it needs to apply the select mode or not, and the answer is not obvious.

**Comment by alexherbo2** [comment]
I just think to whatever happens, just extend the result from a command, for `extend`, and append for `append`.
