### ISSUE TITLE
spell check: delays with tex files.

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#3399]
### Steps 

open a `tex` file with a few hundred lines.

Invoke `spell en` 

### Outcome 

Nothing happens or There's usually an enormous delay which can last up to a minute and a half before it kicks in.

On longer lines this behavior worsens. 

### Expected 
 
To highlight spelling errors as expected within a reasonable timeframe.

Tested with v2020.01.16 and also with https://github.com/mawww/kakoune/commit/6766297623e9718db5b2b09bd655fe183acdcf67

**Comment by lenormf** [comment]
I reckon re-implementing the parsing bit in Awk would help with that. I also noticed longer files take a while to be processed.

**Comment by lenormf** [comment]
Could you please share a file that takes a significant amount of time (e.g. more than 10s) to spell-check, so we can compare implementations properly?

**Comment by lenormf** [comment]
Try the following patch, see if it's better:

```patch
From e83ad2a2a4c78e6c1b753664942f2ddf744a85f3 Mon Sep 17 00:00:00 2001
From: Frank LENORMAND <lenormf@gmail.com>
Date: Mon, 9 Mar 2020 14:22:34 +0300
Subject: [PATCH] rc spell: Re-implement message processing in Awk

Plain shell takes too long on large files.

Fixes #3399
---
 rc/tools/spell.kak | 69 ++++++++++++++++++++++++++++------------------
 1 file changed, 42 insertions(+), 27 deletions(-)

diff --git a/rc/tools/spell.kak b/rc/tools/spell.kak
index 0eeaceb5..a39c2204 100644
--- a/rc/tools/spell.kak
+++ b/rc/tools/spell.kak
@@ -37,33 +37,48 @@ define-command -params ..1 -docstring %{
         fi
 
         {
-            sed 's/^/^/' "$kak_opt_spell_tmp_file" | eval "aspell --byte-offsets -a $options" 2>&1 | {
-                line_num=1
-                regions=$kak_timestamp
-                while read -r line; do
-                    case "$line" in
-                        @\(\#\)*)
-                            # drop the identification message
-                        ;;
-                        [\#\&]*)
-                            if expr "$line" : '^&' >/dev/null; then
-                               pos=$(printf %s\\n "$line" | cut -d ' ' -f 4 | sed 's/:$//')
-                            else
-                               pos=$(printf %s\\n "$line" | cut -d ' ' -f 3)
-                            fi
-                            word=$(printf %s\\n "$line" | cut -d ' ' -f 2)
-                            # trim whitespace to make `wc` output consistent across implementations
-                            len=$(($(printf %s "$word" | wc -c)))
-                            regions="$regions $line_num.$pos+${len}|Error"
-                            ;;
-                        '') line_num=$((line_num + 1));;
-                        \*) ;;
-                        *) printf 'fail %s\n' "${line}" | kak -p "${kak_session}";;
-                    esac
-                done
-                printf 'set-option "buffer=%s" spell_regions %s' "${kak_bufname}" "${regions}" \
-                    | kak -p "${kak_session}"
-            }
+            sed 's/^/^/' "$kak_opt_spell_tmp_file" | eval "aspell --byte-offsets -a $options" 2>&1 | awk '
+                BEGIN {
+                    line_num = 1
+                    regions = ENVIRON["kak_timestamp"]
+                    server_command = sprintf("kak -p \"%s\"", ENVIRON["kak_session"])
+                }
+
+                {
+                    if (/^@\(#\)/) {
+                        /* drop the identification message */
+                    }
+
+                    else if (/^\*/) {
+                        /* nothing */
+                    }
+
+                    else if (/^$/) {
+                        line_num++
+                    }
+
+                    else if (/^[#&]/) {
+                        word_len = length($2)
+                        word_pos = substr($0, 1, 1) == "&" ? substr($4, 1, length($4) - 1) : $3;
+                        regions = regions " " line_num "." word_pos "+" word_len "|Error"
+                    }
+
+                    else {
+                        line = $0
+                        gsub(/"/, "&&", line)
+                        command = "fail \"" line "\""
+                        exit
+                    }
+                }
+
+                END {
+                    if (!length(command))
+                        command = "set-option \"buffer=" ENVIRON["kak_bufname"] "\" spell_regions " regions
+
+                    print command | server_command
+                    close(server_command)
+                }
+            '
             rm -rf $(dirname "$kak_opt_spell_tmp_file")
         } </dev/null >/dev/null 2>&1 &
     }
-- 
2.25.0

```

**Comment by nonumeros** [comment]
@lenormf  I'll test it later... thanks in advance if it works

**Comment by nonumeros** [comment]
@lenormf it made no difference. As a matter of fact, files with fewer lines prior to that patch were working. Not anymore. I'll look into it later. Thanks either way. I appreciate it.

**Comment by nonumeros** [comment]
@lenormf  just to give you a quick comparison between files with fewer and those with longer lines. Head out to https://ctan.org/tex-archive/macros/plain/base 

Therein you'll find some files with fewer lines and other files. One of those files with over seven hundred lines took more than a minute or two to get spell check going.

**Comment by nonumeros** [comment]
@lenormf  mmm... it seems as if the process `aspell` itself needs to be killed, then and only then regardless the size of the file it'd kick in

**Comment by nonumeros** [comment]
in other words 
```
   ps -a 
   kak
   ps
```
get the file invoke `spell en` or whatever dict
```
   ps -a
   kak
   sh
   sh
   sh
   aspell
   ps 
```

kill aspell  but then if you were to `ps -a`
momentarily
```
kak
sh
sh
ps
```
finally after a few seconds `ps -a`
```
kak
ps
```

**Comment by nonumeros** [comment]
> it seems as if the process aspell itself needs to be killed, then and only then regardless the size of the file it'd kick in

Allow me to reply to this self-serving monologue. The above is the first contradiction: because by killing the `aspell` process ahead of time, is only a partial fix and largely depends by the size of the file in question. e.g. first thousand lines are highlighted, or two, or three but not the rest, and since the `aspell` process was killed, good luck with the remainder :) 

I don't know anymore. Or if other problems lie ahead.
Wouldn't it be wishful thinking to have 4k buffer writes a la https://github.com/mawww/kakoune/commit/d91e017803aca3b75dbb3d1cfca26a811022c1d4

**Comment by lenormf** [comment]
On my laptop, spell-checking `plain.tex` takes ~25s with the current implementation of `spell.kak`.

With my patch, it takes ~3s.

I don't see any trailing `aspell` processes either. I'll create a PR and have it verified by other contributors, maybe there are problems with my code, but I don't see them.

**Comment by nonumeros** [comment]
>  don't see any trailing aspell processes either. I'll create a PR and have it verified by other contributors, maybe there are problems with my code, but I don't see them.

thanks again @lenormf . I 'm still having the `aspell` processes. It could be a problem in my end with two different systems
