### ISSUE TITLE
Matrix room for the project

### ISSUE THREAD

**Issue by notramo** [mawww/kakoune#3408]
Matrix aims to be the [successor of IRC](https://matrix.org/faq/#what-is-the-difference-between-matrix-and-irc%3F) (and XMPP and many other platforms). It is open source, federated, and supports Markdown formatting, images, and videos.
More and more users are switching to Matrix, so representing Kakoune in the Matrix ecosystem would be good.
I created an unofficial room: `#kakoune:grin.hu` (I will hand over the admin right to @mawww on request.)

**Comment by mawww** [comment]
i joined the room, no need to make me admin, as I said regarding discuss.kakoune.com, I am happy for the community to self organize, I dont think I need to be managing anything there.

We can add a link to that room on the website though.

**Comment by casimir** [comment]
It’s been some times now that I’m using matrix to connect to kakoune’s irc channel: #freenode_#kakoune:matrix.org
I’m quite happy with this setup and I know I’m not the only one connected using matrix there. 

@notramo is your room also bridged with irc or the one on matrix.org?
