### ISSUE TITLE
Kakrc file highlight doesn't work after updating to latest version

### ISSUE THREAD

**Issue by joeitu** [mawww/kakoune#3412]
### Steps 
Build and install kakrc from latest release ( v2020.01.16 )
fill your kakrc in ~/.config/kak/kakrc
open it with kak

### Outcome 
Text is not highlighted

### Expected 
Text is highlighted

### Additional infos
It worked before updating to latest kak version(`v2020.01.16-124-g329f291a`) previous version was unknow ( package manger bug ) 

when I open a kak file ( kakrc or *.kak ) and run `echo %opt{filetype}` I get the answer :  `kak`

**Comment by lenormf** [comment]
Is there anything in the `*debug*` buffer?

**Comment by joeitu** [comment]
Obviously! I should I thought about that 
yes there is an error:
```
error running hook WinSetOption(filetype=kak)/: 2:5: 'require-module' 3:1: 'require-module' no such module: 'sh'
```

**Comment by joeitu** [comment]
**Solved**:
I had to copy `rc/filetype/kakrc.kak` and `rc/filetype/sh.kak` in my `.config/kak/autoload` 
Opened a new question  #3415

**Comment by lenormf** [comment]
The autoload directory doesn't source any other script that isn't in it, so you need to copy all the dependencies of a given script along.

Please close this issue if your problem was solved!
