### ISSUE TITLE
How do I change the tabstop?

### ISSUE THREAD

**Issue by leliamesteban** [mawww/kakoune#3421]
Hi,

I'm trying to figure out how to use two spaces instead of 4 as indentation. I tried using `:set tabstop=2` but that doesn't work. I also tried `:doc set` but it wasn't helpful.

Also, how do I fix the indentation of a block? In vim that would be gg=G to go to the beginning of the file and fix indentation until the end.

Thank you!

**Comment by eraserhd** [comment]
To change the tabstop: `set window indentwidth 2`.  You can set this in a hook for `WinSetOption` with `filetype=perl` (or whatever) in your `kakrc`.

Kakoune relies on external programs when possible, and reformatting is one area where it does that.  Assuming you have some program `formatter`, `%|formatter<ret>`.

**Comment by mawww** [comment]
There are two different options: `tabstop` which configure the how tab characters are handled (they expand up to the next multiple of whatever column value is in there), and `indentwidth` which configure how many spaces to use for an indent level (with 0 meaning use a tab character).

"Fixing" the indentation of a block is best done by piping this block into a language specific tool that format it. it could be possible to trigger the indentation hooks again somehow, but that would likely be quite brittle.
