### ISSUE TITLE
Moving view continuously when holding keys

### ISSUE THREAD

**Issue by jkonecny12** [mawww/kakoune#343]
Now when I press `v` I can one time press `k` or `j` keys but only one time. Could it be in the way that I'm pressing the keys and the view is moving? In the same way as `k` and `j` alone working now for moving the cursor.

**Comment by mawww** [comment]
A possibility would be to use `V` as a lock in visual control mode (only `v` commands works until you press `esc`). Note that the current `v` commands never change the selection, so scrolling is limited as we need to keep the cursor visible.

What do you think ?

**Comment by jkonecny12** [comment]
I think this should be fine. 
Do I understand it right that the ``V`` command will cancel actual selection?
