### ISSUE TITLE
Focus* hooks do not work when mouse support is disabled

### ISSUE THREAD

**Issue by DanySpin97** [mawww/kakoune#3431]
### Steps 
Add the following lines to `kakrc`:

```
set-option global ncurses_enable_mouse=false
```

### Outcome 
FocusIn and FocusOut hooks stop working.

Reading the source code, focus event report is disabled by sending an escape code [here](https://github.com/mawww/kakoune/blob/6766297623e9718db5b2b09bd655fe183acdcf67/src/ncurses_ui.cc#L1268) when `ncurses_enable_mouse=false`.

**Comment by lenormf** [comment]
This bug is supposed to have been fixed by 8f30e37, everything seems to work as expected on my side with this commit.

Could you please verify that your problem has been resolved with a new build, and close this issue accordingly?

**Comment by DanySpin97** [comment]
Yea, compiling from master resolved the issue.
