### ISSUE TITLE
Allow replacing existing `number-lines` highlighters

### ISSUE THREAD

**Issue by evanrelf** [mawww/kakoune#3436]
New `number-lines` highlighters are always added to the left of the existing ones. This is problematic if you want to change a highlighter (currently only possible by adding and removing it) because it could move from the right of something to the left of something.

### Feature 

Either the ability to override an existing highlighter, given the same name and path, or the ability to specify ordering/positioning. I want line numbers to always be the leftmost highlighter.

Currently you get a "duplicate id" error when trying to use an existing name:

```
error running hook FocusIn(client0)/number-toggle: 1:2: 'number-toggle-update' 5:3: 'add-highlighter' duplicate id: 'number-toggle'
error running hook ModeChange(push:normal:insert)/: 2:3: 'number-toggle-update' 5:3: 'add-highlighter' duplicate id: 'number-toggle'
error running hook ModeChange(pop:insert:normal)/: 2:3: 'number-toggle-update' 5:3: 'add-highlighter' duplicate id: 'number-toggle'
error running hook ModeChange(push:normal:insert)/: 2:3: 'number-toggle-update' 5:3: 'add-highlighter' duplicate id: 'number-toggle'
error running hook ModeChange(pop:insert:normal)/: 2:3: 'number-toggle-update' 5:3: 'add-highlighter' duplicate id: 'number-toggle'

```

### Usecase 

I have a Kakoune plugin that changes the line numbering between absolute and relative, depending which mode you're in. This breaks other highlighters, such as from `lint` or `git show-diff`.

I have an issue in my repo here: https://github.com/evanrelf/number-toggle.kak/issues/2

But I'll copy the visualization/reproduction steps here:

### Steps to reproduce

Enter a file that has changes in Git, with the `number-toggle.kak` plugin enabled:

```
1│# test                                                                           
1│                                                                                 
2│Lorem ipsum dolor sit amet.                                                      
```

Run `git show-diff` to see the diff correctly (the `~` mark on line 3):

```
 1│# test                                                                           
 1│                                                                                 
~2│Lorem ipsum dolor sit amet.                                                      
```

Enter insert mode, triggering relative line numbers, and _breaking the Git highlighter_:

```
1│ # test                                                                           
2│                                                                                  
3│~Lorem ipsum dolor sit amet.                                     
```

Now the `~` mark on line 3 is on the right side of the line numbers, and stays there even when going back to normal mode.

![2020-03-28 22-14-20 2020-03-28 22_16_02](https://user-images.githubusercontent.com/887196/77840975-d47d0f00-7141-11ea-8bd8-10199f643e44.gif)

**Comment by evanrelf** [comment]
Thank you, @mawww!

**Comment by mawww** [comment]
No problem, thanks for the well motivated feature request.
