### ISSUE TITLE
builtin-terminal-ui: Redraw issue

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#3437]
### Steps 

iTerm2+tmux.

Type `:<esc>`.

### Outcome 

![Screen Shot 2020-03-29 at 3 04 40 PM](https://user-images.githubusercontent.com/147284/77857968-a98ccc80-71ce-11ea-821c-dbe6dd76f5ee.png)

### Expected 

menu should have been cleared.

**Comment by eraserhd** [comment]
Oh I forgot: Commit 47b7d154, "Reduce amount of SGR escapes emitted by tracking the active face", and colorscheme palenight.

**Comment by mawww** [comment]
Should be fixed now, thanks for testing that branch btw.
