### ISSUE TITLE
Newlines are encoded when passed as argument to a command

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3439]
### Steps 

Execute the following script:

```
define-command -params 1 foo %{
    echo -debug "%arg{1}"
}

foo "
        1
        2
        3
"
```

### Outcome 

```
␊        1␊        2␊        3␊
```

```
00000000  e2 90 8a 20 20 20 20 20  20 20 20 31 e2 90 8a 20  |...        1... |
00000010  20 20 20 20 20 20 20 32  e2 90 8a 20 20 20 20 20  |       2...     |
00000020  20 20 20 33 e2 90 8a 0a                           |   3....|
00000028
```

### Expected 

```
        1
        2
        3
```

**Comment by Screwtapello** [comment]
Is that "newlines are encoded when passed as argument to a command", or "`echo` encodes newlines"?

It looks like `echo` [unconditionally calls `fix_atom_text()`](https://github.com/mawww/kakoune/blob/master/src/commands.cc#L1333), which is the function that [converts control-codes to visible Unicode characters](https://github.com/mawww/kakoune/blob/master/src/display_buffer.cc#L321).

**Comment by lenormf** [comment]
Actually my usecase is closer to the following:

```
define-command -params 1 foo %{
    b *scratch*
    exec ge \ o "%arg{1}"
}

foo "
        1
        2
        3
"
```

This results in all newline characters being stripped away:

```
00000000: 2020 2020 2020 2020 3120 2020 2020 2020          1       
00000010: 2032 2020 2020 2020 2020 330a             2        3
```

**Comment by Screwtapello** [comment]
If I start `kak -n` and execute:

    :exec ge \ o %sh{printf 'a b\nc'} <esc>

...then at the bottom of the buffer I get the line:

    a bc

...which is to say, a space is preserved and a newline isn't. On the other hand, if I execute:

    :reg a %sh{printf 'a b\nc'}
    :exec ge '"' a p

...then as expected, at the bottom of the buffer I get:

    a b
    c

**Comment by lenormf** [comment]
Still, I want command argument expansions to be usable as-is, without workaround.

**Comment by lenormf** [comment]
Hardcoding the string yields the same results, it seems that the issue is not related to expansions, but to how `exec` behaves with multi-line strings.

```
b *scratch*
exec "ge \ o 1
2
3"
```
