### ISSUE TITLE
spell es returns error running command 'fail "+ usar"

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#3449]
This was tested with the latest revision..

Invoking `spell es` simply returns `error running command 'fail "+ usar"` and nothing else happens.

At one point and as I mentioned at https://github.com/mawww/kakoune/issues/3399#issuecomment-596896201 I had - what seemed  like conflicting instances of kak that somehow were running sh processes on the background. This issue wouldn't get resolved until after `aspell` was successfully killed. ~~This is no longer the case.~~ I just thought of mentioning it here for reference while I encountered the current problem, that didn't come up, until I resolved the prior  conflict. 

There is only so much I can do to go back and check what revision did it... So far https://github.com/mawww/kakoune/releases/tag/v2019.12.10 returns similar messages but unlike the current revision, it seems to work

**Comment by lenormf** [comment]
Duplicate of #3254.

When the language pack is not installed on the system, I get the expected error message printed in the debug buffer (it's just not printed on the UI, c.f. issue above):

```
error running command 'fail "Error: No word lists can be found for the language ""es""."
': Error: No word lists can be found for the language "es".
```

**Comment by nonumeros** [comment]
Thanks for looking into this @lenormf  

I'm getting the exact - well, not exactly the same, but an error nonetheless with`error: no word lists can be found for the language "en-US" under Emacs.. But guess what? It's not an error, because en-US it's not installed :)  

So I installed the French language pack for aspell and guess what?

Now it's recognizing both English and Spanish words indiscriminately. 

Now when I type `muchas gracias` in french, it recognizes them as French.

But then I type: `de nada` and it doesn't.

**Comment by lenormf** [comment]
Could you please exactly what the problem is, using the default issue template?

### Steps 

How to reproduce the issue, step by step.

List of minimal set of conditions that need to be met to reproduce the problem: options, software, versions etc.

### Outcome 

What happens as a result of executing the above steps, within the given conditions.

How was the outcome checked? Commands used etc.

### Expected 

What should have happened.

**Comment by nonumeros** [comment]
**Steps**

latest revision ceff2286
Install aspell-fr only (will install aspell along with it)
$kak spell fr

**Outcome**

```
*** this is a *scratch* buffer which won't be automatically saved ***
*** use it for notes or open a file buffer with the :edit command ***

muchas gracias 
```
![Screenshot from 2020-04-28 01-31-43](https://user-images.githubusercontent.com/11535575/80463789-cbc95580-8906-11ea-80d7-5b8648d2de88.png)

**Expected**

recognize all words both in Spanish and English

**Comment by nonumeros** [comment]
@lenormf  you mentioned something about UI and i have no clue what you're referring to.

What's so hard to understand here? If I were  not using any UI I would have the same results than above. And as I said, it follows Emacs shouldn't behave any differently .

Also and as I've said before If I were to

   ps -a

It'd show the background processes with large `tex` files. Nothing's changed here.

aspell recognizes some but not all, as it should.

**Comment by nonumeros** [comment]
I suspect this has nothing to do with kak @lenormf sorry. I'll close it. Reopen it if you want... but I don't think there's nothing here. If aspell is behaving the same by itself then it can't be kak's
