### ISSUE TITLE
Edit the zsh buffer with kakoune

### ISSUE THREAD

**Issue by blueray453** [mawww/kakoune#3458]
If we hit `Ctrl-x Ctrl-e` (`Ctrl-x e` also works) zsh will launch `$VISUAL` or `$EDITOR`, allowing you to edit the current command to your hearts content, and once you save & close your editor’s window, ZSH will execute your command.

For this to work you have to put the following lines in `.zshrc`:

```
# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line
```

You can learn more about it on:

https://nuclearsquid.com/writings/edit-long-commands/
https://hunden.linuxkompis.se/2018/08/19/edit-your-zsh-buffer-with-your-editor-of-choice.html

How can we use kak instead of vim or emacs for this feature?

**Comment by krobelus** [comment]
> zsh will launch `$VISUAL` or `$EDITOR`

So use `EDITOR=kak`. This works just like with any other editor, there is nothing special to do for Kakoune here.
