### ISSUE TITLE
Capture trailing newline in shell expansion.

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#3470]
If I have a file `test.txt` with three newlines in it, and I run `:reg dquote %sh{cat ~/.clipboard}`, the `"` register is empty. Whereas if I select three newlines in kakoune and yank them with `y`, and then do `:echo %reg{"}`, I have `␤␤␤`. How can I get these newlines into the register as a result of a shell expansion?

**Comment by enricozb** [comment]
I realize that subshells automatically trail newlines, and Kakoune has either also decided to do that or is using a POSIX subshell which is trailing the newlines. However, even if I append a dummy `x` to the end of my shell output to then be "discarded" later won't work because Kakoune has no built-in string manipulation tools.

So I figure some solution with the pipe keys might work, but I can't think of anything at the moment.

**Comment by enricozb** [comment]
Here is what I ended up with. Hopefully there is a better way to do this...
```
printf "%s" ": edit -scratch *clip*<ret>"
printf "%s" "|cat ~/.clipboard<ret>"
printf "%s" "%Hy";
printf "%s" ": delete-buffer *clip*<ret>";
```

**Comment by Screwtapello** [comment]
Can you do something like:

    reg dquote %file{/path/to/.clipboard}

I *think* `%file{}` expands to the contents of the named file without stripping whitespace; unfortunately it requires an absolute path and doesn't support abbreviations like `~` for `$HOME`.

**Comment by enricozb** [comment]
@Screwtapello This is absolutely the right way to do it. If I wanted a relative path I could just do
```
eval %sh{
  dir=$(echo ~/.clipboard);
  printf "%s" "reg dquote %file{$dir}"
}
```
Thanks a ton
