### ISSUE TITLE
Crash when selecting to sentence start on the last empty line

### ISSUE THREAD

**Issue by yuchenshi** [mawww/kakoune#3472]
(BTW, thanks for this awesome project! I've been using it for quite a few months now and I can totally feel a boost in productivity. I love it.)

### Steps 

FYI, I'm using a corp Linux distro based on Debian.

1. On current master (2fca4e564304ee69b33711084ceeefae397619cd): `make debug=yes`
2. In `src`, run `./kak.opt -n`
3. Replace all text with below (e.g. `%ca<ret><esc>`):

```
a

```

That is the letter `a` on the first line followed by an empty line.
4. With the cursor on the second empty line, press `[s` (select to object start, sentence)
5. Kak will crash at this point with SIGSEGV. If not, press `l` and then it definitely crashes.

### Outcome/Stacktrace 

```
Received SIGSEGV, exiting.
Pid: 225585
Callstack:
./kak.opt(Kakoune::Backtrace::Backtrace()+0x18) [0x55b9c44fb908]
./kak.opt(Kakoune::signal_handler(int)+0x4c) [0x55b9c45dcf2c]
/lib/x86_64-linux-gnu/libc.so.6(+0x39fe0) [0x7f0d28102fe0]
./kak.opt(Kakoune::get_column(Kakoune::Buffer const&, Kakoune::ColumnCount, Kakoune::BufferCoord)+0x1f) [0x55b9c450b30f]
./kak.opt(Kakoune::Window::compute_display_setup(Kakoune::Context const&) const+0x190) [0x55b9c46a2010]
./kak.opt(Kakoune::Window::update_display_buffer(Kakoune::Context const&)+0x1d8) [0x55b9c46a39f8]
./kak.opt(Kakoune::Client::redraw_ifn()+0x1de) [0x55b9c451126e]
./kak.opt(Kakoune::ClientManager::redraw_clients() const+0x24) [0x55b9c4514234]
./kak.opt(Kakoune::run_server(Kakoune::StringView, Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, Kakoune::ServerFlags, Kakoune::UIType, Kakoune::DebugFlags, Kakoune::ArrayView<Kakoune::StringView const>)+0xa20) [0x55b9c45e6250]
./kak.opt(main+0x1829) [0x55b9c44f9709]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f0d280efbbb]
./kak.opt(_start+0x2a) [0x55b9c44fa10a]
```

I think this may be caused by `[s` putting the cursor on an invalid position (likely after the last line), but I'm not an expert here.

**Comment by mawww** [comment]
Thanks for the clear bug report, fix incoming.

**Comment by yuchenshi** [comment]
Thanks for the quick fix. I can confirm it does not crash any more on master. Thanks again for this awesome project!
