### ISSUE TITLE
Kakoune on Arch Weird Characters

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#3477]
So, I have a fresh archlinux install with no Xserver or wayland running. When I run kakoune I get a bunch of ~T~B and ~T~@ where I expect the "special" characters like the vertical bars near the line numbers and the characters used to draw clippy.

Any idea what's going on?

**Comment by Delapouite** [comment]
Hello. Looks like you're experiencing a locale issue, similar to : https://github.com/mawww/kakoune/issues/2471

**Comment by enricozb** [comment]
Yep that was it. I had no Locale set. Thanks!
