### ISSUE TITLE
Range highlighter behaves differently depending on how range was specified.

### ISSUE THREAD

**Issue by SolitudeSF** [mawww/kakoune#3479]
`1.1+0|default,rgb:aaaaaa` will highlight no character, while
`1.1,1.1|default,rgb:aaaaaa` will highlight one. `1.1+1|default,rgb:aaaaaa`, highlights two, as expected.

**Comment by mawww** [comment]
I think the two firsts are behaving as expected, while the last one should only highlighting a single character, as the +... syntax contains the length, but from your wording it seems you assume that third option is behaving correctly.

**Comment by SolitudeSF** [comment]
i dont know how they should behave, just that one of them is wrong.
