### ISSUE TITLE
[builtin-terminal-ui] Support the iTerm2 "synchronised updates" feature

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#3482]
One of the potential problems with the builtin-terminal-ui branch is that most terminals don't provide a way for the application to signal that it's repainting the display, so there's a good chance that the the terminal will repaint *its* display halfway through, and then again once the application update has finished, leading to distracting flickering.

The most portable approach to this problem is to just ensure repaints are as concise as possible, but since there's no guaranteed maximum atomic size, and since repaints can be arbitrarily large, this is not a solution.

iTerm2 supports a [synchronised update control sequence](https://gitlab.com/gnachman/iterm2/-/wikis/synchronized-updates-spec). The linked specification has more details, but it basically amounts to:

  - send `ESC P = 1 s ESC \` when a repaint begins
  - send `ESC P = 2 s ESC \` when a repaint ends

Currently, iTerm2 is the only terminal to support this feature, other terminals should ignore it without incident. In that respect, it's like the "enable focus in/out events" sequence Kakoune already uses.

According to [tmux's maintainer](https://github.com/mintty/mintty/issues/881#issuecomment-628475165), tmux only [sends these sequences](https://github.com/tmux/tmux/blob/31621036ad38ef3a2d88da838eb021430ea3c944/tty.c#L1437-L1465) to the outer terminal and does not implement them for the inner terminal, "but I will do that as soon as there are some programs apart from tmux that use it..."

**Comment by occivink** [comment]
Other terminals than iTerm2 support this as well
https://github.com/kovidgoyal/kitty/issues/2145#issuecomment-556726764

**Comment by mawww** [comment]
Done.
