### ISSUE TITLE
options from fzf plugin not being loaded.

### ISSUE THREAD

**Issue by in42** [mawww/kakoune#3491]
### Steps 
My kakrc:
```
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/fzf.kak"

map global normal <c-p> ': fzf-mode<ret>'

set-option global fzf_file_command 'fd' # 'rg', 'ag', 'fd', or 'find'

set global grepcmd 'rg --column --smart-case'

hook global KakEnd .* %{ echo -to-file .kak_history -quoting kakoune reg : %reg{:} }
hook global KakBegin .* %{ try %{ source .kak_history } }
```

### Outcome 
I am getting error: `'set-option' option not found: 'fzf_file_command'. Use declare-option first`. The fzf_file_command option is not recognized. Otherwise fzf.kak is working correctly so the plugin is getting loaded.
Using the prompt, I can see none of fzf options are being loaded.

**Comment by lenormf** [comment]
Did you create an issue on `plug`'s repository first? It's not self-evident that the editor is to blame when the first line of your reproducer uses a third-party script.

**Comment by in42** [comment]
This was solved [here](https://gitlab.com/andreyorst/plug.kak/-/issues/82). The issue was due to lazy loading of fzf.kak.

**Comment by allumik** [comment]
Sorry to reopen, but the link is broken and could not find the issue in fzf.kak. Care to reshare?

**Comment by in42** [comment]
The repository seems to no longer on gitlab.

**Comment by FourtyTwo042** [comment]
(I thought it would be better to have the solution in one place)
@allumik 
Since modules are lazy loaded, one must explicitly state that the configuration must be sourced when the module is activated. This can be done using the `ModuleLoaded` hook,
```
hook global ModuleLoaded fzf %{
    set-option global fzf_tmux_height '20'
}
```
you can also specify it using the `config` block for the plugin,
```
plug "andreyorst/fzf.kak" config %{
    set-option global fzf_tmux_height '20'
}
```

**Comment by allumik** [comment]
Thanks for resolving this!

I tried them and `ModuleLoaded` hook worked for me, but `config` block still gave me errors. As I did not want to make another block, I found this 

```
plug "andreyorst/fzf.kak" require-module fzf %{
  set-option global fzf_file_command 'fdfind -H' # 'ag', 'fd', or 'find'
}
```

which works and does not give any errors, although I do find it a bit weird syntatically to install and require the loading of the same module in the same command.
