### ISSUE TITLE
xi backend

### ISSUE THREAD

**Issue by heyakyra** [mawww/kakoune#3496]
Open this to track the idea, but unlikely to be implemented here because of the sheer amount of work required and also:

>I think the Xi model is misguided, I think in a way it is too technology centric. I dont think users care about 16ms vs 20ms.. What is important is that it "feels" instant, and that whenever it does not, the user can have an intuition it wont in advance.

https://github.com/mawww/kakoune/issues/2454#issuecomment-444682741

(although this seems to be a moot point since xi says nothing about front-end user experience)

### Feature 

Kakoune's model and keybindings could be implemented on top of xi—no need to sacrifice speed and reliability for usability or vice versa. Many in the xi community seem to greatly appreciate the kak concept:
> I don't have a solid of the xi-core yet but I would be interested in working on a kakoune mode. For me it feels way more compatible with a multiple-cursor workflow.

https://github.com/xi-editor/xi-editor/issues/302#issuecomment-302539140

and I also filed a ticket to implement this in xivi:
https://github.com/Peltoche/vixi/issues/18

**Comment by Delapouite** [comment]
Hi heyakyra.

Here's a previous discussion about Xi starting from the exact same quote you mention in your post: https://discuss.kakoune.com/t/feelings-about-xi/217

It's dated from December 2018, and I must admit I didn't much pay attention as closely to recent Xi development. From what I understand, the core team is now focusing on the druid project, is that the case? https://github.com/xi-editor/druid

**Comment by LiHRaM** [comment]
@Delapouite: Correct. The focus shifted a while back, and I suspect it won't be coming back for the foreseeable future. For example: https://twitter.com/raphlinus/status/1262054785756192768.

**Comment by heyakyra** [comment]
The experiment was a bit too challenging for the resources available: https://github.com/xi-editor/xi-editor/issues/1187#issuecomment-491473599
