### ISSUE TITLE
register expansion in command-line (prompt) does not fit well with multiple selections

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#35]
Example:

```
╭───────────╮
│ foobar    │ n: bar
│ ‾‾‾‾‾‾    │
│ bazqux    │ n: qux
│ ‾‾‾‾‾‾    │
╰───────────╯
```

→ `s` `%reg{n}`

```
╭───────────╮
│ foobar    │ n: bar
│    ‾‾‾    │
│ bazqux    │ n: qux
│    ‾‾‾    │
╰───────────╯
```

We can always have the values of main register by executing

→ `s` `<c-r>n`

Instead of

→ `s` `%reg{n}`

**Comment by lenormf** [comment]
Are patterns supposed to be expanded at all during a `select` ? If not, I think this issue can be closed.

**Comment by mawww** [comment]
not sure what we can do about that, closing.
