### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by ekie** [mawww/kakoune#350]
assert failed: 'uncaught exception (N7Kakoune13assert_failedE):         
assert failed "m_buffer->is_valid(m_range.end)" at display_buffer.cc:72
[Debug Infos]
pid: 2443
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x4d92a8]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2b) [0x4d6f1b]
kak(_ZN7Kakoune11DisplayLine5splitEN9__gnu_cxx17__normal_iteratorIPNS_11DisplayAtomESt6vectorIS3_NS_9AllocatorIS3_LNS_12MemoryDomainE7EEEEEENS_9ByteCoordE+0x1ba) [0x4a273a]
kak() [0x500508]
kak(_ZN7Kakoune20highlight_selectionsERKNS_7ContextENS_14HighlightFlagsERNS_13DisplayBufferENS_11BufferRangeE+0x15e) [0x50405e]
kak(_ZN7Kakoune16HighlighterGroup9highlightERKNS_7ContextENS_14HighlightFlagsERNS_13DisplayBufferENS_11BufferRangeE+0x50) [0x4699a0]
kak(_ZN7Kakoune6Window21update_display_bufferERKNS_7ContextE+0x437) [0x4a8267]
kak(_ZN7Kakoune6Client10redraw_ifnEv+0x106) [0x4e1446]
kak(_ZNK7Kakoune13ClientManager14redraw_clientsEv+0x24) [0x52b8a4]
kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0x9fc) [0x4b519c]
kak(main+0xd51) [0x456711]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f0dbb0a9790]
kak(_start+0x29) [0x459d69]
'
pid: 8459
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x4d92a8]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2b) [0x4d6f1b]
kak(main+0x113d) [0x456afd]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f0dbb0a9790]
kak(_start+0x29) [0x459d69]
➜  src git:(tupfile) ✗ a^6a^6a^6a^6terminate called after throwing an instance of  Kakoune::assert_failed'

**Comment by mawww** [comment]
This is probably due to a selection function selecting the buffer end (one past last char), when it happen again, can you post the last command you did ?

**Comment by lenormf** [comment]
It's happened to me several times as well, never could reproduce it predictably. The time it happened, I was scroll down with my touchpad down a buffer (the crash happened after the buffer scrolled down), and I had no selection.

**Comment by ekie** [comment]
just had a crash, tried to scroll the output from an external process within a fifo buffer and got this:

Received SIGSEGV, exiting.
Pid: 21515
Callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x4d92a8]
kak(_Z14signal_handleri+0x174) [0x4b0ff4]
/usr/lib/libc.so.6(+0x335b0) [0x7f9469d245b0]
kak(_ZNK7Kakoune6Buffer9char_nextENS_9ByteCoordE+0x17) [0x4cbb37]
kak(_ZN7Kakoune20highlight_selectionsERKNS_7ContextENS_14HighlightFlagsERNS_13DisplayBufferENS_11BufferRangeE+0x1c3) [0x5040c3]
kak(_ZN7Kakoune16HighlighterGroup9highlightERKNS_7ContextENS_14HighlightFlagsERNS_13DisplayBufferENS_11BufferRangeE+0x50) [0x4699a0]
kak(_ZN7Kakoune6Window21update_display_bufferERKNS_7ContextE+0x437) [0x4a8267]
kak(_ZN7Kakoune6Client10redraw_ifnEv+0x106) [0x4e1446]
kak(_ZNK7Kakoune13ClientManager14redraw_clientsEv+0x24) [0x52b8a4]
kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0x9fc) [0x4b519c]
kak(main+0xd51) [0x456711]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f9469d11790]
kak(_start+0x29) [0x459d69]

**Comment by mawww** [comment]
Hopefully, d19df5d5de5672a4a735824b2da311990fb5d170 will give you an assert earlier, allowing to pin point the faulty code.

**Comment by lenormf** [comment]
Hi,

Just had an issue whenever I resized a window, and it seems that it is linked to the issue described here.

```
assert failed "&buffer() == &context.buffer()" at window.cc:91
[Debug Infos]
pid: 24173
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x500348]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2b) [0x4febeb]
kak(_ZN7Kakoune6Window21update_display_bufferERKNS_7ContextE+0x169) [0x4c5889]
kak(_ZN7Kakoune6Client10redraw_ifnEv+0x106) [0x5084e6]
kak(_ZNK7Kakoune13ClientManager14redraw_clientsEv+0x24) [0x54f0c4]
kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0x9fc) [0x4d29cc]
kak(main+0xd51) [0x456711]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7fe684da3790]
kak(_start+0x29) [0x459d69]
```

The function calls stacks are similar, and d19df5d supposedly stops the execution flow earlier now, so that might be it.

How to reproduce it:
* Open a buffer
* Do anything that will make the autoinfo popup window be displayed (autoinfo set to 2)
* Resize the window

I got the stacktrace on my ~10th try, sometimes I get a memory corruption warning, sometimes the process just stops, and the rest of the time the window turns black and I can't even ^C the process. The window resizing might need to be a bit brutal for the bug to be triggered (resize down to the smallest window possible).

**Comment by lenormf** [comment]
Second stacktrace that might be related to the issue as well:
```
assert failed: 'uncaught exception (N7Kakoune13assert_failedE):
assert failed "buffer.is_valid(sel.anchor())" at selection.cc:393
[Debug Infos]
pid: 18774
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x500348]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2b) [0x4febeb]
kak(_ZNK7Kakoune13SelectionList15check_invariantEv+0x135) [0x4ebe15]
kak(_ZN7Kakoune13SelectionListC2ERNS_6BufferENS_9SelectionEm+0x272) [0x4ec772]
kak(_ZN7Kakoune13SelectionListC1ERNS_6BufferENS_9SelectionE+0x8f) [0x4ec98f]
kak(_ZN7Kakoune10InputModes12MouseHandler10handle_keyENS_3KeyERNS_7ContextE+0x145) [0x4877f5]
kak(_ZN7Kakoune10InputModes6Normal6on_keyENS_3KeyENS_9InputMode9KeepAliveE+0x4b) [0x48a4bb]
kak(_ZN7Kakoune12InputHandler10handle_keyENS_3KeyE+0x248) [0x482e58]
kak(_ZN7Kakoune6Client22handle_available_inputENS_9EventModeE+0xb5) [0x508d15]
kak() [0x551079]
kak(_ZN7Kakoune9FDWatcher3runENS_9EventModeE+0x31) [0x4c8cf1]
kak(_ZN7Kakoune12EventManager18handle_next_eventsENS_9EventModeEP10__sigset_t+0x3f9) [0x4c9469]
kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0xa0c) [0x4d29dc]
kak(main+0xd51) [0x456711]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7fb574642790]
kak(_start+0x29) [0x459d69]
'
pid: 24693
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x500348]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2b) [0x4febeb]
kak(main+0x113d) [0x456afd]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7fb574642790]
kak(_start+0x29) [0x459d69]
```
I have no idea how to reproduce this one, as I was just scrolling down a buffer that had been open for ~3 hours.

**Comment by mawww** [comment]
2eced81753146018fe3470547a8060b595e5da88 should fix that, hopefully ;)

**Comment by lenormf** [comment]
I just had the same issue described in https://github.com/mawww/kakoune/issues/350#issuecomment-129175221.

The stacktrace is the exact same one.
