### ISSUE TITLE
invalid utf-8 on snippet completion with kak-lsp

### ISSUE THREAD

**Issue by kanashimia** [mawww/kakoune#3507]
This happens on newest versions [v2020.01.16-219-g0cbc4f21]
Tested against kak v2020.01.16
### Steps 
Try to complete snippet, for example texlabs `\beg`

### Outcome 
Only inserts `\begin{`, and error occurs:
```emacs
Error: 1:1: 'eval' 4:1: 'lsp-snippets-insert-completion' 1:2: 'eval' 3:5: 'exec' Invalid utf8 in regex
```

### Expected 
No error, and correct snippet:
```tex
\begin{}

\end{}
```

**Comment by lenormf** [comment]
Have you reported this issue to the maintainers of kak-lsp? There's not much to go on here, since the reproducer uses a third-party plugin and only shows an error.

I reckon the issue comes from `lsp-snippets-insert-completion` inserting a single backslash character `\`, which results in the weird error message.

**Comment by kanashimia** [comment]
Ok i've found the issue, the problem was in this line `exec -draft "<a-;><a-/>%val[main_reg_a]<ret>d"`, specifically `%val[main_reg_a]` part. For some reason it's behavior has changed between versions.
After replacing this with `%reg{a}` everything works ok.

The question is: is this intentional?
<details> <summary>original code of 'lsp-snippets-insert-completion'</summary>

```
# First param is the text that was inserted in the completion, which will be deleted
# Second param is the actual snippet
def -hidden lsp-snippets-insert-completion -params 2 %{ eval -save-regs "a" %{
    reg 'a' "%arg{1}"
    exec -draft "<a-;><a-/>%val[main_reg_a]<ret>d"
    eval -draft -verbatim lsp-snippets-insert %arg{2}
    remove-hooks window lsp-post-completion
    hook -once -group lsp-post-completion window InsertCompletionHide .* %{
        try %{
            lsp-snippets-select-next-placeholders
            # On the next key, start replacing the placeholder contents
            on-key %{ exec "<esc>c%val{key}" }
        }
    }
}}
```

</details>

**Comment by krobelus** [comment]
So the issue is that expansion of double quoted `%val{...}` changed:

```
set-register a '\begin'

echo "%val{main_reg_a}"
# prints "\\begin" on master
# prints "\begin" in Kakoune v2020.01.16

# However, an unquoted version always prints the same
echo %val{main_reg_a}
# prints "\begin" in both, just like echo "%reg{a}"
```

This is introduced by 0a66eb9c47ba9a7d3b90286d66a70b5bd7eee15a which made `%val{...}` expand to a list of strings (as noted in the changelog). I don't fully understand how that works yet, but this shows some difference:

```
echo %val{buflist}
# prints "*debug* *scratch*" on master
# prints "'*debug*' '*scratch*'" in Kakoune v2020.10.16
```
