### ISSUE TITLE
Double ESC going missing

### ISSUE THREAD

**Issue by arachsys** [mawww/kakoune#3511]
When I use Kakoune over an ssh link doing remote admin chores (i.e. with a bit of latency and consequent input bunching), I often get bitten when I leave insert mode with ESC, then press an arrow key (bad habit!) in quick succession.

For example, having inserted

    Mary had a little lamb in /etc/passwd

I press ESC quickly followed by <-, but unexpectedly remain in insert mode with

    Mary had a little lamb in /etc/passwd[D

The double ESC in the sequence \\[\\[[D which Kakoune receives is getting completely elided.

I can also demonstrate this by tapping ESC twice quickly in succession while in insert mode: instead of exiting to normal mode, I remain in insert mode.

(NB for casual readers: this isn't the tmux escape-time behaviour described in the FAQ. There is no tmux or screen in the loop here; it's Kakoune's own ESC handling that swallows double-ESC.)

It's easy to see why this happens: at the end of NCursesUI::get_next_key() we have

    if (*c != 27)
        return parse_key(*c);

    if (auto next = get_char())
    {
        if (*next == '[') // potential CSI
            return parse_csi().value_or(alt('['));
        if (*next == 'O') // potential SS3
            return parse_ss3().value_or(alt('O'));
        return alt(parse_key(*next));
    } 
    return Key{Key::Escape};

to handle the ESC and ESC+something cases, including arrows and alt-X.

This will dispatch double ESC as alt(parse_key(27)) which doesn't do anything.

Locally, I've hacked alt-ESC -> ESC with

    --- a/src/ncurses_ui.cc
    +++ b/src/ncurses_ui.cc
    @@ -783,7 +783,8 @@ Optional<Key> NCursesUI::get_next_key()
                 return parse_csi().value_or(alt('['));
             if (*next == 'O') // potential SS3
                 return parse_ss3().value_or(alt('O'));
    -        return alt(parse_key(*next));
    +        if (*next != 27)
    +            return alt(parse_key(*next));
         }
         return Key{Key::Escape};
     }

which stops it catching me out as I at least end up in the right mode and with an unmodified buffer. (Alas one can't just map \<a-esc> in the UI as far as I can tell?)

Ideally, I'd like to fix this properly: to return Key{Key::Escape} for the first ESC and leave the second one to be interpreted as part of a sequence (or not) by the next get_next_key() call. However, it's not obvious to me how to do this cleanly/elegantly without butchering the structure here.

PS: I am aware that ESC followed by a random key can't be disambiguated in general -  is ESC i received in fast succession really \<a-i> or ESC followed by i? But at least in the case of ESC followed by an arrow key, there's only one interpretation as even alt-arrow is not sent with a double-ESC sequence.

[Edited to escape '\\' and '\<' characters against unintended Markdown interpretation by GitHub!]

**Comment by Screwtapello** [comment]
> Alas one can't just map <a-esc> in the UI as far as I can tell?

Pressing Alt+Esc does indeed send `^[^[`, and if I do `set -add global debug keys` and press Alt-Esc, Kakoune logs:

    Client 'client0' got key '<a-�>'

...which I assume means that Kakoune failed to decode the second `^[` byte as `<esc>` and just assumed it was a printable character. Sure enough, if I type:

    :map global normal <a-^V^[> ": echo alt-esc<ret>"

(that is, typing `^V^[` at the prompt to enter a literal `^[`, which gets displayed as `␛`) then I can press Alt-Esc and see "alt-esc" displayed in the status line.

So: you can't map `<a-esc>`, but only because of a bug in Kakoune, not because it's an impossible sequence. It's still a very unlikely sequence, though, so maybe it's worth Kakoune special-casing `^[^[` to be an Esc followed by another sequence, since that's more likely to be useful?

**Comment by arachsys** [comment]
Aha, many thanks for the pointer to `global debug keys` - that makes it much easier to see what's going on.

Interesting, so an alternative bodge to my one would have been to fix the handling of \<a-esc> in alt() in get_next_key() with something like:

    --- a/src/ncurses_ui.cc
    +++ b/src/ncurses_ui.cc
    @@ -607,6 +607,8 @@ Optional<Key> NCursesUI::get_next_key()
             }
             if (c < 27)
                 return ctrl(Codepoint(c) - 1 + 'a');
    +        if (c == 27)
    +            return {Key::Escape};
             if (c == 127)
                 return {Key::Backspace};

and then `:map global insert <a-esc> <esc>` ? I just checked this and it does indeed work equivalently.

In fact, that patch seems to fix the 'ESC then arrow' behaviour even without remapping <a-esc> to <esc> although I don't immediately understand why. (I'll have to investigate more: possibly it's just that my connection latency is a bit lower right now.)

As you say, it would be nicer to actively handle ESC ESC \<keys>  as ESC followed by ESC \<keys> but I guess the feasibility of that depends on whether it's reasonable to implement given the current shape of the code.

**Comment by arachsys** [comment]
Late follow-up, but this problem has gone away completely for me since the terminal-ui branch was merged to replace ncurses. I can no longer reproduce the effect, even on artificially high latency connections.
