### ISSUE TITLE
Output messes up after some arbitrary inputs

### ISSUE THREAD

**Issue by marknikky** [mawww/kakoune#3512]
As the title states, after writing some text the characters,  cursor mess up.
This started to happen after updating the editor.
I'm using Gentoo and recently updated app-editors/kakoune-0_pre20171120 to app-editors/kakoune-2020.01.16.
I will post some screenshots and try to tell what is happening.

![2020-05-28-183440_198x86_scrot](https://user-images.githubusercontent.com/58032212/83162057-e9f6c100-a111-11ea-9f48-c4dfad734dcf.png)

After inserting the exclamation mark word 'prin' duplicates and something weird happens.

![2020-05-28-183523_295x105_scrot](https://user-images.githubusercontent.com/58032212/83162135-009d1800-a112-11ea-8523-1ad838699534.png)

After trying navigating this line with my cursor, more weird magic happens.

![2020-05-28-183705_230x83_scrot](https://user-images.githubusercontent.com/58032212/83162379-5bcf0a80-a112-11ea-91c8-9ae0d158dbf5.png)

I tried switching terminal emulators (alacritty to st). Still happening.
I tried switching window manager (bspwm to dwm). Still happening.
I honestly don't know what is the source of the issue.

**Comment by Screwtapello** [comment]
Alacritty and st are both pretty new and unpolished terminal emulators. Can you reproduce the behaviour inside standard `xterm`, with `$TERM` set to `xterm-256color`?

**Comment by marknikky** [comment]
Thanks for responding. Unfortunately changin `$TERM` to `xterm-256color` didn't solve the issue.

**Comment by lenormf** [comment]
Can you reproduce the issue in Tmux? What about other editors? Seems similar to #3316 (which also involved Gentoo).

**Comment by marknikky** [comment]
Alright it seems like using `xterm` along with `xterm-256color` doesn't reproduce the issue. I tried to use `xterm-256color` with other terminals like `st` and `alacritty`. It didn't work.
I tried `nvim` and didn't encounter this issue.

**Comment by lenormf** [comment]
Could you compile the `builtin-terminal-ui` branch? I reckon you won't have any problems with it, and that this is an Ncurses issue (can't prove it though).

**Comment by marknikky** [comment]
Sorry, I'm not an advanced user. Fairly new to Gentoo so I don't know how to manage outside of my package manager.

**Comment by Screwtapello** [comment]
These symptoms are pretty typical of `$TERM` not matching the terminal you're actually using - the terminal expects one thing, and `$TERM` tricks Kakoune into doing things a different way, and as a result weird things happen.

Inside genuine xterm, use `xterm-256color`.

Inside st, use `st-256color`.

Inside tmux, use `tmux-256color`.

Inside alacritty, use `alacritty` (apparently it always supports 256-color mode, so it doesn't need a special 256-color variant).

**Comment by mawww** [comment]
It does seem this is not a Kakoune but ncurses/terminfo issue, nothing we can really fix in Kakoune, the `builtin-terminal-ui` branch should help.
