### ISSUE TITLE
Clojure linting with Joker

### ISSUE THREAD

**Issue by w33tmaricich** [mawww/kakoune#3518]
Hey! Quite a while ago I created a simple script that could be used to add Clojure linting support with joker. I’ve been using it for years and it works well. I just noticed on the wiki with links to different linters and configs there wasn’t a Clojure entry. Here’s the link to my repo, feel free to add it if you’d like. 

https://github.com/w33tmaricich/clj-kakoune-joker

**Comment by lenormf** [comment]
I edited the [Languages](https://github.com/mawww/kakoune/wiki/Languages) and [Lint](https://github.com/mawww/kakoune/wiki/Lint) pages accordingly.

Note that the wiki is world-editable, feel free to complement it with relevant info!
