### ISSUE TITLE
Mac OS: Kitty won't open new window in detached session

### ISSUE THREAD

**Issue by basbebe** [mawww/kakoune#3530]
If I open a detached session in kitty and try to open a new kakoune editor with `:new`, nothing happens.

`*debug*`:
```
remote client connected: 4
shell stderr: <<<
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 121, in <module>
  File "kitty/__main__.py", line 117, in main
  File "kitty/__main__.py", line 23, in remote_control
  File "kitty/remote_control.py", line 187, in main
  File "kitty/remote_control.py", line 132, in do_io
  File "kitty/utils.py", line 415, in __enter__
OSError: [Errno 5] Input/output error
>>>

```

opening new windows from 'attached' sessions works, though…

**Comment by lenormf** [comment]
This is an error produced by Kitty. Have you created an issue on the relevant repository, or is there additional information you haven't added yet to this report that shows Kakoune has a bug?

**Comment by basbebe** [comment]
> This is an error produced by Kitty. Have you created an issue on the relevant repository, or is there additional information you haven't added yet to this report that shows Kakoune has a bug?

not yet.

Since it works woth attached sessions and there had been a similar bug with tmux, I thought it would be a problem with kakoune.

**Comment by basbebe** [comment]
I don't know if this is related but kakouine uses `kitty @ new-window` which is legacy.

Documentation states to use `kitty @ launch` instead.

**Comment by DERPSQUID9** [comment]
@basbebe By default, `allow_remote_control` in kitty.conf is set to `no`. Have you tried setting it to `yes`? It fixed the issue for me, although I use Linux.

**Comment by basbebe** [comment]
`allow_remote_control` already was set to yes – opening windows from 'attached' sessions works.

In the current version, kakoune doesn/t throw an error but I get a `waiting for shell command to finish` line which never stops counting.
The client and the session become unresponsive.

**Comment by basbebe** [comment]
this still happens for me:

```sh
❯ $SHELL -c 'kak -s bark -d &; echo "bark" '
bark

❯ kak -c bark
```

`:new`

```console
remote client connected: 4
shell stderr: <<<
Traceback (most recent call last):
  File "lib/python3.8/runpy.py", line 282, in run_path
  File "lib/python3.8/runpy.py", line 87, in _run_code
  File "__main__.py", line 127, in <module>
  File "__main__.py", line 123, in main
  File "__main__.py", line 23, in remote_control
  File "kitty/remote_control.py", line 188, in main
  File "kitty/remote_control.py", line 132, in do_io
  File "kitty/utils.py", line 429, in __enter__
OSError: [Errno 5] Input/output error
>>>
```

running most recent HEAD

**Comment by basbebe** [comment]
I _think_ this was supposed to fix the issue:  
pull request https://github.com/mawww/kakoune/pull/4035 by @kayhide  
commit https://github.com/mawww/kakoune/commit/52222a52e4acab1a08f2cba5342d66c1b04ac954

But it seems it doesn't for me.
I'm installing using `brew reinstall kakoune --build-from-source`.

**Comment by basbebe** [comment]
I ignored a fundamental part of the PR: kitty needs to be invoked with `--listen-on` so that **A** the environment-variable `KITTY_LISTEN_ON` is set and **B** kitty listens on a socket to accept commands.

Without it, kitty won't work as expected when connecting to a background kak daemon.

Everything works fine when I use `--listen-on`.

@kayhide out o curiosity (and since this is nowhere documented): do you set `listen_on` in the setting to a fixed socket or do you have session commands that set it?

**Comment by kayhide** [comment]
@basbebe Hi, I am glad to hear that your problem is solved 🙂 

Answering to your question, I am generating a virtually uniq socket by `date +%s` every time .

It is something like:
```
kitty --listen-on unix:@$(date +%s)
```
Note that the `date +%s` returns an epoch time.

**Comment by basbebe** [comment]
thanks!

#### for the record: 

since macOS doesn't support abstract UNIX sockets or starting GUI applications with commandlint options, putting this into `.config/kitty/macos-launch-services-cmdline` works:

```sh
kitty --listen-on unix:/tmp/kitty_(date +%s)
```

sources:  
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-specify-command-line-options-for-kitty-on-macos. 
https://sw.kovidgoyal.net/kitty/invocation.html?highlight=listen#cmdoption-kitty-listen-on
