### ISSUE TITLE
expansion for whole buffer

### ISSUE THREAD

**Issue by basbebe** [mawww/kakoune#3531]
Is there an expansion for referencing the whole buffer?

I would like to write a command that sends the whole buffer / text to an external program and I would like the cursor not to move.

**Comment by danr** [comment]
You can use `%val{selection}` in a `-draft` `eval` context after running `%`.

**Comment by basbebe** [comment]
but then my cursor would move since the whole text ist now selected?

**Comment by danr** [comment]
No the `-draft` flag restores the selection. Try running: 

```
eval -draft %{ exec '%'; echo -debug %val{selection} }
```

Now the *debug* buffer should contain the the entire buffer contents while the selection is unmodified.

**Comment by basbebe** [comment]
Oh yes, thanks!

buut I get an error>
```
Error: 1:1: 'eval' 1:12: 'echo' unknown option '---

```

And I'm surprised that there's no "simpler" solution.

**Comment by danr** [comment]
You can use `echo -debug -- %val{selection}` :P Or handle escaping in a shell expansion (`%sh{ ... do something interesting with $kak_selection ... }`)

Yeah it's a bit surprising. A `val` for this would make sense.

**Comment by basbebe** [comment]
thank you!

**Comment by mawww** [comment]
A specific val would not solve any issues here, as `%val{buffer_content}` would behave exactly the same as `%val{selection}`.

It is not the easiest way to send the buffer content to an external command either, the `<a-|>` command would be more appropriate (`exec -draft '%<a-|>some shell command<ret>'`).
