### ISSUE TITLE
open file in client from terminal

### ISSUE THREAD

**Issue by basbebe** [mawww/kakoune#3533]
I know about [kak.connect](https://github.com/alexherbo2/connect.kak).

But is there another way to send a file to a specified session or client (from a terminal that hasn't been started by kak)?
Or send a file / buffer from one client to another?

**Comment by alexherbo2** [comment]
Look at the [Commands] implementation and [Interfacing] from Kakoune.

[Commands]: https://github.com/alexherbo2/connect.kak/tree/master/rc/paths/commands
[Interfacing]: https://github.com/mawww/kakoune/blob/master/doc/interfacing.asciidoc

**Comment by mawww** [comment]
`echo "evaluate-commands -client $kakoune_client_name edit $filename" | kak -p $kakoune_session_name` ?

**Comment by lenormf** [comment]
I knew I'd answered that question already!

Dupe #3534

**Comment by basbebe** [comment]
this is great, thanks!
