### ISSUE TITLE
Open file in opened client from terminal

### ISSUE THREAD

**Issue by basbebe** [mawww/kakoune#3534]
I know about [kak.connect](https://github.com/alexherbo2/connect.kak).

But is there another way to send a file to a specified session or client (from a terminal that hasn't been started by kak)?
Or send a file / buffer from one client to another?

**Comment by lenormf** [comment]
```
printf 'eval -client %s edit "%s"' <client> /path/to/file | kak -p <session>
```

You can remove the `-client` flag above if you don't care about a client showing the opened file immediately.

**Comment by basbebe** [comment]
dupe
