### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by githububub** [mawww/kakoune#3557]
Arch + sway + alacritty
Debian 10 Stable + GNOME + gnome-terminal
Debian 10 Testing + sway + alacritty

_2020.01.16 release and multiple master builds through 8b36969_

### Steps 
**Case 1:** Normal use, _kak_ launched through a terminal or keybind: `$ kak <file>`

**Case 2:** _kak_ closed using window manager exit/kill keybind (e.g. kill -15) 

### Outcome 
**Case 1:** Frequent 100% cpu usage affecting multiple cores if multiple instances of _kak_ are open. Standalone instances, not reconnected to any existing sessions. Unknown cause; _kak_ is typically closed with `kill!`

**Case 2:** _kak_ process unexpectedly fails to exit and a race condition results in 100% cpu usage. Multiple cores affected if multiple instances of kak are open. Standalone instances, not reconnected to any existing sessions.

End result is a potential denial-of-service state and potential for damage to the cpu(s) if temps are left to continue to rise (_kak_ pushed one of my systems past 66C across six of eight cores before I noticed) and appropriate thermal mitigations are not in place.

### Expected 
In both cases, _kak_ process(es) should close gracefully. Unsure if the issue is related to the client/server and session architecture, but perhaps an option to disable sessions and to run _kak_ as a pure standalone may help workaround this.

### Temporary Workaround
Launching and working with _kak_ within a tmux session whereby editing sessions are exited by way of any of the following tmux `kill-pane` or `kill-window` or `kill-server`.

**Comment by lenormf** [comment]
Dupe #3242

**Comment by mawww** [comment]
I cannot reproduce that here, could you attach a debugger and get a backtrace ?

**Comment by Kratacoa** [comment]
I just noticed I had the same issue on the last release, using st as terminal emulator and tmux, on Void Linux.  

> I cannot reproduce that here, could you attach a debugger and get a backtrace ?
Could you give me some pointers on how to learn to do that and what tools to use? Not a programmer, I'm afraid :sweat_smile: .

**Comment by krobelus** [comment]
First, it you could run a debug build, which has debugging information to show line numbers and more in the backtrace.
Simply compile with `make debug=yes` and then try to reproduce the issue running that.

When it happens, run `sudo gdb -p PID` where PID is the process ID of the affected kak process.
This will stop kak; inside gdb type `bt` to get the backtrace and paste it here.
gdb can do much more, [here is a tutorial](http://www.brendangregg.com/blog/2016-08-09/gdb-example-ncurses.html) on some advanced features.

**Comment by Eluminae** [comment]
I completely relate this issue. On both sway in my desktop and in dwm in my pinephone SXMO (in st)
