### ISSUE TITLE
<c-l> is too smart

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3559]
### Steps 

On Kitty.

* `{ sleep 3; echo foo; }& kak -e info`
* after 3s, hit <kbd>ctrl</kbd><kbd>l</kbd>

### Outcome 

"foo" is printed on the terminal, <kbd>ctrl</kbd><kbd>l</kbd> is a no-op.

### Expected 

The whole terminal is redrawn, getting rid of the "foo" artifact.

The editor seems to refer to a set of heuristics when prompted to redraw, even in "force" mode. I'd like it not to care about internal state when <kbd>ctrl</kbd><kbd>l</kbd> is hit.

**Comment by mawww** [comment]
That is on builtin-terminal-ui, right ?

**Comment by lenormf** [comment]
It is on `builtin-terminal-ui`, I assumed the bug might be present on `master` as well.

Here's an addendum I made: the bug is not reproducible when the changelog autoinfo is displayed, so the command to reliably reproduce the issue is `{ sleep 3; echo foo; }& kak -e info`.

**Comment by lenormf** [comment]
Another reproducer, making the issue clearer:

* run `kak`
* suspend the process
* run `{ sleep 3; echo foo; }& fg %1`
* once the message above has been printed over the buffer's contents, hit <kbd>ctrl</kbd><kbd>l</kbd>
