### ISSUE TITLE
Can't define mapping for the unit separator (^_, 0x1F, C-_, C-/)

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#3573]
I can't seem to make a map for the ^_ control sequence. I tried both
```map global normal <c-_> itesting```
and
```map global normal <c-/> itesting```
but neither of them seem to work? My terminal is definitely sending the control sequence because if I prepare to type a command by typing `:` and then do `<c-_>` or `<c-/>` in the prompt, I see `^_`, meaning that my terminal is indeed sending that sequence.

Am I missing something? Can this control sequence not be mapped in kakoune?

**Comment by Screwtapello** [comment]
See #2553.

You can map US by typing `<c-v><c-/>` (Kakoune should display `␟` to represent the control code) but at the moment there's no printable-ASCII name for that keystroke.

**Comment by enricozb** [comment]
Wow that's actually pretty funny. Just yesterday I mapped <c-v> to paste on my terminal b/c I never thought I would need to type it in kakoune. Thanks for this.

**Comment by Screwtapello** [comment]
For future people finding this issue while trying to figure out how to map the unit separator: PR #3858 causes Kakoune to recognise Ctrl-symbol keys by their actual symbols (like `<c-_>`) instead of having to type them with the Ctrl-V prefix.
