### ISSUE TITLE
Escape < and > in exec with %reg (and possibly other symbols)

### ISSUE THREAD

**Issue by kanashimia** [mawww/kakoune#3576]
If `reg a = <div>` then `exec "<a-/>%reg{a}"` would result in a parse error.
Right now you can do something like `exec "<a-/>%sh{ echo $kak_reg_a | sed 's/</<lt/g; s/>/<gt>/g; s/<lt/<lt>/g' }"`
This doesn't seem like it was intended to be this way :°)

**Comment by Screwtapello** [comment]
You could also `exec "<a-/><c-r>a"` to search for text matching the contents of a register. If `exec` didn't treat `<div>` as a key, it wouldn't treat `<a-/>` as a key either.

**Comment by kanashimia** [comment]
Helpful

**Comment by occivink** [comment]
another possibility is to do `exec '"a<a-/><ret>'`. Doing an 'empty' search will use the content of the register specified (the `/` register by default)
