### ISSUE TITLE
Start kakoune in -ro mode reading from stdin

### ISSUE THREAD

**Issue by enricozb** [mawww/kakoune#3579]
Is there any way for me to start kakoune in readonly mode while reading from a pipe? The use-case for this is man pages and reading logs that populate the buffer as I have it open. Right now something like

    man find | col -b -x | kak -e "set buffer filetype man;\
                                   remove-hooks window man-hooks;\
                                   map buffer normal q :q<ret>"

is what I use for man pages, however I want it to be impossible to enter insert mode. Right now I have `map buffer normal i ""` as well, in order to prevent entering insert mode with `i`, but I want something a bit more robust, so I can't do `o` or paste or cut etc.

If I just do `cat file.txt | kak -ro`, the buffer is not readonly. If I do `cat file.txt | kak -e "set buffer readonly true"`, then kakoune crashes with

    Fatal error: buffer is read-only

Is there any way to do this?

Thanks in advance!

**Comment by alexherbo2** [comment]
``` kak
hook buffer BufCloseFifo .* %{
  set-option buffer readonly true
}
```

**Comment by enricozb** [comment]
Perfect. Thank you!
