### ISSUE TITLE
python plugin is not enabled when filetype=script.python

### ISSUE THREAD

**Issue by ewtoombs** [mawww/kakoune#3581]
### Steps 
```
echo '#!/usr/bin/env python

from os import execvp
execvp('ls', ['ls'])' > /tmp/testscript
kak /tmp/testscript
```
Then in kak, type `:set buffer filetype ` to see its current value.

### Outcome 
 It will say `script.python`, but the python plugin still doesn't activate. Most obviously, there is no syntax highlighting, but the autoindent doesn't work either.

### Expected 
There should be syntax highlighting and autoindent.

### Possible solution
```diff
--- /usr/share/kak/rc/filetype/python.kak	2020-01-16 11:46:42.000000000 +0000
+++ /tmp/python.kak	2020-07-06 19:54:12.570066198 +0000
@@ -11,7 +11,7 @@
 # Initialization
 # ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 
-hook global WinSetOption filetype=python %{
+hook global WinSetOption filetype=(script\.)?python %{
     require-module python
 
     set-option window static_words %opt{python_static_words}
@@ -22,7 +22,7 @@
     hook -once -always window WinSetOption filetype=.* %{ remove-hooks window python-.+ }
 }
 
-hook -group python-highlight global WinSetOption filetype=python %{
+hook -group python-highlight global WinSetOption filetype=(script\.)?python %{
     add-highlighter window/python ref python
     hook -once -always window WinSetOption filetype=.* %{ remove-highlighter window/python }
 }
```

**Comment by Screwtapello** [comment]
On my machine, following the steps-to-reproduce results in the filetype being set to `python`.

The actual filetype value comes from [rc/detection/file.kak](https://github.com/mawww/kakoune/blob/b875a1802c06f9019a514249db4ea17c55af3109/rc/detection/file.kak), which picks it based on the MIME type reported by `file -b --mime-type -L`.

What OS are you running, and what version of `file` do you have? What does it output for the Python script in question?

**Comment by ewtoombs** [comment]
```
text/x-script.python
```

And I'm running archlinux. This is the current version of file:
```
Name            : file
Version         : 5.39-1
Description     : File type identification utility
Architecture    : x86_64
URL             : https://www.darwinsys.com/file/
Licenses        : custom
Groups          : base-devel
Provides        : libmagic.so=1-64
Depends On      : glibc  zlib  xz  bzip2  libseccomp  libseccomp.so=2-64
Optional Deps   : None
Required By     : base  xdg-utils
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 6.56 MiB
Packager        : Sébastien Luttringer <seblu@seblu.net>
Build Date      : 2020-06-16T16:04:54 UTC
Install Date    : 2020-07-04T16:48:10 UTC
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```
So, this must have been a recent addition. I see no apparent archlinux-specific modifications.

**Comment by Screwtapello** [comment]
Ah, i see what's going on. I'm running file 5.38, and you're running 5.39. Although it's not mentioned in the changelog, in February file [changed the MIME type it reports for Python files](https://github.com/file/file/commit/eb373e431ccfeedfbcf497e4da07571d43bdb9f2). If I'm reading the script correctly, it looks like support for this new convention [was added to Kakoune about a month ago](https://github.com/mawww/kakoune/pull/3553). If you build Kakoune from git trunk, does it work for you?

**Comment by ewtoombs** [comment]
idk. I'll just wait for kak to get updated by my distro. I have the temporary fix in until then. You can close this, and if the update undoes my fix, I'll report it back here.

**Comment by Screwtapello** [comment]
@mawww, perhaps you could cut a new Kakoune release soon? If the current Kakoune release is going to be broken by a `file` release, and Kakoune already has the fix, that would be a good way to avoid a bunch of duplicate bug reports.
