### ISSUE TITLE
Strange 5s lag for mundane shell execution (possibly only on builtin-terminal-ui)

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#3585]
The shell script runs no external programs.  It does trigger a display update.  The display update is quick, but maybe it is causing an event to get lost somehow?

Log:
```
            # kak_opt_parinfer_scheme_sexp_comment
            # kak_opt_parinfer_janet_long_strings
            exec parinfer-rust --mode=$mode --input-format=kakoune --output-format=kakoune
        
----
shell execution took 13291 us (spawn: 5040, wait: 8114)
shell:

        line=$kak_opt_parinfer_cursor_line
        column=$kak_opt_parinfer_cursor_char_column
        if [ -n "$kak_selections_display_column_desc" ]; then
            set -- $kak_selections_display_column_desc
        else
            set -- $kak_selections_desc
        fi
        case "$1" in
            *,${line}.${column}) exit;;
        esac
        shift
        echo "select ${kak_opt_parinfer_select_switches} ${line}.${column},${line}.${column} $@"
    
----
window display update for 'centralpark/test/twou/centralpark/server/database/migrations_test.clj' took 2925 us
shell execution took 5009220 us (spawn: 1844, wait: 5007346)
hook 'NormalKey(h)' took 5035009 us
hook 'RawKey(h)' took 0 us
hook 'RawKey(h)' took 0 us
```

**Comment by mawww** [comment]
did you have many selections at the time ? Any simple steps to reproduce that ?

**Comment by eraserhd** [comment]
I definitely usually have just one selection when this happens.  I haven't found simple steps -- this code runs after almost every keystroke but only pauses for 5s once every 1m-5m.

I'll restart Kakoune tomorrow, and if it keeps happening, I'll keep a log for a few hours to see if there's any correlations I can see.

**Comment by eraserhd** [comment]
4 instances today, out of 5094 shell executions (granted, not a lot of code today), so 0.08%.  Very strange that they are usually very slightly over 5 seconds.

2 instances have "window display update", between the shell execution and profile information.  This only happened for a total of 12 shell executions.

```
shell:

        if [ ! "$kak_main_reg_dquote" = "$kak_opt_snarf_last_dquote" ]; then
            printf %s "$kak_main_reg_dquote" |9 9p write snarf/snarf
            printf "set-option global snarf_last_dquote '"
            printf %s "$kak_main_reg_dquote" |sed -e "s/'/''/g"
            printf "'\n"
        fi
    
----
shell execution took 5085923 us (spawn: 1890, wait: 5084015)
shell:

        snarf="$(9 9p read snarf/snarf && printf x)"
        if [ $? -ne 0 ]; then
            exit
        fi
        if [ ! "$snarf" = "${kak_main_reg_dquote}x" ]; then
            printf "set-register dquote '"
            printf %s "${snarf%x}" |sed -e "s/'/''/g"
            printf "'\n"
        fi
    
----
shell execution took 5090160 us (spawn: 5005044, wait: 85103)
shell:

        if [ ! "$kak_main_reg_dquote" = "$kak_opt_snarf_last_dquote" ]; then
            printf %s "$kak_main_reg_dquote" |9 9p write snarf/snarf
            printf "set-option global snarf_last_dquote '"
            printf %s "$kak_main_reg_dquote" |sed -e "s/'/''/g"
            printf "'\n"
        fi
    
----
window display update for 'qmk_firmware/keyboards/crkbd/keymaps/eraserhd/keymap.c' took 5087 us
shell execution took 5117525 us (spawn: 2011, wait: 5115500)
shell:

        if [ ! "$kak_main_reg_dquote" = "$kak_opt_snarf_last_dquote" ]; then
            printf %s "$kak_main_reg_dquote" |9 9p write snarf/snarf
            printf "set-option global snarf_last_dquote '"
            printf %s "$kak_main_reg_dquote" |sed -e "s/'/''/g"
            printf "'\n"
        fi
    
----
window display update for 'qmk_firmware/keyboards/crkbd/keymaps/eraserhd/keymap.c' took 609 us
shell execution took 5009918 us (spawn: 2460, wait: 5007427)
```

**Comment by mawww** [comment]
Hum, hang on, in `shell_manager.cc` you can see that the `shell:\n...` log entry is written *before* executing the shell and execution timing *after*. So the shell snippet you posted is not the one that took 5s, its whatever shell command was executed just after.

**Comment by eraserhd** [comment]
I probably fudged something when I extracted things from the log, and I also lost the original log.  I'll run it again today and see.

**Comment by eraserhd** [comment]
Yesterday's log has 11 out of 8810 shell executions taking almost exactly 5s.  The next slowest is 1s, and a manual curl, and there are no slower ones:

```
5009790 N mode="$1" [ "$kak_opt_par
5010389 N if [ ! "$kak_main_reg_dqu
5077042 N if [ ! "$kak_main_reg_dqu
5078653 Y if [ ! "$kak_main_reg_dqu
5081002 N if [ ! "$kak_main_reg_dqu
5083630 Y if [ ! "$kak_main_reg_dqu
5083648 N if [ ! "$kak_main_reg_dqu
5084286 N if [ ! "$kak_main_reg_dqu
5086413 N if [ ! "$kak_main_reg_dqu
5088253 N snarf="$(9 9p read snarf/
5089427 N if [ ! "$kak_main_reg_dqu
```

Looked at the code, and I couldn't find any references to 5 seconds anywhere.  It's possible this happens when something is eating CPU?  Maybe there's a race and SIGCHLD is not handled?  I'm worried it's another "Mac OS doesn't work properly"  :/

**Comment by mawww** [comment]
Do you have a version where I can see the whole shell script ? Could it be 9p that is slow at processing your command ? Could there be a 5s timeout if 9p server does not respond ?

**Comment by eraserhd** [comment]
It happened on scripts that didn't invoke 9p, but the problem seems to have been remedied by this week's update of Nix packages.  I'll reopen if it comes back.
