### ISSUE TITLE
Suggestion: require :w! for writing to a file other than the current file

### ISSUE THREAD

**Issue by Quelklef** [mawww/kakoune#3587]
Apologies if this has been brought up before; I was unable to find a related issue

### Feature

If `:w FILE` is used where `FILE` is not the currently open file, refuse to write; require `:w!`.

### Usecase

QWERTY places `w` and `e` adjacent to each other. Several times when working with multiple files, I have meant to switch files by typing `:e OTHER_FILE` but accidentally typed `:w OTHER_FILE`, mistakenly overwriting the other file.

Most of the time, that file is in Kak's memory, so I am able to undo back to safety. Once, though, it wasn't. In that case, I was luckily able to `git checkout` without losing work. However, neither of these safeties are guaranteed. As such, it would be nice to include a guard against such an easy typo.

**Comment by CharlesGueunet** [comment]
You may find [this discourse topic](https://discuss.kakoune.com/t/prevent-write-to-overrite-existing-file-by-default/992) interesting.

Here is [the final version](https://github.com/CharlesGueunet/kak/blob/af0de673c762e1790af9d78a6b58a56f3345c27b/kakrc#L126) on my config files.

Could this be a (really small) plugin ?

**Comment by alexherbo2** [comment]
Same happened to me.

**Comment by krobelus** [comment]
Refusing to write if the file exists sounds like a reasonable behavior.
Either chaning the `w` alias or `write` itself.

**Comment by Quelklef** [comment]
@CharlesGueunet Thank you for the snippet!

**Comment by caksoylar** [comment]
Sounds like https://github.com/mawww/kakoune/commit/40e3614cf458a982c783e899143bef81736faa27 resolve this, right?

**Comment by mawww** [comment]
@voroskoi seems I ended up with something very similar to your previous PR, changed my mind about this seeing that it seems to regularly come up and that vim does refuse to overwrite by default as well.
