### ISSUE TITLE
Be verbose about requirement 

### ISSUE THREAD

**Issue by sucrecacao** [mawww/kakoune#3591]
Too often I try a command and nothing happen, like in #3590 . When I dig in the code I realise I miss a dependency. Sometime it will be explicit in the readme, the doc, or commented on top of a file, but sometime not. 

How could we introduce a way to be more verbose about requirement ? The fact that nothing happen at all instead of an error can be very confusing for new users ( and old one too ! ) ,   #3590  is an example that just happen to me, be it's not the first time.

Maybe just ask contributor and pluggin writter to had something like: ( pseudocode)
``` 
if  ! exist(xsel):
    echo " xsel required"
```

**Comment by krobelus** [comment]
usually there should be a "command not found" error in the debug buffer

**Comment by mawww** [comment]
I think the pattern should be:

```
if ! <my command line that requires a tool that might be missing>; then
    echo "fail failed to run my command, see *debug* buffer"
fi
```

We would get the `command not found`  error from the shell or stderr from the command itself in the *debug* buffer.
