### ISSUE TITLE
Add an Alt + % command to select all occurrences of the current selection set

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3592]
<kbd>Alt</kbd> + <kbd>%</kbd> ⇒ <kbd>*</kbd>, <kbd>%</kbd>, <kbd>s</kbd>, <kbd>Return</kbd>

**Comment by mawww** [comment]
As you described, this is already easily implemetable with existing features, its easy to do such a mapping. I dont think its really warranted to add is as a core feature. Kakoune already has too many normal mode commands, new ones need to have a really strong use case. (And I agree `<a-s>` is kind of a precedent for this as it is equivalent to `"_s^<ret>`, but I'd rather not add more like that if we can avoid it).

**Comment by alexherbo2** [comment]
@mawww I am not sure, but I thought it was a common feature in IDEs.
