### ISSUE TITLE
Repeat command is broken with execute-keys from insert mode

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3600]
### How to reproduce

1. Add the following setup:

``` kak
map global insert <space> '<a-;>: insert-space<ret>'

define-command insert-space %{
  execute-keys <space>
}
```

2. Then type:

```
i<space><esc>.
```

Affects [auto-pairs.kak].

[auto-pairs.kak]: https://github.com/alexherbo2/auto-pairs.kak

**Comment by topisani** [comment]
To simplify it, it also happens without calling a command, and without using a mapping>
 - execute `i<a-;>:exec t<ret><esc>`: one `t` is inserted
 - execute `.`: `tt` is inserted
 - execute `.`: `ttt` is inserted

For every repeat, it increases the number of `t`s in the repeat list by one
