### ISSUE TITLE
assert failed "buffer->flags() & Buffer::Flags::Fifo" at buffer_utils.cc:107

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#361]
The following script triggers a failed assertion:
```
hook global BufNew .* %{
    %sh{
        d=$(mktemp -d)
        mkfifo "${d}/e"

        ( for i in {0..9}; do echo $i >> "${d}/e"; sleep 1; done ) &>/dev/null </dev/null &

        echo "
            eval %{
                edit! -fifo '${d}/e' -scroll '${kak_hook_param}'
            }
        "
    }
}
```
What it does it wait for new buffers to be created, and whenever a new one is created, it opens itself with a fifo buffer (if that's even theoretically possible), and kakoune immediately raises an exception:
```
assert failed "buffer->flags() & Buffer::Flags::Fifo" at buffer_utils.cc:107
[Debug Infos]
pid: 13224
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x5002f8]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2b) [0x4feb9b]
kak() [0x49408a]
kak(_ZNSt10_HashtableIN7Kakoune7ValueIdESt4pairIKS1_NS0_5ValueEENS0_9AllocatorIS5_LNS0_12MemoryDomainE14EEENSt8__detail10_Select1stESt8equal_toIS1_ENS0_4HashIS1_EENS9_18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyENS9_17_Hashtable_traitsILb1ELb0ELb1EEEE5clearEv+0x22) [0x4e9f52]
kak(_ZN7Kakoune6BufferD2Ev+0x7e) [0x4e621e]
kak(_ZN7Kakoune6BufferD0Ev+0x9) [0x4e6a09]
kak(_ZN7Kakoune13BufferManagerD1Ev+0x146) [0x4921a6]
kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0xdb5) [0x4d2d45]
kak(main+0xd51) [0x456711]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f0df402c790]
kak(_start+0x29) [0x459d69]
```

Note that if you get rid of the subshell, the new buffer will be created, but kakoune will raise the exception only when the buffer is closed manually.

About the testcase itself: is it theoretically possible to have a buffer reopen itself with a named pipe attached to it ? I'd be interested into having that feature if possible.

**Comment by mawww** [comment]
Note that the way fifo works, you'll only get '0' in the file (as the shell will close the fifo on each loop), you probably want to move the redirection after the done, so that the whole loop writes to the fifo without closing it at each iteration.
