### ISSUE TITLE
Extend selection page up / down

### ISSUE THREAD

**Issue by pickfire** [mawww/kakoune#3611]
### Feature 

Feature parity with the rest of commands to allow current `<c-f>` and `<c-b>` which navigates between extends the page while the capitalized word is used (`<c-F>` and `<c-B>`).

### Usecase 

Sometimes I need to extend selection like 5 pages of my screen (52 * 5) but I need to hold down `<c-J>` which takes quite a while to reach there. Same should apply for `<c-D>` and `<c-U>`.

**Comment by alexherbo2** [comment]
<kbd>Control</kbd> + <kbd>Shift</kbd> is not possible with the terminal.

**Comment by pickfire** [comment]
Aaaa, I didn't know about this. T_T How do you all easily extend over pages usually?

**Comment by alexherbo2** [comment]
I don’t. xD

**Comment by Screwtapello** [comment]
It could be bound to Shift-PgUp and Shift-PgDn, except that most terminals reserve those for navigating scrollback.

For selecting really large amounts of text, I start using structural navigation - `<a-i>{` selects a block of code, `}p` selects until the next blank line, etc. If you're in a CSV file or something that doesn't have multi-line structures to navigate by, maybe you can use `?` to extend to the next match of a regex?

**Comment by lenormf** [comment]
You could mark the beginning of the selection with <kbd>Z</kbd>, then scroll down using whatever method you want (for example <kbd>ctrl</kbd> <kbd>d</kbd>), then use <kbd>a-z</kbd> <kbd>i</kbd>.

**Comment by pickfire** [comment]
> It could be bound to Shift-PgUp and Shift-PgDn, except that most terminals reserve those for navigating scrollback.

I use shift-pageup and shift-pagedown to scroll commonly. So I can't use it.

> }p selects until the next blank line

I need to do that like 10+ times to reach the place I want.

> You could mark the beginning of the selection with Z, then scroll down using whatever method you want (for example ctrl d), then use a-z i.

<kbd>a-z</kbd> <kbd>i</kbd>? Looks interesting, this is what I am looking for. I wonder if there's a good way to see documentation for keys without searching for it like `:h CTRL-F` in vim.
