### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by doa379** [mawww/kakoune#3624]
Kak suffers from poor UI performance in my experience. 

I use Urxvt but the interface is a little laggy and keystrokes go astray or are not timely registered thereby causing unwanted behavior.
It's results in a frustrating user experience. There's no such issue in vim.

There is a relatively prolonged delay when pressing the Esc to exit insert mode back to normal mode. It's very frustraing and ruins the workflow.

**Comment by arrufat** [comment]
Are you using kakoune inside of tmux? If so, does this solve your `Esc` problem?
https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#why-does-leaving-insert-mode-take-more-than-half-a-second-in-tmux-

**Comment by doa379** [comment]
Yes I am. Okay it does. Thank you.
