### ISSUE TITLE
Is there a way to retreive original key from a remaped key ? 

### ISSUE THREAD

**Issue by sucrecacao** [mawww/kakoune#3639]
example:
kakrc:
```
map global normal <backspace> <space>
```
In a kakoune prompt:
`
:retreive-mapping '<backspace>'<ret>    
`
=> return `<space>`

**Comment by Screwtapello** [comment]
Not currently, no.

**Comment by sucrecacao** [comment]
Thanks!
a hacky work around:
`cat kakrc | rg "^map global normal '?$k'?" | cut -d' ' -f5-`
assuming all remapping are in kakrc, and $k hold the key
