### ISSUE TITLE
How can i add a hook that inserts a closing html tag?  

### ISSUE THREAD

**Issue by theamazingwaffle** [mawww/kakoune#3641]
When i type `<p>` i want another `</p>` to get inserted right after the cursor, for example.

I've started with this but then i got stuck.
```
hook buffer InsertChar > %{
  # I don't know what to add here since it's only commands and not movements.

}
```
In something vimscriptish i'd do `<esc>h<a-i>>S <a-space>y<a-a>>a</<esc>pla><a-a>><a-;>;i`

**Comment by alexherbo2** [comment]
It looks difficult to work reliably with hooks.  I use [surround.kak] for that.

[surround.kak]: https://github.com/alexherbo2/surround.kak

**Initial selection**

```
[hello]
```

**Command** – <kbd>q</kbd> <kbd>t</kbd> <kbd>p</kbd> <kbd>Return</kbd>

```
<p>[hello]</p>
```

**Command** – <kbd>q</kbd> <kbd>Return</kbd>

```
<p>
  [hello]
</p>
```

**Comment by mawww** [comment]
@theamazingwaffle `execute-keys` is the command you'd use to, well, execute some keys...
