### ISSUE TITLE
module 'elixir' loaded recursively

### ISSUE THREAD

**Issue by Parasrah** [mawww/kakoune#3651]
### Steps 

Open an elixir file

### Outcome 

`elixir` module fails to load

```
error running hook WinSetOption(filetype=elixir)/: 2:5: 'require-module' 2:1: 'require-module' 3:1: 'require-module' module 'elixir' loaded recursively
```

### Expected 

Module loads successfully with valid syntax highlighting etc

### Environment

Kakoune [2020.08.04](https://github.com/Parasrah/nix-config/blob/715d475bb6cd670e9954a0d27f3d92283a1f26e2/pkgs/kakoune/default.nix)
NixOS

### Additional Information

Seems the additional module was added in [this PR](https://github.com/mawww/kakoune/pull/3462) which, given the documentation of `require-module`, seems like it should work? I understood the intended behavior of `require-module` to mean "if the module is not loaded, load it, otherwise do nothing".

Thanks for all your hard work on kakoune, and let me know if there is anything I can do to provide more information or help test

**Comment by lenormf** [comment]
I think the `elixir` module loads the `eex` one, which also requires the `elixir` module. There's the cyclic dependency.

The simplest way to fix that would be to wrap the module loading in `eex` with a `try`, but that's not very clean.

Since the EEX module does something very similar to the Jinja module (i.e. it just highlights a templating language), maybe it should use [detection logic similar to the Jinja hook](https://github.com/mawww/kakoune/commit/5dc4ce528192847bdcd4c9439c66b09b87912654).

**Comment by Parasrah** [comment]
Maybe it would be worth pulling @Phlogistique into this, because I'm not entirely sure why the `eex` needs to be loaded by the `elixir` module at all? As far as I understand, `eex` files are a framework specific filetype ([Phoenix Framework](https://phoenixframework.org/)) and are unrelated to elixir itself. I don't know why anyone would ever write `eex` templates in an `ex` file. That said, I have yet to write any `eex` templates myself as I use elixir purely for `REST` api's for the time being

Short term I've created a [plugin](https://github.com/Parasrah/elixir.kak) that overrides the `elixir` module to remove the requirement for the `eex` module if anyone else runs into this and needs a quick fix

**Comment by Phlogistique** [comment]
Hi,

There is a special macro in Elixir files to embed EEX templates; and the purpose of EEX templates is to embed Elixir code; so the recursive include makes sense at least semantically.

Now what is strange is that it works on my machine...

**Comment by Parasrah** [comment]
Okay that makes total sense!

I assumed it must be working for you, out of curiosity what version of kakoune are you using?

I'd be happy to take a look at the jinja hook and try to come up with a fix

**Comment by Phlogistique** [comment]
`Kakoune v2019.12.10`

**Comment by Phlogistique** [comment]
Will try installing a more recent version with Nix to check if I reproduce the problem.

**Comment by Parasrah** [comment]
I've got my override for the nixpkgs derivation [here](https://github.com/Parasrah/nix-config/blob/715d475bb6cd670e9954a0d27f3d92283a1f26e2/pkgs/kakoune/default.nix) if that would help out at all

**Comment by Phlogistique** [comment]
Can confirm I can reproduce the problem by running `nix-shell -p kakoune --run 'kak foo.ex'`
