### ISSUE TITLE
Wiki question: math prompt with qalculate instead of bc for more advanced map, where should I put it?

### ISSUE THREAD

**Issue by arrufat** [mawww/kakoune#3657]
In the wiki, I've seen the [Integration with OS and other tools](https://github.com/mawww/kakoune/wiki#integration-with-os-and-other-tools) section, which has a [bc](https://github.com/mawww/kakoune/wiki/Bc) entry.
It contains a mapping for simple math using bc:
``` kak
map global normal = ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>'
```
However, I've found it somewhat limited, so I've replaced bc with [qalculate](http://qalculate.github.io/), which has a cli tool, `qalc` with a **lot** of [features](http://qalculate.github.io/features.html), built-in functions, variables, unit/currency conversions, etc. The mapping looks like this:

``` kak
map global normal = ': prompt math: %{exec "a%val{text}<lt>esc>|qalc -t -f -<lt>ret>"}<ret>'
```

It works exactly the same as `bc` but now we can do things like:
```
1 day + 2 hour + 30 min + 5 s to s
```
select the line with `x` and press `=<ret>` to get:
```
95405 s
```

So my question is, should I add it to the wiki? If so, in its own entry, or should we rename the `bc` entry to `math` and add it as a subsection there?

Thanks in advance.

**Comment by lenormf** [comment]
You can edit the wiki in any way you think is relevant. Try to keep what's already there unless it's deprecated.

**Comment by arrufat** [comment]
Thank you, I know that the wiki can be edited freely, I was just wondering if somebody had strong feelings about a particular option :)
