### ISSUE TITLE
Inconsistent arity of `repl` alias implementations

### ISSUE THREAD

**Issue by chambln** [mawww/kakoune#3680]
### Steps 

1. Run Kakoune inside tmux with e.g. `tmux -c kak`
2. Use the `repl` command with multiple arguments, e.g. `:repl man kak<ret>` (maybe not the best example, since Kakoune has built-in man paging, but bear with me)

### Outcome 

    Error: 1:1: 'repl' 2:5: 'tmux-repl-impl' wrong argument count

### Expected 

Tmux split with kak(1) man page open in your man pager. This would match the behaviour of the `x11.kak` backend. I have not tested the `kitty.kak` backend.

**Comment by lenormf** [comment]
You should use `:send-text 'man kak'`. This command should be renamed to start with "repl-" because it's not obvious what it does unless users read the documentation.

**Comment by mawww** [comment]
`send-text` does indeed need to be renamed, however the initial issue still stands, we should provide a consistent interface through repl, and the best one would be to perfectly forward arguments as provided to kakoune. Its unclear if all backends will support that but it should be the goal.
