### ISSUE TITLE
Support NetBSD Curses

### ISSUE THREAD

**Issue by Ella-0** [mawww/kakoune#3683]
### Feature 
To support the NetBSD curses API by making `ncurses_ui.cc` more portable and less dependent on the internals of ncurses.

### Usecase 
Not all operating systems use ncurses such as NetBSD, sabotage-linux and my own linux installation. Although I could do what NetBSD did for their Kakoune port and statically link
ncurses, this is not ideal as the ncurses terminfo database needs to be installed.

### My Attempt
I have made a very poor attempted to port `ncurses_ui.cc` based on the little curses programming knowledge I have. However, although it builds and launches, there are massive graphical bugs. I have tested it on linux with the [sabotage NetBSD curses port](https://github.com/sabotage-linux/netbsd-curses), Musl libc and the LLVM C++ libraries.

![image](https://user-images.githubusercontent.com/23418164/91451367-dec84400-e86c-11ea-8e04-c78eb69fb331.png)

Though if the terminal size doesn't change then it is partially useable.

![image](https://user-images.githubusercontent.com/23418164/91451523-07e8d480-e86d-11ea-95c7-966bc9184fa2.png)

```patch
--- src/ncurses_ui.cc
+++ /home/user/test/kakoune-2020.08.04/src/ncurses_ui.cc
@@ -23,13 +23,20 @@

 constexpr char control(char c) { return c & 037; }

+extern "C" {
+    char * tigetstr(const char *);
+    char * tparm(const char *, ...);
+    int putp(const char *);
+    WINDOW *__virtscr;
+}
+
 namespace Kakoune
 {

 using std::min;
 using std::max;

-struct NCursesWin : WINDOW {};
+struct NCursesWin;

 void NCursesUI::Window::create(const DisplayCoord& p, const DisplayCoord& s)
 {
@@ -40,7 +47,7 @@

 void NCursesUI::Window::destroy()
 {
-    delwin(win);
+    delwin((WINDOW *)win);
     win = nullptr;
     pos = DisplayCoord{};
     size = DisplayCoord{};
@@ -52,37 +59,37 @@
         return;

     if (force)
-        redrawwin(win);
+        redrawwin((WINDOW *)win);

     DisplayCoord max_pos = pos + size - DisplayCoord{1,1};
-    pnoutrefresh(win, 0, 0, (int)pos.line, (int)pos.column,
+    pnoutrefresh((WINDOW *)win, 0, 0, (int)pos.line, (int)pos.column,
                  (int)max_pos.line, (int)max_pos.column);
 }

 void NCursesUI::Window::move_cursor(DisplayCoord coord)
 {
-    wmove(win, (int)coord.line, (int)coord.column);
+    wmove((WINDOW *)win, (int)coord.line, (int)coord.column);
 }

 void NCursesUI::Window::draw(Palette& palette, ConstArrayView<DisplayAtom> atoms,
                              const Face& default_face)
 {
-    auto add_str = [&](StringView str) { waddnstr(win, str.begin(), (int)str.length()); };
+    auto add_str = [&](StringView str) { waddnstr((WINDOW *)win, str.begin(), (int)str.length()); };

     auto set_face = [&](Face face) {
         if (m_active_pair != -1)
-            wattroff(win, COLOR_PAIR(m_active_pair));
+            wattroff((WINDOW *)win, COLOR_PAIR(m_active_pair));

         face = merge_faces(default_face, face);

         if (face.fg != Color::Default or face.bg != Color::Default)
         {
             m_active_pair = palette.get_color_pair(face);
-            wattron(win, COLOR_PAIR(m_active_pair));
+            wattron((WINDOW *)win, COLOR_PAIR(m_active_pair));
         }

         auto set_attribute = [&](Attribute attr, int nc_attr) {
-            (face.attributes & attr) ?  wattron(win, nc_attr) : wattroff(win, nc_attr);
+            (face.attributes & attr) ?  wattron((WINDOW *)win, nc_attr) : wattroff((WINDOW *)win, nc_attr);
         };

         set_attribute(Attribute::Underline, A_UNDERLINE);
@@ -95,9 +102,9 @@
         #endif
     };

-    wbkgdset(win, COLOR_PAIR(palette.get_color_pair(default_face)));
+    wbkgdset((WINDOW *)win, COLOR_PAIR(palette.get_color_pair(default_face)));

-    ColumnCount column = getcurx(win);
+    ColumnCount column = getcurx((WINDOW *)win);
     for (const DisplayAtom& atom : atoms)
     {
         StringView content = atom.content();
@@ -108,7 +115,7 @@
         if (content.back() == '\n')
         {
             add_str(content.substr(0, content.length()-1));
-            waddch(win, ' ');
+            waddch((WINDOW *)win, ' ');
         }
         else
             add_str(content);
@@ -116,7 +123,7 @@
     }

     if (column < size.column)
-        wclrtoeol(win);
+        wclrtoeol((WINDOW *)win);
 }

 constexpr int NCursesUI::default_shift_function_key;
@@ -432,7 +439,8 @@

     m_info.refresh(false);

-    Window screen{{}, static_cast<NCursesWin*>(newscr)};
+//    Window screen{{}, static_cast<NCursesWin*>(newscr)};
+    Window screen{{}, (NCursesWin*)(__virtscr)};
     if (m_cursor.mode == CursorMode::Prompt)
         screen.move_cursor({m_status_on_top ? 0 : m_dimensions.line, m_cursor.coord.column});
     else
```

**Comment by lenormf** [comment]
Have you tried the `builtin-terminal-ui` branch? It only uses terminal escape sequences, no NCurses involved.

**Comment by Ella-0** [comment]
No I haven't. Thank you; I'll try that now.

**Comment by Ella-0** [comment]
Just built it and it works nicely. However I still think that this issue stands as `ncurses_ui.cc` should be more portable and less dependant on the internals of ncurses though I understand this is a long term goal and is not a high priority at all.

**Comment by mawww** [comment]
The ncurses backend is going away as soon as we merge that `builtin-terminal-ui` branch, hopefully in the coming months, I just need to fix some flickering that has been reported, so the fix there is just to get rid of the ncurses dependency altogether ;)

**Comment by lenormf** [comment]
I don't understand what your patch does, it seems to be only casting pointers, which shouldn't be necessary with GCC or Clang. What internals is the current code relying on?

**Comment by Ella-0** [comment]
The first thing `ncurses_ui.cc` relies on is `WINDOW`. In NetBSD curses this is forward declared so this won't work `struct NCursesWin : WINDOW {};` so I've had to replace it with just `struct NCursesWin` which means casting implicit so i have to cast a bunch of `NCursesWin *` to `WINDOW *`. The second thing it relies on is `newscr` or the Virtual screen which, in NetBSD curses is not exposed as a public API. Though i got around this by adding this line `+    WINDOW *__virtscr;` which allows me to access `__virtscr` which is NetBSD curses internal virtual screen. The final things were just some random functions that aren't included in `curses.h`.

**Comment by Ella-0** [comment]
But if the plan is to remove the NCurses backend all together then I see that this issue is useless and there's no need for it to be open.

**Comment by lenormf** [comment]
Thanks for the explanation.

Even when NCurses isn't a supported frontend any more, it would still be good to have a patch around (Gist? `contrib`? Wiki?) for people who want to keep it, so the portability notes are useful.

**Comment by Ella-0** [comment]
If it would be useful I'd happily keep working on a patch to include somewhere as a compatibility thing. Though I'm a little out of my depth when it comes to curses and I don't know at all what is causing those graphical bugs.

**Comment by lenormf** [comment]
If you're using NetBSD, the editor is broken but you have made (portable) changes that fix your issues (as seems to be the case), I think you should create a PR.

There's no telling when support for the NCurses frontend is going to stop, and we want NetBSD users to be able to use the editor in the meantime :)

**Comment by Ella-0** [comment]
I don't think all of the changes I made are completely portable. The `__virtscr` definitely is not. I haven't actually tested this on a real NetBSD system, only with the NetBSD curses library on my Linux system. NetBSD users still can use the editor. It's in the pkgsrc repository though they link against the ncurses library which is not ideal for them.

I recon this patch could be made portable with either a bunch of `#ifdef`s or removing `__virtscr`/`newscr` though I wouldn't know how to go about removing that.

**Comment by krytarowski** [comment]
Any news on netbsd curses support?

**Comment by Ella-0** [comment]
Not really, use the builtin-terminal-ui branch for now if you can't use ncurses. Though feel free to try and debug my patch if you want.

**Comment by Delapouite** [comment]
Hi. Now that the `builtin-terminal-ui` has been merged into master and ncurses is not used anymore, should we close this ticket?

**Comment by Ella-0** [comment]
I think so
