### ISSUE TITLE
Unicode is show very strange in kak

### ISSUE THREAD

**Issue by h-bar** [mawww/kakoune#3707]
### Steps 
When I open kak some characters are shown in very strange ways. My terminal is using UTF-8 and my font does have faces for the character that should be put in the ~T~@ place

### Outcome 
![image](https://user-images.githubusercontent.com/4517544/92069697-0725d600-ed78-11ea-8878-47279528ef37.png)

### Expected 
![image](https://user-images.githubusercontent.com/4517544/92069795-4c4a0800-ed78-11ea-8873-ba1d652a9300.png)

Thanks!!

**Comment by Screwtapello** [comment]
See the FAQ [Why do I see weird special characters (\~T\~@~U) around clippy?](https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#why-do-i-see-weird-special-characters-tu-around-clippy)

**Comment by h-bar** [comment]
Sorry, I forgot to mention that my locales are already set to UTF-8. 
![image](https://user-images.githubusercontent.com/4517544/92186525-09923980-ee25-11ea-86ce-c895a95499cb.png)

In addition, I compiled the program with the static binary flag on another machine, on which it works fine. Then I copied the static binary into this machine where it does not work. May this be the cause of the issue?

Thanks!

**Comment by Screwtapello** [comment]
The way the locale system works is that the user sets their `$LANG` (or whatever) environment variable to indicate the locale settings they want, the application calls the standard library function `setlocale()` to indicate that it wants to use locale-specific information, and then the standard library goes to load that locale-specific information from files on disk.

On my machine, my locale data is stored in `/usr/lib/locale/locale-archive`, but that path can change between operating systems, and versions of an operating system. If you statically linked the C standard library on one machine and then copied the binary over to another machine, you may also need to copy the locale data files across to the place the original machine's standard library expects to find them.

**Comment by h-bar** [comment]
Thanks for the detailed explanation. But from what I can see the 2 machines use the same location for locale data. But the locale-archive may not be the same since they are different OS and one is very outdated. I'll dig into it more on this approach to see if I can solve this.

Thanks!
