### ISSUE TITLE
<a-X> behavior

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#3708]
Given a block:
```
{
    line
}
```
Selecting it with `m` and then `<a-X>` ends up with two lines selected, like:
```
{
    line
```

Same block, but prepended with some word:
```
abc {
    line
}
```
gives one line selection like:
```
    line
```

I expected one line selection in first case as it is in second.

**Comment by lenormf** [comment]
This mapping [removes lines that aren't "full"](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#L169-L171), i.e. `^.+\n`, from the selection. In your reproducers, <kbd>m</kbd> doesn't select the newline character after `}`, and jumps to `{` (leaving `abc ` behind) - only `^    line\n` remains in both cases.

I don't know whether it's useful or should be changed, but the behaviour you describe is consistent.

**Comment by vbauerster** [comment]
Ok, I see it now. Thank you for explanation!
