### ISSUE TITLE
page up or down not working when there are long lines

### ISSUE THREAD

**Issue by eko234** [mawww/kakoune#3723]
### Steps 
i have a file with a line that is 5019 chars long to be exact, 
when i'm navigating the file with page up
or page down
### Outcome 
 it gets stuck close to that line
### Expected 
i guess that it should just keep going up or down, obviously, maybe it has something to do
with long lines collapsing and the way they are interpreted by kakoune.

**Comment by Screwtapello** [comment]
Are you using the wrap highlighter so you don't have to scroll horizontally to see long lines? If so, this is probably a duplicate of #1517.

**Comment by lenormf** [comment]
I think we can close this.

**Comment by eko234** [comment]
I think issue #1517 is way more elaborated and has more context, I'll close this one, thanks.
