### ISSUE TITLE
Python triple-quoted string with escaped quote before end breaks highlighter

### ISSUE THREAD

**Issue by natec425** [mawww/kakoune#3725]
### Steps

Type a quote-python string in a python buffer with an extra quote at the end.

For example `"""Hello\""""`

### Outcome

The syntax highlighting is broken for the rest of the file.

Screenshot taken from kakoune.
![Screenshot from 2020-09-11 18-02-01](https://user-images.githubusercontent.com/1424988/92979648-ea189380-f458-11ea-871b-c295c88c3b1c.png)

### Expected

The syntax highlighting should highlight the rest of the file correctly.

Screenshot taken from VS Code.

![Screenshot from 2020-09-11 18-04-57](https://user-images.githubusercontent.com/1424988/92979759-51cede80-f459-11ea-9a8b-f19a2fd90187.png)

**Comment by Aajn** [comment]
While fixing that problem I noticed another, but I am not sure how to fix it.
![image](https://user-images.githubusercontent.com/13387911/93259531-49034300-f7a0-11ea-9506-db55b079cc68.png)

**Comment by krobelus** [comment]
How about:

```kak
add-highlighter shared/python/docstring     region -match-capture ((?<!")"""|(?<!')''') (?<!\\)(?:\\\\)*("""|''') regions
```

That seems to match Python's behavior, at least on `"""""x"""`

**Comment by Aajn** [comment]
Breaking example:
![image](https://user-images.githubusercontent.com/13387911/93391651-d5c90200-f86f-11ea-81d0-dc4b1d0c47ac.png)

Python reference says that the strings need to be delimited by whitespace, but CPython doesn't complain. I think it's better not to handle this case.
https://docs.python.org/3/reference/lexical_analysis.html#string-literal-concatenation
