### ISSUE TITLE
Perl Highlighting Error

### ISSUE THREAD

**Issue by Carsenal** [mawww/kakoune#3736]
![Screen Shot 2020-09-15 at 3 17 34 PM](https://user-images.githubusercontent.com/23765149/93254619-9d89cc80-f766-11ea-8967-cbb61cbc2999.png)

Two highlighting errors in Perl shown above. =head regions aren't handled properly, and also q quoting. qq behaves the same way, but not qw, interestingly.

**Comment by Carsenal** [comment]
See also #3377

**Comment by Carsenal** [comment]
Also see also #2247. Maybe this is impossible to patch?

**Comment by krobelus** [comment]
I think both are fixable, the region start and end are on one line each.
Perl has quite some variants of heredoc syntax, I think these are important to fix since the can break highlighting for large areas.

**Comment by krobelus** [comment]
Minimal fixes which should be extended a bit; also `qw` could be added, there is only highlighting for `q` and `qq`.

```diff
diff --git a/rc/filetype/perl.kak b/rc/filetype/perl.kak
index 348b4cd3..e3988ee4 100644
--- a/rc/filetype/perl.kak
+++ b/rc/filetype/perl.kak
@@ -47,0 +48,2 @@ add-highlighter shared/perl/sregex        region s/[^/\n]+/[^/\n]+(?=/) /\w?
+add-highlighter shared/perl/pod           region ^=\w+  ^=cut       fill string
+
@@ -49 +51 @@ add-highlighter shared/perl/q1            region -recurse \{ q\{ \}
-add-highlighter shared/perl/q2            region -recurse \( q\( \)                fill string
+add-highlighter shared/perl/q2            region -recurse \( \bq\( \)                fill string
```

**Comment by Carsenal** [comment]
This works perfect. Thank you @krobelus

**Comment by krobelus** [comment]
we normally keep issues open until we have integrated a good solution

also `<<` heredoc support should be added; at least for the most commonly used variants

**Comment by Carsenal** [comment]
Sorry I closed it, didn't know better.
I've also found some new problems:
![Screen Shot 2020-09-16 at 4 44 55 PM](https://user-images.githubusercontent.com/23765149/93390710-20c92200-f83c-11ea-8bd1-2076ebf9a551.png)

**Comment by krobelus** [comment]
The fix for this should just be

```kak
add-highlighter shared/perl/qq4           region \bqq\| \|               fill string
```

I've been meaning to write up a pull request for Perl highlighting but I don't know when I'll get to it. I don't really know which quoting syntax is commonly used.
