### ISSUE TITLE
Add wayland.kak

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3743]

**Comment by Hardy7cc** [comment]
Hi, for the record at the moment I copied the x11-terminal command from here: 
[https://github.com/mawww/kakoune/blob/master/rc/windowing/x11.kak](url)
Within sway this works fine for generating new terminal instances. However I do not use the focus thing and I'm honest I'm not sure if it is that easy to implement some kind of focus switch.

**Comment by alexherbo2** [comment]
We can add commands such as `sway-focus` and alias it to `focus` when in [Sway].

[Sway]: https://swaywm.org
