### ISSUE TITLE
Highlighting in popup windows.

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#3750]
https://github.com/kak-lsp/kak-lsp/issues/395

**Comment by mawww** [comment]
`info` boxes support markup strings, see `:doc faces markup-strings`

**Comment by m-kru** [comment]
@mawww from what I see in the docs, there are no bold or italic builtin faces. However, for example bold, is used in the documentation.
![image](https://user-images.githubusercontent.com/26227737/93741109-1a47fb00-fbec-11ea-9b4a-a5f634b470ba.png)
How to get bold?

**Comment by Screwtapello** [comment]
```
info -markup "plain {+b}bold {+i}italic {+bi}bold italic"
```

See `:doc faces` for details. You don't have to use the pre-defined faces, you can use the modifiers on existing faces, or just use them alone to affect whatever face Kakoune would normally draw there.
