### ISSUE TITLE
static compilation - /usr/bin/ld: cannot find -lncursesw

### ISSUE THREAD

**Issue by asmarcz** [mawww/kakoune#3756]
Kakoune compiles just fine without the static option. What shall I do differently if I want to compile it statically?

### Steps 
`make static=yes`

### Outcome 
```
asmar:~/p/kakoune$ make static=yes
make -C src Makefile
make[1]: Entering directory '/home/asmar/projects/kakoune/src'
make[1]: Nothing to be done for 'Makefile'.
make[1]: Leaving directory '/home/asmar/projects/kakoune/src'
make -C src all
make[1]: Entering directory '/home/asmar/projects/kakoune/src'
g++ -static -pthread -rdynamic -O3 -pedantic -std=c++17 -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-address -Wno-init-list-lifetime .alias_registry.opt.o .assert.opt.o .backtrace.opt.o .buffer.opt.o .buffer_manager.opt.o .buffer_utils.opt.o .changes.opt.o .client.opt.o .client_manager.opt.o .color.opt.o .command_manager.opt.o .commands.opt.o .completion.opt.o .context.opt.o .display_buffer.opt.o .env_vars.opt.o .event_manager.opt.o .exception.opt.o .face_registry.opt.o .file.opt.o .hash.opt.o .hash_map.opt.o .highlighter.opt.o .highlighter_group.opt.o .highlighters.opt.o .hook_manager.opt.o .input_handler.opt.o .insert_completer.opt.o .json.opt.o .json_ui.opt.o .keymap_manager.opt.o .keys.opt.o .line_modification.opt.o .main.opt.o .memory.opt.o .ncurses_ui.opt.o .normal.opt.o .option_manager.opt.o .option_types.opt.o .parameters_parser.opt.o .ranges.opt.o .ranked_match.opt.o .regex.opt.o .regex_impl.opt.o .register_manager.opt.o .remote.opt.o .scope.opt.o .selection.opt.o .selectors.opt.o .shared_string.opt.o .shell_manager.opt.o .string.opt.o .string_utils.opt.o .unit_tests.opt.o .window.opt.o .word_db.opt.o .version.o -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -lncursesw  -o kak.opt
/usr/bin/ld: cannot find -lncursesw
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:108: kak.opt] Error 1
make[1]: Leaving directory '/home/asmar/projects/kakoune/src'
make: *** [Makefile:2: all] Error 2
```
### Expected 
Compiled statically linked binary.

**Comment by Screwtapello** [comment]
Sounds like you have the dynamic version of ncursesw (`libncursesw.so`) but not the static version of ncursesw (`libncurses.a`). On Debian Linux, both the static and dynamic versions of the library are installed as part of the "libncurses-dev" package, but you'll have to look up how your platform organises such things.

**Comment by asmarcz** [comment]
Thank you, the problem was indeed the absence of the static version of ncursesw. I wasn't aware Manjaro (Arch Linux) doesn't ship static versions most of the time.

One thing I am not sure about is this warning:
```
/usr/bin/ld: .file.opt.o: in function `Kakoune::parse_filename(Kakoune::StringView, Kakoune::StringView)':
/kakoune/src/file.cc:146: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

For anyone's use, instead of manually installing the library I put together a Docker image to build Kakoune for me:

```
FROM buildpack-deps:buster as refresh

RUN TAG="$(curl -s 'https://api.github.com/repos/mawww/kakoune/releases/latest' | \
    python3 -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")" && \
	git clone -b "$TAG" --depth 1 https://github.com/mawww/kakoune

FROM refresh as compile

WORKDIR /kakoune

RUN make static=yes && \
	mkdir /out && \
	cp src/kak /out

VOLUME /out
```

Run with:
```
docker build -t ks:1 . && docker create --name kak ks:1 && docker cp kak:/out/kak ./kak && docker rm kak && docker rmi ks:1
```

**Comment by Screwtapello** [comment]
> One thing I am not sure about is this warning

Static linking does not guarantee a binary that will run without external dependencies.

For example, libc has functions like `getpwuid` that retrieve information about user accounts on the system. The Linux libc implementation can be configured to consult external user databases like LDAP or NIS, and it loads this functionality dynamically. If you build a static binary on one system and copy it to another, it will have hard-coded references to that configuration, which can cause problems if the destination system is not very much like the original.

Another issue is locale information. Kakoune requires a locale that supports UTF-8, and uses the libc locale information to predict how wide a particular line of text should be drawn. Again, if you build a static binary, it will have hard-coded assumptions to the location and format of locale data.

If the static binary you made starts up properly — great! You'll probably be fine. But if you encounter weirdness in future, it may be related to that.
