### ISSUE TITLE
Cannot name user mode like a regular mode

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3758]
### Command

``` kak
declare-user-mode view
```

### Error

```
'declare-user-mode' 'view' is already a regular mode
```

**Comment by Screwtapello** [comment]
If that worked, then what would you expect `map global view x y` to do? Should it add that mapping to the user mode or to the regular mode?

**Comment by alexherbo2** [comment]
Good point.  In other commands (enter user mode and hook parameters) the use of user modes is explicit but not in mappings.

**Comment by mawww** [comment]
Yep, dont think we really need that feature.
