### ISSUE TITLE
Color miscalculation

### ISSUE THREAD

**Issue by YoueG** [mawww/kakoune#3763]
### Steps

Use a color scheme, for instance I used base16-gruvbox-dark-hard.kak from https://github.com/andreyorst/base16-gruvbox.kak

The background is set to "1d2021"

### Outcome

Resulting color is "1c1f20" (all components get +1) on screen

### Expected

Color should be "1d2021"

**Comment by Screwtapello** [comment]
In gnome-terminal 3.38, I launched Kakoune with `kak -n`, then ran:

    set-face global Default default,rgb:1d2021

This changed the background colour, then I used `xmag` to take a screenshot and check the colour value, and it was exactly `#1d2021`.

It also worked fine in xterm, pterm (PuTTY), and kitty. urxvt doesn't seem to support 24-bit colour at all, and qterminal  apparently snapped the value to the closest entry in the 256-color palette.

**Comment by lenormf** [comment]
Relevant FAQ item https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#why-are-colors-misrendered-in-my-kakoune-clients

Kakoune will calculate an approximation of the target colour if the terminal doesn't support TrueColor.

**Comment by YoueG** [comment]
It's strange I'm also using kitty, but under sway and I took the screenshot with grim.

**Comment by mawww** [comment]
If you are not on the builtin-terminal-ui branch you wont get true colors, and then you need a terminal that supports palette changes through ncurses. This depends on wether your terminfo (defined by the TERM env var) contains the relevant capability. Please check TERM matches your terminal and exposes palette change support (assuming kitty does indeed support that)

**Comment by YoueG** [comment]
Just updated my system and  colors are correct this time.
Closing this issue ;)
