### ISSUE TITLE
Wrong highlighter in haskell with #

### ISSUE THREAD

**Issue by tgirod** [mawww/kakoune#3769]
When editing a haskell file, a line starting with `#` or blanks + `#` won't be properly highlighted. Instead the whole line is of the same color (not the same color as comments, but the same as a line starting with `#!`, if it helps).

https://asciinema.org/a/fhlmxDdMLQr5gutyVhu4G6ksJ

**Comment by tgirod** [comment]
is there an easy way to find which highlighter is responsible of some text highlighting?

**Comment by f380cedric** [comment]
I guess it is  due to https://github.com/mawww/kakoune/blob/dd1a582b30cc17c3e484fe77b917485ff7a2ff16/rc/filetype/haskell.kak#L38
It is referenced as 'macro' and is there since the creation of the haskell syntax highlighter in kakoune.
I guess it was here to highlight C macro in haskell.

I do not know much about haskell but since `#` is the *Magic Hash*, I guess we should avoid highlighting it?

**Comment by krobelus** [comment]
`ghc` uses the C preprocessor, so this is expected.
Is there a legitimate Haskell program where the `#` at the start (modulo whitespace) of a line has another meaning? :thinking:

**Comment by tgirod** [comment]
>  Is there a legitimate Haskell program where the `#` at the start (modulo whitespace) of a line has another meaning?

Yes, [TidalCycle](https://tidalcycles.org/) uses the operator `#` quite extensively, which gives you code that usually looks like this:

```haskell
let beats = cI 1 "9"
    off = cI 0 "10"
    length = (cI 0 "11")
    skip = (cI 1 "12")
    degrees = (skip * run length) `mod` scaleLength
    prog = scale scaleName degrees
in d2
    $ (euclidOff beats steps off $ sound "bass:2")
    # note prog
    # octave 4
    # cut 1
    # gain 0.7
    # coarse 6
    # room 0.5 |> size 0.5
    # lpf 1000
```

... and apparently github's code highlighting is ok with that.

**Comment by krobelus** [comment]
> highlighting is special only when # is the first character of the line.

That sounds like a good compromise.

**Comment by danr** [comment]
Then remove `\h*?` from `^\h*?\K#` above and it should be fixed

**Comment by f380cedric** [comment]
The issue has been fixed. Could you close it?

**Comment by tgirod** [comment]
right!
