### ISSUE TITLE
Load plugin at first call to speed up startup time

### ISSUE THREAD

**Issue by sucrecacao** [mawww/kakoune#3770]
The problem is that when you have 20+ plugin installed, it start to sinificantly slow down startup time, but one usually don't need those 20 feature at startup. So the goal is to load them little by little. Maybe a solution could be to load them in parallele but if I recall well kakoune doesn't support multi-processing.

### Feature 

Load a plugin only when one of its function and/or key-mapping is called 

### Usecase 
Plugin doesn't impact startup time. 

Let's say all plugin take 0.01s to load. If you have 20 plugin, you will fell the slow down at startup. But you won't feel much of a difference if the first time you call a function it take 0.01s more. 

Also, some plugin's function won't be called at all during a whole kakoune session, so it's a waist of time to call them at startup.

**Comment by lenormf** [comment]
Are you talking about some third party manager, or just files in `autoload`?

**Comment by sucrecacao** [comment]
Both I guess.
In my case, most time consumption come from plugin I have installed with the `plug` plugin manager. But I think I should not matter how or where the plugin is installed.

**Comment by Screwtapello** [comment]
Kakoune already has the module system (`:provide-module` and `:require-module`) so expensive operations can be postponed until they're necessary.

It's not really possible to delay loading a plugin until a function or key-mapping is used: if you haven't loaded the plugin, you don't know what its functions or key-mappings are. If you load the plugin to find out what its functions and key-mappings are, well, you've already loaded the plugin so there's no point loading it again. If plugins need to keep their functions and key-mappings separate from the parts that are expensive to load, well that's the module system again.

**Comment by lenormf** [comment]
In that case you should probably create an issue on the plugin manager's repository, as it's not being maintained here. Kakoune itself has no notion of plugin, only files containing Kakoune code.

If you have problems with files in `autoload` taking too much time, you could use the `provide-module` command, and load code on-demand with `require-module`. If that still isn't enough, measure and report the slow-down you experience — Kakoune loads dozens of files in a default installation quite quickly, so it'd be surprising if 20 files were noticeably slow to load.

**Comment by sucrecacao** [comment]
Makes senses. Th solution might simply be to provide some good practice and examples of creating plugin with `require-module` and `provide-module` to the wiki. Hopefully I work on it on day :)

For people reading this trying to boost their startup time: you should have a look a `kak -c`

**Comment by alexherbo2** [comment]
@sucrecacao Notice with plug.kak you pay multiple sh calls per plugin to load.

**Comment by andreyorst** [comment]
> It's not really possible to delay loading a plugin until a function or key-mapping is used: if you haven't loaded the plugin, you don't know what its functions or key-mappings are.

Well, actually, fzf.kak works almost like this. Until you run `fzf-mode` command (which user typically binds to some key, like <kbd>Ctrl+p</kbd>, as I don't provide default keybindings outside fzf user mode) module isn't required:

```
fzf-mode %{ require-module fzf; evaluate-commands 'enter-user-mode fzf' }

provide-module fzf %§
... rest of the plugin's code
§
```

So it is possible to delay _requiring_ if plugin has single entry point, and in case of fzf.kak it saved quite a some time.

---

@sucrecacao, you can significantly speedup startup time with plug.kak by using `dash` as your Kakoune shell instead of `bash` by setting `KAKOUNE_POSIX_SHELL` environment variable. I know that plug.kak isn't the fastest, but I have used it on the phone with `dash` with quite fine startup time (e.g. faster than Vim or Emacs with more or less equivalent configs).

**Comment by sucrecacao** [comment]
@andreyorst I'm already using dash and startup time is ~.35 sec  which is okay but not instant. I have around 13 plugins.
