### ISSUE TITLE
Make `o` trigger InsertChar newline hooks

### ISSUE THREAD

**Issue by SeerLite** [mawww/kakoune#3775]
### Feature 
Make `o` trigger `InsertChar \n` hooks.
Basically like mapping `o` to `A<ret>`.

### Usecase 
If I'm on a line like this (`|` is cursor):
```python
|def example():
    print("Example")
```
pressing `o` would activate the `-indent` hooks:
```python
def example():
    |
    print("Example")
```

I don't know of any usecase where doing `o` and not indenting would be wanted. If it's just to insert a blank line, `<a-o>` would do it without activating hooks.

Tell me what you think!

**Comment by krobelus** [comment]
It already does that! On v2020.09.01 and latest master.

**Comment by SeerLite** [comment]
Wow, looks like I had remapped `o` to something else for a workaround and forgot.
Thanks!
