### ISSUE TITLE
Add `u` and `U` aliases to `enter-user-mode` with and without `-lock`

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3781]
It could be nice to quickly fuzzy-search and enter user modes.

**Comment by alexherbo2** [comment]
https://github.com/Delapouite/kakoune-user-modes#tips

**Comment by mawww** [comment]
Aliases only reference command names, they cannot contain extra arguments such as `-lock`. Additionally, as said in another issue, I think we should move away from aliases as a way to accelerate command writing and improve the completion support instead. This is the reason for the recent change to auto-complete on `<space>` for command names, `:eum<space>` will expand to `:enter-user-mode `.

**Comment by alexherbo2** [comment]
@mawww The expansion does not happen for parameters.

``` kak
map g n <ret> :
```
