### ISSUE TITLE
Add `gn` and `gp` aliases to `grep-next-match` and `grep-previous-match` commands

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#3784]

**Comment by mawww** [comment]
I am not really keen on that, I think the general direction with aliases is to use them as an abstraction mechanism (like the `terminal` alias that can have different implementation) while the fuzzy completion system is used for quickly entering the command.

I'd be more keen on making the command prompt auto-expand the command name (auto-tab) on space.

**Comment by AndrewVos** [comment]
I can't seem to create these mappings myself. Any ideas why?

I've tried:

```
map global goto n ': grep-next-match'
```

But this just seems to select the next word :thinking:

**Comment by AndrewVos** [comment]
Never mind, I just needed an `<esc>` for some reason.

```
map global goto n ': grep-next-match<ret>'

```

**Comment by alexherbo2** [comment]
@AndrewVos Mappings start in the mode they are defined.  Prefix your mapping with <kbd>Escape</kbd> or <kbd>Alt</kbd> + <kbd>;</kbd> to return to the normal mode before entering your command.

**Comment by mawww** [comment]
Kind-of fixed with the changes to command name auto completion.
