### ISSUE TITLE
Region highlighter with empty -match-capture does not correctly match closing regex

### ISSUE THREAD

**Issue by krobelus** [mawww/kakoune#3799]
Turns out Perl supports empty heredocs. Here is a simple example I had expected to work:

### Steps 

```sh
$ echo 'print << "";
heredoc closed by empty line' |
kak -n -e '
add-highlighter global/regions regions
add-highlighter global/regions/heredoc region -match-capture <<\h*"(\w*)" ^(\w*)$ fill red
'
```

### Outcome 

The text `<< "";` is highlighted red.

### Expected 

The second line should be red as well.

It works when I use a non-empty heredoc, like `"EOF"`.

**Comment by mawww** [comment]
Sneaky one, thanks for reporting that
