### ISSUE TITLE
How do you automatically lint files?

### ISSUE THREAD

**Issue by AndrewVos** [mawww/kakoune#3807]
Hi, I'm using the `lintcmd` setter for shellcheck as specified in the docs, and `:lint` is working beautifully.

```
# lint shell files
hook global WinSetOption filetype=sh %{
  set-option window lintcmd "shellcheck -fgcc -Cnever"
}
```

My problem is that I want to automatically lint files. I don't want to have to type `:lint`, but only for shell files, because it's really fast.

It seems `lint-enable` used to do this, before the August release. This seems to have been removed. Is there another way to enable automatic linting whenever the buffer changes?

Thanks!

**Comment by lenormf** [comment]
I have the following section in my configuration:

```kak
# Linters
hook global WinSetOption filetype=c %{
    set-option window lintcmd "cppcheck --language=c --enable=warning,style,information --template='{file}:{line}:{column}: {severity}: {message}' --suppress='*:*.h' 2>&1"
}

hook global WinSetOption filetype=cpp %{
    set-option window lintcmd "cppcheck --language=c++ --enable=warning,style,information --template='{file}:{line}:{column}: {severity}: {message}' --suppress='*:*.h' --suppress='*:*.hh' 2>&1"
}

hook global WinSetOption filetype=sh %{
    set-option window lintcmd "shellcheck -fgcc -Cnever"
}

hook global WinSetOption filetype=d %{
    set-option window lintcmd "dscanner -S --errorFormat '{filepath}:{line}:{column}: {type}: {message}'"
}

hook global WinSetOption filetype=python %{
    set-option window lintcmd "flake8 --filename='*' --format='%%(path)s:%%(row)d:%%(col)d: error: %%(text)s' --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E501,E221,E127,E128,E129,F405"
}

hook global WinSetOption filetype=(asciidoc|fountain|markdown|plain) %{
    set-option window lintcmd "proselint"
}

# Enable automatic linting for the above supported filetypes
hook global WinSetOption filetype=(c|cpp|sh|d|python|asciidoc|fountain|markdown|plain) %{
    hook buffer BufWritePost "\Q%val{buffile}" lint
}
```

The last scope runs linting when I save the buffer. Running it on every keypress might be too much (although I haven't tried, cc @eraserhd), so you might want to use the `NormalIdle` hook.

**Comment by AndrewVos** [comment]
@lenormf this is great, thank you very much.

I was hoping there was something like `NormalIdle`!

**Comment by AndrewVos** [comment]
@lenormf One other question, I've noticed in some places the docs say to use `BufSetOption` instead of `WinSetOption`. Why is that different in some places? I would expect `BufSetOption` to be the one to use (because it only works per-buffer, if I understand correctly).

**Comment by Screwtapello** [comment]
The difference between `BufSetOption` and `WinSetOption` is the difference between the buffer and window [scopes](https://github.com/mawww/kakoune/blob/master/doc/pages/scopes.asciidoc).

By convention, filetype-related things are set at window scope, so you can have two windows looking at the same buffer, but with different highlighting, etc. For example, if you had a file that contained a mixture of C and Markdown content, Kakoune doesn't provide c-and-markdown syntax highlighting, but you could set `filetype=c` in one window and `filetype=markdown` in another, and switch between the windows as appropriate for whichever part of the file you were working on.

**Comment by AndrewVos** [comment]
I see @Screwtapello that makes sense thank you.
