### ISSUE TITLE
kakoune and fzf

### ISSUE THREAD

**Issue by cvlmtg** [mawww/kakoune#383]
I'm playing a bit with kakoune and fzf and I'm having a couple of issues

1) I'm able to have a fuzzy selector for the buffers, but if I select the buffer currently displayed, the screen is completely erased except for the status line and I have to move the cursor to force a redraw

2) the file selector is not working as fzf opens with an empty list and I still haven't figured out what's wrong...

```
def·-docstring·'invoke·fzf·to·open·a·file'·\¬
··fzf-file·%{·%sh{¬
····if·[·-z·"$TMUX"·];·then¬
······echo·echo·only·works·inside·tmux¬
····else¬
······FILE=`ag·-l·-g·""·|·fzf-tmux·-d·15`¬
······if·[·-n·"$FILE"·];·then¬
········echo·"eval·-client·'$kak_client'·'edit·${FILE}'"·|·kak·-p·${kak_session}¬
······fi¬
····fi¬
}}¬
¬
def·-docstring·'invoke·fzf·to·select·a·buffer'·\¬
··fzf-buffer·%{·%sh{¬
····if·[·-z·"$TMUX"·];·then¬
······echo·echo·only·works·inside·tmux¬
····else¬
······BUFFER=`echo·${kak_buflist}·|·tr·:·'\n'·|·fzf-tmux·-d·15`¬
······if·[·-n·"$BUFFER"·];·then¬
········echo·"eval·-client·'$kak_client'·'buffer·${BUFFER}'"·|·kak·-p·${kak_session}¬
······fi¬
····fi¬
}}¬
¬
map·global·user·f·:fzf-file<ret>¬
map·global·user·b·:fzf-buffer<ret>¬
```

**Comment by mawww** [comment]
Hello, for the redrawing problem, I think I get what is going in, kakoune gets resized twice while the shell is running, and the second resize puts it back to his original size. In the current implementation that will not trigger a redraw, I'll see how that can be fixed.

**Comment by mawww** [comment]
I did not install fzf to try here, but I expect that commit to fix the resizing bug, please confirm it does when you get the chance.

For the other thing, (empty fzf list), it does not seem like a kakoune bug, as using the buffer list works, I guess you should check whats happening with your ag command.

**Comment by cvlmtg** [comment]
thanks, the resize bug is gone. I'll try to investigate the fzf bug. can you confirm my functions are correct?  I'm not sure if I misunderstood something about %sh{} and wrote something wrong...

**Comment by mawww** [comment]
Well, for `ag` the one I have here does not support a `-g` option, and for what you try to do, the `find` command might be more appropriate.

**Comment by cvlmtg** [comment]
ag is used because it takes into consideration .gitignore files, .hgignore etc... and this is handy when navigating repositories. the -g option is indeed correct, but I don't remember which version introduced it.

**Comment by cvlmtg** [comment]
btw If I run that command in a shell it works correctly, that's why I was wondering if I made some mistake in my kakrc file rather than the ag/fzf command itself

```
bash-3.2$ FILE=`ag --nocolor --depth=10 -l -g '' | fzf-tmux -d 15`
bash-3.2$ echo $FILE
dotfiles/vimrc
```

**Comment by mawww** [comment]
Anything in the *debug* buffer, you'll get %sh stderr output written there.

**Comment by Kareeeeem** [comment]
Anyone have any ideas about this? Having the same problem.

**Comment by mawww** [comment]
Hello, do you mean you are using that same snippet and no options are displayed in fzf ?

**Comment by Kareeeeem** [comment]
Yes. It works fine when using the `find` command but not with ag. And like cvlmtg it works fine on it's own.

**Comment by mawww** [comment]
and is anything written in the `*debug*` buffer ? if ag writes to stderr it should end up there.

**Comment by Kareeeeem** [comment]
Nothing in the debug buffer.

**Comment by Kareeeeem** [comment]
the issue without the surrounding stuff with tmux or scripts.

this works: `files=$(ag -g ""); echo $files` (in shell)
this works: `:%sh{files=$(find * -type f); echo echo $files}` (in kakoune)
this doesn't: `:%sh{files=$(ag -g ""); echo echo $files}` (in kakoune)

**Comment by mawww** [comment]
Thanks for these repro cases, there is definitely something fishy going on, I need to investigate that a bit more.

**Comment by lenormf** [comment]
When running `ag -g ''` in `strace` from `kak`, I get the following output:

```
[…]
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
read(3, "0-3\n", 8192)                  = 4
close(3)                                = 0
mmap(NULL, 65536, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f80af0c7000
fstat(0, {st_dev=makedev(0, 10), st_ino=201011, st_mode=S_IFIFO|0600, st_nlink=1, st_uid=1000, st_gid=100, st_blksize=4096, st_blocks=0, st_size=0, st_atime=2016/04/12-11:33:03.117804735, st_mtime=2016/04/12-11:33:03.117804735, st_ctime=2016/04/12-11:33:03.117804735}) = 0
read(0, "", 4096)                       = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

`ag` is setting up the threading support by reading `procfs`, then tries to read `stdin` and exits with an error code. I was wondering why `ag` would read `stdin` in this particular case (it doesn't when being used in the CLI), and I found the following code in the `ag` source:

`main.c:137`
```
    if (opts.search_stream) {
        search_stream(stdin, "");
```

There doesn't seem to be any option in `ag` to trigger the `search_stream` option, it is automatically set by `ag` itself with the following code;

`options.c:324`
```
    rv = fstat(fileno(stdin), &statbuf);
    if (rv == 0) {
        if (S_ISFIFO(statbuf.st_mode) || S_ISREG(statbuf.st_mode)) {
            opts.search_stream = 1;
        }
    }
```

Remember the `fstat` call from the `strace` output I pasted above ? I think that's the one, and as you can see in the dereferenced `stat` structure, `st_mode` is set to `S_IFIFO`, which apparently triggers the stream option.

Haven't done much else, but I think that's pretty much the issue: `ag` tries to read `stdin`, probably incorrectly (as far as I've seen in `shell_manager.cc`, the file descriptor moves are pretty standard).

HTH.

**Comment by lenormf** [comment]
Hot fix, until the official fix is merged upstream:

```
diff --git a/src/shell_manager.cc b/src/shell_manager.cc
index 26010e1..54706fe 100644
--- a/src/shell_manager.cc
+++ b/src/shell_manager.cc
@@ -128,11 +128,12 @@ std::pair<String, int> ShellManager::eval(
 
     Pipe child_stdin, child_stdout, child_stderr;
     pid_t pid = spawn_shell(cmdline, shell_context.params, kak_env,
-                            [&child_stdin, &child_stdout, &child_stderr] {
+                            [&] {
         auto move = [](int oldfd, int newfd) { dup2(oldfd, newfd); close(oldfd); };
 
         close(child_stdin.write_fd());
-        move(child_stdin.read_fd(), 0);
+        if (input.length())
+            move(child_stdin.read_fd(), 0);
 
         close(child_stdout.read_fd());
         move(child_stdout.write_fd(), 1);
```
