### ISSUE TITLE
kak -d not working

### ISSUE THREAD

**Issue by zcorniere** [mawww/kakoune#3832]
### Steps 
`kak -s whatever  -d `

### Outcome 
kakoune does not exit, and block terminal. SIGINT does not stop it. 
The session socket is actually binded, and the session name can't be reused.

### Expected 
kakoune run in backgroud, with session name "whatever"

**Comment by zcorniere** [comment]
`kak -version` 2020.09.01

**Comment by occivink** [comment]
This was a conscious change from the previous forking behavior, see #3618

**Comment by zcorniere** [comment]
Oh sorry, didn't knew that.

If I understood correctly, to have the behaviour I expected, I must type something like `setsid kak -d -s whatever &`, right ?
