### ISSUE TITLE
How to handle session scoped file type configurations in concise way.

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#3838]
Here is the problem. In `kakrc` I have configuration for different file types defining how `Tab` key should be treated. 
In case of Go language it is fine, as all projects use tabs. However, in case of for example C language the story is a bit different.
Some of the projects use tab for indentation, some use spaces. I wonder if it is possible to somehow configure how the tab key should behave based on the file path. Or maybe there is some better way. Has anyone encountered such problem?

**Comment by Screwtapello** [comment]
This is the sort of thing that https://editorconfig.org/ was created to solve, and Kakoune supports that (if you install [the right helper](https://github.com/mawww/kakoune/wiki/EditorConfig)).

For a more general solution, there's plugins like [Hestia](https://discuss.kakoune.com/t/hestia-plugin-to-load-project-machine-specific-configurations-securely/1208).
