### ISSUE TITLE
[not an issue] a bit of fun

### ISSUE THREAD

**Issue by robinmoussu** [mawww/kakoune#384]
Hi,
I've found on archive.org [that page](https://web.archive.org/web/20061111034118/http://blogs.sun.com/marigan/entry/how_the_vi_editor_would), and I instantly thought about kakoune!
Of course that post should better fit in a forum, but I don't found one.
Cheers :)

**Comment by mawww** [comment]
Yeah, that gif is one of the inspirations for the info assistant (used to be an easter egg in kakoune actually, there was a `-assist` undocumented option for the `:info` command)
