### ISSUE TITLE
How to select and copy everthing from prompt to system clipboard

### ISSUE THREAD

**Issue by blueray453** [mawww/kakoune#3840]
I could not find anything to select text from prompt.

For example, I use:
```
map global prompt <c-right> <a-f>
map global prompt <c-left> <a-b>
```
to jump to previous word.

Is there anything like:

```
map global prompt <s-right> select-next-char
map global prompt <s-left> select-previous-char
map global prompt <c-shift-right> select-next-word
map global prompt <c-shift-left> select-previous-word
```
I think `<s-right> & <s-left>` works in normal mode.

Being said that, is there any trick to save the following prompt commands to system clipboard.

```
<c-w>

    erase to previous word begin, save erased content to clipboard
<c-W>

    erase to previous WORD begin, save erased content to clipboard
<a-d>

    erase to next word begin, save erased content to clipboard
<a-D>

    erase to next WORD begin, save erased content to clipboard
<c-k>

    erase to end of line, save erased content to clipboard
<c-u>

    erase to begin of line, save erased content to clipboard
<c-y>

    insert clipboard content before cursor

```
For example, I am current using:

`map global normal y '<a-|> xsel --input --clipboard <ret>'`

**Comment by Screwtapello** [comment]
The prompt itself does not support any kind of selection, there's just a cursor you can move around. Likewise, I don't think you can add extra behaviours to prompt-mode mappings - in normal mode you can do fancy things by temporarily switching to other modes (prompt mode, pipe mode, etc.) but from prompt mode I don't think you can push another temporary prompt mode on top.

If the prompt were another buffer (#801), this could work, but it isn't, so it doesn't.

That said, at the Kakoune prompt (and in any other terminal application) you can copy text to the clipboard by holding shift, selecting it with the mouse, and (depending on the terminal emulator) pressing some copy-to-clipboard key. On GNOME Terminal, that's Ctrl-Shift-C, but other emulators may be different.

**Comment by blueray453** [comment]
Thank you very much.

**Comment by blueray453** [comment]
is "making prompt another buffer" in your roadmap?

**Comment by Delapouite** [comment]
See https://github.com/mawww/kakoune/issues/801

**Comment by theowenyoung** [comment]
I need this function too. mainly cause I use prompts to find some commands I don't familiar with, then I need to copy these commands to my `kakrc` file, I just can't find a proper way to do it.
