### ISSUE TITLE
Right way to empty a list option?

### ISSUE THREAD

**Issue by SeerLite** [mawww/kakoune#3843]
Hi!
I want to be able to empty a global string option. `unset-option` isn't a possibility because it only works for non-global options.
So my question is what's the right way to empty a list (specifically a str-list) at global scope? Currently I'm doing the following to accomplish it:
```kak
set-option global my_list ''
set-option -remove global my_list ''
```

Maybe `unset-option` should work on global options and empty them?

Thanks

**Comment by occivink** [comment]
You can actually just pass no arguments, so `set-option global my_list`

**Comment by alexherbo2** [comment]
The correct way is:

``` kak
set-option global my_list
```

If you do:

``` kak
set-option global my_list ''
```

the list will have one element with an empty string.

**Comment by SeerLite** [comment]
Ok lol that never occurred to me! Thank you both!

Maybe a note about this could be added to `doc options`.
