### ISSUE TITLE
HTML/js highlighter wrong on `/`

### ISSUE THREAD

**Issue by JJK96** [mawww/kakoune#3856]
Filetype `html`

File contents:
```
<script>
    let a = 1/2
    let b = 3
</script>
```
![Screen Capture_select-area_20201029184831](https://user-images.githubusercontent.com/11193274/97612224-7554e500-1a17-11eb-9418-7c9d512a4de5.png)

**Comment by Ordoviz** [comment]
javascript.kak takes the slash as start of a regex.

https://github.com/mawww/kakoune/blob/90043e7df04359ec9ef629fa46fc6a524673be84/rc/filetype/javascript.kak#L84

**Comment by Carsenal** [comment]
Found similar behavior in pure js.
![Screen Shot 2020-11-03 at 9 56 08 AM](https://user-images.githubusercontent.com/23765149/98000813-e8b17a80-1dba-11eb-8993-3406d6f2f46c.png)'
I wrote a regex that would not misbehave (`\/.*[^\\]\/[gimy]*`), but kakoune is fighting me on using the regex. Hopefully I can push a fix soon, if someone more knowledgeable about region structuring than me can maybe tell me whats wrong with:
`javascript.kak:84: add-highlighter "shared/%arg{1}/regex"         regex /.*[^\\]/[gimuy]*             0:meta`
That'd be greatly appreciated.

**Comment by Carsenal** [comment]
I had deleted that line in my testing, however, but I don't get the behavior in a blank buffer like you said
