### ISSUE TITLE
Change the default face for Python docstring from string to comment.

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#3857]
Docstring in Python files uses `string` face as the default one. I think it is bad idea. When you have both strings and docstrings on the display they blends together.
Example:
![image](https://user-images.githubusercontent.com/26227737/97631501-5fecb480-1a31-11eb-9be0-14fd1ba5e59e.png)

After potential change to comment.
![image](https://user-images.githubusercontent.com/26227737/97631591-7dba1980-1a31-11eb-874c-6acbd4cfb979.png)

**Comment by caksoylar** [comment]
As you might know the other main use case of triple quotes is to define strings than can contain newlines:
```python
my_long_string = """This is a multi-line string,
where this is the second line
    then you can even have indented lines like this one.
"""
print(my_long_string)
print("""Another one with a newline at the end.
""")
```

Is there a reliable and robust way to detect whether a triple-quoted string is a docstring or a regular string? Vim also seems to not make this distinction. This change would be good for docstrings as long as we can reliably detect which one it is.

**Comment by lenormf** [comment]
I advised that change in the [PR that introduces the `documentation` face](https://github.com/mawww/kakoune/pull/2149#issuecomment-399643223).

Triple strings could be highlighted as `documentation` if they are not assigned to a variable, e.g. `^\h*"{3}\b`.

**Comment by m-kru** [comment]
We should also cover following valid variable assignment:
```Python
TEXT = \
"""Some
multiline
text."""

print(TEXT)
```

**Comment by m-kru** [comment]
I was trying to fix this. However, I do not understand what is the meaning of `(?<!\\)(?:\\\\)*` within
```kakoune
add-highlighter shared/python/docstring  region -match-capture ("""|''') (?<!\\)(?:\\\\)*("""|''') regions
```

**Comment by lenormf** [comment]
This bit makes sure that the closing quote is not escaped.
