### ISSUE TITLE
Distinguish <c-h> and Backspace on terminals where that is possible.

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#3863]
## Feature 

Some (many?) terminals in common use today send different codes for Ctrl-H versus Backspace. Kakoune should support that distinction where it's available.

### Usecase 

See #1030, #1270, #3250 

## Notes

The original VT100 terminal had a key above the Enter key labelled "Backspace" that sent 0x08, and another nearby key labelled "Delete" that sent 0x7F.

The VT220 terminal had a key above the Enter key labelled ⌫ that sent 0x7F, and another nearby key labelled "Delete" that sent 0x1B 0x5B 0x33 0x7E, although it could be configured to use the VT100 conventions for compatibility.

Since different terminals followed different conventions, the Unix kernel added support for tracking "what does backspace send" so the kernel's built-in line-editing would work everywhere. Since this is one of the terminal settings from the Before Time (predating termcap/terminfo/curses, I believe) and since getting it wrong is near-instantly visible (backspace doesn't work in the shell!), it's extremely reliable.

(if you'd like to see what *your* terminal is configured to send for backspace, try running `stty -a | grep erase`)

In fact, Kakoune already reads this setting at startup, it just doesn't do anything with it. Inside `NCursesUI::get_next_key()`, instead of detecting Backspace by comparing the incoming character code to `ctrl('h')` or `127`, we could compare it to `m_original_termios.c_cc[V_ERASE]`, and then whichever keycode was *not* backspace could be decoded normally (0x08 as `<c-h>`, 0x7F as `<delete>`).

Unfortunately, Kakoune's current input-parsing code is built on a bunch of inline lambda functions, which are very picky about which values from outer contexts they can access, and apparently "member variables of the enclosing class" are not on the list. I'd make a PR, but I lack the C++ skill to rearrange the code to fit.

**Comment by krobelus** [comment]
Thanks for the nice writeup (as always!)

The `convert` lambda is `constexpr`, which means that it can only access compile time constants.
We can remove the `constexpr` and capture the erase setting by copying it into the static lambda.
Since it's static, that only happens once - `convert` will always use the `erase` value from the first call.
This seems alright since we don't expect the value to change, or do we?
(Beware, completely untested)

```diff
diff --git a/src/ncurses_ui.cc b/src/ncurses_ui.cc
index e52748c9..0e4fd1b7 100644
--- a/src/ncurses_ui.cc
+++ b/src/ncurses_ui.cc
@@ -610,12 +610,13 @@ Optional<Key> NCursesUI::get_next_key()
     if (not c)
         return {};
 
-    static constexpr auto convert = [](Codepoint c) -> Codepoint {
+    const cc_t erase = m_original_termios.c_cc[VERASE];
+    static auto convert = [erase](Codepoint c) -> Codepoint {
         if (c == control('m') or c == control('j'))
             return Key::Return;
         if (c == control('i'))
             return Key::Tab;
-        if (c == control('h') or c == 127)
+        if (c == erase)
             return Key::Backspace;
         return c;
     };
```
