### ISSUE TITLE
Regex Parsing

### ISSUE THREAD

**Issue by Carsenal** [mawww/kakoune#3864]
I was working on a fix for #3856 and I ran into issues with regex. While testing regexes in `javascript.kak`, I noticed the following behavior:
The following two rules, formatted the same except for the replacement of `/` with `x`:
![Screen Shot 2020-11-03 at 10 30 57 AM](https://user-images.githubusercontent.com/23765149/98006305-11883e80-1dc0-11eb-9694-d3e51e4657a4.png)
Only highlights the bottom of the two examples.
![Screen Shot 2020-11-03 at 10 30 31 AM](https://user-images.githubusercontent.com/23765149/98006279-09c89a00-1dc0-11eb-9cde-1d32c247bf08.png)
If I try to escape the `/` with `\/`, I get an error in kakoune about invalid regex parsing. Additionally, `:doc highlighters` and `:doc regex` provides no insight.

Is this a bug? Am I making a stupid mistake? Both?

**Comment by mawww** [comment]
Hello,

If I create an empty buffer and add only those two highlighters, things are working fine, I think the issue you have comes from line 84 in javascript.kak:

```
    add-highlighter "shared/%arg{1}/regex"         region /    (?<!\\)(\\\\)*/[gimuy]* fill meta
```

That means the `/` in `let foo = /...` starts a region called "regex". So your highlighter that apply to the default "code" region wont be applied here.

**Comment by Carsenal** [comment]
I had removed that line in my testing though.

However, if I open a scratch buffer you're right that it works. I'm unsure what the issue is.

**Comment by Carsenal** [comment]
Oops it was the division regex in `javascript.kak`. Everything is fixed now.

Terribly sorry if I wasted anyone's time.

**Comment by mawww** [comment]
No worries at all
