### ISSUE TITLE
Keep cursor position when scrolling the file.

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#3867]
Is there any way to keep the cursor position when a file is scrolled with mouse scroll? As soon as the cursor gets out of the screen it is set to the first or last visible line.

**Comment by krobelus** [comment]
It's currently not possible - the cursor must always be visible, see https://github.com/mawww/kakoune/issues/2982 https://github.com/mawww/kakoune/issues/2125 https://github.com/mawww/kakoune/issues/1517

You can use `Z` to save a selection (restore with `z`).

**Comment by m-kru** [comment]
I am facing different issue. I use highlight for the word under the cursor, so that I can easily find occurrences of that word within the file without searching. When the cursor changes the position it starts highlighting words I am not interested in.

**Comment by Screwtapello** [comment]
The usual Kakoune approach to "look at other occurrences of the current word" would be something like:

- `<a-i>w*` to select the current word and save it to the `/` register, so it's the default search regex
- `%s<ret>` to select all occurrences of that regex in the current buffer
- use `(` and `)` to jump between selections so you can see them in-context

Or if you don't mind holding down keys, `<a-i>w*` to select the current word and save it to the `/` register, then hold down `N` for a while to select all the occurrences.

**Comment by caksoylar** [comment]
Once you save the word to the `/` register you can also enable automatic highlighting [with a RegisterModified hook](https://github.com/mawww/config/commit/92669dbe31a1ca29ee951769dac40270e83b843e) (and optionally [clear it when you like](https://github.com/caksoylar/dotfiles/blob/master/kak/kakrc#L8)).

**Comment by losnappas** [comment]
I think this is fixed?

**Comment by mawww** [comment]
I think it is yeah, thanks for pinging.
