### ISSUE TITLE
Syntax highlighted in blue is not visible against a dark background

### ISSUE THREAD

**Issue by in42** [mawww/kakoune#3872]
While trying to use kakoune against a dark background, I have come across this problem, syntax which is highlighted in blue is not visible against a dark background:
<img src="https://user-images.githubusercontent.com/12832671/98366264-a9ed2000-2059-11eb-805f-8e336617b524.png" height="250">

In comparison, syntax highlighted in blue in neovim is much more visible:
<img src="https://user-images.githubusercontent.com/12832671/98366997-e3725b00-205a-11eb-95c9-0bb2fc645b3b.png" height="250">

Is there any solution for this?

**Comment by Screwtapello** [comment]
By default, Kakoune uses the sixteen colours your terminal provides. On some terminals the dark blue is quite visible against a black background, on other terminals it isn't. NeoVim isn't using the dark blue colour; at a guess, it's using bright cyan for the comments, and bright blue for the `~` at the bottom of the buffer.

Depending on what terminal you're using, you can try configuring the colours it uses to provide a more useful shade of dark blue. Alternatively, you can use try the `:colorscheme` command in Kakoune to use a different scheme that's not based on the colours your terminal provides. Lastly, you could try making your own colour-scheme; see `:doc faces` and the colour schemes that [ship with Kakoune](https://github.com/mawww/kakoune/tree/master/colors).

**Comment by in42** [comment]
ok thanks!
