### ISSUE TITLE
How can I run a multiline terminal command 

### ISSUE THREAD

**Issue by AndrewVos** [mawww/kakoune#3881]
I'm trying to write a command that runs my spec files over and over until I manually exit. I can't seem to work out how to get the argument passed down to the multiline script though.

```
def rspec \
  -override \
  -docstring "Run an rspec spec" \
  -params 1 \
  -shell-script-candidates %{ find spec/**/*_spec.rb } \
  %{
    terminal sh -c %{
      while true; do
        bundle exec rspec %arg{@}
        read -n 1 -s -r -p 'Press any key to repeat, or CTRL-c to exit'
      done
    } %arg{@}
  }
```

When this command executes, it does run `rspec` but the argument passed through is the literal string `%arg{@}`.

Any ideas what I'm doing wrong?

Thanks!

**Comment by lenormf** [comment]
Try "$@" in the shell code.

**Comment by Screwtapello** [comment]
To expand on what lenormf said, Kakoune only expands `%foo{}` expansions when they're alone and unquoted, or when they're in a double-quoted string. They're *not* automatically expanded inside a `%{}` quoted string.

The `rspec` command contains a `%arg{@}` (at the end of the `terminal` command), and the `%{}` wrapping the definition prevents it from being expanded until the command is called.

The `terminal` command contains a `%arg{@}` (inside the shell script), and the `%{}` wrapping the shell-script prevents it from being expanded until the shell-script is invoked. Unfortunately, the shell doesn't recognise Kakoune-style expansions, so it just leaves them as-is.

The shell equivalent of `%arg{@}` is `"$@"` (including the double-quotes, so if you use that, the shell should know what to do with it and it should work as expected.

**Comment by AndrewVos** [comment]
Thanks for the help with this! I've tried out your suggestion @lenormf (by the way, the %arg{@} after the terminal command shouldn't have been there I forgot to remove it), and it is still passing an empty string through to rspec.

```
def rspec \
  -override \
  -docstring "Run an rspec spec" \
  -params 1 \
  -file-completion \
  %{
    terminal sh -c %{
      set -x
      while true; do
        bundle exec rspec "$@"
        read -n 1 -s -r -p 'Press any key to repeat, or CTRL-c to exit'
      done
    }
  }
```

I think I'm a bit confused. How would the string passed to terminal get that parameter?

**Comment by alexherbo2** [comment]
@AndrewVos

Here is an example of a shell command passing arguments to the string command:

``` sh
sh -c '
  echo "$@"
' -- a b c
```

Outputs `a` `b` `c`.

Now in Kakoune we have a `terminal` command where we can pass a single system command and its arguments:

``` kak
terminal sh -c 'echo "$@"' -- a b c
```

or with the block syntax:

``` kak
terminal sh -c %{
  echo "$@"
} -- a b c
```

The third argument is a raw string, and `%val{something}` or `"$@"` is not going to work.
You can verify that by replacing the `terminal` command with `echo`:

``` kak
echo sh -c %{
  echo "$@"
} -- a b c
```

Outputs `sh` `-c` `echo "$@"` `--` `a` `b` `c`.

Where you can see `"$@"` being evaluated:

``` kak
define-command my-echo -params .. %{
  echo %sh{
    echo "$@"
  }
}
```

With `%sh{ ... }` you have access to the arg-list in `"$@"`.

You also have access to it in `%arg{@}` directly:

``` kak
define-command my-echo -params .. %{
  echo %arg{@}
}
```

So in the end in your case, you used a `terminal` command with a raw string, where `"$@"` has a meaning only to the `sh` command you passed.

You could have used the interpolation with the double quoted string, but you’d lost the perfect forwarding of the arguments.

Bad:

``` kak
terminal sh -c "echo %arg{@}"
```

Good:

``` kak
terminal sh -c 'echo "$@"' -- %arg{@}
```

See the [Command parsing] and [Expansions] documents for a complete reference.

[Command parsing]: https://github.com/mawww/kakoune/blob/master/doc/pages/command-parsing.asciidoc
[Expansions]: https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc

**Comment by AndrewVos** [comment]
Wow this is an amazing explanation. Thank you so much!
