### ISSUE TITLE
Server mode show connected client(s) cursors

### ISSUE THREAD

**Issue by casonadams** [mawww/kakoune#3897]
### Usecase while remote paring it would be nice to see the connected client(s) cursors

example using [webtty](https://github.com/maxmcd/webtty) as the peer to peer data channel connection

### Server
```
webtty -o -ni -cmd kak -c pair &
kak -s pair src/main.rs
```

### Client
```
webtty <token>
```

This works amazing!  Only thing that would make it better would be cursors for each connected peer (maybe colorize each)

**Comment by lenormf** [comment]
Dupe #3452

**Comment by mawww** [comment]
Yep, as described in #3452 I believe this feature should live in a plugin/user configuration as it should be relatively easy to implement with the existing building blocks.

**Comment by casonadams** [comment]
Awesome thanks!
