### ISSUE TITLE
suggestions with aspell and tex macros

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#3904]
If I were to have a file with the following macros (more or less)
```
\section
\tabular
$\sum \frac{1}{3} $
\begin{itemize}
\item
\end{itemize}

\end{document}
```
and I were to invoke `spell` with default `en`, it highlights the `ction` of `section`

then, it does not come as a surprise that if I were to invoke `aspell` by selecting each word e.g. `section` returns to be →  correct, but `\section` (notice the backslash of the macro) returns → `section cation, action, caution, ct ion, ct-ion, cations, coin, coon, caption, chino, con, ctn, cushion, Cain, Chin, chin, auction, diction, faction, fiction, section, suction, cation's, Ch'in` 

unfortunately, in the case of `spell es`, the part of `ac` from `\frac` is picked up, and a wider range of words are identified, and thus more macros in general.  If I were to invoke later, aspell with, `\frac`, it retunrs `acá, ca, ACM, a, oc, tac, ah, al, as, ay, oca, eco, anca, arca, arce, arco, asco, ce, acle, acné, acre, acta, acto, ea` 

Is there something that can be done about it. When a file is bigger than say 100 lines, as it's usually the case for most documents, this becomes an annoyance. 

Performance wise, and up to this point, yes, there could be some sort of improved performance compared to say, ispell and flyspelling the buffer from emacs, but generally speaking now, the outcome with `spell.kak` is satisfactory.  That is,  the amount of time of takes for `spell.kak` to do what it has to do before the process is finished is acceptable. 

But I have no idea what can be done about this issue.

**Comment by lenormf** [comment]
When running `aspell` on your test file manually, I'm getting the following:

```
$ aspell --byte-offsets -a < test.tex
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
& ction 24 3: cation, action, caution, ct ion, ct-ion, cations, coin, coon, caption, chino, con, ctn, cushion, Cain, Chin, chin, auction, diction, faction, fiction, section, suction, cation's, Ch'in
[…]
```

As you can see, `ction` is picked up by `aspell` (incorrectly), which tells me this is not a Kakoune bug.

**Comment by nonumeros** [comment]
@lenormf  thanks. I'll close the issue.
