### ISSUE TITLE
Crash on closing buffers

### ISSUE THREAD

**Issue by ifreund** [mawww/kakoune#3909]
### Steps 

Not able to reproduce, but it happened while closing several buffers in series. This happened on `Kakoune v2020.09.01-218-g698b028f`. If there's any other information that can be of use, let me know.

### Outcome/Stacktrace 
```
Received SIGSEGV, exiting.
Pid: 20466
Callstack:
kak(Kakoune::Backtrace::Backtrace()+0x18) [0x565508936f28]
kak(Kakoune::signal_handler(int)+0x6f) [0x565508a2484f]
/usr/lib/libc.so.6(+0x3b9b0) [0x7f95256549b0]
kak(Kakoune::InputHandler::mode_line() const+0x24) [0x5655089ebbe4]
kak(Kakoune::Client::generate_mode_line() const+0xf2) [0x56550894cc72]
kak(Kakoune::Client::redraw_ifn()+0x5b) [0x56550894d51b]
kak(Kakoune::ClientManager::redraw_clients() const+0x24) [0x565508950874]
kak(Kakoune::run_server(Kakoune::StringView, Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, Kakoune::ServerFlags, Kakoune::UIType, Kakoune::DebugFlags, Kakoune::ArrayView<Kakoune::StringView const>)+0x998) [0x565508a2e748]
kak(main+0x19c8) [0x565508934c28]
/usr/lib/libc.so.6(__libc_start_main+0xeb) [0x7f952563fdeb]
kak(_start+0x2a) [0x56550893569a]
sh: 1: xmessage: not found
zsh: segmentation fault  kak
```

**Comment by lenormf** [comment]
Could you please share your configuration, especially the part that deals with the modeline?

**Comment by ifreund** [comment]
My complete config can be found here: https://github.com/ifreund/dotfiles/tree/master/config/kak
The modeline is set up here: https://github.com/ifreund/dotfiles/blob/master/config/kak/autoload/modeline.kak

**Comment by mawww** [comment]
Weird one, cannot really find an explanation of what might be going on there, it looks like the mode stack is empty but I cannot see how that would happen.
