### ISSUE TITLE
could there be an easier way to add languages to markdown code block highlighting?

### ISSUE THREAD

**Issue by BrianHicks** [mawww/kakoune#3913]
### Feature 

I'd love an easier way to add new highlighters to markdown fenced code blocks. For example, I write a lot of markdown with the `elm` and `nix` tags, and neither of those are highlighted.

(If it makes sense for me to just send in a PR to add them to the big list, that's fine! Just let me know and I can do that!)

Looking at this code:

https://github.com/mawww/kakoune/blob/14f7d2637c80258d80e5ae204e16dbb67a896ebc/rc/filetype/markdown.kak#L42-L55

I can kinda squint and see a command that adds a new highlighter by name (just the inner part of that loop.) I'd like to be able to add something like `add-markdown-language elm` to my config to take care of this myself for whatever other wild languages I use in the future.

### Usecase 

Leaving this heading since it's in the template, but I described my use-case above!

**Comment by BrianHicks** [comment]
to be clear: I kinda see a way forward with this? But, I didn't see a lot of prior work on this, and I'm sure I'm missing considerations of why it may not work, so I'm opening an issue to talk through this instead of just sending in a patch!

**Comment by danr** [comment]
This code was written (originally by me) when all regions had to be declared in one single add-highlighter invocation. The API is more convenient now as we can see and a command `add-markdown-language R` like you suggest would make more sense. Go for it! :v:

**Comment by lenormf** [comment]
Regarding your specific usecase, adding `elm` and `nix` to the list makes sense, since both of these languages are supported out of the box.

Now in the case of languages not supported upstream or even arbitrary filetypes only implemented locally, I think an `str-list` option that would store the `$languages` hardcoded list in `markdown.kak` could be warranted.

Or maybe an option that only handles “extra” filetypes, on top of built-in ones?

cc @mawww

**Comment by eraserhd** [comment]
I like the `str-list` option, with all filetypes.

**Comment by krobelus** [comment]
this should be done as of commit 907ad84f46447e1c73fcd80c6a020a50b9ea2266. The commit message explains how to use it. For example, use

```kak
            provide-module hs %{
                    require-module haskell
                    add-highlighter shared/hs ref haskell
            }
```

to highlight "hs" markdown code blocks as haskell

**Comment by mawww** [comment]
Yep, I think we can close this.
