### ISSUE TITLE
Converting word to all uppercase and all lowercase

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#3916]
What is the fastest (less key strokes) way to convert a word to all uppercase and all lowercase?

**Comment by occivink** [comment]
Pressing the ` and ~ keys is pretty fast

**Comment by lenormf** [comment]
Please make sure you read the documentation before creating an issue.

It's available [in file format](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc) and in the editor itself, via the `:doc keys` command.
