### ISSUE TITLE
screen scrambled when scrolling with tmux through ssh

### ISSUE THREAD

**Issue by cduret** [mawww/kakoune#3917]
### Steps 
I launch a ssh session to a Centos 7 VM.
I have compiled kakoune with gcc `8.3.1 20190311` and ncurses `6.2.20200212`
I launch tmux with config :
```
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*col*:Tc"
set -g mode-mouse on
set-option -g mouse-select-pane on
set-option -g mouse-select-window on
set-option -g mouse-resize-pane on
set -s escape-time 0
```

### Outcome 
The screen get scrambled whenever I scroll up and down with `c-u` and `c-d`

### Expected 
The screen should be updated cleanly

### Remarks
- The scroll works good through the ssh session without tmux
- The scroll works good with tmux when using `pg up` and `pg down` keys
- The scroll works good when using vim `7.4.629` `c-u` and `c-d` with tmux
- When the screen is scrambled and I resize the ssh (putty) window the screen get back to normal

**Comment by Screwtapello** [comment]
If I understand your report correctly:

- Kakoune sees `$TERM` set to `screen-256color`
- Kakoune is running inside tmux on CentOS 7
- tmux is running inside an SSH connection
- ssh sees `$TERM` set to something else
- ssh is running inside some other kind of terminal

What terminal is ssh running inside? What `$TERM` does it see?

**Comment by cduret** [comment]
Exactly

I use putty on windows.
The `$TERM` when I log on :

```
$ echo $TERM
xterm
```

**Comment by cduret** [comment]
it does not seem to be putty related anyway because when I launch ssh through the windows console (`cmd.exe`) the problem is the same

**Comment by cduret** [comment]
by the way my tmux version :
```
$ sudo yum list tmux
Installed Packages
tmux.x86_64                                                                       1.8-4.el7
```

**Comment by Screwtapello** [comment]
PuTTY (especially old versions of PuTTY) may not be a good match for `TERM=xterm`. Try running tmux with:

    TERM=putty tmux

...and if that doesn't work, maybe try something even more primitive like `TERM=ansi` or `TERM=vt220`.

> it does not seem to be putty related anyway because when I launch ssh through the windows console (cmd.exe) the problem is the same

The Windows Console, as far as I know, doesn't support any terminal escape sequences at all. I don't know how they get interpreted for the ssh-from-cmd use-case, but I'm guessing it's even more primitive and limited than PuTTY.

**Comment by lenormf** [comment]
It's an obvious question but do you have the right terminfo database installed on the VM?

Does the bug occur when you remove the terminal override from the Tmux configuration? Why not use `tmux-256color` as base terminal name, which should be supported by all distros by now?

Did you base this configuration on the [FAQ](https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#im-using-tmux-and-colors-look-weird)?

**Comment by cduret** [comment]
I presume could be more related to the old tmux version than putty because I have exactly the same behavior on a mintty terminal with cygwin.

The `TERM=ansi` does the job, no other value did work.

Thanks for help !

**Comment by pdjacobs** [comment]
I encountered this issue too, and was able to fix it with the step from the  [FAQ](https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#im-using-tmux-and-colors-look-weird), using using tmux-256color.  I'm using Windows terminal to ssh into an Ubuntu machine, using Kakoune v2020.01.16-12-g27490931 and tmux version 2.6 and 3.1c.  Scrolling up failed using <pageup>, <c-u> or mousewheel.

cduret, I'd recommend trying Windows terminal and openssh instead of Putty, if you're able - I'm able to get it working with a more feature-full TERM than "ansi", and with the more recent Windows terminal version, mouse interaction with Kakoune and tmux works as well.
