### ISSUE TITLE
Mac Install error

### ISSUE THREAD

**Issue by prtysh** [mawww/kakoune#393]
Might be slightly noobish but am stuck and I really want to try kakoune.
Brew giving me following error:
insert_completer.cc:131:31: error: no member named 'accumulate' in namespace 'std'
    const auto longest = std::accumulate(matches.begin(), matches.end(), 0_char,
                         ~~~~~^
1 warning and 1 error generated.
make: *** [.insert_completer.o] Error 1

Manual make giving me following error.
insert_completer.cc:131:31: error: no member named 'accumulate' in namespace 'std'
    const auto longest = std::accumulate(matches.begin(), matches.end(), 0_char,
                         ~~~~~^
1 warning and 1 error generated.
make: *** [.insert_completer.o] Error 1

**Comment by mawww** [comment]
Hello

There was a bug in the latest version, which broke compilation on mac, it should be fixed now, howerver travis-ci does not work here right now, so I cannot guarantee it, but it should be ok if you update to latest code.

Sorry for the inconvenience.

**Comment by mawww** [comment]
a7d93fa11ee985c94950e819720109659af8a5d3 should fix it

**Comment by prtysh** [comment]
Hey mawww thanks for the response.
Yes it is working now. My only gripe was that error was not that informative. 

I have also been trying to install Kak in RHEL Unix and Ubuntu (and failing). I will start a thread if I am not able to do today either.
