### ISSUE TITLE
Bad symbol when adding selection register index.

### ISSUE THREAD

**Issue by CharlesGueunet** [mawww/kakoune#3930]
### Steps

In insert mode, simply type: `<c-r>#`.

### Outcome

kakoune insert the symbol: 

### Expected

kakoune should insert: 1 (the first index)
This worked some times ago and stopped recently, I can bisect this in the future.

### Additional:

I am on kakoune master.

see small discussion [here](https://github.com/mawww/kakoune/pull/3891#issuecomment-743033128):
I have tried `:map buffer insert X <c-r>#` with no avail.

I have reproduce this bug using the `-n` flag, on Kitty and WezTerm, with and without tmux.

**Comment by loovjo** [comment]
Could you send a hexdump of the character itself? Save the buffer into a file and run `xxd` on it?

**Comment by CharlesGueunet** [comment]
I did it on two lines:
```
00000000: 010a                                     ..
00000000: 020a                                     ..
```

**Comment by mawww** [comment]
Which commit is that happening on ?

**Comment by CharlesGueunet** [comment]
Sorry- I made a mistake in one of my tests, this came from a local change on my local version.
