### ISSUE TITLE
freepascal syntax highlighting? 

### ISSUE THREAD

**Issue by pyrotek45** [mawww/kakoune#3933]
hi, I was wondering if freepascal could be added to the syntax highlighting. I would love to do it myself but I Don't understand it well enough to do a good job. 

https://www.freepascal.org/

anyways kakoune is great and a lot of fun to learn.

cheers.

**Comment by Ordoviz** [comment]
Free Pascal is a compiler. You actually want Pascal and Object Pascal support, right?

**Comment by pyrotek45** [comment]
yes. sorry for not wording it correctly.

**Comment by dubst3pp4** [comment]
I would like to see the Object Pascal support, too :+1:

**Comment by cryptolake** [comment]
I just wanna add that i appreciate pascal support too
