### ISSUE TITLE
When EditorConfig is enabled, spaces are never inserted, always tabs

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3952]

**Comment by occivink** [comment]
See #3727

**Comment by lenormf** [comment]
Isn't the problem in #3727 that the user expects the <kbd>tab</kbd> key to insert spaces?

I have no information other than what's in the title of this issue, so I don't know if it's a valid bug report or not. I will close this ticket if nobody has had whitespace-related issues with EditorConfig, I want to make sure in the meantime that there isn't any linkage blindness.

**Comment by occivink** [comment]
I'm almost 99% sure that was what the survey taker meant. In most text editors, the tab key can be directly configured to insert a tab, or N spaces. In kakoune that's not possible for the reasons mentioned [here](https://github.com/mawww/kakoune/issues/1038#issuecomment-270616520), but it's achievable with a little scripting.

**Comment by lenormf** [comment]
Alright, one down!
