### ISSUE TITLE
Allow `:git` to select or revert hunks

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3953]
### Feature 

The `:git` command should allow more control over hunks, for example selecting or reverting them.

HTH.

**Comment by TuM0xA-S** [comment]
btw it is really usable
i think it should have "expand hunk"  feature to actually see what it is / fold it (expanding in simplest from may look just as jump to appropriate diff)

**Comment by krobelus** [comment]
this implemented in `:git apply` now. Users have been looking for it in `:git add`, maybe we should make things more discoverable
