### ISSUE TITLE
Multibyte grapheme incorrect cursor behavior

### ISSUE THREAD

**Issue by pickfire** [mawww/kakoune#3963]
### Steps 

https://github.com/LukeMathWalker/zero-to-production/blob/master/src/domain.rs#L60

1. `i"a̐"`
2. `lll`

### Outcome 

Cursor disappears and it moves through the third byte

### Expected 

It should just went to the third character instead of cursor disappearing and going to the third byte.

**Comment by lenormf** [comment]
Dupe #1447
