### ISSUE TITLE
Add `:debug register` to inspect the value of all registers

### ISSUE THREAD

**Issue by cole-h** [mawww/kakoune#3978]
### Feature 

A new subcommand for `:debug` that displays the contents of all registers would be useful.

* Should the subcommand be `register` or `registers`?
* Should only registers with content be printed (if there's a way to differentiate)?
  * If there is a way to differentiate, should there be a `-all` flag to print all registers regardless of state?

### Usecase 

It would be nice to be able to inspect the value of all registers (the most obvious example I can make is to help newbies like me determine if they need to use `-save-regs` with `eval` or `exec`).

**Comment by tototest99** [comment]
`echo -debug register a is: %reg{a}`
You can define a command for multiple registers based on this

**Comment by caksoylar** [comment]
Also see: https://github.com/Delapouite/kakoune-registers
