### ISSUE TITLE
No Syntax Highlighting for portable shebang (OSX)

### ISSUE THREAD

**Issue by jmpohl** [mawww/kakoune#3982]
### Steps 

Open file with a shebang of 

```
#!/usr/bin/env zsh
```

### Outcome 

Doesn't syntax highlight

### Expected 

Syntax highlighting

### Additional Context

I tried the solution referenced in [this](https://github.com/mawww/kakoune/issues/2858) issue, but it didn't work. I am also on OSX which I think makes things a little different. Thanks!

**Comment by jmpohl** [comment]
Just to document this somewhere in case anyone else needs it, I had to copy the magic directory from `/usr/share/file/magic` into a place where it is editable (it is  read-only on OSX, by default). 

Then I added a new file named `zsh` (or you could add it to one of the files that is in the `magic` dir already) to the `magic` dir with the proper syntax for `#!/usr/bin/env zsh`, which looked like

```
 0   string/wt   #!\ /usr/bin/env\ zsh   Paul Falstad's zsh script text executable
 !:mime  text/x-shellscript 
```

You need to use the `MAGIC` environment variable to point to the new editable `magic` dir. For me, in my `zprofile`:

```
export MAGIC="/Users/jmpohl/src/magic"
```
Now `file` should be using the editable `magic` dir that now includes the portable *zsh* shebang `#!/usr/bin/env zsh`

**Comment by codesoap** [comment]
JFYI: I've created https://github.com/mawww/kakoune/pull/3984. I'm not sure whether OSX usually uses `text/x-shellscript` or `application/x-shellscript`.
