### ISSUE TITLE
Wrong syntax detection

### ISSUE THREAD

**Issue by NightH4nter** [mawww/kakoune#3995]
### Steps 

1. use solarized-dark colorscheme
2. open [this file](https://gist.github.com/NightH4nter/0630e17b24e323ec15ce98bd879e0a4e) (same with elisp and rust files)

### Outcome 
![image](https://user-images.githubusercontent.com/31319604/103306277-1b67a000-4a05-11eb-985b-a76143550d38.png)
![image](https://user-images.githubusercontent.com/31319604/103306287-215d8100-4a05-11eb-8ce3-633747201c82.png)
![image](https://user-images.githubusercontent.com/31319604/103306296-24f10800-4a05-11eb-8783-bf45a91da5bf.png)
![image](https://user-images.githubusercontent.com/31319604/103306307-2b7f7f80-4a05-11eb-84fa-04b545d33b62.png)

### Expected 
Judging by the contents of [this file](https://github.com/mawww/kakoune/blob/master/colors/solarized-dark.kak), something like this (nvim screenshots):
![image](https://user-images.githubusercontent.com/31319604/103306246-0428b280-4a05-11eb-8b96-8c082fe45028.png)
![image](https://user-images.githubusercontent.com/31319604/103306253-08ed6680-4a05-11eb-8606-b0884e78153d.png)
![image](https://user-images.githubusercontent.com/31319604/103306260-0d198400-4a05-11eb-9f47-5af515b91cf4.png)
![image](https://user-images.githubusercontent.com/31319604/103306266-13a7fb80-4a05-11eb-8a4e-565882a40d0f.png)

### Additional info:
- Distro: Arch
- Kakoune version: 2020.09.01-1
- Terminal emulator: Alacritty
- kakrc: https://gist.github.com/NightH4nter/4d24672ad761b09312e7d36602c379da#file-kakrc

**Comment by krobelus** [comment]
One difference is that macros like `#define FOO(x) 123` are monochrome - the entire line has the "meta" face.
This is defined in `rc/filetype/c-family.kak`, so this part is not specific to the solarized theme.

**Comment by NightH4nter** [comment]
> One difference is that macros like `#define FOO(x) 123` are monochrome - the entire line has the "meta" face.
> This is defined in `rc/filetype/c-family.kak`, so this part is not specific to the solarized theme.

Well, even if it's not specific to Solarized, it's probably not the way it has to work. Anyway, other colors are completely off, which is very distracting.

**Comment by krobelus** [comment]
Can you give small examples for the things that you expect to be different? It's not clear for the casual reader what exactly should be changed.

In `colors/solarized-dark.kak` the font face for `type` is `${red}` where `red='rgb:dc322f'`.
Turns out they used to be yellow before b63d410219bfe95356ca8e30e1a2bac5e832d4df (https://github.com/mawww/kakoune/pull/2145), which seems closer to your nvim screenshot. I'm not sure what's the motivation for that change is, maybe @mattvilim knows.

**Comment by NightH4nter** [comment]
The problem is not only the colors being wrong, but also because some syntax elements aren't being detected.
Example (left-to-right: the colorscheme file with couple fixes made by me, `dwm.c` opened in `nvim` and `dwm.c` opened in `kak` (with some catastrophic rendering bugs if text is scrolled with mouse while inside `tmux`, but that's not the point of this issue)):
![image](https://user-images.githubusercontent.com/31319604/103341075-bc923d00-4a7d-11eb-8a8a-64a766d0dbf5.png)
As you can clearly see, color `${blue}` is assigned to functions, but the functions just have the default foreground color in Kakoune.
Speaking of macros being monochrome: there's not that much point for them to be color-coded, if they're monochrome. Look at this (`nvim` on the left, `kak` on the right):
![image](https://user-images.githubusercontent.com/31319604/103341618-50b0d400-4a7f-11eb-997d-8a2cc22ecac7.png)
While the left version isn't perfect, it's still way more readable then what you can see on the right side.

**Comment by krobelus** [comment]
The c-family highlighter does not detect functions yet. A highlighter that does is `src/filetype/rust.kak`:

```
add-highlighter shared/rust/code/function_call        regex _?[a-zA-Z]\w*\s*(?=\() 0:function
add-highlighter shared/rust/code/function_declaration regex (?:fn\h+)(_?\w+)(?:<[^>]+?>)?\( 1:function
```

so a very rough implementation for C would be

```diff
diff --git a/rc/filetype/c-family.kak b/rc/filetype/c-family.kak
index 0af8fcff..acfc814b 100644
--- a/rc/filetype/c-family.kak
+++ b/rc/filetype/c-family.kak
@@ -214,2 +214,3 @@ evaluate-commands %sh{
             add-highlighter shared/$ft/macro/ regex /\\*.*?\\*/ 0:comment
+            add-highlighter shared/$ft/macro/function_call regex \b\w+\b(?=\() 0:function
 	EOF
@@ -284,2 +285,3 @@ evaluate-commands %sh{
         add-highlighter shared/c/code/values regex \b($(join "${macros}" '|'))\b 0:value
+        add-highlighter shared/c/code/function_call regex \b\w+\b(?=\() 0:function
     "
```

Not sure what to do about C++; highlighting should probably remain consistent between C and C++.

**Comment by NightH4nter** [comment]
Well, it *sort of* works, still doesn't recognize custom types.
Can't upload the screenshot here for some reason, so https://imgur.com/kClaWSi.

**Comment by krobelus** [comment]
Yeah the type names are hardcoded right now. (usually a small text file is enough to reproduce the issue).
There are limits to what regex-based highlighters can do. Fixing this case seems easy for C but harder for C++.
kak-lsp can provide semantic highlighting via clangd's semantic tokens, YMMV
