### ISSUE TITLE
Duplicate line numbering when soft wrap is enabled

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#4004]
Is there any way not to show, or omitting superfluous duplicate numbered lines while those lines are being wrapped with or without any options notwithstanding the fact, as a visual selector text editor, an `x` will highlight the line in question, regardless. 

Only the beginning of the line is all that may be needed for that corresponding line number to be chosen. As it currently stands with  default values,  some folks might find it practical or even visually appealing, but the way I personally see it, is overwhelmingly duplicate number of lines that can go on for as long as the wrap is extended. 

e.g. 
```
100 holy shit some text
100 that will wrap and wrap
100 with numbers that wrap too
```

If I'm not mistaken, vim's default line numbering is similar to what I said  earlier. Is this implemented? If so, my apologies, but I couldn't find any literature regarding this issue.

**Comment by Ordoviz** [comment]
You can use the `LineNumbersWrapped` face to give these numbers the same color as the background by editing your color scheme: Copy the color scheme file in your data folder (e.g. /usr/share/kak/colors) to your user config folder (e.g. ~/.config/kak/colors) and edit it as desired.

**Comment by nonumeros** [comment]
@Ordoviz  thanks. thanks. 

I guess I understand your idea. 

I said I guess, because quite frankly, one would have to customize every color scheme under the roof, in order to have  numbered lines not highlighted during the course of line wrapping. But only in the beginning of line.

In other words, as it is, and with default factory values, if you were to fire up vim which it'd give you, only the start of the numbered line highlighted, but not the rest. Of course, I've never used vim extensively nor did I ever customized it, to the point, as some folks here probably have done in the past. 

For example, if you were to pick a colorscheme. Say for now, any of the preconfigured ones. And let's assume it'd be the `default` scheme which does not include `LineNumbersWrapped`, so this face, must be added later to the file of the initialization path.

From there, one would have to choose a value that will receive the best amount of color treatment  while the line is being wrapped. 

Because `LineNumbers` alone with white and blue selected, will give different shades for the same line, and not necessarily by keeping a nice contrasting touch. You're right. If you were to select for `LineNumbers` white and blue, it'd would simply throw everything off. One no longer knows which lines to follow. 

for example, I can see that the option entitled `LineNumbersWrap` like you suggested would have to be added on, in order to have better background color cues. 

This is not ideal. I understand though, that this level of customization is perhaps desired.  But I honestly thought that there would be a faster way, sort of a works-for-most-folks-with-a-switch method that would get there based on the chosen colorscheme. 

But thanks a lot @Ordoviz . As always, your help is appreciated.
