### ISSUE TITLE
Scroll up events interact badly with line wrapping

### ISSUE THREAD

**Issue by shachaf** [mawww/kakoune#4026]
To reproduce:

* Make a narrow window and fill it with long lines (long enough to wrap).
* Enable wrapping: `addhl window/ wrap`.
* Scroll up and down with the mouse wheel.

Scroll down events work fine, but scroll up events get "stuck" when the window has enough continuation lines, so nothing happens (although `-debug keys` confirms that `<scroll:-3>` events are still being received).

**Comment by Screwtapello** [comment]
Dupe of #1517?

**Comment by shachaf** [comment]
Oh, so it is.
