### ISSUE TITLE
regex character class \s does not match NO-BREAK SPACE (Unicode A0).

### ISSUE THREAD

**Issue by avalenn** [mawww/kakoune#4034]
### Steps 
`%s\s+<enter>`
### Outcome 
Only ASCII whitespaces selected.
### Expected 
no-break space characters to be selected too, possibly also applicable to all characters in Unicode Zs General Category.

### Additionnal information
From @Screwtapello on IRC
> `:doc regex` doesn't seem to mention that character-class escapes are only defined for ASCII characters, so it seems reasonable to file an issue.
> Kakoune usually follows the ECMAScript regex syntax, but that says \s "Matches a single white space character, including space, tab, form feed, line feed, and other Unicode spaces. Equivalent to [ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]."

**Comment by 7h3w1zz** [comment]
I have created a pull request for a tentative fix to this.  I can write some tests if the implementation looks fine.
