### ISSUE TITLE
Crash when spelling after writing file

### ISSUE THREAD

**Issue by Schmiddiii** [mawww/kakoune#4042]
### Steps 
Include this line in your kakrc:
`hook global BufWritePost .*\.tex spell`

Edit and write some Latex files and it will sometimes crash.
If it crashes once writing a tex file will always crash the next times.
I have not found a more reliable way to make this crash happen.

I have seen this crash on fish, bash and zsh, always on alacritty.

### Outcome/Stacktrace 
Here are some error messages i recieved:

`malloc_consolidate(): invalid chunk size
fish: Job 3, 'kak myfile.tex' durch Signal SIGABRT (Abbruch) beendet`

`Received SIGSEGV, exiting.
Pid: 4609
Callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x5559c4c7a0b8]
kak(_ZN7Kakoune14signal_handlerEi+0x6a) [0x5559c4d7d1ea]
/lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f8c59f1e040]
kak(_ZN7Kakoune6String6resizeENS_9ByteCountEc+0x5c) [0x5559c4e4488c]
kak(_ZN7Kakoune14CommandManager7executeENS_10StringViewERNS_7ContextERKNS_12ShellContextE+0xd1e) [0x5559c4ca2d0e]
kak(+0xd65da) [0x5559c4cba5da]
kak(_ZN7Kakoune14CommandManager22execute_single_commandENS_9ArrayViewIKNS_6StringEEERNS_7ContextERKNS_12ShellContextENS_11BufferCoordE+0x33e) [0x5559c4ca104e]
kak(_ZN7Kakoune14CommandManager7executeENS_10StringViewERNS_7ContextERKNS_12ShellContextE+0xad8) [0x5559c4ca2ac8]
kak(_ZN7Kakoune11HookManager8run_hookENS_4HookENS_10StringViewERNS_7ContextE+0x1926) [0x5559c4d3dc36]
kak(_ZN7Kakoune11HookManager8run_hookENS_4HookENS_10StringViewERNS_7ContextE+0x900) [0x5559c4d3cc10]
kak(_ZN7Kakoune11HookManager8run_hookENS_4HookENS_10StringViewERNS_7ContextE+0x900) [0x5559c4d3cc10]
kak(+0xd5584) [0x5559c4cb9584]
kak(+0xd5c85) [0x5559c4cb9c85]
kak(_ZN7Kakoune14CommandManager22execute_single_commandENS_9ArrayViewIKNS_6StringEEERNS_7ContextERKNS_12ShellContextENS_11BufferCoordE+0x33e) [0x5559c4ca104e]
kak(_ZN7Kakoune14CommandManager7executeENS_10StringViewERNS_7ContextERKNS_12ShellContextE+0xad8) [0x5559c4ca2ac8]
kak(+0x1c36e0) [0x5559c4da76e0]
^[[Ofish: Job 3, 'kak myfile.tex' durch Signal SIGSEGV (Adressbereichsfehler) beendet`

Edit: One more message I just got:

`malloc(): memory corruption
fish: Job 3, 'kak myfile.tex' durch Signal SIGABRT (Abbruch) beendet`

### Version
I am currently on `Kakoune v2020.09.01-302-g7751c7e1`.
The last version i was on (i think January 2020) didn't have this issue.

### Additional Info
I have altered my spell.kak to use `aspell -t` for spelling Latex files, but even without the modification it crashes.

**Comment by mawww** [comment]
I believe this was the issue, please confirm it is fixed when you can give it a try.

**Comment by Schmiddiii** [comment]
I have now tried it out a few times and it did not crash.
So it seems to be fixed, but as this crash only happens occasionally I can't say it for sure.

I will report back if it crashes again, otherwise consider it fixed.
