### ISSUE TITLE
grep command: no results

### ISSUE THREAD

**Issue by basbebe** [mawww/kakoune#4044]
### Steps 
I  assume that `:grep [WORD]` gives me all instances of [WORD] in all opene kakoune buffers.

I'm on macOS 11.2, kitty terminal and kakoune [26cf5cd](https://github.com/mawww/kakoune/commit/26cf5cd1dce362a34593fcf5994c961f8aa53bc0)

I enter `:grep [WORD]`.

### Outcome 

`*grep*` buffer gets opened but stays empty.

### Expected 

show all instances or [WORD].

**Comment by krobelus** [comment]
> :grep [WORD] in all opene kakoune buffers.

No, runs grep, so it searches on the filesystem.

https://github.com/occivink/kakoune-find does that

**Comment by basbebe** [comment]
I see!

Sorry, then my assuption was wrong.

`:grep [WORD] ./` does what I was looking for.

I might look into `kakoune-find` later, thanks!
