### ISSUE TITLE
Select-to-matching-char inconsistent selection extension

### ISSUE THREAD

**Issue by memeplex** [mawww/kakoune#405]
As an example of the general, expected, beahavior (at least AFAICS):
1. Say `_` is the cursor in `xxxx_yyyy`.
2. Press `shift-b` and say `|...|` is the selection, you get: `|_xxxx|yyyy`.
3. Press `shift-w`, you get: `|xxxxyyyy_|`.

Now try this:
1. `xxxx_yy(yy)`
2. Press `shift-b`: `|_xxxx|yy(yy)`.
3. Press `shift-m`: `xxxx|yy(yy)_|`.

But `|xxxxyy(yy)|` would be both consistent and more useful. Notice `shift-m` is inverting the selection of the entire `xxxxyy(yy)` sequence in step 3.

**Comment by memeplex** [comment]
Now I understand the coherence in the current behavior: `b` and `w` don't really need the `shift` modifier above, they just work from the cursor, not from the anchor; the `shift` modifier in `shift-m` is the cause of the "selection inversion", but this is the rule for extending with `shift`, not an exception.

Novertheless, I would like to ask for advice here. In vim `vb%` will do the same that `b<shift-m>` for my example above, but I also can avoid visual mode and do, say, `db%` to quickly delete a function call like `f(1,2,3)`. What will be the kak equivalent, `b;<shift-m>d` maybe?

**Comment by mawww** [comment]
Hello,

so yeah, thats the expected behaviour, the anchor stays fixed when extending the selection (usually with shift).

as you found out `b;M` would be the best way to do the selection you describe, folowed by `d` to erase it.
