### ISSUE TITLE
Wrong anchor for backward search

### ISSUE THREAD

**Issue by memeplex** [mawww/kakoune#406]
Say the cursor is over the first `y` in `xxxyyyxxx`, then `alt-/xx` will select the *first* two `x` but `alt-/xxx` will select the *last* three `x`s. I think the backward search is anchoring in the wrong position. This is also problematic when you're searching backwards some string `xxx` and the buffer contains yuxtaposed ocurrences of this string, `xxxxxx`, then one ocurrence will be selected but the other one skipped.

**Comment by mawww** [comment]
Thanks for the report, should be fixed now.
