### ISSUE TITLE
Add -working-directory switch to evaluate-commands

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#4065]
It could be nice to set the working directory to evaluate commands.

The use case is to send commands from the command-line.

**Example**

``` sh
kak -p kanto <<EOF
  evaluate-commands -working-directory "$PWD" edit pokemon.json
EOF
```

**Comment by mawww** [comment]
Using absolute paths would work as well, I dont see much value in Kakoune providing this.

**Comment by alexherbo2** [comment]
@mawww Using absolute paths requires to know what the arguments are.  It could help to forward a context from the command-line, like we can set the environment when we run a [process][`Process`].  It is difficult to use my [`kcr send`] when the Kakoune commands use paths and the terminal / server directory differ.

[`Process`]: https://crystal-lang.org/api/Process.html
[`kcr send`]: https://github.com/alexherbo2/kakoune.cr#send

To work reliably with any command, [kak-lsp] uses a `cd` to change the server directory, so imo the problem exists.

[kak-lsp]: https://github.com/kak-lsp/kak-lsp

As a side note, it could also simplify the [`main.cc`] with the `-c` switch.

[`main.cc`]: https://github.com/mawww/kakoune/blob/master/src/main.cc

**Comment by krobelus** [comment]
kak-lsp is [moving away](https://github.com/kak-lsp/kak-lsp/pull/454) from running `cd` - there are multiple solutions to that

**Comment by alexherbo2** [comment]
@krobelus What is the solution to implement a `kcr send` command using relative paths?

```
kcr send <command> [arguments]
```

**Comment by alexherbo2** [comment]
@mawww Please reopen.  I see very much value for sending commands with relative paths from the CLI.

``` sh
kcr send edit src/main.cc
```

``` sh
kcr send grep -i kakoune docs
```

**Comment by mawww** [comment]
Then maybe a pushd/popd mechanism would make more sense than putting this as an evaluate command switch ? Also, what happens when grep returns relative paths that are based off the temporary working directory ? As soon as we exit that scope we the grep buffer becomes unusable.
