### ISSUE TITLE
Problem running kak after upgrading to Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Drilip** [mawww/kakoune#4072]
I upgraded ubuntu and now I get this when i try to use kak:
/home/philip/.local/bin/kak: error while loading shared libraries: libncursesw.so.5: cannot open shared object file: No such file or directory

Any help appreciated.

**Comment by Screwtapello** [comment]
It sounds like you built Kakoune for a previous version of Ubuntu that used ncurses v5, and the modern version of Ubuntu uses ncurses v6. You might be able to `apt install libncursesw5` to get your existing binary working, but it would probably be better to just rebuild Kakoune against the new version. In particular, ncurses v6 now supports scrolling with the mouse-wheel both down *and* up.

**Comment by Drilip** [comment]
Thank you! I'm still a bit of a rookie so i opted for the apt install and it worked perfectly. I can scroll both up and down :)
