### ISSUE TITLE
Broken usages of ModeChange hook

### ISSUE THREAD

**Issue by muffin4** [mawww/kakoune#4078]
I noticed that the some usages of the `ModeChange` hook are broken. The hook param never matches `insert:.*` because it always begins with `push:` or `pop:`, and so the related commands never get executed. See [doc/pages/hooks.asciidoc](https://github.com/mawww/kakoune/blob/master/doc/pages/hooks.asciidoc#default-hooks)

https://github.com/mawww/kakoune/blob/7c321e121d5910a9316cd04a6c596c1fe95b8bde/rc/filetype/ninja.kak#L19
https://github.com/mawww/kakoune/blob/7c321e121d5910a9316cd04a6c596c1fe95b8bde/rc/filetype/gluon.kak#L18
https://github.com/mawww/kakoune/blob/7c321e121d5910a9316cd04a6c596c1fe95b8bde/rc/filetype/dhall.kak#L17

**Comment by krobelus** [comment]
Nice find, you can create a PR if you want
