### ISSUE TITLE
Default mapping for rotating selection's content backward doesn't work with German keyboard

### ISSUE THREAD

**Issue by jtrees** [mawww/kakoune#4082]
### Steps 
1. Have the following three selections: `a`, `b`, `c`
2. Try to rotate their contents backward (with `<alt>+<shift>+8`)

### Outcome 
```
register '/' set to 'a|b|c'
```

### Expected 
The selection contents should be rotated, resulting in `c`, `a`, `b`.

### Notes
- keyboard layout is German
- `kakrc` is empty
- version: `Kakoune v2020.09.01-217-g14f7d263`
- kitty terminal emulator
- rotating contents forward (with `<alt>+<shift>+9`) works

**Comment by lenormf** [comment]
I think you have the primitive mixed up:

https://github.com/mawww/kakoune/blob/60c44e16236487957c41d28bc037976afdc691a7/doc/pages/keys.asciidoc#L359,L360

**Comment by Screwtapello** [comment]
Outside of Kakoune, what gets printed when you run `cat` and press `<a-(>` ?

**Comment by jtrees** [comment]
> Outside of Kakoune, what gets printed when you run `cat` and press `<a-(>` ?

If I press `<a-(>` I get `^[*`. Pressing `<a-)>` (which appears to work as intended) results in `^[(`.

I didn't know this trick.

**Comment by jtrees** [comment]
> I think you have the primitive mixed up:

How so?

**Comment by mawww** [comment]
`^[*` means `<a-*>` which is what I'd expect from a regular qwerty keyboard where `*` is Shift+8, this seems to match with `^[(` you get by pressing Alt+Shift+9. Are you confided your configuration actually sets the keyboard layout to german ?

**Comment by Screwtapello** [comment]
Even if the keyboard layout is configured correctly at the OS level, Kitty may be incorrectly mapping keycodes to the terminal encoding.

**Comment by jtrees** [comment]
> Even if the keyboard layout is configured correctly at the OS level, Kitty may be incorrectly mapping keycodes to the terminal encoding.

Wow. That is most likely what's going on. I tried the `cat` thing in elementary Terminal (I'm on elementary OS) and sure enough: `<a-(>` gives me `^[(` and `<a-)>` gives me `^[)`. So it's either a config thing or a Kitty bug.

Thanks!
