### ISSUE TITLE
O(N^2) case for updating ranges

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#4084]
This can be triggered by kak-ansi.  `ansi-render` filters out all ANSI escapes, which ends up being a large number of changes, then updates a ranges option with a close-to-equal number of ranges, using the prior timestamp.

When the option is updated, every range is iteratively updated with every "relevant" change, resulting in (I think) N^2/2 iterations.  Long runtimes are reported in eraserhd/kak-ansi#6, sometimes six or eleven minutes.

## Solution

We are clearly duplicating work.  If we know the ranges are sorted and the changes are sorted, we could solve this in O(N) with no new memory, though I don't think we can fit the algorithm to the ForwardChangesTracker interface.

If one or the other isn't sorted, then I think we need O(N) memory for cached intermediate adjustments.

1. Sort changes O(N log N)
2. Allocate N buckets for total insertions before change N
3. Allocate N buckets for total deletions before change N
4. Populate 2 and 3 in O(N)
5. Iterate through ranges, binary search for the last relevant change for that range, then update it with the buckets O(N log N).

Back-of-the-envelope math says the [profile given to me](https://gist.github.com/malte-v/574e9fcc55808a9f768ed36201493be5) by @malte-v will run in 177 seconds instead of 2134 seconds.

[Here](https://github.com/mawww/kakoune/blob/master/src/changes.hh#L46-L58) is the code in question.

EDIT: Fix iteration count.

**Comment by eraserhd** [comment]
(Oh, I'm thinking about doing this work.  The issue is for discussion on details.)

**Comment by mawww** [comment]
I dont quite fully understand where the quadratic complexity you refer to comes from, but the whole point of the logic in changes.hh is to transform a O(n^2) naive algorithm (update all ranges with all changes) in faster one by recognizing that:

1. ranges are sorted
2. changes are strictly sorted, but as they are usually generated through multi-selections and they can be seen as a flattened `list<sorted list<change>>` (each sorted list might be sorted forward or backward, backward ordering is usually the result of an undo operation).

For the case you describe I would expect linear time, the changes should be forward sorted and I'd expect `advance_while_relevant` to advance by one change for each range.

Now there does indeed seem to be some issue if we get the reported timings, I am just not sure the reason for that has been identified.

**Comment by eraserhd** [comment]
Ok, using this script:

```bash
#!/bin/bash

# git l is a git log which lots of color
PAGER='dd of=/tmp/git-l.txt' git l

for (( i = 0; i < 15 ; i++ )); do
    printf '== STEP %d ==\n' $i
    rm -f /tmp/in.txt
    for (( j = 0; j < i; j++ )); do
        cat /tmp/git-l.txt >> /tmp/in.txt
    done
    time ./src/kak.debug -n -e 'source ../kak-ansi/rc/ansi.kak ; ansi-render ; kill!' /tmp/in.txt
done
```

I get this N,real,user,sys:

```
0,0.093,0.023,0.029
1,1.397,1.166,0.194
2,2.752,2.329,0.372
3,4.089,3.490,0.550
4,5.461,4.625,0.786
5,6.751,5.803,0.893
6,8.108,6.936,1.110
7,9.584,8.178,1.308
8,10.743,9.250,1.415
9,12.201,10.469,1.641
10,13.421,11.554,1.807
11,14.742,12.657,2.008
12,16.086,13.818,2.196
13,17.449,14.951,2.406
14,18.724,16.116,2.525
```

Which is definitely linear:

![plot](https://user-images.githubusercontent.com/147284/109991261-2a562180-7cd8-11eb-888e-9a3339a47787.png)

**Comment by eraserhd** [comment]
I did this on Mac OS, with a nixpkgs environment, which uses clang.  NixOS uses gcc.  I wonder if there's a compiler difference which causes the lambda state (`it`) to be copied instead of referenced?  (This is what I thought was happening, originally.)

The following patch performs exactly the same for me, but does it do something for you, @malte-v?

```
diff --git a/src/changes.hh b/src/changes.hh
index 5ebb3ded..018d5adc 100644
--- a/src/changes.hh
+++ b/src/changes.hh
@@ -47,8 +47,8 @@ template<typename RangeContainer>
 void update_forward(ConstArrayView<Buffer::Change> changes, RangeContainer& ranges)
 {
     ForwardChangesTracker changes_tracker;
-    auto advance_while_relevant = [&, it = changes.begin()]
-                                  (const BufferCoord& pos) mutable {
+    auto it = changes.begin();
+    auto advance_while_relevant = [&] (const BufferCoord& pos) mutable {
         while (it != changes.end() and changes_tracker.relevant(*it, pos))
             changes_tracker.update(*it++);
     };
```

**Comment by eraserhd** [comment]
Ok, so I don't know about @malte-v's problem yet, but kak-ansi gets quadratic even when update-option is linear, for an obvious reason:  BufReadFifo is called for regular sized chunks, so it makes an outer, linear loop.  This means that every iteration, the time for `update-option` gets linearly bigger, and that all sums up to quadratic.

![timings](https://user-images.githubusercontent.com/147284/110179561-417b3900-7dd6-11eb-8f18-d0150e9e6362.png)

The purple is the total time for each BufReadFifo triggered.  Each iteration processes about 300 lines at the end of the buffer.  The green is the sum of all the shell executions and the sourcing of the script that adds new ranges for that iteration.  I have another log showing that `update-option` is indeed the culprit here.

So...

The only fix I can think of is to start `update_forward()` with a binary search for the first range for which the first change is relevant, and process ranges linearly from there.  This will work for this case.  

But is it too hacky (overly specialized) a change?  Is there something else we can do?

**Comment by malte-v** [comment]
Sorry for the late reply @eraserhd. Here is the new profile: https://gist.github.com/malte-v/ae7cfe4cee4c45a6cb7ed985557429a3.
Looks like your patch slightly improved the performance (it doesn't make much of a difference from a usability perspective though).

**Comment by mawww** [comment]
This is what I had after a quick investigation that led to the same conclusions as @eraserhd 

```diff
diff --git a/src/buffer_utils.cc b/src/buffer_utils.cc
index 206dc4b7..c572815f 100644
--- a/src/buffer_utils.cc
+++ b/src/buffer_utils.cc
@@ -157,7 +157,7 @@ Buffer* create_fifo_buffer(String name, int fd, Buffer::Flags flags, bool scroll
             // if we read data slower than it arrives in the fifo, limiting the
             // iteration number allows us to go back go back to the event loop and
             // handle other events sources (such as input)
-            constexpr size_t max_loop = 16;
+            constexpr size_t max_loop = 1000;
             bool closed = false;
             size_t loop = 0;
             char data[buffer_size];
diff --git a/src/changes.hh b/src/changes.hh
index 5ebb3ded..feda6019 100644
--- a/src/changes.hh
+++ b/src/changes.hh
@@ -53,8 +53,11 @@ void update_forward(ConstArrayView<Buffer::Change> changes, RangeContainer& rang
             changes_tracker.update(*it++);
     };

-    for (auto& range : ranges)
-        update_range(changes_tracker, range, advance_while_relevant);
+    auto range_it = std::lower_bound(ranges.begin(), ranges.end(), changes.front(),
+                                     [](auto& range, const Buffer::Change& change) { return get_last(range) < change.begin; });
+
+    for (auto end = ranges.end(); range_it != end; ++range_it)
+        update_range(changes_tracker, *range_it, advance_while_relevant);
 }

 template<typename RangeContainer>
```

This does improve the runtime but not yet into acceptable territory. I suspect part of the issue is also that Kakoune becomes irresponsive even though it should react to user input while processing the incoming fifo data.

**Comment by eraserhd** [comment]
I noticed that the `set-option -add ...` that executes every iteration also increases with the size of the existing option, although it was not nearly at the same constant factor as the `update-option`.  It could be the next bottleneck.

It looks like `option_list_postprocess()` sorts the whole list, so it's O(N log N).  It could sort the new elements and merge the lists in O(N).  I suspect that's the best we can do without a fancy data structure.

**Comment by eraserhd** [comment]
The `set-option -add` is the only thing growing now.  The `update-option` with the binary search part of the above patch is now miniscule!  (Please keep it.)  Strangely, I upped the file size and no matter what happens it processes the file in 150 iterations now?  I'm confused about that part.

![timings](https://user-images.githubusercontent.com/147284/110354531-458d9d80-8006-11eb-9a91-863a21d110b6.png)

Now it looks like I can do better by removing shell executions. I think I can remove the mktemp and rm by reusing a temporary filename, and I can get rid of the getstart by making the filter compute it.  That seems like 40% of the time.
