### ISSUE TITLE
Ruby auto-indent feature is misbehaving

### ISSUE THREAD

**Issue by greenfork** [mawww/kakoune#4086]
### Steps 

Copy this to file and save:
```ruby
class AccountsControllerTest < ActionDispatch::IntegrationTest
  test 'can bump sync date' do
    travel_to '2020-06-04' do
      assert_not account.can_bump_sync_date?


    assert_equal?
  end
end
```

Go to line right below `assert_not ...` and try to write `end` at the same level as `travel_to '2020-06-04' do`.

### Outcome 

`assert_equal?` is deindented to the very start of the line.

### Expected 

`assert_equal?` should stay at the same place.

**Comment by greenfork** [comment]
This is probably related to https://github.com/mawww/kakoune/pull/3634 by @johnisom

**Comment by johnisom** [comment]
@greenfork I no longer actively work on anything Kakoune since I'm busy with a job and studying heavily on the side. If you or anyone else can take this, please do so.

**Comment by greenfork** [comment]
Alright, thanks for letting know about it!
