### ISSUE TITLE
Add support for pure C to c-family & clang

### ISSUE THREAD

**Issue by bb010g** [mawww/kakoune#410]

**Comment by lenormf** [comment]
What's supposed to be supported from the C language that isn't already ?

**Comment by bb010g** [comment]
Mostly nicer Clang support (parsing as C rather than C++). (Highlighting could be more exclusive, but that's a minor issue.)

**Comment by mawww** [comment]
Done, C files should be detected correcty, highlighted only with C keywords, and clang completion/diagnostics should run in c mode.
