### ISSUE TITLE
Start kakoune in insert mode

### ISSUE THREAD

**Issue by D3faIt** [mawww/kakoune#4123]
Hi.

I'm making the switch from nano to kakoune, and was wondering if it's possible to start kakoune in insert mode?
_Might be something people generally NOT want to do, but as for the switch from nano, I think it's one step in the right direction_

In vim, I know you can do this with `vim -c 'startinsert' FILENAME`

**Comment by SolitudeSF** [comment]
kak -e 'exec i'

**Comment by alexherbo2** [comment]
You might want to start insert mode when creating a new client:

`~/.config/kak/kakrc`

``` kak
hook -group start-insert-mode global KakBegin '.*' 'execute-keys i'
hook -group start-insert-mode global ClientCreate '.*' 'execute-keys i'
```

With this config, `kak` will start in insert mode, and `:new` will start in insert mode as well.

See [Hooks] for other events.

[Hooks]: https://github.com/mawww/kakoune/blob/master/doc/pages/hooks.asciidoc

**Comment by D3faIt** [comment]
> You might want to start insert mode when creating a new client:
> 
> `~/.config/kak/kakrc`
> 
> ```
> hook -group start-insert-mode global KakBegin '.*' 'execute-keys i'
> hook -group start-insert-mode global ClientCreate '.*' 'execute-keys i'
> ```
> 
> With this config, `kak` will start in insert mode, and `:new` will start in insert mode as well.
> 
> See [Hooks](https://github.com/mawww/kakoune/blob/master/doc/pages/hooks.asciidoc) for other events.

Thank you! it worked!

A bit curious why this "no-hooks" shows up automatically now: 
![Screenshot_20210401_010300](https://user-images.githubusercontent.com/8147434/113221809-0b6e8f00-9286-11eb-8a3e-7f5413cff9ed.png)

**Comment by alexherbo2** [comment]
Replace with `execute-keys -with-hooks i`.

See [`execute-keys` specific switches] for more details.

[`execute-keys` specific switches]: https://github.com/mawww/kakoune/blob/master/doc/pages/execeval.asciidoc#execute-keys-specific-switches

**Comment by D3faIt** [comment]
That fixed it, thank you so much!

**Comment by stacyharper** [comment]
I'm trying to do this for a specific filetype. I got something like this but this is not working :(

```
hook global WinSetOption filetype=sms %{ 
    execute-keys -with-hooks i 
} 
 
hook global BufNewFile .*/Draft %{ set buffer filetype sms } 
```

**Comment by alexherbo2** [comment]
Try with `WinCreate` and `window` scope.

**Comment by stacyharper** [comment]
Mhh can you be more specific ? I think I tried all combination without success :D

**Comment by stacyharper** [comment]
Okay I found my way with : 

```
hook global BufCreate .*/Draft %{ 
    set buffer filetype sms 
    hook -once buffer WinDisplay .* %{ 
        execute-keys -with-hooks i 
    } 
} 
```
