### ISSUE TITLE
When no TMPDIR is set, tmux.kak will spawn shells with it set but blank

### ISSUE THREAD

**Issue by Elither** [mawww/kakoune#4161]
### Steps 

- have `TMPDIR` unset
- run kak in tmux and use one of  the `tmux-terminal` commands

### Outcome 

The new shell will have the `TMPDIR` variable set but blank. It will therefore not use the default but treat the current dir as the tmp folder when making fifo files and other similar things. This breaks some plugins such as kakoune.cr

### Expected 

It should not do this. The `TMPDIR` variable should stay blank and therefore cause the default to be used. I have temporarily mitigated this on my system by setting the `TMPDIR` variable in my `.bashrc`, but would prefer it to not be needed.

**Comment by Screwtapello** [comment]
This is because the `tmux.kak` plugin unconditionally sets `$TMPDIR` when launching tmux:

https://github.com/mawww/kakoune/blob/272b70298e357ceb6f6a7743c02c689106017116/rc/windowing/tmux.kak#L25

This behaviour was introduced to fix #1319.

**Comment by Elither** [comment]
Would it be possible to make it fail or set to a sane default if `$TMPDIR` is orignally blank? As it currently is, asuming that its not blank and causing this issue breaks quite a few plugins and general functionality. If not then at least a warning would be beneficial.

**Comment by Elither** [comment]
I have created a pull request that fixes this issue
