### ISSUE TITLE
Can't use -p with daemons on macOS

### ISSUE THREAD

**Issue by ne-on** [mawww/kakoune#4163]
I've tried:

- setting up a plist and using launchd via `launchctl`
- `brew install util-linux` and using `setsid`

These work, I can join them with `kak -c`,
but commands sent via `kak -p` have no effect.

If I run `kak -d -s $name &` in a shell, `kak -p` works,
but of course I can't exit the shell without losing the session.

On macOS 10.14, and installed kakoune from src yesterday.

Aside:
I understand removing forking, but it does cause some minor bumps on macOS:

- launchd uses static xml, hard to create on the fly
- `setsid` doesn't exist

**Comment by Screwtapello** [comment]
`kak -c` and `kak -p` use exactly the same mechanism to communicate with the server, so if one works, the other should too. What commands are you trying to send via `kak -p`?

Exiting the shell shouldn't close a backgrounded process. You may need to use the `disown` shell command to make sure the shell doesn't try to clean up backgrounded processes at exit (in my experience, `zsh` requires `disown` and `bash` doesn't).

**Comment by ne-on** [comment]
There was some confusion and tiredness on my part last night.
Once I took a fresh run at the basics, it does indeed work.

Sorry about that! Appreciate the prompt help and the work you do.
