### ISSUE TITLE
`builtin-terminal-ui` doesn’t render well in Zellij

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#4164]
[Zellij]

[Zellij]: https://zellij.dev

![2021-04-25_21:24:52](https://user-images.githubusercontent.com/5666362/116006760-e7943400-a60c-11eb-9e1d-68f8de38f4a9.png)

**Comment by mawww** [comment]
This looks to be an issue Zellij side.

First their implementation of `CSI H` looks to be broken, when the second parameter (the column) is absent it should default to the begining of the line but for some reason they seem to defaut to the line value...

Then they dont seem to implement `CSI M` to delete lines, which breaks scrolling.

**Comment by mawww** [comment]
A quick look at the Zellij code indicates that they indeed have bugs in their CSI H handling, this does not look to be a Kakoune issue, closing.
