### ISSUE TITLE
Using `kak` as $EDITOR causes errors with sudoedit/crontab

### ISSUE THREAD

**Issue by Somasis** [mawww/kakoune#417]
```
somasis@cicero:~/ % sudoedit /etc/paludis/notyetcreated
sh: xmessage: command not found
sh: xmessage: command not found
terminate called after throwing an instance of 'Kakoune::assert_failed'
sudoedit: /etc/paludis/notyetcreated unchanged
```

The exact same error happens if I run `crontab -e`.

**Comment by ekie** [comment]
assert failed "m_fs_timestamp != InvalidTime" at buffer.cc:51
[Debug Infos]
pid: 29039
callstack:
/usr/bin/kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x55efd8]
/usr/bin/kak(_ZN7Kakoune16on_assert_failedEPKc+0x2e) [0x5134ce]
/usr/bin/kak(_ZN7Kakoune6BufferC1ENS_6StringENS0_5FlagsESt6vectorINS_6RefPtrINS_10StringDataES5_EENS_9AllocatorIS6_LNS_12MemoryDomainE3EEEEl+0x58a) [0x4f470a]
/usr/bin/kak(_ZN7Kakoune23create_buffer_from_dataENS_10StringViewES0_NS_6Buffer5FlagsEl+0x63b) [0x4d357b]
/usr/bin/kak(_ZN7Kakoune23create_buffer_from_fileENS_10StringViewE+0xdc) [0x53b03c]
/usr/bin/kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0x689) [0x4e3c79]
/usr/bin/kak(main+0x1206) [0x453d56]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7f4f5e425610]
/usr/bin/kak(_start+0x29) [0x458d49]

**Comment by Somasis** [comment]
Also, I meant to mention this only happens if the file is not created yet.

**Comment by mawww** [comment]
Should be fixed now.
