### ISSUE TITLE
Allow to delete buffers under a directory

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#4173]
I’m using [sidetree] from @topisani and I would like to delete buffers under a directory.

`~/.config/sidetree/sidetreerc`

```
map d shell kcr send delete-buffer "$sidetree_entry"
```

So for example, if I select the `docs` directory, I can close all document buffers.

[sidetree]: https://github.com/topisani/sidetree

**Comment by mawww** [comment]
I have this in my kakrc:

```
define-command delete-buffers-matching -params 1 %{
    evaluate-commands -buffer * %{
        evaluate-commands %sh{ case "$kak_buffile" in $1) echo "delete-buffer" ;; esac }
    }
}
```

Deleting a buffers from a directory would be `delete-buffers-matching <dir>/*`

I dont think we need a built-in command for that.
