### ISSUE TITLE
repeat last normal command

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#42]
Possible candidates to repeat command with counts are `.` or `Tab`.

Example: `-m` to select the previous match, then type `Tab` to repeat `m` with `-1` as count.
#15 no equivalent to opposite direction
#41 support negative counts
#43 move 'n' command in 'm'

[EDITED] refer to normal commands

**Comment by lenormf** [comment]
I implemented the feature with the following snippet:

```kak
map -docstring 'repeat the last normal-mode command' global normal @ ': eval -- %sh{printf %s "${kak_main_reg_colon}"}<ret>'
```

One fewer keystroke than Vim, yay!
