### ISSUE TITLE
Grammar correction on projects web page

### ISSUE THREAD

**Issue by rjc** [mawww/kakoune#4212]
I'm glad the _fewer_ vs. _less_ issue has been resolved here, in the project repository - #968 #985 ;^)

Project's web page, however, still has the glaring:

> Modal editor · Faster as in less keystrokes · Multiple selections · Orthogonal design

Any changce to get that fixed? :^)

Web page repo perhaps?

**Comment by krobelus** [comment]
This is in the `gh-pages` branch

**Comment by rjc** [comment]
Ah, yes - I've missed the comment in on of the linked PRs. Thansk!

BTW, given that there's no mention of it in the `README` or anywhere else, it seems - this isn't obvious **at all**.

**Comment by rjc** [comment]
PR #4214 so closing this issue. Thanks again @krobelus
