### ISSUE TITLE
Allow users to build a statically linked binary

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#422]
Hi,

It'd be nice to be able to drop a `kak` executable on some remote server that doesn't have the required dependencies installed, and use the editor. Could we have a `Makefile` rule that allows to build a statically linked `kak` binary ?

Thanks.

**Comment by whereswaldon** [comment]
There appears to be a static option at the top of the Makefile, but it fails to compile if you enable it. It would really be nice if that worked though. I'm trying to make a portable version as well.

**Comment by lenormf** [comment]
@whereswaldon what is the error message you're getting? I successfully compiled a static binary on a Debian Stretch container, you will need the `libgmp-dev` additional package in order to generate it.

Please create a new issue if you're still having issues with building.

**Comment by whereswaldon** [comment]
The problem was my dyslexia, so it's all good. I was getting errors about libgpm, but making sure that libgmp was installed properly. Cheers!
