### ISSUE TITLE
Restore window title on quit

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#4228]
I’m using [Alacritty] in [Sway].

[Alacritty]: https://github.com/alacritty/alacritty
[Sway]: https://swaywm.org

**Comment by Screwtapello** [comment]
For security reasons, xterm doesn't allow the current title to be read out, so the title can't be restored that way. However, it *does* provide `\e[22t` to save the current title and `\e23t` to restore the most recently-saved title. Those are listed [in Alacritty's documentation](https://github.com/alacritty/alacritty/blob/master/docs/escape_support.md#csi-control-sequence-introducer---esc-) (under "CSI t"), and they seem to work in GNOME Terminal too.
