### ISSUE TITLE
No way to escape curly braces '}'

### ISSUE THREAD

**Issue by yerlaser** [mawww/kakoune#4245]
### Steps 

Add this to kakrc

`hook global InsertChar \{ %{ exec "\}<esc>hi" }`

### Outcome 

Error: wrong number of arguments for hook

### Expected 

No error, typing opening curly brace should automatically close it and move cursor inside the braces.

It appears the opening brace escape works because if I substitute the closing brace with any other character it gets inserted.
I tried wrapping it inside angular brackets and that doesn't help either.

**Comment by Calum-J-I** [comment]
You can actually use a range of symbols for a `%{ }` block to get around this issue. Try

```
hook global InsertChar '\{' %[  exec '}<a-;>h' ]
```

**Comment by yerlaser** [comment]
Yes, that works. Thank you.

But, don't you think that a special notation like <leftbrace> <rightbrace> would be better.

**Comment by yerlaser** [comment]
OK. Never mind, I'll close it as there's a working solution.
