### ISSUE TITLE
markdown syntax highlighting: inline code

### ISSUE THREAD

**Issue by basbebe** [mawww/kakoune#4247]
inline code is highlighted [using this regex](https://github.com/mawww/kakoune/blob/master/rc/filetype/markdown.kak#L95)

```
add-highlighter shared/markdown/inline/text/ regex "^( {4}|\t)+([^\n]+)" 2:meta
```

However, this – when indentation is set to 2 spaces – also highlights nested lists like these (_level 3_ and _continued level 2_, because they also are indented 4 spaces):

```markdown

- list level 1
- list level 1
  - list level 2
  - list level 2
    - list level 3
    - list level 3
  - list level 2
    continued level 2
  - list level 2
```

I'm not very experienced with regex and this is how far I got:

`"(?:(?:^\h*[^-*\n]+.*)|(?:\n))\n( {4}|\t)+([^-*\n]+.*)"`

But this does only get every other line of inline code and it also gets _continued level 2_.

Any idea how this could work?

And something else: Is it intended behavior that at _level 2_ only every other bullet is highlighted?

Thanks

**Comment by Ordoviz** [comment]
Related: #4196. Also see the discussion at #4208

**Comment by basbebe** [comment]
yep, sorry for overloocking these
