### ISSUE TITLE
Buffer reload popup not drawn automatically when continuing kak

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#425]
Hi,

When a buffer is modified and the kak process that edits it is suspended, the popup that asks the user if they would like to reload the buffer isn't displayed unless a key is hit, when resuming the execution of `kak`.

HTH.

**Comment by lenormf** [comment]
Hi,

The reload menu still isn't drawned automatically when receiving a `SIGCONT`, I still have to hit a key to have it displayed.

**Comment by mawww** [comment]
Now that is strange, it works flawlessly here. If you do `:e<c-z>fg<ret>` is the command completion menu and the `edit` command info box correctly restored ?

**Comment by lenormf** [comment]
@mawww yes it is.

Here is how I test this issue, first I edit the following file:
```

int
main (void)
{
return 0;}
```
Then I `^Z`, run astyle on the file with the default options (`astyle a.c`), resume the process (`fg`), and no menu is in sight unless I hit an arrow key or something.

**Comment by lenormf** [comment]
Just tried after recompiling the project from scratch, got an exception thrown back:
```
assert failed: 'uncaught exception (N7Kakoune13assert_failedE):
assert failed "buf == &buffer" at client.cc:192
[Debug Infos]
pid: 24096
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x503b48]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2e) [0x50245e]
kak(_ZN7Kakoune6Client13reload_bufferEv+0x61) [0x508381]
kak(_ZN7Kakoune6Client20on_buffer_reload_keyENS_3KeyE+0x5b8) [0x509a38]
kak() [0x50a21f]
kak(_ZN7Kakoune10InputModes7NextKey6on_keyENS_3KeyENS_9InputMode9KeepAliveE+0x41) [0x488bf1]
kak(_ZN7Kakoune9InputMode10handle_keyENS_3KeyE+0x32) [0x488942]
kak(_ZN7Kakoune12InputHandler10handle_keyENS_3KeyE+0x193) [0x483783]
kak(_ZN7Kakoune6Client22handle_available_inputENS_9EventModeE+0x12f) [0x50c70f]
kak() [0x55b749]
kak(_ZN7Kakoune9FDWatcher3runENS_9EventModeE+0x31) [0x4cc8d1]
kak(_ZN7Kakoune12EventManager18handle_next_eventsENS_9EventModeEP10__sigset_t+0x3f9) [0x4cd049]
kak(_Z10run_serverN7Kakoune10StringViewES0_bbbNS_9ArrayViewIKS0_EE+0x9ac) [0x4d73dc]
kak(main+0x1216) [0x455446]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7fbb67a58610]
kak(_start+0x29) [0x45a549]
'
pid: 24096
callstack:
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x503b48]
kak(_ZN7Kakoune16on_assert_failedEPKc+0x2e) [0x50245e]
kak(main+0x1908) [0x455b38]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7fbb67a58610]
kak(_start+0x29) [0x45a549]

sh: xmessage: command not found
terminate called after throwing an instance of 'Kakoune::assert_failed'
```

**Comment by mawww** [comment]
Still cannot reproduce, the assert failed should not happen anymore as the whole reloading code was refactored. Is it still happening ?

**Comment by lenormf** [comment]
Seems to be fine now.

**Comment by lenormf** [comment]
Actually recently I've had to go back to hitting a key to force the UI redraw when resuming execution of kak after a ^Z, so I guess this issue has to be reopened..
