### ISSUE TITLE
Ctrl-W deletes a word, not a WORD

### ISSUE THREAD

**Issue by PaulDugdale** [mawww/kakoune#4250]
### Steps 
Kakoune v2020.09.01 started with `-n`
In the Prompt, enter a `WORD` (consecutive non-whitespace)
e.g. `:this-is-a-test`
Press Ctrl-W to delete the `WORD` behind the cursor.

### Outcome 
Only the last `word` has been deleted, not the entire `WORD`
e.g. `:this-is-a-`

### Expected 
The entire `WORD` should have been deleted

Note: 
ctrl-w and ctrl-W have the same behaviour
alt-b and alt-B have the expected behaviours of moving back a `word` or a `WORD` respectively.

**Comment by nash-pillai** [comment]
I used the program **showkey** to see what codes are sent for each key. When CSI u was disabled both `<c-w>` and `<c-W>` sent `<ETB>` (Hex: 17). When CSI u was enabled `<c-w>` sent `<ETB>` and `<c-W>` sent `<ESC>[87;5u`. This was done on iTerm2.

This is not kakoune's fault. Without CSI u, it cannot tell the difference between the two. Try turning on CSI u in your terminal settings.

**Comment by PaulDugdale** [comment]
Great! Thank you so much.

I'll leave these links here in case they help:
https://iterm2.com/documentation-csiu.html
https://github.com/tmux/tmux/wiki/Modifier-Keys#limitations-of-ctrl-keys
