### ISSUE TITLE
builtin-terminal-ui: tmux interprets italics differently

### ISSUE THREAD

**Issue by krobelus** [mawww/kakoune#4260]
Happens since c12699d2e9c2806d6ed184032078d0b84a3370bb

### Steps

    echo > test.md "\
    [![Build Status][codebuild_img]][codebuild]
    [![Build Status][codebuild_windows_img]][codebuild_windows]"
    tmux new kak test.md

### Outcome

![image](https://user-images.githubusercontent.com/6853872/125353635-15169100-e363-11eb-9fce-6cd86107c142.png)

### Expected

White background throughout.

---

This is cause by this highlighter in markdown.kak:

    add-highlighter shared/markdown/inline/text/ regex (?<!_)(_([^\s_]|([^\s_](\n?[^\n_])*[^\s_]))_)(?!_) 1:+i

For sake of example, reduce to something that simply highlights all underscores

    add-highlighter global/ regex _ 0:+i

There are two things going on here

1. tmux does not interpret `+i` as italic but just swaps colors. This might be a regression, since it worked with ncurses.
2. the regex (which was last improved in 9e142c66436ce716fa5f26647ad843a1dc527a3a) wants to highlight `_italic_ _words_` but should not highlight `snake_word`.

**Comment by Screwtapello** [comment]
Kakoune now hard-codes the SGR 3 sequence for enabling italic. The shell command:

    printf '\e[3mhello\e[0m world\n'

...should produce:

> *hello* world

both inside tmux and outside it.

As another wrinkle, italic support is somewhat of a novelty among terminals (it's newer than 256 colour support, maybe not newer than 24-bit colour support), so even if tmux recognises that Kakoune is using italics, it may believe the outer terminal is not capable of rendering them, and is substituting a more widely available method of emphasis. I *think* tmux works off the terminfo database, so if `tput sitm; echo hello; tput sgr0` does not produce italic text in the outer terminal, that might be the problem.

**Comment by krobelus** [comment]
Thanks, yeah the printf command works but the tput one didn't.

The solution was to use set a proper TERM with `set -g default-terminal "tmux-256color"`
(instead of "screen-256-color").

I'll prepare a patch to fix the markdown highlighter
