### ISSUE TITLE
info box misaligment if left edge crosses double width character

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#4262]
In file with following text:
```
0123456789abc
let c = '藏';

info -anchor 1.11 %{line one
line two}
```
select two last lines, then type `:<c-r>.<ret>` in order to invoke selected info command.

Result is like this:
<img width="154" alt="Screen Shot 2021-07-13 at 22 09 06" src="https://user-images.githubusercontent.com/2206533/125495827-cd1b86dc-6f96-4271-9762-0c0d4652951f.png">

Expected info box with straight edges.

**Comment by mawww** [comment]
I am afraid Kakoune cannot really solve this issue as it would need somehow to display the first half of `藏` which is not possible on current terminals AFAIK. The best we can do is to print single column placeholder there which I guess would be better than the current status quo, but is not a proper fix either.

**Comment by Screwtapello** [comment]
For comparison, ncurses replaces the full-width character with a single-width space so the info box can be displayed. Once the info box is dismissed, the full-width character remains a single-width space until the line is redrawn (by selecting it, or with `<c-l>`). That last bit's probably a bug, but shows that it shouldn't be too difficult to be on par with ncurses, even if the result is not completely correct.

**Comment by mawww** [comment]
Also fixed the other case where the only the front of the double width character is overwritten (`info -anchor 1.10 X`)
