### ISSUE TITLE
Select the data inserted by the `p` and `P` primitives

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#4277]
Related to #1468

### Feature 

It'd be nice to have data arbitrarily inserted into the buffer via pasting be selected upon insertion.

### Usecase 

That feature would simplify the process of inserting data into a buffer that subsequently needs to be modified, especially when dealing with multiple line insertions (e.g. pasting from the clipboard).

This would probably have implications that are not necessarily comfortable to deal with interactively, I haven't thought much about it (better try it on a test branch and see how that goes).

HTH.

**Comment by krobelus** [comment]
How is this different from `<a-p>`? I guess because `p` just pastes one value from the given register.

**Comment by eraserhd** [comment]
I think this would be a big win.  IMHO, the selection information is currently effectively "lost" and has to be recreated.

1. Most times when I paste, it is followed immediately by `j` or `k`, or maybe some number and `g`.
2. `pi` has the same effect.  `pa` seems more predictable.
3. `p;` isn't hard in cases where it is wanted.  `p<a-;>;` well, is hard, but I don't think it would be used frequently.

**Comment by ctem** [comment]
Since redo results in selection, how about abusing it for a funny workaround like `map global normal p 'puU'`?

**Comment by Calum-J-I** [comment]
A possible implementation would be to add undo groups as a text object. The object would be defined by the start and end of the changed region(s) (for Type::Erase this would a single character). Counts would specify how far back in the history. You could then
```
map normal p 'pl<a-a>h'
map normal ! '!l<a-a>h'
```
where `h` stands for history since `u` is already taken.

**Comment by Delapouite** [comment]
A new experimental branch has been started on the topic: https://github.com/mawww/kakoune/commit/6e81879afd61a3fba0c8cbf3b63dc2bcf51e9b12

**Comment by occivink** [comment]
This can now be closed
