### ISSUE TITLE
Readonly support is broken

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#4278]
### Steps 

* `kak -ro foo.txt`
* `:e bar.txt`
* `:echo %opt{readonly}`

### Outcome 

The `readonly` option is set to `true` on the `bar.txt` buffer, which was opened without the `-readonly` flag.

### Expected 

Only `foo.txt` is in readonly mode.

### Note

Another reproducer:

* `:e foo.txt`
* `:e -readonly bar.txt`
* <kbd>ga</kbd>
* `:echo %opt{readonly}`

HTH.

**Comment by lenormf** [comment]
Any way to please set some sort of priority on this? I'll look into it myself as soon as I get the opportunity, but in the meantime it's making my Git merger trip (all buffer gets the readonly bit flipped).

**Comment by occivink** [comment]
does setting the `readonly` option to false manually (as opposed to using the switches) trigger this as well?

**Comment by lenormf** [comment]
Manually setting the option (`set buffer readonly true`) does not trigger the bug.

**Comment by lenormf** [comment]
Thanks for that!
