### ISSUE TITLE
Alias command not working with alias names containing '-' signs

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#428]
Hi,

This is an issue I could only reproduce in `rc/c-family.kak`, everything works just fine in other scripts of my own (i.e. `rc/golang.kak` or `rc/dlang.kak`).

In the `WinSetOption` hook that declares all the hooks and the `alt` alias, [here](https://github.com/mawww/kakoune/blob/master/rc/c-family.kak#L115), aliases won't work if they have '-' signs in their names. I've tried changing the order of declaration (the `alt` alias obviously works), the function that was alias'd, I checked that the aliases didn't exist prior to entering that scope… None of my tests worked aside from removing the '-' signs and making the names whole words.

I have no idea why that's happening, because the exact same alias names (with different callbacks) work perfectly in other files.

**Comment by mawww** [comment]
Not sure I get what's happening, here the comment-selection alias in that block works correctly, and does contain a '-' in its name.

**Comment by lenormf** [comment]
As you can see below, the aliases are just not recognized, but they are when I get rid of the `-` signs in the names.

![screen1](https://i.imgur.com/44YNyD3.png)

![screen2](https://i.imgur.com/nHHq0dd.png)

**Comment by mawww** [comment]
Hum, still cant reproduce `comment-selection` and `comment-line` aliases do work here, anything in the `*debug*` buffer ?

**Comment by lenormf** [comment]
No that's the thing, it doesn't look like there's any error, hence my supposition that the error comes from the alias command. I had a quick look at the parser that handles alias names, could this issue stem from its implementation ? It sounds unlikely since other files like `dlang.kak` manage to declare aliases with the exact same names, but idk.

**Comment by mawww** [comment]
You could try to break in AliasRegistry::add_alias, and see if anything special happens differently between the call for 'alt' and the others.

**Comment by lenormf** [comment]
Hi,
I did some debugging this evening, and I've got closer to the issue. Basically I removed every single file from my autoload and left only the following: `c-family.kak client.kak kakrc.kak mime.kak`. I then modified `alias_registry.cc` to print on the debug buffer all the aliases that were added when I open a C file, and here's the output (format: "a: {}; c: {}", alias, command):

```
a: e; c: edit
a: e!; c: edit!
a: w; c: write
a: wa; c: writeall
a: q; c: quit
a: q!; c: quit!
a: b; c: buffer
a: bn; c: buffernext
a: bp; c: bufferprev
a: db; c: delbuf
a: db!; c: delbuf!
a: ah; c: addhl
a: rh; c: rmhl
a: nc; c: nameclient
*** This is the debug buffer, where debug info will be written ***
a: alt; c: c-family-alternative-file
a: comment-selection; c: c-family-comment-selection
a: comment-line; c: c-family-comment-line
a: format-code; c: c-format-astyle
```

This output has not changed consecutively to any of the modifications I've made in files in the `autoload` directory.

So with only the files I mentionned above loaded, everything is fine (I can use all the aliases in my modified `c-family.kak` file, from the commenting to the formatting functions), but then I added another file that I had modified, `dlang.kak`, to the directory. By trial&error, I managed to narrow down the issue to the bit that declares the exact same aliases that `c-family.kak` declares too. If I change the names of the aliases in `dlang.kak`, everything goes back to normal for C buffers (I can use any all the aliases), but if the names stay the same, then none of them work. I checked that I hadn't used unicode hyphens instead of regular minus signs to write the alias/function names (it's happened to me recently, and it could have been an explanation), but the names are seemingly all declared correctly.

As I said above, there is no error whatsoever in the debug buffer either, so if there's an error somewhere, then it's being discarded silently. *But* when I copy my modified `c-family.kak` and my `dlang.kak` that only declares aliases to the global `/share/kak/rc` directory, everything works ; *however* when I copy my modified `c-family.kak` and my entire modified `dlang.kak` to the global directory, aliases fail again.

I quickly checked that funky syntax error was left undetected (unmatched parenthesis/bracket/etc, weird unicode sign instead of regular punctuation), and everything seems to be in order.

Do you have any other idea of things I could check for ? The alias names seem to be parsed just fine, but the function are not added to the "AST" under certain conditions…

**Comment by mawww** [comment]
Aha, very simple in fact, your unaliases in dlang.kak (and in golang.kak by the way) do not specify the expected value of the alias (they do in c-family.kak).

So whats happening is just that you have a hook that, for every window where the filetype is different from dlang, removes the aliases. use `unalias format-code dlang-format-dfmt` so that unalias only works if the current value of the `format-code` alias is `dlang-format-dfmt`,

**Comment by lenormf** [comment]
Oooh, that explains everything… I will modify and try that at home (I'll make a merge request for the wrong calls to `unalias` in the files I maintain).
