### ISSUE TITLE
Redrawing is sometimes done improperly when the process is resumed after a pause

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#429]
Hi,

The buffer fails to be redrawn sometimes, after the process is resumed after being suspended.

How to reproduce (it's seemingly random, so you might need a couple tries):
* open a file with `kak`
* suspend the process (`^Z`)
* resume the execution (`fg`)

HTH.

**Comment by mawww** [comment]
Cant reproduce here, does it still happen on your side ?

**Comment by lenormf** [comment]
I couldn't reproduce it either on neither of my upgraded setups, I'm closing the issue for now.

**Comment by lenormf** [comment]
Just had the issue with the latest build, this time with tmux: I made a new client to edit a file in a tmux session with `:new e file.hpp`, and the newly created buffer wasn't displayed properly (only the statusbar was rendered). It happens any time I open a new client in tmux, and only in tmux.

tmux 2.1-1
