### ISSUE TITLE
Error in debug, when opening file from within folder with spaces

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#4291]
Opening a file from within folder with space like `untitled folder` in my case, dumps following error in `*debug*`. It also happens when invoking `:change-directory` command into folder with space and then invoking `:edit file`.

```
shell stderr: <<<
sh: line 2: cd: /Users/vbauer/go/src/github.com/mawww/kakoune/untitled: No such file or directory
>>>
```

**Comment by krobelus** [comment]
This must be something in your configuration because Kakoune's `:cd` or `:edit` don't shell out. Did you override those commands?

**Comment by vbauerster** [comment]
No I didn't override those.
I'm on macOS and my default shell is zsh.

**Comment by Screwtapello** [comment]
Perhaps something has hooked the `BufNewFile`, `BufOpenFile`,`BufCreate`, `WinCreate` or `WinDisplay` hooks?

If I do:

    mkdir 'foo bar'
    kak -e 'edit "foo bar/blort"'

...I do not get any (relevant) messages in my `*debug*` buffer.

**Comment by vbauerster** [comment]
@Screwtapello You're right, I have some unquoted cd inside `BufOpenFile` in my config.
