### ISSUE TITLE
Is there a way to save the file when you forget to use sudo?

### ISSUE THREAD

**Issue by skittlesvampir** [mawww/kakoune#4294]
Hello people who read this,
in vim, when I edit a file that only root can access but I forgot to invoke sudo, I type `:w !sudo tee %` and my changes will be written with root privileges.
Is there an equivalent command for kakoune?

**Comment by alexherbo2** [comment]
@occivink wrote [kakoune-sudo-write].  You can check out the implementation [here][`sudo-write.kak`].

[kakoune-sudo-write]: https://github.com/occivink/kakoune-sudo-write
[`sudo-write.kak`]: https://github.com/occivink/kakoune-sudo-write/blob/master/sudo-write.kak

**Comment by skittlesvampir** [comment]
Thank you.
