### ISSUE TITLE
no such command: 'format'

### ISSUE THREAD

**Issue by SaphiraKai** [mawww/kakoune#4301]
### Steps 
I'm attempting to run `:format`

### Outcome 
I get the error `no such command: 'format'`

### Expected 
My Rust code should be formatted successfully

There's a good 90% chance I'm just doing something wrong, but I can't for the life of me find any information on how to set this up correctly. Everyone online seems to just be able to run `:format` and have it work

**Comment by krobelus** [comment]
Does it work with `HOME=$(mktemp -d) kak` ? If yes, then it must be something in you configuration.

**Comment by SaphiraKai** [comment]
Yup, sure does. What file is responsible for defining `format`?

**Comment by krobelus** [comment]
`%val{runtime}/rc/tools/format.kak`

**Comment by krobelus** [comment]
If you have created your own autoload (which you probably don't want) then you could place a symlink to `rc` in your autoload dir.

**Comment by SaphiraKai** [comment]
I just copied the file to my autoload... Oh. yeah that's a more intelligent solution, I'll try that thanks xD

**Comment by SaphiraKai** [comment]
All is well now. Thanks for the help!
