### ISSUE TITLE
Flicker (lines drawn too high)

### ISSUE THREAD

**Issue by kak-0** [mawww/kakoune#4320]
After upgrading to v2021.08.28, I often see flicker. I use xterm.

One way I can reproduce it is when opening the following file with `kak -n`:

```

--------------------------------------------------------------------------------

********************************************************************************

--------------------------------------------------------------------------------

********************************************************************************

--------------------------------------------------------------------------------

********************************************************************************

--------------------------------------------------------------------------------

********************************************************************************

--------------------------------------------------------------------------------

********************************************************************************

--------------------------------------------------------------------------------

********************************************************************************

--------------------------------------------------------------------------------

********************************************************************************

--------------------------------------------------------------------------------

********************************************************************************
```

If I press `]p` and then press and hold `<a-.>` to go down the file, then there is often flicker. Specifically, it seems all lines below the selection (including the status line) are briefly drawn 2 lines higher than they should be, before being redrawn correctly.

The first bad commit is 5466f63eebad4e7957b611919ca3d74dc6bad187 (Use insert/remove lines escapes to reduce terminal traffic).

**Comment by kak-0** [comment]
The bug reappears in v2021.10.28 (using xterm).

The first bad commit is 60165bacf93a6625571c38cc8ab7ea182b5b1dec (Use DECRQM/DECRPM to detect support for synchronized output).

Workaround:

```
set-option -add global ui_options terminal_synchronized=false
```

**Comment by kak-0** [comment]
Can you reopen this issue?
Apparently I don't have permission to reopen it because it wasn't closed by me.

**Comment by mawww** [comment]
I can re-open this, however this is a weird bug that could indicate either our detection code is wrong, or xterm advertises support but does not actually do synchronized output.

**Comment by Screwtapello** [comment]
What version of xterm are you using? I'm using xterm 369, and I get:

    $ printf '\033[?2026$p'; cat
    ^[[?2026;0$y

Since the last parameter there is 0, that should indicate "this mode is not supported" and Kakoune should interpret that as "don't use the synchronisation codes".

**Comment by Screwtapello** [comment]
(as a different issue, GNOME Terminal reports "4", indicating "this mode is permanently disabled", but since it's not 0, Kakoune will assume the mode is available and try to enable it anyway)

**Comment by kak-0** [comment]
> What version of xterm are you using? I'm using xterm 369, and I get:
> 
> ```
> $ printf '\033[?2026$p'; cat
> ^[[?2026;0$y
> ```

xterm 369, and I get the same.

This code seems wrong:

```
                if (params[0] == 2026)
                    m_synchronized.supported = (params[0] != 0);
```

If `params[0] == 2026` then `params[0] != 0` is always true.

**Comment by Screwtapello** [comment]
That... is a very good point and I'm a little ashamed I didn't notice that myself.

**Comment by mawww** [comment]
Ouch, I guess that's on me for only testing this against a terminal that does not answer at all and one that supports the feature.

**Comment by mawww** [comment]
That should be fixed now, detection looks ok on xterm here, but could you confirm this works as expected on your side @kak-0 ?

**Comment by kak-0** [comment]
It does. Thank you.
