### ISSUE TITLE
Forward jump no longer working in kitty (regression)

### ISSUE THREAD

**Issue by jtrees** [mawww/kakoune#4333]
### Steps 
- Open a scratch buffer
- Jump to end of buffer (`ge`)
- Jump back (`<c-o>`)
- Attempt to jump forward again (`<c-i>`)

### Outcome 
Nothing happens.

### Expected 
The selection should jump back to the end of the buffer.

### Comments
This appears to be a regression that was introduced somewhere between v2020.09.01 and v2021.08.28.

**Comment by Screwtapello** [comment]
I cannot reproduce this problem with `kak -n` in GNOME Terminal, or in xterm.

**Comment by jtrees** [comment]
Oh, interesting. I am using [kitty](https://sw.kovidgoyal.net/kitty/) but can confirm that it still works with GNOME Terminal.

**Comment by jtrees** [comment]
The kitty maintainer wrote this:

> This will be a bug in kakoune's support of the extended keyboard protocol

Dunno if that helps.

**Comment by Screwtapello** [comment]
I guess this should be marked as a dupe of #4242

**Comment by jtrees** [comment]
Ah, that makes sense.

**Comment by jtrees** [comment]
I'd like to re-open this. PR #4415 fixed most key-combos for me but <c-i> still isn't working.

**Comment by mawww** [comment]
Should be fixed now.

**Comment by jtrees** [comment]
Yay! It works! Thanks a bunch. <3
