### ISSUE TITLE
Use Asciinema for demos

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#434]
[asciinema](asciinema.org) offers the following advantages over gifs/videos:
- ability to copy text
- bandwidth usage
- easy markdown embedding

**Comment by lenormf** [comment]
The website already loads bootstrap's js library, which requires jquery, I don't think adding more javascript will make for a nice user experience. The videos are light in size, and users have no text to copy from those since they just demonstrate features.

**Comment by mawww** [comment]
Latest video I just added wont work as well, as it shows multiple terminals handled by i3, as much as I like asciinema in principle, it seems more practical to stay with videos.
