### ISSUE TITLE
Characters may get duplicated when changing case

### ISSUE THREAD

**Issue by tomKPZ** [mawww/kakoune#4347]
### Steps

The issue reproduces with kakoune v2021.08.28
Start with ```FOO BAR```.  Type ```xS\s*<ret>` ```.

### Outcome 
```foo bbar```

### Expected
 ```foo bar```

**Comment by lenormf** [comment]
Can't reproduce with `kak -n`.

**Comment by Screwtapello** [comment]
If I checkout v2021.08.28 and build it (gcc 10.3 on Debian Testing):

```console
$ echo "FOO BAR" | kak -f 'xS\s*<ret>`'
foo bbar
```

Using the latest commit on master:

```console
$ echo "FOO BAR" | kak -f 'xS\s*<ret>`'
foo bar
```

...so apparently this has already been fixed. None of the commits since v2021.08.28 look especially relevant, though.

**Comment by tomKPZ** [comment]
A bisect points to 33a80e644ccf19d1059363ac0555148e7bff6e3d (the first commit after the v2021.08.28 release) that fixed the issue.  I don't understand why it fixes the issue, though.

**Comment by tomKPZ** [comment]
Issue is fixed in latest release
