### ISSUE TITLE
v2021.08.28: `set global ui_options ncurses_status_on_top=yes` not working

### ISSUE THREAD

**Issue by jericdeleon** [mawww/kakoune#4348]
### Steps 
1. Use Kakoune v2021.08.28 together with a `kakrc` containing a single line:
```
set global ui_options ncurses_status_on_top=yes
```

### Outcome 
Status / Command Line should appear at the top

### Expected 
Status / Command Line remains at the bottom

**Comment by Screwtapello** [comment]
Kakoune no longer uses the ncurses library, so `ncurses_*` options no longer do anything.

You probably want the new `terminal_status_on_top=yes` UI option.

**Comment by jericdeleon** [comment]
`terminal_status_on_top=yes` works as expected, thank you!
