### ISSUE TITLE
Markdown syntax highlighting: closing ``` ignored after indented code

### ISSUE THREAD

**Issue by kak-0** [mawww/kakoune#4351]
When opening the following Markdown file in Kakoune:

    ```
        a
    ```

    b

The closing ``` is not detected, causing `b` to be highlighted like a codeblock.
This seems to happen whenever there is indented code inside a codeblock.

The relevant highlighters from `markdown.kak` are: 

```
add-highlighter shared/markdown/inline/codeblock region -match-capture \
    ^(\h*)```\h* \
    ^(\h*)```\h*$ \
    fill meta
add-highlighter shared/markdown/codeblock region "^( {4}|\t)" "$" fill meta
```

**Comment by Ordoviz** [comment]
The fenced codeblock highlighter should not be inline.  I suggest the following simple fix:
```kak
add-highlighter shared/markdown/codeblock region -match-capture \
    ^(\h*)```\h* \
    ^(\h*)```\h*$ \
    fill meta
add-highlighter shared/markdown/codeline region "^( {4}|\t)" "$" fill meta
```
Please test for regression.

**Comment by krobelus** [comment]
Yep, that fix looks good.
I believe that nested region highlighters are applied starting from the outermost one: first the `shared/markdown` region was applied, which contained the indented code block. This split up the file, so the inner highlighter would see two disjoint regions.

> codeline

I think we should use `fenced_code_block` and `indented_code_block`, to follow CommonMark terminology.

**Comment by kak-0** [comment]
@Ordoviz Your fix works. I think it can be merged.
