### ISSUE TITLE
Create man page buffers in read-only mode

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#4357]
### Steps 

* Open a man page, e.g. `:man man`
* Hit a primitive that would modify the buffer in some way, e.g. <kbd>o</kbd>

### Outcome 

The buffer is modified.

### Expected 

An error is thrown, that mentions the buffer cannot be modified.

**Comment by lenormf** [comment]
Not too stressed about that one, the desired behaviour can be picked from the user configuration easily, whichever users pick.

However, I think it makes sense to make this a default, as users are not expected to edit these files.

**Comment by krobelus** [comment]
No strong opinion on this one but I love the fact that `*grep*` and `*make*` are editable.

**Comment by occivink** [comment]
Same. At least for `*grep*` it's an easy way to do further filtering by removing lines that do or do not match a pattern (and also it happens to be useful combined with [one of my plugins](https://github.com/occivink/kakoune-find))

**Comment by lenormf** [comment]
Got it, I'll just set this behaviour in my user configuration, then. Thanks for the feedback!

**Comment by lenormf** [comment]
Not exactly as easy as I thought it'd be, since there are hooks that modify the buffer on resize, but that does the job:

```kakscript
hook global WinSetOption filetype=man %{
    set-option buffer readonly true
    remove-hooks window man-hooks
    hook -group man-hooks window WinResize .* %{
        set-option buffer readonly false
        man-impl %opt{manpage}
        set-option buffer readonly true
    }
}
```
