### ISSUE TITLE
Alt-Commands conflict with special character insertion.

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#436]
As a German user, i want to type some umlauts now and then. However I do not use the german QWERTZ layout but rather Colemak, which requires holding the alt-key to insert characters with accents. This is sort of a hindrance when writing a thesis for example, because I have to do some stupid workaround to either insert such a character or join some lines.

**Comment by lenormf** [comment]
As a workaround, you could set your keyboard layout to another layout, and use a compose key to insert special characters.

**Comment by FranzSkuffka** [comment]
I could also re-create the alt-commands in a different way or copy and paste the special characters. My question is rather whether this is a permanent, viable solution.

Is it possible to remap the alt-commands? If yes, can you give me an example?

**Comment by mawww** [comment]
you cannot remap 'alt' as a whole, but you can remap individual commands using `:map`

for example, you can remap `<a-a>` to `<c-a>` in normal mode using `:map global normal <c-a> <a-a>`

**Comment by dumblob** [comment]
Just popped up in my mind: is there any possibility to dump (to the buffer or stdout or some file) all currently defined keyboard mappings in use from a running kak session?

**Comment by mawww** [comment]
well, we could write some infos in the debug buffer, with a `:debug keymap` but not sure what we could write there besides the key itself.

**Comment by dumblob** [comment]
>well, we could write some infos in the debug buffer, with a `:debug keymap`

Sounds reasonable.

>but not sure what we could write there besides the key itself.

The idea is to ease (massive) remapping, so if it's possible to write there some hints about what the mapping does, I would do that (e.g. the descriptions shown by the built-in clamp help).

**Comment by mawww** [comment]
You can already get most of that by just taking the code in normal.cc, that has a big array of the mapping, IIRC there is a ruby script that does exactly that to extract the key list that is in the wiki.

**Comment by dumblob** [comment]
Oh, thanks @mawww, I completely missed the `contrib/` directory. It seems to be good start as there shouldn't be many later defined bindings.

**Comment by niko** [comment]
What's the best workaround for this? I'm running a QWERTZ-MBP with Linux (I know) and OSX keybindings. The ALT-key is pretty much occupied.

I modified the kakmap.rb to generate a .kak file which remaps ALT to CTRL (where not occupied itself)… is this the way to go?

**Comment by mawww** [comment]
Ctrl is tricky because a few combinations maps to other keys, `<c-m>` is `<ret>`, `<c-i>` is `<tab>`. I am not familiar with QWERTZ, but on AZERTY keyboards its altgr that is used to some accentuated characters, maybe the is something to do between alt and altgr.

**Comment by niko** [comment]
Hm. My keyboard looks like this:

![MacBook QWERTZ(http://www.meicronshop.com/WebRoot/Store18/Shops/63229397/53ED/D88D/9602/8829/E3A3/C0A8/2ABB/C8DC/AMBP_QWERTZ_Tastatur_Folie_1.png)

No ALT_GR. :(

I use CMD as CTRL and CTRL as i3-MOD key. ALT is ALT. FN is used for media keys. CTRL is definitley the most ergonomic choice.

A Mac keyboard may be a special case… but it's the same on OSX I think. CMD and FN are taken. ALT is a modifier. That leaves CTRL.

I never encountered an app which uses ALT as much as kakoune does.

**Comment by FranzSkuffka** [comment]
@niko that is just my issue. Kakoune's heavy usage of alt severely impacts it's usability on Mac Computers. ALT is used for special character insertion and critical for us.
However, FN is not really taken. It is actually barely used and I mapped it to snap windows in combination with arrow keys.

**Comment by mikebenfield** [comment]
Is there any workaround or plan to fix this? As far as I can tell, kakoune isn't really usable on a Mac right now (the ALT- bindings just don't work at all for me).

**Comment by FranzSkuffka** [comment]
@mikebenfield take a look at the wiki on how to enable ALT:
https://github.com/mawww/kakoune/wiki/Normal-mode-commands

If you can spare special character insertion you can use the alt key for kakoune instead.
But 'not really usable' is a superstition. I use it without the alt key and it's perfectly fine.

**Comment by mikebenfield** [comment]
Ah, I missed that bit on the wiki; thanks.

**Comment by mawww** [comment]
I was wondering about that problem, and one possible solution is to have a prefix key that acts as alt, lets call it <prefix>, we would interpret <prefix> followed by <key> as <alt-key>. The remaining problem would be to find that key, the keyboard is already full, and we want a very accessible key for that.

Would that be ok ?

**Comment by niko** [comment]
@mawww: +1

**Comment by dumblob** [comment]
@mawww +1

**Comment by FranzSkuffka** [comment]
@mawww +1 let's just remap caps lock :laughing: For that reason, it would be great if `<prefix>` could be a combination of keys.

**Comment by mawww** [comment]
it would be yeah, but we again hit limitations of the terminal input model...

**Comment by dumblob** [comment]
Well, maybe we should first ask @leonerd if it's somehow solvable as he's the creator of the awesome library libtickit https://github.com/leonerd/libtickit . Any ideas @leonerd ?

**Comment by leonerd** [comment]
I probably have tonnes of ideas. But I have more questions.
Are you a terminal program? What are you processing input with currently? I see mentions of being vim-like. Vim in particular is terrible at this, due to mistakes in its own internal model.
Programs in general can solve this problem just fine, but how much work it would take for your program in particular depends a lot on internal architecture.

**Comment by mawww** [comment]
Hi @leonerd,

We currently use ncurses with some additional manual escape sequences handling (for focus in/out events for example), and timeout based alt detection. The implementation is in src/ncurses_ui.cc, mainly the `NCursesUI::get_key` method.

**Comment by vbauerster** [comment]
iTerm2 allows to refine how alt key should act. `Normal` option will let you input special characters.
[![i_Term-alt.png](https://s25.postimg.org/6zbb2awz3/i_Term-alt.png)](https://postimg.org/image/f4td0gl7v/)

**Comment by meydjer** [comment]
Check [Setting up Kakoune on Mac](https://medium.com/@Jernfrost/kakoune-the-text-editor-i-didnt-know-i-needed-23d5f1d6ad97)
