### ISSUE TITLE
Initialise an `str-list` with a shell scope

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#4361]
I want to initialise a list with the data returned by a shell command. `decl str-list test %sh{env}` puts the totality of the output in one element.

The best I have at the moment is a shell scope that adds values to the list by writing on `$kak_command_fifo`. But it's not really elegant so, is there a way out of this?

**Comment by occivink** [comment]
As discussed on irc, this can be done by adding a parsing level with `eval`, like so:
`eval decl str-list test %sh{echo a "'b c'" d}`
which would result in the three items `a`, `b c` and `d`.

For trivia's sake, this was changed in ec169696, before that the output of %sh{} blocks would always be automatically reparsed.

**Comment by lenormf** [comment]
Thanks!
