### ISSUE TITLE
Add more letter case commands

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#4369]
We have:

- **Lowercase** ⇒ Convert to lowercase in selections.
- **Uppercase** ⇒ Convert to uppercase in selections.
- **Swap case** ⇒ Swap case in selections.

We don’t have:

- **Capitalize** ⇒ Convert the first letter to uppercase and every subsequent letter to lowercase in selections.
- **Camel case** ⇒ Convert underscores to camelcase boundaries in selections.
- **Snake case** ⇒ Convert camelcase boundaries to underscores in selections.

See also [Letter case].

[Letter case]: https://en.wikipedia.org/wiki/Letter_case

**Comment by Delapouite** [comment]
I often use this plugin from for this kind of tasks: https://gitlab.com/FlyingWombat/case.kak

**Comment by mawww** [comment]
All of those should be trivially implementable with the existing primitives, I dont think we need to make them core features.
