### ISSUE TITLE
What does the status line print, and can it be modified?

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#437]
Hi,

Here is an example of what the right part of the status line is displaying for me:
`filename 25:1 [+] 1 sel - unnamed0@[9923]`
I'm specifically wondering about the meaning `[+]` and `unnamed0@[9923]`. I haven't seen anything in the documentation about it.

As mentionned in the title, can I modify what is being printed? Not that there is anything I would like to change, I'm mostly wondering.

**Comment by mawww** [comment]
Hello. The [+] signifies the buffer is modified compared to the file system version. Unnamed0@[9923] means this is client 'unnamed0' (can be changed with the nameclient command) on session '9923' (can be set at launch with the -s switch). 

Part of the modeline is controlable through the modelinefmt option (see readme)

**Comment by occivink** [comment]
Ah, so this is called the mode line. Thanks for your answer.

Let me also compliment you on the design of this editor.
