### ISSUE TITLE
putty mouse copy/paste 

### ISSUE THREAD

**Issue by lougxing** [mawww/kakoune#4372]
### Question

I connect the server with putty. editing a file with kakoune,  How to copy/paste with the mouse ?

**Comment by Screwtapello** [comment]
Most applications don't request mouse events from the terminal, so when you click and drag, the terminal does highlighting (and sometimes copy/paste) itself.

Kakoune *does* request mouse events, so when you click and drag the terminal passes them straight through, and doesn't process them.

If you hold down Shift while clicking or dragging, that will temporarily prevent Kakoune from receiving mouse events, so the terminal's highlighting (and sometimes copy/paste) will work as usual.

If you add something like:

    set-option global ui_options terminal_enable_mouse=false

...to your `.kakrc`, that will permanently prevent Kakoune from requesting mouse events.

**Comment by caksoylar** [comment]
User questions like this one are probably more appropriate for one of the communities listed at https://kakoune.com/, such as IRC, discuss.kakoune.com or Discord. You might find that this or a similar question has already been asked and answered.

**Comment by lougxing** [comment]
@Screwtapello  thanks again.
@caksoylar I Got it.
