### ISSUE TITLE
I'm able to compile and run all sorts of programs in vim, Want that block of vimscript to run in kakoune

### ISSUE THREAD

**Issue by zim0369** [mawww/kakoune#4377]
```
### Question

"shortcut to run current filetype
map mr :call CompileRunGcc()<CR>
func! CompileRunGcc()
    exec "w"
    if &filetype == 'c'
        exec "!clear && gcc % -o %<"
        exec "!clear && time ./%<"
    elseif &filetype == 'cpp'
        exec "!clear && g++ % -o %<"
        exec "!clear && time ./%<"
    elseif expand('%:t') == 'main.rs'
        exec "!clear && cargo build --manifest-path=%:p:h:h/Cargo.toml"
        exec "!time cargo run --manifest-path=%:p:h:h/Cargo.toml"
    elseif &filetype == 'rust'
        exec "!clear && rustc %:p --out-dir=%:p:h"
        exec "!time " .expand("%:p:r")
    elseif &filetype == 'java'
        exec "!clear && javac %"
        exec "!clear && time java -cp %:p:h %:t:r"
    elseif &filetype == 'sh'
        exec "!clear && time bash %"
    elseif &filetype == 'python'
        exec "!clear && time python3 %"
    elseif &filetype == 'javascript'
        exec "!clear && time node %"
    elseif &filetype == 'html'
        exec "!brave-nightly % &"
    elseif &filetype == 'tex'
        exec "!pdflatex --output-directory=%:p:h %"
    elseif &filetype == 'go'
        exec "!go build %<"
        exec "!clear && time go run %"
    elseif &filetype == 'text'
        exec "!clear && echo 'words : ' && wc -w % && echo 'lines : ' && wc -l % && echo 'size : ' && du -h %"
    elseif &filetype == 'noft'
        exec "!clear && echo 'words : ' && wc -w % && echo 'lines : ' && wc -l % && echo 'size : ' && du -h %"
    elseif &filetype == 'markdown'
        exec "!clear && echo 'words : ' && wc -w % && echo 'lines : ' && wc -l % && echo 'size : ' && du -h %"
    endif
endfunc

```

These are the most important lines in my vimrc. I can open vim from any folder and compile and run programs without being in that particular directory. The path's are correctly expanded and programs can build and run without any issue. For example to build a cargo package I have to be in a directory where cargo can find the Cargo.toml file but with vim I just don't need to care. I can just open the main.rs from anywhere, edit, build, run... Same goes for all the filetypes. Can I do this with kakoune. Or maybe things could be simpler if I were able to do this correctly inside kakoune :
`%sh{vim -c "norm mr" %val{buffile}}`
I want this to equate to a shell command -> `vim -c vim-commands filepath`
I tried using this to run the program inside of vim instead of kakoune and thus avoiding to convert the above vimscript block to adapt to kakoune. But this didn't work. Even if this line worked I'd be more than happy to keep learning and using kakoune.

**Comment by krobelus** [comment]
The easiest way is to define your own `makecmd` in your `kakrc`:

```kak
set global makecmd 'kake "${kak_buffile}"'
map global user m %{: write-all<ret>:make<c-p><ret><esc>} -docstring 'make [<arguments>]'
```

This means that the `:make` command will run a custom script and pass the name of the file as argument.
The second line adds a mapping `,m` that saves all modified buffers and runs your most recent ":make" command.

The `kake` script could look like this:

```sh
#!/bin/sh
set -e
file=$1
shift
case "$file"
	c)
		gcc "$file" -o "${file%.*}" &&
		time ./"${file%.*}" "$@"
	;;
esac
```

This way the logic is independent of the editor.

**Comment by Calum-J-I** [comment]
To add to krobelus' comment `%opt{filetype}` or `$kak_opt_filetype` in a shell block is equivalent to `& filetype`.

**Comment by zim0369** [comment]
Thanks that made things a bit simpler.
