### ISSUE TITLE
Link Website URL in Repository description

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#438]
There is no interconnection between the repo and http://kakoune.org/ yet.

**Comment by lenormf** [comment]
As discussed on IRC, I reckon most people find the github page through the website, and not the other way around. There's no info on the webpage that isn't on the project page either, so it doesn't seem necessary to link back to the landing page.

**Comment by FranzSkuffka** [comment]
In terms of SEO it would still make sense to link the website on the github page.
