### ISSUE TITLE
wrong linebreak indentation on fennel filetype

### ISSUE THREAD

**Issue by eko234** [mawww/kakoune#4386]
### Version of Kakoune

v2021.08.28-80-g689553c2

### Reproducer

- open a file with the fnl extension
- enter insert mode
- try to enter the following code withouth exiting insert mode
  ``` fennel
  (fn test []
    (print "hello"))
  ```
NOTE: obviously we don't want to use trailing whitespaces

### Outcome

``` fennel 
    (fn test []
       _main_selection_
    )
```

### Expectations

the line break at the first line after the lambda list should not indent in a c lang fashion, insted it should
let a state as this:
``` fennel
    (fn test []
        _main_selection_)
```

**Comment by krobelus** [comment]
works for me, please try without config (`HOME=$(mktemp -d) kak test.fnl`)

**Comment by eko234** [comment]
mmm, I forgot to mention I use autopairs, maybe it is in conflict with the hooks.

**Comment by eko234** [comment]
this definitely is not a bug, sorry, I think I should take it to the auto-pairs repo.

**Comment by eko234** [comment]
upon seeing the issues there, seems some functionality is broken due to an actual bug with kakoune hooks, will just leave it here for the record.
