### ISSUE TITLE
Cannot scroll down with MBUTTON anymore

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#439]
Hi,

I can't scroll down with the middle button of my mouse anymore, either in normal or insert mode.

572cf9d

HTH.

**Comment by mawww** [comment]
Hello, do you mean using the scroll wheel does not work anymore ?

**Comment by lenormf** [comment]
Yep.

**Comment by mawww** [comment]
Does setting `ui_options ncurses_wheel_down_button=5` help ?

**Comment by lenormf** [comment]
Yes, that fixed it. Why did it stop working out of nowhere ?

**Comment by mawww** [comment]
not sure, did you change your terminal emulator/start using tmux ?

**Comment by ekie** [comment]
same happened for me, i have no recent terminal emulator update. can this relate to a ncurses 6 update ?

**Comment by lenormf** [comment]
@mawww I noticed it didn't work in tmux either, but I mostly use `kak` outside of it. I almost always upgrade to the latest versions of all my packages as soon as they're available, so I run the latest "everything": termite 4b08fd9, vte3-ng 0.42.0.a, ncurses 6.0.

**Comment by mawww** [comment]
could be from ncurses yeah.
