### ISSUE TITLE
[BUG][CRASH] command_fifo fast re-opening crashes kakoune

### ISSUE THREAD

**Issue by mralusw** [mawww/kakoune#4410]
### Version of Kakoune

v2021.10.28

### Reproducer

```
nop -- %sh{
  i=9000
  while :; do
    i=$(( i - 1 ))
    [ $i -ge 0 ] || break
    echo >"$kak_command_fifo" 'echo -debug hi'
  done
}
```

### Outcome

Immediate crash with `kak` most of the time (debug or stripped, gcc 9/10 or clang-12).

Adding a delay (`sleep 0.1`) avoids crashes. Or maybe it makes them less frequent.

With `valgrind kak`, source it a couple of times to get invalid reads/writes in `handle_next_events()` (`event_manager.cc:143`): [vg.log](https://github.com/mawww/kakoune/files/7439577/vg.log). Relevant code:
```
              if (it != m_fd_watchers.end())
                  (*it)->run(events, mode);
```

### Additional information

You might say "keep the FIFO open as long as possible", but until closing the FIFO, `kak` doesn't interpret any commands sent to it that way. Thus, no interactive screen updates, which would make the feature pointless.

Another crash courtesy of `handle_next_events()` (in `pselect`), also caused by fast re-opening of `command_fifo`. No repro, just the log; this occured while trying to add `command_fifo` support to the plugin manager https://github.com/jdugan6240/kak-bundle but I can't really reduce the code to minimal example. Valgrind: [vg.log](https://github.com/mawww/kakoune/files/7439497/vg.log)

There are several other problems, including missed commands, unreliability of `response_fifo` ("interrupted system call" when the shell `read`s from it; then on retry, a hang). Pretty hard to reduce to reproducible examples, but I might give it a try.

Of course, `command_fifo` is hardly documented, probably hardly tested, and, it seems, hardly used by the community if at all.

**Comment by alexherbo2** [comment]
It could be nice for the FIFO creation and lifetime to be explicit, and inspired by channels in programming languages.

``` kak
evaluate-commands -with-fifo %{
  # Writes `echo %val{selections}` in FIFO.
  spawn echo -to-file %val{response_fifo} -quoting kakoune -- echo %val{selections}

  # Executes `echo %val{selections}`.
  echo -to-file %val{command_fifo} -quoting kakoune -- echo %val{selections}

  # Executes the command received in the FIFO.
  evaluate-commands %sh{
    cat "$kak_response_fifo"
  }

  # Same with `nop`.
  nop %sh{
    cat "$kak_response_fifo" > "$kak_command_fifo"
  }
}
```

**Comment by mralusw** [comment]
@alexherbo2 these seem like worthwhile ideas (you'd need to explain more, as there is no `spawn` or `%val{response_fifo}` &mdash; and it's not clear what they would do). But first of all, `{command,repsonse}_fifo` needs to not crash.

I've tried the latest commits in `master` and at least my repro seems to not crash anymore.

**Comment by alexherbo2** [comment]
I’m such a noob to explain, but I will try.

We have `%val{name}` in Kakoune and `${kak_name}` or `${kak_quoted_name}` in the shell.

We define the creation and the lifetime of the FIFOs with `evaluate-commands -with-fifo <block>`.
We now have `%val{command_fifo}` and `%val{response_fifo}` in Kakoune, and respectively `${kak_command_fifo}` and `${kak_response_fifo}` in the shell.

When we write something to the **command** FIFO, Kakoune executes it.
When we write something to the **response** FIFO, it does nothing special, but Kakoune will wait for finishing the block.

We need `spawn` for writing to the FIFO without blocking.

Here are a few examples of what we could do, assuming we have `a`, `b` and `c` as selections.

``` kak
evaluate-commands -with-fifo %{
  echo -to-file %val{command_fifo} -quoting kakoune -- echo %val{selections}
}

# is the same as:
echo %val{selections}

# or:
'echo' 'a' 'b' 'c'
```

Another example:

``` kak
evaluate-commands -with-fifo %{
  echo -to-file %val{response_fifo} -quoting kakoune -- echo %val{selections}
  # will block forever
}

evaluate-commands -with-fifo %{
  spawn echo -to-file %val{response_fifo} -quoting kakoune -- echo %val{selections}
  # does not block
  ...
  # does block
}

evaluate-commands -with-fifo %{
  spawn echo -to-file %val{response_fifo} -quoting kakoune -- echo %val{selections}
  # does not block
  evaluate-commands %sh{
    cat "$kak_response_fifo"
  }
  # does not block
}

evaluate-commands -with-fifo %{
  spawn echo -to-file %val{response_fifo} -quoting kakoune -- echo %val{selections}
  # does not block
  nop %sh{
    cat "$kak_response_fifo" > "$kak_command_fifo"
  }
  # does not block
}

evaluate-commands -with-fifo %{
  spawn echo -to-file %val{response_fifo} -quoting kakoune -- echo %val{selections}
  # does not block
  evaluate-commands "%%file{%val{response_fifo}}"
  # does not block
}
```

Note in all examples, we are executing `'echo' 'a' 'b' 'c'` as a literal, not `echo %val{selections}`.
