### ISSUE TITLE
Add support for horizontal view manipulations

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#442]
Hi,

It'd be nice to have the same kind of shortcuts `kak` already has for vertical view manipulations (centering, moving the cursor etc), but horizontally.

I often have the cursor on the right hand side of the screen, in the middle of a long line, and I wish there was a way to center the screen horizontally around the cursor so I can see what's off-screen.

**Comment by mawww** [comment]
vm will try to center cursor horizontally, that will not always work however, as the window will try to get as much or the selection visible, so if you have a selection that starts at the begining of the line (or earlier),  the window will try to make the column 0 visible, potentially negating the view command. Not sure what is the best behaviour to have there, trying to expand the view to include as much as possible of the selection is quite handy, like if you select the current block with `<a-a>B` and the start of the block is not visible yet.

**Comment by lenormf** [comment]
The way things work now is good enough, I don't mind the selection having the priority over the cursor.
