### ISSUE TITLE
[REQUEST] please expose current kakoune executable being... executed

### ISSUE THREAD

**Issue by mralusw** [mawww/kakoune#4433]
### Feature

Please expose the current kakoune executable, so that background `%sh{}` scripts can run `"$kak_bin" -p ...`.

In an environment containing multiple `kak` versions (e.g. `/opt/kak-master`, `/usr/bin/kak`, `/opt/kak-v2021.11.08` etc, with symlinks on top of that) it's confusing to tell which `kak` is being executed. Granted, `kak -p` only acts as a client, and probably can send commands just fine, and probably reads the same config files as the session-master; but this is just another uncertainty layer lurking in the back.

Another reason: `kak` may not be in the `$PATH` at all.

**Comment by alexherbo2** [comment]
It could be nice to expose the underlying socket path too, so we won’t need to spawn a process for each `kak -p`.

**Comment by Screwtapello** [comment]
When Kakoune launches a shell-block, it prefixes `$PATH` with a directory that only contains a symlink to the running version of Kakoune:

https://github.com/mawww/kakoune/blob/19e2225153ce988674ea838989158251f1602789/src/shell_manager.cc#L76-L82

That way, scripts that naively invoke `kak` will automatically get the right executable.

**Comment by krobelus** [comment]
> It could be nice to expose the underlying socket path too, so we won’t need to spawn a process for each kak -p.

That's also considered in https://github.com/kak-lsp/kak-lsp/issues/553. Not sure what are reasonable use cases, `kak -p` is usually fast enough.

**Comment by mralusw** [comment]
> When Kakoune launches a shell-block, it prefixes `$PATH` with a directory that only contains a symlink to the running version of Kakoune:

But the binary *has* to be named `kak`? E.g. if I run `/opt/kak-master/bin/kak.debug`, then scripts using `kak -p` would still get `kak`, not `kak.debug`.

**Comment by mralusw** [comment]
> When Kakoune launches a shell-block, it prefixes `$PATH` with a directory that only contains a symlink to the running version of Kakoune:

... or is that a real symlink in a removed tmp dir?

**Comment by Screwtapello** [comment]
When you run `make` in the Kakoune repo, it builds a binary whose name is based on the given compilation options (`kak.opt`, `kak.debug.san_a`, etc.) and then symlinks that binary to `kak`:

https://github.com/mawww/kakoune/blob/master/src/Makefile#L93-L96

Meanwhile, `libexec/kak/kak` is a symlink to the `kak` symlink created above:

https://github.com/mawww/kakoune/tree/master/libexec/kak/kak

If you `make install`, the build system ensures that the binary you built is installed as `bin/kak` in your chosen prefix, and that `libexec/kak/kak` is a symlink to that binary.

You can definitely break this system if you copy the binary to a new location without also copying the libexec directory to the same relative path, but you can also break things by omitting to copy the system kakrc or the standard library plugins or the online documentation, so it's no different in that respect.

**Comment by sidkshatriya** [comment]
> Then I guess the remaining limitation is that the binary has to be named kak

Even if you rename your kak binary to something really custom, you can get around this problem on linux by executing

```bash
"/proc/${kak_session}/exe" -p -s $kak_session
```

The `exe` file is a symlink to the kak binary (whatever it is called) in the `/proc` file system.

**Comment by lenormf** [comment]
What’s your usecase?

**Comment by sidkshatriya** [comment]
Hmm... I thought about this more. Something like 

```
"/proc/${kak_client_pid}/exe" -p $kak_session
```

should always work in linux if have a custom name for your kak executable, even if you have named sessions...

**Comment by mralusw** [comment]
> > Then I guess the remaining limitation is that the binary has to be named kak
> 
> Even if you rename your kak binary to something really custom, you can get around this problem on linux by executing

It's nothing "really custom", it's compiling with gcc/clang (with their versions) and finishing up with install/install-strip. In order to **test** bugs, one needs multiple executables around, being spawned predicatably.

> ```shell
> "/proc/${kak_session}/exe" -p $kak_session
> ```

Yes! But that's Linux-only. Why not expose `$kak_bin`?

**Comment by mralusw** [comment]
> When you run `make` in the Kakoune repo, it builds a binary whose name is based on the given compilation options (`kak.opt`, `kak.debug.san_a`, etc.) and then symlinks that binary to `kak`:

OK. For now, the workaround is to install each `kak` into its own `/opt/kak-v*[.debug][.branch]` or whatever. Don't install multiple executables into `/opt/kak/bin/`.
