### ISSUE TITLE
kakoune cannot build

### ISSUE THREAD

**Issue by LollipopFt** [mawww/kakoune#4461]
### Version of Kakoune

master branch

### Reproducer

git clone, follow steps outlined in README.md until ```make``` command.

### Outcome

make gives this error message:
```
g++  -O3 -pedantic -std=c++2a -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-address -Wno-init-list-lifetime -MD -MP -MF .alias_registry.opt.d -c -o .alias_registry.opt.o alias_registry.cc
In file included from string.hh:6,
                 from alias_registry.hh:5,
                 from alias_registry.cc:1:
units.hh:8:10: fatal error: compare: No such file or directory
    8 | #include <compare>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:104: .alias_registry.opt.o] Error 1
```

### Expectations

no error message, just build.

### Additional information

WSL Distribution of Ubuntu.

**Comment by sidkshatriya** [comment]
What version of gcc are you using? When I use gcc 10.3 I'm able to compile kakoune. 

With older versions you might have a problem.

Try 
`$ sudo apt install gcc-10`

and then make sure that g++ 10 is indeed what is invoked when running make. 

Ubuntu has a concept of a default alternative. Check `update-alternatives --query g++` before running `make` again.

**Comment by LollipopFt** [comment]
oh, you're right, my bad. thanks!

**Comment by losnappas** [comment]
For posterity: can also do `sudo apt install g++-10`, `CXX="g++-10" make` and not have to touch default alternatives
