### ISSUE TITLE
[BUG] Cosmetic modeline inconsistency between normal and insert mode

### ISSUE THREAD

**Issue by arachsys** [mawww/kakoune#4466]
In normal mode, the mode line contains "1 sel" or "n sels (k)" when n > 1, filled out by

  https://github.com/mawww/kakoune/blob/master/src/input_handler.cc#L334

In insert mode, the mode line contains "n sels (k)" unconditionally, even when n == 1, filled out by

  https://github.com/mawww/kakoune/blob/master/src/input_handler.cc#L1446

Moving in and out of insert mode, the mode line therefore flips between "1 sel" and "1 sels (1)" in a slightly jarring way.

It's trivial to fix: locally, I use

``` diff
diff --git a/src/input_handler.cc b/src/input_handler.cc
index fbfadf8..6efd6f6 100644
--- a/src/input_handler.cc
+++ b/src/input_handler.cc
@@ -1443,8 +1443,9 @@ public:
         auto main_index = context().selections().main_index();
         return {AtomList{ { "insert", context().faces()["StatusLineMode"] },
                           { " ", context().faces()["StatusLine"] },
-                          { format( "{} sels ({})", num_sel, main_index + 1),
-                             context().faces()["StatusLineInfo"] } }};
+                          { num_sel == 1 ? format("{} sel", num_sel)
+                              : format("{} sels ({})", num_sel, main_index + 1),
+                            context().faces()["StatusLineInfo"] } }};
     }
 
     KeymapMode keymap_mode() const override { return KeymapMode::Insert; }
```

But just to check, I'm not missing some deliberate reason for this distinction am I?

**Comment by sidkshatriya** [comment]
This change makes sense to me. You should consider sending a pull request!

**Comment by arachsys** [comment]
Will do! Thanks, just wanted to make sure there wasn't some obvious justification that I was missing.
