### ISSUE TITLE
[REQUEST] Background blink

### ISSUE THREAD

**Issue by 0phoff** [mawww/kakoune#4474]
### Feature

Kakoune allows to set a "blink" attribute for the foreground color of a face.
Would it be possible to add a blink to the background color ?

The documentation does not mention what blink does exactly.
While the name is self explanatory about the behavior, It would be nice to clearly state that blink currently only affects the foreground.

### Usecase

I would like to enable a blinking cursor when I am in insert mode.
Currently it changes color, but I actually dislike using too many different colors in my editor... :3

**Comment by Screwtapello** [comment]
When Kakoune turns on "blink" mode, exactly how that appears is up to the terminal emulator, not up to Kakoune. Most terminals will actually hide/show the text, some will just make the background colour brighter (if the background colour can be brightened).

Kakoune could reset the cursor on a timer event, but currently the only Kakoune behaviour that happens on a regular cycle is the "Waiting for shell... (5s)" prompt which counts up seconds until the shell script completes. Everything else is done in response to an event (a key press, a mouse click, a command sent from an external application), or in response to a short timeout after an event (the `NormalIdle` and `InsertIdle` hooks).

It would certainly be possible to write a Kakoune plugin that just does `while true; do sleep 1; echo trigger-user-hook TimerTick | kak -p; done`while Kakoune is running, and then other plugins could hook that tick to do things like blink text, but that might be considered heavyweight.

**Comment by 0phoff** [comment]
Thanks for explaining what it actually does!
I might look into my terminal to see if I can change this behaviour then, and otherwise I will leave my settings as is (ie. inverted colorscheme when in insert mode)
