### ISSUE TITLE
[REQUEST] Swap ; and h in normal mode

### ISSUE THREAD

**Issue by sandeep-datta** [mawww/kakoune#4491]
### Feature

Hi, I'd like to swap the `;` and `h` keys in normal mode.

### Usecase

"Move right" is a more frequently used operation than "reduce selections to their cursor" and since I already have a finger resting over the ";" key I want to assign the "Move right" operation to it. I also do not want to loose the operation previously triggered by ";" hence it makes sense to move it to the now unused "h" key. I also do not want to change how the j, k and l keys work hence I think swapping the keys is the most sensible option for me.

**Comment by SolitudeSF** [comment]
https://github.com/mawww/kakoune/blob/master/doc/pages/mapping.asciidoc

**Comment by sandeep-datta** [comment]
I tried that but I was not able to make it work. It appears these keys cannot be remapped.

**Comment by Screwtapello** [comment]
They can indeed be remapped, but note that `;` is also the statement-terminator character so something like:

    map global normal ; h

...will just give you a "wrong argument count" error: Kakoune sees the command `map global normal` that doesn't make sense on its own.

Instead, you need to escape the `;` key; `:doc mapping` mentions that it's other name is `<semicolon>`. Therefore:

    map global normal <semicolon> h
    map global normal h <semicolon>

...should do what you want.

**Comment by sandeep-datta** [comment]
Thanks, <semicolon> worked for me!
