### ISSUE TITLE
[REQUEST] report error name instead of code when evecve fails in shell manager

### ISSUE THREAD

**Issue by TeddyDD** [mawww/kakoune#4501]
### Feature

Currently, we get information like this in debug buffer:

```
shell stderr: <<<
execve failed: 7
>>>
```
It's enough to figure out what's wrong if you know about `errno` (I didn't) or you can use `strace`. Reporting 

```
shell stderr: <<<
execve failed: E2BIG 7 Argument list too long
>>>
```

would be much better UX tho.

**Comment by Screwtapello** [comment]
Out of curiosity, what platform are you on? I suspect this is unpolished because on Linux this error is mostly theoretical, not something people bump into regularly.

**Comment by TeddyDD** [comment]
x86_64 Linux.

```
getconf -a | grep ARG_MAX
ARG_MAX                            2097152
_POSIX_ARG_MAX                     2097152
```
