### ISSUE TITLE
[BUG] ctrl-[ is not the same as esc

### ISSUE THREAD

**Issue by richyliu** [mawww/kakoune#4518]
### Version of Kakoune

v2021.11.08-59-g9acd4e62

### Reproducer

* Tested with latest release and master
* Open kakoune with `kak`
* Enter insert mode with `i`
* Press `<c-[>` (`ctrl` and `[`)

### Outcome

`<c-[>` does not exit insert mode

### Expectations

I expect `<c-[>` to exit insert mode like Vim.

### Additional information

This issue only happens on iTerm (as opposed to Terminal) on Mac OS 11.6. Somehow Kakoune is able to distinguish between ctrl-[ and esc (when they should be equivalent).

This is not urgent, as it can be fixed with `:map global insert <c-[> <esc>`. However, it is confusing to Vim users switching to Kakoune as it is not documented anywhere (perhaps document it [here](https://github.com/mawww/kakoune/wiki/Migrating-from-Vim)).

**Comment by SolitudeSF** [comment]
its not a bug https://iterm2.com/documentation-csiu.html

**Comment by richyliu** [comment]
That setting is turned off ("Report modifiers using CSI u"). I don't see any other options related to CSI u in iTerm. Is it always on or is there a way to turn it off?

**Comment by richyliu** [comment]
Closing this as this is more of a feature than a bug
