### ISSUE TITLE
[BUG] Regex alternation matching does not match docs nor pcre nor ecmascript

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#4519]
### Version of Kakoune

v2021.11.08

### Reproducer, observed output and expected output

The regex documentation states:
> The | character introduces an alternation, which will either match its
> left-hand side, or its right-hand side (preferring the left-hand side)

However, it sometimes skips the left-hand side as in this example:

```sh
$ echo ' foobar' | kak -f '/foobaz|foo|foobar<ret>~'
 FOOBAR
```

This expected output is ` FOObar` since `foo` is to the left alternative.
That is what pcre-grep matches:

```sh
$ echo ' foobar' | grep -Po 'foobaz|foo|foobar'
foo
```

and node (ecmascript):

```javascript
$ echo 'console.log(" foobar".match(/foobaz|foo|foobar/))' | node
[ 'foo', index: 1, input: ' foobar', groups: undefined ]
```

### Additional information

Kak can also choose the third alternative when the second should be matched:

```sh
$ echo ' foobar' | kak -f '/foobaz|foobar|foo<ret>~'
 FOObar
```

(Should be ` FOOBAR`)

Removing the first alternative makes it match as expected:

```sh
$ echo ' foobar' | kak -f '/foobar|foo<ret>~'
 FOOBAR
$ echo ' foobar' | kak -f '/foo|foobar<ret>~'
 FOObar
```

**Comment by mawww** [comment]
Good catch, tricky one to solve elegantly, it is a bug in the regex VM logic. There is a pretty simple hacky fix but I am trying to see if I can come up with something more satisfying without introducing performance regressions.
