### ISSUE TITLE
Can't map <a-x>, <a-X> in lower_case_only_modes mode

### ISSUE THREAD

**Issue by mralusw** [mawww/kakoune#4521]
Was this intended? I used to be able to

```
  map global goto <a-F> '<esc>: mru-files'
  map global goto <a-f> '<esc>: mru-files<ret>'
```
(just replace `mru-files` with `fail this-works` to test without anything)

Now I get `error: mode only supports lower case mappings`. This nice message appears in f4ff59f8 first.

**Comment by Screwtapello** [comment]
When you say "used to", how long ago was that?

The error message you describe was added (as you mention) in commit f4ff59f on 2022-01-23.

Before that, the "goto" mode was case-sensitive like all other modes, since commit 4afe923 fixing #3976 on 2021-09-14.

Before that, the "goto" mode was silently case-insensitive, where you could add mappings that differ only by case, but upper-case mappings could never be triggered.

**Comment by mralusw** [comment]
I mean latest stable (v2021.11.08).

I don't really care about being able to map `gx` and `gX` to different things; however, as things stand, I can't map `g<a-x>` *at all* as it triggers that nice message. If possible, I'd like to be able to map `g<a-x>` and `g<a-X>` to different things, but it's not that important.

**Comment by mralusw** [comment]
... and I've just checked that commit f4ff59f breaks `g<a-x>` (repro at the top of this issue).

**Comment by Screwtapello** [comment]
Looking at the code modified in f4ff59f:

```cpp
key[0].codepoint().map(iswupper).value_or(true)
```

...we try to grab the codepoint associated with the key (if any), and if it's uppercase, or if there's no codepoint associated with the key, then Kakoune assumes it's a case-sensitive mapping and blocks it.

Apparently, Kakoune believes that a key with modifiers can't have a codepoint, and therefore (by the above logic) it must be case-sensitive and should be blocked.

I definitely think that keys with a Shift modifier should be blocked, but maybe other modifiers are OK? Perhaps Kakoune should strip the Shift modifier and convert the key to lowercase (if possible) while leaving the rest of the modifiers alone... but Kakoune very carefully avoids any knowledge of keyboard layouts, so it wouldn't be easy to block (say) `map global goto '{' blah`.

**Comment by mralusw** [comment]
> or if there's no codepoint associated with the key

Why? This is breaking valuable functionality for absolutely no reason. Why not stick with known uppercases?

**Comment by mralusw** [comment]
If case insensitivity is *that* important, perhaps `kak` should auto-map the `to_lower` (if any) and `to_upper` (if any) of the requested key. This avoids dealing with unknown codepoints, and also removes the `to_lower` operation (potentially expensive) from code that runs *on every keystroke*.

**Comment by mawww** [comment]
This was an unintended bug from my part, fixed, thanks for your report.
