### ISSUE TITLE
[REQUEST] diff-jump should also handle absolute file paths

### ISSUE THREAD

**Issue by stacyharper** [mawww/kakoune#4531]
### Feature

diff-jump should also handle absolute file paths

### Usecase

Sometime you have to diff-jump absolute file paths

**Comment by krobelus** [comment]
Yep; I sent a fix via mail (since this probably needs little discussion)
See https://lists.sr.ht/~krobelus/kakoune/patches/29165#%3C20220207135238.934577-3-aclopte@gmail.com%3E

**Comment by stacyharper** [comment]
> Yep; I sent a fix via mail (since this probably needs little discussion)
> See https://lists.sr.ht/~krobelus/kakoune/patches/29165#%3C20220207135238.934577-3-aclopte@gmail.com%3E

I tested it and it works very well ! Plus knowing the <ret> is bind by default made my day :D
