### ISSUE TITLE
Query: source of the name

### ISSUE THREAD

**Issue by kivikakk** [mawww/kakoune#454]
Not an 'issue' so much as an inquiry; what's the origin of the name, if any? I had a look around and couldn't find anything (except #259; I rather like the abbreviation, as it's similar to the Estonian word 'kakk', for owl!).

**Comment by mawww** [comment]
Hello,

The name comes from New Caledonia, my home country, where it means "A strong blow", could be shouted during a football game to tell a player to hit the ball as hard as possible, or could mean to punch/kick in a fight (always with that 'as hard as possible' notion).

**Comment by kivikakk** [comment]
Hi there! Thank you so much for your response! It's lovely to hear the origin.
