### ISSUE TITLE
[BUG] Failed to build from source on upcoming Fedora 36

### ISSUE THREAD

**Issue by tim77** [mawww/kakoune#4544]
### Version of Kakoune

2021.11.08

### Reproducer

Rebuild Fedora package.

### Outcome

[Full build log](https://kojipkgs.fedoraproject.org//work/tasks/2926/81982926/build.log).

### Expectations

On Fedora 35 compiles fine. GCC 12 regressions?

### Additional information

- GCC: 12.0.1-0.6
- https://gcc.gnu.org/gcc-12/porting_to.html

**Comment by Screwtapello** [comment]
Your "full build log" link leads me to a 404 error.

**Comment by tim77** [comment]
Very weird, should work. Sorry for inconvenience. Attached to GH: [build.log](https://github.com/mawww/kakoune/files/8053149/build.log)

**Comment by Screwtapello** [comment]
There's a bunch of warnings in that log, but it looks like the actual fatal error is:

```
In file included from face.hh:4,
                 from face_registry.hh:4,
                 from scope.hh:5,
                 from buffer.hh:12:
color.hh: In constructor 'constexpr Kakoune::Color::Color(unsigned char, unsigned char, unsigned char, unsigned char)':
color.hh:54:23: error: call to non-'constexpr' function 'void Kakoune::Color::validate_alpha()'
   54 |         validate_alpha();
      |         ~~~~~~~~~~~~~~^~
color.hh:58:10: note: 'void Kakoune::Color::validate_alpha()' declared here
   58 |     void validate_alpha();
      |          ^~~~~~~~~~~~~~
```

...and sure enough, that function is not marked constexpr.

**Comment by Screwtapello** [comment]
Thanks!
