### ISSUE TITLE
[QUESTION] Should the installation instructions teach how to use gcc 10 on Ubuntu?

### ISSUE THREAD

**Issue by hugomg** [mawww/kakoune#4571]
### Question

On Ubuntu 20.04 (current LTS), the default GCC version is not recent enough. To compile Kakoune I had to use 

    CXX=g++-10 make

instead of just

    make

I wonder if we should update the README accordingly.

**Comment by sidkshatriya** [comment]
Given that ubuntu is quite popular, adding a short note to the README might be useful. Try submitting a PR and see if it is accepted?

If you make the instructions a bit more generic the PR has a higher likelihood of being merged.

**Comment by mawww** [comment]
I think this is fixed now
