### ISSUE TITLE
[QUESTION] Profiling performance on network-mounted files

### ISSUE THREAD

**Issue by WojciechP** [mawww/kakoune#4574]
### Question

Hello,

occasionally I see a noticeable delay between me pressing a key and Kakoune acting on it, in all modes. In insert mode what is shown can sometimes be a few words behind what I'm typing. This only happens when editing files that are on a network-mounted filesystem (like NFS, but specific to my company). Editing files on local disk is fast.

I would expect `:w` and `:e` to be slow, because they need I/O which is lagging. Once a file has been loaded into a buffer, however, I would expect the actual editing to be fast.

I tried to pinpoint the issue:

1. I disabled all extra hooks/plugins I could find
2. I am editing a file with an arbitrary filename extension, so that it is not recognized as any particular filetype to reduce the number of active core plugins
3. I enabled logging by `kak -e "set global debug hooks|shell|profile|commands" random.noext`

There is still visible lag, but the `*debug*` buffer has nothing interesting: there is only a few hooks listed there (because I disabled most of the stuff) and they all took 0us.

I compared the experience of three variants: kak-over-network, kak-on-local-disk and vim-over-network, and only kak-over-network is slow sometimes.

The issue does not happen every time, sometimes everything runs smoothly.

What else can I do to find the cause and fix this?

EDIT: All of the above is within tmux on iTerm2, MacOS 12.3.

**Comment by Screwtapello** [comment]
If you launch Kakoune with `kak -n`, it will prevent Kakoune from loading any of its startup configuration, either the standard library plugins or any custom configuration. If Kakoune works smoothly like that, it's got to be (an interaction with) one of the extra plugins.

Do you have the XCode tools for macOS installed? I believe it comes with a tool called Instruments which can give some insight into what a process is doing and what things might be taking longer than normal.

**Comment by WojciechP** [comment]
Thanks for `kak -n`! It is still slow with it sometimes, so that's not a plugin.

I don't have XCode tools but I can get them - let me play around a bit and get back.

**Comment by mawww** [comment]
This could be due to Kakoune checking if the buffer file has changed, which could block on a slow network disk.

I believe we only check for the currently displayed buffer, so if this is correct you should not experience any slowdown on a scratch buffer. You could check by copying your current buffer to a `:edit -scratch` buffer and seeing if you can reproduce slowdowns in it. You can also `set global autoreload no` to disable that behaviour and check if it indeeds remove the slowdowns.

This is controlled by the fs_check_timeout option which is 500ms by default, so you could reduce that issue by raising this option to check every 10s or so.

**Comment by WojciechP** [comment]
I had also switched from iTerm to kitty and I couldn't replicate the problem. Maybe it was just that my network fs was having a bad day, and maybe it was in fact related to rendering with iTerm. Either way the problem is gone; if it reappears, I will take a look at the autoreload settings and at Instruments. Thank you!
