### ISSUE TITLE
Outdated Wiki page on Ambiguous Keys?

### ISSUE THREAD

**Issue by Pound-Hash** [mawww/kakoune#4577]
The page on [Ambiguous Keys](https://github.com/mawww/kakoune/wiki/Ambiguous-Keys) lists mappings, but those mappings don't do what the page says. For example, `Ctrl-H` doesn't `backspace`, `Ctrl-I` doesn't `tab`.

Also, the page isn't listed in the table of contents on the right side of the Wiki.

**Comment by Screwtapello** [comment]
What terminal are you using? Some terminals support a more complex keyboard reporting protocol that Kakoune can use to distinguish `<c-i>` from `<tab>`.

**Comment by Pound-Hash** [comment]
Okay. I'm using Kitty.

**Comment by Screwtapello** [comment]
Yes, Kitty is one of the few terminals that supports the more complex keyboard reporting protocol.

**Comment by Pound-Hash** [comment]
Should I close this issue? Or perhaps I can amend the wiki page to provide a more thorough explanation? But in that case, I don't know which terminals are exceptions to the explanation.

**Comment by krobelus** [comment]
> Or perhaps I can amend the wiki page to provide a more thorough explanation?

That would be great, TIA

> But in that case, I don't know which terminals are exceptions to the explanation.

I think it's "some terminal like Kitty, iterm and foot" should be a good start

**Comment by Pound-Hash** [comment]
Done
