### ISSUE TITLE
[REQUEST] Autosave

### ISSUE THREAD

**Issue by gabriel-del** [mawww/kakoune#4580]
### Feature

Autosave.
Save the file automatically all the time.

**Comment by Screwtapello** [comment]
Could this be done with a `NormalIdle` hook that just calls `:write` ?

**Comment by gabriel-del** [comment]
I don't know, what should I put on the kak.rc?

**Comment by gabriel-del** [comment]
It'worked, thank you a so much @Screwtapello!

I just added the "InsertIdle" line, so it saves everytime, the final code is:

hook global BufCreate /.* %{
hook buffer NormalIdle .* %{ write }
hook buffer InsertIdle .* %{ write }
}

**Comment by occivink** [comment]
I'm just going to mention that these two hooks are _very_ greedy and the file will be written very often. One improvement would be to check the status of the value `modified` and only actually save if it is true. One way to do it would be 
`hook buffer NormalIdle .* %{ try %{ eval %sh{ [ "$kak_modified" = false ] && printf 'fail' } ; write } }`
(and the same for InsertIdle)

**Comment by gabriel-del** [comment]
Thank you for the tip, @occivink .
I tried with this 2 options below, but it didn't work. Do you know what should be modified?
 
hook buffer NormalIdle .* %{
  try %{ eval %sh{ [ "$kak_modified" = false ] && printf 'fail' } ; write }
}

hook global BufCreate /.* %{
hook buffer NormalIdle .* %{
	try %{ eval %sh{ [ "$kak_modified" = false ] && printf 'fail' } ; write }
}

**Comment by occivink** [comment]
That just looks like an imbalance in braces. It should look like
```
hook global BufCreate /.* %{
    hook buffer NormalIdle .* %{
        try %{
            eval %sh{ [ "$kak_modified" = false ] && printf 'fail' }
            write
        }
    }
}
```

**Comment by gabriel-del** [comment]
You was right @occivink, it works now, thank you! 

hook global BufCreate /.* %{
  hook buffer NormalIdle .* %{ try %{ eval %sh{ [ "$kak_modified" = false ] && printf 'fail' } ; write } }
  hook buffer InsertIdle .* %{ try %{ eval %sh{ [ "$kak_modified" = false ] && printf 'fail' } ; write } }
}
