### ISSUE TITLE
[BUG] eval -bufer * should be synchronous

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#4586]
### Version of Kakoune

Kakoune v2021.11.08-135-geae8ea8a

### Reproducer

I use following script to write output into a file. Second echo inside a try block is indicator for external read script that there is no more data coming and that it should stop reading and collect what it got. Unfortunately this script is unreliable because `<<END>>` token can appear in the middle of data while first echo still running. I'm not sure why is that, but this happens only with `-bufer *`.
```
try %{ eval -buffer * %{
    echo -quoting kakoune -to-file %opt{file_out} %val{bufname}
    echo -to-file %opt{file_out} <<END>>
}} catch %{
    echo -to-file %opt{file_err} %val{error}
}
```

### Outcome

`'buf1' 'buf2' <<END>> 'buf3'`

### Expectations

`<<END>>` token should always appear last like:
`'buf1' 'buf2' 'buf3'<<END>>`

**Comment by Screwtapello** [comment]
Huh, I would have expected the output to look like:

```
'buf1'
<<END>>
'buf2'
<<END>>
'buf3'
<<END>>
```

...since the commands passed to `eval -buffer *` should be executed for each buffer.

Something like this should work, perhaps?

```kak
try %{
    eval -buffer * %{
        echo -quoting kakoune -to-file %opt{file_out} %val{bufname}
    }
    echo -to-file %opt{file_out} <<END>>
} catch %{
    echo -to-file %opt{file_err} %val{error}
}
```

**Comment by vbauerster** [comment]
You're right @Screwtapello! I understood that `eval -buffer *` is executing its block for each non debug buffer.
