### ISSUE TITLE
[BUG] FTBFS with anything but GCC 11

### ISSUE THREAD

**Issue by mralusw** [mawww/kakoune#4600]
### Version of Kakoune

master ceaac1c4

### Reproducer

I've tried building the current master with `clang++` 12, 13, and 14 and the (supposedly kosher) `g++ 10.3.0-1ubuntu1~20.04`. They all fail. Only `g++ 11` works. `v2021.11.08` has no such problems.

### Outcome

On LLVM 13 & 14:

```
ranges.cc:30:17: error: no viable constructor or deduction guide for deduction of template arguments of 'Array'
    check_equal(Array{{""_sv, "abc"_sv, ""_sv, "def"_sv, ""_sv}} | flatten(), "abcdef"_sv);
                ^
./constexpr_utils.hh:14:8: note: candidate template ignored: couldn't infer template argument 'T'
struct Array
       ^
./constexpr_utils.hh:14:8: note: candidate function template not viable: requires 0 arguments, but 1 was provided
```

I don't care much for GCC (hard to upgrade on most systems, plus it has other bugs that I'll post separately).

### Expectations

Build

### Additional information

Ubuntu 20.04, Debian 11. LLVM installed from github releases. GCC 11 (the only one that works) built from source.

**Comment by Screwtapello** [comment]
See also #4597.

**Comment by mralusw** [comment]
> See also #4597.

Ah. I assumed that would be a Mac-only report.

**Comment by mawww** [comment]
I believe this is fixed now
