### ISSUE TITLE
[BUG] Cannot Make Install on Ubuntu 20.04

### ISSUE THREAD

**Issue by yudjinn** [mawww/kakoune#4607]
### Version of Kakoune

Newest

### Reproducer

Trying to build from source following the install documentation:
` CXX=g++-10 PREFIX=$HOME/.local make install`

### Outcome

Numerous "no known conversion for argument 4" stemming from:
`  auto [end, errc] = std::to_chars(res.m_data, res.m_data + N, val, format)`

### Expectations

Successful build of kak

### Additional information

Ubuntu 20.04, manually installed g++-10

**Comment by Screwtapello** [comment]
What specific version does `g++-10 --version` report?

**Comment by sidkshatriya** [comment]
_Workaround:_ If you have clang++ and libc++ (the c++ standard library implemented by llvm team instead of GNU team) installed on your local machine:

You can do the following
```bash
$ make clean
$ CXX='clang++ -stdlib=libc++' make
$ make install
```

I used clang++ version 14. It generates a lot of warnings but it compiles fine!

**Comment by Calum-J-I** [comment]
Get the same error on GCC 10.3.0 which builds the most recent release.

GCC 11.2.0 builds fine

[logs](https://gist.githubusercontent.com/Calum-J-I/76236889c96ce257d2e9b27874cf16b9/raw/e392d8ece256c79643cada8053ca00ae38a1a976/kakoune-2021-05-08-56c3ab4ff86798aaf4f79d3d1a92041d05d202d6_ggc@10.3.0)

**Comment by Screwtapello** [comment]
It looks like this code was introduced with commit d2f9bc8d80cef5008d989380a5c3237b027f4613, which landed on 2022-05-05 and [broke all the CI builds](https://github.com/mawww/kakoune/runs/6298252038) in exactly the same way. Does the previous commit (5c6238ef113da8c2844ff9bcfa27c87e3473c150) work?
