### ISSUE TITLE
Improve tmux support

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#461]
Hi,

It'd be nice to have additional features implemented (in an eventual `rc/tmux.kak` maybe ?), such as providing more control over where the pane will be created when the `new` command is used within a tmux session.

Thanks.

**Comment by lenormf** [comment]
In the works #472

**Comment by mawww** [comment]
Done, we now have `tmux-new-{vertical,horizontal,window}`, you can select the default one by changing the `new` alias (yep, thats an alias now). However there is still one problem, that alias is set in the `KakBegin` hook, so after the user kakrc is sourced. You can switch it manually for now, need to be fixed at some point though.

**Comment by lenormf** [comment]
Perfect !
