### ISSUE TITLE
kakoune hangs when using multiple selection on big files

### ISSUE THREAD

**Issue by MoonZ** [mawww/kakoune#462]
I've been using Sublime Text 2 for years, multiple selection and regexes are a big part of my job especially when analyzing log files, extracting datas, manipulating and reformatting them into reports.

I recently discovered kakoune, seems to be very promising. I managed to install it in a Babun environment, but I'm having an issue:
when working on a 20 MB log files (around 90k lines), kakoune hangs when I try to perform a multiple selection:

1°) I select the whole buffer using %
2°) I press s to enter the search mode
3°) I press ^ and that's it, it hangs. I tried waiting for several minutes, no change. Windows shows 25% of CPU consumption for the process but the perf graph per core doesn't show a clear cap:

![image](https://cloud.githubusercontent.com/assets/4658347/10922015/2f6a542a-8279-11e5-9c13-1ef020d01306.png)

I tried with a random letter as the first char as well, same result, it freezes. Under Sublime Text 2, the selection is updated in "real-time", that is under a second.

I've been advised on the dedicated IRC channel to open an issue as you might be interested in that kind of feedback.

If you need any more information, logs files or more infos on the setup, I'd gladly help.

**Comment by mawww** [comment]
Hello,

I am definitely going to investigate that, it seems its really regex related, if you use `%<a-s>` to get one selection per line, it is quite fast here on big files.

**Comment by mawww** [comment]
Should be quite fast now, 20MB files should be comfortable on non debug builds (and workable on debug ones), dont hesitate to signal if you still hit performance problems.

**Comment by MoonZ** [comment]
It is indeed way better,however it's still too slow to be workable. Once in search mode (s), the first character (random alphabetical char) pressed freezes kakoune for ~8 seconds. If I type a short sequence of 4 chars (like 'INFO') without waiting for the selection update, it freezes to ~20 seconds. Pressing Enter to validate adds 4-5 seconds to that. I'm not using a debug build afaik.

**Comment by mawww** [comment]
Hi,

Default compilations options build a debug version, you need to use "make debug=no" to build an optimized version. On big files, you might want to set the incsearch option to false so that the regex is not applied at each keystrokes as well.

I will investigate more on how to fix these performance problems.

**Comment by MoonZ** [comment]
Hi mawww,

I recompiled kakoune with debug=no, set the incsearch to false, and now the feedback is near instant.

Thanks a lot, I'll stay tuned regarding your performance investigations.
