### ISSUE TITLE
[BUG] possibly regression after commit ae001a1f

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#4630]
### Version of Kakoune

Kakoune v2021.11.08-197-gae001a1f

### Reproducer

After commit ae001a1f my `kak-lsp` setup doesn't work as expected and debug buffer is filled with:

### Outcome

```
accepting connection failed: socket read failed: Resource temporarily unavailable
accepting connection failed: socket read failed: Bad file descriptor
```

### Expectations

Before that commit everything worked as expected.

### Additional information

kakoune was compiled with Apple clang version 13.0.0

**Comment by vbauerster** [comment]
it's triggered by completion. Here is part of debug:
```
----
shell:
 (printf %s "
session  = \"${kak_session}\"
buffile  = \"${kak_buffile}\"
filetype = \"${kak_opt_filetype}\"
version  = ${kak_timestamp:-0}
method   = \"textDocument/semanticTokens/full\"
[params]
" | eval "${kak_opt_lsp_cmd} --request") > /dev/null 2>&1 < /dev/null & 
----
shell:

        if [ $kak_opt_lsp_timestamp -eq $kak_timestamp ]; then
            echo "fail"
        fi
    
----
shell:
 (printf %s "
session  = \"${kak_session}\"
buffile  = \"${kak_buffile}\"
filetype = \"${kak_opt_filetype}\"
version  = ${kak_timestamp:-0}
method   = \"textDocument/inlayHint\"
[params]
buf_line_count = ${kak_buf_line_count}
" | eval "${kak_opt_lsp_cmd} --request") > /dev/null 2>&1 < /dev/null & 
----
accepting connection failed: socket read failed: Resource temporarily unavailable
```

**Comment by vbauerster** [comment]
If I revert commit ae001a1f then there are no such messages in debug and kak-lsp works as expected.

**Comment by krobelus** [comment]
inlay hints and semantic tokens are off by default in kak-lsp, can you provide a minimal config to reproduce?

**Comment by vbauerster** [comment]
It's happening with inlay hints and semantic tokens are off as well.
My minimal config:
```
hook global KakEnd .* lsp-exit
hook global WinSetOption filetype=rust %{
    remove-highlighter window/rust
    set-option window lsp_auto_highlight_references true
    set-option window lsp_hover_anchor true
    lsp-enable-window
    lsp-auto-signature-help-enable
    hook -once -always window WinSetOption filetype=.* %{ lsp-disable-window }
}
```

**Comment by vbauerster** [comment]
if it matters my `/bin/sh` is symlinked to `/bin/dash`.

**Comment by krobelus** [comment]
I can consistently reproduce with kak-lsp + rust-analyzer using this config:

```kak
eval %sh{kak-lsp -s $kak_session --kakoune}
# minimize noise
define-command -override lsp-handle-progress -params .. %{}
lsp-enable
```

```shell
$ cargo init repro
$ kak repro/src/main.rs
```

wait a few seconds for rust-analyzer to start up and type `std::` in a new line.
Then the debug buffer has

	accepting connection failed: socket read failed: Invalid argument

The last part ("Invalid argument") is misleading, it's just a stale `errno` value.
`recvmsg` actually succeeds but reads 0 bytes (despite `fd_readable()` succeeding!) which is why we report an error.

**Comment by krobelus** [comment]
This script reproduces  the problem in around 8 seconds on my system:

```shell
script=$(mktemp)

printf %s 'printf %s "
nop ' > $script

dd if=/dev/zero count=220220 2>/dev/null | tr "\0" a >> $script

printf %s '
" |
kak -p session
' >> $script


src/kak -s session -n -e "
	nop %sh{ sh $script >/dev/null 2>&1 </dev/null & }
	buffer *debug*
"

rm -f $script
```

**Comment by shachaf** [comment]
The reason this is failing is that `-p` goes to `run_pipe()` which doesn't make an `EventManager`. So this code in `file.cc`:

```
        else if (errno == EAGAIN and EventManager::has_instance())
            EventManager::instance().handle_next_events(EventMode::Urgent, nullptr, false);
        else
            throw file_access_error(format("fd: {}", fd), strerror(errno));
```

doesn't find an instance, and treats EAGAIN as a fatal error.

The confusing error message ("accepting connection failed: socket read failed: Invalid argument") is another bug, as mentioned above. In `remote.cc`:

```
        int res = recvmsg(sock, &msg, 0);
        if (res <= 0)
            throw disconnected{format("socket read failed: {}", strerror(errno))};
```

recvmsg can return 0 to indicate EOF, in which case errno is not set.
