### ISSUE TITLE
Replace boost with a simpler regex lib 

### ISSUE THREAD

**Issue by charles-l** [mawww/kakoune#464]
Since boost is just being used for regex it might be simpler to just use a simpler lib like SLRE (https://github.com/cesanta/slre). I'd be happy to do a PR if this seems reasonable.

**Comment by somasis** [comment]
IIRC the only reason Boost is even used right now is because not everyone can use the C++11 standard which includes the regex stuff that Kakoune uses.

**Comment by charles-l** [comment]
@somasis yep, that's what I read in the coding guidelines. I think SLRE is just a smaller shim than boost, and once stdc++ is ready for prime time, it'll be simple to remove.

**Comment by ekie** [comment]
actually the guidelines are not precise in that matter anymore since kakoune started to rely on features that are not supported by the c++11 standard. i dont know if slre implements the feature set needed but @mawww mentioned that he is looking for a library that works with arbitrary iterator types.

**Comment by mawww** [comment]
Yep @ekie is right, the plan is still to use the standard C++11 regexes, but there are a few features we use regularly that are not supported: lookbehinds, `\K` and `\h`.

Seems `\h` should be implementable in standard regex by hooking in regex traits, `\K` might be hackable around as well, but lookbehinds are more tricky.

And yeah, we need a regex library that supports either arbitrary iterators, or at least multi pieces subject strings, as we match along multiple lines, but each line is allocated separately.

**Comment by charles-l** [comment]
@mawww ah, OK. I didn't realize lookbehinds were being used.

**Comment by mawww** [comment]
Unfortunately they are, and they are rather usefull, we use them to validate that a delimiter like `"` is preceded by a even number (or no) of `\` when highlighting string regions (as an example). You'll see a lot of `(?<!\\)(\\\\)*"` to match potential closing double quotes.
