### ISSUE TITLE
[BUG][CRASH] set-face global FaceName default,+b,@PrimaryCursor causes crash

### ISSUE THREAD

**Issue by DocSunset** [mawww/kakoune#4647]
### Version of Kakoune

v2021.11.08

### Reproducer

:set-face global WhateverFaceName default,+b,@PrimaryCursor

### Outcome

Kak aborts ("Aborted (core dumped)") due to pointer issues. I have seen "double free or corruption (out)" as well as "free(): invalid pointer".

### Additional information

Linux twarchbook 5.18.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Jun 2022 18:10:56 +0000 x86_64 GNU/Linux

**Comment by DocSunset** [comment]
Not sure the face spec is necessarily valid, but either way...

**Comment by Screwtapello** [comment]
Using the current `breaking-changes` branch (commit 5bd78ba1f), I tried:

    ./src/kak-debug -n -e "set-face global WhateverFaceName default,+b,@PrimaryCursor"

Instead of a crash, I got an error message:

    1:1: 'set-face': invalid face description, expected [<fg>][,<bg>[,<underline>]][+<attr>][@base] or just [base]

If I make a debug build of v2021.11.08 and try the same thing, I get a backtrace:

```
assert failed "m_value >= 0" at units.hh:121
[Debug Infos]
pid: 2833884
callstack:
./src/kak.debug(_ZN7Kakoune9BacktraceC1Ev+0x2b) [0x55af317c2a7d]
./src/kak.debug(_ZN7Kakoune16on_assert_failedEPKc+0x24) [0x55af317c2144]
./src/kak.debug(_ZN7Kakoune19StronglyTypedNumberINS_9ByteCountEiEcvmEv+0x25) [0x55af317c2d5b]
./src/kak.debug(_ZN7KakounepLERNS_6StringENS_10StringViewE+0x49) [0x55af317c2d18]
./src/kak.debug(+0x7c21aa) [0x55af31ac51aa]
./src/kak.debug(+0x7c2d90) [0x55af31ac5d90]
./src/kak.debug(_ZN7Kakoune6formatENS_10StringViewENS_9ArrayViewIKS0_EE+0xd3) [0x55af31ac5280]
./src/kak.debug(_ZN7Kakoune6formatIJRNS_10StringViewEEEENS_6StringES1_DpOT_+0x7f) [0x55af317c2705]
./src/kak.debug(_ZN7Kakoune12str_to_colorENS_10StringViewE+0xdf0) [0x55af3180dca4]
./src/kak.debug(+0x5c0630) [0x55af318c3630]
./src/kak.debug(+0x5c0d9a) [0x55af318c3d9a]
./src/kak.debug(_ZN7Kakoune12FaceRegistry8add_faceENS_10StringViewES1_b+0x2ac) [0x55af318c4ff6]
./src/kak.debug(+0x538297) [0x55af3183b297]
./src/kak.debug(+0x53833e) [0x55af3183b33e]
./src/kak.debug(_ZSt13__invoke_implIvRPFvRKN7Kakoune16ParametersParserERNS0_7ContextERKNS0_12ShellContextEEJS3_S5_S8_EET_St14__invoke_otherOT0_DpOT1_+0x61) [0x55af318883a1]
./src/kak.debug(_ZSt10__invoke_rIvRPFvRKN7Kakoune16ParametersParserERNS0_7ContextERKNS0_12ShellContextEEJS3_S5_S8_EENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESD_E4typeEOSE_DpOSF_+0x67) [0x55af31882034]
```

Since this no longer happens in the latest version, I assume this crash has been fixed since the last release.

**Comment by mawww** [comment]
This indeeds seems fixed on latest master
