### ISSUE TITLE
[QUESTION] how to clear multi selections? `,` is conflict with user mode

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4660]
### Question

> To clear multiple selections, use ,. To keep only the nth selection use n followed by ,, in order to remove a selection, use <a-,>.

When I type `C` to make a multiply selection, I can't cancel it, type `,` will call a user-mode prompt.

**Comment by occivink** [comment]
This behavior was changed very recently, and the `,` and `<space>` keys were swapped. 
Before this change (and likely in the version you're using), the `<space>` key is used to clear multiple selections (and `<a-space>` to remove a selection).
After this change (and in future releases), the `,` (and `<a-,>`) are used.

**Comment by theowenyoung** [comment]
I'm using the latest kakoune now. Now I can clear the multiple selections.
