### ISSUE TITLE
[BUG] `X` select multiple line not works

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4661]
### Version of Kakoune

f3cb2e434004a718d1225cb0d74c694e66a7248b

### Reproducer

```
#!/bin/sh
set -e
rm -rf /tmp/kakoune
git clone https://github.com/mawww/kakoune.git /tmp/kakoune
cd /tmp/kakoune/src
make install debug=no PREFIX=${HOME}/.local
# clean
rm -rf /tmp/kakoune
```

```
kak any.txt
```

### Outcome

There is no line selected.

### Expectations

Select lines.

**Comment by theowenyoung** [comment]
Also, `5x` doesn't work too.

**Comment by sidkshatriya** [comment]
There has been a recent change in behavior of `x`.

Please see https://github.com/mawww/kakoune/commit/ef8a11b3dbefb8a1222974a8c34e15fa006d56e0

**Comment by sidkshatriya** [comment]
But I too I am surprised why (capital) `X` has stopped working.

**Comment by theowenyoung** [comment]
I don't get it, is it expeted? so now how to select multiple lines?

**Comment by gsf** [comment]
Looks like extending lines with `X` was removed here: https://github.com/mawww/kakoune/commit/ef8a11b3dbefb8a1222974a8c34e15fa006d56e0#diff-8748240e7618f4dc3deec7f9d6be10117a716628df4186d86a0e0f09b74e2d6dL2298

**Comment by Screwtapello** [comment]
Yeah, to select multiple lines you can press <kbd>J</kbd> a bunch of times until at least part of each line you want is selected, then <kbd>x</kbd> to "fill out" the selection to the beginning and end of each line.

**Comment by mawww** [comment]
The other way around should work as well: `x` followed by `J` a bunch of times will select full lines.

**Comment by mawww** [comment]
> edit: I think I will survive this change. I understand x + J or K actually IS the more logical and consistent behavior

Sounds good, this change simplifies the editing model so I think we can close that issue now.
