### ISSUE TITLE
Buffer improperly redrawn in a client

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#469]
Hi,

This issue does not occur in a tmux session:
* open a fresh kak session
* create a new client with `:new`
* open a man page (e.g. `:man 2 stat`)
* search for a word (e.g. `stat`) and hold down the `n` key

The buffer is improperly redrawn (massive black lines inserted everywhich way, scroll down improperly rendered).

33253a8

**Comment by mawww** [comment]
Thats actually either a ncurses bug, or a vte one, the scroll region gets desynchronized between the 2, with the terminal still having the pre resize one, and ncurses assuming the post resize one. Problably a vte one, as other terminals work correctly.

**Comment by mawww** [comment]
Was it with sakura ? or another terminal ? which vte version ?

**Comment by lenormf** [comment]
The terminal is termite with vte3 0.42.1.

**Comment by mawww** [comment]
Can you check if that commit fixes the problem for you ?

**Comment by lenormf** [comment]
Nope :/

**Comment by mawww** [comment]
How about now ? cannot reproduce here with Sakura anymore.

**Comment by lenormf** [comment]
That seems to have done it :) Gj.
