### ISSUE TITLE
[BUG] x and X are broken somewher after 167929c1  

### ISSUE THREAD

**Issue by altunyurt** [mawww/kakoune#4691]
### Version of Kakoune

v2021.11.08-318-g08f5bc39

### Reproducer

Today I've updated to 08f5bc39 from 167929c1 and apparently x and X are broken somewhere in between. 

### Outcome

Hitting x in normal mode multiple times does not move onto next line selecting it, as it did before. Instead it stays on the same line, keeping the line selected. 

Hitting X in normal mode does not select the line, nor it  extends the selection to next line on when pressed multiple times.  

### Expectations

x would select the line and multiple hits would move the cursor onto next line, selecting it. 

X would select current line,  and multiple hits would extend the selection to following lines.

**Comment by krobelus** [comment]
This is expected; `git log --grep='\bx\b' points to ef8a11b3dbefb8a1222974a8c34e15fa006d56e0
You can use xJJJ.

**Comment by caksoylar** [comment]
Also see the [CHANGELOG](https://github.com/mawww/kakoune/blob/master/doc/pages/changelog.asciidoc#development-version), which is by default displayed when you open `kak` without an argument.

**Comment by altunyurt** [comment]
Ah yes, totally missed the changelog. Thanks.
