### ISSUE TITLE
[QUESTION] State of the buffer when multiple hooks modify buffer at the same character insert.

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#4705]
### Question

I have two hooks working at the same character `c` insert. They are executed in the same order in which they are registered. Lets call them hook `A` and hook `B`. Lets also assume, that buffer is in `state0` before inserting the character `c`. I wonder what is the input state for hook B. Is it `state0` or `stateA` (state after executing hook `A`)?. From what I observe it looks like both hooks have `state0` as the input state. If this is true, is there any way to feed hook `B` with buffer `stateA`? If this is not true, then probably I have some bug in my hooks that I still haven't found.

Btw. Is it possbile to dump the buffer to the `debug` buffer before and after particular hook execution?

**Comment by Screwtapello** [comment]
I think the second hook sees the results of the first hook. Consider this test-case:

    kak -n -e 'hook global InsertKey c %{ exec 1 }; hook global InsertKey c %{ exec <esc>xs1<ret>r2 }'

1. when the user hits `c`, the first hook inserts an additional `1` character
2. when the user hits `c`, the second hook selects all `1`s on the current line and replaces them with `2`s

When I execute the above command then press `oc` to trigger the hooks, I get the output:

    c2

...that is, the first hook added a `1` then the second hook converted it to a `2`.

> Is it possbile to dump the buffer to the `*debug*` buffer before and after particular hook execution?

I don't think there's an automated feature for it, but you could always do some kind of `exec -draft '%s: echo -debug Current Buffer: %val{selection}<ret>'` to log the buffer contents yourself.

**Comment by m-kru** [comment]
Ok, I have found the bug in my hook. Thanks!
