### ISSUE TITLE
[BUG] Behaviour of keysym `KP_Add` differs from `plus`

### ISSUE THREAD

**Issue by HermannDppes** [mawww/kakoune#4718]
### Version of Kakoune

```
$ kak -version
Kakoune unknown
$ apt show kakoune
Package: kakoune
Version: 2019.07.01-1build1
[…]
```

### Reproducer

Open Kakoune, go into insert or normal mode or to the command prompt and press `+` on the numpad (or any other combination of keys that sends the same “keysym 0xffab, KP_Add”).

### Outcome

In normal mode, it inserts a blank line above the current selection and then moves the cursor one position higher as if pressing `k`. In insert mode or the command prompt, it inserts the letter `k` just as if the key `k` had been pressed.

### Expectations

The same things that happen when the “keysym 0x2b, plus” is entered, e.g. inserting a `+` in insert mode.

### Additional information

I'm running the Kakoune version from the Linux Mint package manager. (I'd try running master, but that same package manager does not yet have sufficiently current versions of GCC and clang, it seems.)

I did mostly test this in Gnome-Terminal but have confirmed that at least some of the unexpected behaviour reproduces in XTerm.

**Comment by Screwtapello** [comment]
Cannot reproduce in the current development version of Kakoune.

The traditional terminal encoding for the keypad <key>+</key> is `^[Ok`, which could look like "leave insert mode, open a new line above, type `k`" or "press `<a-o>`, then `k`" in programs that don't properly support it. Kakoune does support it (now) though:

https://github.com/mawww/kakoune/blob/master/src/terminal_ui.cc#L928

**Comment by HermannDppes** [comment]
Hmm, this was introduced in the commit f78adeda4 in the file `src/ncurses_ui.cc`. When I build this version of the app, I have *different* ~~unexpected~~ behaviour. Somewhat more recently, I can still build v2021.11.08 and then KP_Add seems to behave fine in insert mode and prompts, but in normal mode it seems to double up the selections in place. But the same happens for plus, ~~so it is indeed a different bug than the one in the originally reported version.~~

~~(If it is a bug at all. I'm still entertaining the idea that this is a feature for which I have yet to find the documentation.)~~

Okay, `:doc keys` has this behaviour documented. (=
