### ISSUE TITLE
[QUESTION] How to list all clients of a session?

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4726]
### Question

I can list all sessions by `kak -l`, but how to list all clients of a session?

maybe like `kak -c session-name -l`?

I use this to check if there are some clients, if not, I will open a new tmux split window to run kak client.

**Comment by Screwtapello** [comment]
The list of clients is available as `%val{client_list}` once you're connected to a session, but right now there's no easy way to get that information back out (see #2118 for a description and workaround).
