### ISSUE TITLE
[QUESTION] How to delete all buffer?

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4727]
### Question

in VSCode, I can close all tabs, or close other tabs, or close right tabs.

How to do this in Kakoune?

I tried: `delete-buffer! *`

it didn't work.

also, I tried to delete two buffers at once: `delete-buffer! a.md b.md`, witch also didn't work.

**Comment by Screwtapello** [comment]
The `:delete-buffer!` command only deletes a single buffer. The way to run a command for multiple buffers is with `eval -buffer *`:

    evaluate-commands -buffer * %{ delete-buffer! }

Note that `*` here is a keyword, not a pattern, so you can't delete just some buffers; it's one specific buffer or all of them. This behaviour is described in `:doc execeval`.

**Comment by krobelus** [comment]
I use this to delete buffers matching a regex:

```kak
define-command delete-buffers-matching -params 1..2 %{
	evaluate-commands %sh{
		cmd=delete-buffer
		if [ "$1" = -f ]; then {
			cmd=delete-buffer!
			shift
		} fi
		buffers_escaped=$(eval printf '%s\\n' "$kak_quoted_buflist" | grep "$@" | sed "s/'/''/g")
		if [ -z "$buffers_escaped" ]; then {
			echo fail no matching buffer
		} else {
			nl=$(printf '\n.')
			IFS=${nl%.}
			printf '%s\n' "$buffers_escaped" |
			while read bufname
			do {
				printf "$cmd '%s'\n" "$bufname"
			}; done
		} fi
	}
}
```
