### ISSUE TITLE
Linting warning and error messages unaffected by a change in their faces

### ISSUE THREAD

**Issue by ghost** [mawww/kakoune#4729]
### Question

To make it easier to distinguish which kakoune window is active I'm using configuration I've adapted from https://github.com/greenfork/active-window.kak:

```kakscript
# from kakrc:

# UI
set-face global LineNumbers bright-black,default
set-face global LineNumbersWrapped bright-black,default
set-face global PrimaryCursor black,yellow
set-face global SecondaryCursor black,bright-black
set-face global PrimaryCursorEol black,bright-cyan
set-face global SecondaryCursorEol black,cyan
set-face global PrimarySelection bright-white,blue
set-face global SecondarySelection black,blue
set-face global Information black,yellow
set-face global Error black,red

# Dim ui when kakoune is not active
###########################################

set-face global InactiveHighlight white,bright-black

hook global WinDisplay .* %{
  set-face window PrimaryCursor PrimaryCursor
  set-face window PrimaryCursorEol PrimaryCursorEol
  set-face window SecondaryCursor SecondaryCursor
  set-face window SecondaryCursorEol SecondaryCursorEol
  set-face window LineNumberCursor LineNumberCursor
  set-face window PrimarySelection PrimarySelection
  set-face window SecondarySelection SecondarySelection
  set-face window Information Information
  set-face window Error Error
}

hook global FocusIn .* %{
  set-face window PrimaryCursor PrimaryCursor
  set-face window PrimaryCursorEol PrimaryCursorEol
  set-face window SecondaryCursor SecondaryCursor
  set-face window SecondaryCursorEol SecondaryCursorEol
  set-face window LineNumberCursor LineNumberCursor
  set-face window PrimarySelection PrimarySelection
  set-face window SecondarySelection SecondarySelection
  set-face window Information Information
  set-face window Error Error
}

hook global FocusOut .* %{
  set-face window PrimaryCursor InactiveHighlight
  set-face window PrimaryCursorEol InactiveHighlight
  set-face window SecondaryCursor InactiveHighlight
  set-face window SecondaryCursorEol InactiveHighlight
  set-face window LineNumberCursor InactiveHighlight
  set-face window PrimarySelection InactiveHighlight
  set-face window SecondarySelection InactiveHighlight
  set-face window Information InactiveHighlight
  set-face window Error InactiveHighlight
}
```

It works quite well and results in the following ui:

![image](https://user-images.githubusercontent.com/7355199/189477814-45b6448d-0d77-4064-a788-33d571d26e42.png)

So as you can see, the bottom right window is focused, and it's quite clear that it is. However, I'm not able to get it to work for lint diagnostics for some reason:

![image](https://user-images.githubusercontent.com/7355199/189477907-7e75790b-0857-4a6b-a83f-9a3e512cba4e.png)

In this screenshot the bottom right window has focus again, and the selections are dimmed as expected. But the lint error and warning in the statusline are not using the inactivehighlight.

At first I thought I was using the wrong face, but Information and Error do seem to be the right ones: https://github.com/mawww/kakoune/blob/master/rc/tools/lint.kak#L322. Also, setting Information and Error to something else initially, say black,green, does change their appearance as expected. It's just that that colors don't respond when I change them in the FocusOut hook. Why is that? Can I make this work somehow?

It does work as expected for the user menu for example:

![image](https://user-images.githubusercontent.com/7355199/189478087-a81e6c3b-73bf-4472-ab3f-daf392b2523c.png)

which also uses the Information face, so I'm confused as to why it's not affecting the lint warning face, which also uses Information.

**Comment by Screwtapello** [comment]
I don't immediately know why this would be, but this pattern looks weird to me:

    set-face window PrimaryCursor PrimaryCursor

I would expect this to have no effect at all. If you change this to:

    unset-face window PrimaryCursor

...does that behave any differently?
