### ISSUE TITLE
Closed server instances don't recover the names of the previously named clients

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#473]
Hi,

Usecase:
* start kak, create a new client with `:new`
* name the new client something (I use `:nameclient make-client` because my `toolsclient` variable is set to "make-client")
* quit the first instance of kak (the server)
* start kak again, and use a command that should be using the previously named client (in my case, `:make` should be printing output to the second client, but doesn't)

I reckon it is not quite possible to have done with the current implementation, is it ?

**Comment by mawww** [comment]
When you start kak again, if you dont specify '-c <session>', you are in a separate session, so there is no way for that kakoune instance to interact with the client from another session.

**Comment by lenormf** [comment]
Good.
