### ISSUE TITLE
[BUG] Alacritty terminal alt+i didn't work

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4730]
### Version of Kakoune

v2021.11.08-364-g021da117

### Reproducer

Open any text file:

move to some paragraph

`<a-i>`

`p`

### Outcome

there is no effect, not only `p`, all `<a-i>` keys not work.

 I tried `a-a`, and it works fine.

### Expectations

selecting the whole paragraph.

### Additional information

OS: macOS

I don't know if I miss something, but it's a basic function, I wonder maybe I'm wrong with something...

**Comment by Screwtapello** [comment]
Have you set up Option to be used as Alt instead of the default type-accented-letters behaviour, as [described in the wiki](https://github.com/mawww/kakoune/wiki/macOS-tips#alt-key)?

**Comment by theowenyoung** [comment]
Yes, alt-i can trigger a prompt, but when I press any keys, it's like kakoune just treat them as normal mode instead text object.

alt-a works fine.

**Comment by Screwtapello** [comment]
If I just run `cat` directly inside a terminal, and then press `<a-i>p`, it produces the text:

    ^[ip

Is that also what your terminal produces? What terminal are you using?

**Comment by theowenyoung** [comment]
```bash
^[iˆp
```

**Comment by Screwtapello** [comment]
Apparently your terminal is configured so that pressing `<a-i>` sends `ESC i` *and then* the circumflex that Option-I normally produces on macOS, rather than `ESC i` *instead of* the circumflex. Kakoune doesn't have a mapping for `ˆ` in "select inner object" mode, so it takes you back to normal mode, and then `p` does the normal paste operation.

I'm afraid I don't know enough about Alacritty to guess how to configure it to work properly with Kakoune.

**Comment by theowenyoung** [comment]
Thanks @Screwtapello 

Now I confirmed it's an alacritty behavior. it seems that they didn't solve it yet. I guess I must change my terminal now. 

Related issues:

https://github.com/alacritty/alacritty/issues/2017

https://github.com/rust-windowing/winit/issues/768

https://github.com/mawww/kakoune/issues/2694

**Comment by jpe90** [comment]
Just FYI,  I have this working on macOS with the following relevant config lines:

```
alt_send_esc: true
```
```
key_bindings:
  - { key: I,         mods: Alt,       chars: "\x1bi"                       }
```
