### ISSUE TITLE
[QUESTION]  How to select surrounded word by current cursor?

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4732]
### Question

I want to select the current surrounding word, like `w`.

For example, if I have a text `smart-select`, and the cursor points `m`, I want to select `smart`

I tried `<a-i>w`,  it will select `smat-select`

**Comment by Screwtapello** [comment]
I start `kak -n`, type `smart-select`, and put the cursor on `m`:

!["smart-select", with the m selected](https://user-images.githubusercontent.com/1450918/189616695-1c074146-d0a1-4656-8ca7-96cf3901e793.png)

I type `<a-i>w`, and get:

!["smart-select", with "smart" selected](https://user-images.githubusercontent.com/1450918/189616786-9d3a7606-d837-40b0-89d4-5ad19cd95069.png)

If instead I type `<a-i>W` then I get:

!["smart-select", fully selected](https://user-images.githubusercontent.com/1450918/189616907-912ea092-20d9-47ff-ae14-574a3510ee54.png)

**Comment by Delapouite** [comment]
Some languages have the dash char `-`  added to to the `extra_word_chars` option. This could explain the observed behavior.
