### ISSUE TITLE
[QUESTION] How to select the column range of the current line?

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4733]
### Question

How to select the column range of the current line?

For example, if I have the text:

```bash
hello world
```
my cursor is pointed to any position of hello world line.

I want to choose `world`, which is  `6-end`,

what is the keys?

**Comment by Screwtapello** [comment]
If you want to select a range of columns in the current line, the most straight-forward approach might be something like:

    gh6lGl

That is, go all the way to the beginning of the line, move right 6 times to `w`, then select to the end of the line.

If you have line and column numbers, however, you might find it easier to use the `:select` command to just directly select particular ranges.

**Comment by theowenyoung** [comment]
Thank you! Nice way.
