### ISSUE TITLE
[QUESTION] How to know if the current buffer content is empty?

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4734]
### Question

Hi, How to know if the current buffer content is empty?

I tried: 

```bash
eval %sh{ test "$kak_selection" = "" && echo "echo empty" }
```

```bash
eval %sh{ test "$kak_selection" = " " && echo "echo empty" }
```

```bash
eval %sh{ test "$kak_selection" = " \n" && echo "echo empty" }
```

All of these do not work, how can I check if the buffer is empty? T'hanks!

**Comment by Screwtapello** [comment]
A buffer can never be completely empty, it must always contain at least one line, which means it must always contain at least one newline character. Therefore, if a buffer contains at least *two* characters, it's not empty.

```kak
try %{
    exec -draft '/..<ret>'
    echo "not empty"
} catch %{
    echo "empty"
}
```
