### ISSUE TITLE
[QUESTION] How to always lock a `user-mode` when I'm in a buffer 

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4735]
### Question

When I in some special buffer, like `grep` buffer, I want to enter a user mode, that is always there, no matter any keys, except `<esc>`

I tried `enter-user-mode -lock xxx`, but when I press some key that I don't map in this user mode, for example, `j`,  it'll quit.

```bash
declare-user-mode buffer-switcher-menu
map global buffer-switcher-menu <ret> ': buffer-switcher-switch<ret>' -docstring "open buffer"
map global buffer-switcher-menu <d> ': buffer-switcher-delete<ret>' -docstring "delete current line or selection buffer"
map global buffer-switcher-menu <D> ': buffer-switcher-delete-force<ret>' -docstring "force delete current line or selection buffer"
map global buffer-switcher-menu <q> ': delete-buffer *buffer-switcher*<ret>' -docstring "back"
map global buffer-switcher-menu <x> ': evaluate-commands -buffer * %{ delete-buffer }' -docstring "delete all buffers"
map global buffer-switcher-menu <X> ': evaluate-commands -buffer * %{ delete-buffer! }' -docstring "force delete all buffers"
```

Context:

I'm trying to develop a buffer plugin, like `grep` plugin or [buffer-switcher-plugin](https://github.com/occivink/kakoune-buffer-switcher), when the user enters this buffer manager buffer, I want to keep the user mode there, so I can listen to user's operators.

<img width="1276" alt="Screen Shot 2022-09-14 at 00 01 42" src="https://user-images.githubusercontent.com/62473795/189950773-945b4d7f-6f8a-4789-9429-60f19f59001d.png">

Another way I thought is to map normal mode, and show `info <help-info>` box there, like:

```bash
map global normal <d> ': buffer-switcher-delete<ret>' -docstring "delete current line or selection buffer"
map global normal <?> ': buffer-switcher-show-help<ret>' -docstring "show help info"
```
if the user wants to know help info, they can press `?`, this is maybe a better experience.

**Comment by Screwtapello** [comment]
An even better experience might be to put the menu text in a comment at the top of the buffer. If you make sure all the lines containing buffer names have a special prefix (like `> ` or `-` or something) then you can treat lines beginning with `#` as comments, and maybe add other prefixes to indicate things like `%val{modified}`.

**Comment by theowenyoung** [comment]
Thanks, I will use `>`, and `+` as prefixes to distinguish which buffer is modified or current buffer
