### ISSUE TITLE
[QUESTION] How to add sorround double quotes for selection?

### ISSUE THREAD

**Issue by theowenyoung** [mawww/kakoune#4736]
### Question

Hi,

when I select `hello` string, I want to add double quotes(or other pairs, like parentheses) for this selection, how to do it in kakoune?

**Comment by Delapouite** [comment]
Hi.

Have a look at this plugin for inspiration about surrounding stuffs https://github.com/Delapouite/kakoune-mirror
Other cool ones are listed at the bottom of the readme.

**Comment by Screwtapello** [comment]
Try `i"<esc>a"<esc>`

You seem to have a lot of questions about Kakoune, you might get more and better responses on [the IRC channel](https://web.libera.chat/?channels=#kakoune), on [the official forums](https://discuss.kakoune.com/) or [the unofficial Discord](https://discord.gg/uzZZG2X).

**Comment by theowenyoung** [comment]
Thanks, guys. I'm new to kakoune, it's my first week using it, and I don't have any vim experiences before, so I may have some questions, I'd like use forums or issues to submit questions, cause it may help other people. If the question is too simple, I'll ask it on IRC or Discord, thanks very much!
