### ISSUE TITLE
[QUESTION] Recommended approach for multiple formatters for a single filetype

### ISSUE THREAD

**Issue by ismay** [mawww/kakoune#4739]
### Question

I couldn't find this in the docs or existing issues. I'm wondering what the recommendations are when you want to have multiple formatters for a single filetype. For css for example: https://github.com/mawww/kakoune/wiki/Format#css. There's prettier and stylelint. Let's say I'd like them both to be available as formatting commands so I can run either on demand on a css file. Is that possible, and if so, what is the recommended approach?

**Comment by Screwtapello** [comment]
As described on that wiki page, you can set which program to use for formatting a buffer by setting the `formatcmd` option. The given example hooks fire when the `filetype` option is set for a buffer, but you can make the logic as complicated as you like — check the absolute file path so you can use different tools for different projects, check a config file in the current directory, call a REST API, whatever you can do in a shell script.

**Comment by Screwtapello** [comment]
> What I mean is, it seems like you can have only one formatcmd per filetype, right?

Not at all.

```kak
hook global BufSetOption filetype=css %{
    set-option buffer formatcmd %sh{
        case "$kak_buffile" in
            # Work projects demand CSS is formatted with `prettier`
            */projects/work/*)
                 printf '%s' 'prettier --stdin-filepath=%val{buffile}'
                 ;;
            # For everything else, I prefer stylelint
            *)
                printf '%s' 'npx stylelint --fix --stdin-filename=%val{buffile}'
                ;;
        esac
    }
}
```

That example switches between formatters based on the absolute path of the buffer, but like I said, you can decide based on any logic you can put into a shell script. You can even set `formatcmd` yourself interactively, or write your own commands that set it before calling `:format`, anything you like.
