### ISSUE TITLE
Make each client maintain its own buffer history

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#474]
Hi,

There are situations where using `ga` opens up an unwanted buffer that was opened in a different client, e.g. when using `ga` in a regular buffer after using `:make` (or `:man`, `:grep` etc) brings up the output of the `make` command again. This behaviour is undesirable because when a client is named after the `toolsclient` variable, the user expect the output of the `make` command to remain in its own client.

Thanks.

**Comment by ekie** [comment]
#266
