### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#4775]
### Question

I might be wrong here but I think that 69053d96239e5ef1f97522949d8c712fa5846eab actually does the opposite of what was intended.  And rather than saving a tab tap, I ended up having to use another tab tap. 

Although I found the idea behind it nice,  it's problematic 

Let me post a screenshot. Visually speaking, and since there's highlighting involved with the editor,I think I'm better off by explaining it like this. 

If one were to look at the the first screenshot , I was just trying to change to the directory  `Downloads` which in turn has a subdirectory named `lcdf-typetools` 

![Screenshot_2022-11-08_02-52-17](https://user-images.githubusercontent.com/11535575/200511116-767703a1-8c9b-4506-adaf-70ec39c5481c.png)

Now, normally speaking, or the way I was taught to change to a directory was by not having to press another key 

and when I said it's a misleading behavior, it is really. 

Once the `enter` key is pressed, I expected it to show me the files inside  the `lcdf-typetools` directory but not the files inside the subdirectory `autom4te.cache`  that happens to be the highlighted subdirectory 

![Screenshot_2022-11-08_03-10-19](https://user-images.githubusercontent.com/11535575/200512683-7081162c-af4c-42b5-b0ad-262613780628.png)

I reverted the line 2555 (I think) from commands.cc and it behaved as I was expecting it. But I don't know if it would be more rational to just correct it  rather than removing a line.

cc: @krobelus

**Comment by krobelus** [comment]
This is intentional but I can see how this is surprising at first.

The upside is that this change enables `cd Downloads/lcdf<ret>` (or `cd Dow<tab>lcdf<ret>`), saving a tab.

To get the behavior in your screenshot you literally need to type `cd Downloads/lcdf-typetools/`.
If you don't type the trailing slash, it will work fine.
Is there any reason why you added the slash?
I know that tab completion adds a slash but following completions will only descend into the directory if you don't accept the literal completion.
I guess you typed something like `cd Downloads/lcdf<tab>a<backspace>` to get to this state?

**Comment by krobelus** [comment]
there is an argument to to including `Downloads/` in the completion list if the token is exactly that but I'm not sure.

> I was just trying to change to the directory Downloads which in turn has a subdirectory named lcdf-typetools

It's not clear to me which directory you are going for / what you typed exactly

**Comment by nonumeros** [comment]
> there is an argument to to including `Downloads/` in the completion list if the token is exactly that but I'm not sure.
> 
> > I was just trying to change to the directory Downloads which in turn has a subdirectory named lcdf-typetools
> 
> It's not clear to me which directory you are going for / what you typed exactly

@krobelus  sorry for the noise.

when I checked this thoroughly (by thoroughly I mean, a few hours ago), I even went as far as looking for the "bad" commit and "good" commit .  

at one point I was opening kak directly from the `src` dir, while other times I chose to install it on the system, so I could further verify whether in fact I was just doing an extremely dumb operation, (not the first time), or that kak had simply outsmarted me altogether. 

At one point, while editing a file that resided on another directory but calling out kak from within the `src` directory, ended up with executable files written inside that kak `src` directory.  No good. Thank goodness that these files had an easy-to-remember-filename or else I would still be searching for them. My first reaction was that of an absolute-relative path dilemma. But I was wrong. Let me explain, and check this out. This is actually trying to see where different kak versions differed. 

```
--- a/src/commands.cc
+++ b/src/commands.cc
@@ -2555,7 +2555,8 @@ const CommandDesc change_directory_cmd = {
              return { 0_byte, cursor_pos,
                       complete_filename(prefix,
                                         context.options()["ignored_files"].get<Regex>(),
-                                        cursor_pos, FilenameFlags::OnlyDirectories) };
+                                        cursor_pos, FilenameFlags::OnlyDirectories),
+                      Completions::Flags::Menu };
         }),
     [](const ParametersParser& parser, Context&, const ShellContext&)
```

By looking at the `Completions::Flags::Menu ` I myself wondered how was it, that such a change had created havoc 

It wasn't a spur of the moment reaction to what I had found, but rather a set of frustrating keystrokes trying to keep up with these modifications. 

```
git bisect bad 0b5dcf062fd9af87428d599d26acad2dcecb3d30
# good: [a1715a0c4151884a2e12f78d10f4c4820902f1e3] Use menu behavior when completing scope arguments
git bisect good a1715a0c4151884a2e12f78d10f4c4820902f1e3
# bad: [69053d96239e5ef1f97522949d8c712fa5846eab] Use menu behavior when completing change-directory
git bisect bad 69053d96239e5ef1f97522949d8c712fa5846eab
# first bad commit: [69053d96239e5ef1f97522949d8c712fa5846eab] Use menu behavior when completing change-directory
```

Now. Unlike before, that is… a few hours ago when I opened the issue, and  After installing different kak revisions (versions) on the system, it seems as if I can't reproduce it. Any of it. Like. Gone. Magically. 

But  all versions (revisions) seem to be working now, as long as all revisions are installed on the system. 
Lo and behold if kak were called out from withing the `src` directory,

Look at this screenshot. I didn't type a slash, but rather I was merely completing the `cd ` operation with the `tab` key

Look at that screenshot for me. What am I supposed to do from there?

Perhaps enter the `tab` key again, or perhaps no? If the former, it will certainly send me (highlight the pop-up menu with the different choices of these subdirectories or highlight the list of subdirectories with the completion accordingly, right). If, on the other hand, the latter, that is, by pressing the `enter` key, it'll surely open up a subdirectory for which I had no intention to edit the files within it. 



![Screenshot_2022-11-08_18-24-07](https://user-images.githubusercontent.com/11535575/200698437-06e848e5-67de-481d-a9dd-a57f0cc3b271.png)

**Comment by nonumeros** [comment]
@krobelus  allow me please to show another screenshot .

Look at this one, which is calling out kak from within the `src` directory. 

It's clear that the choices are straightforward in this example. 

If I were to press the `enter` key, it would `cd` to the directory that shows on the kak menu bar and not from whatever  it's highlighted by the completion menu. If on the other hand I was to press the `tab` key again, it would simply scroll down to the list of choices of all subdirectories from that completion menu. 

![Screenshot_2022-11-08_19-10-26](https://user-images.githubusercontent.com/11535575/200704807-daf2bf96-859d-490a-8faa-c9350137e96f.png)

**Comment by Screwtapello** [comment]
Rather than `<tab>` or `<ret>` I think you're supposed to hit `<backspace>`.

Let's say I have the following directory structure:

    mkdir -p /tmp/aaaaaaaaaa/1
    mkdir -p /tmp/aaaaaaaaaa/2

Inside Kakoune, if I type:

    :cd /tmp/aa<tab>

...then it completes to:

    :cd /tmp/aaaaaaaaaa/

...but the completion menu is *items in `/tmp`*, not `1` and `2`, so I can hit `<ret>` to change into that directory. If, instead of typing `<ret>` I type `x`:

    :cd /tmp/aaaaaaaaaa/x

Now I get no completions because there's no subdirectories containing "x". Now if I type `<backspace>`:

    :cd /tmp/aaaaaaaaaa/

This is the same command-line as before, but now the completions are the subdirectories `1/` and `2/`, so if I hit `<ret>` then it'll take me into `/tmp/aaaaaaaaaa/1`. In order to change into the directory I want, I have to hit `<backspace>` one more time:

    :cd /tmp/aaaaaaaaaa

Now the highlighted item in the completion menu is `/tmp/aaaaaaaaaa/` so if I hit `<ret>` I'll be in the place I wanted.
