### ISSUE TITLE
[BUG] Keep pressing plus (+) and memory keeps increasing without limit

### ISSUE THREAD

**Issue by lobre** [mawww/kakoune#4802]
### Version of Kakoune

20221031

### Reproducer

Just keep pressing `+` for a few seconds. 

### Outcome

The memory will keep increasing and the editor (and the system) will freeze rapidly. See also the number of selections reported in the status line.

![image](https://user-images.githubusercontent.com/3764103/205321840-1da08a1c-e08d-4823-b227-ebb69cb19aae.png)

### Expectations

I know this key duplicates the selection, so I guess it allocates memory to do this. But maybe we should have a limit to avoid being in that situation.

**Comment by vbauerster** [comment]
Duplicate of https://github.com/mawww/kakoune/issues/4533

**Comment by lobre** [comment]
How could I miss this issue, it even has pretty much the same title as mine? Anyway, sorry, closing.
