### ISSUE TITLE
Wrong mimetype

### ISSUE THREAD

**Issue by antoyo** [mawww/kakoune#481]
Hello.
When I open a rust file (`main.rs`), I get the C syntax highlighting.
I can get the rust one by setting the `filetype` option, but it should not be necessary.
I found one that the `file` command returns `text/x-c` for rust files.
It is obviously wrong, so perhaps we should use an alternative way to get the mimetype.
The `mimetype` command returns the right mime type (`text/rust`).
It could be an option.
Thanks to fix this issue.

**Comment by mawww** [comment]
Hello,

ideally the file command should get fixed to recognize rust, where does that mimetype command come from, I do not have it on my system.

**Comment by antoyo** [comment]
On ArchLinux, the `mimetype` command comes from the `perl-file-mimeinfo` package (http://unix.stackexchange.com/questions/185216/file-command-apparently-returning-wrong-mime-type).
Anyway, I'm not sure the mimetype should be used here. Why not using the file extension? That's partly what vim does (it also looks for specific contents in the file).

**Comment by mawww** [comment]
extension should now take precedence for rust files.

**Comment by lenormf** [comment]
> Why not using the file extension?

To expand a bit on this: the extension is used for file types that do not have (and don't need) a mimetype, i.e. source code files. The argument is that the mimetype of a source code file (such as rust) is `text/plain` no matter what, and there's no real reason to have a dedicated mimetype set for a particular language (although some do). As such, kak has it's own `filetype` variable (most times reflected by the `mimetype` one) which you can override when the mimetype of a file isn't appropriate (you can see this in use in `rc/dlang.kak`, `rc/golang.kak`, and you will see it in other scripts supporting languages that are not fancy enough to have their own mimetype).
