### ISSUE TITLE
[QUESTION] What is this cool dot matrix font in your editor image snapshot?

### ISSUE THREAD

**Issue by vegabook** [mawww/kakoune#4818]
### Question

https://github.com/mawww/kakoune/blob/master/doc/screenshot-i3.gif

What is this font please? Thank you!

**Comment by Screwtapello** [comment]
Looks like [Terminus](https://terminus-font.sourceforge.net/)

**Comment by vegabook** [comment]
> Looks like [Terminus](https://terminus-font.sourceforge.net/)

NIce - thank you.
