### ISSUE TITLE
[BUG] expected <buffer>@<timestamp>@main_index

### ISSUE THREAD

**Issue by nonumeros** [mawww/kakoune#4828]
### Version of Kakoune

v2022.10.31

### Reproducer

Consider the folloring on the scratch buffer

ef

cd

ab

Select `cd` and specify a target register, 

Let `a` be the target register

Save the selection with `Z` 

Scroll up to `ef` and select it

Combine selection to target register `a`

Swap selections 

Save selection with target register `a` and yank it 

Scroll down and paste the contents of register `a`

Restore the selection of register `a` 

Obviously, If target register falls back to default `^`,  no error is shown after restoring the selecton of the register. 

If a register is specified it does. 

```
expected <buffer>@<timestamp>@main_index
```

### Outcome

If a register is specified, it throws the error.  Selections cannot be restored.

```
expected <buffer>@<timestamp>@main_index
```

### Expectations

No error whatsoever after restoring selections to a specified register

**Comment by nonumeros** [comment]
Running kak on revision https://github.com/mawww/kakoune/commit/d8883d47c0d3e4f967c512213fe7790dc2c1f9f8  ­— I think. Installed system-wide.

**Comment by nonumeros** [comment]
This has been de facto for awhile now. Only a release dating back to 2018.08.04 didn't have it. 

```
        throw runtime_error("selections can only be saved to the '^' and alphabetic registers");
```
and

```
    // Use the last two values for timestamp and main_index to allow the buffer
    // name to have @ symbols
    struct error : runtime_error { error(size_t) : runtime_error{"expected <buffer>@<timestamp>@main_index"} {} };
```

**Comment by nonumeros** [comment]
Furthermore , if 

```
    struct error : runtime_error { error(size_t) : runtime_error{"expected <buffer>@<timestamp>@main_index"} {} };
    auto end_content = content[0] | reverse() | split('@') | transform([] (auto bounds) {
        return StringView{bounds.second.base(), bounds.first.base()};
    }) | static_gather<error, 1, false>();
```

a SIGSEGV segmentation fault is more than likely here

but I couldn't quite follow that even with a 

```
    if (content.size() < 0)
```

barely makes any difference, if at all. The steps from above can be reproduced

**Comment by nonumeros** [comment]
Some steps from above are superfluous to reproduce the problem

Going over it again, can be summed up as follows

* Restoring multiple selections  with an assigned register results in `expected <buffer>@<timestamp>@main_index` 

* If restoring the assigned register with  multiple selections, Any yanking operation with multiple selections cannot be assigned a register. Falls back to default `"` (then restoring is successful)

* Restoring an assigned register without the error from the running operation `expected <buffer>@<timestamp>@main_index` is possible, if and only If multiple selections are selected, as long as a yanking operation is assigned a different register.

**Comment by Screwtapello** [comment]
Vim has a set of marks `'a` through `'z`, and a set of registers, `"a` through `"z`. In Vim, you can set `'a` to a particular place in the document, then yank to `"a`, move around, then jump back to `'a`, and it all works because marks and registers are completely separate.

Kakoune only has registers `"a` through `"z`. If you save a selection to `"a`, then yank some text to `"a`, that replaces the selection coordinates that were previously saved. You can save a selection to `"a`, then paste all the items from that register with `"a<a-p>` and you'll see that indeed the first item is of the form `<buffer>@<timestamp>@main_index`.

**Comment by Screwtapello** [comment]
If you yank some text to `"a` and then try to restore the selection from `"a`, and the text you yanked isn't in the format Kakoune expects, you'll get the `expected <buffer>@<timestamp>@main_index` error. That's expected behaviour.

**Comment by nonumeros** [comment]
> If you yank some text to `"a` and then try to restore the selection from `"a`, and the text you yanked isn't in the format Kakoune expects, you'll get the `expected <buffer>@<timestamp>@main_index` error. That's expected behaviour.

Not because  is an expected behavior, it fully justifies a lack of features and functionalities (separate or not which vim may have, and kak does not). What would be the point of registers without assigned registers behaving accordingly? 

In the current state of affairs, registers are behaving accordingly alright with features such as `expected <buffer>@<timestamp>@main_index` 
because of coordinates and so forth. 

It surely looks like a «lack thereof» and not an «expected» (as if the latter would clear kak of all shortcomings). 

Because, then it  would no longer be an experiment for an editor, kakoune that is, but a failure in and of itself. As the proverbial saying goes it looks as if the philosophy of registers are an end with kak, which does not justify the means

**Comment by nonumeros** [comment]
@Screwtapello  sometimes I wonder whether kakoune is a marketing experiment tool rather than an editor. I do. 

Every once in a while I find a myriad of excuses as if all of these excuses, would justify somehow where kakoune surpasses vim and where it doesn't. If the latter occurs, it's not surprising to find kak not at fault but vim.

**Comment by nonumeros** [comment]
Of course, to complicate matters even more, every once in awhile Google marketing tags all the messages/notifications coming from kak as promotions, and goes ahead and labels them as such. I'm not sure if it stopped or what. 

But it does the same even with supposedly free software, so it's not unusual on Google's part. At the end of the day, it surely feels as the saying goes with: the pot calling the kettle black. 

Anyhow…

**Comment by nonumeros** [comment]
@Screwtapello  thanks though. I've been just slightly frustrated with the current behavior. And was just expressing what I do think about it as a result. 

But to recapitulate on this, It boils down that for successfully restoring selections that involves any yanking-pasting, every one of these yanking  operations on selections, must be accompanied either by a different register,  or simply fall back to default `"` 

So, in order to successfully restore a given selection by specifying a target register `a`, then another register, different register, let's call it `b`,  must be specified that handles the yanking-pasting operation, or simply by using the default regular copy-paste for every selection.

**Comment by ZakharEl** [comment]
I am trying to create an independent snippet manager that is divorced from any text editor and OS. Basically I want to be implement the same snippet functionality as found in both vscode and textmate snippets with some added features in the same format across different text editors and OSes. I have been a fan and enthusiastic user or kakoune for a while now. I believe if has the possibility to outperform vim, and vscode - also emacs depending on what your opinion of what a text editor should be able to do versus efficiency. It is my favorite text editor right now and for a while. However it is lacking in plugin functionality. This largely is not kakoune's fault. There merely isn't as many users using kakoune to create as many plugins. One very important plugin missing from kakoune is an adequate snippet plugin. I have used snippet plugins for kakoune and all of them so far either do not work or are lacking a lot of functionality. I will have to implement some features on a text editor basis like some kind of bookmarking for the fields within a snippet. My plan was to use the marks - restoring from text within a file or return from my snippet manager upon a request. However with this current bug marks can not be restored from text even if it matches the format of a mark or selection. I have tried using ```kak
set-register caret %sh{ cat file-with-mark-or-selection-format }
``` or something like that but that doesn't work. Neither does ```kak
select %sh{ cat file-with-mark-or-selection-format }
exec Z
```.

**Comment by ZakharEl** [comment]
There seems to currently is a bug with embedding code blocks in markdown on github. I have tried to reedit my previous post. The second code block will not render as a code block.

**Comment by ZakharEl** [comment]
I miss the old functionality with select and marks. Being able to save and restore selections more persistently was nice.

**Comment by ZakharEl** [comment]
Thanks for the text editor. It has been great using it. I have more experience with git and contributing. I also now understand asciidoc. If I could fix this I will. C++ code is more difficult though I have plenty of experience with that as well. However getting into someone's else's code without pointers may take a while.

**Comment by Screwtapello** [comment]
> There seems to currently is a bug with embedding code blocks in markdown on github.

If you want to use the triple-backtick code block syntax, you need to leave a blank line before the first triple-backticks and a blank line after the last. You can't use them in the middle of a paragraph.

> However with this current bug marks can not be restored from text even if it matches the format of a mark or selection.

If you're doing something like:

    set-register caret %sh{ cat file-with-mark-or-selection-format }

..then that's not going to work. The register is a list of strings, where the first string is the `buffer@timestamp@index` item, and the rest are the selections. A `%sh{}` block only produces a single string, so it can't have the correct output.

For example, if you start Kakoune with `kak -n`, then execute the following command:

    set-register caret "*scratch*@1@0 1.2,2.3"

...and press "z" to load it as a selection, you'll get an error. However, if you provide the content as a *list* of strings:

    set-register caret "*scratch*@1@0" "1.2,2.3"

...and press "z", then it loads fine.

Also, be aware that the buffer name at the beginning of the first item needs to be the full, absolute path of an open file. If you try to restore a mark saved from a buffer that isn't open, you'll get an error, Kakoune won't try to open the file.

**Comment by nonumeros** [comment]
> For example, if you start Kakoune with `kak -n`, then execute the following command:
> 
> ```
> set-register caret "*scratch*@1@0 1.2,2.3"
> ```
> 
> ...and press "z" to load it as a selection, you'll get an error. However, if you provide the content as a _list_ of strings:
> 
> ```
> set-register caret "*scratch*@1@0" "1.2,2.3"
> ```
> 
> ...and press "z", then it loads fine.
> 

That's a good one. I like it.

But I think is just an illusion that  `@1@0` would be the main index. And the load desc of that register might as well be too.  It goes right to the newline that follows it

> Also, be aware that the buffer name at the beginning of the first item needs to be the full, absolute path of an open file. If you try to restore a mark saved from a buffer that isn't open, you'll get an error, Kakoune won't try to open the file.

with the recurrent problem you'd be better off by just making multiple selections optional.
