### ISSUE TITLE
[REQUEST] eval -buffer * output with delimiter

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#4835]
### Feature

It's unfortunate that `eval -buffer *` appends results without any delimiter. Here is what I mean:

First let's make a fifo and cat it waiting for output:
```
mkfifo ff && cat ff
```

then in another terminal in the same directory where `ff` is:
```
kak -n -e 'eval -buffer * %{ echo -to-file ff -quoting kakoune %val{bufname} }' a b c
```
eventual result of `cat ff` is `'a''b''c'` where evaluation of each buffer is appended without any delimiter.

It would be nice to see `'a' 'b' 'c'` output, so it's parse-able by external script.

### Usecase

I'm working on [kamp](https://github.com/vbauerster/kamp) utility where parsing `eval -buffer *` needs special case and which might fail if entry contains a quote.

**Comment by Screwtapello** [comment]
Because the block is evaluated in its entirety for each buffer, you can add an unquoted delimiter yourself:

```
kak -n -e 'eval -buffer * %{ echo -to-file ff -quoting kakoune %val{bufname}; echo -to-file ff %{ } }' a b c
```

You could also echo `%val{buflist}` rather than combining `eval -buffer *` with `%val{bufname}` but then you'd get the `*debug*` buffers too, which might not be appropriate.

**Comment by vbauerster** [comment]
That's solves my issue. Thanks for a hint!
