### ISSUE TITLE
[BUG] Prompt completion erroneously interferes with input

### ISSUE THREAD

**Issue by ManDay** [mawww/kakoune#4840]
### Version of Kakoune

2022.10.31

### Reproducer

Typing `:hook -group xyz global ` will

### Outcome

will, upon insertion of the last space, forcefully autocomplete to `:hook -group xyz GlobalSetOption `,

### Expectations

although the `global` would be a correct continuation of the command after the `-group` switch.

**Comment by krobelus** [comment]
confirmed. As a workaround type `'global'` instead of `global`.
`CommandManager::complete` should reuse the `ParametersParser` logic to fix similar issues.

**Comment by krobelus** [comment]
proposed fix in https://github.com/mawww/kakoune/pull/4842
