### ISSUE TITLE
[QUESTION] `ModuleLoaded` behaviour

### ISSUE THREAD

**Issue by glaeqen** [mawww/kakoune#4841]
Is it sane for `ModuleLoaded` hook not to be triggered if it was defined after `require-module` call?

```
provide-module a %{
    hook global ModuleLoaded b %{}
}

provide-module b %{}

require-module b

require-module a # hook will not ever be triggered!
```

As a result, order of lazy-evaluation matters. Is there any rationale behind it? I was expecting the hook to be instantly triggered as soon as I `require-module a`.

**Comment by mawww** [comment]
This is an interesting corner case, I think it would make sense for ModuleLoaded hooks to immediately execute if the module has already been loaded. Any opinions ?

**Comment by krobelus** [comment]
If we didn't expose the `windowing_modules` option this would allow to remove the `KakBegin` hook from windowing/detection.kak.
The suggested behavior makes sense. It's useful for "mixin" style modules like `repl/x11.kak` which adds functionality on top of `x11.kak`.

It would also help kak-lsp get rid of this workaround:

```kak
try %{
    add-highlighter shared/kakrc/code/lsp_keywords regex \[(language\.[a-z_]+\.settings(?:\.[^\]\n]*)?)\] 1:title
} catch %{
    hook global -once ModuleLoaded kak %{
        add-highlighter shared/kakrc/code/lsp_keywords regex \[(language\.[a-z_]+\.settings(?:\.[^\]\n]*)?)\] 1:title
    }
}
```
