### ISSUE TITLE
[BUG] FTBFS with new GCC 13

### ISSUE THREAD

**Issue by tim77** [mawww/kakoune#4851]
### Version of Kakoune

v2022.10.31

### Reproducer

https://github.com/mawww/kakoune/commit/be49f362059c641ea58807cde3571b14be2cabe7

### Outcome

* Full build task https://kojipkgs.fedoraproject.org/work/tasks/5715/97825715/
* [build.log](https://github.com/mawww/kakoune/files/10797187/build.log)

### Expectations

Compiles successfully as before

### Additional information

* Fedora 38
* GCC 13.0.1
* Kakoune version tried:
  * 2022.10.31
  * Master branch
* https://gcc.gnu.org/gcc-13/porting_to.html

**Comment by krobelus** [comment]
I think this is fixed by https://github.com/mawww/kakoune/pull/4858

**Comment by tim77** [comment]
> I think this is fixed by #4858

Can confirm, [compiles](https://koji.fedoraproject.org/koji/buildinfo?buildID=2166499) fine now. Thanks!
