### ISSUE TITLE
[BUG] error on make: ‘uint64_t’ does not name a type

### ISSUE THREAD

**Issue by antono2** [mawww/kakoune#4854]
### Version of Kakoune

master
EDIT: same for release https://github.com/mawww/kakoune/releases/tag/v2022.10.31

### Reproducer

make

### Outcome

`ranked_match.hh:10:21: error: ‘uint64_t’ does not name a type`

### Expectations

compile

### Additional information

Fixed by adding `#include <stdint.h>` or `#include <cstdint>` in 

- `src/ranked_match.hh`
- `src/keys.hh`

gcc 12.2 from their master branch was used, but I have no idea if it has an impact.

**Comment by mujo-hash** [comment]
For kakoune 2022.10.31 I have similar errors for gcc-13, see attached build.log
