### ISSUE TITLE
[BUG]? `:change-directory` uses first autocompletion candidate which might give suprising results

### ISSUE THREAD

**Issue by vsyl** [mawww/kakoune#4866]
### Version of Kakoune

Kakoune v2022.10.31

### Reproducer
- `$ kak -n`
- `:cd ../<ret>`
- `:echo %sh{ echo $PWD }`

### Outcome

working directory changes to the first completion candidate that appeared after typing `../`. 

So for example when you are in the home directory (`/home/username/`) and type `:cd ../<ret>` you won't land in `/home/` but you would stay in `/home/username` assuming `../username` would be the first autocompletion candidate.

This can be prevented pressing `<c-o>` before `<ret>` to disable completions.

### Expectations

working directory should change to  `../` relatively to the current working directory

### Additional information

OS: Linux

**Comment by vsyl** [comment]
I can see that going to the first completion candidate might be considered a feature but this corner case is a bit annoying

**Comment by vsyl** [comment]
`cd ..` works correctly because `../` will be the first completion candidate, so overall this is a very minor bug that some might even consider a feature

**Comment by krobelus** [comment]
thanks for reporting, this is fixed on latest master by 59b8b9957 (Accept "cd dir/" again instead of using a subdirectory, 2022-11-12)

**Comment by vsyl** [comment]
Right, I should have grepped the commits, thanks for the fast reply.
