### ISSUE TITLE
Relative path completion in insert mode should suggest only paths relative to the current buffer

### ISSUE THREAD

**Issue by ismay** [mawww/kakoune#4869]
### Feature

See https://github.com/mawww/kakoune/issues/1562 and https://github.com/mawww/kakoune/issues/609. Currently the filename completer mixes several types of path completion in insert mode. When working in a kakoune session, and editing a buffer that is below the working directory of that session, completion for `'../` will suggest path completions that are relative to the kakoune server's working directory, the buffer's working directory, and suggestions from root, aka `/`.

I find that rather unhelpful, it is confusing to figure out which paths are relative to the buffer, and which are from somewhere else, especially as there is no indication which is which. Not to mention that besides having to figure this out, it is a huge amount of clutter in the completion dialog that I have to scroll through.

I have never wanted to complete a relative file path relative to the server or root, so I would prefer if this could be turned off (or if filename completion relative to the current buffer could be made exclusive). Say by splitting up the `filename` completer into `filename-buffer-relative`, `filename-server-relative`, `filename-absolute`, etc. (Though it seems to me that if a dot precedes the slash it should always be interpreted as relative, and if it's just a slash it should always be interpreted as absolute, but that's besides the point I'm trying to make here)

### Usecase

To complete relative paths in insert mode relative to the buffer more easily. Currently it's way too confusing.

**Comment by krobelus** [comment]
the current mode is the right default, it's consistent with command like `:edit` and `gf`.
Maybe you want to automatically `cd` to the buffer's directory?
What kind of file contains paths that are relative to the file itself? Typescript imports?

**Comment by Screwtapello** [comment]
>  What kind of file contains paths that are relative to the file itself? Typescript imports?

HTML and CSS links, C/C++ `#include` directives, all kinds of things.

**Comment by krobelus** [comment]
Looks like this feature already exists with the `path` option. (I thought it only affected `gf` but it works for filename completion as well).

The default value is `set-option global path ./ '%/' /usr/include` which means the working directory takes precedence over the buffer directory (aka `%/`).

Use `set-option global path '%/' ./ /usr/include` to get the inverted behavior. Neat, huh?

**Comment by ismay** [comment]
I'll close this since it's resolved as far as I'm concerned. Feel free to reopen if necessary!
