### ISSUE TITLE
[REQUEST] Add file opened from command line to edit command history

### ISSUE THREAD

**Issue by caolan** [mawww/kakoune#4874]
### Feature

When opening a file via the command line, e.g. `kak filename.txt`, add this to the command history for `:e`.

### Usecase

Often, after opening an initial file in a deeply nested subdirectory I then want to edit adjacent files and having the path I've just opened in the command history makes constructing those paths easier. I can type `:e` then press up and edit the path instead of tab completing the whole path.

**Comment by Screwtapello** [comment]
If it helps, you can type `:e <c-r>%` to get the name of the current buffer, which you can then edit.

**Comment by caolan** [comment]
> If it helps, you can type `:e <c-r>%` to get the name of the current buffer, which you can then edit.

Thanks. That's a good tip.

**Comment by mawww** [comment]
The `%` register is the way to go to avoid having to write the whole buffer path, I dont think we should inject commands that were not actually typed into the history.
