### ISSUE TITLE
Hardcoded yellow face

### ISSUE THREAD

**Issue by benoit-intrw** [mawww/kakoune#491]
Hello,

There is hard-coded faces to yellow in file `input_handler.cc`

An example :
https://github.com/mawww/kakoune/blob/master/src/input_handler.cc#L857

I found this one trying to change the color of "prompt" display color in status line.

Regards.

**Comment by mawww** [comment]
Yeah, per modes status are using hard coded faces, the "insert" tag, selection numbers, normal mode params, etc... Not sure how/if we want to make all that configurable.

**Comment by lenormf** [comment]
I want it configurable please ! The status bar looks ugly with some color schemes.
