### ISSUE TITLE
[BUG] modeline-parse is too slow for big file

### ISSUE THREAD

**Issue by xnuk** [mawww/kakoune#4911]
### Version of Kakoune

v2022.10.31-189-gcfa658b8

### Reproducer

I feel this issue is duplicated but I cannot find one. Feel free to close/modify this issue.

Let's say you accidentally opened a big file with Kakoune. To do so, you need a big file:
```sh
$ ruby -e '10000.times { puts "a" * 10000 }' > big
$ wc -c big
100010000 big
```

Or you can download [Deno] - this was my case.
```sh
$ wget https://github.com/denoland/deno/releases/download/v1.34.0/deno-x86_64-unknown-linux-gnu.zip
$ unzip deno-x86_64-unknown-linux-gnu.zip
$ sha256sum deno
b5efbe92f540b3b9ebd102adea6fc8a4265d28f0770d0e3065ea9b10962e02f5  deno
$ du -sh deno
105M	deno
```

So root cause of slow loading time was `hook global BufCreate .* %{ try modeline-parse }` in my configure file:
```sh
$ wget https://raw.githubusercontent.com/mawww/kakoune/cfa658b899b44a8a0f4c7f3dd9811ae0d44ddd3a/rc/detection/modeline.kak

$ /bin/time -f "%E secs" kak -n -ui dummy -e 'source ./modeline.kak; try modeline-parse; quit' big
17.96 secs

$ /bin/time -f "%E secs" kak -n -ui dummy -e 'source ./modeline.kak; quit' big
0.14 secs
```

Open `kak -n big` and typing `%saaaa` also can make your Kakoune stuck.

[Deno]: https://github.com/denoland/deno

### Outcome

Stuck - hitting single CPU core up to 99%

### Expectations
Any of these:
- Should open a file in 5 seconds with `hook global BufCreate .* %{ try modeline-parse }` configuration, for any ~100MB file.
- The file is opened in a second, and `modeline-parse` fails for it.
- Kakoune fails to open it.

### Additional information

- [fish], version 3.6.1
- [alacritty] 0.12.1 (5fdfd47f)
- [sway] version 1.8.1
- Arch Linux x64
- CPU: AMD Ryzen 7 1700

[alacritty]: https://github.com/alacritty/alacritty
[sway]: https://github.com/swaywm/sway
[fish]: https://github.com/fish-shell/fish-shell

**Comment by krobelus** [comment]
as a workaround, you can press `<c-g>` to cancel the regex.

The \z part of the regex runs in a pretty inefficient way, it builds up lots of captures even though it will fail most of the time

Possible fix:

```diff
diff --git a/rc/detection/modeline.kak b/rc/detection/modeline.kak
index 32fbf9724..9e7a6de48 100644
--- a/rc/detection/modeline.kak
+++ b/rc/detection/modeline.kak
@@ -118,9 +118,10 @@ define-command -hidden modeline-parse-impl %{
 #   [text]{white}{vi:|vim:|ex:}[white]{options}
 #   [text]{white}{vi:|vim:|Vim:|ex:}[white]se[t] {options}:[text]
 define-command modeline-parse -docstring "Read and interpret vi-format modelines at the beginning/end of the buffer" %{
-    try %{ evaluate-commands -draft %{
-        execute-keys <percent> "s(?S)\A(.+\n){,%opt{modelines}}|(.+\n){,%opt{modelines}}\z<ret>" \
-             s^\S*?\s+?\w+:\s?[^\n]+<ret> x
+    try %{ evaluate-commands -draft -save-regs ^ %{
+        execute-keys gk %opt{modelines} J x Z
+        execute-keys gj %opt{modelines} K x <a-z> a
+        execute-keys s^\S*?\s+?\w+:\s?[^\n]+<ret> x
         evaluate-commands -draft -itersel modeline-parse-impl
     } }
 }
```
