### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by YuFei29** [mawww/kakoune#4919]
There's a typo in wiki->ui->line flags
`flag_lines `should be `flag-lines`
![image](https://github.com/mawww/kakoune/assets/125109356/f0fdd9af-67db-4aa9-a360-e819c248adaf)

**Comment by krobelus** [comment]
Correct. Can you update it? The wiki is writable to everyone with a github account.

**Comment by YuFei29** [comment]
sure, how nice a community
