### ISSUE TITLE
SIGSEGV when using certain registers

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#493]
Hi,

I've noticed that using certain registers ( ```€```, ```£```, ```µ```, ```¨```, ```ß```, ```§```, possible others) crashes kakoune.

I'd also like to ask if there is a way to use an empty register when performing an action that uses one? For example I do not want ```d``` to yank the selection before deleting it. At the moment I'm using an alias to yank to a register I do not use, but that feels like a crutch to me.

**Comment by alpha123** [comment]
Can confirm this on FreeBSD 10.1. Unfortunately I was running a release build so the core dump was not especially useful.

> I'd also like to ask if there is a way to use an empty register when performing an action that uses one? For example I do not want d to yank the selection before deleting it. At the moment I'm using an alias to yank to a register I do not use, but that feels like a crutch to me.

I don't see anything hacky about that, it's the vim/kak way. The register equivalent of /dev/null doesn't really seem that useful to me.

**Comment by alexherbo2** [comment]
@occivink I added an issue #497 to have the `_` black hole register just like in vi.
