### ISSUE TITLE
Unable to build from source on FreeBSD

### ISSUE THREAD

**Issue by donaldcallen** [mawww/kakoune#4944]
### Version of Kakoune

v2023-07-04

### Reproducer

Clone the repository on a FreeBSD 13.2 system and run make.

### Outcome

c++ -I/usr/local/include -O3 -pedantic -std=c++2a -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-address -frelaxed-template-template-args -Wno-ambiguous-reversed-operator -MD -MP -MF .highlighters.opt.d -c -o .highlighters.opt.o highlighters.cc
In file included from highlighters.cc:1:
In file included from ./highlighters.hh:4:
In file included from ./color.hh:4:
In file included from ./exception.hh:4:
In file included from ./string.hh:7:
In file included from ./utf8.hh:5:
In file included from ./unicode.hh:7:
In file included from ./array_view.hh:5:
In file included from /usr/include/c++/v1/iterator:616:
In file included from /usr/include/c++/v1/__iterator/reverse_access.h:14:
/usr/include/c++/v1/__iterator/reverse_iterator.h:118:41: error: call to deleted function 'addressof'
    pointer  operator->() const {return _VSTD::addressof(operator*());}
                                        ^~~~~~~~~~~~~~~~
/usr/include/c++/v1/__config:826:15: note: expanded from macro '_VSTD'
#define _VSTD std
              ^
./display_buffer.hh:145:53: note: in instantiation of member function 'std::reverse_iterator<std::move_iterator<std::__wrap_iter<const Kakoune::DisplayAtom *>>>::operator->' requested here
            m_range.end = std::max(m_range.end, last->end());
                                                    ^
highlighters.cc:1853:32: note: in instantiation of function template specialization 'Kakoune::DisplayLine::insert<std::move_iterator<std::__wrap_iter<const Kakoune::DisplayAtom *>>>' requested here
            auto it = line_it->insert(
                               ^
/usr/include/c++/v1/__memory/addressof.h:71:27: note: candidate function [with _Tp = Kakoune::DisplayAtom] has been explicitly deleted
template <class _Tp> _Tp* addressof(const _Tp&&) noexcept = delete;
                          ^
/usr/include/c++/v1/__memory/addressof.h:25:1: note: candidate function [with _Tp = const Kakoune::DisplayAtom]
addressof(_Tp& __x) _NOEXCEPT
^
In file included from highlighters.cc:1:
In file included from ./highlighters.hh:4:
In file included from ./color.hh:4:
In file included from ./exception.hh:4:
In file included from ./string.hh:7:
In file included from ./utf8.hh:5:
In file included from ./unicode.hh:7:
In file included from ./array_view.hh:5:
In file included from /usr/include/c++/v1/iterator:616:
In file included from /usr/include/c++/v1/__iterator/reverse_access.h:14:
/usr/include/c++/v1/__iterator/reverse_iterator.h:118:41: error: calling a private constructor of class 'std::__wrap_iter<const Kakoune::DisplayAtom *>'
    pointer  operator->() const {return _VSTD::addressof(operator*());}
                                        ^
/usr/include/c++/v1/__config:826:15: note: expanded from macro '_VSTD'
#define _VSTD std
              ^
/usr/include/c++/v1/__iterator/wrap_iter.h:145:57: note: declared private here
    _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_AFTER_CXX11 __wrap_iter(iterator_type __x) _NOEXCEPT : __i(__x) {}
                                                        ^
2 errors generated.
make[1]: *** [Makefile:104: .highlighters.opt.o] Error 1
make[1]: Leaving directory '/usr/home/dca/Software/FreeBSD/kakoune/src'
make: *** [Makefile:2: all] Error 2
dca@giovanni:/home/dca/Software/FreeBSD/kakoune$ which c++
/usr/bin/c++
dca@giovanni:/home/dca/Software/FreeBSD/kakoune$ c++ --version
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd13.2
Thread model: posix
InstalledDir: /usr/bin
dca@giovanni:/home/dca/Software/FreeBSD/kakoune$

### Expectations

An error-free build.

**Comment by Screwtapello** [comment]
Can you try building with the version of clang in ports, instead of the one in the base system? I vaguely recall the one in the base system is only intended for building the base system, not for building third-party software...

**Comment by krobelus** [comment]
FreeBSD and macOS CI has been failing the same way. Likely a bug in an old version of libcxx.
We should find a workaround. Probably introduced by e0728d343 (Speed up regions highlighting on files with big lines, 2023-06-09)

**Comment by chenrui333** [comment]
I am seeing couple of build failures with 2023.07.29 release.

**Comment by mawww** [comment]
Fixed by d1e189f1bf8ed296872235e73c51ab75251b2e8c and made a new 2023.08.05 release
