### ISSUE TITLE
[BUG] "new" command breaks in kitty if it was defined by headless

### ISSUE THREAD

**Issue by Abraxas-Knister** [mawww/kakoune#4954]
### Version of Kakoune

v2022.10.31

### Reproducer

Alternative 1:

* open kitty `kitty --config NONE`
* start the headless by `setsid kak -d -s session`
* connect to it `kak -c session`
* issue `:new` 

Alternative 2:

* open kitty instance A
* start headless by `kak -d -s session`
* close kitty instance A
* go to any kitty instance B
* connect to headless `kak -c session`
* issue `:new`

Alternative 3:

* open kitty instance A
* start keadless by `kak -d -s session`
* do not close kitty
* go to a different kitty instance B
* connect to headless `kak -c session`
* issue `:new`

### Outcome

Alternatives 1 and 2: 

After `:new` no new client spawns. In debug buffer:
```raw
shell stderr: <<<
Error: open /dev/tty: no such device or address
>>>
```

Alternative 3:

`:new` spawns new client, but as a kitty window in instance A. After closing A, we are in alternative 2

### Expectations

`:new` should create a new kitty window of the currently active kitty instance, running a new client.

### Additional information

`setsid kitty @ launch kak -c session`  gives the same error message as will be in the debug buffer.

---

`setsid kak -d -s session -E 'echo -debug %sh{ file /dev/tty }'` writes `/dev/tty: character special (5/0)` into the debug buffer. This means the headless has a controlling terminal, however `setsid kak -d -s s -E 'nop %sh{ echo a >> /dev/tty }'` does not print `a` to the console, so it is not the same controlling terminal as for the shell that set it up. Moreover this leads to the following entry in the debug buffer
``` raw
shell stderr: <<<
sh: line 1: /dev/tty: No such device or address
>>>
```
so I guess it exists and does not exist at the same time. Schrödingers controlling terminal.

**Comment by Screwtapello** [comment]
`/dev/tty: character special (5/0)` does not indicate that the process has a controlling terminal, it just indicates that `/dev/tty` exists (as it should, it's a real directory entry on disk). The only weird thing about `/dev/tty` is that *if* your process does not have a controlling terminal, then trying to open `/dev/tty` returns `ENXIO`.

Kitty's special `kitty @` syntax uses some special mechanism for figuring out what Kitty window or pane it's running inside of. I don't know how it works, and it's quite possible it does something that depends on tracing the process hierarchy from the `kitty` command all the way back up to the `kitty` GUI, in which case when Kakoune puts itself into the background that's going to break Kitty's system. Looking at the Kitty plugin in Kakoune, it seems there's special support for a `$KITTY_LISTEN_ON` variable to tell the command-line tool how to communicate to the parent GUI, although I don't think it's enabled by default. Do you have that feature enabled?

**Comment by Abraxas-Knister** [comment]
I had `allow_remote_control yes` in my kitty.conf, which apparently was enough to let `kitty @` understand where it is in alternative 3. I changed that to
```raw
allow_remote_control socket-only
listen_on /tmp/kitty
```
which hat all alternatives working as expected. Many thanks!
