### ISSUE TITLE
[BUG] ctrl-z does not background the server

### ISSUE THREAD

**Issue by Abraxas-Knister** [mawww/kakoune#4957]
### Version of Kakoune

Kakoune v2023.07.29

### Reproducer
 
Open two clients in the same session, from the same terminal

 *`kak -s hi`
 * `<c-z>`
 * `kak -c hi`

### Outcome

client started by `kak -c` doesn't show anything and there is no reaction to any keys.

### Expectations

In [this discourse](https://discuss.kakoune.com/t/i-closed-the-terminal-that-had-the-kak-server-now-the-clients-are-sad/2269/15) maxime said `<c-z>` should background the server, meaning the new client should be working like any other.

### Additional information

If you input something into the blank window, `<c-z>` out of it, and foreground the previous client again (eg `fg 1`) you'll see that your input actually did affect the session.

**Comment by Screwtapello** [comment]
For efficiency, Kakoune doesn't start the server separately until a second client connects. If you do those same operations in a different order:

* `kak -s hi` in terminal 1
* `kak -c hi` in terminal 2
* `<c-z>` in terminal 1

...then things should work as you expect.

**Comment by krobelus** [comment]
here is a quick fix. Techincally it includes a race conditon (if another client connects and disconnects while we are still converting to a client, we exit..)

```diff
diff --git a/src/main.cc b/src/main.cc
index 5e7c50b5c..df35fcd40 100644
--- a/src/main.cc
+++ b/src/main.cc
@@ -698,11 +698,7 @@ std::unique_ptr<UserInterface> create_local_ui(UIType ui_type)
         LocalUI()
         {
             set_signal_handler(SIGTSTP, [](int) {
-                if (ClientManager::instance().count() == 1 and
-                    *ClientManager::instance().begin() == local_client)
-                    TerminalUI::instance().suspend();
-                else
-                    convert_to_client_pending = true;
+                convert_to_client_pending = true;
            });
         }
 
@@ -918,8 +914,10 @@ int run_server(StringView session, StringView server_init,
                 show_startup_info(local_client, global_scope.options()["startup_info_version"].get<int>());
         }
 
+        bool converting_to_client = false;
         while (not terminate and
-               (not client_manager.empty() or server.negotiating() or server.is_daemon()))
+               (not client_manager.empty() or server.negotiating()
+                    or server.is_daemon() or converting_to_client))
         {
             client_manager.redraw_clients();
 
@@ -936,6 +934,8 @@ int run_server(StringView session, StringView server_init,
                 }
             }
             catch (const cancel&) {}
+            if (not client_manager.empty())
+                converting_to_client = false;
 
             client_manager.process_pending_inputs();
 
@@ -972,6 +972,8 @@ int run_server(StringView session, StringView server_init,
                     server.close_session(false);
                     throw convert_to_client_mode{ std::move(session), std::move(client_name), std::move(buffer_name), std::move(selections) };
                 }
+
+                converting_to_client = true;
             }
         }
     }
```

**Comment by lobre** [comment]
Hey, I wanted to rely on this automatic backgrounding of the server on `<c-z>` to allow me to detach from a session and reattach to another one, but I hit this exact same problem.

As of today, it seems there is no way to really detach without writing a wrapper to `kak` or without explicitly starting kakoune in daemon mode. This is sad because this feature on suspend is quite nice in terms of design.

**Comment by lobre** [comment]
I see there is a `:daemonize-session` that explicitly does what I want in fact.

**Comment by mawww** [comment]
Almost, I think we should fork the server to background on `<c-z>` if `daemonize-session` has been called. AFAIR we do not do that currently, but fork to background on exit of the merged client/server process.

The reason we do not fork to background on `<c-z>` if we have a single process is that it seems unlikely we would want to connect to the server while the initial client is suspended and moving to separate client/server processes seems wrong without a strong reason. If we have explicitely called `daemonize-session` it would be a strong enough signal that we will want to use the server independently of the original client, so we might as well fork it.
