### ISSUE TITLE
[BUG]  The "fix" 'Only make cursor visible after buffer or selection change' makes this editor unusable for me

### ISSUE THREAD

**Issue by donaldcallen** [mawww/kakoune#4963]
### Version of Kakoune

Kakoune v2023.08.05-4-g1e38045d

### Reproducer

Edit any file longer than a page. The cursor is over the first character in the buffer. Use ctrl-f to page down. The cursor does not move to the top of the newly displayed text, as those of us who have used vim for years would expect,  but is still over the first character in the file. If you then use <count> j to move down in the new text, you end up back on the first page of the file.

### Outcome

Utter frustration. This change is unacceptable to me. Yes, I can back it out by running the released version. But I prefer to run the current sources to get the latest fixes, though this is a perfect example of what that may be a bad idea. If this change doesn't get backed out before the next release or is (perhaps) fixable by some key-mapping trickery, I won't be able to continue using kakoune.

### Expectations

I expect it to behave as (n)vim does, as helix does, and as kakoune did before this change.

**Comment by evanrelf** [comment]
I personally love the new behavior, because I don't have to worry about scrolling affecting my selections. I don't have to be careful not to scroll, or double check my selections haven't drifted. I'm no longer stressed about having selections outside the viewport.

Maybe this could be configurable, or there could be new mappings so you could access both behaviors.

**Comment by donaldcallen** [comment]
On Tue, Aug 22, 2023 at 9:07 PM Evan Relf ***@***.***> wrote:

> I personally love the new behavior, because I don't have to worry about
> scrolling affecting my selections. I don't have to be careful not to
> scroll, or double check my selections haven't drifted. I'm no longer
> stressed about having selections outside the viewport.
>
> Maybe this could be configurable, or there could be new mappings so you
> could access both behaviors.
>
I can certainly understand that this is subjective (my guess is that people
with long vim histories will not be happy about finding themselves betrayed
by muscle memory; perhaps you are not one of them). Your suggestion of
making it configurable/optional is a good one.

**Comment by mawww** [comment]
This change is indeed experimental and clearly needs tweaking, I expected to have a bit more time to iterate but have been busier than I thought. The current behaviour is frustrating in various corner cases and I do intend to improve on that.

**Comment by mawww** [comment]
I intend to iterate on this on the no-cursor-move-on-scroll branch, in the meantime I reverted this change from master as I think the current status is a bit too rough to impose on all users tracking it.
