### ISSUE TITLE
Doesn't compile on cygwin

### ISSUE THREAD

**Issue by loreb** [mawww/kakoune#498]
highlighters.cc:735:52: error: ‘snprintf’ was not declared in this scope

That's because cygwin's stdio.h only declares snprintf if __cplusplus is > (not >=) 201103

Googling "cygwin c++ snprintf" brings up some disagreeing opinions on who's to blame
and what compiler flags should be used, but in the meantime explicitly declaring snprintf
(`extern "C" int snprintf(char *, size_t, const char *, ...);`) works.

**Comment by mawww** [comment]
Hello,

That is strange, I compile Kakoune very regularly on cygwin as I use windows at work.

It seems its linked to gcc 4.8.2, right ? if so, does including <cstdio> and using std::snprintf helps ?

**Comment by loreb** [comment]
Cygwin is fully up to date, running on windows 10 64 bits.
$ g++ --version
g++ (GCC) 4.9.3

Replacing "snprintf" => "std::snprintf" in line 735
=> highlighters.cc:735:9: error: ‘snprintf’ is not a member of ‘std’

Leaving snprintf without "std::" and Including stdio.h or cstdio works, meaning that my previous explanation of the bug was wrong :)
(in my defense, I was misled by google, I have a 80x25 terminal in cygwin, and ">=" in stdio.h is split between the '>' and the '=')

No idea why it was working for you at this point...

**Comment by loreb** [comment]
No, wait, I'm a moron...
Since I have no other use for Boost I compile with -DKAK_USE_STDREGEX,
maybe boost/regex.hpp pulls in stdio somehow.

**Comment by mawww** [comment]
Yeah seems its a missing include, and that by chance boost does include it anyway.

KAK_USE_STDREGEX is not supported unfortunately, its some experimental code, many unstandardised features (lookbehind, \K, \` and \', \h...) are used in language support scripts, some of them not easy to get rid of.

**Comment by loreb** [comment]
Oh, ok.
