### ISSUE TITLE
[BUG] cannot open path containing single quotes

### ISSUE THREAD

**Issue by FlyingWombat** [mawww/kakoune#4980]
### Version of Kakoune

01fd6552af6b909f533d5cd8bf3a5385d4e35215

### Reproducer

```bash
mkdir test\'test
echo foobar > test\'test/foo.txt
kak -d -s foo -n &
kak -c foo test\'test/foo.txt
# also triggers
cd test\'test
kak -c foo foo.txt
```

### Outcome

Kakoune fails to open the file, and instead displays a "new file" buffer.

No messages in debug buffer

status line says
`1:1: 'edit': test/foo.txt' is not a number              ~/test\ 1:1 [new file] 1 sel - client0@[asdf]`

### Expectations

open file

### Additional information

Only single  quotes `'` in paths produce this bug, not double-quotes or other special characters (e.g. `!` `?` `;` `*` `|`). I haven't exhaustively tested all special characters.

`kak -n test\'test/foo.txt` opens the file as expected. This bug is only triggered when connecting to a remote session.

**Comment by arachsys** [comment]
The `kak -c foo test\'test/foo.txt` command sends `edit '/tmp/kak/test\'test/foo.txt';` to the remote session, but single quotes in single-quoted strings should be escaped by doubling-up, not with backslash. The fix below sends `edit '/tmp/kak/test''test/foo.txt';` instead in this case:

```diff
diff --git a/src/main.cc b/src/main.cc
index 7527e80..54ae248 100644
--- a/src/main.cc
+++ b/src/main.cc
@@ -1231,7 +1231,7 @@ int main(int argc, char* argv[])
             }
             String new_files;
             for (auto name : files) {
-                new_files += format("edit '{}'", escape(real_path(name), "'", '\\'));
+                new_files += format("edit '{}'", escape(real_path(name), "'", '\''));
                 if (init_coord) {
                     new_files += format(" {} {}", init_coord->line + 1, init_coord->column + 1);
                     init_coord.reset();
```
