### ISSUE TITLE
[REQUEST] Dark mode support

### ISSUE THREAD

**Issue by Ashvith10** [mawww/kakoune#4981]
### Feature

Add support for dark mode. I can think of three possible circumstances:
- users who do not want this can simply set the `default_scheme` and disable dark mode in the script
- users who want to auto-set themes when the system theme changes can simply enable this behavior in the configuration and set the `night-scheme` (by making use of `xdg-desktop-portal`)
- users who would prefer manual switch also have the option to toggle theme

### Usecase

Explained above with three different circumstances

**Comment by Screwtapello** [comment]
Kakoune's default colorscheme *is* dark mode, and you can change it any time you want with the `colorscheme` command. What would you expect "supporting dark mode" to look like? A command? A hook? A register?

**Comment by FlyingWombat** [comment]
Kakoune's default colorscheme is just your terminal's colors. If you are using a light-themed terminal, kakoune will use the same light colors.

If you want something different, you can set the colorscheme to anything you like in your kakrc.

**Comment by Ashvith10** [comment]
@FlyingWombat what I meant is that I want to be able to choose a custom theme, like gruvbox-light and gruvbox-dark without having to rely on the `:colorscheme <color>` command. So basically, watching the dark mode value from xdg-desktop-portal.

**Comment by FlyingWombat** [comment]
Oh, so you want to pick between different custom colorschemes depending on an external variable. OK.

You could use a shell expansion in your kakrc, something like:
```kak
colorscheme %sh{
  DARKMODE= ... # get xdg dark mode value
  if [ "$DARKMODE" = "true" ]; then
    printf gruvbox-dark
  else
    printf gruvbox-light
  fi
}
```

If I understand your feature request correctly, you want something like this to be put in kakoune's stdlib and for it to be the default behavior. One barrier to doing that, is that not all colorschemes have both dark and light variants.

**Comment by Ashvith10** [comment]
@FlyingWombat Not an external variable, but more like a hook for [xdg-desktop-portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings). Perhaps checking out this Vim plugin would make sense: [vim-lumen](https://github.com/vimpostor/vim-lumen). I think that this plugin has a constraint that themes always have to provide both the light and dark schemes.

But on second thought, since Kakoune is an editor that ties itself around the coreutils, it makes a lot of sense to rely only on the default theme, and rather override it from the app itself to get that consistent color between multiplexer, shell and the editor itself.

**Comment by FlyingWombat** [comment]
For the first option, someone more experienced with kakoune's code than me will have to weigh in. AFAIK, kakoune doesn't have any real IPC for external processes. A xdg-desktop-portal hook sounds it may require that.

As is, I know you can send commands to a given session using the -p flag, like so:
```bash
for session in $(kak -l); do
  echo 'colorscheme gruvbox-light' | kak -p $session
done
```
You could maybe write an external script with this snippet to hook into xdg-desktop-portal.

**Comment by SolitudeSF** [comment]
shouldnt you just change your terminal colors for that?

**Comment by Ashvith10** [comment]
@FlyingWombat that makes a lot of sense. For now, I'm making use of the terminal scheme, and adding modifications over it, as it provides an overall consistency with the theme of the shell.
