### ISSUE TITLE
[BUG] Line highlighting does not work on all lines

### ISSUE THREAD

**Issue by 4sdx** [mawww/kakoune#5001]
### Version of Kakoune

v2023.08.05

### Reproducer

Enable cursor line highlighting by [ui.kak](https://github.com/kkga/ui.kak) or [crosshair](https://github.com/insipx/kak-crosshairs).
Than scrolling through a file, not all lines will be highlighted.

Another way to reproduce:
1. Open a source file (e.g.: any from Kakoune)
2. Remove cursor line highlighter: `remove-highlighter window/cursorline`
3. Add cursor line highlighter: `add-highlighter window/cursorline line <line-number> CursorLine`

### Outcome

Sometimes the cursor line highlighting works for specific lines, but fails for others.

### Expectations

It shall be able to highlight any line in the window.

### Additional information

The feature started to malfunction from this commit: [e0728d3434d5ea335521484521d246473ca06165](https://github.com/mawww/kakoune/commit/e0728d3434d5ea335521484521d246473ca06165)

**Comment by DISSISOR** [comment]
Still true at current master with following in my kakrc:
```
hook global RawKey .+ %{
    try %{ remove-highlighter window/curhl }
    try %{add-highlighter window/curhl line %val{cursor_line} default,rgb:282828}
}
```

Though, it doesn't reproduce without adding highlighter for line numbers! Also, it seems to always highlight line with ` '` and ` "` substrings (spaces are intentional. Replaceable with tabs on my config).

**Comment by mawww** [comment]
Thanks for bumping this up, fix incoming.

**Comment by DISSISOR** [comment]
Thanks a lot for your work! Already tried and it's awesome. Appreciate a lot.

**Comment by 4sdx** [comment]
I tried too. It works as expected.
Thanks for fixing the best code editor! :)
