### ISSUE TITLE
Have a man page for the project

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#503]
Hi,

Some time ago I had started writing a man page for the project (and had it installed by default, in the Makefile), but several recent changes would have me go over everything so I'm putting this on the back burner for now.

How about we generate the man page automatically from the `README` of the repository ? It could be done with `rst2man.py` or directly from `asciidoc`, after touching up the file a bit.

Cheers.

**Comment by jkonecny12** [comment]
If I understand you right you want to convert the mega big README in git to man page? I don't think this is good idea. IMHO manpage should be only about what is the program, how to start it and description of console parameters which is maybe 5% of the README and I think in bad format.

**Comment by jkonecny12** [comment]
Maybe it would be best give here the converted manpage we can then look on it and we will see.

**Comment by lenormf** [comment]
It would take at least an hour of work to move everything from the README to a man page, the only sane way to do this is generate it.

**Comment by jkonecny12** [comment]
Yeah I meant generated manpage of course I didn't want you to write it. 

Truth is it's better to have any manpage than nothing and I think we don't find somebody who have time to create written documentation and will synchronize it with newest features. 
So you have my vote for the generated manpage.

It will be really nice to have it in the Fedora package.

**Comment by lenormf** [comment]
Done!
