### ISSUE TITLE
[BUG] Windows Terminal `keep pipe:y`

### ISSUE THREAD

**Issue by tom-huntington** [mawww/kakoune#5032]
### Version of Kakoune

Kakoune v2021.11.08-122-g13b16815

### Reproducer

Start Kakoune 
```
$ kak
```
Control-Z to put kakoune in background
```
$ fg
```
to bring kakoune to foreground

### Outcome

Greeted by kakoune prompt
```
keep pipe:y
```

### Expectations

kakoune comes back in state I pressed control-z in i.e. normal mode

### Additional information

Notably it doesn't happen everytime, only about 50% of the time.

Also, this only became a problem after changes on the windows side. When I first originally build kakoune, this was not happening.

Original issue from terminal: https://github.com/microsoft/terminal/issues/16094

Note: this doesn't happen if I run wsl from command promp

**Comment by caksoylar** [comment]
Can confirm the same here. Doesn't happen in `tmux`, which is probably to be expected.

**Comment by Screwtapello** [comment]
As the Microsoft Terminal issue suggests, a control-sequence sent by the terminal to Kakoune is being interpreted as keys. If you can reproduce this, try `:set global debug keys` before hitting `<c-z>`, and then when you bring Kakoune back, if the problem reproduces, go check the `*debug*` buffer and see what keys have been pressed. It would be interesting to know if it's always the same bytes being misinterpreted as keys (meaning, possibly a problem in Kakoune's input state machine) or if it's sometimes different (meaning, the input stream being split across packets, preventing Kakoune from detecting them as a single control sequence).

**Comment by tom-huntington** [comment]
I seem to be always getting the same keys when it reproduces
```
Client 'client0' got key '<a-[>'
Client 'client0' got key '0'
Client 'client0' got key '$'
Client 'client0' got key 'y'
```
and nothing when it does not reproduce

**Comment by tom-huntington** [comment]
This also happens if I open a second client 
```
# First shell
kak -s myproject
```

```
# Second shell
kak -c myproject
# keep pipe:y
```

**Comment by Screwtapello** [comment]
When Kakoune initialises a terminal, it asks the terminal if it supports mode 2026 (output synchronisation):

    \033[?2026$p

The terminal is supposed to respond with "I've never heard of that mode", "yes, and it's currently enabled", or "yes, and it's currently disabled":

    \033[?2026;0$y  // never heard of it
    \033[?2026;1$y  // enabled
    \033[?2026;2$y  // disabled

It seems your terminal is instead sending:

    \033[0$y

...which is *vaguely* like a query response, but I can't see a situation where a terminal should send a response like that.


Here's a command that sends all the control sequences Kakoune sends at startup, then 

    reset; printf '\033[?1049h\033[?1004h\033[>4;1m\033[>5u\033[22t\033[?25l\033=\033[?2026$p\033[?2004h'; read

If you paste that command into a terminal then press Enter twice, it should clear the screen and then you'll see whatever the terminal sends back, which I *expect* will look something like this:

    ^[[I^[[0$y

Is that what happens?

**Comment by tom-huntington** [comment]
tmux and command prompt send nothing.

Terminal sends
```
^[[?2026;0$y
```

**Comment by Screwtapello** [comment]
You said originally that the problem reproduces 50% of the time in Kakoune - when you run the `printf` command, does it *always* respond `^[[?2026;0$y` or just some of the time?

**Comment by tom-huntington** [comment]
Your `printf` command has returned the same thing every time I tried it. However, the response very slow, and there may be a timing problem.

If I hit `<enter>` before the text appears then I get `2026;0$y` in my terminal prompt.

It also makes the cursor disappear, and causes the terminal to make a notification sound when navigated away from, and to.

**Comment by arachsys** [comment]
I've seen problems from the startup query for terminal synchronisation support too. In my case, it was over a networked serial console, whose slowness can break atomic read() of escape sequences by kakoune. (Interestingly, this is the only breakage I experience in practice with kak on a slow serial console.)

Unfortunately, disabling sync support with
```
set-option -add global ui_options terminal_synchronized=false
```
in `kakrc` doesn't stop the query being sent.

For my own build, I have a local patch
```diff
diff --git a/src/terminal_ui.cc b/src/terminal_ui.cc
index b232a38..a35d3c7 100644
--- a/src/terminal_ui.cc
+++ b/src/terminal_ui.cc
@@ -1466,7 +1466,6 @@ void TerminalUI::setup_terminal()
         "\033[22t"    // save the current window title
         "\033[?25l"   // hide cursor
         "\033="       // set application keypad mode, so the keypad keys send unique codes
-        "\033[?2026$p" // query support for synchronize output
         "\033[?2004h" // force enable bracketed-paste events
     );
 }
@@ -1536,6 +1535,8 @@ void TerminalUI::set_ui_options(const Options& options)
     auto synchronized = find("terminal_synchronized").map(to_bool);
     m_synchronized.set = (bool)synchronized;
     m_synchronized.requested = synchronized.value_or(false);
+    if (not m_synchronized.queried and not m_synchronized.set)
+        write(STDOUT_FILENO, "\033[?2026$p");
 
     m_shift_function_key = find("terminal_shift_function_key").map(str_to_int_ifp).value_or(default_shift_function_key);
 
diff --git a/src/terminal_ui.hh b/src/terminal_ui.hh
index e1a9633..774b436 100644
--- a/src/terminal_ui.hh
+++ b/src/terminal_ui.hh
@@ -158,6 +158,7 @@ private:
 
     struct Synchronized
     {
+        bool queried : 1;
         bool supported : 1;
         bool set : 1;
         bool requested : 1;

```
to skip the query when I've explicitly disabled support. Possibly worth sending upstream if others are seeing problems too - I assumed I was the only one who used kakoune in a weird enough niche that it could cause issues.

**Comment by tom-huntington** [comment]
This is not reproducing for me anymore. Windows Terminal patched?
