### ISSUE TITLE
[QUESTION][BUG or FEATURE?] Can't access terminal environement variable when connecting to a session

### ISSUE THREAD

**Issue by thhck** [mawww/kakoune#5054]
### Question

Let's open a terminal and create a new kakoune session with environment variable:
```
MY_VAR=FOO kak -s my_sess
```
If I run in this kakoune instance:
`echo %sh{ echo $MY_VAR}`
I get:
`FOO`

Now let's open a second terminal and connect to this session with a different environment variable:
`MY_VAR=BAR kak -c my_sess`
Now if I run in this kakoune instance:
`echo %sh{ echo $MY_VAR}`
I am expecting :
`BAR`
But I get:
`FOO`

So it seems that if I connect to a specific kakoune session I can only access the environment variable from the shell that created the session. 

THis is a bit struggling when using kakoune inside zellij for example ( a tmux alternative ) because the ZELLIJ_SESSION_NAME will always return the zellij session of the first shell,  so each zellij command run from a `kak -c` will not be run in the the shell running `kak -s`

**Comment by krobelus** [comment]
> `MY_VAR=BAR kak -c my_sess`
> Now if I run in this kakoune instance:
> `echo %sh{ echo $MY_VAR}`
> I am expecting :
> `BAR`
> But I get:
> `FOO`

This is working as intended.
You can use `%sh{ echo $kak_client_env_MY_VAR }` for client-specific environment variables.
The existing `:zellij-*` commands already use this actually.

**Comment by thhck** [comment]
Thanks ! I miss this one. closing
