### ISSUE TITLE
[BUG] Soft wrap -width only soft wrapping for first portion of long line

### ISSUE THREAD

**Issue by sdothum** [mawww/kakoune#5069]
### Version of Kakoune

v2023.08.05

### Reproducer

Opening a markdown file with with paragraphs of text written as a single line (one <return> char at end of line).

Highlighter is set as:

`hook global WinSetOption filetype=markdown %{ add-highlighter global/ wrap -word -indent -marker "  ↪ " -width 80 }`

### Outcome

For each paragraph, the first displayed line is soft wrapped at -width setting. 

The following line is the portion of the line that would have displayed to the terminal width.

The remaining lines display, soft wrapped, to the terminal (window) width.

### Expectations

Consistent soft wrapping of long lines of text to -width setting. 

### Additional information

OS: Alpine Linux 3.19

Same results with latest compiled git master.

**Comment by Screwtapello** [comment]
I think there must be more going on than that.

I made a Markdown file with long, unwrapped lines, then I launched Kakoune with:

    kak -n unwrapped.md -e 'add-highlighter global/ wrap -word -indent -marker "  ↪ " -width 80'

I wound up with the following:

![image](https://github.com/mawww/kakoune/assets/1450918/1800c6cd-60f8-49d7-89f6-cb4e52923c12)

I could not reproduce the behaviour you describe. Possibly in your configuration other highlighters are interfering?

**Comment by sdothum** [comment]
Thank you for checking this.. i thought it unlikely that this could have gone unnoticed till now!

(i'm a late adopter of Kakoune -- vi/vim for forever and recently Helix, but Kakoune has won me over -- so it never occurred to me to look for a conflicting highlighter.)
