### ISSUE TITLE
[BUG] test gets stuck at "regression/0-intermediate-regex-saved-in-history"

### ISSUE THREAD

**Issue by arrufat** [mawww/kakoune#5073]
### Version of Kakoune

v2023.08.05-190-g9b166e800

### Reproducer

Just run `make test`

### Outcome

The test suit gets stuck at `regression/0-intermediate-regex-saved-in-history`

### Expectations

All tests should pass

**Comment by krobelus** [comment]
maybe this was the cause of the `Failed to start an instance: FAILED_PRECONDITION: Monthly compute limit exceeded!` failures we're seeing now

**Comment by arrufat** [comment]
Thank you, @krobelus, I can confirm that makes all test pass now.
