### ISSUE TITLE
[BUG] <a-O> no longer works correctly

### ISSUE THREAD

**Issue by ismay** [mawww/kakoune#5074]
### Version of Kakoune

v2023.07.29

### Reproducer

1. Press `<a-O>`
2. Kakoune should add empty line above cursor without entering insert mode

### Outcome

Kakoune adds an empty line below the cursor without entering insert mode

### Expectations

For the empty line to be added above the cursor, not below.

### Additional information

I'm using arch, fish and alacritty. I double checked the keycodes, and verified that alacritty is picking up the keys I press as `<a-O>`. I also double checked fish, and that also seems to be picking up the keys I press as `<a-O>`. So kakoune is receiving the correct keys, just not performing the expected action. I have not remapped `<a-O>` in my kakoune config.

**Comment by krobelus** [comment]
Can't reproduce

**Comment by ismay** [comment]
I inspected it some more. Even though `alacritty --print-events` is logging the correct keycodes, something seems to be going wrong there. In kitty it all works fine. I'll open this in the alacritty repo, thanks for the quick reply!

**Comment by ismay** [comment]
https://github.com/alacritty/alacritty/issues/7567
