### ISSUE TITLE
[REQUEST] macOS Terminal.app windowing support

### ISSUE THREAD

**Issue by 2xsaiko** [mawww/kakoune#5077]
### Feature

It would be great to have support for Terminal.app so :new, kak-fzf and whatever else uses :terminal work with it. It should be relatively straight forward to adapt from the iTerm code.

It sets TERM_PROGRAM=Apple_Terminal.

To run a command in a new window, this is what I found:

```applescript
tell application "Terminal"
	do script "exec kak"
end tell
```

**Comment by mawww** [comment]
Hello, I would merge support for apple terminal if a PR was opened, but I do not intend to work on this as I do not use Terminal.app. It should be pretty straight forward to implement (most windowing support scripts are under 100 lines). Take a quick look at files in `rc/windowing/`. `detection.kak` is the entry point.
