### ISSUE TITLE
[BUG] Unmapped bindings are still visible in view mode

### ISSUE THREAD

**Issue by postsolar** [mawww/kakoune#5091]
### Version of Kakoune

master

### Reproducer

Run `kak -n`
In kakoune `: eval %sh{ printf 'map global view %s ""\n' v c t m b h j k l }`
Press v

### Outcome

![image](https://github.com/mawww/kakoune/assets/120750161/75f790a5-1855-4569-a8bf-d3107b2be968)

The screenshot is showing the view mode key hints with empty keybindings

### Expectations

Keys set to `""` would not be visible

**Comment by postsolar** [comment]
Related:
https://github.com/mawww/kakoune/pull/5041
https://github.com/mawww/kakoune/issues/4918

**Comment by krobelus** [comment]
can't reproduce. Are sure you are running latest master and your command didn't error?

**Comment by postsolar** [comment]
Yeah it looks like there's some issue with my package, I can't reproduce on freshly-downloaded master either. Sorry for the confusion!
