### ISSUE TITLE
[BUG] Incorrect computation of max_content_width for unframed info boxes

### ISSUE THREAD

**Issue by ftonneau** [mawww/kakoune#5106]
### Version of Kakoune

v2023.08.05-261-g80b231c3

### Reproducer

Execute this command:

    set-option buffer ui_options "terminal_info_max_width=2"

Then this one:

    info -style above AA

### Outcome

No info box shows up on the screen.

### Expectations

An info box with 'AA' as text should be visible on the screen.

### Additional information

This bug seems to be related to the computation of max_content_width in **terminal_ui.cc**, lines 1313-1315. On line 1314:

    (framed ? 4 : 2) -

Kakoune removes 4 chars from max_content_width in the case of info boxes with borders ("framed"), and removes 2 chars from max_content_width otherwise. Removing 4 chars from framed info boxes makes sense because there are indeed 4 additional chars to be accounted for (two on the left, two on the right). But why should we remove 2 chars from unframed info boxes? I think the correct computation should be:

    (framed ? 4 : 0) -

and indeed, replacing 2 by 0 in line 1314 gets rid of the bug. The 2-char wide info box ('AA') does show up on the screen.

**Comment by krobelus** [comment]
Makes a lot of sense. If I run

    kak src/terminal_ui.cc -e 'exec "/4 : 2<ret>"; git blame-jump'

I get an uninteresting change

```diff
-    const auto max_content_width = max_size.column - (framed ? 4 : 2) - (assisted ? m_assistant[0].column_length() : 0);
+    const auto max_content_width = (m_info_max_width > 0 ? std::min(max_size.column, m_info_max_width) : max_size.column) -
+                                   (framed ? 4 : 2) -
+                                   (assisted ? m_assistant[0].column_length() : 0);
```

running another `git blame-jump` on the deleted line, I get another
uninteresting commit, which only moved this line:


```diff
+    const auto max_content_width = max_size.column - (framed ? 4 : 2) - (assisted ? m_assistant[0].column_length() : 0);
 ...
-    const auto content_width = size.column - (framed ? 4 : 2) - (assisted ? m_assistant[0].column_length() : 0);
```

blaming the deleted line again, I get 34f48cc85 (Rework ncurses info display,
crop content when overlflowing, 2019-11-24) which added

```diff
+    const auto content_width = size.column - (framed ? 4 : 2) - (assisted ? m_assistant[0].column_length() : 0);
```

Since it's talking about overflowing, I tried an `info -style above`
command that overflows and it has the same bug; it fails to fill the last
two remaining columns - but that works fine when using a framed info box.

So there seems to be no reason for the current behavior, the fix sounds good.

**Comment by ftonneau** [comment]
Thanks -- can you take charge of replacing 2 by 0 on line 1314, or should I submit a pull request?

**Comment by krobelus** [comment]
On Tue, Feb 27, 2024 at 01:40:57AM -0800, François Tonneau wrote:
> Thanks -- can you take charge of replacing 2 by 0 on line 1314, or should I submit a pull request?

Sure, I'll queue it, thanks. FWIW, it is possible to send changes to the mailing list using `git send-email`, no need to make a PR.
