### ISSUE TITLE
How to imitate p and P behavior for clipboard paste

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#5115]
### Question

I have following mappings for the clipboard paste:
```kak
map global user p '<a-!> xsel --output --clipboard <ret>' -docstring 'System Clipboard - Paste After'
map global user P '!xsel --output --clipboard <ret>'      -docstring 'System Clipboard - Paste Before'
```

I have observed it works a little bit different than `p` and `P`.

Example text:
![image](https://github.com/mawww/kakoune/assets/26227737/630a0f64-363e-4cd8-952c-b64e404a9e4c)

If I yank whole second line and paste it using `p` or `P` I end with:
![image](https://github.com/mawww/kakoune/assets/26227737/17ecd5e8-d362-46bc-bd62-93685c174a6d)

However, if I paste it from the clipboard I end with:
![image](https://github.com/mawww/kakoune/assets/26227737/25f4e7f5-0706-402e-8613-d972aa8af74f)

It looks like `p` and `P` check whether the buffer ends with the newline, and paste it as a whole line.
On the other hand, my custom mappings simply paste the buffer where the cursor is.
Is it possible to achieve `p` and `P` behavior when pasting from the clipboard?

**Comment by Screwtapello** [comment]
> It looks like `p` and `P` check whether the buffer ends with the newline, and paste it as a whole line.

Correct, this is special behaviour for Kakoune's internal paste handling, which isn't applied to the output of commands like `!` and `<a-!>`. You can get around that by writing a wrapper command that loads the clipboard contents into the Kakoune clipboard register and using the regular `p` and `P` commands:

```kak
define-command paste-from-clipboard -params 1 %{
    # We save the " register because we don't want to clobber
    # the current Kakoune clipboard contents
    evaluate-commands -save-regs '"' %{
        # Set the " register to the output of this command
        set-register '"' %sh{
            xsel --output --clipboard
            # Like shell's $(),
            # %sh{} trims a trailing newline from its collected output,
            # so we add an extra newline for it to eat.
            echo
        }
        # Paste from the " register in the way we were asked
        execute-keys %arg{1}
    }
}

map global user -docstring "paste after" p ":paste-from-clipboard p<ret>"
map global user -docstring "paste before" P ":paste-from-clipboard P<ret>"
```

**Comment by m-kru** [comment]
Thanks @Screwtapello, you made my day.
