### ISSUE TITLE
[BUG] Documentation pages are missing since transition to posix make

### ISSUE THREAD

**Issue by lobre** [mawww/kakoune#5116]
### Version of Kakoune

master

### Reproducer

To make it reproducible, I have used docker.

```
# clone fresh kakoune repo
cd $(mktemp -d)
git clone https://github.com/mawww/kakoune.git
cd kakoune
git show # returns d299a7059e9becedfa0e15a6f15e5b24b762ce9e

# launch an alpine container
docker run --rm -it -v $(pwd):/kakoune --workdir /kakoune alpine ash

# install deps
apk add alpine-sdk
make debug=no
make PREFIX="/usr" debug=no install

# result
ls -l /usr/share/kak/doc/ # returns nothing
```

### Outcome

`/usr/share/kak/doc/` is empty, so no documentation is available in kakoune when doing `:doc`.

### Expectations

I was expecting all the doc pages to be here.

### Additional information

If I build kakoune at `e56ffd9d3659a4f74133e5d137bb56459d838cfd` (before POSIX make commits), I do see all pages from the `:doc`. Then incrementally building more recent ones, the build keeps failing until I try to build at `fix install of kakrc` (`64b3433905eeb33653ed617d61906ba68c686916`), it builds but I do not have all doc pages.

**Comment by mawww** [comment]
I have not been able to reproduce this here on either my local box or an alpine based server. I did in each case use a manual DESTDIR=... not to pollute the filesystem but I cannot see how that would impact the result.

I do not have docker available here to run exactly your instructions, but I wonder what could be the difference, could you show what `make -v` outputs in your container ?

**Comment by Screwtapello** [comment]
I thought I was not able to reproduce this on my system, but I was just running "make install" in a temporary directory and checking that the asciidoc files wound up in the place the makefile put them, which of course they did. I hadn't noticed the difference between `share/doc/kak/` and `share/kak/doc/`. Sure enough, I can reproduce the problem on my Debian system with the following:

    rm -rf /tmp/kakoune-install-test
    mkdir -p /tmp/kakoune-install-test
    make PREFIX=/tmp/kakoune-install-test/ install
    /tmp/kakoune-install-test/bin/kak -e 'exec :doc<space>'

Changing the definition of `docdir` is enough to fix it:

```diff
diff --git a/Makefile b/Makefile
index aa148807..eb8b8e13 100644
--- a/Makefile
+++ b/Makefile
@@ -38,7 +38,7 @@ DESTDIR = # root dir
 bindir = $(DESTDIR)$(PREFIX)/bin
 libexecdir = $(DESTDIR)$(PREFIX)/libexec/kak
 sharedir = $(DESTDIR)$(PREFIX)/share/kak
-docdir = $(DESTDIR)$(PREFIX)/share/doc/kak
+docdir = $(DESTDIR)$(PREFIX)/share/kak/doc
 mandir = $(DESTDIR)$(PREFIX)/share/man/man1
```

...but this use of `docdir` seems to be copied from [GNU Autotools conventions](https://www.gnu.org/software/automake/manual/html_node/Standard-Directory-Variables.html) for the benefit of Linux distros who already have highly automated systems for packaging "software that works like GNU Autotools", but evidently Kakoune is not designed to follow those conventions.

The official Debian package for Kakoune just puts the documentation files in `share/kak/doc`, though. I think `share/doc/kak` is expected to be for documentation that the tool can't use itself, like a README file.
I'd recommend installing the docs to `$(sharedir)/doc` and putting a comment above it pointing out that this is Kakoune's online help, not the content expected in `$(docdir)`.
