### ISSUE TITLE
[REQUEST] Rotate values from registers when pasting

### ISSUE THREAD

**Issue by jameschensmith** [mawww/kakoune#5135]
### Feature

When selection count is greater than count of values in the register, the last value is repeated. It would be really nice if the values rotated in a modulus-like fashion, going back to the first value. When the end is reached.

### Version

```
Kakoune v2023.08.05
```

### Usecase

This feature works very well with tables or {C,S,T}SVs, where you have something like the following:

```
a,b,c
1,2,3
4,5,6
7,8,9
```

And you'd like to write the values out linearly:

```
a: 1
b: 2
c: 3

a: 4
b: 5
c: 6

a: 7
b: 8
c: 9
```

This could be done with something like the following:

```
<a-l>S,<ret>"ad<a-d>2CZ<a-l>S,<ret>do<c-r>a:<space><c-r>"<esc>xd<a-,>2jo<esc><space>q
```

But that currently produces the following:

```
a: 1
b: 2
c: 3

c: 4
c: 5
c: 6

c: 7
c: 8
c: 9
```

**Comment by schragge** [comment]
I do see why this feature may be useful in principle, but not in this particular case. Copying the header line is easy:
```
xyPPCCs\w<ret>"ad<a-d>CCxs<ret>do<c-r>a:<space><esc>P<a-f>,bd1,d<space>q
```
However, I'd rather do it differently:
```
xd%<a-s>PCs\W<ret>r<ret><a-h><a-k>\d<ret>d_k<a-o><c-o>pk<a-J>i:<esc><space>q
```
I'd take a similar approach to solve the latest VimGolf challenge ([Truth Table to ModelSim](https://www.vimgolf.com/challenges/9v00660ce706000000000267)):
```
x`d%<a-s>PChdy%s<space>+<ret>R<a-h><a-k>\d<ret>d<a-d><c-o>_pk<a-j>iforce<space><end><space>@<space>0<esc>]p<a-,>"#p3+d<a-.><a-s>bP%arun<space>80<esc><space>q
```

**Comment by jameschensmith** [comment]
Wow, I really like your approach (the second example) to the usecase. That is fair that there are other ways to solve the problem, especially through an external tool. I may have to think of some other good usecases. But I'm also having a hard time finding good usecases for the current state of repeating the last value in the register. To me (subjective opinion alert), it would make more sense if the values kept rotating if the end of the list was hit.

**Comment by mawww** [comment]
I do not remember how I decided to just paste the last value for extra selections, I suspect I needed something that would work when pasting a single copied value to many selections and this is the first behaviour that came to mind. It seems to me that rotating would be a slightly more consistent behaviour than just duplicating the last entry, I am not sure it would make such a big difference in usability but it does feel "cleaner" so I am tempted to change that.

Any opinions on this ? Workflow that actually relies on the last entry being repeated ?

**Comment by ftonneau** [comment]
Rotating and last-value repetition give the same results when pasting 1 value over n slots. Rotating has the advantage of being potentially more useful than last-value repetition when pasting 2 values over n slots, 3 values over n slots, etc. 

As a matter of fact, rotating (called "**recycling**") is what the statistical language, **R**, always does when pasting vectors of different lengths. For example, pasting (1, 2) and (1, 2, 3, 4) horizontally gives a two-row matrix:

1 2 1 2
1 2 3 4

where (1, 2) is recycled up to 4 slots.

**Comment by schragge** [comment]
I was trying to find another use case for this beyond flattening/converting tabular data to vertical linear format, but was not very successful. VimGolf has the challenge [Label grid cells (6x6)](https://www.vimgolf.com/challenges/5d6aa7f288ff50000c123d49). Currently, I'd solve it like this:
```
5O<a-;>CABCDEF<esc>bs.<ret>6+y<a-+>Pll_i<space><esc><space>q
```
If selections were reused in the round-robin fashion, this could be rewritten differently. E.g.
```
5O<a-;>CABCDEF<esc>,bs.<ret>y5<a-C>Pll_i<space><esc><space>q
```
Perhaps, there are more efficient ways of doing this, but the only gain I see now is that `+` and `<a-+>` are more awkward to type than `,` and `<a-C>` (on American and French keyboard layouts, that is; on German keyboard `+` is located more handily).

And again, I'd rather do it in Bash, anyway:
```
printf %s\\n {A..F}{A..F}|pr -6Tts' '
```

**Comment by schragge** [comment]
Ah sorry, I've totally messed up. The correct "recycling" solution would be something like
```
cABCDEF<esc>QbS.<ret>i<ret><esc><a-C>Qy5p<a-o>q<a-j>gld<space>q
```
