### ISSUE TITLE
[QUESTION]: hook gives different results when the same keystrokes are splitted to two `execute-keys`. Why?

### ISSUE THREAD

**Issue by VKondakoff** [mawww/kakoune#5140]
### Question

Hi!

While experimenting with Kakoune I created a one-line hook to modify the text in `*scratch*` buffer which appears automatically when you start `kak` without parameters.
Here is the text: 
```
*** this is a *scratch* buffer which won't be automatically saved ***
*** use it for notes or open a file buffer with the :edit command ***
```
For testing purposes I'm replacing the `***` with `yyy`.
Here is the hook:
```
hook global BufCreate '^\*scratch\*$' %{
  execute-keys -buffer *scratch* '%s\*\*\*<ret>cyyy<esc>'
}
```
Everything works as expected. Here is the output:
<img width="820" alt="Снимок экрана 2024-04-11 в 00 47 23" src="https://github.com/mawww/kakoune/assets/230824/6f9108d6-2206-4aa3-a31b-f335c9685b86">

But if I split `execute-keys` into two lines, the output is different and wrong:
```
hook global BufCreate '^\*scratch\*$' %{
  execute-keys -buffer *scratch* '%s\*\*\*<ret>'
  execute-keys -buffer *scratch* 'cyyy<esc>'
}
```
Output:
<img width="820" alt="Снимок экрана 2024-04-11 в 00 49 55" src="https://github.com/mawww/kakoune/assets/230824/bbf7ba5b-f8c2-4217-b357-d3714ffe3ba5">

Why this happens?

**Comment by krobelus** [comment]
the `-buffer` switch makes it run in a draft context so selections etc. won't escape. See also clippy's comments on `:execute-keys`

**Comment by VKondakoff** [comment]
Got it. Thank you, closing the issue.
