### ISSUE TITLE
[QUESTION] Cursor position independent way to select word under the cursor

### ISSUE THREAD

**Issue by m-kru** [mawww/kakoune#5141]
### Question

What is the best/recommended way to select word under the cursor in a cursor position independent way? Usually I do `be` or `eb`. However, If cursor is at the first word letter, then `be` selects the previous word. On the other hand, when cursor is at the last word letter, then `eb` selects  the next word.  Is there any way to select word under the cursor in a cursor position independent way stroking no more than 2 keys?

**Comment by Delapouite** [comment]
What about using a text object such as "inner word" `<a-i>w`?
