### ISSUE TITLE
goto and view keybindings don't work properly when there is a wrap highlighter [BUG] 

### ISSUE THREAD

**Issue by QiBaobin** [mawww/kakoune#5146]
### Version of Kakoune

master branch

### Reproducer

run `:add-highlighter global/ wrap -word`, then open a file contains some very long lines.  Go to one of those line,
run `gc`, `gb`, `vc`, `vb` etc.

### Outcome

most of those key bindings don't work visually

### Expectations

wrap lines are treated like real lines for those modes?

### Additional information

Mac OSX, and use master branch.

**Comment by Screwtapello** [comment]
This is the same underlying problem as #3919 and #1517.
