### ISSUE TITLE
Center view when performing big jumps

### ISSUE THREAD

**Issue by doppioandante** [mawww/kakoune#515]
At the moment, commands like search, that could move the selection in a non visible region of the screen, display the selection either at the last or at the first line of the view when this happens.
I don't think this is very convenient, particularly while searching, because the context around the match is partially lost.

Just for showcase this is a simple patch that tries to center the search match, while keeping the most of the match visible.

``` Diff
diff --git a/src/normal.cc b/src/normal.cc
index 24f5e1c..d9114dd 100644
--- a/src/normal.cc
+++ b/src/normal.cc
@@ -31,6 +31,29 @@ enum class SelectMode
     Append,
 };

+void center_selection_view(Context& context, const Selection& sel)
+{
+    const auto dim = context.window().dimensions();
+    const auto pos = context.window().position();
+    // cursor is out of the window boundaries
+    if (abs(sel.cursor().line - pos.line) > dim.line)
+    {
+        const auto half = dim.line / 2_line;
+        const auto selLines = (sel.cursor() - sel.anchor()).line;
+        LineCount correction;
+        if (selLines > 0_line)
+        {
+            correction = std::max(0_line, selLines - half);
+        }
+        else
+        {
+            correction = std::min(0_line, half + selLines);
+        }
+
+        context.window().display_line_at(sel.cursor().line, half+correction);
+    }
+}
+
 template<SelectMode mode, typename T>
 void select(Context& context, T func)
 {
@@ -644,6 +667,11 @@ void search(Context& context, NormalParams params)
                          do {
                              select_next_match<direction, mode>(context.buffer(), context.selections(), ex);
                          } while (--c > 0);
+
+                         if (mode == SelectMode::Replace)
+                         {
+                             center_selection_view(context, context.selections().main());
+                         }
                      }
                  });
 }
@@ -659,6 +687,8 @@ void search_next(Context& context, NormalParams params)
         do {
             select_next_match<direction, mode>(context.buffer(), context.selections(), ex);
         } while (--params.count > 0);
+
+        center_selection_view(context, context.selections().main());
     }
     else
         throw runtime_error("no search pattern");
```

The problem looks subtle though, I wanted to hear your opinion.

**Comment by mawww** [comment]
I think you can get a nice behaviour already by setting the `scrolloff` option to something like 3,0 (you'll always have 3 lines margins around main selection).

**Comment by doppioandante** [comment]
What about an options that acts only when jumping?
The difference between a jump and a scroll is that in a scroll you can predict how the view reacts (e.g. pressing `j` at the bottom of the view scrolls down by one line).
For the same reasoning, I would have `/` only adapt the view when the word searched is found outside of the current view. This also makes looking at the screen more predictable, because you know that the search result is going to be at the center.
It seems difficult to me though to differentiate between the two cases (scroll/jump).

**Comment by dumblob** [comment]
Well, I'm using the `scrolloff` option and it feels fine when jumping (I use jumping a lot).

**Comment by lenormf** [comment]
I think this issue can be closed.

**Comment by doppioandante** [comment]
Well I still don't like the default behavior, but this looks like something very easy to do with a remapping.

**Comment by dumblob** [comment]
@doppioandante could you please then post here your solution?
