### ISSUE TITLE
[BUG] %val{buflist} does not produce quoted output by default

### ISSUE THREAD

**Issue by gknittl** [mawww/kakoune#5158]
### Version of Kakoune

v2022.10.31

### Reproducer

Doc error at https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc 
%val{buflist}

    quoted list of the names of currently-open buffers (as seen in %val{bufname})
should read
%val{buflist}

    list of the names of currently-open buffers (as seen in %val{bufname})

Quoting requires either echo -quoting or $kak_quoted_buflist as with any other expansion which could perhaps be added as a hint.

### Outcome

n/a

### Expectations

expect the docs are wrong, not the code

**Comment by krobelus** [comment]
good find, yeah the doc seems wrong here
