### ISSUE TITLE
Decide on what scripts should be auto-loaded by default

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#516]
Hi,

Let's trim the scripts currently loaded by default when no `autoload` directory has been created in the user's home directory. For that we need to decide what scripts should be taken out, and possibly come up with a checklist that would help decide if future scripts should be loaded by default.

**Comment by lenormf** [comment]
Here is my list of scripts I think should be moved out:
* `asciidoc.kak`
* `cabal.kak`
* `coffee.kak`
* `cucumber.kak`
* `dockerfile.kak`
* `exherbo.kak`
* `fish.kak`
* `grench.kak`
* `haml.kak`
* `jedi.kak`
* `julia.kak`
* `kickstart.kak`
* `ragel.kak`
* `sass.kak`
* `scss.kak`
* `tupfile.kak`
* `yaml.kak`
* `scala.kak`

This would leave the following scripts in the default installation:
* `autorestore.kak`
* `autowrap.kak`
* `c-family.kak`
* `clang.kak`
* `clojure.kak`
* `commenting.kak`
* `css.kak`
* `ctags.kak`
* `diff.kak`
* `dlang.kak`
* `etc.kak`
* `formatter.kak`
* `gas.kak`
* `git.kak`
* `git-tools.kak`
* `golang.kak`
* `grep.kak`
* `haskell.kak`
* `html.kak`
* `ini.kak`
* `java.kak`
* `javascript.kak`
* `json.kak`
* `kakrc.kak`
* `lisp.kak`
* `mail.kak`
* `makefile.kak`
* `make.kak`
* `man.kak`
* `markdown.kak`
* `mime.kak`
* `perl.kak`
* `python.kak`
* `ruby.kak`
* `rust.kak`
* `sh.kak`
* `tmux.kak`
* `x11.kak`

I'm going to assume that the former list is going to be moved to a `kakoune-extra` repository, although @mawww hasn't decided anything yet AFAIK (I'm all about that idea btw, as a replacement for `scripts.html` on `kakoune.org`).

Now about how to decide which scripts to integrate into the main repo: if the file implements a functionality of the editor (`grep.kak`, `make.kak` etc) or if the file adds support for something (language, tool etc) that is objectively used by a lot of people that don't all belong to the same "field" (i.e. `sass.kak` is used mostly by web devs vs `etc.kak` used by anybody who runs a UNIX), then it should probably be kept.

**Comment by doppioandante** [comment]
I have mixed feelings about those list. The rule you devised is subjective exactly in deciding what is objectively used by the most programmers. E.g. I use Julia much more than D, for sure mawww depends a lot on the exherbo.kakrc. The argument on etc vs sass is shaky because of the sheer number of web developers, and could apply to clojure and a few others in the second list.
The only categorical change I would have is keeping asciidoc.kakrc because it is used to dicument kakoune itself. 

I agree that the repo is the way to go, but then what's the criteria for accepting scripts there? For comparison, the vim ecosystem has a 1:1 correspondence between repository and "script". 
We should provide a rudimentary "plugin manager" before splitting out the current autoload folder.

**Comment by somasis** [comment]
I think it is better to just keep the autoload how it is right now. Users should make this decision.

**Comment by gokcehan** [comment]
Following the discussion from #561, I vote for a few changes to the list:

- `asciidoc.kak` should stay in main for the README file.
- `julia.kak` should stay in main.
- `jedi.kak` should stay in main.
- `clojure.kak`/`scala.kak` could be left for the extra although I'm fine either way. My observation is that people coding in java ecosystem usually rely on autocomplete and other advanced ide features to feel comfortable. Without these features (which I doubt will come anytime soon for these languages) I don't think people will be using kakoune for their editing.
- `x11-repl.kak`/`tmux-repl.kak` (#565) could be left for the extra although I'm fine either way. I would like to see these in the main but I understand that extra is more appropriate for these as they assume a specific workflow which may not suit everyone. So I think these could stay in extra for now.

**Comment by lenormf** [comment]
@gokcehan the changes you mentioned have already been applied, and pending pull requests will be merged in `core` by default and eventually moved to the `extra` respository if needed.

I'm closing this issue so as to not duplicate comments on the matter, post your remarks on the dedicated pull request #561.
