### ISSUE TITLE
[BUG] Files getting created when using autocomplete

### ISSUE THREAD

**Issue by atiedebee** [mawww/kakoune#5174]
### Version of Kakoune

v2023.08.05

### Reproducer

Open a file with kakoune, and use autocomplete. 
It happened most reliably when the autocomplete was succeeded by a space. I noticed it happened a lot when using scheme.

I have provided an asciinema file where I reproduced the issue:
[out.gz](https://github.com/mawww/kakoune/files/15282602/out.gz)

### Outcome

Random files get created. Sometimes they only contain the start of a word and are created in mass (I'll end up with files named `s st str stri strin` and `string`.

I've found that sometimes files with non-alphanumeric special characters get created (for example `{` and `\`), although I haven't reproduced that yet.

### Expectations

These files shouldn't be created.

### Additional information

I'm running OpenSUSE Leap 15.4.
I'm using kakoune from the github, which I have manually installed in `/usr/local/bin/`.

My config is located in `~/.config/kak/` and the plugins I use (apart from smarttab) don't have any hooks that I am aware of.
I have linked most of the actual files from autoload, apart from some programming languages I don't use and some windowing code. 

I am willing to provide my config files if needed.

**Comment by krobelus** [comment]
does it happen with `kak -n`? If not then it must be something in your config or similar

**Comment by atiedebee** [comment]
> does it happen with `kak -n`? If not then it must be something in your config or similar

No it didn't. I suspect it has something to do with the text completion of keywords, which aren't enabled without the config. I'll try disabling different parts of my config to narrow down the issue

**Comment by atiedebee** [comment]
I have found the issue. It turns out I misconfigured the `readtags` command.
I have now properly installed readtags and it all works fine.
