### ISSUE TITLE
[BUG] rendering issue in asciidoc with nested stars and backticks

### ISSUE THREAD

**Issue by lobre** [mawww/kakoune#5198]
### Version of Kakoune

80fcfebca8c62ace6cf2af9487784486af07d2d5

### Reproducer

From within Kakoune, open the execeval doc.

```
:doc execeval
```

Then, scroll to the `-buffer` flag explanation.

### Outcome

![image](https://github.com/mawww/kakoune/assets/3764103/fadbbaa9-2155-49c9-ad97-7b892524097f)

The asciidoc syntax is not rendered correctly. We see that the star disappeared at the beginning of the second sentence, and there is more bold than desired.

### Expectations

If I check the source code, here it is:

```
*-buffer* <names>::
    Execute in the context of each buffer specified in the comma separated
    list *names*. `*` can be used as a *name* to iterate over all non-debug
    buffers.
```

So it should render like below instead:

> `*` can be used as a **name**

### Additional information

I tried playing with the asciidoc playground there: https://asciidoc.org/#try

But I cannot find a way to have a star in a block quote, plus "name" rendered as bold at the end.

I have tried:

```
# The first star is ok, but *name* appears as is, enclosed by stars and without being bold
`\*` can be used as a *name*

# It works, except that I have a pound sign instead of the desired star at the beginning
`#` can be used as a *name*

# The whole line is bold, and the first and last stars are not present anymore
`*` can be used as a *name*
```

**Comment by arachsys** [comment]
The rendering in kak's help mode is done by a handful of regex matches in doc-render in `rc/tools/doc.kak` and it looks to me as if the contents of 'code quotes' aren't excluded properly from processing for things like bold and italic. The region highlighters used for normal syntax highlighting would be able to express this nicely because they can recurse, but as far as I know, they don't support removing the \`...\`, \*...\* or \_...\_ wrappers as the same point as highlighting them.

**Comment by arachsys** [comment]
I wonder if selections could be used in a cleverer way to solve this. Select all the \`code quotes\` and transform+highlight them. Then subtract those selections from the buffer before doing the transform+highlight for \*bold\* and \_italic\_? Something like that anyway.

**Comment by mawww** [comment]
It seems this instance can be solved by re-ordering the parsing of \`...` sequences before the ones of \*...* 

I am not convinced its a full fix, but it seems a bit better because it seems more reasonable to see a \* in a \`...` sequence than the opposite.

**Comment by arachsys** [comment]
Does that work to prevent this behaviour? Wouldn't
```
`*foo*`
```
still get rendered as bold foo inside a code block?

**Comment by mawww** [comment]
Yeah that would not work for the general case, to properly handle this we need more complex logic, its probably expressible but might get very ugly.

**Comment by mawww** [comment]
Closed without a proper fix, the doc renderer is not really intended to fully implement asciidoc and can require a bit of help.
