### ISSUE TITLE
Visible whitespaces

### ISSUE THREAD

**Issue by jkonecny12** [mawww/kakoune#520]
It would be nice to have command to show whitespace characters. Disabled by default of course.
It could be ``→`` for TAB and ``-`` for space.

Recently I found python2 source code where this too was mixed in the same source code. This feature is really must have to work with this kind of mess.

**Comment by ekie** [comment]
hello,
there is the ```:addhl show_whitespaces``` highlighter that does exactly what u desire, tho spaces are represented with ```·``` .

**Comment by jkonecny12** [comment]
Super, thank you much. I thought it's implemented already but I can't found it.
Is here some documentation I missed?

**Comment by haarts** [comment]
Perhaps someone stumbles over this and wonders, where indeed, that documentation is to be found. 

When you do `:addhl ` (note the space), you'll see all the currently available highlighers. 
There's also `:doc highlighters` but there the documentation re the `show_whitespaces` seems missing.
