### ISSUE TITLE
cygwin compilation error using gcc (windows10)

### ISSUE THREAD

**Issue by hcwanz** [mawww/kakoune#5206]
### Question

backtrace.opt.o: in function `Kakoune::Backtrace::desc() const'
backtrace.cc:62:(.text+0x9e): undefined reference to `__imp_SymFromAddr'
backtrace.cc:52:(.text+0x205): undefined reference to `__imp_SymInitialize'
collect2: error: ld returned 1 exit status
make: *** [Makefile:113: src/kak.opt] Error 1

**Comment by mawww** [comment]
Those symbols should be in the `dbghelp` library, which we try to add in Makefile at line 64, this would indicate the os variableat line 46 is not "Windows", could you show what `uname | sed 's/.*_NT.*/Windows/'` echoes on your system ? and what the full linking command line is ?

**Comment by hcwanz** [comment]
c++          -std=c++2a -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-sign-compare  -O3 -g3    -Wno-init-list-lifetime -Wno-stringop-overflow   -ldbghelp   src/alias_registry.opt.o .........

**Comment by hcwanz** [comment]
I can find the libdbghelp.a file in cygwin
At the same time, if I modify -ldbghelp, it will report an error. I think dbghelp is referenced normally
And I can find the definition of SymInitialize in libdbghelp.a using nm
![image](https://github.com/user-attachments/assets/3f056c74-d806-45ee-aa85-98a02f944d47)

**Comment by hcwanz** [comment]
> 这些符号应该在库中，我们尝试将其添加到 Makefile 的第 64 行，这表明第 46 行的 os 变量不是“Windows”，您能否显示系统上的回声？完整的链接命令行是什么？`dbghelp``uname | sed 's/.*_NT.*/Windows/'`

c++ -std=c++2a -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-sign-compare -O3 -g3 -Wno-init-list-lifetime -Wno-stringop-overflow -ldbghelp src/alias_registry.opt.o .........

$ uname
CYGWIN_NT-10.0-19045
$ uname | sed 's/._NT./Windows/'
Windows

I can find the libdbghelp.a file in cygwin
At the same time, if I modify -ldbghelp, it will report an error. I think dbghelp is referenced normally
And I can find the definition of SymInitialize in libdbghelp.a using nm
![image](https://github.com/user-attachments/assets/251693a2-7c84-4244-8b04-6d3833a47a88)

**Comment by hcwanz** [comment]
> Those symbols should be in the `dbghelp` library, which we try to add in Makefile at line 64, this would indicate the os variableat line 46 is not "Windows", could you show what `uname | sed 's/.*_NT.*/Windows/'` echoes on your system ? and what the full linking command line is ?


c++ -std=c++2a -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-sign-compare -O3 -g3 -Wno-init-list-lifetime -Wno-stringop-overflow -ldbghelp src/alias_registry.opt.o .........

$ uname
CYGWIN_NT-10.0-19045
$ uname | sed 's/._NT./Windows/'
Windows

I can find the libdbghelp.a file in cygwin
At the same time, if I modify -ldbghelp, it will report an error. I think dbghelp is referenced normally
And I can find the definition of SymInitialize in libdbghelp.a using nm
![image](https://github.com/user-attachments/assets/251693a2-7c84-4244-8b04-6d3833a47a88)

**Comment by hcwanz** [comment]
Compiled successfully in wsl2- alpine

**Comment by mawww** [comment]
Looks like we correcty detect Windows in cygwin and hence we should have `-ldbghelp` as part of the linker command line. What you posted is the compiler one, I am interested in the last command executed when you build, the one with `kak.opt` in it.

**Comment by hcwanz** [comment]
![image](https://github.com/user-attachments/assets/463460bb-afbc-48cc-9cdd-f4aca917e230)
[make.txt](https://github.com/user-attachments/files/16362236/make.txt)

**Comment by mawww** [comment]
Can you check with this patch, I suspect this is an ordering issue
```
From 2f562deebf0b3ffca230aeeb40e04a69cae05aad Mon Sep 17 00:00:00 2001
From: Maxime Coste <mawww@kakoune.org>
Date: Fri, 26 Jul 2024 22:54:51 +1000
Subject: [PATCH] Pass libs after object files to linker

---
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 6e995139..670a48ed 100644
--- a/Makefile
+++ b/Makefile
@@ -110,7 +110,7 @@ src/kak: src/kak$(tag)
 	ln -sf kak$(tag) $@
 
 src/kak$(tag): src/.version.o $(objects)
-	$(CXX) $(KAK_LDFLAGS) $(KAK_CXXFLAGS) $(KAK_LIBS) $(objects) src/.version.o -o $@
+	$(CXX) $(KAK_LDFLAGS) $(KAK_CXXFLAGS) $(objects) src/.version.o $(KAK_LIBS) -o $@
 
 deps = $(shell touch src/.version$(tag).d && find src -type f -name '.*$(tag).d') # Ensure we find one deps for FreeBSD make
 deps != touch src/.version$(tag).d && find src -type f -name '.*$(tag).d' # Ensure we find one deps for FreeBSD make
-- 
2.45.2
```

**Comment by hcwanz** [comment]
Compilation successful
![image](https://github.com/user-attachments/assets/22031807-1516-4c15-83ba-4f426caff056)
