### ISSUE TITLE
[REQUEST] Allow git-apply to stage/reverse hunk at cursor.

### ISSUE THREAD

**Issue by MarcCoquand** [mawww/kakoune#5225]
### Feature

Heya,

It would be awesome if `:git apply` also worked with hunks that are made visible with `:git show-diff` directly in the file you're editing. So if you run `:git apply --cached` while on a line that contains a hunk, that change gets staged, and if you run `:git apply --reverse`, that change is removed.

### Usecase

Today we have two awesome features in Kakoune, `:git apply` and `:git show-diff`. A user can enable `show-diff` to see hunks and jump to them directly while editing, which is extremely useful. Also, a user can apply hunks using `:git apply` on patches.

However, if a user tries to run `:git apply` when editing a file instead of looking at a diff, they are met with the confusing error: `'execute-keys': no matches found: '^diff'`. The reason is that `:git apply` operates only on patches. So in order for a user to stage a hunk, they need to first run `:git diff<ret>`, search for the change they made, and then run `:git apply<ret>`. It would be much faster for `:git apply` to be smart and apply the hunk where the cursor is currently located.

Scenario where this is useful:

1. You delete some obsolete code, or make a small minor change that should be its own commit
2. You run `:git apply --cache`. Alternatively a new command might be needed, like `:git stage-hunk`. The change is then moved to staging.
3. You run `:git commit -m "chore: Remove obsolete func"`. 

Another scenario is:

1. You notice some changes you made were unnecessary, you didn't need to change X function. 
2. You run `:git apply --reverse` while hovering the changed function and revert the changes you just made.

The end result is that the user can stay better in the flow, and makes creating atomic commits much much more ergonomic. When I used this feature in neovim, I found it immensely productive and useful.

**Comment by krobelus** [comment]
sounds reasonable. In my `kakdiff` branch I have a `diff-jump-reverse` command that jumps from file to diff location, that could be used as starting point.
