### ISSUE TITLE
Weird highlighters artifacts when searching after setting scrolloff

### ISSUE THREAD

**Issue by doppioandante** [mawww/kakoune#523]
To reproduce: 
* open a file, e.g. main.cc
* set window scrolloff 3,0
* search something
* begin scrolling down dumbly by keeping j pressed

Sometimes the whitespace at the beginning of a line becomes gray.

**Comment by lenormf** [comment]
This sounds oddly familiar, could you try following the steps given in #469 ? It might be completely unrelated, but you never know.

What terminal are you using (vte ?) ?

**Comment by doppioandante** [comment]
I tried to reproduce that but it worked fine.

I'm using gnome-terminal version 3.18.2, VTE-Version 0.42.1

**Comment by lenormf** [comment]
Couldn't reproduce with either ncurses 5 or 6, on termite.

**Comment by doppioandante** [comment]
I could reproduce with xterm, but the problem was there with terminator, that uses VTE.
It's either VTE itself or a weird interaction between ncurses and vte.
