### ISSUE TITLE
[BUG] hang at startup if pwd is git backed directory

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#5235]
### Version of Kakoune

Kakoune 2024.05.18-135-gb4b3ddae

### Reproducer

Opening any file inside git backed directory makes `kakoune` to hang up. Looks like culprit commit is fab8a7ef3cee5be6aeb074ecfc2cd47fdf4086f8.

### Outcome

![Screenshot from 2024-09-18 04-25-38](https://github.com/user-attachments/assets/2d0f1db1-a624-4e51-84d6-53b38eb40f4c)

Terminating `diff - ...` process unleashes `kakoune`.

### Expectations

No hang up.

### Additional information

My guess is that there is something wrong with `git diff` command, maybe because I use [delta](https://dandavison.github.io/delta/get-started.html) as git's pager instead of plain old `diff`.

**Comment by Screwtapello** [comment]
How have you configured git to use delta instead of its own diff tool?

**Comment by krobelus** [comment]
does this fix it:

```diff
diff --git a/rc/tools/git.kak b/rc/tools/git.kak
index c79c8ad9f..473d7a164 100644
--- a/rc/tools/git.kak
+++ b/rc/tools/git.kak
@@ -230,7 +230,7 @@ define-command -params 1.. \
         }"
         (
             set -o pipefail
-            git show "$rev:${buffile_relative}" |
+            git show --no-ext-diff "$rev:${buffile_relative}" |
                 diff - ${kak_response_fifo} "$@" |
                 sed -e "1c--- a/$buffile_relative" \
                     -e "2c+++ b/$buffile_relative"
```

**Comment by krobelus** [comment]
I don't think it's the pager because that one is turned off (try `git -c core.pager='echo BAD PAGER' show | cat`).
But it might be the diff tool (`git -c diff.tool=delta`)

**Comment by vbauerster** [comment]
> does this fix it:
> 
> ```diff
> diff --git a/rc/tools/git.kak b/rc/tools/git.kak
> index c79c8ad9f..473d7a164 100644
> --- a/rc/tools/git.kak
> +++ b/rc/tools/git.kak
> @@ -230,7 +230,7 @@ define-command -params 1.. \
>          }"
>          (
>              set -o pipefail
> -            git show "$rev:${buffile_relative}" |
> +            git show --no-ext-diff "$rev:${buffile_relative}" |
>                  diff - ${kak_response_fifo} "$@" |
>                  sed -e "1c--- a/$buffile_relative" \
>                      -e "2c+++ b/$buffile_relative"
> ```

No it doesn't, however if I remove line 202 then it's ok.

https://github.com/mawww/kakoune/blob/b4b3ddae0d93fbd652d1440f87541b81315838aa/rc/tools/git.kak#L202

**Comment by vbauerster** [comment]
> How have you configured git to use delta instead of its own diff tool? Following the instructions you linked to?

Yes, my git config is based of https://dandavison.github.io/delta/get-started.html

**Comment by krobelus** [comment]
Can't reproduce with the config from that page.
I need more information. Either give me a way to reproduce (try with `HOME=$(mktemp -d)` and then reduce to the offending config).
Or do some debugging. Apparently `${kak_response_fifo}` is never written to.

I'd maybe start with something like

```diff
diff --git a/rc/tools/git.kak b/rc/tools/git.kak
index 65009b041..ea60f3883 100644
--- a/rc/tools/git.kak
+++ b/rc/tools/git.kak
@@ -223,12 +223,13 @@ define-command -params 1.. \
     diff_buffer_against_rev() {
         rev=$1 # empty means index
         shift
+        set -x
         buffile_relative=${kak_buffile#"$(git rev-parse --show-toplevel)/"}
         echo >${kak_command_fifo} "evaluate-commands -save-regs | %{
             set-register | %{ cat >${kak_response_fifo} }
             execute-keys -client ${kak_client} -draft %{%<a-|><ret>}
-        }"
-        git show "$rev:${buffile_relative}" |
+        }" | tee /dev/stderr >${kak_command_fifo}
+        git show "$rev:${buffile_relative}" | tee /dev/stderr |
             diff - ${kak_response_fifo} "$@" |
             sed -e "1c--- a/$buffile_relative" \
                 -e "2c+++ b/$buffile_relative"
```

Are you on macOS? How are triggering it, are you calling `git show-diff`? Does it happen if you run it manually (not from a hook)?

**Comment by krobelus** [comment]
ok it's a problem with macOS `sed`. Will fix

**Comment by krobelus** [comment]
from the debug buffer:

```
 shell stderr: <<<
 sed: 1: "1c--- a/README.asciidoc
 ": command c expects \ followed by text
 >>>
```

**Comment by krobelus** [comment]
hmm fixed that error with

```diff
diff --git a/rc/tools/git.kak b/rc/tools/git.kak
index 65009b041..82262478b 100644
--- a/rc/tools/git.kak
+++ b/rc/tools/git.kak
@@ -230,8 +230,11 @@ define-command -params 1.. \
         }"
         git show "$rev:${buffile_relative}" |
             diff - ${kak_response_fifo} "$@" |
-            sed -e "1c--- a/$buffile_relative" \
-                -e "2c+++ b/$buffile_relative"
+            awk -v buffile_relative="$buffile_relative" '
+                NR == 1 { print "--- a/" buffile_relative }
+                NR == 2 { print "+++ b/" buffile_relative }
+                NR > 2
+            '
     }
 
     blame_toggle() {
```

but I still can't reproduce the hang you're seeing.

**Comment by krobelus** [comment]
ok I can reproduce with

```
hook global BufOpenFile ^[^*]+$ %{ evaluate-commands %sh{
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    for hook in WinCreate BufReload BufWritePost; do
      echo "hook buffer $hook %val{buffile} 'git show-diff'"
    done
  fi
}}
```

**Comment by vbauerster** [comment]
> And check the `*debug*` buffer (anything in there already?).

After terminating `diff` process I have following in `*debug*`:
```
error while waiting for shell: 1:1: 'evaluate-commands': 3:13: 'execute-keys': no such client: '-draft'
```

> Are you on macOS? How are triggering it, are you calling `git show-diff`? Does it happen if you run it manually (not from a hook)?

I'm not on macOS. If I manually do `git show-diff` it doesn't reproduce.

**Comment by vbauerster** [comment]
Removing following hook from my kakrc resolves the problem.
```kak
hook global BufOpenFile .* %{
    evaluate-commands %sh{
        [ "$kak_buffile" = "$kak_bufname" ] && exit 0
        directory="${kak_buffile%/*}"
        if git -C "$directory" rev-parse HEAD >/dev/null 2>/dev/null; then
          printf "hook buffer -group git-update-diff %s .* 'git update-diff'\n" WinCreate BufReload BufWritePost
        fi
    }
}
```

**Comment by krobelus** [comment]
right, a fix is here https://lists.sr.ht/~mawww/kakoune/%3C20240918145343.70170-2-aclopte@gmail.com%3E/raw
