### ISSUE TITLE
[BUG] :git diff shows escape sequences instead of colors

### ISSUE THREAD

**Issue by ygrek** [mawww/kakoune#5243]
### Version of Kakoune

2024.05.18

### Reproducer

`:git diff`

### Outcome

![2024-10-02_23-44](https://github.com/user-attachments/assets/c8c6d32e-f4a8-498e-bcf4-f2d4ca4b4b7f)

### Expectations

see + - lines, not escape sequences

### Additional information

this is xfce4-terminal 1.0.4 in xfce 4.18
TERM=xterm-color or xterm-256color same result
moved away ~/.config/kak directory, result is the same (modulo colors)
![2024-10-02_23-48](https://github.com/user-attachments/assets/8504983f-0e5d-4a8c-a817-e9753381a96f)
what can be the reason?

**Comment by Screwtapello** [comment]
Normally when `git diff` is run from another program, it turns off colour formatting, which Kakoune adds back in with its syntax highlighting rules.

Do you have git configured to use a custom diff tool, or have you configured it to always output colour?

**Comment by ygrek** [comment]
oh, good guess, you are right, I have `diff.external` set to patience diff (other `diff` options don't seem to matter).
so `:git diff --no-ext-diff` works
I would argue that `--no-ext-diff` should be a default, this patch fixes it for me :
```
diff --git a/rc/tools/git.kak b/rc/tools/git.kak
index cf2f7319..c1d0850f 100644
--- a/rc/tools/git.kak
+++ b/rc/tools/git.kak
@@ -154,10 +154,10 @@ define-command -params 1.. \
     }
 
     show_git_cmd_output() {
-        local filetype
+        local filetype default_opts
 
         case "$1" in
-           diff) filetype=git-diff ;;
+           diff) filetype=git-diff; default_opts="--no-ext-diff" ;;
            show) filetype=git-log ;;
            show-branch) filetype=git-show-branch ;;
            log)  filetype=git-log ;;
@@ -166,7 +166,7 @@ define-command -params 1.. \
         esac
         output=$(mktemp -d "${TMPDIR:-/tmp}"/kak-git.XXXXXXXX)/fifo
         mkfifo ${output}
-        ( trap - INT QUIT; git "$@" > ${output} 2>&1 & ) > /dev/null 2>&1 < /dev/null
+        ( trap - INT QUIT; git "$@" $default_opts > ${output} 2>&1 & ) > /dev/null 2>&1 < /dev/null
 
         printf %s "evaluate-commands -try-client '$kak_opt_docsclient' '
                   edit! -fifo ${output} *git*
```

**Comment by ygrek** [comment]
Thanks!

**Comment by krobelus** [comment]
I don't think that "git diff" should behave like "git diff --no-ext-diff".
If your external diff tool outputs terminal escape sequences despite the output being redirected that's a bug in that tool.
I'm failing to reproduce your problem; my

	git -c diff.external=patiencediff show|cat

works fine (i.e. it outputs no colors)

**Comment by ygrek** [comment]
ftr patdiff is from https://github.com/janestreet/patdiff
it also outputs extra delimiters to the point that <ret> cannot jump to the file, so it is not just about the color. But I get your point that their could be other diff helpers that behave the way kak expects and users would expect them to be picked up by default. Idk if it makes sense to add optional default options to :git diff.
ftr i workaround my issue with git-mode and `define-command -override -docstring "diff" git-mode-diff %{ git diff --no-ext-diff }` so i am ok with status quo.

**Comment by krobelus** [comment]
`patdiff` does word-level diffing; the Kakoune highlighters don't know about that.
So maybe install [kak-ansi](https://github.com/eraserhd/kak-ansi) and use something like `hook global BufCreate \*git\* ansi-enable`

**Comment by ygrek** [comment]
interesting, thanks!
