### ISSUE TITLE
ctags-search failing, when showing results with `menu -markup`

### ISSUE THREAD

**Issue by MrOneTwo** [mawww/kakoune#5244]
When running `ctags-search` I'm getting this error (looking for tag `device_get_binding`):

```
error running command 'evaluate-commands -client client0  %&ctags-search %@device_get_binding@&
': 1:1: 'evaluate-commands': 1:1: 'ctags-search': 1:23: 'evaluate-commands': 1:1: 'menu': unclosed face definition
```

Interestingly enough everything works well if I look for `DEVICE_DT_GET` tag.

The error goes away when I remove `-markup` from https://github.com/mawww/kakoune/blob/5e0f9a2ce0377d8b5aba71f2916a30257221bac8/rc/tools/ctags.kak#L63

Should that `markup` even be there? Why would that menu expect a string with markup?

**Comment by krobelus** [comment]
Probably there is a `{` which is interpreted as markup.
We can indeed remove the -markup switch since it's no longer used. Submitted a patch [here](https://lists.sr.ht/~mawww/kakoune/%3C20241005154204.1702502-1-aclopte@gmail.com%3E). Thanks!
