### ISSUE TITLE
[BUG] ":exec i≠" actually inserts '≀'

### ISSUE THREAD

**Issue by svmhdvn** [mawww/kakoune#5250]
### Version of Kakoune

v2024.05.18

### Reproducer

Run `:exec i≠`

### Outcome

The '≀' character (U+2240) gets inserted.

### Expectations

The '≠' character (U+2260) should be inserted instead.

### Additional information

Same observation on master branch.
Other similar unicode characters don't have any issues and work just fine.

**Comment by arrufat** [comment]
I just tried running this `kak -n -e "exec i≠"` and it works fine for me.
Can you try with running with `-n` flag, to avoid sourcing your config?

**Comment by svmhdvn** [comment]
I originally did test it with `kak -n` with the following configurations all failing:
* terminal: foot version 1.19.0 with TERM=foot and with font Comic Code
* terminal: foot version 1.19.0 with TERM=xterm-256color and with font Comic Code
* terminal: alacritty 0.13.2 with default out of the box config and default font

I'm on alpine linux edge, compiling kakoune with gcc and musl libc

**Comment by svmhdvn** [comment]
I just tested on both NixOS (glibc) and FreeBSD (it's own libc) and this bug *does not* reproduce there. Maybe it's an issue with musl libc?

**Comment by arachsys** [comment]
My machine is a Linux/musl box (head of Rich's git repo rather than a release, but I don't see any relevant changes since the last one), and I also can't reproduce this bug on my kakoune.

For what it's worth, I compile against llvm libc++ with clang. (Potentially might be some kind of libstdc++ vs libc++ interaction?)

**Comment by svmhdvn** [comment]
Only thing I can tell that I haven't mentioned is that I'm on a pinebook pro (aarch64) with my own custom kernel config, but I don't see how that could be relevant. I've tried many different terminal emulators and even SSH through tmux, same reproduction on this system with `kak -n`. I'll continue testing and find different (more popular) system configurations to reproduce on. And if not, I'll close the bug and do my own digging.

**Comment by Screwtapello** [comment]
Can you type `≠` normally? Can you paste it into Kakoune? Does `kak -n -e 'info ≠'` show the character correctly?

I notice that the two character are exactly one bit different. I wonder if some UTF-8 handling code somewhere has a typo, or is miscompiled on aarch64 or something.

**Comment by svmhdvn** [comment]
I don't exactly know how to type it in normally, but I can copy and paste it just fine into kakoune and it renders correctly on all fonts/terminals. I can also yank/put it from place to place using `d` and `p`. The only thing I can't do is insert it programmatically in, e.g. with `exec`. My use case is to bind that character to a user mapping.

**Comment by arachsys** [comment]
Bingo! I can reproduce it with `kak -n -e "exec i≠"` on aarch64 but not amd64.

**Comment by arachsys** [comment]
Yes, I've confirmed that hunch: `CXXFLAGS=-funsigned-char` is sufficient to break it on amd64, and `CXXFLAGS=-fsigned-char` gets it working correctly on arm32 and arm64.

**Comment by arachsys** [comment]
> Does `kak -n -e 'info ≠'` show the character correctly?

This is another interesting case: no it doesn't. The pop-up contains '�' instead with unsigned characters... but `kak -n -e 'info "≠"'` does work fine, as does `kak -n -e 'exec "i≠"'`!

**Comment by mawww** [comment]
Thanks for the investigation, was quite easy to fix on the unsigned-char issue was identified
