### ISSUE TITLE
[BUG] BufReadFifo hook parameter reports overlapping spans

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#5255]
### Version of Kakoune

2024.05.18-132-gdaa7e37e

### Reproducer

```
(echo a; sleep 1; echo b; sleep 1; echo c) |
    kak -n -e 'hook global BufReadFifo .* %{ echo -debug %val{hook_param} }; buffer *debug*'
```

### Outcome

The `*debug*` buffer reports:

```
1.1,1.2
1.2,2.2
2.2,3.2
```

### Expectations

The description of `BufReadFifo` in `:doc hooks` says:

> The hook param contains the range of text that was just inserted, in a format compatible with the select command.

I understand this to mean that the range covers exactly the characters just read from the FIFO. Since a character can't be read more than once from a FIFO, I would expect each character to be covered by exactly one range. However, the character at 1.2 appears in both the first and second events, while the character at 2.2 appears in both the second and third events. Instead, I would expect output like:

```
1.1,1.2
2.1,2.2
3.1,3.2
```

**Comment by krobelus** [comment]
Thanks, I had started working on this but didn't have a test, only a suspicion that something is wrong.
Namely the way `read_fifo()` juggles around the final `\n` to keep scrolling or not (depending on `edit -scroll`).
Given that this is so tricky, I hope we can get rid of this newline and simply implement autoscrolling via hooks or options.

**Comment by mawww** [comment]
Its going to be hard to have something as nice as just doing `ge` on a fifo buffer to have scrolling regardless of how we got into that buffer.

**Comment by krobelus** [comment]
true; we should maybe also make `gj` work, which currently only works if the last BufReadFifo had a trailing newline.

a related thing I broke is scrolling in stdin buffers. That should be solvable

**Comment by Screwtapello** [comment]
Commits 5d378fa3a5139ca7c075ddf1a533856f53943f73 and 658915086fc4883c45f1af98f1b37a01822e9feb worked nicely for me; I tested them and they worked nicely. However c3b01a3c9caf030a8c6f6dca56688aca57a9248e seems to have regressed things somewhat.

### Steps to reproduce:

1. Save the following as `fifo-chunk-log.kak`:

        declare-option range-specs last_fifo_chunk 1 1.1,1.1|

        hook global BufReadFifo .* %{
            # update-option buffer last_fifo_chunk

            echo -debug last chunk: %opt{last_fifo_chunk}
            echo -debug curr chunk: %val{timestamp} "%val{hook_param}|"

            set-option buffer last_fifo_chunk %val{timestamp} "%val{hook_param}|"
        }

1. Run Kakoune like this:

        (while true; do echo hello; sleep 1; done) | kak -n -e 'source fifo-chunk-log.kak; buffer *debug*'

1. This should produce messages in the *debug* buffer like this:

        last chunk: 1 1.1,1.1|
        curr chunk: 4 1.1,2.1|
        last chunk: 4 1.1,2.1|
        curr chunk: 5 2.1,3.1|
        last chunk: 5 2.1,3.1|
        curr chunk: 6 3.1,4.1|

    The "last chunk" value always exactly matches the "curr chunk" from the previous iteration, which is what you'd expect.
1. Uncomment the `update-option` command in the hook, and run Kakoune again.

### Expected results: 

Since BufReadFifo is fired when new data is added to the end of the buffer, the "last chunk" content shouldn't be affected, and the `update-option` command shouldn't change anything but the timestamp ID. With previous commit 658915086fc4883c45f1af98f1b37a01822e9feb this is what I get:

    last chunk: 3 1.1,1.1|
    curr chunk: 3 1.1,1.6|
    last chunk: 4 1.1,1.6|
    curr chunk: 4 2.1,2.6|
    last chunk: 5 2.1,2.6|
    curr chunk: 5 3.1,3.6|

### Actual results:

With the latest commit, I get the following:

    last chunk: 4 1.1,1.1|
    curr chunk: 4 1.1,2.1|
    last chunk: 5 1.1,3.1|
    curr chunk: 5 2.1,3.1|
    last chunk: 6 2.1,4.1|
    curr chunk: 6 3.1,4.1|

The timestamp *and* the coordinates have been updated; now the end of the "last chunk" matches the end of the "curr chunk" from the same timestamp, rather than the previous timestamp. This means that "last chunk" always completely overlaps "curr chunk" instead of being adjacent to it.

**Comment by krobelus** [comment]
that should be addressed by https://lists.sr.ht/~mawww/kakoune/%3C20241128122525.2910465-1-aclopte@gmail.com%3E
(also there was a tangentially related issue for stdin buffers)
