### ISSUE TITLE
[BUG] `echo -to-file` hangs for unopen fifo and cannot be aborted

### ISSUE THREAD

**Issue by losnappas** [mawww/kakoune#5256]
### Version of Kakoune

vgit-d86e505fad397251a8a618c545a7d78f43a70a34

### Reproducer

```sh
mkfifo test
kak
:echo -to-file test -end-of-line testing
```

### Outcome

Hangs until I do `cat test` in another terminal. Neither `c-c` nor `c-g` work inside kakoune, you're basically stuck unless you know which fifo to open.

### Expectations

I would expect `c-c` to cancel

### Additional information

- nixos
- on latest git master, was happening on previous commits too
- kakoune is running inside `foot` terminal

**Comment by losnappas** [comment]
https://github.com/mawww/kakoune/issues/1799 Kinda related, talks about how kakoune hangs on `write` to fifo. I don't think `echo -to-file` existed back when that was going.

**Comment by krobelus** [comment]
I started working on this; looks like it would require us to handle `ctrl-c` in the client code.
This kind of undermines the event loop. It's probably possible to do this targeted fix but it might be somewhat ugly.

This is mainly relevant when debugging plugins that are writing to fifos, right?
Note that you can always do `gdb -p $(pgrep kak)` to figure out which fifo yo uneed to read from.
