### ISSUE TITLE
Jumping back from a symbol's definition is broken

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#535]
Hi,

When looking up a symbol that is declared in the same buffer with the `:tag` command, the jump back to the previous location is off by several lines.

* select a symbol that was declared in the same buffer (macro, function etc)
* jump to the definition with the `:tag` command
* jump back with `^O`

Most likely a regression from a8d81e395b9ebfff7250f0d491520ed7c1a29543.

HTH.

**Comment by mawww** [comment]
Seems that is only broken when jumping to a tag in the current buffer, is that right ?

**Comment by lenormf** [comment]
Yes.
