### ISSUE TITLE
Issues with anchors in regex search

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#536]
Hi,

There seem to be some issues with anchors (`^`, `$`, `\b`, `\B`, `\<`, `\>`) in regex search, seemingly related to the fact that the search starts directly before/after the selection. 

For example:
searching `^.` (forward and backward) matches any character, even though it should only match the first character of a line.
searching `.$` (only backward) also matches any character.
searching `$` backward only matches the end of the first line of the buffer
searching `^` backward does not match anything

lookarounds probably also play into that issue, to make things more complicated.

On a related note, I would argue that empty matches from regex searches (e.g. `a?`, `^`, `(?=a)`, `a\K`) should be ignored, instead of selecting the first character after the position of the empty match.

**Comment by lenormf** [comment]
Using the case of `^`, this character will match the beginning of the selection as well as line starts, so the fact that `^.` selects the first character after the current selection is consistent.

You're mistaking searching and selecting, the patterns you gave should be used after issuing `%s`.

**Comment by occivink** [comment]
>^ will match the beginning of the selection
I'm assuming you mean beginning of the text after the selection, because this is what is happening now. 
Still, I'm not sure if this is desirable, because it would mean that `previous_match ∘ next_match ∘ next_match ≠ next_match`, which is not what I would expect.

>You're mistaking searching and selecting, the patterns you gave should be used after issuing %s.
This seems like two different use cases, and I can see value in both.

**Comment by lenormf** [comment]
I don't know, it seems normal to me but maybe that's because I'm used to using kak now.

**Comment by mawww** [comment]
Hello, I agree this is not ideal, the only fix I can think of is to always pass whole lines to the regex engine, and to filter afterwards, but its not very satisfying either. Not sure what can be done there.

**Comment by occivink** [comment]
I think setting the flags `regex_constants::match_not_bol` and `regex_constants::match_not_eol` depending on whether the search starts in the middle of the string would work. 

`regex_constants::match_not_null` also seems might be useful regarding the second point I raised.

**Comment by mawww** [comment]
good point, seems that would work fine

**Comment by mawww** [comment]
So that opens a new question, what to do with boost specific \A and \Z (also available as \` and \'), I let them for now, the best course of action would be to remove uses (to try to get closer to std::regex)

**Comment by occivink** [comment]
Well boost::regex also have [flags for these](http://www.boost.org/doc/libs/1_60_0/libs/regex/doc/html/boost_regex/ref/match_flag_type.html), namely `regex_constants::match_not_bob` and `regex_constants::match_not_eob`.
