### ISSUE TITLE
command doc dialog looks odd (terminal issue)

### ISSUE THREAD

**Issue by fbrau** [mawww/kakoune#539]
see pinture
![captura de pantalla_2015-12-25_16-22-51](https://cloud.githubusercontent.com/assets/8375315/12004193/f6aac5ba-ab3c-11e5-8c20-13fcde15e441.png)

**Comment by greduan** [comment]
What terminal do you have? What version? What Linux distro and what version? What shell? etc.

**Comment by mawww** [comment]
seems like you are not using an utf8 locale, whats your current locale ?

**Comment by fbrau** [comment]
yes. I am using LANG=C... sorry about that and thanks
