### ISSUE TITLE
build without boost-regex

### ISSUE THREAD

**Issue by fbrau** [mawww/kakoune#541]
Hi, my current system has a completly broken boost/icu setup. I dont wanna lose hours compiing it from 0.

Is there a replacement for boost-regex (?), maybe a light alternative.
I have read somewhere where you said kak shouldn't rely on boost or something like that...

Is there a way I could help to support another regex backend?

THIS IS NOT A BUG REPORT but, it is failing me due to this (dirty setup of my own):

`
/usr/lib64/gcc/x86_64-slackware-linux/4.9.3/../../../../lib64/libboost_regex.so: undefined reference to`icu_54::Locale::Locale(icu_54::Locale const&)'
/usr/lib64/gcc/x86_64-slackware-linux/4.9.3/../../../../lib64/libboost_regex.so: undefined reference to `icu_54::Locale::~Locale()'
/usr/lib64/gcc/x86_64-slackware-linux/4.9.3/../../../../lib64/libboost_regex.so: undefined reference to`u_digit_54'
`

**Comment by lenormf** [comment]
The project could drop the dependency to boost and use std::regex, unfortunately there's a lot of things that several scripts rely on currently in the implementation of boost::regex that are not available in std::regex (like backreferences, for example).

**Comment by mawww** [comment]
While its been a goal for a long time, replacing boost::regex is not easy, as we rely on various specific features that are not in std::regex, notably
* lookbehind
* `\K`
* `\h`

Some of these could be avoided, `\h` is `[ \t]', \K could be avoided by relying more on capture groups...

We dont have much choice besides std::regex and boost::regex as we want to search on non const char*, so we need an iterator based interface. That could be worked around if we decided that regex matching is now done line wise, as lines are available as single const char*, but multiline regex matching, although not used regularly, is still very handy when you need it.

It might be worth it to explore multi segment matching support in pcre, as libpcre is aguably more widely available than boost regex, but that would complexify the regex implementation.

So yeah, that boost dependency is unfortunate, I dont like it either, but fixing it is not an easy job.

**Comment by somasis** [comment]
I think pcre might be a good idea to explore, it's a lot smaller so it'd be more suitable for low-resource environments where I still want to have a nice editor.

**Comment by dumblob** [comment]
Or just use statically linked [Onigmo](https://github.com/k-takata/Onigmo) library, which is pretty stable, very fast and should support all the needs mentined above. It will require though writing a tiny iterator interface (because the library is in pure C), but that's IMHO a subtle issue.

**Comment by occivink** [comment]
I don't think you'd be able to do that, onigmo just takes a `char*` and iterates over that. The entire input has to be contiguous in memory. 
I had a look a while ago at pcre2 and it would be possible to make multi-line matching (even with lookbehinds and `\k`) work but it would also require a lot of plumbing and copying strings around in the case of such multi-line matches. I don't think getting UTF-8 correctness (which is the only benefit I see here, although I agree that's very important) is worth the increased complexity. 

Is there a chance to ever remove the reliance on lookbehinds without losing any feature?

**Comment by dumblob** [comment]
>I don't think you'd be able to do that, onigmo just takes a `char*` and iterates over that. The entire input has to be contiguous in memory.

Correct - Onigmo just flashed in my mind and I felt the need to immediately mention it without deeper thinking. Even though if we really need lookbehinds, we might also change the library to use a simple interface over the chunked text instead of `char*`.

>Is there a chance to ever remove the reliance on lookbehinds without losing any feature?

I second this question.

**Comment by mawww** [comment]
As far as I remember, their main use is to match string closers when we want to express a quote (or double quote) not preceded by a pair number of antislash.

**Comment by Delapouite** [comment]
`boost-regex` has been removed from the deps and replaced by a custom implementation. This issue can be closed.
