### ISSUE TITLE
Allow to delete word in command line (and maybe insert mode)

### ISSUE THREAD

**Issue by memeplex** [mawww/kakoune#543]
It is pretty common when editing in the command line to delete the last type word, i.e. an entire parameter for the current command. Currently there are word movements implemented for the command line but nothing like the usual shell `<c-w>` (moreover, `<c-w>` is bound to word movement which I find counterintuitive for a unix lifelong user). I suggest to add `<c-backspace>` (and maybe `<c-delete>` for symmetry).

Indeed deleting the last word is a usual requirement in insert mode too, because it's usually faster to retype the entire word than to correct some mispelling. But currently (AFAIK) it's too cumbersome to do than in kak, as it implies going out to normal mode and back, or alternatively pressing `<m-;>` twice for two one-shot normal commands.

**Comment by memeplex** [comment]
Btw as I'm unable to find a mailing list or irc channel for kakoune I want to add here that I'm pleased about your good taste for software and ui design (ui in the relevant sense, not fancy screens). You have selected you lego pieces with art and economy. Kudos.

**Comment by ekie** [comment]
hello, 
u can solve your need for deleting a word in insert mode with a mapping. Something like `:map global insert <c-w> <esc>bdi` .

you find the irc channel #kakoune on freenode.

**Comment by memeplex** [comment]
Thank you very much @ekie. I know I can write mappings, I was suggesting to add a builtin one because IMO it's a very frequent use case.

**Comment by lenormf** [comment]
The solution is indeed what was proposed by @ekie, this "issue" about shell shortcuts not being implemented in kakoune comes up regularly, you can read an answer to it in #334.

**Comment by lenormf** [comment]
I think this issue can be closed.

**Comment by mawww** [comment]
Yeah, its still a more general problem with command line editing, but this specific issue can be closed.
