### ISSUE TITLE
ui responsiveness  of   [n] and [alt-n] feels inconsistent 

### ISSUE THREAD

**Issue by fbrau** [mawww/kakoune#544]
if I type %sSOMETHING

then keep 'n' pressed, the cursor iterates over the matches ("gradually").

alt-n instead, doesn't. It just arrives at destiny.

**Comment by mawww** [comment]
Hello,

I am not sure which behaviour feels inconsistent to you, `n` will search forward for next match, `alt-n` will search backward. In my current tests it seems to work just fine. Can you elaborate ?

**Comment by fbrau** [comment]
I now see it was not about behaviour; I've found the editor peaking proccessor at 99%,
and that seemed like different ui bhaviour but It is actually a byproduct of overloading the
processor.

Anyways, in this case what I'm doing is:

``` 
kak commands.cc     (medium-sized src code file)

%sreg                      (giving like 96 selections)
``` 
Now, if i type 'n' the solution/effect Is done immeatly (including window scroll if necesary)
but, (in my laptop) if I type `<a-n>` solution takes about 1 second to process and the process
is seen using 99% of processor time (with top).

now if I press `<a-n>` and hold it takes a long time until the interface becomes responsive again,

**Comment by mawww** [comment]
I see, yeah reverse searching is very innefficient, so with a defaut (non optimized) build, and 96 selections, it can take some time, optimizing reverse search would be very nice, but it is tricky.

**Comment by occivink** [comment]
This can be closed
