### ISSUE TITLE
colorscheme command, "Bad sustitution" on complete

### ISSUE THREAD

**Issue by benoit-intrw** [mawww/kakoune#548]
Hello, 

While trying to reuse `-shell-completion` code from `colorscheme` command I notice that it always generate an error in debug windows:

```
shell stderr: <<<
/bin/sh: 2: /bin/sh: Bad substitution
>>>
```

I've tested on two computers, both of them running Debian Jessie.

I don't have `XDG_CONFIG_HOME` env variable but it seems taken into account in the source code.

I had neither `${localconfdir}/colors` directory but creating it doesn't change the behavior.

I'm not able to found the guilty part of the script, someone else is encountering this problem ?

Regards.

Benoît

**Comment by mawww** [comment]
Yeah, there was a non posix substitution `${1:0:${kak_pos_in_token}}`, that should be fixed now.
