### ISSUE TITLE
Add <a-S> to split selections on boundaries

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#550]

**Comment by mawww** [comment]
Whats the motivating use case for that feature ?

**Comment by alexherbo2** [comment]
You could select a `function` `end` block, split selections on boundaries then `'` and `<a-&>` to align. :)

It is used in scripts but works pretty well interactively.

**Comment by mawww** [comment]
isnt that better handled by user defined text objects ?

**Comment by alexherbo2** [comment]
I don’t think these features are related. :o

Once you get you block selection, you split at the begin and end of selection then run command alignment.  That way you can align `end` to its `function`, `else` to its `if`, etc.

It is just a convenience to `s` `\A|\Z` after all.

**Comment by nochiel** [comment]
+1 for this feature.  Use case (with the key mapping @alexherbo2 is proposing):

## Deleting parenthesis (or other matching pairs):  `|(foo)`
`mS\w+d` would become `m<a-S>d`

## Inserting markdown or simple matching pairs:
Given an arbitrary block of text, I often create a selection then want to surround it with \* or \`. Currently, this requires something like:`3Wi*<esc>a*` (where `i*<esc>a*` is mapped to a surround command that takes a parameter).

This would become: `3W<a-S>i*`.  

Is there already a simple way to do this?
