### ISSUE TITLE
Dynamic highlighters should be updated while searching to handle search highlighting

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#552]
Use case is with

```
addhl dynregex '%reg{/}' 0:search
```

**Comment by mawww** [comment]
What does not work for you exactly ?

**Comment by alexherbo2** [comment]
Searching for `foo`, `foo` is not highlighted until we move around the buffer.

**Comment by lenormf** [comment]
Note that using `*` does allow the highlighter to apply the face without having to move around to refresh the UI.

**Comment by Delapouite** [comment]
Same issue: https://github.com/mawww/kakoune/issues/1054

Fixed in https://github.com/mawww/kakoune/commit/25451ac1128feb0f1ce8c1adbf327964f6b8b086
