### ISSUE TITLE
autoload clarification

### ISSUE THREAD

**Issue by benoit-intrw** [mawww/kakoune#554]
Hello all,

I feel it is not obvious that once you have an `autoload` directory in your `.config/kak/` it is necessary to symlink files from `rc` dir. 

It's explained here https://github.com/mawww/kakoune#23-running but because highlighting works by default it took me a while to understand why it doesn't work any more once I created my config tree. Having an empty autoload dir is enough.

I see more the paragraph about autoload in the *Installing* section, after `make install` than in the *Running* one.

Sorry to not offer a "Pull request" but may be it's only me ;-)

**Comment by benoit-intrw** [comment]
Hum it seems I missed a second paragraph : https://github.com/mawww/kakoune#51-kakrc

So there is two approach once `kak/autoload` exist:

* Symlink all files from `/usr/local/share/kak/autoload` to user `kak/autoload`, advantage is it's possible to chose which file you want
* Symlink the `/usr/local/share/kak/autoload` directory into user `kak/autoload`, advantage new kak files are available automatically after `make install`

Do I miss something else ?

**Comment by ekie** [comment]
hello @benoit-intrw,

the point of this design decision/convention was to offer full flexibility for configurations in the userspace if the user decides to do so, while its still possible to finetune systemwide autoloading. ../share/kak/autoload is a symlink to to ../share/kak/rc which contains every single *.kak file thats ships with kakoune.
as soon as u decide to create $XDG_CONFIG_HOME/kak/autoload u are responsible for what will be loaded.
i would say, once u created $XDG_CONFIG_HOME/kak/autoload there is only one approach, and just autoload what u need in your setup. or, if u dont overwrite *.kak scripts that are shipped with kakoune just symlink ../share/kak/autoload to a subdir in $XDG_CONFIG_HOME/kak/autoload, it will load the scripts recursively in any subdirectory.

mayb the documentation can be improved in that regard. @mawww is always happy with feedback and contributions.

**Comment by mawww** [comment]
ekie is spot on, the goals was to provide both by default autoloading of provided scripts with a way to fine tune the ones the user actually wants. That was the simplest design we could come up with after long irc discussions.
