### ISSUE TITLE
Allow scripts to declare 'enum' or 'flags' variables

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#556]

**Comment by mawww** [comment]
Not sure its worth it, the current flags/enum implementation works well for c++ types, as it uses to type system directly. That would require quite a few changes for a small improvements.

**Comment by lenormf** [comment]
It would allow custom scripts (such as the one in #557) not to declare a simple `str` typed variable, and enforce combinations of values from a given set. I can work around that, but it feels wrong to have such a lose type when we're only interested in a couple words pipe-separated.
