### ISSUE TITLE
Support for snippets, auto-completion?

### ISSUE THREAD

**Issue by agauniyal** [mawww/kakoune#558]

**Comment by lenormf** [comment]
You'll have to give more details as to what you are expecting, because autocompletion is implemented (it just won't give you suggestions for some context-aware calls, like the arguments of a function), and you can insert any number of files into the current buffer already.

**Comment by agauniyal** [comment]
are there any plugins for autocompletion for different languages? does kakoune support some sort of snippets eg snipmate format?

**Comment by mawww** [comment]
Hello,

autocompletion plugins are availble for C/C++/ObjectiveC via the clang.kak script, and for python with the jedi.kak script. Other languages are still missing.

There is not snippets script yet, I´ll be happy to help implementing that, seeing what feature is needed in core.

**Comment by agauniyal** [comment]
Okay, I initially tried it with a cpp source file but only keywords contained in that file were being suggested instead of methods, data members etc. Is there something to do before clang.kak script gets working?

**Comment by mawww** [comment]
Hello,

you need to enable the completion, either manually with the `clang-enable-autocomplete` command, or by adding a hook that does that for you in your kakrc, something like

```
hook global WinSetOption filetype=(c|cpp) %{
    clang-enable-autocomplete 
}
```

**Comment by rennis250** [comment]
If one wanted to build on an already available external command, then there is this:

https://github.com/FabienArcellier/snip
