### ISSUE TITLE
The `itersel` flag will only make exec/eval iterate over the main selection

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#560]
Hi,

I might not have understand how `itersel` is supposed to work, but I was under the impression that it was supposed to be used to iterate over all the selections that were made previously, except I can't get that switch to do just that.

Example:
* select a few lines in a random file and split them with `<a-s>`
* use the following command: `:exec -draft -itersel ":echo %sh{ echo $kak_selection >&2 }<ret>"`
* check the debug buffer, only the main selection was echo'd

Am I missing something ?

**Comment by mawww** [comment]
use `:eval -draft -itersel 'echo %val{selection}'`, it works.

With your version, the %sh get evaluated when parsing the "..." string, so before we start iterating on selections. if you had used single quotes it probably would have worked (as the %sh evaluation would have been done while evaluating each `:echo` commands)

**Comment by lenormf** [comment]
Actually I didn't paste the code that revealed the issue in the first place, here it is:

```
def _test %{
    %sh{
        echo "[:${kak_selection}]" >&2
        echo "[${kak_selections}]" >&2
    }
}

exec -draft %{
    gg xX
    <a-s>
    :eval -draft -itersel _test<ret>
}
```

I'm expecting the output to be the first two lines of the buffer, in different bracket pairs, but I only have the last one displayed.

**Comment by mawww** [comment]
Hello,

Not sure what that is supposed to do,

I suspect you miss some "echo -debug" in the _test function.

Additionally, your `:eval -draft -itersel _test<ret>` needs to be quoted if you want to preserve the spaces.

**Comment by lenormf** [comment]
I want to be able to iterate over all the selections, using "$kak_selection" as iterator, and this `eval -draft -itersel` command as a "loop".

The output I expected from the code above was to have all the selections printed to the debug buffer, one after another, but it turns out that only the last one is printed (it's the main selection from the `xX <a-s>`).

I don't want to make a shell loop over "$kak_selections", so I thought this would do the job.

**Comment by mawww** [comment]
Ahhh, just understood whats going on...

your exec params are in a %{...} block, so exec gets a single string parameter, which contains the indent spaces.

That means between you <a-s> and `:eval` we run `<space>` many times, removing the multiple selections.

This does the trick:
```
exec -draft gg xX <a-s> ':eval -draft -itersel _test<ret>'
```

**Comment by lenormf** [comment]
Now I get it, thanks for the help (that was blocking me to finish #567).
