### ISSUE TITLE
`%sh{}` scopes have issues parsing the `}` character properly

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#568]
Hi,

It seems that the code parsing `%sh{}` scopes does not take any context into account, and will stop grabbing code as soon as a literal `}` character is encountered. This can be a problem when embedding the `}` character in contexts that kakoune shouldn't be reading into, e.g. strings or comments.

The following bit of code will spawn an error instead of executing the `}p` key combination.
```
%sh{echo "exec }p"}
```

The error: `p"}: no such command`.

A workaround for this is to generate the `}` character with a subshell, e.g. `printf '\x7D'` (maybe we need a `<leftbrace>`/`<rightbrace>` pair ?).

I haven't checked whether this issue is specific to `%sh{}` scopes.

**Comment by mawww** [comment]
Hello,

%sh, as all %... strings, can use any separator, you can use `%sh[...]`, `%sh(...)`, `%sh~...~`,... when the separator are nestable, it will respect the nesting in the subject string, so `%sh{ echo ${blah} }` will work fine.

In your case, use another separator for your %sh, you'll see that many kak script do that already.

**Comment by lenormf** [comment]
Pretty much all the punctuation signs I could think of are used on multiple occasions in my average `%sh{}` scope, so using `{}` is the most convenient solution. I'll stick to my workaround as it seems this is by design.
