### ISSUE TITLE
Setting tabstop to 0 will cause crash

### ISSUE THREAD

**Issue by sebsebmc** [mawww/kakoune#583]
Steps to reproduce:
Set indentwidth to non-zero value
set tabstop to zero
insert tab character -> SIGFPE

OR
set indentwidth to 0
set tabstop to 0 -> SIGFPE

**Comment by fbrau** [comment]
I can reproduce by setting tabstop to 0 and then press tab key

`
Received SIGFPE, exiting.
Pid: 32200
Callstack:
/home/suse/bin/kakoune-repo-hg/src/kak(_ZN7Kakoune9BacktraceC2Ev+0x18) [0x58dda8]
/home/suse/bin/kakoune-repo-hg/src/kak(_Z14signal_handleri+0x74) [0x5234d4]
/lib64/libc.so.6(+0x35120) [0x7f7b63041120]
/home/suse/bin/kakoune-repo-hg/src/kak(_ZN7Kakoune18expand_tabulationsERKNS_7ContextENS_14HighlightFlagsERNS_13DisplayBufferENS_11BufferRangeE+0x32d) [0x4bef4d]
/home/suse/bin/kakoune-repo-hg/src/kak(_ZN7Kakoune16HighlighterGroup9highlightERKNS_7ContextENS_14HighlightFlagsERNS_13DisplayBufferENS_11BufferRangeE+0x3b1) [0x4b8211]
/home/suse/bin/kakoune-repo-hg/src/kak(_ZN7Kakoune6Window36scroll_to_keep_selection_visible_ifnERKNS_7ContextE+0x359) [0x4da559]
/home/suse/bin/kakoune-repo-hg/src/kak(_ZN7Kakoune6Window21update_display_bufferERKNS_7ContextE+0x18c) [0x4dab1c]
/home/suse/bin/kakoune-repo-hg/src/kak(_ZN7Kakoune6Client10redraw_ifnEv+0xee) [0x51fc6e]
/home/suse/bin/kakoune-repo-hg/src/kak(_ZNK7Kakoune13ClientManager14redraw_clientsEv+0x24) [0x589ba4]

`
