### ISSUE TITLE
Hot reload of kak commands

### ISSUE THREAD

**Issue by nojhan** [mawww/kakoune#59]
Once a kak file has been sourced, it is impossible to source it a second time, because FunctionGroup does not allow to append previously declared FunctionAndId and throw an exception.

**Comment by spelufo** [comment]
I put this in a kak file to bind `,<ret>` to evaluate the main selection on kak files. Then you can do `%,<ret>` for the whole file.

```
hook global BufSetOption filetype=kak %{
	map buffer user <ret> ':eval %val{selection}<ret>'
}
```

**Comment by lenormf** [comment]
I think this issue can be closed.

**Comment by mawww** [comment]
Yeah, I think we dont have a nice solution for this problem without introducing lots of complexity, usually its just easier to execute the part of code you are working on with a `:<c-r>.<ret>`

**Comment by alexherbo2** [comment]
Why commands are not overridable by default?

**Comment by mawww** [comment]
Seemed safer to detect that a command was redeclared by default.

**Comment by alexherbo2** [comment]
Ouukii
