### ISSUE TITLE
Smart search does not work with certain codepoints.

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#595]
Hi,

Searching won't work with the `*` key when non-ascii unique codepoints are being used (`no matches found` error message).

How to reproduce the issue:
* open up `kak`, and input the same character on several lines (the codepoints have to be on their own on the line)
* hit `*` when the cursor is on one of the codepoints, then hit `n`
* the error message is displayed

Test file (the ellipsis will work, unlike the other two characters):
```
д
д
…
…
é
é
```

An issue with `\b` that's inserted into the smart pattern, maybe ?

**Comment by mawww** [comment]
yeah, that seems to be the case the problem seems to be in boost regex that does not handle the given codepoints as words.

**Comment by lenormf** [comment]
According to [this SO answer](https://stackoverflow.com/questions/4213800/is-there-something-like-a-counter-variable-in-regular-expression-replace/4214173#4214173), word boundaries don't work like I thought they would. They seem to be simple syntastic flavors around `\W\w` and `\w\W` more than anything else, so their behaviour might be the one expected as far as codepoints is concerned.

**Comment by mawww** [comment]
yeah \b is a zero width assertion equivalent to (?<\w)(?=\W)|(?<\W)(?=\w) the problem here is that boost regex seems to only consider bytes, so word codepoints are not recognized by \w. Not sure what a clean solution might be here

**Comment by lenormf** [comment]
I don't think this issue has been resolved yet, I can still reproduce the bug with the steps from the first message.
