### ISSUE TITLE
Remap colon

### ISSUE THREAD

**Issue by rennis250** [mawww/kakoune#598]
In Vim, I had re-mapped ':' to ';', so that I don't have to press shift every time I want to access the command window. Is it possible to do the same in Kakoune? At the moment, a simple map, like the following, does not appear to work:

```
map global normal ; : 
```

Best,
Rob

**Comment by ekie** [comment]
hello @rennis250,

`;` is a command seperator you would need to escape it. `map global normal \; :` should do the trick.

**Comment by rennis250** [comment]
Thanks. That did it! For those that are curious, the following also works, so that you can still set all selections back to a single cursor:
```
map global normal \; :
```
