### ISSUE TITLE
Abstract buffer shows part of the original buffer

### ISSUE THREAD

**Issue by jkonecny12** [mawww/kakoune#599]
Hello all.

I'm thinking if you can implement special abstract buffer which will be view to another buffer. Basically to extract few lines or specific parts from the original buffer and show them in a new kakoune buffer(s). When user then change the context in any of these buffers it will immediately do this change in every view and original buffer.

Is this doable at all?

**Comment by mawww** [comment]
whats your use case for that ?

As a first idea, that would more be on the window side (restrict the window to display only a certain line range of the bufffer) than with a special buffer type.

**Comment by jkonecny12** [comment]
Yeah it could be. I'm thinking of some general use-case mainly for plugins but not only for them.

When you have some code you may want to change 4 parts in one time and it could be cleaner when you see only the interesting parts.
For the plugins you can show user the part of the code where the bug is or something similar. 

Truth is I thought the buffers won't do the change immediately now. I should test it before, Kakoune is still surprising me :).

I'm still thinking that the window view restriction could be usable so this is valid but it's lower priority on the list now.

**Comment by lenormf** [comment]
>When you have some code you may want to change 4 parts in one time and it could be cleaner when you see only the interesting parts.

Vim has code folding for that one case. I don't know if there's anything else.

>For the plugins you can show user the part of the code where the bug is or something similar.

That sounds like a job for the range highlighter!

**Comment by jkonecny12** [comment]
OK you got me :D. If you think this is invalid request feel free to close it.
