### ISSUE TITLE
Make `:e` without any arguments open the `*scratch*` buffer

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#607]

**Comment by lenormf** [comment]
Let this issue be merely a suggestion, I will for my part be using a simple key mapping, as it's as simple as the argument-less `:e` suggested.

```
## shortcut to open a scratch buffer
map global user 's' %{:edit -scratch *scratch*<ret>}
```

**Comment by mawww** [comment]
I dont think thats a good default as it wont mirror `:e!` that reloads the current buffer.
