### ISSUE TITLE
add BufChange hook

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#611]

**Comment by lenormf** [comment]
Wouldn't a more informative title be "add shebang support" :) ?

**Comment by mawww** [comment]
I would need a pretty good use case for that, it is tempting but requires quite a refactoring if we want to have access to the current context.

So for now, I wont implement it, it adds complexity and does not have a good use case attached.

**Comment by lenormf** [comment]
Hold on, what kind of refactoring do you have in mind ? I thought this issue was about detected shebangs in extension-less files, which would basically be a `x` followed by a regex to detected which interpreter is being called ?
