### ISSUE TITLE
tmux-send-text doesn't work over a remote connection

### ISSUE THREAD

**Issue by rennis250** [mawww/kakoune#615]
Over a remote connection, using development tmux on Ubuntu 14.04LTS and a version of kakoune just built a few days ago, I can open a tmux-repl window, but selected text is not sent to that window when I run either the send-text or tmux-send-text commands. It works just fine when everything is run locally.

Best,
Rob

**Comment by mawww** [comment]
Not sure I get what the setup is, can you precise which processes are running on which machines ?

**Comment by rennis250** [comment]
I am working on my laptop, but have access to an Ubuntu 14.04LTS machine. I log in via SSH and start the following processes:

- zsh
- tmux
- kakoune

Then, I use the tmux-repl command to open a repl pane, which works successfully. However, when I select text and then issue the tmux-send-text command, nothing is sent to the repl pane.

**Comment by lenormf** [comment]
Sorry for the late response @rennis250. This issue stems from the fact that your server is probably using an old version of `tmux`, the plugin was made with `tmux 2.x` in mind -or so it seems. I don't think it'd be worth it for the project to start handling backward-compatibility, so the solutions that you have left are:
* upgrade `tmux` to a `2.x` version
* fork the `tmux-repl.kak` script to add support for older `tmux` versions

HTH.
