### ISSUE TITLE
Select portion of completed command instead of just expanding

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#617]
Taking `foobar`, `foobaz` and `fooqux` commands.

Typing `:foo` then pressing `tab` twice will expand and select `baz`.

```
:foo【baz】
```

Pressing `backspace` or `delete` will remove / undo expansion.

**Comment by alexherbo2** [comment]
The reason behind the issue is

 1. The token being completed is not visible when it expands.
 2. There is no command to cancel completion.

I discuss with @mawww on [IRC](irc://chat.freenode.net/kakoune) and it was proposed that `<c-c>` to cancel completion.

**Comment by lenormf** [comment]
This seems to be a completely different behavior than what's implemented already, why not have both ? Since obviously some people will prefer one over the other, it'd be too bad to sack either group.

**Comment by mawww** [comment]
The more I think of this, the less it makes sense with the current, non prefix based completion system.
