### ISSUE TITLE
Kakoune suddenly slow

### ISSUE THREAD

**Issue by rennis250** [mawww/kakoune#627]
I don't know if it is just me or something to do with being on a Mac, but sometime in the past week or so, some change was made that has rendered Kakoune rather slow on my machine. I'll try doing a git bisect to see when it happened.

**Comment by rennis250** [comment]
I guess I was daydreaming all this time. It now appears to run slowly even on the earliest commit that I ever tried. To be clear, by "slowly", I mean that I can notice the time it takes for the cursor to move from one selection to the next, especially in comparison to cursor movement in vim.

**Comment by mawww** [comment]
Whenever you see that again, can you try running with `kak -n` to see if its script related. Also, you can use the `set global debug profile` command to have some timings written in the debug buffer. (To go even a little further, if the slow ness seems to come from some shell exectution, you can `set global debug profile|shell` to also get the actual shell commands printed in the debug buffer).

**Comment by lenormf** [comment]
Do you have a big `modelinefmt` ?

**Comment by rennis250** [comment]
@mawww Thanks, I will do that in the future.

@lenormf No, I haven't changed the modelinefmt from the default.
