### ISSUE TITLE
User commands broken?

### ISSUE THREAD

**Issue by rennis250** [mawww/kakoune#629]
I don't know why, but whenever I try to run a command with a user mapping, it prints out the user mapping to the buffer and doesn't run it. For instance, the following mapping is in .kakrc:

```
map global user n ':eval %{buffernext}<ret>'
```

When I type ',n', into an empty kak buffer, the following text is inserted:

```
 %{buffernext}
```

No command is actually run, even if, in this case, multiple buffer windows are open.

Best,
Rob

**Comment by mawww** [comment]
Cannot reproduce that here, is the command written plainly in the kakrc ? or wrapped in anything ?

**Comment by rennis250** [comment]
Listed below are the full contents of my kakrc. When that is the only line, the error does not occur. I briefly tested kak on ArchLinux, and I believe the same problem occurred there, as well. Perhaps it has something to do with all of the keyboard mappings I have made? I use a Colemak keyboard layout and this selection of mappings makes using the editor much easier for me.

```
colorscheme github

map global normal n j
map global normal N J
map global normal j n
map global normal J N
map global normal e k
map global normal E K
map global normal k e
map global normal K E
map global normal i l
map global normal I L
map global normal l i
map global normal L I
map global normal \; :
map global normal : \;

map global goto n j
map global goto N J
map global goto j n
map global goto J N
map global goto e k
map global goto E K
map global goto k e
map global goto K E
map global goto i l
map global goto I L
map global goto l i
map global goto L I

map global view n j
map global view N J
map global view j n
map global view J N
map global view e k
map global view E K
map global view k e
map global view K E
map global view i l
map global view I L
map global view l i
map global view L I

map global menu n j
map global menu N J
map global menu j n
map global menu J N
map global menu e k
map global menu E K
map global menu k e
map global menu K E

set global scrolloff 2,2
set global BOM utf8
set global incsearch true
set global grepcmd pt\ -fHn
set global formatcmd par

hook global WinSetOption filetype=* ctags-enable-autoinfo
hook global WinSetOption filetype=(c|cpp) %{ clang-enable-autocomplete; clang-enable-diagnostics }
hook global WinCreate .* %{addhl number_lines}
#hook global WinCreate .* %{addhl show_whitespaces}
hook global WinCreate .* %{set global indentwidth 4}
hook global WinCreate .* %{set global tabstop 4}

# Add autowrap to 72 characters in git-commit
hook -group GitWrapper global WinSetOption filetype=git-commit %{
    set buffer autowrap_column 72
    autowrap-enable
}

hook -group PythonJediAutostart global WinSetOption filetype=python %{
    jedi-enable-autocomplete
}

hook global WinSetOption filetype=(?!python).* %{
    jedi-disable-autocomplete
}

map global user n ':eval %{buffernext}<ret>'
map global user b ':eval %{bufferprev}<ret>'

# yank and paste to/from external clipboard
map global user y '<a-|>pbcopy<ret>:echo -color Information "Yanked to clipboard"<ret>'
map global user p '<a-!>pbpaste<ret>:echo -color Information "Pasted from clipboard"<ret>'

# yank to system clipboard always
hook global NormalKey y|d|c %{ nop %sh{
   echo "$kak_selection" | pbcopy
}}

# show all trailing whispaces red
hook -group TrailingWhitespaces global WinCreate .* %{
    addhl regex '\h+$' 0:default,red
}

# select all occurrences in this buffer
map global user a '*%s<c-/><ret>'

def -docstring 'invoke fzf to open a file' \
  fzf-file %{ %sh{
    if [ -z "$TMUX" ]; then
      echo echo only works inside tmux
    else
      FILE=`pt -l -g "" | fzf-tmux -d 15`
      if [ -n "$FILE" ]; then
        echo "eval -client '$kak_client' 'edit ${FILE}'" | kak -p ${kak_session}
      fi
    fi
}}

def -docstring 'invoke fzf to select a buffer' \
  fzf-buffer %{ %sh{
    if [ -z "$TMUX" ]; then
      echo echo only works inside tmux
    else
      BUFFER=`echo ${kak_buflist} | tr : '\n' | fzf-tmux -d 15`
      if [ -n "$BUFFER" ]; then
        echo "eval -client '$kak_client' 'buffer ${BUFFER}'" | kak -p ${kak_session}
      fi
    fi
}}

map global user f :fzf-file<ret>
map global user b :fzf-buffer<ret>
```

**Comment by lenormf** [comment]
You mapped `:` to `;`, so you need to take that into account in your following key mappings. Changing `:bufferprev` to `;bufferprev` did the trick for me, with your configuration.

Another thing:
```
hook global WinSetOption filetype=* ctags-enable-autoinfo
```

The `*` is a repeat operator in the current regex engine, I think what you want is `.*` or `.+`.

**Comment by mawww** [comment]
User keymaps should not respect other keymaps IMHO (as in general, keymaps do not use mapping recursively), I'll have a fix for that.

**Comment by rennis250** [comment]
Thanks for the tips! @mawww, unfortunately, that change hasn't fixed the problem. I still need to use @lenormf's approach of replacing ":" with ";" in each of the user mappings. I would happily help out with the coding, but I know nothing about C++.

**Comment by mawww** [comment]
@rennis250 That is strange, I just tested again with your kakrc, and the `,n` binding does correctly cycle through the buffers.

**Comment by lenormf** [comment]
Yea it works here as well, maybe there are two `kak` binaries in his `$PATH`, and the old one gets picked first ?

Anyway, it's much more convenient now, thanks for the fix.

**Comment by rennis250** [comment]
@lenormf is right. It appears Homebrew is grabbing the latest commit and building but not putting the executable in the right spot or something. I will double check this. Sorry for the noise and thanks again for the fix!
