### ISSUE TITLE
The `-f` option arbitrarily adds newlines in CLI mode

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#633]
Hi,

Running the following command inserts `abc` into a new buffer, and everything goes as expected:
```
printf 'abc' | kak
```

However, the following commands will respectively one and two newline characters after `abc`:
```
printf 'abc' | kak -f '' # xxd: 6162 630a
printf 'abc' | kak -f '~' # xxd: 4142 430a 0a
```

I expected the above commands to return `abc` and `ABC` without any trailing newline character, which is precisely what happens when no filter is passed to the `-f` option.

**Comment by mawww** [comment]
Actually that is not specific to the `-f` but a problem with the current buffer implementation: Buffer invariant is that the buffer is never empty, it at least contains a single empty line, but that does not work well when we do a replacement at the end of the buffer, and an additional end of line appears.

**Comment by lenormf** [comment]
Yes, I understand why a newline would be added automatically to the end of the buffer, however the uppercase command should not add one after the text.

**Comment by mawww** [comment]
Definitely, what I meant is that this is a bigger bug than just something happening with `-f` and I know the cause of the bug, however we need some refactoring to be able to fix that, the basic problem is that at the moment, you can only insert/erase from a buffer, replacing (with `R`, or `|` or `~` or many other commands) is handled by erasing then inserting, but if you erase the last eol, the buffer will automatically reinsert it, and if the following insert had a `\n` at the end (supposed to restore the erased `\n`), we end up with a spurious `\n`. I will look into that, one solution would be to add a 'replace' method to the buffer, where it can check by itself if it needs to insert a new `\n` or if the whole replace operation will maintain the buffer invariant.

**Comment by lenormf** [comment]
OK I understand now, thanks for the explanation.
