### ISSUE TITLE
Fast file finder?

### ISSUE THREAD

**Issue by perpen** [mawww/kakoune#655]
First of all, I love kakoune! I have only been using it for one day so it may still be just a fling, but it's looking good. I really love the %sh construct, what a refreshing change from viml (although it can get a bit meta-confusing).

One feature I'm really missing from vim is an interactive search for a file under the current dir hierarchy, where each new character typed in filters the list of files in realtime, a la [ctrlp](https://github.com/ctrlpvim/ctrlp.vim) or [Unite](https://github.com/Shougo/unite.vim).
I imagined it must have been done already but I couldn't find anything similar in the provided rc files.

Ideally I would invoke the file search from the command mode, similarly to the completion you get for `:edit`, but I don't see a way to do this without modifying the actual c++ source to provide an alternative to commands.cc/filename_completer(). Am I correct?

Edit:
I just found `-shell-completion` and wrote this:
```
def finder -params 1 -shell-completion %{
    find . -type f | grep "$@"
} -docstring "Finds file" %{
    edit %arg{@}
}
```
This is actually not too bad and I will use that for now, replacing the grep call with a fuzzier filter, but I would still prefer not having to type the tab key to see completions.

**Comment by FranzSkuffka** [comment]
hey there, you can use `fasd -f. That's the way I do it.

last section:
https://github.com/mawww/kakoune/wiki/Getting-Started

**Comment by Delapouite** [comment]
Here are some thoughts about `fzf` https://github.com/mawww/kakoune/issues/383

**Comment by mawww** [comment]
WIP is the -shell-candidates completion, where we run the shell once to gather the candidates, then filter them using Kakoune built-in fuzzy matcher.

It does not yet work correctly as it does not reset the candidates between different "completion sessions" (that is, when you reuse the command later, you'll always get the set of completions of the first try to used the command). But that should hopefully allow to define a new user command that forwards to edit, but uses find or ag to get the whole list of candidates.

**Comment by lenormf** [comment]
Save yourself a process and pass `-iname` or `-name` to `find`:
```
find -type f -name "$@"
```

**Comment by perpen** [comment]
Thanks all for your suggestions.
I disabled the test `if (token != token_to_complete)` in the `shell-candidates` handling block so the shell script is always run, and the builtin fuzzy matcher works well enough.
I don't understand this `if` condition actually, couldn't the decision whether to cache anything resource-intensive be left to the shell script itself?

**Comment by mawww** [comment]
Hi,

The use case for that was matching tags, which I was trying on big tag files (linux source code, 400M tag file). In that case just reading the tag file is slow, and, unfortunately, filtering it is slow as well. That is why shell-candidates was designed around running the shell script only once.

**Comment by mawww** [comment]
@perpen the latest version should correctly update the candidates everytime you restart a completion session, so the commit you maintain should not be needed anymore. Could you try with the current code, and if thats working for you, we can close that issue.

By the way, for future reference, you can create a 'find' command to edit a file, that will use kakoune builtin fuzzy matcher on all files in the current directory with:

```
def find -params 1 -shell-candidates %{ find . -type f } %{ edit %arg{1} }
```

**Comment by perpen** [comment]
Works great without hacks now, thanks @mawww
