### ISSUE TITLE
User interface lags when using a `modelinefmt` that takes a while to return info

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#657]
Hi,

I use the following "widgets" for the modeline (they're all concatenated to one another and added to the `modelinefmt` option):
```
            ## cursor coordinates in the buffer
            "%val{cursor_line}:%val{cursor_char_column}"
            ## filetype of the buffer detected by kak
            "%opt{filetype}"
            ## name of the buffer
            "%val{bufname}"
            ## current git branch, or <none>
            "%sh{
                branch=\$(cd \$(readlink -e \$(dirname \${kak_bufname})) && git rev-parse --abbrev-ref HEAD 2>/dev/null)
                test -n \"\${branch}\" && echo -n \"\${branch}\"
            }"
```

The issue is that the last widget spawns several processes. And when they take too much time to exit to let kakoune render the modeline, the UI isn't updated on the buffer.

Example: after hitting `vt`, sometimes all I can see in the window is the `autoinfo` menu that lists the keys available after hitting `v`. I have to hit another key (i.e. `<esc>`) to force the UI to be redrawn, and see that the changes have indeed been taken into account, they just haven't been rendered.

It happens with anything from inserting data into the buffer, to changing the view, basically anything that changes the main view. It doesn't happen when I remove the process-heavy widget from the modeline though.

Thanks.

**Comment by mawww** [comment]
Hi,

The modeline is reevaluated on every redraw, Kakoune has no way to know if it needs to update it, or not. If evaluating the modeline is slow, there are plenty of ways to fix that. One solution in the case you show is the add a str option 'modeline-git-branch', replace the %sh{...} by %opt{modeline-git-branch}, and update modeline-git-branch externally, potentially in an async way (launched on NormalIdle for example).

**Comment by lenormf** [comment]
Why not compile the `modelinefmt` option asynchronously, instead of making the user do it itself ?

**Comment by mawww** [comment]
Well, for a few reasons, first for simplicity, for the use case you describe we would need to do the update in a separate thread, so basically put in place threading support in Kakoune which will add loads of complexity all around the place. Second you probably want things like `"%val{cursor_line}:%val{cursor_char_column}"` to be eagerly updated, not having any delay there. Kakoune cannot really guess if a %sh{...} is going to be fast or slow either. Seems simpler to let the user, who can have an idea of the speed of his commands, make the call.

**Comment by lenormf** [comment]
That sounds reasonable. Here's what I've changed to my config, for documentation purposes:
```
## customize the status bar
hook global BufOpen .*/?[^*].+ %{
    %sh{
        function add_hook_on_idle {
            echo "hook global NormalIdle .* %{ $@ }"
        }

        tools=(
            ## cursor coordinates in the buffer
            "%val{cursor_line}:%val{cursor_char_column}"
            ## filetype of the buffer detected by kak
            "%opt{filetype}"
            ## name of the buffer
            "%val{bufname}"
        )
        fmt_line=""

        ## current git branch
        if which git 1>/dev/null; then
            echo "decl str modeline-git-branch"
            tools[${#tools[@]}]="%opt{modeline-git-branch}"
            add_hook_on_idle "%sh{
                branch=\$(cd \$(readlink -e \$(dirname \${kak_bufname})) && git rev-parse --abbrev-ref HEAD 2>/dev/null)
                test -n \"\${branch}\" && echo \"set global modeline-git-branch '\${branch}'\"
            }"
        fi

        for t in "${tools[@]}"; do
            test -z "${t}" && continue
            test -n "${fmt_line}" && fmt_line="${t} ${fmt_line}" || fmt_line="${t}"
        done

        echo set global modelinefmt "'${fmt_line}'"
    }
}
```
