### ISSUE TITLE
Handle external reads on stdin (sudo etc)

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#660]
Hi,

It'd be great if kakoune could handle input reads from external commands, called by commands iniated from kakoune.

Example: `:nop %sh{sudo touch /}`, where `sudo` is configured to read a password on the standard input (won't work as of now).

**Comment by mawww** [comment]
Hello,

Unfortunately that is not really doable with the current design:
1. `%sh{...}` are evaluted on the server, so the sudo would be running in the server terminal, which wont be whats expected.
2. clients do not guarantee they run in a terminal, the built-in ncurses client does, but json-ui or any other graphical client does not, so even if we managed to run the sudo client side, we dont have a terminal for it there.

In the specific case you show, if there is a strong use case behind, we could think about providing a -password to `:prompt` so that we can ask the user for passwords, getting a proper secure implementation of that would be tricky though.

**Comment by lenormf** [comment]
My use case for now is the following tool:

```
## save the current buffer to a file, with `sudo` rights
def sudo-write -docstring "Write the content of the buffer to a file using sudo" %{
    eval -save-regs '/"|^@m' %{
        prompt -init %val{bufname} -file-completion 'Path: ' m %{exec -draft "\% <a-|>sudo tee %reg{m}<ret>"}
    }
}
map global user 'W' %{:sudo-write<ret>}
```

I don't set `NOPASSWD` on my user in the `sudoers` file, and I don't like starting my editor with root rights right off the bat (I'm always paranoid that I'm going to leave it open in a terminal somewhere, and I don't like that). So basically I only require root rights when I need them, and drop them off immediately afterwards, and the function above does just that. Right now I have to suspend `kak` and run a command with `sudo` to cache my credentials, but that won't work for users who use `sudo -k` to disable "sessions".

**Comment by occivink** [comment]
@lenormf: did you manage to make a usable `sudo-write` binding?

**Comment by lenormf** [comment]
@occivink due to the way shell scopes are handled by the server, it's not possible to have a seamless integration of `sudo` with the editor at the moment.

**Comment by mawww** [comment]
What would be the main problem ?

**Comment by lenormf** [comment]
If credentials are not cached or if they have expired, there's no way to input the password directly into the prompt displayed by `sudo`.

**Comment by occivink** [comment]
I think with the -password switch you should be able to at least always input the password. At some point with somebody on irc we got to this point:
```
def sudo-write -docstring "Write the content of the buffer to a file using sudo" %{
    prompt -password 'Password: ' %{
        exec -draft %{ \%<a-|>
        tmp=$(mktemp XXXXXX)
        tee $tmp
        echo %val{text} | sudo -S tee $kak_buffile < $tmp
        rm $tmp<ret>
}}}
```
but this doesn't work for some quoting-related reasons that I can't figure out. I also kinda gave up after realizing that it was harder to get right than I had thought.

There's probably other tricky things when it comes to incorrect password.

**Comment by lenormf** [comment]
I use `|` to pass the contents of the buffer to `sudo tee` (I don't want to pass sensitive data to a shell pipeline), using a temporary file is an alternative I have mentioned already but I don't like that the password is now stored in an editor option.

`sudo` does more than a `read()` on `stdin` when prompting for the password, I read an interesting article about that a while ago (couldn't find it back), so I'm interested in having a seamless handling of standard inputs, in shell scopes.

There's also the _askpass_ option, using the `-A` flag, with which you could hack something together I suppose. Either way it's not a big deal, I can cache credentials in advance when I need it.

**Comment by occivink** [comment]
I revisited this issue and came up with a possible implementation of `sudo-write`:
```
declare-option -hidden str sudo_write_tmp

def sudo-write -docstring "Write the content of the buffer using sudo" %{
    prompt -password 'Password: ' %{
        %sh{
            printf "set-option buffer sudo_write_tmp \"%s\"\n" $(mktemp --tmpdir XXXXXX)
        }
        write %opt{sudo_write_tmp}
        %sh{
            unset-option buffer sudo_write_tmp 
            echo "$kak_text" | sudo -S -- awk --assign=output="$kak_buffile" "// { print \$0 > output } END { close(output) }" "$kak_opt_sudo_write_tmp" > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                echo "edit!"
            else
                echo "echo -markup \"{Error}Couldn't write, incorrect password?\""
            fi
            rm -f "$kak_opt_sudo_write_tmp"
        }
    }
}
```

It does pass the password around in a shell pipeline (not sure whether it's VERY unsafe or just a little) which may be a concern, but it's quite practical for editing system configuration files.

**Comment by lenormf** [comment]
You could also have used `-A` or `$SUDO_ASKPASS`, I think they would have simplified the second half of the command.

**Comment by occivink** [comment]
Usually that would prompt a graphical program asking for the password, right? 
I guess the version I posted could still be useful in an ssh session.

**Comment by lenormf** [comment]
According to the documentation, using `-A` prevents `sudo` from reading the password on the standard input, and the `$SUDO_ASKPASS` variable contains the path to the program to use to ask for the password. That way you could potentially have kakoune spawn a new window and use a safer method to get the password?

**Comment by andreyorst** [comment]
I wonder if some general purposed script could be written to pass to all kinds of `$\w+_PASS` variables, as I suppose that majority of programs, that request such variable, are operating the same. Maybe Kakoune could be suspended with `C-z` event, until the password is inserted?
