### ISSUE TITLE
The `tag` command doesn't take the path of the current tags file into account

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#662]
Hi,

How to reproduce:
* generate a tags file in `/a`: `cd /a && ctags -R`
* change the current directory to `/a/b`
* open up a buffer (whose symbols will be listed in `/a/tags`), and set the `ctagsfiles` variable accordingly: `set -add buffer ctagsfiles ':/a/tags'`
* look up a symbol that is defined out of the `/a/b` directory with the `:tag` command
* kakoune will try to open the buffer whose path is listed in `/a/tags`, but relatively to the current buffer's path, and not relatively to the path of the tags path

Also, I don't really understand why there is a `ctagspaths` variable, either we should specify full paths in `ctagsfiles`, or specify directories in `ctagspaths` in which kakoune will looks for a `ctagsfile` (non-existent variable as of now) file. Why is that paths variable only used in the generation functions ? Don't we want the update functions to update the tags that we are using without worrying about paths ?

Thanks.

**Comment by mawww** [comment]
Hi, sorry for the delay, `ctagspaths` is the list of paths we want to pass to ctags to generate the tags file, that is, the list of file, or directories, to analyze and generate tags from.

For the base bug, thats correct, Kakoune should take the paths in tags file as relative to the tag file itself.

**Comment by lenormf** [comment]
I had a WIP fix for this issue, which did the same thing that the f9260a6 does. Except I've been itching to just get rid of the `awk` bit, because it seems more cryptic than a `sed`/`expr` pair, and it will also print an error message as soon as a tags file doesn't contain the tag being looked up (regardless of whether that tag is in the other files of the `ctagsfiles` variable).

Anyway, something that needs to be fixed in the current implementation:
```
diff --git a/rc/base/ctags.kak b/rc/base/ctags.kak
index cc78af7..a642145 100644
--- a/rc/base/ctags.kak
+++ b/rc/base/ctags.kak
@@ -21,7 +21,7 @@ def -params 0..1 \
                 re=$0;
                 sub(".*\t/\\^", "", re); sub("\\$?/$", "", re); gsub("(\\{|\\}|\\\\E).*$", "", re);
                 keys=re; gsub(/</, "<lt>", keys); gsub(/\t/, "<c-v><c-i>", keys);
-                out = out " %{" $2 " {MenuInfo}" re "} %{eval -collapse-jumps %{ try %{ edit %{" $2 "}; exec %{/\\Q" keys "<ret>vc} } catch %{ echo %{unable to find tag} } } }"
+                out = out " %{" $2 " {MenuInfo}" re "} %{eval -collapse-jumps %{ try %{ edit %{" ENVIRON["tagroot"] $2 "}; exec %{/\\Q" keys "<ret>vc} } catch %{ echo %{unable to find tag} } } }"
             }
             /[^\t]+\t[^\t]+\t[0-9]+/ { out = out " %{" $2 ":" $3 "} %{eval -collapse-jumps %{ edit %{" ENVIRON["tagroot"] $2 "} %{" $3 "}}}" }
             END { print length(out) == 0 ? "echo -color Error no such tag " ENVIRON["tagname"] : "menu -markup -auto-single " out }'
```

**Comment by andreyorst** [comment]
> Anyway, something that needs to be fixed in the current implementation:
> 
> ```
> diff --git a/rc/base/ctags.kak b/rc/base/ctags.kak
> index cc78af7..a642145 100644
> --- a/rc/base/ctags.kak
> +++ b/rc/base/ctags.kak
> @@ -21,7 +21,7 @@ def -params 0..1 \
>                  re=$0;
>                  sub(".*\t/\\^", "", re); sub("\\$?/$", "", re); gsub("(\\{|\\}|\\\\E).*$", "", re);
>                  keys=re; gsub(/</, "<lt>", keys); gsub(/\t/, "<c-v><c-i>", keys);
> -                out = out " %{" $2 " {MenuInfo}" re "} %{eval -collapse-jumps %{ try %{ edit %{" $2 "}; exec %{/\\Q" keys "<ret>vc} } catch %{ echo %{unable to find tag} } } }"
> +                out = out " %{" $2 " {MenuInfo}" re "} %{eval -collapse-jumps %{ try %{ edit %{" ENVIRON["tagroot"] $2 "}; exec %{/\\Q" keys "<ret>vc} } catch %{ echo %{unable to find tag} } } }"
>              }
>              /[^\t]+\t[^\t]+\t[0-9]+/ { out = out " %{" $2 ":" $3 "} %{eval -collapse-jumps %{ edit %{" ENVIRON["tagroot"] $2 "} %{" $3 "}}}" }
>              END { print length(out) == 0 ? "echo -color Error no such tag " ENVIRON["tagname"] : "menu -markup -auto-single " out }'
> ```

This implementation has various bugs. You can reproduce most of them with kakoune documentation file `buffers.asciidoc`.

I've made a [simpler command](https://github.com/andreyorst/dotfiles/blob/a6f3e05213f58d665ae7e91affffee6e9792bdd6/.config/kak/commands.kak#L87-L102) `symbol` that allows jumping within the file, but it essentially is the same as `ctags-search`, and I've rewritten this huge awk sorcery to simple `while` loop:
```sh
menu=$(readtags -t $tags "$1" |
while read tag; do
    file=$(printf "%s\n" "$tag" | cut -f 2)
    search=$(printf "%s\n" "$tag" | cut -f 3 | sed -E 's:^/\^|\$/$::g;')
    if [ -n "$file" ] && [ -n "$search" ]; then
        menu="$menu %{$file {MenuInfo}$search} %{ evaluate-commands %{ try %{ edit %{$file}; execute-keys %{/\Q$search<ret>vc} } catch %{ echo -markup %{{Error}unable to find tag} } } }"
        printf "%s\n" "$menu"
    fi
done | tail -n 1)
if [ -n "$menu" ]; then
        printf "%s\n" "menu -markup -auto-single $menu"
fi

```
This way it has no bugs of previous awk command, adn supports spaces and special symbols in tag names. Should this be integrated to `ctags.kak` script?

**Comment by lenormf** [comment]
The current implementation fares pretty well on big `ctags` files, e.g. the one from the Linux kernel. How does yours do? It seems to be creating many processes, which `awk` doesn't.

**Comment by andreyorst** [comment]
opening a tag from Linux project seems to be as fast as `awk` implementation but I've did not measured anything precisely. But I've noticed a caveat with `cut` and tags that begin with `.` (dot).

**Comment by andreyorst** [comment]
@lenormf I've figured out that you can't use unmatched `{` in sh expansion even if it is part of some command, which is kind of strange, but I've reworked obtaining of third argument by using `sed`, in the same fashion how it was implemented in current `awk` command. Thus if tag will contain a `{` in the middle we will not be able to find it, since we need to strip this curly brace away, so menu command will not have unmatched string error (same as `:echo %{{}`). Which is super weird to me. I'll see what can be done.

**Comment by occivink** [comment]
@andreyorst generally balanced strings are not a good match if you have arbitrary data inside. If you want *perfect* handling you need to use quoted strings `'...'` and double up any `'` inside (actually any delimiter will work).

A good enough approach is to use `%X...X` where X is a rare punctuation sign, like `§` and double them up as needed. So in your case you would have something like:
```
menu="$menu %§$file {MenuInfo}$search§ %§ evaluate-commands %§§ try %§§§§ edit %§§§§§§§§$file§§§§§§§§; execute-keys %§§§§§§§§/\Q$search<ret>vc§§§§§§§§ §§§§ catch %§§§§ echo -markup %§§§§§§§§{Error}unable to find tag§§§§§§§§ §§§§ §§ §"
```

As you can see that gets rather silly. To avoid this crazy nesting, you can define a separate command and pass the input as parameters:
````
# params are: file, search
define-command something-handler -params 2 %{
    menu "%arg{1} {MenuInfo}%arg{2}" %{
        eval %{
            try %{
                edit %arg{1}
                reg / "\Q%arg{2}\E"
                exec /<ret>vc
            } catch %{
                echo -markup "{Error}Unable to find tag"
            }
        }
    }
}
# so the shell script only has to do
menu="$menu %§$file§ %§$search§"
```

**Comment by andreyorst** [comment]
> you need to use quoted strings '...' and double up any ' inside 

Yeah, I know. Now I think how to handle single quotes inside the tag itself
![image](https://user-images.githubusercontent.com/19470159/49654069-e1a35580-fa47-11e8-9695-5432d80ef194.png)

**Comment by occivink** [comment]
That won't work if $file or $search contains any `'` which you may or may not find acceptable. If you don't like the amount of quotes, use the separate command solution.

**Comment by andreyorst** [comment]
This is an experiment anyway since I just want to handle amount of quotes inside `$file` and `$search` and see how well it will work.

**Comment by andreyorst** [comment]
I don't see how external command would help. We still need to pass a `{` to it, and it will fail, since the resulting menu would contain unbalanced `{` at the moment of execution.

Well. Anyway. Now I see that there's lot more caveats to solve associated with parsing strings in kakoune. If I'll achieve something as complete as current implementation I'll come back.

**Comment by occivink** [comment]
That's because the command doesn't get parsed at the same time. Try out this simple example:
```
def test -params 1 %{ eval %{ info %arg{1} } }
test 'weird { string ' " } }} %{ <'
```
The only part where you have to be careful is when you call `test`

**Comment by andreyorst** [comment]
I still don't see how is this going to work. We build a really long menu with lots of candidates, and then blast it to `menu` command. Your example is nice for known amount of strings, which is not the case here.

**Comment by occivink** [comment]
Yes that particular case is trickier than with a known number of arguments.  I think it could be handled like that (untested but I think it should work):
```
def command-that-does-stuff -params 2 %{ 
    #do something here
}
def menu-command -params .. %{
    eval %sh{ 
        printf 'menu'
        i=1
        while [ $# -ne 0 ]; do 
            iplusone=$((i+1))
            printf " '%%arg{%s} {MenuInfo}%%arg{%s}'" $i $iplusone
            printf " 'command-that-does-stuff %%arg{%s} %%arg{%s}'" $i $iplusone
            shift 2
            i=$((i+2))
        done
    }
}
eval %sh{
    menu='menu-command'
    menu="$menu %§$file§ %§$search§"
    menu="$menu %§$file§ %§$search§"
    #...
    printf %s "$menu"
}
```

Basically do as little as possible expansions in shell scope, and leave it up to kakoune where it's properly handled. Then if you really care about perfect input you only need to manipulate $file and $search where the menu-command is generated (and to watch out for markup expansion I guess).

**Comment by andreyorst** [comment]
I don't like this solution. It surely will be slower than current `awk`, and all those expansions look like danger zone for me.
This code works, though it doesn't look fancy:
```sh
menu=$(readtags -t ./tags "$1" |
while read tag; do
    file=$(printf "%s\n" "$tag" | cut -f 2)
    search=$(printf "%s\n" "$tag" | cut -f 3 | sed -E 's:^/\^|\$/$::g;')
    if [ -n "$file" ] && [ -n "$search" ]; then
        name=$(printf "%s\n" "$file" | sed "s:':'':g")
        file=$(printf "%s\n" "$file" | sed "s:':'''''''''''''''':g")
        search=$(printf "%s\n" "$search" | sed "s:':'''''''''''''''':g")
        command="evaluate-commands '' try '''' edit ''''''''$file''''''''; execute-keys ''''''''/\Q$search<ret>vc'''''''' '''' catch '''' echo ''''''''unable to find tag'''''''' '''' ''"
        menu="$menu '$name' '$command'"
        printf "%s\n" "$menu"
    fi
done | tail -n 1)
if [ -n "$menu" ]; then
    printf "%s\n" "menu -auto-single $menu"
fi
```
However it is slower in the menu building part compared to current awk implementation. Investigating further.

**Comment by andreyorst** [comment]
```sh
menu="${TMPDIR:-/tmp}/ctags-menu"
open='{'; close='}'
readtags "$1" |
while read tag; do
    name=$(printf "%s\n" "$tag" | cut -f 2 | sed "s:':'':g")
    menuinfo=$(printf "%s\n" "$tag" | sed "s:.*/\^\(\s\+\)\?::;s:\$/$::;s:':'':g;s:$open:\\\\$open:g")
    keys=$(printf "%s\n" "$tag" | sed "s:.*/\^::;s:\$/$::;s:':'''''''''''''''':g")
    file=$(printf "%s\n" "$name" | sed "s:'':'''''''''''''''':g")
    command="evaluate-commands '' try '''' edit ''''''''$file''''''''; execute-keys ''''''''/\Q$keys<ret>vc'''''''' '''' catch '''' echo -markup ''''''''{Error}unable to find tag'''''''' '''' ''"
    if [ -n "$file" ] && [ -n "$keys" ]; then
        printf "%s " "'$name {MenuInfo}$menuinfo' '$command'" >> $menu
    fi
done
if [ -n "$menu" ]; then
    printf "%s\n" "menu -markup -auto-single $(cat $menu)"
fi
rm $menu
```

This version supports markup and possibly little more faster, because we don't build insanely growing line inside single variable, and don't print every unfinished line inside while loop to cut last variant with `tail -n 1` command. I don't see a way of speeding it up more. the `open='{'; close='}'` used to build escaped markup sequence.

@lenormf I think that this is better than current awk implementation since it isn't breaking tags that contain `{` and just little more slower when we have insane amount of similar tags in different files. If you have any idea how to speed it up, I'd like to hear it.

**Comment by lenormf** [comment]
If you have an implementation faster than the current one that can lookup a symbol in a couple of big tags files one after the other (`ctagsfiles` is a list), create a PR so everybody can just pull a branch and test it.
