### ISSUE TITLE
Send the current selection to the left/right most side of the window

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#663]
Hi,

It'd be nice to be able to shift the current view to the left/right as much as possible, while still seeing the current selection. Kind of like a `v-h` or `v-l`, but looped over until the current selection hits the side of the window.

Sometimes I would lookup some text in a buffer, and would like to read what's two or three lines under the selection, several dozen columns to the left or right of the current selection's column count, but can't without saving the selection move around awkwardly hoping that restoring the selection will still allow me to see the text I want to read.

Thanks.

**Comment by mawww** [comment]
Thats basically `999vh` or `999vl`, I am not convinced its a common enough need to warrant another binding.

**Comment by lenormf** [comment]
Correct, closing.
