### ISSUE TITLE
Expose information about the actually usable buffer space in scripts

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#675]
Hi,

An issue I noticed while using the `:man` command is that the man pages are always too large for the kakoune buffer to fit in when the `number_lines` highlighter is active (there's always a couple characters out of the screen that I need to `<a-l>` to). That's because the `man` executable is given the total width of the window (`window_width`), instead of the width of the area that will hold the data: the width passed to `man` has to be `window_width` minus the width that the `number_lines` highlighter takes up on the screen (including the seperator).

As such this rendering issue can be solved (at least) two ways: either highlighters are exposed along with the options that they were passed, or another default variable is created that holds the coordinate of the top-left corner of the "rendering area" (for lack of a better term), as well as its width and height. Either way, the `:man` command would be able to pass the `man` binary a more accurate width, and avoid off-screen litter.

Thanks.

**Comment by Delapouite** [comment]
Hi.

I tried to expose the data needed in this PR: https://github.com/mawww/kakoune/pull/1570
The new `window_range_column` *seems* to do the job.
