### ISSUE TITLE
Structural regular expression support

### ISSUE THREAD

**Issue by bb010g** [mawww/kakoune#677]
Described [here](http://doc.cat-v.org/bell_labs/structural_regexps/), and implemented in a vi-like editor here: [martanne/vis](https://github.com/martanne/vis). Even if it's just a config option, I think having them available would be very nice.

**Comment by mawww** [comment]
Hello,

By its design, Kakoune already supports structural regex, although with the difference that edition are always sequential.

`s` selects matches of the given regex *in the current selections*, `S` splits the current selections based on the given regex, <a-k> keeps selections if they contain a match for a given regex and <a-K> if they dont.

Is there a particular structural regex feature we dont have ?

Cheers
