### ISSUE TITLE
Highlighting multiple language within one file

### ISSUE THREAD

**Issue by FranzSkuffka** [mawww/kakoune#683]
How do I write a highlighter re-uses other highlighters? Could not find anything in the docs.

**Comment by lenormf** [comment]
Hi,

You can use `ref` to create regions that will be highlighted in the same manner some previously declared regions are. An example of this syntax can be found in the [Dockerfile support script](https://github.com/mawww/kakoune/blob/master/rc/extra/dockerfile.kak#L33).

However, consider dropping by the IRC channel (#kakoune @ irc.freenode.net) in the future, simple questions such as these are more easily answered and don't necessarily need an issue to be created.

**Comment by FranzSkuffka** [comment]
Thank you for pointing me in the right direction and sorry for spamming the issue tracker.
