### ISSUE TITLE
`git commit -v` results in diff being put in commit message

### ISSUE THREAD

**Issue by somasis** [mawww/kakoune#686]
On occasion, running `git commit -v` with kakoune as the editor will cause git to interpret the diff as part of the commit message.

My `kakrc`...
```
set global tabstop 4
set global indentwidth 4
set global grepcmd "ag --column"

set global ui_options ncurses_set_title=true
set global ui_options ncurses_assistant=clippy

hook global WinCreate .* %{
	hook window InsertChar \t %{ exec -draft <left>@ }
    addhl number_lines -separator " │" -hlcursor
    addhl regex ((?:TODO|FIXME|XXX|NOTE)(?:\(\w+\)+)?:?|(?:\h+)?$) 0:white,red+b 1:red,red # highlight trailing whitepace and TODOs
}

hook global WinCreate /var/tmp/options.*\.conf %{
    set buffer filetype paludis-conf
}
```

**Comment by lenormf** [comment]
Couldn't reproduce the issue.

Everything below the following line is removed from the commit message, using `kak` as well as other editors when writing the commit message:
```
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
```

Have you noticed any signs that might indicate that kakoune has altered those comments ? Do you have a test case that reproduces the issue ?

**Comment by lenormf** [comment]
Any news on this ? Do you have steps that reproduce the bug ?

**Comment by somasis** [comment]
Sorry for the radio silence. I reproduced it just now:

```
Makefile: `mkdir` before attempting to install

This fixes the install targets if the directories in question do not exist.

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Mon Jun 27 00:42:53 2016 -0400
#
# On branch master
# Your branch is ahead of 'origin/master' by 1 commit.
#   (use "git push" to publish your local commits)
#
# Changes to be committed:
#       modified:   Makefile
#
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
diff --git a/Makefile b/Makefile
index 4a41298..282b53d 100644
--- a/Makefile
+++ b/Makefile
@@ -99,9 +99,13 @@ hangouts-test.exe: $(TEST_C_FILES) $(PURPLE_COMPAT_FILES)
        $(WIN32_CC) -o $@ -DDEBUG $^ $(WIN32_PIDGIN2_CFLAGS) $(WIN32_PIDGIN2_LDFLAGS) -Ipurple2compat
 
 install: $(HANGOUTS_TARGET) install-icons
+       mkdir -p $(HANGOUTS_DEST)
        install -p $(HANGOUTS_TARGET) $(HANGOUTS_DEST)
 
 install-icons: hangouts16.png hangouts22.png hangouts48.png
+       mkdir -p $(HANGOUTS_ICONS_DEST)/16
+       mkdir -p $(HANGOUTS_ICONS_DEST)/22
+       mkdir -p $(HANGOUTS_ICONS_DEST)/48
        install hangouts16.png $(HANGOUTS_ICONS_DEST)/16/hangouts.png
        install hangouts22.png $(HANGOUTS_ICONS_DEST)/22/hangouts.png
        install hangouts48.png $(HANGOUTS_ICONS_DEST)/48/hangouts.png
```

Results in this in `git log`:

```
commit 52390cfb25a6ce2f6791e4fa32e64a6a08686dd2
Author: Kylie McClain <somasis@exherbo.org>
Date:   Mon Jun 27 00:42:53 2016 -0400

    Makefile: `mkdir` before attempting to install
    
    This fixes the install targets if the directories in question do not exist.
    
    diff --git a/Makefile b/Makefile
    index 4a41298..282b53d 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -99,9 +99,13 @@ hangouts-test.exe: $(TEST_C_FILES) $(PURPLE_COMPAT_FILES)
            $(WIN32_CC) -o $@ -DDEBUG $^ $(WIN32_PIDGIN2_CFLAGS) $(WIN32_PIDGIN2_LDFLAGS) -Ipurple2compat
    
     install: $(HANGOUTS_TARGET) install-icons
    +       mkdir -p $(HANGOUTS_DEST)
            install -p $(HANGOUTS_TARGET) $(HANGOUTS_DEST)
    
     install-icons: hangouts16.png hangouts22.png hangouts48.png
    +       mkdir -p $(HANGOUTS_ICONS_DEST)/16
    +       mkdir -p $(HANGOUTS_ICONS_DEST)/22
    +       mkdir -p $(HANGOUTS_ICONS_DEST)/48
            install hangouts16.png $(HANGOUTS_ICONS_DEST)/16/hangouts.png
            install hangouts22.png $(HANGOUTS_ICONS_DEST)/22/hangouts.png
            install hangouts48.png $(HANGOUTS_ICONS_DEST)/48/hangouts.png
```

**Comment by lenormf** [comment]
Here's what I think happens: when opening a buffer, kak will auto detect the format of line ends (if a line ends with "\r\n", the detected format is `CRLF`, otherwise it's `LF`), and when saving it, it will convert all the CRLF to LF or vice-versa according to the detected format.

The thing is, if you include a single CRLF into a commit message (as is the case with the patch above), all LF will be replaced with CRLF, and that's where the issue lies. The seperator used by `git` to know where the patch starts ends with LF, and `git` won't detect it if it ends with CRLF. I'm not sure why, but that's what my experiments have shown.

Now the issue doesn't happen with `vim` (it's the only one I've tried), because either vim only transforms the ending of inserted lines (and leaves the ones that were already there when the buffer was opened), or it didn't try to modify anything because it wasn't configured to do so.

Is this a `git` bug? I don't see why separators that end with CRLF are ignored, but maybe the reason is documented somewhere.

**Comment by mawww** [comment]
Good analysis, Kakoune does a very simple job for end of lines, as soon as it sees a `CRLF` sequence it considers the whole buffer to be using `CRLF` and will normalize line endings.

We could change that behaviour to consider a file as `CRLF` only if every lines ends with `CRLF`, which would be a vim like behaviour, and would preserve files with mixed line endings.
