### ISSUE TITLE
Cursors disappear after undoing align

### ISSUE THREAD

**Issue by xzfc** [mawww/kakoune#688]
Open buffer with following lines:
```
 +
  +
 +
  +
```
After typing `CCCe&u` I have 2 cursors, but I expect to have 4.

**Comment by lenormf** [comment]
`CCCe` will collapse two cursors onto the next one, so you don't have 4 cursors to begin with.

`%s\+<ret>&u` does keep the initial amount of cursors prior to the aligning.

**Comment by xzfc** [comment]
> `CCCe` will collapse two cursors onto the next one
Look carefully, the file have one or two spaces on each line.

> `%s\+<ret>&u`
I have two cursors after typing this.

**Comment by lenormf** [comment]
Indeed, I think this behavior has to do with the range computation function (`selection.cpp:257`), not sure if you can work around it.

**Comment by mawww** [comment]
when using undo/redo, kakoune tries to find the modified ranges and selects them, here you get two ranges because there is only two selections where align actually did insert some spaces.

**Comment by mawww** [comment]
Closing that as it is the expected behaviour of undo.
