### ISSUE TITLE
Cleaning up dead kakoune sessions?

### ISSUE THREAD

**Issue by tony** [mawww/kakoune#689]
How is kakoune supposed to clean up dead sessions that are no longer available to connect to?  Is there a way to tell ahead of time which sessions in``/tmp/kakoune`` are still alive?

<img width="1013" alt="screen shot 2016-06-01 at 6 20 34 pm" src="https://cloud.githubusercontent.com/assets/26336/15728953/92828ad0-2825-11e6-9c9e-d423569e265c.png">

To recreate, start a few kakoune process, ``kak``, ``kak -d``. Then type ``kill -9 kak``. Sometimes kak may crash on its own also.

<img width="948" alt="screen shot 2016-06-01 at 6 23 30 pm" src="https://cloud.githubusercontent.com/assets/26336/15729008/0775a048-2826-11e6-8837-403683ccdbb9.png">

After that happens, is there a command to reattach the sessions / sweep out the old ones?

**Comment by lenormf** [comment]
> Is there a way to tell ahead of time which sessions in/tmp/kakoune are still alive?

I would go for the following, granted that you do not have any named session running/dead:
```
kak -l | while read pid; do ps -p "${pid}" >/dev/null || echo "Dead session: ${pid}"; done
```

In the event that you do have named sessions, you'd need to try connect to the socket at `${TMPDIR}/kakoune/${USER}/${name}`, or you can use `lsof` to get a quick summary or the sessions running (the `-V` flag will tell you which sockets are invalid):
```
lsof -F p -- /tmp/kakoune/${USER}/* | sed -n '1~2p'
```

I don't know if there's anything you can do with broken sessions, @mawww ?

**Comment by tony** [comment]
The behavior I'd expect kak to flush out any that weren't useable. Even if it kakoune's startup trying and failing to connect to each one to rule them out.

However, after reading a related ticket #538, I'm not sure how well that request will go. :smile:  IMO the application should handle at least some of that stuff so the user can focus on other things.

**Comment by mawww** [comment]
Yeah, the remaining sessions files are problematic, although they should not be common, Kakoune should remove them even when it crashes. Having a way to detect and clean up session files would be nice though. Not sure what the best way of doing that would be.
