### ISSUE TITLE
libtinfo linking error in gentoo

### ISSUE THREAD

**Issue by ianlinkcd** [mawww/kakoune#695]
Having ncurses 6 built with the USE flag tinfo produces 
/lib64/libtinfow.so.6: error adding symbols: DSO missing from command line
when trying to build.

**Comment by mawww** [comment]
Hello, does `pkg-config --libs ncursesw` output contains libtinfow ? if so maybe its time to bite the bullet and depend on pkg-config for flags configuration (that could simplify the makefile greatly actually).

**Comment by lenormf** [comment]
@mawww I have looked into such a change already, and it would completely break travis builds, as the old distro it's running don't have up-to-date (when it has them at all, for some packages) pkgconfig files.

**Comment by ianlinkcd** [comment]
These are the flags that were returned

-lncursesw -ltinfow

**Comment by lenormf** [comment]
https://stackoverflow.com/a/19905704

**Comment by ianlinkcd** [comment]
Got it for Gentoo I made conf file in /etc/portage/env/ncurseDSOmiss.conf

added the line

LDFLAGS='-Wl,--start-group -lncursesw -ltinfow -Wl,--end-group'

and made another file in /etc/portage/package.env/kakoune

with

app-editors/kakoune ncurseDSOmiss.conf

**Comment by mawww** [comment]
Reopening, so that Hummer12007 can take a look at fixing the ebuild.

**Comment by Hummer12007** [comment]
@ianlinkcd: the proper fix shall get into the portage tree soon
