### ISSUE TITLE
Command looses focus when externally commanding kak

### ISSUE THREAD

**Issue by doppioandante** [mawww/kakoune#697]
Open an empty kak session, press : (colon), then from the command line
```
echo "eval -client unnamed0 b *debug*" | kak -p <session>
```
The buffer will be changed and when coming back the cursor will be at the text, while the popup stays open.
Pressing : and ESC makes it disappear.

I don't know which is better: the command input to regain its focus or the popup to be closed?

**Comment by lenormf** [comment]
Bonus: make the completion menu popup on the original buffer, then do the buffer switch from the shell. Nothing makes it disappear, apparently.

**Comment by mawww** [comment]
While I'd preferred to keep the prompt to stay alive even though we changed the buffer, doing that was tricky and potentially error prone (if a prompt was created on the previous buffer, and does a buffer specific operation, on what buffer does it apply ? it depends on the prompt command implementation, additionally, if we have other input states (on next key, insert, menu...) it is ambiguous as well). So I went the safe way, reset to normal mode, and clear up displayed info/menus.
