### ISSUE TITLE
Allow using `-itersel` with `-draft`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#706]
Hi,

Why can't we use `-itersel` without `-draft` ? Is it a technical limitation or a design choice ? There are some cases in which it'd be handy to be able to modify selections in a loop.

Thanks.

**Comment by mawww** [comment]
It is a technical limitation, when we iterate on selections (mainly to avoid selection merging logic), we need to introduce a temporary context in which we use each selections one after the other. It could be possible to do that on the current context by tweaking the implementation.

**Comment by lenormf** [comment]
It'd be nice to have that working, I've managed to work around it by saving the description of the selections I changed in a draft, and apply that description with `select` afterward, but that breaks the code into two parts unecessarily.

I'm changing the title of the issue, to add it to the list of features to implement.
