### ISSUE TITLE
configurable evaluated (%sh{…}) strings

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#71]
I want ability to add direct fish evaluation, `%fish{…}`.

**Comment by mawww** [comment]
Just %sh{...} seems good enough, other languages are already accessible through it and a built in method would require supporting various ways of passing the script (piped into stdin ? through a temp file passed on command line ? as a command line parameter ?)

**Comment by lenormf** [comment]
I gave this some thoughts as well, and I came to the same conclusion that spawning a shell that will then invoke the actual interpreter we want to use is best.

Another case that I stumbled upon, while I was looking to add a `%py{}` scope, is what version of the language kakoune should be using by default, or how to easily allow the user to chose without having a murder of aliases (i.e. `python2` vs `python3`).
