### ISSUE TITLE
[JSON-RPC] Add an `id` field to the server replies

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#716]
Hi,

All requests that do not contain an `id` field with a value chosen by the client should be rejected, and the response objects to those who do should contain this same id, as per [the spec](http://www.jsonrpc.org/specification#request_object).

I'm still not convinced the protocol doesn't need an id that will be reflected in the client's replies. I.e. if a UI decides to use the -currently unimplement- getoption command in several consecutive requests, and one of them turns out to fail (e.g. using a wrong option name), the UI needs to be able to pinpoint which request failed to decide whether the error can be displayed and ignored or not.

**Comment by mawww** [comment]
We dont need an id for now, we might at some point as an implementation detail if we end up responding to requests (which we dont as of now), but implementing id for the sake of it makes no sense.

**Comment by lenormf** [comment]
Actually I gave an example that showed it wasn't "for the sake of it", but ok we'll see.

**Comment by mawww** [comment]
Hello, I mean that adding an `id` field itself is not an issue, for sure if we add a getoption command or similar, we will introduce an `id` as an implementation detail.
