### ISSUE TITLE
[JSON-RPC] Document the guaranteed integrity of server objects when followed by a newline character

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#717]
Hi,

Ensure that complete JSON objects are followed by a newline character, to save the client any checks.

**Comment by doppioandante** [comment]
This does already happen I think:
```c++
    auto q = format(R"(\{ "jsonrpc": "2.0", "method": "{}", "params": [{}] }{})",
method, concat(std::forward<Args>(args)...), "\n");
```

**Comment by mawww** [comment]
Yeah, the current implementation should not insert newlines except at the end of rpc calls, I think we can decide to put that in the doc and guarantee it.
