### ISSUE TITLE
[JSON-RPC] Wrong atom face sent

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#718]
Hi,

* ~~Line numbering from the `number_lines` highlighter is wrong, no matter what buffer is opened. [Here](http://codepad.org/OiHtQ3Cb) is the data you'll get from opening `src/Makefile` in json mode, as you can see the first two lines are both labeled `1` (the rest of the numbering is fine though).~~
* ~~Sometimes newlines characters are not sent to the client, which results in lines being merged. It seems to be the same lines from one execution of the client to another.~~
* The first atom that isn't a part of the line numbers has the wrong foreground color (e.g. the first '#' character in a Makefile)

**Comment by lenormf** [comment]
For some reasons two of the above issues went away. I do however still get a bad face for the first character of any file I edit.

**Comment by mawww** [comment]
Are you sure what you are seeing is not the cursor ?

**Comment by mawww** [comment]
Kakoune does not send the selections to the UI, selections are applied as any other highlighter, so the cursor, which starts on the first character, will apply a different face than what the syntax highlighting would have done, I am pretty confident thats what you see here.

**Comment by lenormf** [comment]
It was a typo in a subfunction that handles how the face is applied… Sorry for the white noise.
