### ISSUE TITLE
keybindings with capital letters, symbols

### ISSUE THREAD

**Issue by tony** [mawww/kakoune#722]
I am having issues on OS X with various keybindings.

For one, in lldb, return/``ctrl-m`` keys will not work in buffer or prompt. However it will work in vim/neovim.

While debugging / exploring the source, I tried adding additionally keys to ``Prompt.on_key`` at https://github.com/mawww/kakoune/blob/master/src/input_handler.cc#L668.  During this time, I discovered that keys didn't handle certain keys:

- Modified ones with capitalization (e.g. ``ctrl('B')``)
- Symbols ``ctrl('[')``, ``ctrl(',')``

This may be the tip of the iceberg in that respect, since different terminals are going to handle input differently.

I remember this being a limitation in vim.  I believe neovim/vis addresses it with [libtermkey](http://www.leonerd.org.uk/code/libtermkey/) ([git repo](https://github.com/neovim/libtermkey)).

I'm considering experimenting with a libtermkey branch to see if that alleviates it.  Any thoughts?

**Comment by tony** [comment]
My biggest pain-point with this is ``ctrl-m``/Enter not working at all in LLDB, whereas in vim/vis/neovim it works fine.

**Comment by mawww** [comment]
Hello,

Regarding `return` in lldb, is there a key that gets sent ? if so, what is that key ?

For more general modifiers support, yeah we would need to use libtermkey or to implement key parsing by ourselves. I am not keen on any of these solutions, libtermkey is abandonned in favor of libtickit, which implements a whole ncurses alternative, and parsing the keys ourselves could be quite error prone if we want to robustly support various terminals.

We could have a libtickit based user interface implementation though, choosing between the two at compile time and/or runtime should be doable, even though ncurses is not as encapsulated as I'd like (see `LocalUI` in main.cc for example).

I must say, except for the `return` key not working on lldb, i think this is more of a minor inconvenience, and I am worried about adding another dependency (and putting a precedent in place for optional dependencies) to libtickit. So I am not sure it is something to pursue right now.

On the other hand, we are experimenting with the json ui interface to allow external UIs, so maybe the case for an alternative console interface could be made as a separate project.

**Comment by tony** [comment]
> Regarding return in lldb, is there a key that gets sent ? if so, what is that key ?

How would I most effectively be able to log/record that?

**Comment by tony** [comment]
> i think this is more of a minor inconvenience, and I am worried about adding another dependency (and putting a precedent in place for optional dependencies) to libtickit. So I am not sure it is something to pursue right now.

Agreed.  I would be really happy to diagnosis the lldb thing.  Do you experience the same effect in lldb?

I may still keep a branch trying it for exploratory reasons kakoune can use

> libtickit

Or maybe a libtickit branch.  Had to get bazaar installed to grab a copy of it.

**Comment by mawww** [comment]
> > Regarding return in lldb, is there a key that gets sent ? if so, what is that key ?

> How would I most effectively be able to log/record that?

You could put a breakpoint into the Kakoune::NormalMode::on_key method and hit the return key in normal mode (you might want to run kakoune with the `-n` switch to avoid any hooks triggering the breakpoint during startup). See if you hit the breakpoint and what is the value of the `key` parameter.

**Comment by tony** [comment]
```
* thread #1: tid = 0x75b1dc, 0x00000001001e20c7 kak`Kakoune::InputModes::Prompt::on_key(this=0x0000000100a00090, key=(modifiers = Control, key = U+0x0000006a U'j')) + 39 at input_handler.cc:660, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00000001001e20c7 kak`Kakoune::InputModes::Prompt::on_key(this=0x0000000100a00090, key=(modifiers = Control, key = U+0x0000006a U'j')) + 39 at input_handler.cc:660
   657
   658      void on_key(Key key) override
   659      {
-> 660          History& history = ms_history[m_prompt];
   661          const String& line = m_line_editor.line();
   662          bool showcompl = false;
   663
(lldb) frame v
(Kakoune::InputModes::Prompt *) this = 0x0000000100a00090
(Kakoune::Key) key = (modifiers = Control, key = U+0x0000006a U'j')
(History &) history = size=0
(const Kakoune::String &) line = 0x000000010090d303: {
  m_data = {
    l = (ptr = 0x0000000000000000, size = 0, capacity = 0)
    s = (string = "", size = '\0')
  }
}
(bool) showcompl = false
```

**Comment by tony** [comment]
On FreeBSD 11-CURRENT, I fair far worse in lldb. The screen is blank.

**Comment by tony** [comment]
If I attach kakoune via pid in a separate terminal, returns work, all is fine:

```
(lldb) frame v
(Kakoune::InputModes::Prompt *) this = 0x00007fcc231003f0
(Kakoune::Key) key = (modifiers = Control, key = U+0x0000006d U'm')
(History &) history = size=0
(const Kakoune::String &) line = 0x00007fcc21e03503: {
  m_data = {
    l = (ptr = "", size = 8660237365479997503, capacity = 8388441)
    s = (string = "", size = '\0')
  }
}
(bool) showcompl = false
```

Related: http://dirac.org/linux/gdb/07-Debugging_Ncurses_Programs.php, https://stackoverflow.com/questions/11965328/debugging-ncurses-application-with-gdb

**Comment by mawww** [comment]
So it seems you get a `<c-j>` instead of `<c-m>` when running in lldb, I think that should be fixed by first adding a proper "Return" keystroke, and moving the `<c-j>`/`<c-m>` == `<ret>` logic in the ncurses ui. `<c-j>` seems sort-of valid, as it is `LF` in ascii (when `<c-m>` is `CR`).
