### ISSUE TITLE
Contributor agreement / License

### ISSUE THREAD

**Issue by tony** [mawww/kakoune#724]
Re: https://github.com/mawww/kakoune/pull/721#issuecomment-230335249

By default, I assume my contribution is public domain anyway, since the [UNLICENSE](https://github.com/mawww/kakoune/blob/master/UNLICENSE) is there. It is very familiar to MIT, but it adds things:

> In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

It looks like legal speak.  I copy-paste this sentence-by-sentence google it and don't see lawyers using this a boilerplate ([example](https://www.google.com/search?q=%22In+jurisdictions+that+recognize+copyright+laws%2C+the+author+or+authors+of+this+software+dedicate+any+and+all+copyright+interest+in+the+software+to+the+public+domain%22+-unlincese+-unlicense.org)).

I am ok signing a CLA, examples of some I've used before, i.e. https://github.com/aseprite/opensource/blob/master/cla.md, https://cla.microsoft.com/cladoc/microsoft-contribution-license-agreement.pdf. However, the CLA requested on this project / recommended on the unlicense website is a bit of a red flag to me.

My confusion: The wording on this goes beyond my submission (present and future rights), it also leaves open to ambiguity what "the software" is. Is a fork still "the software"?  There is also contradiction in it, the UNLICENSE is very very liberal, but under the CLA, it seems as if I'm also waiving my ability to use the software under public domain.

I also note I am from United States, I am not sure if this is normal in other jurisdictions. However, it seems like less of a concern over that and more that unlicense wasn't drafted by a legal professional (see [https://lists.opensource.org/pipermail/license-discuss/2011-December/000039.html](https://web.archive.org/web/20150921224734/https://lists.opensource.org/pipermail/license-discuss/2011-December/000039.html)).  Unlike other licenses like CC-0, MIT, BSD, Apache, this one hasn't been vetted properly.

When researching UNLICENSE, I am seeing a lot of other concerned voices:

- https://fedoraproject.org/wiki/Licensing/Unlicense
- https://groups.google.com/forum/#!msg/unlicense/G6pzAFtgrx0/9TCxE-je2qMJ
- https://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense
- [https://lists.opensource.org/pipermail/license-review/2012-January/000047.html](https://web.archive.org/web/20150908045401/https://lists.opensource.org/pipermail/license-review/2012-January/000047.html)
- [https://lists.opensource.org/pipermail/license-review/2012-January/000052.html](https://web.archive.org/web/20150907225139/https://lists.opensource.org/pipermail/license-review/2012-January/000052.html)

Some of the last two posts on the OSI mailing list are strongly worded (the term "crayon license"). The concern isn't taking a jab at unlicense in particular (his gripe seems to be with non-lawyers drafting licenses and it being pasted about in a cargo-cult fashion) but a lot of the concepts thrown in don't work well across jurisdictions.  There are discussions mentions it being [invalid in Germany](https://groups.google.com/forum/#!topic/unlicense/GrjYlqmF92Q) due to how public domain / heirs work, more [comments](https://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense/147120#comment420751_147120) from a stackexchange post.

Any willingness to change the license to [MIT](https://en.wikipedia.org/wiki/MIT_License#License_terms)?  It is very similar and doesn't have the same ambiguity around it.

**Comment by mawww** [comment]
Hello,

I understand your concerns, when I made the licensing decision some years ago, one of my main objective was to get my project out of copyright, so UNLICENSE matched quite well with that intent, as it is explicitely trying to do that. Nowadays, I get that the legal system is slightly more involved and that using a more recognized license would have been safer, although I still consider that the intent of UNLICENSE is clear.

Regarding the copyright waiver I am asking, it is actually the one from sqlite, which forms the first part of the unlicense text.

I am not really keen on changing the licensing, I believe I legally can (as much as anybody else), as all the existing code is either under public domain, or covered by the fallback license, depending on the jurisdiction. But in the end, its a bit of a strange situation: If I can change the license, then we dont have any problems to begin with, so no need to change the licence.

By the way, I dont live in the US either, I used to live in france, where you cannot put work in the public domain, and now live in Ireland, where I believe we can, as we have a legal framework based on common law.

Cheers,

Maxime.

**Comment by tony** [comment]
> Regarding the copyright waiver I am asking, it is actually the one from sqlite, which forms the first part of the unlicense text.

I have read that unlicense comes from sqlite.

I see SQLite everywhere.  I see UNLICENSE as much of a barrier to usage, but to contribution, I think it could be a chilling effect. I don't hear as much about its contributions back (but am interested to know). The best I can do is: https://system.data.sqlite.org/index.html/timeline?n=9999&y=ci&v=0.

> But in the end, its a bit of a strange situation: If I can change the license, then we dont have any problems to begin with, so no need to change the licence.

This whole chicken egg thing is why I'm confused.

> But in the end, its a bit of a strange situation: If I can change the license, then we dont have any problems to begin with, so no need to change the licence.
>  I still consider that the intent of UNLICENSE is clear.

I'm not in agreement that its clear. Not relative to other contracts I've signed that clearly defined what's happening.

Did you sign the CLA? If that is the case, if someone were, "relinquishment in perpetuity of all present and future rights to this software under copyright law." sounds like that signer agreeing to waive the right even to relicensing it.  The software is still the software. Whatever that means. In much legal stuff I see in USA, words subject to ambiguity like that are put into quotes and defined early in the contract.

I've already probably spent 30+ hours in kakoune forks. Even if my branches don't end up making in kakoune, even if unlicense would be in-whole or in-part thrown out it in USA / other jurisdictions, I don't wanna sign something saying " I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law." D:

It doesn't even state scope. D:  I don't want to relinquish / waive rights, I'm happy to assign / grant rights to use code. Here is an example from [Microsoft's CLA](https://cla.microsoft.com/cladoc/microsoft-contribution-license-agreement.pdf):

> You grant Microsoft, and those who receive the Submission directly or indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third parties. 

To that end, if we took off the CLA and UNLICENSE and just used an MIT, wouldn't we remove the ambiguity all together?

**Comment by mawww** [comment]
Hello,

> Did you sign the CLA? If that is the case, if someone were, "relinquishment in perpetuity of all present and future rights to this software under copyright law." sounds like that signer agreeing to waive the right even to relicensing it.

I dont have a copyright waiver, but I did put the UNLICENSE file in the repository, which have the same effect (I clearly showed my intent to put Kakoune in the public domain, or, if not possible, to license it under as permissive conditions as possible). It seems I also abandonned rights to relicense Kakoune, as that is likely covered as a "right under copyright law".

I am not sure what is concerning you besides theoretical legal problems. I want Kakoune to be as close to public domain as legally possible, and it seems I documented that intent enough so that I am not a legal danger for anybody. Every contributor has a commit in their name stating that same intent, and I am asking new contributors to do the same so that we can assume Kakoune is still public domain, or as close to public domain as possible.

I understand some people could find it a bit hard to abandon their copyright on some work, It took me some time before I convinced myself that was the "right thing"™.

Call me an optimist, I still trust the UNLICENSE will be interpreted based on common sense, I mean that if there is an ambiguity on the word "Software", it might be on whereas the docs are part of it (I consider they are), but clearly the core of the code is part of it.

**Comment by tony** [comment]
> Call me an optimist, I still trust the UNLICENSE will be interpreted based on common sense, I mean that if there is an ambiguity on the word "Software", it might be on whereas the docs are part of it (I consider they are), but clearly the core of the code is part of it.

I don't doubt your sincerity and your intentions w/ it.  But I don't want to defer interpretation on technical wording and scope since its a legal agreement.

Re: common sense.  In USA is an adversarial legal system where two sides have a different interpretation of what's common sense.

> I am not sure what is concerning you besides theoretical legal problems.

Then what is a legal problem that _isn't_ theoretical as you see it? :smile:

Everything legal is just theoretical until its in front of a court? 

One of the big things a lawyer does is write documents in this way.  http://www.archives.gov/federal-register/write/legal-docs/

The point of drafting a correct legal document is to alleviate theoretical concerns and have a clear, concise understanding.  http://www.archives.gov/federal-register/write/legal-docs/ambiguity.html

> I want Kakoune to be as close to public domain as legally possible,

If you do want it to really be public domain, the license has to be upheld. You could probably achieve your end using a license more like CC-0, which has been drafted to be compatible internationally.  See https://creativecommons.org/publicdomain/zero/1.0/

You also would be ok with [ISC](https://opensource.org/licenses/ISC) (even simpler than MIT).

The whole point of using software licenses like CC-0 and MIT is they're drafted by people who understand the law.  I feel unlicense ultimately goes against your intentions, a legal license isn't interpreted by whats in your heart but what's on paper.

This process sort of wears me out and I don't want to spend more time on it.  Are you willing to accept PR's without the CLA signed?

**Comment by lenormf** [comment]
Without talking about being an obstacle to contributing, the fact that the unlicense is so heavily (although accurately) criticized is subject for concern. We don't want the license text to be questioned and its intended consequences over individual rights (contributors) nullified, in any situation (country, wording etc).

Following the fedora foundation's advice on the matter is probably the best course of action, even if it pains me to add tons of legal gibberish for something as simple as giving up individual rights on contributions. But I'd rather add the 5kb CC-0 license file to the repository and be sure that no angle could allow one to work around giving up their rights, than hoping on national jurisdictions using their common sense -which I reckon will have very little weight when balanced against actual words and the meanings put behind them.

**Comment by dumblob** [comment]
@lenormf speaking about Fedora, if I'm not mistaken, they've solved "the issue with public domain" by globally relicensing every such work under by-them-chosen license (MIT), because public domain allows that. From this point of view, public domain "licenses" shift the whole legal responsibility to others (which is though a significant problem for enterprises).

I myself dislike licensing of open source in general, but if I expect not only individuals to use my software for their own non-profit purposes, I stick to principles mentioned in https://www.youtube.com/watch?v=-bAAlPXB2-c (keynote about licenses from the GitHub co-founder) and look at http://choosealicense.com/ to choose a globally legally respected and globally legally-proved-to-be-ok license.

**Comment by lenormf** [comment]
What's the status on this then ? If the license isn't going to change, we might as well close the issue.

**Comment by mawww** [comment]
Based on unlicense being in http://choosealicense.com/licenses/, and the discussion at https://github.com/project-open-data/project-open-data.github.io/pull/135 I ended deciding to keep the unlicense, whose spirit matches my intent better than the MIT. I'll continue to ask for the copyright waiver as well.
