### ISSUE TITLE
Unable to drop a selection with `<a-space>` in selections iterated over with `exec`/`eval`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#729]
Hi,

It's not possible to arbitrarily drop selections with the following command:
```
exec -itersel <a-space>
```

Thanks.

**Comment by mawww** [comment]
Yep, thats expected, you cannot drop a single selection.

**Comment by lenormf** [comment]
Hm, thanks. I didn't realize the parent scope was completely separate from the one iterated over.
