### ISSUE TITLE
Allow some commands not to be inserted in the history

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#738]
Hi,

I have a binding in my configuration that allows me to copy some text to the X clipboard, and that displays a message using `echo -color Information`. I just found out that this call to `echo` is inserted into my history, which is a bit annoying because it's just a status update notification, not really something I would use again later.

How can this be fixed ? Maybe only insert in the history commands that were entered through the UI prompt ?

Thanks.

**Comment by mawww** [comment]
It should already be the case that commands executed from other commands / exec / eval should not touch the history, however if it comes from a keymapping at the moment it will get recorded. We could probably disable that, however there is already a way for a command not to be recorded in history (regardless of how the user enters it): prefix the command with a whitespace (`:<space>command...`).

**Comment by lenormf** [comment]
Perfect, thanks.
