### ISSUE TITLE
Handle tmux focus capacities

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#739]
Hi,

I've been wondering why when I resumed kak after suspending the process, kakoune always display the `<a-i>` autoinfo message box. I think that's because tmux sends the underlying process escape sequences to notice him of focus events (`<esc>[I` and `<esc>[O`), and those trigger actions in kakoune.

I figured this out while reading the following link, which basically abuses key bindings to redirect those capacities to actual commands:
https://github.com/tmux-plugins/vim-tmux-focus-events/blob/master/plugin/tmux_focus_events.vim

Cheers.

**Comment by mawww** [comment]
How do you reproduce that ?

**Comment by lenormf** [comment]
```
$ tmux
$ kak
:new
<c-b>o
^Z
fg
<up>
```

After following the above steps, the inner selection menu pops up.

**Comment by mawww** [comment]
Does not seems to reproduce anymore, is that still the case for you ?

**Comment by lenormf** [comment]
I could reproduce this outside of `tmux` recently, and I think my window manager (`i3`) sends focus events (`^I`) to terminals, so it might not be related to `tmux`.
