### ISSUE TITLE
Session recovery support after quitting

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#74]

**Comment by dumblob** [comment]
+1 this is very important (at least cursor position, command history, and search history).

Except for session recovery, there should be also a crash recovery helping to avoid unsaved changes getting lost.

**Comment by alexherbo2** [comment]
@dumblob I end up using [attach](https://github.com/alexherbo2/dotfiles/blob/master/bin/attach) which is a wrapper around [dtach](http://dtach.sourceforge.net).

**Comment by dumblob** [comment]
@alexherbo2 how do you make it persistent e.g. across reboots? Also the command history, search history and cursor positions can't be restored after quitting kak and running it again :(

I use these features in (Neo)Vim a lot. I'm thinking about few special hooks for this purpose, but haven't started to write them as I haven't decided yet which format to use for the metadata "cache" as it has to be simple enough to allow very fast and easy manipulation on all supported platforms (=> langages not mentioned in POSIX are no go => assuming there is no specific support in Kakoune, the best available language is just AWK).

**Comment by mawww** [comment]
Yep, I am not sure exactly what the best way to support that would be. For selection, it seems that having a command to select a list of range would be nice, even for plugins (something that reads the $kak_selections_desc format and select it). For history we could have dump/restore to file. For the rest, hooks/user commands should be enough.

**Comment by Screwtapello** [comment]
Specifically for cursor positions, I've created [kakoune-state-save](https://gitlab.com/Screwtapello/kakoune-state-save), and I'm open to saving additional kinds of state once Kakoune has commands, options or expansions that allow them to be extracted and injected.

**Comment by mawww** [comment]
Closing this as most of those are now doable with individual features (restoring registers for history, saving selections, ...)
