### ISSUE TITLE
:doc command should show autocompletion immediately when command is typed

### ISSUE THREAD

**Issue by jkonecny12** [mawww/kakoune#750]
~~I think it would be nice to autocomplete ``:doc`` command. If I understand it correctly it's only showing content of files in some folder so it shouldn't be so hard.~~

EDIT: Doc command is showing autocompletion only after TAB key is pressed

**Comment by lenormf** [comment]
There is autocompletion on `doc` already, isn't it working for you ?

**Comment by jkonecny12** [comment]
AHAAA!! 
Yes it's there but it's not working correctly. When I write ``:doc `` nothing happen but the autocompletion will show after I press TAB. It's really confusing, everything else shows the possible options automatically after ``:doc `` is typed.

**Comment by lenormf** [comment]
Only builtin commands have that kind of behavior, those defined in kak scripts require you to hit `<tab>` to have the completion activated.

**Comment by mawww** [comment]
The problem here is that running the given completion command can be arbitrarily long, so we dont want to trigger it without a user intervention. What we could do however, as here the completions are static, is to add another way to specify completions for a commands, where you give a fixed list of candidates, that way we could just `def doc -completion-canddiates %sh{ ... find all docs ... } ...` and we have a static list to complete from.

**Comment by lenormf** [comment]
We still need to be able to complete the argument passed to the command, which we can't do with `-shell-candidates`

**Comment by jkonecny12** [comment]
If this is happening for some commands there should be some kind of information that you can get completion by hitting TAB. I really don't think I would ever use TAB to test it.

**Comment by lenormf** [comment]
The issue with completion on user defined functions is that you never know how big the completion script (when it's assigned) will be, so proposing completion candidates by default can get in the way.

But regarding the `doc` command specifically, completion suggestions should come up automatically yes.

**Comment by jkonecny12** [comment]
> The issue with completion on user defined functions is that you never know how big the completion script (when it's assigned) will be, so proposing completion candidates by default can get in the way.

Maybe I said it badly. I'll try to rephrase it. 
I don't think kakoune should do the completion but it should somehow warn a user that the completion can be done by TAB key if he wants.

Or another solution can be to have there timer and kill the completion job if it takes too long, or do it in background as separated thread.

**Comment by lenormf** [comment]
I see.

You can use ^C if a completion task takes too long to complete already, I guess this needs to be documented as well.
