### ISSUE TITLE
Selection undo issues

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#753]
I start with the following file:
```
one
two
three
```
Now: after `%<alt-s>yp`, I get:
```
one
one[]
two
two[]
three
three[]
```
So far so good. Now I hit `u` and I get
```
one
[t]wo
[t]hree[]
```
instead of
```
one[]
two[]
three[]
```
Plus, the selections are lost. Another `p` and a `u` and I end up with:
```
one
two
[t]hree[]
```
---
Second situation:
Same ini file. Now I try `%<alt-s>cHello<esc>u` which gives me:
```
one
two
thre[e]
```
instead of
```
one[]
two[]
three[]
```

**Comment by mawww** [comment]
Hello, what you are seeing is the expected result, at least with the current implementation:

When we undo, we do not restore the previous selections, as we dont save them for each modifications. What we do is finding the modified ranges provoked by the undo. In the first case, we see 3 deletions, starting at the begining of each even lines. So we just select the position of the deletions. the last one ends up past the buffer end, so it gets clamped to the last char. which gives us the 3 selections you saw. In other words, we deleted from (1,0), (3,0) and (5,0), compensating for deleted lines before each deletions, we get (1,0),(2,0) and (3,0). (3,0) is not valid anymore so we clamp it to buffer end (2,5) (actually seems we avoid the end of line as well so (2,4)).

I am not sure if we can do much better without saving selections in the undo data, which might be a bit coslty memory wise.

**Comment by kurkale6ka** [comment]
Thanks for the explanation :)
I am glad this is not a bug.
The issue can be closed I suppose
