### ISSUE TITLE
Selection behaviour with single chars

### ISSUE THREAD

**Issue by doppioandante** [mawww/kakoune#755]
Hi, in the following snippet
```
0  NUL
9  HORIZONTAL
10 LINE
12 FORM
13 CARRIAGE
32 SPACE
```
Selecting the whole first column with C and then pressing e selects the whole line in the first two lines, but only the number in the remaining lines. Is this the intended behaviour?

**Comment by mawww** [comment]
Yeah thats the expected behaviour, whats happening here is that one the first two lines, the cursor is already on the 'number' word end, so 'e' goes to the next word end. On the other lines, the next word end is the end of the 'number' word, so it just goes there.
