### ISSUE TITLE
Buffer-local definition of words

### ISSUE THREAD

**Issue by perpen** [mawww/kakoune#758]
I am currently writing some scheme and clojure code, and the word completion does not work properly as it does not consider chars like #, -, : as word characters.
It would be useful to make the definition of words buffer-local.

**Comment by lenormf** [comment]
You can use the `static_words` option to set words you want to be completed upon in the `buffer` scope, and use fuzzy matching to complete words that contain special non-alnum characters.

**Comment by mawww** [comment]
That would be a pretty nice addition actually, I'll see if it seems possible without impacting too much on performances.

**Comment by mawww** [comment]
I pushed a proposal in the `completion-extra-word-chars` branch, its an option called `completion_extra_word_chars` which is a string whose characters will be considered as word character for insert completion purpose. I am not very satisfied with the naming, so comments welcome.

**Comment by perpen** [comment]
Thanks @mawww, perfect.

**Comment by perpen** [comment]
Hmm actually not perfect yet...
I wanted to have the movement keys that involve words (so e/Alt-e/E/b/w etc.) handle the lisp-style words, and taking as first example the 'e' command I came up with `exec /(\h*([\w!:#?-]+|[^\n\w!:#?-]+))<ret>`
So I'm actually emulating the original behaviour but adding to standard word chars (`\w`) the chars I have in my `completion_extra_word_char` option. I can automate the construction of this command using the `%sh` construct, but it doesn't feel nice.

What about instead changing `is_word()` to take into account the current value of `completion_extra_word_char`?
Or even better, replace `completion_extra_word_char` with a `word_char` option which would specify all characters that can make up a word, maybe using the regex range syntax (would be for example `\w!:#?-`)

Ofc that would mean adding an options param to quite a few functions that may invoke `is_word()`.
Any thought on this @mawww ?

(and by the way, I'm quite curious about why you chose to implement functions like `select_to_next_word_end()` by doing manual parsing, rather than using regexes. Is it more efficient?)
