### ISSUE TITLE
How to set value to a completions option?

### ISSUE THREAD

**Issue by casimir** [mawww/kakoune#760]
I can't find a way to set a value to a `completions` option.  An example with `kak -n -e "source test.kak"`, _test.kak_ content being the following:
```sh
decl completions test_completions '1.1@1:a:b'
# gives → test.kak:1:1: 'decl' not enough elements in tuple

decl completions test2_completions
set buffer test2_completions '1.1@1:a:b'
# not executed because of the first error but does the same
```

Any insight?

**Comment by mawww** [comment]
Hello,

Ok, sorry for the docs which are not in sync with the latest code.

a completion candidate is not a single string, but 3 strings separated by `|`, it should be `<completion text>|<docstring>|<menu display text>`.

**Comment by casimir** [comment]
It works way better now! A bonus question then, where can I see the docstring and menu in the UI?

**Comment by lenormf** [comment]
My question would be why not use the `:` separator, just like with string lists ?

**Comment by mawww** [comment]
We have a list of tuples (excluding the first element), lists are `:` separated, tuples are `|` separated, its the same for line-flags or range-faces options.
