### ISSUE TITLE
True Color support lost in Tmux

### ISSUE THREAD

**Issue by bhajneet** [mawww/kakoune#762]
`face PrimaryCursor rgb:ffffff,rgb:e57373`

This is white on white inside tmux kakoune. It correctly shows white on pink/red when kakoune is loaded in gnome-terminal without tmux.

Checked for true color support by 

```
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

Which shows a gradient in both gnome-terminal and tmux.

**Comment by mawww** [comment]
It all depends on the value of $TERM, is it correctly a 256color terminal in tmux ?

**Comment by bhajneet** [comment]
echo $TERM properly shows "xterm-256color". I had it set to "tmux" which the arch wiki says to do for tmux 2.1 and over. That doesn't work either.

**Comment by bhajneet** [comment]
oddly enough, e57373 now isn't white, but black. I don't know if this is a hint or not.

**Comment by lenormf** [comment]
Put `set -g default-terminal "screen-256color"` in `~/.tmux.conf`.

**Comment by bhajneet** [comment]
Still converts rgb:e57373 to black.

Here is tmux showing that it can output the range:
![screenshot from 2016-08-20 11-42-11](https://cloud.githubusercontent.com/assets/14130567/17832205/626f995c-66cb-11e6-9490-c463829f8902.png)

Here is the color scheme (Note colour1:red is different than the cursor color red):
![screenshot from 2016-08-20 11-45-29](https://cloud.githubusercontent.com/assets/14130567/17832234/c72106a6-66cb-11e6-9aeb-498a33937bf8.png)

Kak as 1) I'm having to use it now, 2) How I'd like it to be, and 3) How it becomes instead:

1) ![as is](https://cloud.githubusercontent.com/assets/14130567/17832272/b56a1c58-66cc-11e6-8c5b-87d8d65d119a.png)
2) ![as wanted](https://cloud.githubusercontent.com/assets/14130567/17832274/b7187e64-66cc-11e6-80ca-52b254d5b89d.png)
3) ![as becomes](https://cloud.githubusercontent.com/assets/14130567/17832275/b89d1a88-66cc-11e6-9f50-801f67d39930.png)

The way I want it to work is fine outside tmux. I think the problem in tmux may be that it's outputting 256 colors but not True Colors (16 million)? Which is odd because I'm using the script on the true color github page to check if it is. That page is here: https://gist.github.com/XVilka/8346728.

And that image to prove it is at the very top of this post.

**Comment by mawww** [comment]
Hello,

Thanks for the very detailed report,

I'd need to investigate a bit more, but to add a bit of context, Kakoune does not support (yet) True Colors in terminal, it will use the 256 color mode, changing the palette if possible to match exactly the asked for colors, or, if that is not possible, projecting to the closest color in the palette.

Could you try to put a breakpoint in ncurses_ui.cc:142 and see if thats hit ?

Cheers,

Maxime.

**Comment by bhajneet** [comment]
As a reminder, kakoune properly displays Tc when outside tmux. Not sure if that's important.

I tried today (I think I updated kakoune in between testing) and it's working inside tmux now. Not sure what fixed it finally. Perhaps restarting my computer may have even done the trick? I'm really at a loss, sorry.

I used gdb and entered these commands (apologies if I'm doing this wrong):

`gdb /usr/bin/kak
break ncurses_ui.cc:142
y [to break on future shared library load]
run
:face PrimaryCursor white,rgb:e57373`

When I exit kakoune, Breakpoint 1 is pending. Though I'm not even sure I did this right. Never debugged C++ before.

That being said, it's working randomly as it should in picture 2, as it did outside tmux. I'll try and see if it was the tmux conf file (restarting computer this time to test).

**Comment by bhajneet** [comment]
Okay, tested with a manual color picker (My eyes aren't that good!). It seems there was some improvement, and that more colors are available now, but still aren't exactly there.

e57373 translates to d75f5f

That being said, the difference is slightly noticeable, but not enough to bother me. Will be nice to see Tc implemented sometime :+1:

**Comment by lenormf** [comment]
I don't think the breakpoint was set properly as `gdb` asked you if you wanted to set it anyway, in case a library loaded in the future had that symbol (which it didn't when you issued the command).

As for `tmux`, I've given up trying to understand why the colors are always toned down in it (that's the best you'll ever get if you want colors). It's an issue that everyone seems to have, but can't explain why we don't have a perfect fix.

**Comment by mawww** [comment]
Seems in tmux, can_set_color() returns false, so we try to project queried colors to the one we expect to be in the existing 256 color palette. Actually the project code might be slightly off because we try to minimze the euclidian distance between queried color and the color palette, which is probably not what we want for colors.

It would be nice to support the true colors escapes, but that basically means getting rid of ncurses and implementing the terminal display ourselves.

**Comment by FreeFull** [comment]
https://en.wikipedia.org/wiki/Color_difference There's a bunch of possible metrics for colour distance, I don't know which one would be easiest to code while still working well enough.

**Comment by lenormf** [comment]
To add to the mystery, I noticed that colors that are used in a face in inverted mode are displayed correctly, e.g. test displayed with a black on white face will be less brighter than text displayed with an _inverted_ white on black face.

**Comment by mawww** [comment]
The problem here is that tmux does not support changing the color palette, only the true color escapes. NCurses does not support the true color escapes, only changing the color palette.

Until one of these two projects implements the needed feature, we cannot do much, short of rewriting terminal output completely without using ncurses.

It might be easier to add color palette modification support to tmux (OSC 4 command).

**Comment by lenormf** [comment]
OSC 4 support was added in `tmux`, as per [314e933914de4096c40e623c793049d26484d53a](https://github.com/tmux/tmux/commit/314e933914de4096c40e623c793049d26484d53a), but that doesn't seem to have changed how colors are rendered. Is there something the editor should do to make use of those escape sequences?

I've broken onto lines that call `can_change_color()`, and the function still returns `false` in `tmux` (but not outside).

**Comment by Screwtapello** [comment]
Kakoune doesn't need to do anything, but ncurses will keep returning `false` until the appropriate terminfo database entry is edited to add the `initc` capability.

For example, put the following into a text file:

    tmux-256color|tmux with 256 color and palette setting,
    	use=tmux-256color,
    	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,

... (note that leading whitespace must be tabs) then run `tic path/to/that/file`. It should create `~/.terminfo/t/tmux-256color`. Then you can set `TERM=tmux-256color` and start Kakoune, and colours should work.

Eventually I'm sure somebody will update the upstream terminal database in ncurses, and this local modification won't be needed.

**Comment by lenormf** [comment]
Unfortunately, that had no effect.

**Comment by Screwtapello** [comment]
The command-line equivalent to ncurses' `can_change_color()` is basically `tput initc && echo "yes"`. You can test it yourself with `tput initc P R G B` where `P` is the palette entry number, and `R`, `G`, and `B` are numbers from 0-1000 representing the intensity of the respective colour. Pipe the output of `tput` to `hexdump -C` to confirm it is actually producing the correct OSC 4 sequence.

**Comment by lenormf** [comment]
The escape sequences are produced correctly, still the colors are off when I open a highlighted file in `tmux`, as if they were still being approximated (as opposed to being set in palettes using OSC4).

**Comment by lenormf** [comment]
`can_change_color()` still returns `false` in the editor (I checked with `gdb`), and no errors related to OSC4 seem to be recorded by `tmux` (`show-messages -T`).

**Comment by mawww** [comment]
if `can_change_color()` returns false, you wont get any feedback from tmux as kakoune wont even try to change colors. AFAIK `can_change_colors()` returns a value directly from terminfo.

**Comment by lenormf** [comment]
Does this mean `tmux`'s terminfo entry for `tmux-256color` has to be fixed, or can we do something on our side?

**Comment by mawww** [comment]
terminfo entry has to be fixed, or you can use another value for `TERM` that might work for you. Nothing to do on Kakoune side.

**Comment by lenormf** [comment]
I got things to work, documented in #1871.
