### ISSUE TITLE
View port issues

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#763]
Hi,

imagine the following file:
```
lorem
lorem
lorem
~
~
~
```
plus many more empty lines

After executing the following: `%slorem<ret>`, the screen looks like:
```
lorem
~
~
~
~
```
so if I decide to change the contents with `c`, I can't interactively see it happening. I only see the last 'lorem'

Similarly,

begging with the following file:
```
lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem




Hello lorem


```
(add even more 'lorem's to make the first line very long)

Then, when I search for lorem (`/lorem<ret>`) and continue my search with `n` till I get to `Hello lorem`, my view is shifted to the right and I only see `lorem` but not the `Hello ` any more

**Comment by doppioandante** [comment]
#515 maybe is related.

**Comment by kurkale6ka** [comment]
Thanks @doppioandante.

As @mawww suggests in https://github.com/mawww/kakoune/issues/515, using `scrolloff` (`set global scrolloff 3,40`) solves my second issue.

As for the first one, `vv` works fine but automatically displaying everything would be better since the only matches are at the top

**Comment by kurkale6ka** [comment]
Actually `set global scrolloff 3,40` is not a good solution because then even with normal navigation content can become invisible on the left (since I always display 40 to the right).

`vv` is not good either in cases where I have more that half a screen of `lorem` lines.

Solution?: always display as much as possible from the top and from the left

**Comment by lenormf** [comment]
>Solution?: always display as much as possible from the top and from the left

That seems rather arbitrary as there some cases where you want to be able to see what's under/on the right of the selection.

**Comment by mawww** [comment]
Yeah, its pretty tricky to chose a behaviour that's satisfying for all use cases here. The current logic is "scroll as minimum as possible to ensure the main selection is wholly visible, favor cursor".

In your specific case, you can do `vb` to push the main selection on the bottom on the screen, you'll then get as many "lorems" as possible displayed.

For horizontal alignement, its the same problem, here you'd like to autoscroll back to line begin, but sometimes we want to keep view move to a minimum. We could try to be smarter and use a more complex behaviour to try to guess what to do, but I dont think all the added complexity is worth it (more complex code, less easy to predict behaviour).
