### ISSUE TITLE
mingw build

### ISSUE THREAD

**Issue by Swoorup** [mawww/kakoune#764]
I have to use windows quite a bit. Is it possible to compile this under Mingw64 compiler, not cygwin though? 

I am using msys2. 

Are there are plans yet to port to native windows?

**Comment by mawww** [comment]
Hello,

Porting to native windows would be a big design change, as it would mean not relying on posix tools anymore, which would break every kak scripts under the sun. Thats not planned.

I use Kakoune under cygwin at work, more recently I have been experimenting with WSL, which seems to work ok (and have much better performance, especially for `fork`). For msys2, my understanding is that it lacks boost support.

If you can build boost manually on msys2, you should be able to compile Kakoune as well.
