### ISSUE TITLE
Allow comments containing delimiters in % tokens

### ISSUE THREAD

**Issue by doppioandante** [mawww/kakoune#784]
Currently something like this
```
hook ..something... {
    # comment with }
}
```
Doesn't work because `get_until_closing_delimiter` (command_manager.cc) treats the `}` inside the comment as the closing brace.
I believe that the same happens when using different delimiters but I have not tried.

**Comment by mawww** [comment]
Thats tricky, up to now, Kakoune considers a %...{....} token as a literal string (the eventual sh/val/.../ tells it how to expand the string afterwards). The change you request would require Kakoune to know the semantics of the contained text (that `#` starts a comment).

**Comment by doppioandante** [comment]
What about calling `parse` recursively on the string literal when it is not a shell expansion?

**Comment by mawww** [comment]
We dont know if thats correct or not, maybe the string is an option value, and the user wants a line with `#` in it, or its a list of commands, and `#` is a comment, or its a key list, and `#` must be passed as a keypress...

**Comment by mawww** [comment]
The point of the %{...} style quoting is to avoid the problem you regularly have in shell, when you have to manually add a (or multiple) `\` in front of every separator. %{...} support nesting of the separator, but if you want to it contain unbalanced `{` and `}`, my advice would be to use another separator for the string, like %[...] or %<...> or %(...) or %~...~

**Comment by lenormf** [comment]
This happened to me a while ago, usually when regex or shell script are involved you can use `%!…!`, which arguably should fit most snippets. Or just always make sure parsing isn't messed up by a stray character in your code the way it happened, sometimes you don't get an error when that's the case.
