### ISSUE TITLE
Assign <ret> to something useful

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#786]
Currently `<ret>` is a noop in normal mode.
It'd be very handy to implement for it the following behaviour (same as Vim):

move [count] lines downward, on the first non-blank character

this map comes close to it but goes to the very beginning of the line instead of the first non blank char: `:map global normal <ret> jgh`

**Comment by lenormf** [comment]
Even though I agree in principle, this will conflict with scripts like `grep.kak` that use `<ret>` to jump to specific locations in buffers.

**Comment by kurkale6ka** [comment]
I think scripts could use mappings (open file in grep's case) that override the default behaviour

**Comment by lenormf** [comment]
Actually I was thinking about adding an `-override` flag to `onkey` that would be used over any already existing mapping. @mawww ?

**Comment by lenormf** [comment]
Here's a way to implement that feature:

```
hook -group custom-normal-bindings global NormalKey <ret> %{
    try %{
        exec <a-x>X1s\n(.)<ret>I<esc><space>
    }
}
```

HTH.

**Comment by kurkale6ka** [comment]
Hmm, the problem is I use `addhl dynregex '%reg{/}' 0:default,rgb:373b41`, so then I would have highlighted start of lines for every Enter hit

**Comment by lenormf** [comment]
You can use `-save-regs /` to prevent that register from being modified.

**Comment by mawww** [comment]
I think keeping ret free to be bound by filetype specific support is still the best solution for now (things like grep/make buffers, having the freedom to bind ret to "jump to result under cursor" seems nice).

Besides, I dont think we have any strong candidate for what `ret` would do.
