### ISSUE TITLE
Support true color escapes

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#788]
Hi,

It would be nice to handle true color (without modifying the palette), for several reasons that have started piling up recently:
- seamless rendering of color schemes within/outside tmux, which doesn't support modifications to its palette (see issue #762)
- display raw escape sequences, which isn't possible with `ncurses`, to:
  - allow rendering man pages within `kakoune` the same way `less` does it in the terminal (using the `LESS_TERMCAP_*` environment variables)
  - allow the use of tools like [highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php#ch1_2) to handle highlighting automatically: allowing a tool to -optionally- fully handle highlighting would make up for a lot of holes in kak's syntax highlighting support

`ncurses` could stay as a helper to handle the differences between terminals I suppose, as I'm only interesting in having more control over rendering itself.

Discuss.

**Comment by lenormf** [comment]
As per [an issue I created](https://github.com/tmux/tmux/issues/552#issuecomment-250099037) on the `tmux` repository, the maintainer of the `tmux` project won't implement changes that would allow palette switching, but he's willing to accept contributions.

Since `ncurses` [cannot technically detect 24bits support](https://lists.gnu.org/archive/html/bug-ncurses/2013-10/msg00007.html) because of the 16bits encoding in the terminfo, we're left with implementing parsing of OSC 4 sequences and making a PR to `tmux`, or removing `ncurses`.

**Comment by Screwtapello** [comment]
ncurses 6.1 and higher *can* handle direct-colour output... with some awkwardness. See #1807.

**Comment by mawww** [comment]
Closing this in favor of #1807
