### ISSUE TITLE
Fast keystrokes missed

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#789]
Hi,

Sometimes I type too fast for `kak` to catch my keystrokes when they are too close to each other, which is annoying. My best usecase is `<a-a>p`, which allows me to see the `autoinfo` menu popup and then disappear as I hit `p`, but no selection is made.

Can this be fixed ?

Thanks.

**Comment by greduan** [comment]
So then there's lag, or does `kak` actually skip over keystrokes?

**Comment by FreeFull** [comment]
Try binding an action to `p`, to see if kakoune is actually receiving `p<a-a>`

**Comment by FreeFull** [comment]
I've experimented by rebinding `<a-a>` and `p` to do something else. It seems the `<a-a>` always gets through, but the p ends up getting lost

**Comment by mawww** [comment]
So after investigation, the most likely is that `alt` is still pressed for a short time when `p` is pressed, leading to `<a-a><a-p>` being sent instead of `<a-a>p`, its a bug in the hand movement control software, cant be fixed on kakoune's side :D

**Comment by lenormf** [comment]
My fix:
```
map global object <a-p> p
```
