### ISSUE TITLE
"Repeat last movement and extend selection" key

### ISSUE THREAD

**Issue by greduan** [mawww/kakoune#794]
Would be nice to have a key that "repeats last movement and extends selection".

So for example, do `}p` and we get the following (inside `[]` is selection):

```
[paragraph 1
]
paragraph 2

paragraph 3
```

Then we press a special key and we'd get:

```
[paragraph 1

paragraph 2
]
paragraph 3
```

And again:

```
[paragraph 1

paragraph 2

paragraph 3
]
```

And this'd allow us to give a count param to any movement, since the movement itself doesn't have to know how to handle it, we can just do `}p2<special key>` and that'd do `}p` and repeat it 2 times (with the extending variation).

**Comment by lenormf** [comment]
I think your example has to be fixed, this is what we would get if the "repeat" key was to work:
```
[paragraph 1
]
paragraph 2

paragraph 3
```

Otherwise the "extending" operation would stay stuck in the first paragraph.

**Comment by greduan** [comment]
@lenormf Oh yes very good point, thank you. Fixed. :)

**Comment by doppioandante** [comment]
It reminds me of http://wikemacs.org/wiki/Expand_region

**Comment by greduan** [comment]
@doppioandante yeah sorta. Except that works on whatever is the most appropriate region to expand, while we would work with the same expand movement every time it was pressed.

**Comment by mawww** [comment]
I think the `<a-.>` feature is sufficient for that, closing.
