### ISSUE TITLE
Allow arrows + h,l and maybe backspace to wrap around newlines

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#796]
So:
- with cursor at beginning of line, `<left>`, `h` and `<backspace>` to move at above's EOL. in normal/insert mode
- idem for `<right>` and `l` but in the reverse direction

**Comment by lenormf** [comment]
It has been considered previously, here what came out of it:

```
mawww_hk        I am wondering if h/l should really block on eol, they could be more generally "go to previous/next character" and just continue to the next/previous line
mawww_hk        Any opinions on that ?
ironzorg        <a-h> and <a-l> wouldn't make much sense if that was the case
mawww_hk        you mean the link between <a-h> and h, <a-l> and l ?
ironzorg        yes
mawww_hk        thats true
ironzorg        also what about merging multiple selections when using h/l
ironzorg        that's going to be a headache
mawww_hk        Good point about multi selection, sometimes you really want to block on eol
mawww_hk        Ok thats enough to convince me its a bad idea
mawww_hk        I am surprised we never had a need for a "next char" "previous char" command actually, it seems like one of the most basic primitives in text edition
```

**Comment by kurkale6ka** [comment]
I am not sure what the problem is with merging selections? Still thing this would be a good idea. Sometimes you are at the begging of a line and you just want to go back to the EOL of the previous line. `kgl` feels a bit clumsy

**Comment by mawww** [comment]
The problem arise when you have multiple selections on consecutive lines, with wrapping h/l you cannot rely anymore of h/l blocking at first/last char of the line, it will wrap and merge with the one on next line.

Its not a big problem its more that we are used to be able to rely on that, and changing it will make Kakoune less forgiving to lazily holding h/l.

That said, we used to prevent l from going on end of line character, and we removed that, and it works pretty well in the end. It might be worth it to experiment with wrapping h/l.

**Comment by Delapouite** [comment]
Ongoing experiment starting from : https://github.com/mawww/kakoune/commit/2a60af25dc9d065434875d38377305f6136bd95e

**Comment by mawww** [comment]
Thats now in, and there has not been any massive push backs, I like it, and I believe it goes in the right direction as we handle EOL more and more as any other character. I think its here to stay, so this issue is now fixed :)

BTW @kurkale6ka if you ever have a bit of time for that, would you give us a bit of feedback on what made you switch back to vim (just curious, no pressure).

**Comment by kurkale6ka** [comment]
Hi @mawww. I haven't used kak for very long so whatever I say now won't be accurate but here is a list of things I had put down at the time:
https://github.com/kurkale6ka/kakoune-extra/blob/master/README.md
Feel free to ask for precisions and I will try my best to explain. Regards.
