### ISSUE TITLE
Markdown code sections missing languages.

### ISSUE THREAD

**Issue by jpfeltracco** [mawww/kakoune#808]
I've been using markdown.kak for some markdown note taking with code sections and I came across two problems.

1. Syntax highlighting only seems to support sh, fish, and ruby right now. I messed around with [this line](https://github.com/mawww/kakoune/blob/master/rc/base/markdown.kak#L18) and was able to get c/cpp/java syntax highlighting working by copying the lines for sh/fish/ruby and replacing those names with c, cpp, and java. It would be nice for that list to include all supported languages.
2. Also, when I added a code section for c in a .md markdown file, the next time I opened the file the highlighter was set for c, not for markdown. I "fixed" this by squashing [these mimetype hooks](https://github.com/mawww/kakoune/blob/master/rc/core/c-family.kak#L21) but I'm sure there's a better solution to this.

**Comment by lenormf** [comment]
There's no way to get a list of all the languages supported by the highlighting engine from within `markdown.kak`, so this list of languages in the markdown support script has to be edited by hand (which you did correctly). Don't hesitate to create a pull request if you feel like some languages are missing.

If the detected mimetype for your file is `c` (which happens whenever there's more C than markdown in your file), the `mimetype` variables will be set to `c`. This mimetype detection is done automatically by the `file` utility when the buffer is opened, but I think will have the priority over extension checks (which are done generally sooner, when the buffer is created). This is a real issue that needs to be fixed, but I've come to work around it [in my scripts](https://github.com/lenormf/kakoune-extra/blob/master/bitbake.kak#L15), maybe you can use that too.
