### ISSUE TITLE
Wrap it

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#810]
A few motions would greatly benefit from wrapping capabilities + it would make things more consistent:
- `f/t` to wrap after end of file, `<a-f/t>` to wrap before start of file (similar to `n/<a-n>`)
- `m/M` to wrap after EOLs (+ end of file of course)
- arrows + `h/l` to wrap around lines, start/end of file (https://github.com/mawww/kakoune/issues/796)

**Comment by maximbaz** [comment]
All of this is already implemented, correct? Can be closed then?

**Comment by mawww** [comment]
f/t does not wrap at EOL, but I dont think that will happen.
