### ISSUE TITLE
Startup commands are executed before parsing kakrc

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#812]
Hi,

My kakrc contains the following:
```
map global normal d \"_d
```
However, if on a file such as 
```
abc
def
ghi
```
I call `kak $file -e "exec 'xy%dR'"`
then the content is unchanged, whereas I expect it to be
```
abc
```

Would it be possible to parse kakrc before executing the commands, so that the mappings are considered?

Thanks.

**Comment by mawww** [comment]
Hello,

actually, initial commands are executed *after* sourcing kakrc, whats happening here is that the `:exec` command does not follow mapping by default, if you want mappings to be respected, use `:exec -with-maps ...`.

**Comment by occivink** [comment]
Ah I see, I shouldn't just assume how the implementation is done.
What do you think of having `exec` respect mappings by default, and optionally ignore them? I think it is more intuitive.
Although all scripts would have to explicitly ignore them.

**Comment by lenormf** [comment]
Cross-reference to #707.
