### ISSUE TITLE
Linux (non-debug) binary size is 33MB - but can be 2MB using strip

### ISSUE THREAD

**Issue by rlofc** [mawww/kakoune#813]
Consider adding the following to the build rules:
`strip -s -R .comment -R .gnu.version ./kak`

**Comment by mawww** [comment]
Hello,

I wonder if we should do that in the Makefile, or let the distribution packaging scripts do the job.
I'd favor the latter, as having the debug symbols available in non-debug builds is still pretty useful to get a callstack/to run in gdb.

Another option would be to strip debug symbols in make install.

**Comment by jubalh** [comment]
Definitely this is a job that distributions do.

For example if you install kakoune from openSUSE it only has 2.2 MB in size. And there is a seperate debug-symbol package provided.

**Comment by lenormf** [comment]
Agreed, stripping symbols is the responsability of packagers, but I guess people who build the project in non debug mode would be happy to have a stripped executable (a simple `strip -s` will do, no need to be too specific about the section names).

**Comment by greduan** [comment]
Maybe a `make build-stripped` or something?

**Comment by rlofc** [comment]
Sounds good! We could also follow https://www.gnu.org/prep/standards/html_node/Standard-Targets.html and use `make install-strip` perhaps?
