### ISSUE TITLE
Recursive regex search fails in medium sized source files.

### ISSUE THREAD

**Issue by rlofc** [mawww/kakoune#816]
Getting `Regex searching error: Ran out of stack space trying to match the regular expression` when activating the following shortcut:
`map global normal = %{:exec /\{([^{}]|(?R))*\}<ret><ret><a-;>;}`
In the beginning of `kakoune/src/selection.cc` for example.

Context: I'm trying to implement a way to quickly traverse matching blocks of code.

**Comment by rlofc** [comment]
In the meantime I learned of what seems to be the better way to do what I wanted:
`map global normal = 'f{m<a-;>;'`

**Comment by lenormf** [comment]
Basically your regex backtracks too much, you'll have to simplify it (or allow a higher stack size for your process which I wouldn't recomend).

The only thing with your second binding that might be annoying is that it will make you enter parent scopes, and jump through all its inner scopes if there are any (lambdas, dictionaries, etc according to the language you're using it in).

Here's what I would do to jump only to parent scopes:
```
:reg ^ ''<ret>
Qzf{m;Zm;Q
```

Execute the above once (when you're at the top of the file, before any parent scope), then use 'q' to jump to the next parent scope.

**Comment by mawww** [comment]
Hello, there is not much we can do, this is a limitation of the backtracking regex algorithm used by boost regex, some regexes have a pathological behaviour.
