### ISSUE TITLE
Kakoune state not available through environment variable when it contains dashes in its name

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#824]

**Comment by lenormf** [comment]
What state are you refering to ? Do you have an example ?

**Comment by alexherbo2** [comment]
``` kak
decl str foo-bar foo-bar
```

``` kak
echo %opt{foo-bar}
→ foo-bar
```

``` kak
echo %sh{ echo ${foo-bar} }
→ bar
```

**Comment by somasis** [comment]
That's because environment variable names can't contain most special characters. Kakoune should probably be changing it to use `_` in place of `-`...

**Comment by alexherbo2** [comment]
Yep I thought it were possible with `${foo-bar}` but no x)

**Comment by mawww** [comment]
Adding support for that seems doable, but do we really want it, up to now it seems we just use `_` as a word separator in option names. I think it actually would make sense to limit option names to the alphanumeric + underscore set, as most languages do for variables.

**Comment by somasis** [comment]
That sounds like a better idea
