### ISSUE TITLE
make check causes stack smashes on ppc64 and s390x systems

### ISSUE THREAD

**Issue by dwaas** [mawww/kakoune#828]
Might be some issue regarding big-little endianity.

LINKS:
Project with make check enabled:
https://build.opensuse.org/package/show/editors/kakoune

In particular

ppc64 build logs:
https://build.opensuse.org/package/live_build_log/editors/kakoune/openSUSE_Factory_PPC/ppc64

OR

http://paste.opensuse.org/94344488

s390x build logs:
https://build.opensuse.org/package/live_build_log/editors/kakoune/openSUSE_Factory_zSystems/s390x

OR

http://paste.opensuse.org/3487891

EDIT: added logs on pastebin

**Comment by mawww** [comment]
Thanks for the report, I am looking at how to setup a qemu ppc64 vm to reproduce that.

**Comment by dwaas** [comment]
In the case you actually don't manage to but still have a rough idea of where the code might cause issues I can get my hands on both architectures and eventually contribute.

**Comment by mawww** [comment]
Well, seems emulating ppc64 on x86_64 is very slow, so setting up a machine and building Kakoune does not seems practical. I tried to see if there are some free shell services on ppc64/sparc servers, but did not find any.

If you can try to build a non optimized version on a big endian arch, and run it with stack protector, or valgrind, the bug should reproduce on startup. With a more detailed callstack I might understand what is going one.

Cheers,

Maxime.

**Comment by k0da** [comment]
@mawww @dwaas You can have a public VM for debugging purposes over http://openpower.ic.unicamp.br/minicloud/

**Comment by mawww** [comment]
@k0da Nice, I'll try to set that up to debug this issue, thanks for the link.

**Comment by dwaas** [comment]
Thanks a lot for fixing, Maxime. The build seems to be fixed on both architectures.

BUILD LINK
~~~~~~~~

https://build.opensuse.org/package/show/home:dwaas:branches:editors/kakoune

**Comment by mawww** [comment]
Thank for the report.
