### ISSUE TITLE
Yanking Multiple Selections to Different Buffer

### ISSUE THREAD

**Issue by bhajneet** [mawww/kakoune#829]
* Shift+C multiple lines
* y
* change buffer
* p

Only pastes first line's selection even though yank on first buffer outputs: 

`yanked XX selections to register"`

Edit: Actually this doesn't even have to do with switching buffers. It simply only pastes as many selections are available. Is this intended? I have to create the same number of selections to paste multiple selections in a different area?

**Comment by doppioandante** [comment]
I think you want alt-p.

**Comment by bhajneet** [comment]
Not sure why one would want to only paste one selection after copying multiple, but the control option is nice. Can always re-hook on my end. Thanks @doppioandante

**Comment by mawww** [comment]
If you have multiple selections while pasting, `p` will paste first yank on first selection, second yank on second selection, third on third... single selection is not treated as a special case, so you get the first yank only. `<a-p>` will paste all yanks on all selections.
