### ISSUE TITLE
Shell arguments lost across an `eval` scope

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#835]
Hi,

Consider the following snippet:
```
def -params 1 foo %{ eval %{
    nop %sh{ echo "$1" >&2 }
} }
```

Upon calling `foo` with an argument, the debug buffer will print an empty line, as it seems that arguments are not passed over from the function's body to the shell scope.

HTH.

**Comment by mawww** [comment]
It is the 'eval' here that loses the arguments, this would be working if you get rid of the eval wrapper.
