### ISSUE TITLE
Easy multiple selections

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#838]
Hi,

It would be good to have an easier way to get multiple selections.
Sometimes you need 3/4 selections but there is no easy regex for it. So then the only option is to do the following:

- Select your first selection
- `Z` 
- Select your 2nd selection
- `<a-z>`
- `Z`
- Select your 3rd selection
- `<a-z>`

It would be useful to implement `<c-left click>` say to simply add to the current selections. Example:

- Select your first selection
- Hold `Ctrl` and select your 2nd selection
- Hold `Ctrl` and select your 3rd selection

**Comment by occivink** [comment]
This is also something I've encountered. While multiple selections with the cursor would be nice, I think this is an area where the default keyboard navigation could be improved (not that I have any suggestions atm).

**Comment by alexherbo2** [comment]
Agreed with that.

**Comment by alexherbo2** [comment]
How about a way to freeze selections?

**Comment by lenormf** [comment]
You mean `-draft` ?

**Comment by alexherbo2** [comment]
No, something like a freeze selections command so that selections keep visibles and you can move around, select something, freeze, etc. then unfreeze – which selects previously frozen selections.

**Comment by lenormf** [comment]
How about working on a scratch copy of the current buffer, and appending/overwriting the selection register of the original one with the selection description created in the copy?

**Comment by occivink** [comment]
>How about a way to freeze selections?

I think marks are not too far from being able to do that, it's just that they're not very visual by default. I tried adding an highlighter for the currently marked regions, but I couldn't get it to work properly and it's quite awkward:

```
decl -hidden range-faces marks
face marked black,green
hook global WinCreate .* %{
    addhl ranges marks
}
hook global NormalKey Z %{
    set buffer marks %sh{
        echo "${kak_reg_caret}" | sed -e 's/\([:@]\)/|marked\1/g' -e 's/\(.*\)@.*%\(.*\)/\2:\1/'
    }
}
```
The issues I've encountered:

- The mark register and range-faces syntax differ a bit. In particular, the mark register is inclusive of the last character in a region, but the range-faces is not.  
- The marks highlighter gets applied before other highlighters so the mark face may be overriden (maybe there's a way to set the order of highlighters but I don't know how).
- The marks register may be modified in other ways than through `Z` and `<a-z>` (need a RegisterModified hook?)
- The need for a timestamp in a range highlighter means that the highlight disappear as soon as a change is made to the buffer (but the marks may still be valid)

**Comment by alexherbo2** [comment]
+1

**Comment by lenormf** [comment]
@occivink 

The `range-faces` should be inclusive, other wise the `spell` command wouldn't work very well.

A new hook for modified registers sounds good, maybe you could create an issue?

The timestamp is needed for ranges, as currently we want the highlighting to go away when the buffer is modified (once again, `spell` command), and you can restore it using hooks (`NormalIdle` and `InsertIdle` maybe ?).

**Comment by occivink** [comment]
>The range-faces should be inclusive, other wise the spell command wouldn't work very well.

Maybe I'm not expressing myself correctly, but a `range-faces` option such as `timestamp:1.1,1.1|face` will not highlight anything (instead of just the first character if it were inclusive). Maybe the `spell` command just uses a past-the-end index?

**Comment by lenormf** [comment]
@occivink according to the documentation (`:doc options range-faces`):

```
range-faces
a : separated list of a pairs of a buffer range (<begin line>.<begin
column>,<end line>.<end column>) and a face (separated by |), except for
the first element which is just the timestamp of the buffer.
```

Which means your example isn't supposed to work in the first place.
