### ISSUE TITLE
add default value to `edit -scratch` command

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#849]
How about `edit -scratch` to edit `*scratch*` buffer?

**Comment by lenormf** [comment]
Why ?

**Comment by alexherbo2** [comment]
It’s a sensible default value, less to type.

Plus `*scratch*` is the default scratch buffer name when running `kak` with no argument.

**Comment by casimir** [comment]
If so, `edit -scratch` == `edit *scratch*`?

**Comment by alexherbo2** [comment]
No, `-scratch` flag defaults to `*scratch*`.
