### ISSUE TITLE
create / regenerate *scratch* buffer when deleting last buffer

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#850]
How about to create / regenerate the `*scratch*` buffer when deleting the last buffer?

**Comment by lenormf** [comment]
I think it's better if that behavior is handled by a script, for instance:
```
hook global BufClose .* %{ %sh{
    for i in $(printf %s "${kak_buflist}" | tr : '\n'); do
        if expr "${i}" : '^[^*]' >/dev/null; then
            exit
        fi
    done

    echo 'edit -scratch *scratch*'
} }
```

The above works, except I get the following exception when quitting `kak`:
```
terminate called after throwing an instance of 'Kakoune::assert_failed'
```

**Comment by alexherbo2** [comment]
I think it’s better to not relying on scripts.

Kakoune always has to have a buffer.

So it’s a sensible default behaviour to have the `*scratch*` buffer to the rescue.
