### ISSUE TITLE
Env var 'kak_reg_<r>' is not exported for some values of <r>

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#853]
Hi,

It seems like the environment variables `kak_reg_<r>` are not exported when `<r>` is outside of the range `A-Za-z0-9_` (might be shell-dependant). Which is unfortunately most of the default ones.

**Comment by mawww** [comment]
That was already supported, but undocumented, should be fixed now.

**Comment by occivink** [comment]
Thanks. I think maybe you meant hash instead of dash?

**Comment by mawww** [comment]
Yeah, good catch, fixed
