### ISSUE TITLE
focus command doesn't work for iTerm clients

### ISSUE THREAD

**Issue by casimir** [mawww/kakoune#854]
The AppleScript API doesn't seem to allow that. Maybe It is possible with env variable and more AppleScript to talk to the compositor.

**Comment by mawww** [comment]
Can the http://iterm2.com/documentation-escape-codes.html `^[]1337;StealFocus^G` escape sequence help here ? something like `printf '\033[1337;StealFocus\b' > /dev/tty` ?

**Comment by mawww** [comment]
This was fixed
