### ISSUE TITLE
Don't expand the `~` character in buffers when completing file names

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#855]
Hi,

Sometimes the auto expansion of the `~` character into the value of `$HOME` gets in the way when trying to write shell scripts, since it will insert a system-dependant path and break portability. I end up manually replacing the prefix that was inserted back with `~` after completing a complex path, it's a bit cumbersome.

Can this behaviour be modified, or at least controlled?

Thanks.

**Comment by mawww** [comment]
To make sure I get that correctly, are we talking about insert mode here, or command mode, or both ?

**Comment by lenormf** [comment]
Only insert mode, I don't mind the expansion in the prompt mode (it's even preferable to expand the paths in the prompt mode I should say).

When I insert a `~` character, I'd like the completion to append to it, not replace it.
