### ISSUE TITLE
Replace operations modify the parent scope's selection even when in a draft

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#857]
Hi,

When a selection has been made and some characters on the same line (before the selection in terms of columns) are replaced in a draft, the selection is modified.

This is due to the way the underlying implementation of the replace operation is executed, it basically removes the characters and then inserts the replacement ones, which modifies the selection regardless of the draft.

To reproduce this issue, modify [my sokoban script](https://github.com/lenormf/kakoune-extra/blob/master/games/sokoban.kak#L243):
- enable (uncomment) the selection of holes: `select %opt{_sokoban_holes}`
- remove the `FIXME` comments and the `select` line that they're associated with
- load level 0 with the following command: `:sokoban 0`

Thanks.

**Comment by occivink** [comment]
For a simpler reproducer, `:exec -draft ca<esc>` shifts the selection instead of leaving the cursor in place.

**Comment by mawww** [comment]
Thats totally normal, `c` deleted the selected text, leading to a single char selection, once we get there `a` will not extend that selection from another context.
