### ISSUE TITLE
Kakoune freezes when trying to connect to a suspended session

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#866]
Hi,

I was trying to connect an already existing -but suspended- session, and the whole client/server seem to have been left in a weird zombie state where the screen is completely cleared and the client unresponsive.

Reproducing steps:
* start a client `kak -n`
* suspend the process with `^Z`
* connect to this suspended session `kak -c 1234`

I understand that it doesn't really make sense to try to open files in a suspended session, but maybe this could be detected (and the target session resumed)?

Stacktrace:
```
#0  0x00007f3e452bf367 in kill () from /usr/lib/libc.so.6
#1  0x00007f3e45f0b41a in ?? () from /usr/lib/libncursesw.so.6
#2  <signal handler called>
#3  0x00007f3e452bf04f in raise () from /usr/lib/libc.so.6
#4  0x0000561baaf255be in ?? ()
#5  <signal handler called>
#6  0x00007f3e452bf04f in raise () from /usr/lib/libc.so.6
#7  0x0000561baaf0755a in Kakoune::NCursesUI::get_key() ()
#8  0x0000561baae963ff in Kakoune::Client::get_next_key(Kakoune::EventMode) ()
#9  0x0000561baae9aff6 in Kakoune::Client::handle_available_input(Kakoune::EventMode) ()
#10 0x0000561baaf066f8 in ?? ()
#11 0x0000561baaf1d760 in Kakoune::FDWatcher::run(Kakoune::EventMode) ()
#12 0x0000561baaf1df49 in Kakoune::EventManager::handle_next_events(Kakoune::EventMode, __sigset_t*) ()
#13 0x0000561baaf2e93c in run_server(Kakoune::StringView, Kakoune::StringView, bool, bool, bool, UIType, Kakoune::ArrayView<Kakoune::StringView const>, Kakoune::BufferCoord) ()
#14 0x0000561baae680ce in main ()
```

HTH.

**Comment by mawww** [comment]
This happens because we do not fork the server to the background on suspend if we have a single client (the local one).

If we want to support that, I think we shoud rather just bite the bullet and always for the server. There starts to be too much, too complicated code for handling all the special cases.

**Comment by lenormf** [comment]
I understand, it's not a big deal. I'll close this for now.
