### ISSUE TITLE
Counts with newline commands

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#873]
Hi,

I think it'd be useful if you could prefix a count to `o` and `O` which would specify the number of new lines to create. All the new lines would then be individually selected.

**Comment by mawww** [comment]
Thats an interesting feature, I'd like however to have a good motivating use case for it, right now I only can see vimgolf like challenges that would benefit from that. Do you have an actual kind of editing you wanted to make that would have benefitted much from opening multiple lines at once ?

**Comment by occivink** [comment]
Sure, it's actually out of practical concern that I'm asking. The main use-case for it would be to insert similar elements that follow one-another. 

For example if you're adding (n) member functions to a class, you could open (n) new lines and write the common parts all together, before reducing the selections and completing the unique parts individually.

Or if you want to complete to initialize a map like that:
```
auto map = new_map()
map["foo"] = "bar"
map["abc"] = "def"
map["kak"] = "vim"
```

I think it'd be nicer than writing the first element and then copying it as many times as needed.

**Comment by lenormf** [comment]
I could use this as well, it's always a bit annoying to write a boilerplate, yank it, and then paste using a count.

**Comment by occivink** [comment]
I could also imagine opening consecutive cursors on the current line after the cursor by pressing `<count>i` but it's a bit harder thinking of a use-case, I don't think I've ever needed it.

**Comment by occivink** [comment]
Thanks!
