### ISSUE TITLE
Autorestore won't work on mac os

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#874]
Hi,

I noticed this issue while writing a basic test for #871, basically I think the `find` call in `autorestore.kak` works only with `GNU/find`, but not with whatever implementation is installed on macs.

HTH.

**Comment by greduan** [comment]
Just by looking at the manpages one can figure out what the difference is and what's causing the problem in this case (I don't knowit). But basically GNU `find` is not POSIX compatible.

So we're using a non-POSIX feature in the `autorestor.kak` script.

**Comment by lenormf** [comment]
What "feature" are you refering to? [The POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html) defines a set of flags that are implemented by `GNU/find`, so it's definitely compliant.

What would actually be useful is to know the specific differences between the gnu and bsd implementations. Feel free to do it if you want to help.

**Comment by casimir** [comment]
I don't think `-delete`, `-readable` and `-printf` exist on macOS. I will check when I can acces my MacBook.

**Comment by mawww** [comment]
658d993d7190839c3a854b81080e407ec2406f11 should have fixed it, @lenormf could you rebase your tests to check that ?

**Comment by lenormf** [comment]
It seemed to have worked, I also applied the following changes (won't be included in the PR):
```
diff --git a/rc/extra/autorestore.kak b/rc/extra/autorestore.kak
index e5a8ccf..18b77ef 100644
--- a/rc/extra/autorestore.kak
+++ b/rc/extra/autorestore.kak
@@ -6,14 +6,14 @@ def autorestore-restore-buffer -docstring "Restore the backup for the current fi
     %sh{
         test ! -f "${kak_buffile}" && exit
 
-        buffer_basename=$(basename "${kak_buffile}")
+        buffer_basename="${kak_buffile##*/}"
         buffer_dirname=$(dirname "${kak_buffile}")
 
         ## Find the name of the latest backup created for the buffer that was open
         ## The backup file has to have been last modified more recently than the file we are editing
         ## Other backups are removed
-        backup_path=$(find "${buffer_dirname}" -maxdepth 1 -type f -name "\.${buffer_basename}\.kak\.*" \
-                           \( \( -newer "${kak_buffile}" -exec ls -1t {} + \) -o \( -exec rm {} \; \) \) 2>/dev/null)
+        backup_path=$(find "${buffer_dirname}" -maxdepth 1 -type f -name "\\.${buffer_basename}\\.kak\\.*" \
+                           \( \( -newer "${kak_buffile}" -exec ls -1t '{}' + \) -o \( -exec rm '{}' \; \) \))
 
         if [ -z "${backup_path}" ]; then
             exit
```

I got rid of the unecessary call to `basename` and escaped characters properly. Sucks that `-delete` isn't POSIX because supported by both `GNU/find` and `BSD/find`, it would have avoided another unecessary process.
