### ISSUE TITLE
Special characters in the commenting options allow injections

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#875]
Hi,

As per one of the tests from #871, it's possible to mess up the selection commenting process because of unproper escaping of the commenting options (characters).

**Comment by mawww** [comment]
Thats a `commenting.kak` bug, isnt it ?

**Comment by lenormf** [comment]
Yes it is, and it's tricky to fix because any character can be used for commenting selections, which means it's always possible to inject code according to what character is used to make the scopes.

**Comment by occivink** [comment]
This didn't get close when merging. Also nice rebase spam
