### ISSUE TITLE
'\n' hook gets executed with the wrong selection when creating line above the first

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#877]
Hi,

If you add a hook like `hook buffer InsertChar \n %{ exec -draft ia }` and press `O` while the cursor is on the first line, the 'a' will be inserted on what is now the second line, instead of on the newly created line (which is what happens if you press `o` or `O` anywhere else). 

There's another issue but it seems related so I'm not going to post it separately yet:
If the first line is empty and the second is anything (even empty), pressing `O` while the cursor is on the second line will make the cursor jump to the first line instead of what should now be the second. 
Illustration:
```
⏎
[a]
```
press `O`
```
[⏎]
⏎
a
```
What is after the second line does not matter, but the empty line needs to be the first to reproduce this.

**Comment by lenormf** [comment]
Nice find, I reproduced the two issues with `kak -n`.
