### ISSUE TITLE
Undo doesn't work when piping into kakoune

### ISSUE THREAD

**Issue by FreeFull** [mawww/kakoune#881]
Reproduction steps:
Start a new kakoune session where data is piped in from stdin, for example: `echo foo | kak`. Go into insert mode, make any edit and then try to undo. You will get the message `nothing left to undo`.

**Comment by mawww** [comment]
Thats expected, its the same behaviour as `:edit file`, when you get the content of the file, you cannot undo. when piping into kak, `*stdin*` content is whatever was written into the pipe input.

**Comment by ff2000** [comment]
On Tue, 18 Oct 2016 23:32:15 -0700, Maxime Coste <notifications@github.com> wrote:
> Thats expected, its the same behaviour as `:edit file`, when you get the content of the file, you cannot undo. when piping into kak, `*stdin*` content is whatever was written into the pipe input.

Probably you missed the important point: pipe into kak AND THEN EDIT in kak => you are not able to undo THE EDITS you did to the buffer.
I would expect this to be possible.

**Comment by mawww** [comment]
Ooops, yep thats a bug.
