### ISSUE TITLE
Replacing `run` with a regular unit testing framework

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#882]
Hi,

The code that handles printing and actual testing has become a bit bloated, and that makes maintaining it tedious work. I understand this is a simple way of running tests, but it's hard to add features to it and it takes a lot of time to execute the entire test suite now that we have 200+ tests.

It's only a matter of time before we reach the breaking point in terms of execution time, so we might as well check if there are good, supported alternatives that would allow use to only care about testing (and not displaying the status, the names, the results etc).

**Comment by mawww** [comment]
I dont really get what you have in mind.

An unit test framework wont be able to run kakoune with various set of keystrokes, gather the relevant output and compare it to the expected one magically, we will need to set all that up, and I doubt it will be cleaner than the `run` script. I dont actually see what a unit test framework will help for there.

We do have C++ side unit tests, they are run at startup at every launches for debug builds.

Can you precise what you had in mind ? And how it would work compared to the `run` script ?

**Comment by lenormf** [comment]
The shell script we have right now takes a lot of time to run all the tests, and it's only going to get worse (because we are going to add more tests), so having a unit tester that doesn't spawn a dozen processes prior to actually doing a test would be nice.

The script has code that handles pretty printing, which litters and clutters the code a bit, we could let whatever unit tester is in use handle that instead of doing it ourselves.

It's complicated to add features to the script, even though we don't need to very often, because of the reason above, but also because it's a big for loop with several conditional branches.

That's why I'm thinking that maybe someone knows of a unit test framework that could allow us to run our tests faster, could handle accessory features such as pretty printing, and possibly lighten the amount of code we have to write and maintain (as of today, the script still isn't POSIX compliant) to make it suit our needs (our needs being sending keystrokes, getting the outputs etc). As time goes, it just looks like we are rewriting a regular unit test framework in shell script, which used to be OK back in the days when it was sufficient, but now that I've started doing individual tests for builtin scripts, I realize that `run` will sooner or later have to be replaced.

**Comment by mawww** [comment]
Closing for now, we will revisit that if the test script really becomes a bottleneck.
