### ISSUE TITLE
`BufWrite` hooks take `buffile` for parameter, and not `bufname`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#886]
Hi,

It looks like the `BufWrite` hooks don't use the buffer's name for filtering, unlike stated in the documentation.

HTH.

**Comment by casimir** [comment]
I'd say this is the interned behaviour (see https://github.com/mawww/kakoune/commit/d50087eabee0fa0067a5f44462782332230bdf3e) but that the doc is out of date.

**Comment by lenormf** [comment]
Good find, but I'd like to understand why the path is passed now, as opposed to the name. @mawww ?

**Comment by mawww** [comment]
We now pass the path so that you can hook on `BufWrite %val{buffile}` and be sure that its only when writing to the associated file that the hook gets executed, instead of whenever the buffer is written (to a temporary file for example).

**Comment by lenormf** [comment]
It sounds specific, but I can't think of a case where we would want to hook a virtual buffer, so OK. Documentation update it is then.

**Comment by mawww** [comment]
"Hook a virtual buffer" ?

**Comment by lenormf** [comment]
Buffers not backed by a file on disk.

**Comment by mawww** [comment]
You can, juste hook on `hook buffer BufWrite .*` (which you can do on any file, if you dont care where its written to)
