### ISSUE TITLE
Have access to counts from `onkey` callbacks

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#890]
Hi,

It'd be nice to have access to counts passed to keys hooked with the `onkey` command, possibly with an expansion from kakoune script and shell.

EDIT: actually having access to counts from any mapping could be nice as well.

Thanks.

**Comment by mawww** [comment]
That seems to be already working: `100:onkey m %{ echo %val{count} }<ret>` does echo 100

**Comment by lenormf** [comment]
I hadn't seen it in the documentation, so I assumed it was undocumented. I'll make a PR to fix this (it's not documented, right?).
