### ISSUE TITLE
Expand `count` in shell scopes

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#895]
Hi,

It'd be good if the `count` variable was made available within shell scopes. It'd also be nice to document this variable (in the `expansions` page I reckon).

Thanks.

**Comment by mawww** [comment]
It needs to be documented yeah, but it is already available in shell scopes. remember that `%val{blah}` *is* `$kak_blah`.

**Comment by lenormf** [comment]
I can't remember what I had tried, but it didn't print the expected count. Just tried with `5:echo -debug %sh{ echo $kak_count }<ret>` and it's working.
