### ISSUE TITLE
Allow counts to be used with maps

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#896]
Hi,

I want to change this map to take a count into account:
`map global normal <c-a> 'h"_/\d<ret><a-i>na+1<esc>|bc<ret>'`

tried this:

`map global normal <c-a> 'h"_/\d<ret><a-i>n:exec "a+1+%val{count}"<ret><esc>|bc<ret>'`
but then when using `5<c-a>` 5 isn't used, 0 is

**Comment by mawww** [comment]
I think moving your `:exec` at the begining will do the trick `':exec "h\"_/\d<ret><a-i>na+1+%val{count}<ret><esc>|bc<ret>"'`

**Comment by kurkale6ka** [comment]
One more issue:
`map global normal <c-a> ':inc %val{count}...'` works as expected
but for
`map global user a ':inc %val{count}...'`
the count passed is always 0
