### ISSUE TITLE
Undo selection change

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#898]
Hi,

It often happens to me that I carefully craft a selection with multiple cursors, ready to make changes elegantly, only to completely mess it up by pressing a wrong key (by merging the cursors for example). Being able to undo the last selection change (even if only until the previous buffer change) would make this much less painful.

**Comment by lenormf** [comment]
[Answer](https://github.com/mawww/kakoune/issues/753#issuecomment-236429855)

**Comment by occivink** [comment]
I think it's a bit different, my issue is more of a feature request regarding selection changes within the same state of the buffer, and not really related to the current undo feature.

**Comment by doppioandante** [comment]
This happens to me all the times. Do you get all your multiple selections perfectly in your workflow?

**Comment by lenormf** [comment]
@occivink The relevant part is:

>I am not sure if we can do much better without saving selections in the undo data, which might be a bit coslty memory wise.

The feature you want would force the editor to save selection modifications, and saving only the last one wouldn't be very consistent, so that's that.

**Comment by doppioandante** [comment]
> The feature you want would force the editor to save selection modifications, and saving only the last one wouldn't be very consistent, so that's that.
One generally needs to undo selections only when multiple selections are used, what about saving the previous selections as soon as there's more than one selection, while we save only the last one when there is only one?

Tangentially,  I think that an hypothetic "undo selection" should be associated to a different command/key than `u`.

**Comment by alexherbo2** [comment]
hook global NormalKey .* %{ %sh{
  selection_count=$(echo $kak_selections_desc | tr : "\n" | wc --lines)
  [ $selection_count = 1 ] || echo exec '<c-s>'
}}

**Comment by occivink** [comment]
That actually works nicely, but it's a shame that you kind of lose the jump-list functionality.

**Comment by alexherbo2** [comment]
Agreed

**Comment by ianthehenry** [comment]
Sublime Text has this feature, and I use it. It does save every cursor and selection modification (coalescing multiple character moves into a single undo item and such), and it offers two undo commands: "undo" (on a mac, cmd+z) and "soft undo" (cmd+u). "Soft undo" undoes *everything* -- cursor moves or selection changes or modifications -- where "undo" continually undoes everything until it reaches the first modification. I use it for these things, in order of frequency:

- I hit cmd-d too many times and selected one too many words (this seems less compelling in Kakoune given range-refinement)
- I jumped somewhere else in the file, and I want to return my cursor to where it was (an after-the-fact mark, like ``` `` ```)
- I flubbed a multiselect (though after six years with Sublime, I have gotten pretty careful)

**Comment by danr** [comment]
Can we put this under a feature request badge or so? It's an oft-asked feature here and on IRC. I'd be happy to use my computer's memory to store millions of cursors from the past :)

**Comment by mawww** [comment]
Yeah, I think I will implement that, because it seems pretty useful, and I realized we only need to store selection changes from the last buffer change (they are not relevant before that). What is still missing is a nice keybinding for it.

**Comment by mawww** [comment]
Yeah, I think I will implement that, because it seems pretty useful, and I realized we only need to store selection changes from the last buffer change (they are not relevant before that). What is still missing is a nice keybinding for it.

**Comment by lenormf** [comment]
>we only need to store selection changes from the last buffer change (they are not relevant before that)

What about the undo-tree, aren't all changes relevant to allow going back/forward in time?

**Comment by danr** [comment]
> we only need to store selection changes from the last buffer change (they are not relevant before that)

I'm also confused about this: I would like to be able to undo several times and have my cursors restore as they were at that point (and not use today's heuristics).

**Comment by occivink** [comment]
@danr I think you're confusing two issues, you're thinking of saving cursors position in the undo tree (#1184) , while this issue is about a potential new selection-undo-stack which would let you cycle between cursors position without modifying the state of the buffer.

**Comment by irisjae** [comment]
Vim had this feature (in a limited form) as `gv`, restoring last selection. I missed it a lot when using kak.

**Comment by geppettodivacin** [comment]
It's been a while since this has been bumped, and it's absence has been my biggest (still minor) annoyance with using kak.

Suggestion for keybindings: gu (back) and gU (forward), since it's really an undoing of a movement command.

If there aren't any plans to look at this in the near future, I can take a look at it when I get a chance. I'd enjoy another excuse to dive into the source.

**Comment by alexherbo2** [comment]
For reference:

``` kak
# Save selections to the [b]ackup register.
hook -group backup-selections global NormalIdle .* %{
  set-register b %reg{z}
  execute-keys -draft '"zZ'
}

# Add a mapping to easily reach the command.
map -docstring 'Restore selections from the [b]ackup register' global user z '"bz'
```

Source: [Restoring selections after accidental clear]

[Restoring selections after accidental clear]: https://discuss.kakoune.com/t/restoring-selections-after-accidental-clear/1366

**Comment by kconner** [comment]
Another case for which I want this feature: Using `f` or `t` and then repeating `<a-.>`, it's easy to overshoot the character you meant to stop at and want to back up one. In vim I use `;` and `,` to iterate both forward and backward, but in oak I think I would need a selection undo to pair with `<a-.>`.

**Comment by mralusw** [comment]
Note for newbies: https://github.com/mawww/kakoune/issues/898#issuecomment-727516233 restores with `,z` (thanks to `map ... global user`). It doesn't seem to be possible to move the mapping to e.g. `global view` or `global goto` (i.e. `gz` or `vz`)

**Comment by alexherbo2** [comment]
Prefix the mapping with `<esc>` to go back in normal mode where `"bz` can be executed.

**Comment by erinkim4** [comment]
(I'm completely new to kakoune and to modal editing, but..)

Wasn't this the entire point of having object-verb grammar? As it is right now, having to start a sentence over in Kakoune seems no different than having to undo and then start over in vi.

from "Why Kakoune":
> vi basic grammar is verb followed by object ... That means that errors are not handled well. If you express your object wrongly with a delete verb, the wrong text will get deleted, you will need to undo, and try again.
> 
> Kakoune’s grammar is object followed by verb, combined with instantaneous feedback, that means you always see the current object (In Kakoune we call that the selection) before you apply your change, which allows you to *correct errors on the go*.

As an additional note, wouldn't backspace be an appropriate key for this in normal mode? Thinking of the editing model as "interactive sentence-building," an undo selection would be "delete one command from the sentence (object of the sentence)"

**Comment by sclu1034** [comment]
@erinkim4 
The point of the object->verb grammar is to interactively build and get visual feedback on your "object" before you have to commit to a "verb".

E.g. in Vim, you have to simply _know_ that `5cw` is the amount of words you want to replace. Only after you typed `w` you might realize that you wanted just four.
In Kakoune, you could instead do a conservative `3w`, pause and verify, add one more `w` and only then commit with `c`. Or you can build an arbitrary sequence of `n` and `<s-n>` if you want to replace very specific occurrences of a search term while leaving others untouched.

It is true that without undo functionality the "correct errors on the go" part is not always possible, especially for the more complex commands. But some selection changes can already be reverted through an opposite action (e.g. `<s-h>` reverts `<s-l>`).

**Comment by erinkim4** [comment]
I understand that, but just having visual feedback doesn't seem to take full advantage of the potential of object-verb grammar. Having opposite actions for everything seems like an ad-hoc solution, and it won't be possible (or easy) for actions that "increase entropy" (e.g. deselect, collapse anchors).

**Comment by erinkim4** [comment]
Update:
I realized that `f` and `t` wouldn't work. Since `map` lacks modes for `f`, `t`, `<a-f>`, and `<a-t>`, I created user modes for each of them, and mapped every single character to execute `<c-s>.`

Working on this "solution" seemed to expose a number of problems with hooks and maps.
- There are no hooks for `prompt`, `goto`, or `object` mode.
- There are no hooks or maps for `f` and `t` modes.
- There are no escape characters for commands.
- Maybe maps could benefit from regex.

Here's the new kakrc, with 468 lines:
https://gist.github.com/erinkim4/94c234778c1e2bced4207865f21dc080

**Comment by krobelus** [comment]
I have an experimental implementation in my [undo-selection-change](https://github.com/krobelus/kakoune/tree/undo-selection-change) branch. Happy to hear feedback on the UI.
I haven't tested it much yet (it's hard to unlearn muscle memory).

**Comment by krobelus** [comment]
Functional implementation [here](https://github.com/mawww/kakoune/pull/4725), this is indeed a very useful and intuitive feature. Naturally, Gimp has had it for years. I wonder if there are other features we can steal from image editors

**Comment by krobelus** [comment]
`<c-l>` is a secret undocumented command to force-redraw the screen (rarely necessary but sometimes useful after scrolling a terminal).
This is from the ncurses influence.

**Comment by tomsaleeba** [comment]
That commit :point_up: introduced this feature in version `2023.07.29`. From [the changelog](https://github.com/mawww/kakoune/releases/tag/v2023.07.29):

> `<a-u>` and `<a-U>` now undo/redo selection changes; the previous meaning of moving in history tree has been moved to `<c-j>` and `<c-k>`

Thanks mawww :smiling_face_with_three_hearts: 💪
