### ISSUE TITLE
Incompatibility with the `mdocml` man implementation

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#901]
Hi,

Several users have reported errors when using the `doc` command:

```
man: No entry for /usr/local/share/kak/../doc/kak/manpages/faq.gz in the manual.
```

I think this error occurs because this implementation of the `man` command won't acccept filepaths as arguments, unlike it's `man-db` counterpart.

**Comment by somasis** [comment]
It actually can accept files names, if you do `man -l /usr/local/share/kak/../doc/kak/manpages/faq.gz` instead.

The better fix may be to just set MANPATH to `/usr/local/share/kak/../doc/kak/manpages/` and run man with the basename...

**Comment by lenormf** [comment]
The `-l` flag isn't POSIX and we can't assume anything as far as directories because they can be changed at compile time.

**Comment by lenormf** [comment]
I tried playing around with the `MANPATH` variable, couldn't get anything to work. It looks like this particular implementation requires a `mandoc.db` file to be generated in the `MANPATH` directory, which is a specific requirement that we can't really enforce (relying on `MANPATH` is already non standard, even though it's widely used).

**Comment by mawww** [comment]
we dont use man pages for internal doc anymore closing.
