### ISSUE TITLE
Have a `lint-prev` command, rename the already existing commands

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#905]
Hi,

Some linters emit lots of false positives, it'd be nice to have a `lint-prev` command to be able to jump to a close error above the current selection, instead of jumping before using `lint-next`.

As for the names, I think they should be more expressive (as fuzzy matching makes completion very easy), e.g. `lint-next` → `lint-jump-next-error`.

**Comment by kurkale6ka** [comment]
Added `lint-prev` here: https://github.com/mawww/kakoune/pull/904/commits/94d6f6d20133c985df1d9fef3064ff85df8738e3

**Comment by mawww** [comment]
I dont think we need to have more explicit command names for now, there is not a lot of things `lint-next` or `lint-prev` could mean, so I'll close that for now.
