### ISSUE TITLE
Incorrect Formatting: Insert space after Asterisk 

### ISSUE THREAD

**Issue by bhajneet** [mawww/kakoune#911]
Reproduce in .md file (start in normal):

`i*<space>test<enter><esc>i<space>`

This leaves a semi-permanent highlighting formatting. After the space, you can exit to normal mode and move the cursor up and down and it will persist. See: 

![1478180722](https://cloud.githubusercontent.com/assets/14130567/19968301/63ab5602-a1aa-11e6-815f-09e16ee9e3a4.png)

**Comment by mawww** [comment]
Hello, whats happening here is that after `<ret>` you already have an `* ` auto inserted, then you insert an additional space, which leads to a double space at the end of the line.

In `markdown.kak` I see we highlight `\H\K\h\h$` with the `PrimarySelection` face. @alexherbo2 do you remember what that is supposed to do, seems using `PrimarySelection` is not a good idea.

I think the auto insert behaviour is correct (copying the start + space), but the highlighting seems wrong.

**Comment by Delapouite** [comment]
I guess this highlighter is used to show double spaces at the end of line which are supposed to be translated to `<br>` in markdown: https://daringfireball.net/projects/markdown/syntax#p

So yeah `PrimarySelection` is probably not the best fit here.
