### ISSUE TITLE
Hook on buffer changes (timestamp?)

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#912]
Hi,

It'd be nice to be able to hook on buffer changes, or more generally to hook on builtin value changes (to hook on `timestamp`).

Thanks.

**Comment by mawww** [comment]
That would require a very strong motivating use case, as hooking on buffer change can really kill performance.

**Comment by lenormf** [comment]
Automated backups of the buffer after a certain amount of time, if the buffer has been changed. Now that I think of it such a hook wouldn't be a very good idea unless the hook was executed asynchronously (or lazily), but it brings me back to having timed hooks.

**Comment by rouanth** [comment]
Hi. I probably have a valid use case for this hook.

I'm currently writing a plugin for kakoune for Coq.
Coq is a language for proving theorems, and it is used interactively. One writes Coq programs while simultaneously running typechecker on every new line.
At all times a Coq interpreter should be able to tell which parts of a buffer were proven and which weren't, and if a change occurs in parts of the buffer that were already proven, then the whole proof must be invalidated.
It would be great to have a hook which on every change signalled which parts were changed. Then it would be a matter of a simple check to see whether the changed parts intersect with the proven ones and invalidate proofs if they do. As for now, I have to manually call a function to check if all the parts that were proven are still the same.

**Comment by danr** [comment]
@rouanth for that use case it might be enough if you could ask for the changes (as some kind of  diff) from the last timestamp you knew of (as in, what the coq interpreter thinks the document is) up to now.

**Comment by rouanth** [comment]
@danr, thank you for an advice, but this is a solution for providing on-demand checks, and I already can validate everything on demand. What I wanted is that which happens in every other editor for Coq (vim with coquille, CoqIDE, emacs with their plugin): the editor reacts instantly if the user edits a sentence that was proven already. One doesn't have to explicitly ask the editor to check again if all proofs are still valid.

**Comment by danr** [comment]
I have used coq with proof general in emacs.

Is not a hook on InsertEnd or NormalBegin enough for this purpose?

**Comment by danr** [comment]
Also relevant: `InsertChar`, `InsertIdle` and `NormalIdle`

**Comment by rouanth** [comment]
One can mess up proofs by deleting or pasting lines, both of which can be done without entering insert mode.

**Comment by rouanth** [comment]
Maybe `NormalIdle` is an answer. I haven't noticed this hook before. I'll see if it suffices, thanks!

**Comment by mawww** [comment]
Yeah, my preferred way is hooking on NormalIdle and checking if `$kak_timestamp` changed, as this will get triggered *after* a set of changes have been made, instead of having a hook triggered in between changes.

**Comment by rouanth** [comment]
`NormalIdle` did the trick, thank you all again! It does feel instantaneous.
What I did was
```
decl -hidden -docstring "Timestamp of the last check" int my_var_last_checked
hook window NormalIdle .* %{
    %sh{
        if [ "${kak_opt_my_var_last_checked}" != "${kak_timestamp}" ]; then
            echo # Do whatever I wanted
        fi
    }
    set current coq_last_checked $val{timestamp}
}
```

**Comment by mawww** [comment]
Nice, I'll close that issue as I think that this is the general way to go whenever somebody wants to act on buffer change: wait for NormalIdle (or InsertIdle eventually) and check the timestamp.
