### ISSUE TITLE
SIGSEGV with non-ascii characters and 's' or 'S'

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#917]
Hi,

If a selection contains characters such as `àéèêô` (I'm extrapolating that to non-ascii characters) and in normal mode you enter `s.*`, kakoune crashes just as you type `*`.

**Comment by lenormf** [comment]
Couldn't reproduce, what's the stacktrace? Is it a release build? Boost version? Commit hash?

**Comment by occivink** [comment]
So I just rebuilt the application and it seems to work properly. I tried various parameters (non-debug build, stripped binaries) and I cannot reproduce the bug. Unfortunately I've overwritten the faulty binary (my bad) so I can't give a stacktrace either. 

It was on cygwin64 with boost 1.60. I'm also sure that it was compiled with the same boost version.

**Comment by lenormf** [comment]
Was the binary built in release mode by any chance? There's been strange bugs happening on cygwin with those lately (#885).

**Comment by occivink** [comment]
Most likely, but I can't answer with certainty. Note that I can't reproduce with a fresh build, even release.
