### ISSUE TITLE
can't build on gentoo

### ISSUE THREAD

**Issue by rpolasek** [mawww/kakoune#920]
using gcc 4.9.3
-------------------
g++ -DKAK_DEBUG -I/usr/include/ncursesw -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .memory.debug.d -c -o .memory.debug.o memory.cc
g++ -DKAK_DEBUG -I/usr/include/ncursesw -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .main.debug.d -c -o .main.debug.o main.cc
In file included from scope.hh:7:0,
                 from buffer.hh:8,
                 from main.cc:2:
option_manager.hh: In instantiation of ‘Kakoune::Option& Kakoune::OptionsRegistry::declare_option(Kakoune::StringView, Kakoune::StringView, const T&, Kakoune::OptionFlags) [with T = Kakoune::EolFormat; void (* validator)(const T&) = 0u]’:
main.cc:221:72:   required from here
option_manager.hh:236:84: error: ambiguous class template instantiation for ‘struct Kakoune::option_type_name<Kakoune::EolFormat, void>’
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
In file included from option_manager.hh:8:0,
                 from scope.hh:7,
                 from buffer.hh:8,
                 from main.cc:2:
option_types.hh:23:8: error: candidates are: struct Kakoune::option_type_name<T, void>
 struct option_type_name<T, void_t<decltype(T::option_type_name)>>
        ^
option_types.hh:29:8: error:                 struct Kakoune::option_type_name<Enum, typename std::enable_if<std::is_enum<_Tp>::value>::type>
 struct option_type_name<Enum, typename std::enable_if<std::is_enum<Enum>::value>::type>
        ^
In file included from scope.hh:7:0,
                 from buffer.hh:8,
                 from main.cc:2:
option_manager.hh:236:84: error: incomplete type ‘Kakoune::option_type_name<Kakoune::EolFormat, void>’ used in nested name specifier
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
option_manager.hh:237:89: error: incomplete type ‘Kakoune::option_type_name<Kakoune::EolFormat, void>’ used in nested name specifier
                                         : format("[{}] - {}", option_type_name<T>::name(), docstring);
                                                                                         ^
option_manager.hh: In instantiation of ‘Kakoune::Option& Kakoune::OptionsRegistry::declare_option(Kakoune::StringView, Kakoune::StringView, const T&, Kakoune::OptionFlags) [with T = Kakoune::ByteOrderMark; void (* validator)(const T&) = 0u]’:
main.cc:223:43:   required from here
option_manager.hh:236:84: error: ambiguous class template instantiation for ‘struct Kakoune::option_type_name<Kakoune::ByteOrderMark, void>’
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
In file included from option_manager.hh:8:0,
                 from scope.hh:7,
                 from buffer.hh:8,
                 from main.cc:2:
option_types.hh:23:8: error: candidates are: struct Kakoune::option_type_name<T, void>
 struct option_type_name<T, void_t<decltype(T::option_type_name)>>
        ^
option_types.hh:29:8: error:                 struct Kakoune::option_type_name<Enum, typename std::enable_if<std::is_enum<_Tp>::value>::type>
 struct option_type_name<Enum, typename std::enable_if<std::is_enum<Enum>::value>::type>
        ^
In file included from scope.hh:7:0,
                 from buffer.hh:8,
                 from main.cc:2:
option_manager.hh:236:84: error: incomplete type ‘Kakoune::option_type_name<Kakoune::ByteOrderMark, void>’ used in nested name specifier
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
option_manager.hh:237:89: error: incomplete type ‘Kakoune::option_type_name<Kakoune::ByteOrderMark, void>’ used in nested name specifier
                                         : format("[{}] - {}", option_type_name<T>::name(), docstring);
                                                                                         ^
option_manager.hh: In instantiation of ‘Kakoune::Option& Kakoune::OptionsRegistry::declare_option(Kakoune::StringView, Kakoune::StringView, const T&, Kakoune::OptionFlags) [with T = Kakoune::AutoInfo; void (* validator)(const T&) = 0u]’:
main.cc:229:59:   required from here
option_manager.hh:236:84: error: ambiguous class template instantiation for ‘struct Kakoune::option_type_name<Kakoune::AutoInfo, void>’
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
In file included from option_manager.hh:8:0,
                 from scope.hh:7,
                 from buffer.hh:8,
                 from main.cc:2:
option_types.hh:23:8: error: candidates are: struct Kakoune::option_type_name<T, void>
 struct option_type_name<T, void_t<decltype(T::option_type_name)>>
        ^
option_types.hh:29:8: error:                 struct Kakoune::option_type_name<Enum, typename std::enable_if<std::is_enum<_Tp>::value>::type>
 struct option_type_name<Enum, typename std::enable_if<std::is_enum<Enum>::value>::type>
        ^
In file included from scope.hh:7:0,
                 from buffer.hh:8,
                 from main.cc:2:
option_manager.hh:236:84: error: incomplete type ‘Kakoune::option_type_name<Kakoune::AutoInfo, void>’ used in nested name specifier
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
option_manager.hh:237:89: error: incomplete type ‘Kakoune::option_type_name<Kakoune::AutoInfo, void>’ used in nested name specifier
                                         : format("[{}] - {}", option_type_name<T>::name(), docstring);
                                                                                         ^
option_manager.hh: In instantiation of ‘Kakoune::Option& Kakoune::OptionsRegistry::declare_option(Kakoune::StringView, Kakoune::StringView, const T&, Kakoune::OptionFlags) [with T = Kakoune::Autoreload; void (* validator)(const T&) = 0u]’:
main.cc:254:39:   required from here
option_manager.hh:236:84: error: ambiguous class template instantiation for ‘struct Kakoune::option_type_name<Kakoune::Autoreload, void>’
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
In file included from option_manager.hh:8:0,
                 from scope.hh:7,
                 from buffer.hh:8,
                 from main.cc:2:
option_types.hh:23:8: error: candidates are: struct Kakoune::option_type_name<T, void>
 struct option_type_name<T, void_t<decltype(T::option_type_name)>>
        ^
option_types.hh:29:8: error:                 struct Kakoune::option_type_name<Enum, typename std::enable_if<std::is_enum<_Tp>::value>::type>
 struct option_type_name<Enum, typename std::enable_if<std::is_enum<Enum>::value>::type>
        ^
In file included from scope.hh:7:0,
                 from buffer.hh:8,
                 from main.cc:2:
option_manager.hh:236:84: error: incomplete type ‘Kakoune::option_type_name<Kakoune::Autoreload, void>’ used in nested name specifier
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
option_manager.hh:237:89: error: incomplete type ‘Kakoune::option_type_name<Kakoune::Autoreload, void>’ used in nested name specifier
                                         : format("[{}] - {}", option_type_name<T>::name(), docstring);
                                                                                         ^
option_manager.hh: In instantiation of ‘Kakoune::Option& Kakoune::OptionsRegistry::declare_option(Kakoune::StringView, Kakoune::StringView, const T&, Kakoune::OptionFlags) [with T = Kakoune::DebugFlags; void (* validator)(const T&) = 0u]’:
main.cc:277:72:   required from here
option_manager.hh:236:84: error: ambiguous class template instantiation for ‘struct Kakoune::option_type_name<Kakoune::DebugFlags, void>’
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
In file included from option_manager.hh:8:0,
                 from scope.hh:7,
                 from buffer.hh:8,
                 from main.cc:2:
option_types.hh:23:8: error: candidates are: struct Kakoune::option_type_name<T, void>
 struct option_type_name<T, void_t<decltype(T::option_type_name)>>
        ^
option_types.hh:29:8: error:                 struct Kakoune::option_type_name<Enum, typename std::enable_if<std::is_enum<_Tp>::value>::type>
 struct option_type_name<Enum, typename std::enable_if<std::is_enum<Enum>::value>::type>
        ^
In file included from scope.hh:7:0,
                 from buffer.hh:8,
                 from main.cc:2:
option_manager.hh:236:84: error: incomplete type ‘Kakoune::option_type_name<Kakoune::DebugFlags, void>’ used in nested name specifier
         String doc =  docstring.empty() ? format("[{}]", option_type_name<T>::name())
                                                                                    ^
option_manager.hh:237:89: error: incomplete type ‘Kakoune::option_type_name<Kakoune::DebugFlags, void>’ used in nested name specifier
                                         : format("[{}] - {}", option_type_name<T>::name(), docstring);
                                                                                         ^
Makefile:76: recipe for target '.main.debug.o' failed
make: *** [.main.debug.o] Error 1

**Comment by lenormf** [comment]
As per the `README` file of the project, you need `gcc>=5` or `clang>=3.4` to compile.

**Comment by rpolasek** [comment]
i'm sorry i've overlooked it

**Comment by lenormf** [comment]
Sure. Could you close the issue please?
