### ISSUE TITLE
Different regex behaviour

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#921]
In a file with empty lines,
`%s^$<ret>`
and
`%<a-s><a-k>^$<ret>`
should end up selecting the same text but they don't.

**Comment by occivink** [comment]
I think regex with results of size 0 is kind of a strange case (what should be selected, the first character after?), but I would say that the second behavior is the correct one.

**Comment by kurkale6ka** [comment]
The first behaviour is correct actually.
`^$` is a pretty standard way of selecting empty lines. Works in Vim, awk, grep...

**Comment by casimir** [comment]
Is it themsame on HEAD? The first one end up with a "nothing selected" error and the selection stays the same as `%`.

**Comment by kurkale6ka** [comment]
You have to use it on a file with empty lines @casimir

**Comment by casimir** [comment]
Right, forget what I said.

**Comment by lenormf** [comment]
I don't think it helped unfortunately, the `<a-k>` test case still won't select empty lines.

**Comment by mawww** [comment]
Yeah, for some still unknown reason the regex engine finds a match for ^$ at the end of the line (just after the \n) on every line, which does not make sense as we set the match_not_eol flag.

**Comment by mawww** [comment]
So, I found one bug, but it does not totally fix the use case:
```
non-empty\n
non-empty\n

```

If you do `%<a-s><a-k>^$<ret>`, you'll end up with the 2 last lines kept, because the second non empty line does match `^$` at its end (just after its \n, we have the next like \n).
