### ISSUE TITLE
Custom regex objects

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#925]
It'd be useful in many situations, such as xml tags for instance:
`:map global object t '<([^>]+)>,</\1>'`

**Comment by mawww** [comment]
Ok, I remember why we dont use regex, but plain strings for custom objects: We cannot efficiently search backward for a regex.

We could mitigate that by searching lines by lines in reverse order though.

**Comment by lenormf** [comment]
Bump.

**Comment by occivink** [comment]
Could this now be implemented?

**Comment by mawww** [comment]
Yep, this can be implemented now, but needs a bit of refactoring.
