### ISSUE TITLE
tag issues

### ISSUE THREAD

**Issue by kurkale6ka** [mawww/kakoune#928]
I can't use `:tag` after the latest update to `ctags.kak`:
```
 1 *** This is the debug buffer, where debug info will be written ***
 2 shell stderr: <<<
 3 awk: syntax error at source line 10
 4  context is
 5     D { print length(out) >>>  == <<<  0 ? "echo -color Error no such tag " ENVIRON["tagname"] : "menu -markup -auto-single " out }
 6 awk: illegal statement at source line 10
 7 /bin/sh: line 7: printf: write error: Broken pipe
 8 /bin/sh: line 7: printf: write error: Broken pipe
 9 >>>
10
```

**Comment by mawww** [comment]
What version of awk are you using ?

**Comment by kurkale6ka** [comment]
`awk version 20070501`. Do I need to `brew install gawk`?

**Comment by mawww** [comment]
You should not need it, its pretty strange you get this as i dont think that line changed.

**Comment by lenormf** [comment]
The comment on the commit mentioned that this happened when looking up a specific tag (with multiple colons), is that the case, or will this error occur with any tag?

**Comment by mawww** [comment]
Does wrapping print arguments in ( ... ) helps ?
