### ISSUE TITLE
Handle "hidden" directories when using the file completion in prompts

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#929]
Hi,

I noticed that completion suggestions listed when e.g. picking a file for editing from the prompt do not show dot files. Could this be fixed, or activated using an option?

Thanks.

**Comment by mawww** [comment]
That already works, as soon as you write the prefix dot you should seehidden files proposed as candidates.

**Comment by lenormf** [comment]
The fuzzy matching ignores dot files completely, e.g. when trying to open a file in `$XDG_CONFIG_HOME`:

```
cd ~
kak
:e config
```

**Comment by mawww** [comment]
Yeah, the `ignored_files` regex option prevents .config to be showed, but as soon as the text you enter matches `ignored_files`, they will start being considered as candidates.

```
cd ~
kak
:e .c
```

**Comment by lenormf** [comment]
I hadn't realised this option existed/was documented.

**Comment by lenormf** [comment]
Actually even when I empty this variable, I still do not get a list of all the files in the current working directory.
