### ISSUE TITLE
implement on top of emacs?

### ISSUE THREAD

**Issue by wbolster** [mawww/kakoune#955]
this is more of a question than an actual issue, but i was wondering whether you have considered to build kakoune on top of emacs, just like evil-mode implements (a better imho) vim on top of emacs.

it would mean that a lot of the plumbing would be in place already, but of course it may also pose some challenges even though emacs itself is very hackable.

anyway, interesting project.

**Comment by lenormf** [comment]
Maybe you could have a headless kakoune server running, and you could implement hooks in `emacs` that send info over through the json-rpc protocol? I'm speculating, maybe it's not possible at the moment.

**Comment by casimir** [comment]
I guess the this the same use case as evil-mode, so the better way would be te reimplement a minor mode handling selection and actions.

**Comment by wbolster** [comment]
yeah, this project is like evil-mode in that it implements a modal editing layer, but evil relies on existing emacs functionality for i/o, processes, window management, completion, syntax highlighting, and much more, so it can just focus on the modal ui.

**Comment by casimir** [comment]
Do you mean like kakoune would be a client for an emacs server?

**Comment by wbolster** [comment]
no, i was just wondering whether this project had considered implementing the ui on top of an extensible editor core such as emacs, instead of reimplementing all the complex stuff again. this is the approach that evil-mode took, and i am very about it, so i was just wondering whether it had been under consideration, since, you know (better than i do), implementing an editor is hard. ;)

**Comment by doppioandante** [comment]
Kakoune is designed to work inside UNIX and to use tools like grep, awk, etc.
An Emacs implementation wouldn't make much sense unless it were re-thought to fit inside Emacs instead of inside a POSIX environment.
I don't see this as a goal of the project, but anyone is free to try of course, an obvious advantage would be windows compatibility and lisp scriptability.

**Comment by lenormf** [comment]
@doppioandante see this more as `emacs` being a frontend to `kak`, as far as I can tell.

**Comment by doppioandante** [comment]
@lenormf that's a possibility of course but I don't see much sense in it frankly.

**Comment by wbolster** [comment]
just to make myself clear, this ticket is just for having a
conversation, and not intended in any way to change the course of
this project. and it is not intended as trolling either.

when reading the feature list, the topmost items are about th
modal ui approach, such as multiple selections as a central way
of interacting, selection manipulation primitives, text objects,
text manipulation primitives.

other features seem more generic: interaction with external
programs, completion, hooks, and syntax highlighting.

this is when i realised there is a similarity with how evil-mode
implements a modal editor (specifically, a vim clone) by building
on top of emacs, which provides the core editor features that are
not directly related to the modal interaction approach.

also, no need for the thumbs down reaction, @trevorriles, this is
an honest inquiry from my side about the technical choices made
by this very interesting project.

**Comment by casimir** [comment]
@wbolster while the idea is quite interesting, the bug tracker is usually used to report errors and track their solutions, I bet you'll we have a broader discussion on IRC it would be nice if you could join #kakoune on Freenode.

**Comment by doppioandante** [comment]
@wbolster your logic is sound, there's an advantage to use POSIX as a base instead of Emacs though, and this is that POSIX is actually standardized.
Speaking from personal experience, when I first got into kakoune the big shift was not the particular type of editing but the fact that you need to learn unix tools to use kakoune effectively.
Most notably, kakoune doesn't have a classical extension system like Emacs or Vim, the .kak files are really just editor commands the spawn various external posix or external utilities that do the job and talk back to kakoune.

**Comment by mawww** [comment]
Hello @wbolster,

There was never any plans to implement Kakoune on top of Emacs. When Kakoune started as a project, around 5 years ago, I was looking to learn more about C++11, so implementing on top of Emacs would not worked. I was as well a big vim user, and rarely worked on machines where Emacs was available, so I never really thought about doing that.

The project would be quite different nowadays if that has been the case, and would likely not rely as much on POSIX tools as it does now.

I'd be happy to see Kakoune emulation, or Kakoune inspired extensions appear for Emacs, it would be a pretty good sign that Kakoune interaction model is getting some tractions, but I have no plans to work on that.

Cheers,

Maxime.

**Comment by jmorag** [comment]
Pretty late to the party, but I've taken a stab at implementing very basic emulation. It's nowhere near as comprehensive as evil-mode is for vim, but it's a start.
[kakoune.el](https://github.com/jmorag/kakoune.el)

**Comment by osor-io** [comment]
That would be amazing @jmorag !

If that gives me the option to have it everywhere, even in a windows environment and rely that I can get used to that style of editing without the worry of going to a platform that doesn't have it that would be a game changer for me.

Thanks a lot for your work! 😊
