### ISSUE TITLE
download for windows

### ISSUE THREAD

**Issue by anjanb** [mawww/kakoune#956]
hi there,

  wondering if there's a windows binary available for installation ?

if not, what are the plans ?

thank you.

BR,
~A

**Comment by joereynolds** [comment]
Section 2.1 of the README states

> Kakoune can be built on Linux, MacOS, and Cygwin. Due to Kakoune relying heavily on being in a Unix-like environment, no native Windows version is planned.

So it's probably not going to happen.

**Comment by casimir** [comment]
Some user use it daily under Cygwin and it was reported to work on WSL.

**Comment by lenormf** [comment]
Extract of the FAQ, that you can read using the `:doc faq` command:

> Is there going to be a Windows port of Kakoune ?
> 
> As many features provided by UNIX systems would be missing, or if anything much less efficient on a Windows system, the incentive to porting the project to this operating system is pretty low.
> 
> Moreover, you can get pretty decent performance by using Kakoune on Cygwin (which is officially supported).
