### ISSUE TITLE
Add delete to beginning / delete to end shortcuts in prompt

### ISSUE THREAD

**Issue by dlee** [mawww/kakoune#958]
I was unable to find a way to delete to the beginning of the line or to the end of the line in the prompt.

**Comment by occivink** [comment]
You're looking for `<a-h>` to select to the beginning of the line, and `<a-l>` to the end. Follow that with `d` to delete the selection.

**Comment by dlee** [comment]
@occivink Those shortcuts do not work in the prompt. `alt-h` moves the cursor left one character, and `alt-l` moves the cursor right one character.

**Comment by occivink** [comment]
Right my bad, I missed the prompt part.

**Comment by doppioandante** [comment]
A lot of these are being implemented in #800, but it has not been merged yet.

**Comment by dlee** [comment]
@doppioandante Thanks, I just left a comment there. I'll close this in favor of that PR.
