### ISSUE TITLE
Literal insertion (c-v) does not work for all keycodes

### ISSUE THREAD

**Issue by dlee** [mawww/kakoune#960]
I cannot insert `<c-c>`, `<esc>`, or any `<a-*>` keycodes using the literal insertion command `<c-v>`.

**Comment by lenormf** [comment]
This probably has to do with the way all of those are implemented:

* `<c-c>` is a signal, and it's used to kill background jobs (like a big completion job from the prompt, e.g. `:man <tab>`)
* `<a-*>` are keys with a modifier, they don't refer to any symbol that could be inserted
* `<esc>` should be implemented I reckon, yes

**Comment by mawww** [comment]
Thats a pretty good explanation, I'd think both `<c-c>` and `<esc>`, which have a well defined codepoint associated with them, should work. `<a-*>` cant really, there is no codepoint associated with them, we could insert the `*` part, but thats as arbitrary as not inserting anything.

**Comment by lenormf** [comment]
I think this issue can be closed.
