### ISSUE TITLE
Homebrew formula needs to set XML_CATALOG_FILES

### ISSUE THREAD

**Issue by kballard** [mawww/kakoune#963]
When installing on macOS using the Homebrew instructions, the install fails. The formula depends on docbook and asciidoc, but it doesn't set the `XML_CONFIG_FILES` environment variable, so it fails to work properly. Looking at other formulae that use docbook and asciidoc, they either pass something like `--with-xml-catalog=#{etc}/xml/catalog` to their `configure` script, or they set `ENV["XML_CATALOG_FILES"] = etc/"xml/catalog"`.

**Comment by doppioandante** [comment]
Yes, dup of #954.
If you want feel free to make a PR for this.

**Comment by mawww** [comment]
Should be fixed now.
