### ISSUE TITLE
Unable to map control keys

### ISSUE THREAD

**Issue by TheDerkus** [mawww/kakoune#970]
Running the command `map global normal ^K :` (where `^K` is inserted literally, by typing control-v followed by control-k) does not raise an error, but has no effect.

Running the same command, but typing Enter instead of control-k, causes a strange box character to appear instead of the expected `^M`. The command throws an error `1:1: 'map' wrong argument count`

I was unable to find any help in the docs regarding mapping control characters and other such keys. If this is possible, how might I do it?

**Comment by lenormf** [comment]
`map global normal <c-k> ihello` works for me, the `^X` syntax has to be converted into `<c-x>`.

**Comment by TheDerkus** [comment]
Strangely, using that method, I am able to map <c-k> and <c-x> successfully, but not <c-m>.

**Comment by mawww** [comment]
This is due to terminal input, <c-m> and <ret> generate the same input, <c-i> and <tab> as well. No easy fix for that, we could migrate to @leonerd's input system, but that would basically mean getting rid of ncurses, at least for input handling.

**Comment by leonerd** [comment]
@mawww You could become one of the early adopters of `libtickit` instead. It should provide you a superset of ncurses' features.

Currently sitting at an RC1 prerelease, but I'm hoping to call that a real 0.1 any day now:
http://www.leonerd.org.uk/code/libtickit/

**Comment by lenormf** [comment]
If we're going to remove `ncurses`, I'd rather it's replaced by something that supports True Color.

**Comment by mawww** [comment]
@leonerd is there a page that lists terminal emulators supporting the input model you proposed ?

**Comment by leonerd** [comment]
@lenormf Ahyes; I don't yet have truecolour support in libtickit, but adding is probably a couple of hours work at most. If you consider that your only blocker that should be easy enough to fix.

**Comment by lenormf** [comment]
I created issue #1012 to discuss an eventual change, to keep this one clean.

**Comment by mawww** [comment]
`<c-m>` and `<c-i>` are a general terminal input issue, closing this.
