### ISSUE TITLE
Website only has WebM videos

### ISSUE THREAD

**Issue by kballard** [mawww/kakoune#973]
All of the videos on the website are WebM, which isn't supported by all browsers (notably, Safari doesn't support it). This means the website has a bunch of broken videos scattered around.

**Comment by pho** [comment]
[asciinema](https://asciinema.org/) would be a nice alternative for this use case

**Comment by lenormf** [comment]
I guess we could re-encode the videos with `x264` and have an imgur-type format selection, but at the time we decided that enough browsers could read webm so we didn't bother.

The alternative is also asciinema, but I don't like centralizing documentation resources (can we export asciinema sequences to a video, to back them up?).

**Comment by pho** [comment]
Asciinema has a standalone player which could be embedded statically on the web, if thats what you were worried about: https://github.com/asciinema/asciinema-player

Although after a second thought, the work required to redo every example in asciinema is quite a lot, compared to reencoding and setting multiple sources on the <video>...

**Comment by kballard** [comment]
What do you mean by "imgur-type format selection"? All you need is 2 `<source>` tags inside your `<video>` tag and the browser will pick whichever one it supports.

**Comment by lenormf** [comment]
Imgur as a `gifv` filetype that does exactly what you described.

**Comment by mawww** [comment]
Thats now fixed.

**Comment by kballard** [comment]
The videos are still broken. I see you have .mp4 files now, but neither Safari nor QuickTime Player can play them (though Chrome can). Unfortunately, I'm not sure why it can't, but the problem is likely due to the mp4 profile or level.

**Comment by lenormf** [comment]
Indeed, the videos were encoded with the `High` profile instead of the `Baseline` one. I'll fix it if someone opens an issue.

**Comment by kballard** [comment]
Filed as #1178.

**Comment by lenormf** [comment]
Thanks!
