### ISSUE TITLE
for syntax higlighting

### ISSUE THREAD

**Issue by oroulet** [mawww/kakoune#975]
I am currently looking at kakoune, syntax highligting works for some python files but not others. I haven't managed to figure out why. But in the meantime how do I set a specific language?

**Comment by pauldub** [comment]
You can set the `filetype` option for a buffer using `:set buffer filetype python`. This is done by the python rc file here: https://github.com/mawww/kakoune/blob/master/rc/core/python.kak#L8,L12

**Comment by lenormf** [comment]
`set buffer filetype python`

What  python files are not detected as such ? What does `:echo %opt{filetype}` return? Do you have code in another language embedded in the python file?

File type detection is being reworked, you shouldn't have any issues in the future, when the changes are merged.

You can also read the documentation using the `:doc` command, i.e. `:doc options filetype`.

**Comment by oroulet** [comment]
that works thanks. looks like there is a file type detection bug

**Comment by oroulet** [comment]
leaving open as there is really a bug

**Comment by oroulet** [comment]
it says cpp. there is absolutely no cpp in that file

**Comment by oroulet** [comment]
the files starts with import logging at the first line

**Comment by casimir** [comment]
This is due to the mime-type inference see #878 #949. This is annoying but we couldn't agree on a design yet.

As a workaround you can put `hook global BufCreate .+\.cpp %{ set buffer filetype cpp }` until this is fixed.
