### ISSUE TITLE
split?

### ISSUE THREAD

**Issue by oroulet** [mawww/kakoune#976]
I see that split is not implemented by design. How are we supposed to split current window or edit several files?

**Comment by lenormf** [comment]
You can use the `new` command which will create a new client in an X11 window, or a `tmux` pane if possible.

**Comment by oroulet** [comment]
thanks, we should add that to wiki. I can do it when I get the feeling that I undestand

**Comment by lenormf** [comment]
We limit wiki entries to failry non-trivial things, the `new` command is well documented.

**Comment by oroulet** [comment]
then maybe in the migrating from vim guide?

**Comment by lenormf** [comment]
The wiki is open for editing to anybody, so it's up to you, but keep in mind that we don't want the wiki to be  a copy of the documentation with different explanations/examples.

**Comment by mawww** [comment]
We have a Migrating From Vim page there, so could make sense to have a quick recap of window management in that page.

**Comment by mawww** [comment]
Closing that issue, as its not something that'll change in Kakoune, feel free to add some info on Kakoune's window management in https://github.com/mawww/kakoune/wiki/Migrating-from-Vim
