### ISSUE TITLE
Update the `homebrew` recipe for the project

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#977]
Hi,

As mentioned in #974, the upstream recipe for the project is outdated. Some major changes have been done since [the last PR](https://github.com/Homebrew/homebrew-head-only/pull/40), and it's causing mac users some trouble.

**Comment by mawww** [comment]
I dont think that is relevant anymore.

**Comment by lenormf** [comment]
Actually the recipe that is made available to users in the legacy repository is still way out of date, I just made [a pull request](https://github.com/Homebrew/homebrew-boneyard/pull/273) to fix that.
