### ISSUE TITLE
Autodetecting javascript filetype doesn't work

### ISSUE THREAD

**Issue by umurgdk** [mawww/kakoune#979]
First of all, thanks for bringing many great ideas to the text editor area. I'm hoping kakoune will get much bigger community support in the future.

Right now if i open a javascript file (something.js) it doesn't understand the filetype and syntax highlighting doesn't work (i think it sees as cpp) after i run ":set buffer filetype javascript" it works as expected. I checked the .kak file for javascript and there is pattern matching for javascript file extension but have no idea why it doesn't work

**Comment by lenormf** [comment]
This issue stems from the `file` utility mis-detecting the mimetype of the file, which is then used as reference to activate highlighting.

C.f. #975.
