### ISSUE TITLE
How to scroll in context help

### ISSUE THREAD

**Issue by sanbor** [mawww/kakoune#983]
When I press `:` I get a long list of suggestion and something that looks like an scrollbar. I tried to scroll with different keys and mouse but couldn't find how. I also looked in the man page, the readme of this repo and issues but I couldn't find any information.

Here is an screenshot:

![image](https://cloud.githubusercontent.com/assets/51512/21189502/abb1037a-c1fd-11e6-834d-74a5a5617bdb.png)

**Comment by mawww** [comment]
You cannot manually scroll that, but by using <tab> you can select the next completion, and once you get past the last one you'll get a new page. that scroll bar is just a visual indicator of the current page.

**Comment by sanbor** [comment]
> You cannot manually scroll that, but by using you can select the next completion, and once you get past the last one you'll get a new page

Sorry but I didn't get that. By using what?

**Comment by Delapouite** [comment]
A word is missing indeed. I guess mawww is talking about the Tab key.

**Comment by lenormf** [comment]
`<tab>` and `<c-n>` are used to cycle through completion candidates or menu items.

**Comment by mawww** [comment]
Yeah, sorry, if I dont quote `<tab>` in monospace font, it just disappear of the rendered text, probably interpretted as an html tag.

**Comment by sanbor** [comment]
Thank you, I tried it out and it works. I think this should be improve somehow.

The [design document](https://github.com/mawww/kakoune/blob/master/doc/design.asciidoc) says
> provides the discoverability which is often lacking in non GUI tools

I was excited about this but when playing with it I couldn't iterate over the list of suggestions.

Maybe kakoune could implement `<c-n>`/`<c-p>` to go thought the list and/or add a legend "`<tab>` to select the next candidate".

Thanks for your help!

**Comment by lenormf** [comment]
Quoting [my own message](https://github.com/mawww/kakoune/issues/983#issuecomment-267349691):
>`<tab>` and `<c-n>` are used to cycle through completion candidates or menu items.

Do you mean to say that `<c-n>` and `<c-p>` don't work on your terminal? Those two bindings are implemented, can you tell me what terminal you're using (I suppose those two bindings are intercepted by it)?

**Comment by sanbor** [comment]
@lenormf `<c-n>` works fine in my terminal. Looks like Kakoune only uses `<Tab>` and `<Shift-Tab>` to cycle through completion candidates.

Just open Kakoune, press `:` and try to go through the suggestions using `<c-n>`.

I'm suggesting than having some shortcut to scroll the list would be useful for discoverability, instead of pressing 30 times `<Tab>`.

**Comment by lenormf** [comment]
OK, your comment looked like nothing was allowing you to cycle through suggestions.

I agree that it would be nice to have a shorter to go through the list faster, as sometimes there are many candidates in the list and finding out what to type to have the fuzzy matching algorithm bring the candidate we want within `<tab>` range requires more effort/time than going through the list to select the item we want directly.

**Comment by Delapouite** [comment]
> Maybe kakoune could implement `<c-n>/<c-p>` to go thought the list and/or add a legend "`<tab>` to select the next candidate".
> Just open Kakoune, press : and try to go through the suggestions using `<c-n>`.

There are 2 scenarios:
- when you are in **insert mode**, an autocompletion menu may appear right next to your cursor, displaying suggestions. In this case `<c-n>` and `<c-p>` have the same effect than `<tab>` and `<backtab>`:

https://github.com/mawww/kakoune/blob/master/src/input_handler.cc#L589

```cpp
        else if (key == Key::Down or key == Key::Tab or
                 key == ctrl('n') or (not m_edit_filter and key == 'j'))
        {
            auto it = std::find_if(m_selected+1, m_choices.end(), match_filter);
            if (it == m_choices.end())
                it = std::find_if(m_choices.begin(), m_selected, match_filter);
            select(it);
        }
        else if (key == Key::Up or key == Key::BackTab or
                 key == ctrl('p') or (not m_edit_filter and key == 'k'))
        {
            ChoiceList::const_reverse_iterator selected(m_selected+1);
            auto it = std::find_if(selected+1, m_choices.rend(), match_filter);
            if (it == m_choices.rend())
                it = std::find_if(m_choices.rbegin(), selected, match_filter);
            select(it.base()-1);
        }
```

- when you press `:`, you enter the **prompt** mode. In this case `<c-n>` / `<c-p>` actions (move in history) are different than `<tab>` and `<backtab>`: 

https://github.com/mawww/kakoune/blob/master/src/input_handler.cc#L775-L854

```cpp
       else if (key == Key::Up or key == ctrl('p'))
        {
            if (m_history_it != history.begin())
            {
                if (m_history_it == history.end())
                   m_prefix = line;
                auto it = m_history_it;
                // search for the previous history entry matching typed prefix
                do
                {
                    --it;
                    if (prefix_match(*it, m_prefix))
                    {
                        m_history_it = it;
                        m_line_editor.reset(*it);
                        break;
                    }
                } while (it != history.begin());

                clear_completions();
                m_refresh_completion_pending = true;
            }
        }
        else if (key == Key::Down or key == ctrl('n')) // next
        {
            if (m_history_it != history.end())
            {
                // search for the next history entry matching typed prefix
                ++m_history_it;
                while (m_history_it != history.end() and
                       not prefix_match(*m_history_it, m_prefix))
                    ++m_history_it;

                if (m_history_it != history.end())
                    m_line_editor.reset(*m_history_it);
                else
                    m_line_editor.reset(m_prefix);

                clear_completions();
                m_refresh_completion_pending = true;
            }
        }
        else if (key == Key::Tab or key == Key::BackTab) // tab completion
        {
            const bool reverse = (key == Key::BackTab);
            CandidateList& candidates = m_completions.candidates;
            // first try, we need to ask our completer for completions
            if (candidates.empty())
            {
                refresh_completions(CompletionFlags::None);
                if ((not m_prefix_in_completions and candidates.size() > 1) or
                    candidates.size() > 2)
                    return;
            }

            if (candidates.empty())
                return;

            if (not reverse and ++m_current_completion >= candidates.size())
                m_current_completion = 0;
            else if (reverse and --m_current_completion < 0)
                m_current_completion = candidates.size()-1;

            const String& completion = candidates[m_current_completion];
            if (context().has_client())
                context().client().menu_select(m_current_completion);

            m_line_editor.insert_from(line.char_count_to(m_completions.start),
                                      completion);

            // when we have only one completion candidate, make next tab complete
            // from the new content.
            if (candidates.size() == 1 or
                (m_prefix_in_completions and candidates.size() == 2))
            {
                m_current_completion = -1;
                candidates.clear();
                m_refresh_completion_pending = true;
            }
        }
```
