### ISSUE TITLE
Support for bright terminal colors

### ISSUE THREAD

**Issue by nonphoto** [mawww/kakoune#988]
I prefer to have my editor match my terminal color scheme. In Kakoune, you can define faces by name (e.g. "black", "red", "green"), but there are no valid strings for the corresponding "bright" colors. It would make sense to allow color assignment with integer values 0-255 like Vim does.

**Comment by ekie** [comment]
https://github.com/mawww/kakoune#7-faces

fg_color and bg_color can be:

A named color: black, red, green, yellow, blue, magenta, cyan, white.

default, which keeps the existing color

An rgb color: rgb:RRGGBB, with RRGGBB the hexadecimal value of the color.

**Comment by mawww** [comment]
'bright' and 'bold' are the same thing AFAIK, so that would be 'red+b' for bold/bright red

**Comment by kballard** [comment]
Bright and Bold are not the same thing. Many terminals render bold text using bright colors, but it's not required (Terminal.app has a setting for this). Using xterm escapes, the normal colors are `\e[30m` through `\e[37m`, and the bold colors are `\e[90m` through `\e[97m`. You can experiment yourself by using `tput setaf` with the color number after it to emit the escape. Colors 0-7 are the normal set, and 8-15 are the bright set.

**Comment by mawww** [comment]
Yeah, I got confused with the bold attribute, which is sometimes rendered bright,

We could make it so the 8-15 colors are accessible, but one goal in the face design is to be not too tied with the terminal implementation, the ncurses ui is pretty isolated in Kakoune codebase, and we can have alternatives UIs.

So, I dont really like the idea of exposing the xterm 256 color palette as index colors, but I am on the fence for the 8-15 set, as I can see the appeal of setting a colorscheme at the terminal emulator level, and then using the 16 color palette from there.

A possibility would be a bright attribute on faces side, that ncurses would interpret, but once you get to rgb colors, bright does not make much sense (that said we have dim already, which does not make more sense).

**Comment by nonphoto** [comment]
Why not add more named colors by prefixing them with "bright"? Then you would have "bright-black", "bright-red", "bright-green", colors and so on. This is the typical naming scheme for colors 0-15.

**Comment by mawww** [comment]
Its another possibility, but it feels very tied to terminals, I am not strongly against it though.

**Comment by kballard** [comment]
I think @nonphoto's suggestion makes the most sense. The available colors right now are based on the normal terminal set. Adding a second set of "bright" colors doesn't make it any more dependent on terminal semantics than it was before.

**Comment by nicholastmosher** [comment]
What about creating a script to set face colors based on a [`.Xresources`](https://wiki.archlinux.org/index.php/X_resources#Xresources_syntax) file? It could quickly check for properties like `kakoune.Colorscheme.PrimaryCursor` etc.

It may or may not be possible based on whether faces can be overridden or undefined then redefined, but that way users could define the colors of their terminal (at least if they're using xterm) and their kakoune colorscheme in the same place.

**Comment by kballard** [comment]
@nicholastmosher That seems rather orthogonal to this issue. You can certainly create such a script, but the presence or absence of the script doesn't affect the issue of whether Kakoune should support bright terminal colors.
