### ISSUE TITLE
alt-a : behaves badly when using , as delimiter

### ISSUE THREAD

**Issue by kballard** [mawww/kakoune#992]
It looks like `alt-a :` doesn't work properly when trying to use `,` as a delimiter. Here's a list of behaviors I've seen:

input | behavior
----------|--------
`,` | error, `expected <open>,<close>`. Seems reasonable.
`,,` | selection changes to covering 3 characters centered on the cursor. This makes no sense. Except if the cursor is on the first character in the buffer, then Kakoune crashes instead. Filed as #993.
`,,,` | error, `expected <open>,<close>`. I expected this to parse `<open>` and `<close>` as `,`
`.,` | error, `expected <open>, <close>`. Seems reasonable.
`,.` | if there exists a `.` anywhere after the cursor, Kakoune enters an infinite loop sucking up 100% CPU until it's killed (and ^C is eaten so it has to be killed externally). Filed as #994.

**Comment by mawww** [comment]
Hello, commas should be escaped with `\` if they are not intended as a separator. Crashes should be fixed now.

**Comment by kballard** [comment]
What about the behavior with `,,`? That part is really weird. If I'm supposed to escape the commas, then I'd expect `,,` to give me the same error `expected <open>,<close>` that I get from other inputs.

**Comment by kballard** [comment]
Ah, you did actually fix that case too. 👍
